Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::aggregator_operation Class Reference
tbb::interface6::aggregator_operation Class Reference
#include <aggregator.h>
Public Types
enum aggregator_operation_status { agg_waiting =0, agg_finished }
Public Member Functions
aggregator_operation ()
void start ()
Call start before handling this operation.
void finish ()
Call finish when done handling this operation.
aggregator_operation * next ()
void set_next (aggregator_operation *n)
Private Attributes
uintptr_t status
aggregator_operation * my_next
Friends
template<typename handler_type >
class aggregator_ext
Detailed Description
Definition at line 36 of file aggregator.h.
Member Enumeration Documentation
enum tbb::interface6::aggregator_operation::aggregator_operation_status
Enumerator
agg_waiting
agg_finished
Definition at line 41 of file aggregator.h.
 { agg_waiting=0, agg_finished };
Constructor & Destructor Documentation
tbb::interface6::aggregator_operation::aggregator_operation () inline
Definition at line 42 of file aggregator.h.
 : status(agg_waiting), my_next(NULL) {}
Member Function Documentation
void tbb::interface6::aggregator_operation::finish () inline
Call finish when done handling this operation.
The operation will be released to its originating thread, and possibly deleted.
Definition at line 47 of file aggregator.h.
References tbb::internal::itt_store_word_with_release().
Referenced by tbb::interface6::internal::basic_handler::operator()().
 { itt_store_word_with_release(status, uintptr_t(agg_finished)); }
aggregator_operation* tbb::interface6::aggregator_operation::next () inline
Definition at line 48 of file aggregator.h.
References tbb::internal::itt_hide_load_word().
Referenced by tbb::interface6::internal::basic_handler::operator()().
 { return itt_hide_load_word(my_next);}
void tbb::interface6::aggregator_operation::set_next (aggregator_operation * n) inline
Definition at line 49 of file aggregator.h.
References tbb::internal::itt_hide_store_word().
 { itt_hide_store_word(my_next, n); }
void tbb::interface6::aggregator_operation::start () inline
Call start before handling this operation.
Definition at line 44 of file aggregator.h.
References tbb::internal::acquired, and tbb::internal::call_itt_notify().
Referenced by tbb::interface6::internal::basic_handler::operator()().
 { call_itt_notify(acquired, &status); }
Friends And Related Function Documentation
template<typename handler_type > friend class aggregator_ext friend
Definition at line 37 of file aggregator.h.
Member Data Documentation
aggregator_operation* tbb::interface6::aggregator_operation::my_next private
Definition at line 39 of file aggregator.h.
Referenced by tbb::interface6::aggregator_ext< internal::basic_handler >::execute_impl().
uintptr_t tbb::interface6::aggregator_operation::status private
Definition at line 38 of file aggregator.h.
Referenced by tbb::interface6::aggregator_ext< internal::basic_handler >::execute_impl().
The documentation for this class was generated from the following file:
aggregator.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.