Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::allowed_parallelism_control Class Reference
tbb::internal::allowed_parallelism_control Class Reference
Public Member Functions
size_t active_value_if_present () const
Private Member Functions
virtual size_t default_value () const __TBB_override
virtual bool is_first_arg_preferred (size_t a, size_t b) const __TBB_override
virtual void apply_active () const __TBB_override
virtual size_t active_value () const __TBB_override
Additional Inherited Members
Public Attributes inherited from tbb::internal::padded_base< control_storage, NFS_MaxLineSize, sizeof(control_storage)%NFS_MaxLineSize >
char pad [S-R]
Protected Attributes inherited from tbb::internal::control_storage
size_t my_active_value
atomic< global_control * > my_head
spin_mutex my_list_mutex
Detailed Description
Definition at line 446 of file tbb_main.cpp.
Member Function Documentation
virtual size_t tbb::internal::allowed_parallelism_control::active_value () const inline private virtual
Reimplemented from tbb::internal::control_storage.
Definition at line 458 of file tbb_main.cpp.
References tbb::internal::market::max_num_workers(), and tbb::internal::min().
{
 /* Reading of my_active_value is not synchronized with possible updating
    of my_head by other thread. It's ok, as value of my_active_value became
    not invalid, just obsolete. */
         if (!my_head)
             return default_value();
         // non-zero, if market is active
         const size_t workers = market::max_num_workers();
         // We can't exceed market's maximal number of workers.
         // +1 to take master into account
         return workers? min(workers+1, my_active_value): my_active_value;
     }
size_t tbb::internal::allowed_parallelism_control::active_value_if_present () const inline
Definition at line 471 of file tbb_main.cpp.
Referenced by tbb::internal::market::app_parallelism_limit().
{
         return my_head? my_active_value : 0;
     }
virtual void tbb::internal::allowed_parallelism_control::apply_active () const inline private virtual
Reimplemented from tbb::internal::control_storage.
Definition at line 453 of file tbb_main.cpp.
References __TBB_ASSERT, and tbb::internal::market::set_active_num_workers().
{
         __TBB_ASSERT( my_active_value>=1, NULL );
         // -1 to take master into account
         market::set_active_num_workers( my_active_value-1 );
     }
virtual size_t tbb::internal::allowed_parallelism_control::default_value () const inline private virtual
Implements tbb::internal::control_storage.
Definition at line 447 of file tbb_main.cpp.
References tbb::internal::governor::default_num_threads(), and tbb::internal::max().
{
         return max(1U, governor::default_num_threads());
     }
virtual bool tbb::internal::allowed_parallelism_control::is_first_arg_preferred (size_t a, size_t b) const inline private virtual
Reimplemented from tbb::internal::control_storage.
Definition at line 450 of file tbb_main.cpp.
{
         return a<b; // prefer min allowed parallelism
     }
The documentation for this class was generated from the following file:
tbb_main.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.