Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::atomic_impl< T > Struct Template Reference
tbb::internal::atomic_impl< T > Struct Template Reference
Base class that provides basic functionality for atomic<T> without fetch_and_add.
#include <atomic.h>
Classes
union converter
Union type used to convert type T to underlying integral type.
union ptr_converter
union ptr_converter< value_t * >
Public Types
typedef T value_type
Public Member Functions
atomic_impl ()=default
constexpr atomic_impl (value_type value)
template<memory_semantics M>
value_type fetch_and_store (value_type value)
value_type fetch_and_store (value_type value)
template<memory_semantics M>
value_type compare_and_swap (value_type value, value_type comparand)
value_type compare_and_swap (value_type value, value_type comparand)
operator value_type () const volatile
template<memory_semantics M>
value_type load () const
value_type load () const
template<memory_semantics M>
void store (value_type value)
void store (value_type value)
Protected Member Functions
value_type store_with_release (value_type rhs)
Protected Attributes
aligned_storage< T, sizeof(T)> my_storage
Static Private Member Functions
template<typename value_t >
static converter< value_t >::bits_type to_bits (value_t value)
template<typename value_t >
static value_t to_value (typename converter< value_t >::bits_type bits)
template<typename value_t >
static converter< value_t >::bits_type & to_bits_ref (value_t &value)
Detailed Description
template<typename T>
struct tbb::internal::atomic_impl< T >
Base class that provides basic functionality for atomic<T> without fetch_and_add.
Works for any type T that has the same size as an integral type, has a trivial constructor/destructor, and can be copied/compared by memcpy/memcmp.
Definition at line 220 of file atomic.h.
Member Typedef Documentation
template<typename T> typedef T tbb::internal::atomic_impl< T >::value_type
Definition at line 271 of file atomic.h.
Constructor & Destructor Documentation
template<typename T> tbb::internal::atomic_impl< T >::atomic_impl () default
template<typename T> constexpr tbb::internal::atomic_impl< T >::atomic_impl (value_type value) inline
Definition at line 275 of file atomic.h.
 :my_storage(value){}
Member Function Documentation
template<typename T> template<memory_semantics M> value_type tbb::internal::atomic_impl< T >::compare_and_swap (value_type value, value_type comparand) inline
Definition at line 289 of file atomic.h.
Referenced by tbb::queuing_rw_mutex::scoped_lock::acquire(), tbb::internal::arena::advertise_new_work(), tbb::internal::concurrent_vector_base_v3::helper::assign_first_segment_if_necessary(), tbb::internal::atomic_do_once(), tbb::internal::atomic_update(), tbb::interface5::fetch_and_and(), tbb::interface5::fetch_and_or(), tbb::internal::concurrent_vector_base_v3::internal_grow_to_at_least_with_result(), tbb::internal::concurrent_queue_base_v3::internal_insert_if_not_full(), tbb::internal::concurrent_queue_base_v3::internal_pop_if_present(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_try_pop(), tbb::interface5::reader_writer_lock::set_next_writer(), tbb::internal::rml::private_worker::start_shutdown(), tbb::internal::rml::private_worker::wake_or_launch(), and tbb::internal::rml::private_server::wake_some().
{
         return to_value<value_type>(
                 internal::atomic_traits<sizeof(value_type),M>::compare_and_swap( &my_storage.my_value, to_bits(value), to_bits(comparand) )
         );
     }
template<typename T> value_type tbb::internal::atomic_impl< T >::compare_and_swap (value_type value, value_type comparand) inline
Definition at line 295 of file atomic.h.
{
         return compare_and_swap<full_fence>(value,comparand);
     }
template<typename T> template<memory_semantics M> value_type tbb::internal::atomic_impl< T >::fetch_and_store (value_type value) inline
Definition at line 278 of file atomic.h.
Referenced by tbb::interface9::internal::flag_task::mark_task_stolen(), tbb::interface6::internal::aggregator_generic< operation_type >::start_handle_operations(), and tbb::interface6::aggregator_ext< internal::basic_handler >::start_handle_operations().
{
           return to_value<value_type>(
                   internal::atomic_traits<sizeof(value_type),M>::fetch_and_store( &my_storage.my_value, to_bits(value) )
           );
     }
template<typename T> value_type tbb::internal::atomic_impl< T >::fetch_and_store (value_type value) inline
Definition at line 284 of file atomic.h.
{
         return fetch_and_store<full_fence>(value);
     }
template<typename T> template<memory_semantics M> value_type tbb::internal::atomic_impl< T >::load () const inline
Definition at line 306 of file atomic.h.
Referenced by tbb::concurrent_vector< padded_element, padded_allocator_type >::concurrent_vector(), tbb::concurrent_vector< padded_element, padded_allocator_type >::grow_by(), tbb::internal::concurrent_vector_base_v3::internal_swap(), tbb::internal::concurrent_vector_base_v3::segment_t::load(), tbb::internal::concurrent_vector_base_v3::segment_t::operator=(), tbb::internal::concurrent_vector_base_v3::segment_t::segment_t(), internal::async_storage< T >::set(), internal::async_storage< T >::subscribe(), and tbb::concurrent_vector< padded_element, padded_allocator_type >::~concurrent_vector().
{
         return to_value<value_type>(
                 internal::atomic_load_store_traits<M>::load( to_bits_ref(my_storage.my_value) )
         );
     }
template<typename T> value_type tbb::internal::atomic_impl< T >::load () const inline
Definition at line 312 of file atomic.h.
{
         return load<acquire>();
     }
template<typename T> tbb::internal::atomic_impl< T >::operator value_type () const volatile inline
Definition at line 299 of file atomic.h.
                                          {                // volatile qualifier here for backwards compatibility
         return  to_value<value_type>(
                 __TBB_load_with_acquire( to_bits_ref(my_storage.my_value) )
         );
     }
template<typename T> template<memory_semantics M> void tbb::internal::atomic_impl< T >::store (value_type value) inline
Definition at line 317 of file atomic.h.
Referenced by internal::async_storage< T >::async_storage(), tbb::internal::concurrent_vector_base_v3::concurrent_vector_base_v3(), tbb::internal::concurrent_vector_base_v3::internal_swap(), tbb::internal::concurrent_vector_base_v3::segment_t::operator=(), tbb::internal::concurrent_vector_base_v3::segment_t::segment_t(), internal::async_storage< T >::set(), tbb::internal::concurrent_vector_base_v3::segment_t::store(), tbb::internal::task_scheduler_observer_v3::task_scheduler_observer_v3(), and tbb::internal::task_scheduler_observer_v3::~task_scheduler_observer_v3().
{
         internal::atomic_load_store_traits<M>::store( to_bits_ref(my_storage.my_value), to_bits(value));
     }
template<typename T> void tbb::internal::atomic_impl< T >::store (value_type value) inline
Definition at line 321 of file atomic.h.
{
         store<release>( value );
     }
template<typename T> value_type tbb::internal::atomic_impl< T >::store_with_release (value_type rhs) inline protected
Definition at line 326 of file atomic.h.
{
        //TODO: unify with store<release>
         __TBB_store_with_release( to_bits_ref(my_storage.my_value), to_bits(rhs) );
         return rhs;
     }
template<typename T> template<typename value_t > static converter<value_t>::bits_type tbb::internal::atomic_impl< T >::to_bits (value_t value) inline static private
Definition at line 236 of file atomic.h.
{
         return converter<value_t>(value).bits;
     }
template<typename T> template<typename value_t > static converter<value_t>::bits_type& tbb::internal::atomic_impl< T >::to_bits_ref (value_t & value) inline static private
Definition at line 259 of file atomic.h.
{
         //TODO: this #ifdef is temporary workaround, as union conversion seems to fail
         //on suncc for 64 bit types for 32 bit target
         #if !__SUNPRO_CC
             return *(typename converter<value_t>::bits_type*)ptr_converter<value_t*>(&value).bits;
         #else
             return *(typename converter<value_t>::bits_type*)(&value);
         #endif
     }
template<typename T> template<typename value_t > static value_t tbb::internal::atomic_impl< T >::to_value (typename converter< value_t >::bits_type bits) inline static private
Definition at line 240 of file atomic.h.
{
         converter<value_t> u;
         u.bits = bits;
         return u.value;
     }
Member Data Documentation
template<typename T> aligned_storage<T,sizeof(T)> tbb::internal::atomic_impl< T >::my_storage protected
Definition at line 222 of file atomic.h.
The documentation for this struct was generated from the following file:
atomic.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.