Intel(R) Threading Building Blocks Doxygen Documentation: streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args > Class Template Reference
streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args > Class Template Reference
Classes
class run_finalize_func
class run_kernel_func
class send_func
Public Member Functions
args_storage (const kernel_type &kernel, StreamFactory &f, Args &&...args)
args_storage (const args_storage &k)
args_storage (const args_storage_base &k, Args &&...args)
void enqueue (kernel_input_tuple &ip, output_ports_type &op, const streaming_node &n) __TBB_override
void send (device_type d) __TBB_override
args_storage_base * clone () const __TBB_override
Public Member Functions inherited from streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage_base
virtual ~args_storage_base ()
Private Types
typedef args_storage_base::output_ports_type output_ports_type
typedef tbb::internal::stored_pack< Args... > args_pack_type
Private Member Functions
template<int N>
bool do_try_put (const kernel_input_tuple &ip, output_ports_type &op) const
template<int... S>
bool do_try_put (const kernel_input_tuple &ip, output_ports_type &op, internal::sequence< S... >) const
Static Private Member Functions
template<typename FinalizeFn >
static run_finalize_func< FinalizeFn > make_run_finalize_func (kernel_input_tuple &ip, StreamFactory &factory, FinalizeFn fn)
Private Attributes
args_pack_type my_args_pack
Additional Inherited Members
Public Types inherited from streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage_base
typedef kernel_multifunction_node::output_ports_type output_ports_type
Protected Member Functions inherited from streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage_base
args_storage_base (const kernel_type &kernel, StreamFactory &f)
args_storage_base (const args_storage_base &k)
Protected Attributes inherited from streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage_base
const kernel_type my_kernel
StreamFactory & my_factory
Detailed Description
template<typename... Ports, typename JP, typename StreamFactory>
template<typename... Args>
class streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >
Definition at line 492 of file _flow_graph_streaming_node.h.
Member Typedef Documentation
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> typedef tbb::internal::stored_pack<Args...> streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::args_pack_type private
Definition at line 631 of file _flow_graph_streaming_node.h.
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> typedef args_storage_base::output_ports_type streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::output_ports_type private
Definition at line 493 of file _flow_graph_streaming_node.h.
Constructor & Destructor Documentation
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::args_storage (const kernel_type & kernel, StreamFactory & f, Args &&... args) inline
Definition at line 588 of file _flow_graph_streaming_node.h.
             : args_storage_base( kernel, f )
             , my_args_pack( std::forward<Args>(args)... )
         {}
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::args_storage (const args_storage & k) inline
Definition at line 593 of file _flow_graph_streaming_node.h.
 : args_storage_base( k ), my_args_pack( k.my_args_pack ) {}
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::args_storage (const args_storage_base & k, Args &&... args) inline
Definition at line 595 of file _flow_graph_streaming_node.h.
 : args_storage_base( k ), my_args_pack( std::forward<Args>(args)... ) {}
Member Function Documentation
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> args_storage_base* streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::clone () const inline virtual
Implements streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage_base.
Definition at line 625 of file _flow_graph_streaming_node.h.
{
             // Create new args_storage with copying constructor.
             return new args_storage<Args...>( *this );
         }
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> template<int N> bool streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::do_try_put (const kernel_input_tuple & ip, output_ports_type & op) const inline private
Definition at line 497 of file _flow_graph_streaming_node.h.
References S.
{
             const auto& t = get<N + 1>( ip );
             auto &port = get<N>( op );
             return port.try_put( t );
         }
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> template<int... S> bool streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::do_try_put (const kernel_input_tuple & ip, output_ports_type & op, internal::sequence< S... >) const inline private
Definition at line 504 of file _flow_graph_streaming_node.h.
References or_return_values().
{
             return internal::or_return_values( do_try_put<S>( ip, op )... );
         }
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> void streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::enqueue (kernel_input_tuple & ip, output_ports_type & op, const streaming_node< tuple< Ports... >, JP, StreamFactory > & n) inline virtual
Implements streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage_base.
Definition at line 597 of file _flow_graph_streaming_node.h.
References tbb::internal::call(), and do_try_put().
{
             // Make const qualified args_pack (from non-const)
             const args_pack_type& const_args_pack = my_args_pack;
             // factory.enqure_kernel() gets
             //  - 'ip' tuple elements by reference and updates it (and 'ip') with dependencies
             //  - arguments (from my_args_pack) by const-reference via const_args_pack
             tbb::internal::call( run_kernel_func( ip, n, *this ), const_args_pack );
             if (! do_try_put( ip, op, input_sequence() ) ) {
                 graph& g = n.my_graph;
                 // No one message was passed to successors so set a callback to extend the graph lifetime until the kernel completion.
                 g.increment_wait_count();
                 // factory.finalize() gets
                 //  - 'ip' tuple elements by reference, so 'ip' might be changed
                 //  - arguments (from my_args_pack) by const-reference via const_args_pack
                 tbb::internal::call( make_run_finalize_func(ip, this->my_factory, [&g] {
                     g.decrement_wait_count();
                 }), const_args_pack );
             }
         }
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> template<typename FinalizeFn > static run_finalize_func<FinalizeFn> streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::make_run_finalize_func (kernel_input_tuple & ip, StreamFactory & factory, FinalizeFn fn) inline static private
Definition at line 569 of file _flow_graph_streaming_node.h.
References fn.
{
             return run_finalize_func<FinalizeFn>( ip, factory, fn );
         }
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> void streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::send (device_type d) inline virtual
Implements streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage_base.
Definition at line 619 of file _flow_graph_streaming_node.h.
References tbb::internal::call(), and d.
{
             // factory.send() gets arguments by reference and updates these arguments with dependencies
             // (it gets but usually ignores port_ref-s)
             tbb::internal::call( send_func( this->my_factory, d ), my_args_pack );
         }
Member Data Documentation
template<typename... Ports, typename JP , typename StreamFactory > template<typename... Args> args_pack_type streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::my_args_pack private
Definition at line 632 of file _flow_graph_streaming_node.h.
The documentation for this class was generated from the following file:
_flow_graph_streaming_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.