Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::__TBB_InitOnce Class Reference
tbb::internal::__TBB_InitOnce Class Reference
Class that supports TBB initialization.
#include <tbb_main.h>
Public Member Functions
__TBB_InitOnce ()
Add initial reference to resources.
~__TBB_InitOnce ()
Remove the initial reference to resources.
Static Public Member Functions
static void lock ()
static void unlock ()
static bool initialization_done ()
static void add_ref ()
Add reference to resources. If first reference added, acquire the resources.
static void remove_ref ()
Remove reference to resources. If last reference removed, release the resources.
Static Private Member Functions
static void acquire_resources ()
Platform specific code to acquire resources.
static void release_resources ()
Platform specific code to release resources.
Static Private Attributes
static atomic< int > count
Counter of references to global shared resources such as TLS.
static bool InitializationDone
Specifies if the one-time initializations has been done.
static __TBB_atomic_flag InitializationLock
Global initialization lock.
Friends
void DoOneTimeInitializations ()
Performs thread-safe lazy one-time general TBB initialization.
void ITT_DoUnsafeOneTimeInitialization ()
Detailed Description
Class that supports TBB initialization.
It handles acquisition and release of global resources (e.g. TLS) during startup and shutdown, as well as synchronization for DoOneTimeInitializations.
Definition at line 41 of file tbb_main.h.
Constructor & Destructor Documentation
tbb::internal::__TBB_InitOnce::__TBB_InitOnce () inline
Add initial reference to resources.
We assume that dynamic loading of the library prevents any other threads from entering the library until this constructor has finished running.
Definition at line 73 of file tbb_main.h.
References add_ref().
 { add_ref(); }
tbb::internal::__TBB_InitOnce::~__TBB_InitOnce () inline
Remove the initial reference to resources.
This is not necessarily the last reference if other threads are still running.
Definition at line 77 of file tbb_main.h.
References add_ref(), initialization_done(), remove_ref(), and tbb::internal::governor::terminate_auto_initialized_scheduler().
                       {
         governor::terminate_auto_initialized_scheduler(); // TLS dtor not called for the main thread
         remove_ref();
         // We assume that InitializationDone is not set after file-scope destructors
         // start running, and thus no race on InitializationDone is possible.
         if( initialization_done() ) {
             // Remove an extra reference that was added in DoOneTimeInitializations.
             remove_ref();
         }
     }
Member Function Documentation
static void tbb::internal::__TBB_InitOnce::acquire_resources () static private
Platform specific code to acquire resources.
void tbb::internal::__TBB_InitOnce::add_ref () static
Add reference to resources. If first reference added, acquire the resources.
Definition at line 120 of file tbb_main.cpp.
References tbb::internal::governor::acquire_resources(), and count.
Referenced by __TBB_InitOnce(), tbb::internal::DoOneTimeInitializations(), tbb::internal::market::global_market(), and ~__TBB_InitOnce().
{
     if( ++count==1 )
         governor::acquire_resources();
 }
static bool tbb::internal::__TBB_InitOnce::initialization_done () inline static
Definition at line 68 of file tbb_main.h.
References tbb::internal::__TBB_load_with_acquire().
Referenced by tbb::internal::DoOneTimeInitializations(), tbb::internal::governor::one_time_init(), tbb::internal::governor::release_resources(), and ~__TBB_InitOnce().
 { return __TBB_load_with_acquire(InitializationDone); }
static void tbb::internal::__TBB_InitOnce::lock () inline static
Definition at line 64 of file tbb_main.h.
References __TBB_LockByte().
Referenced by tbb::internal::DoOneTimeInitializations(), tbb::interface9::global_control::internal_create(), tbb::interface9::global_control::internal_destroy(), and remove_ref().
 { __TBB_LockByte( InitializationLock ); }
static void tbb::internal::__TBB_InitOnce::release_resources () static private
Platform specific code to release resources.
void tbb::internal::__TBB_InitOnce::remove_ref () static
Remove reference to resources. If last reference removed, release the resources.
Definition at line 125 of file tbb_main.cpp.
References __itt_domain_create, __itt_string_handle_create, __itt_string_handle_createA(), __TBB_ASSERT, tbb::internal::__TBB_load_ittnotify(), _T, count, tbb::internal::initialize_cache_aligned_allocator(), tbb::internal::ITT_DOMAIN_ALGO, tbb::internal::ITT_DOMAIN_FLOW, tbb::internal::ITT_DOMAIN_MAIN, ITT_DoUnsafeOneTimeInitialization, ITT_FINI_ITTLIB, tbb::internal::ITT_NUM_DOMAINS, ITT_SYNC_CREATE, lock(), tbb::internal::governor::release_resources(), tbb::internal::Scheduler_OneTimeInitialization(), and unlock().
Referenced by tbb::internal::market::destroy(), tbb::internal::DoOneTimeInitializations(), and ~__TBB_InitOnce().
{
     int k = --count;
     __TBB_ASSERT(k>=0,"removed __TBB_InitOnce ref that was not added?");
     if( k==0 ) {
         governor::release_resources();
         ITT_FINI_ITTLIB();
     }
 }
static void tbb::internal::__TBB_InitOnce::unlock () inline static
Definition at line 66 of file tbb_main.h.
References __TBB_UnlockByte.
Referenced by tbb::internal::DoOneTimeInitializations(), and remove_ref().
 { __TBB_UnlockByte( InitializationLock ); }
Friends And Related Function Documentation
void DoOneTimeInitializations () friend
Performs thread-safe lazy one-time general TBB initialization.
Definition at line 214 of file tbb_main.cpp.
{
     suppress_unused_warning(_pad);
     __TBB_InitOnce::lock();
     // No fence required for load of InitializationDone, because we are inside a critical section.
     if( !__TBB_InitOnce::InitializationDone ) {
         __TBB_InitOnce::add_ref();
         if( GetBoolEnvironmentVariable("TBB_VERSION") )
             PrintVersion();
         bool itt_present = false;
 #if DO_ITT_NOTIFY
         ITT_DoUnsafeOneTimeInitialization();
         itt_present = ITT_Present;
 #endif /* DO_ITT_NOTIFY */
         initialize_cache_aligned_allocator();
         governor::initialize_rml_factory();
         Scheduler_OneTimeInitialization( itt_present );
         // Force processor groups support detection
         governor::default_num_threads();
         // Dump version data
         governor::print_version_info();
         PrintExtraVersionInfo( "Tools support", itt_present ? "enabled" : "disabled" );
         __TBB_InitOnce::InitializationDone = true;
     }
     __TBB_InitOnce::unlock();
 }
void ITT_DoUnsafeOneTimeInitialization () friend
Referenced by tbb::internal::DoOneTimeInitializations(), and remove_ref().
Member Data Documentation
atomic< int > tbb::internal::__TBB_InitOnce::count static private
Counter of references to global shared resources such as TLS.
Definition at line 45 of file tbb_main.h.
Referenced by add_ref(), and remove_ref().
bool tbb::internal::__TBB_InitOnce::InitializationDone static private
Specifies if the one-time initializations has been done.
Flag that is set to true after one-time initializations are done.
Definition at line 54 of file tbb_main.h.
__TBB_atomic_flag tbb::internal::__TBB_InitOnce::InitializationLock static private
Global initialization lock.
Scenarios are possible when tools interop has to be initialized before the TBB itself. This imposes a requirement that the global initialization lock has to support valid static initialization, and does not issue any tool notifications in any build mode.
Definition at line 61 of file tbb_main.h.
The documentation for this class was generated from the following files:
tbb_main.h
tbb_main.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.