Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::allocate_additional_child_of_proxy Class Reference
tbb::internal::allocate_additional_child_of_proxy Class Reference
#include <task.h>
Public Member Functions
allocate_additional_child_of_proxy (task &parent_)
task &__TBB_EXPORTED_METHOD allocate (size_t size) const
void __TBB_EXPORTED_METHOD free (task &) const
Private Attributes
task * self
No longer used, but retained for binary layout compatibility. Always NULL.
task & parent
Detailed Description
Definition at line 47 of file task.h.
Constructor & Destructor Documentation
tbb::internal::allocate_additional_child_of_proxy::allocate_additional_child_of_proxy (task & parent_) inline explicit
Definition at line 52 of file task.h.
References __TBB_EXPORTED_METHOD, allocate(), free(), size, and tbb::internal::suppress_unused_warning().
                                                                      : self(NULL), parent(parent_) {
             suppress_unused_warning( self );
         }
Member Function Documentation
task & tbb::internal::allocate_additional_child_of_proxy::allocate (size_t size) const
Definition at line 132 of file task.cpp.
References __TBB_CONTEXT_ARG, tbb::internal::generic_scheduler::allocate_task(), tbb::internal::governor::local_scheduler_weak(), parent, and s.
Referenced by allocate_additional_child_of_proxy(), and tbb::internal::allocate_root_with_context_proxy::allocate_root_with_context_proxy().
{
     parent.increment_ref_count();
     generic_scheduler* s = governor::local_scheduler_weak();
     return s->allocate_task( size, __TBB_CONTEXT_ARG(&parent, parent.prefix().context) );
 }
void tbb::internal::allocate_additional_child_of_proxy::free (task & task) const
Definition at line 138 of file task.cpp.
References tbb::internal::generic_scheduler::free_task(), tbb::internal::governor::local_scheduler_weak(), tbb::internal::local_task, parent, and task.
Referenced by allocate_additional_child_of_proxy(), and tbb::internal::allocate_root_with_context_proxy::allocate_root_with_context_proxy().
{
     // Undo the increment.  We do not check the result of the fetch-and-decrement.
     // We could consider be spawning the task if the fetch-and-decrement returns 1.
     // But we do not know that was the programmer's intention.
     // Furthermore, if it was the programmer's intention, the program has a fundamental
     // race condition (that we warn about in Reference manual), because the
     // reference count might have become zero before the corresponding call to
     // allocate_additional_child_of_proxy::allocate.
     parent.internal_decrement_ref_count();
     governor::local_scheduler_weak()->free_task<local_task>(task);
 }
Member Data Documentation
task& tbb::internal::allocate_additional_child_of_proxy::parent private
Definition at line 50 of file task.h.
task* tbb::internal::allocate_additional_child_of_proxy::self private
No longer used, but retained for binary layout compatibility. Always NULL.
Definition at line 49 of file task.h.
The documentation for this class was generated from the following files:
task.h
task.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.