Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::allocate_root_proxy Class Reference
tbb::internal::allocate_root_proxy Class Reference
#include <task.h>
Static Public Member Functions
static task &__TBB_EXPORTED_FUNC allocate (size_t size)
static void __TBB_EXPORTED_FUNC free (task &)
Detailed Description
Definition at line 149 of file task.h.
Member Function Documentation
task & tbb::internal::allocate_root_proxy::allocate (size_t size) static
Definition at line 39 of file task.cpp.
References __TBB_ASSERT, __TBB_CONTEXT_ARG, tbb::internal::task_prefix::context, tbb::task_group_context::itt_caller, ITT_STACK_CREATE, tbb::internal::governor::local_scheduler_weak(), and p.
Referenced by operator new().
{
     internal::generic_scheduler* v = governor::local_scheduler_weak();
     __TBB_ASSERT( v, "thread did not activate a task_scheduler_init object?" );
 #if __TBB_TASK_GROUP_CONTEXT
     task_prefix& p = v->my_innermost_running_task->prefix();
     ITT_STACK_CREATE(p.context->itt_caller);
 #endif
     // New root task becomes part of the currently running task's cancellation context
     return v->allocate_task( size, __TBB_CONTEXT_ARG(NULL, p.context) );
 }
void tbb::internal::allocate_root_proxy::free (task & task) static
Definition at line 51 of file task.cpp.
References __TBB_ASSERT, tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), tbb::internal::allocate_root_with_context_proxy::allocate(), tbb::task_group_context::binding_required, tbb::task_group_context::fp_settings, tbb::internal::allocate_root_with_context_proxy::free(), tbb::task_group_context::isolated, ITT_STACK_CREATE, tbb::internal::governor::local_scheduler_weak(), tbb::internal::local_task, s, size, and task.
Referenced by operator delete().
{
     internal::generic_scheduler* v = governor::local_scheduler_weak();
     __TBB_ASSERT( v, "thread does not have initialized task_scheduler_init object?" );
 #if __TBB_TASK_GROUP_CONTEXT
     // No need to do anything here as long as there is no context -> task connection
 #endif /* __TBB_TASK_GROUP_CONTEXT */
     v->free_task<local_task>( task );
 }
The documentation for this class was generated from the following files:
task.h
task.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.