Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::affinity_partitioner_base_v3 Class Reference
tbb::internal::affinity_partitioner_base_v3 Class Reference
Defines entry point for affinity partitioner into tbb run-time library.
#include <partitioner.h>
Private Member Functions
affinity_partitioner_base_v3 ()
Zeros the fields.
~affinity_partitioner_base_v3 ()
Deallocates my_array.
void __TBB_EXPORTED_METHOD resize (unsigned factor)
Resize my_array.
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
affinity_id * my_array
Array that remembers affinities of tree positions to affinity_id.
size_t my_size
Number of elements in my_array.
Friends
class tbb::affinity_partitioner
class tbb::interface9::internal::affinity_partition_type
Detailed Description
Defines entry point for affinity partitioner into tbb run-time library.
Definition at line 81 of file partitioner.h.
Constructor & Destructor Documentation
tbb::internal::affinity_partitioner_base_v3::affinity_partitioner_base_v3 () inline private
Zeros the fields.
Definition at line 90 of file partitioner.h.
 : my_array(NULL), my_size(0) {}
tbb::internal::affinity_partitioner_base_v3::~affinity_partitioner_base_v3 () inline private
Deallocates my_array.
Definition at line 92 of file partitioner.h.
References __TBB_EXPORTED_METHOD, and tbb::interface9::internal::affinity_partition_type::factor.
 {resize(0);}
Member Function Documentation
void tbb::internal::affinity_partitioner_base_v3::resize (unsigned factor) private
Resize my_array.
Retains values if resulting size is the same.
Definition at line 161 of file task.cpp.
References tbb::internal::governor::local_scheduler(), tbb::internal::generic_scheduler::max_threads_in_arena(), new_size, tbb::internal::NFS_Allocate(), and tbb::internal::NFS_Free().
Referenced by tbb::interface9::internal::affinity_partition_type::affinity_partition_type().
{
     // Check factor to avoid asking for number of workers while there might be no arena.
     size_t new_size = factor ? factor*governor::local_scheduler()->max_threads_in_arena() : 0;
     if( new_size!=my_size ) {
         if( my_array ) {
             NFS_Free( my_array );
             // Following two assignments must be done here for sake of exception safety.
             my_array = NULL;
             my_size = 0;
         }
         if( new_size ) {
             my_array = static_cast<affinity_id*>(NFS_Allocate(new_size,sizeof(affinity_id), NULL ));
             memset( my_array, 0, sizeof(affinity_id)*new_size );
             my_size = new_size;
         }
     }
 }
Friends And Related Function Documentation
friend class tbb::affinity_partitioner friend
Definition at line 82 of file partitioner.h.
friend class tbb::interface9::internal::affinity_partition_type friend
Definition at line 83 of file partitioner.h.
Member Data Documentation
affinity_id* tbb::internal::affinity_partitioner_base_v3::my_array private
Array that remembers affinities of tree positions to affinity_id.
NULL if my_size==0.
Definition at line 86 of file partitioner.h.
Referenced by tbb::interface9::internal::affinity_partition_type::affinity_partition_type().
size_t tbb::internal::affinity_partitioner_base_v3::my_size private
Number of elements in my_array.
Definition at line 88 of file partitioner.h.
The documentation for this class was generated from the following files:
partitioner.h
task.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.