Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::arena_slot Struct Reference
tbb::internal::arena_slot Struct Reference
#include <scheduler_common.h>
Public Member Functions
void fill_with_canary_pattern (size_t, size_t)
void allocate_task_pool (size_t n)
void free_task_pool ()
Deallocate task pool that was allocated by means of allocate_task_pool.
Additional Inherited Members
Public Attributes inherited from tbb::internal::padded_base< arena_slot_line1, NFS_MaxLineSize, sizeof(arena_slot_line1)%NFS_MaxLineSize >
char pad [S-R]
Public Attributes inherited from tbb::internal::arena_slot_line1
generic_scheduler * my_scheduler
Scheduler of the thread attached to the slot.
task **__TBB_atomic task_pool
__TBB_atomic size_t head
Index of the first ready task in the deque.
Public Attributes inherited from tbb::internal::padded_base< arena_slot_line2, NFS_MaxLineSize, sizeof(arena_slot_line2)%NFS_MaxLineSize >
char pad [S-R]
Public Attributes inherited from tbb::internal::arena_slot_line2
unsigned hint_for_pop
Hint provided for operations with the container of starvation-resistant tasks.
__TBB_atomic size_t tail
Index of the element following the last ready task in the deque.
size_t my_task_pool_size
Capacity of the primary task pool (number of elements - pointers to task).
task **__TBB_atomic task_pool_ptr
Detailed Description
Definition at line 375 of file scheduler_common.h.
Member Function Documentation
void tbb::internal::arena_slot::allocate_task_pool (size_t n) inline
Definition at line 385 of file scheduler_common.h.
References tbb::internal::NFS_Allocate(), and tbb::internal::NFS_MaxLineSize.
Referenced by tbb::internal::generic_scheduler::prepare_task_pool().
{
         size_t byte_size = ((n * sizeof(task*) + NFS_MaxLineSize - 1) / NFS_MaxLineSize) * NFS_MaxLineSize;
         my_task_pool_size = byte_size / sizeof(task*);
         task_pool_ptr = (task**)NFS_Allocate( 1, byte_size, NULL );
         // No need to clear the fresh deque since valid items are designated by the head and tail members.
         // But fill it with a canary pattern in the high vigilance debug mode.
         fill_with_canary_pattern( 0, my_task_pool_size );
     }
void tbb::internal::arena_slot::fill_with_canary_pattern (size_t , size_t) inline
Definition at line 382 of file scheduler_common.h.
Referenced by tbb::internal::generic_scheduler::enqueue(), and tbb::internal::generic_scheduler::prepare_task_pool().
 {}
void tbb::internal::arena_slot::free_task_pool () inline
Deallocate task pool that was allocated by means of allocate_task_pool.
Definition at line 395 of file scheduler_common.h.
References __TBB_ASSERT, and tbb::internal::NFS_Free().
{
         // TODO: understand the assertion and modify
         // __TBB_ASSERT( !task_pool /*TODO: == EmptyTaskPool*/, NULL);
         if( task_pool_ptr ) {
            __TBB_ASSERT( my_task_pool_size, NULL);
            NFS_Free( task_pool_ptr );
            task_pool_ptr = NULL;
            my_task_pool_size = 0;
         }
     }
The documentation for this struct was generated from the following file:
scheduler_common.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.