Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::atomic_backoff Class Reference
tbb::internal::atomic_backoff Class Reference
Class that implements exponential backoff.
#include <tbb_machine.h>
Public Member Functions
atomic_backoff ()
atomic_backoff (bool)
void pause ()
Pause for a while.
bool bounded_pause ()
Pause for a few times and return false if saturated.
void reset ()
Private Attributes
int32_t count
Static Private Attributes
static const int32_t LOOPS_BEFORE_YIELD = 16
Time delay, in units of "pause" instructions.
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
Class that implements exponential backoff.
See implementation of spin_wait_while_eq for an example.
Definition at line 349 of file tbb_machine.h.
Constructor & Destructor Documentation
tbb::internal::atomic_backoff::atomic_backoff () inline
Definition at line 359 of file tbb_machine.h.
 : count(1) {}
tbb::internal::atomic_backoff::atomic_backoff (bool) inline
Definition at line 361 of file tbb_machine.h.
References tbb::internal::pause().
 : count(1) { pause(); }
Member Function Documentation
bool tbb::internal::atomic_backoff::bounded_pause () inline
Pause for a few times and return false if saturated.
Definition at line 376 of file tbb_machine.h.
References __TBB_Pause().
Referenced by tbb::internal::prolonged_pause().
{
         __TBB_Pause(count);
         if( count<LOOPS_BEFORE_YIELD ) {
             // Pause twice as long the next time.
             count*=2;
             return true;
         } else {
             return false;
         }
     }
void tbb::internal::atomic_backoff::pause () inline
Pause for a while.
Definition at line 364 of file tbb_machine.h.
References __TBB_Pause(), and __TBB_Yield.
Referenced by __TBB_AtomicAND(), __TBB_AtomicOR(), tbb::internal::__TBB_FetchAndAddGeneric(), tbb::internal::__TBB_FetchAndStoreGeneric(), __TBB_LockByte(), tbb::internal::__TBB_MaskedCompareAndSwap(), tbb::internal::generic_scheduler::acquire_task_pool(), tbb::internal::concurrent_vector_base_v3::helper::extend_segment_table(), tbb::interface5::fetch_and_and(), tbb::interface5::fetch_and_or(), tbb::internal::concurrent_vector_base_v3::internal_grow_to_at_least_with_result(), tbb::internal::mail_outbox::internal_pop(), tbb::internal::micro_queue::push(), tbb::interface5::spin_wait_until_and(), tbb::internal::spin_wait_until_eq(), tbb::strict_ppl::internal::micro_queue< T >::spin_wait_until_my_turn(), tbb::internal::spin_wait_while(), tbb::internal::spin_wait_while_eq(), tbb::interface5::spin_wait_while_geq(), and tbb::TBB_runtime_interface_version().
                  {
         if( count<=LOOPS_BEFORE_YIELD ) {
             __TBB_Pause(count);
             // Pause twice as long the next time.
             count*=2;
         } else {
             // Pause is so long that we might as well yield CPU to scheduler.
             __TBB_Yield();
         }
     }
void tbb::internal::atomic_backoff::reset () inline
Definition at line 387 of file tbb_machine.h.
                  {
         count = 1;
     }
Member Data Documentation
int32_t tbb::internal::atomic_backoff::count private
Definition at line 354 of file tbb_machine.h.
const int32_t tbb::internal::atomic_backoff::LOOPS_BEFORE_YIELD = 16 static private
Time delay, in units of "pause" instructions.
Should be equal to approximately the number of "pause" instructions that take the same time as an context switch. Must be a power of two.
Definition at line 353 of file tbb_machine.h.
The documentation for this class was generated from the following file:
tbb_machine.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.