Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::async_node< Input, Output, Policy, Allocator > Class Template Reference
tbb::flow::interface10::async_node< Input, Output, Policy, Allocator > Class Template Reference
Implements async node.
#include <flow_graph.h>
Classes
class receiver_gateway_impl
struct try_put_functor
Public Types
typedef Input input_type
typedef Output output_type
typedef receiver< input_type > receiver_type
typedef receiver_type::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
typedef receiver_gateway< output_type > gateway_type
typedef internal::async_body_base< gateway_type > async_body_base_type
typedef base_type::output_ports_type output_ports_type
Public Types inherited from tbb::flow::interface10::multifunction_node< Input, tuple< Output >, Policy, Allocator >
typedef Input input_type
typedef null_type output_type
typedef internal::wrap_tuple_elements< N, internal::multifunction_output, tuple< Output > >::type output_ports_type
typedef internal::multifunction_input< input_type, output_ports_type, Policy, Allocator > input_impl_type
typedef internal::function_input_queue< input_type, Allocator > input_queue_type
Public Types inherited from tbb::flow::interface10::internal::multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator >
typedef Input input_type
typedef internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type output_ports_type
typedef multifunction_body< input_type, output_ports_type > multifunction_body_type
typedef multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator > my_class
typedef function_input_base< Input, Policy, Allocator, my_class > base_type
typedef function_input_queue< input_type, Allocator > input_queue_type
Public Types inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator > >
typedef Input input_type
The input type of this receiver.
typedef receiver< input_type >::predecessor_type predecessor_type
typedef predecessor_cache< input_type, null_mutex > predecessor_cache_type
typedef function_input_queue< input_type, Allocator > input_queue_type
typedef Allocator::template rebind< input_queue_type >::other queue_allocator_type
Public Types inherited from tbb::flow::interface10::receiver< Input >
typedef Input input_type
The input type of this receiver.
typedef internal::async_helpers< Input >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::sender< Output >
typedef Output output_type
The output type of this sender.
typedef internal::async_helpers< Output >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
template<typename Body >
async_node (graph &g, size_t concurrency,)
async_node (const async_node &other)
gateway_type & gateway ()
bool register_successor (successor_type &r) __TBB_override
Add a new successor to this node.
bool remove_successor (successor_type &r) __TBB_override
Removes a successor from this node.
template<typename Body >
Body copy_function_object ()
Public Member Functions inherited from tbb::flow::interface10::multifunction_node< Input, tuple< Output >, Policy, Allocator >
multifunction_node (graph &g, size_t concurrency,)
multifunction_node (const multifunction_node &other)
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::internal::multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator >
multifunction_input (graph &g, size_t max_concurrency,)
multifunction_input (const multifunction_input &src)
Copy constructor.
~multifunction_input ()
Body copy_function_object ()
task * apply_body_impl_bypass (const input_type &i)
output_ports_type & output_ports ()
Public Member Functions inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator > >
__TBB_STATIC_ASSERT (!((internal::has_policy< queueing, Policy >::value)&&(internal::has_policy< rejecting, Policy >::value)),"queueing and rejecting policies can't be specified simultaneously")
function_input_base (graph &g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(size_t max_concurrency, node_priority_t priority))
Constructor for function_input_base.
function_input_base (const function_input_base &src)
Copy constructor.
virtual ~function_input_base ()
Destructor.
task * try_put_task (const input_type &t) __TBB_override
Put item to successor; return task to run the successor if possible.
bool register_predecessor (predecessor_type &src) __TBB_override
Adds src to the list of cached predecessors.
bool remove_predecessor (predecessor_type &src) __TBB_override
Removes src from the list of cached predecessors.
Public Member Functions inherited from tbb::flow::interface10::receiver< Input >
bool try_put (const typename internal::async_helpers< Input >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< Input >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
Public Member Functions inherited from tbb::flow::interface10::sender< Output >
virtual bool try_get (Output &)
Request an item from the sender.
virtual bool try_reserve (Output &)
Reserves an item in the sender.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
virtual bool try_release ()
Releases the reserved item.
virtual bool try_consume ()
Consumes the reserved item.
Protected Member Functions
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::multifunction_node< Input, tuple< Output >, Policy, Allocator >
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator >
void reset (reset_flags f)
Protected Member Functions inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator > >
void reset_function_input_base (reset_flags f)
void reset_receiver (reset_flags f) __TBB_override
put receiver back in initial state
graph & graph_reference () __TBB_override
task * try_get_postponed_task (const input_type &i)
Protected Member Functions inherited from tbb::flow::interface10::receiver< Input >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Protected Member Functions inherited from tbb::flow::interface10::sender< Output >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Private Types
typedef multifunction_node< Input, tuple< Output >, Policy, Allocator > base_type
typedef internal::multifunction_input< Input, typename base_type::output_ports_type, Policy, Allocator > mfn_input_type
Private Member Functions
async_node * self ()
bool try_put_impl (const Output &i)
Implements gateway_type::try_put for an external activity to submit a message to FG.
Private Attributes
tbb::flow::interface10::async_node::receiver_gateway_impl my_gateway
Additional Inherited Members
Static Public Attributes inherited from tbb::flow::interface10::internal::multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator >
static const int N
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Protected Attributes inherited from tbb::flow::interface10::internal::multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator >
multifunction_body_type * my_body
multifunction_body_type * my_init_body
output_ports_type my_output_ports
Protected Attributes inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, multifunction_input< Input, internal::wrap_tuple_elements< tbb::flow::tuple_size< tuple< Output > >::value, internal::multifunction_output, tuple< Output > >::type, Policy, Allocator > >
graph & my_graph_ref
const size_t my_max_concurrency
size_t my_concurrency
input_queue_type * my_queue
predecessor_cache< input_type, null_mutex > my_predecessors
Static Protected Attributes inherited from tbb::flow::interface10::multifunction_node< Input, tuple< Output >, Policy, Allocator >
static const int N
Detailed Description
template<typename Input, typename Output, typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>>
class tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >
Implements async node.
Definition at line 3493 of file flow_graph.h.
Member Typedef Documentation
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef internal::async_body_base<gateway_type> tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::async_body_base_type
Definition at line 3504 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef multifunction_node< Input, tuple< Output >, Policy, Allocator > tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::base_type private
Definition at line 3494 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef receiver_gateway<output_type> tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::gateway_type
Definition at line 3503 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef Input tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::input_type
Definition at line 3498 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef internal::multifunction_input<Input, typename base_type::output_ports_type, Policy, Allocator> tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::mfn_input_type private
Definition at line 3495 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef base_type::output_ports_type tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::output_ports_type
Definition at line 3505 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef Output tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::output_type
Definition at line 3499 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef receiver_type::predecessor_type tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::predecessor_type
Definition at line 3501 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef receiver<input_type> tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::receiver_type
Definition at line 3500 of file flow_graph.h.
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> typedef sender<output_type>::successor_type tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::successor_type
Definition at line 3502 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> template<typename Body > tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::async_node (graph & g, size_t concurrency) inline
Definition at line 3557 of file flow_graph.h.
References tbb::flow::interface10::graph_node::my_graph.
       : base_type(
         g, concurrency,
         internal::async_body<Input, typename base_type::output_ports_type, gateway_type, Body>
         (body, &my_gateway) __TBB_FLOW_GRAPH_PRIORITY_ARG0(priority) ), my_gateway(self()) {
         tbb::internal::fgt_multioutput_node_with_body<1>(
             tbb::internal::FLOW_ASYNC_NODE,
             &this->my_graph, static_cast<receiver<input_type> *>(this),
             this->output_ports(), this->my_body
         );
     }
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::async_node (const async_node< Input, Output, Policy, Allocator > & other) inline
Definition at line 3571 of file flow_graph.h.
References tbb::flow::interface10::graph_node::my_graph.
                                           : base_type(other), sender<Output>(), my_gateway(self()) {
         static_cast<async_body_base_type*>(this->my_body->get_body_ptr())->set_gateway(&my_gateway);
         static_cast<async_body_base_type*>(this->my_init_body->get_body_ptr())->set_gateway(&my_gateway);
         tbb::internal::fgt_multioutput_node_with_body<1>( tbb::internal::FLOW_ASYNC_NODE,
                 &this->my_graph, static_cast<receiver<input_type> *>(this),
                 this->output_ports(), this->my_body );
     }
Member Function Documentation
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> template<typename Body > Body tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::copy_function_object () inline
Definition at line 3603 of file flow_graph.h.
References __TBB_override.
{
         typedef internal::multifunction_body<input_type, typename base_type::output_ports_type> mfn_body_type;
         typedef internal::async_body<Input, typename base_type::output_ports_type, gateway_type, Body> async_body_type;
         mfn_body_type &body_ref = *this->my_body;
         async_body_type ab = *static_cast<async_body_type*>(dynamic_cast< internal::multifunction_body_leaf<input_type, typename base_type::output_ports_type, async_body_type> & >(body_ref).get_body_ptr());
         return ab.get_body();
     }
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> gateway_type& tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::gateway () inline
Definition at line 3580 of file flow_graph.h.
References __TBB_override, and tbb::internal::fgt_multioutput_node_desc().
{
         return my_gateway;
     }
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> bool tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::register_successor (successor_type & r) inline virtual
Add a new successor to this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 3593 of file flow_graph.h.
{
         return internal::output_port<0>(*this).register_successor(r);
     }
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> bool tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::remove_successor (successor_type & r) inline virtual
Removes a successor from this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 3598 of file flow_graph.h.
{
         return internal::output_port<0>(*this).remove_successor(r);
     }
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> void tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::reset_node (reset_flags f) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 3638 of file flow_graph.h.
{
        base_type::reset_node(f);
     }
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> async_node* tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::self () inline private
Definition at line 3543 of file flow_graph.h.
 { return this; }
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> bool tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::try_put_impl (const Output & i) inline private
Implements gateway_type::try_put for an external activity to submit a message to FG.
Definition at line 3546 of file flow_graph.h.
References tbb::flow::interface10::internal::execute_in_graph_arena(), tbb::internal::fgt_async_try_put_begin(), tbb::internal::fgt_async_try_put_end(), tbb::flow::interface10::graph_node::my_graph, and tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::try_put_functor::result.
{
         internal::multifunction_output<Output> &port_0 = internal::output_port<0>(*this);
         tbb::internal::fgt_async_try_put_begin(this, &port_0);
         try_put_functor tpf(port_0, i);
         internal::execute_in_graph_arena(this->my_graph, tpf);
         tbb::internal::fgt_async_try_put_end(this, &port_0);
         return tpf.result;
     }
Member Data Documentation
template<typename Input , typename Output , typename Policy = queueing_lightweight, typename Allocator = cache_aligned_allocator<Input>> tbb::flow::interface10::async_node::receiver_gateway_impl tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::my_gateway private
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.