Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::auto_empty_task Class Reference
tbb::internal::auto_empty_task Class Reference
Smart holder for the empty task class with automatic destruction.
#include <scheduler_utility.h>
Public Member Functions
auto_empty_task (__TBB_CONTEXT_ARG(generic_scheduler *s, task_group_context *context))
~auto_empty_task ()
operator task & ()
task * operator& ()
task_prefix & prefix ()
Private Attributes
task * my_task
generic_scheduler * my_scheduler
Detailed Description
Smart holder for the empty task class with automatic destruction.
Definition at line 34 of file scheduler_utility.h.
Constructor & Destructor Documentation
tbb::internal::auto_empty_task::auto_empty_task (__TBB_CONTEXT_ARG(generic_scheduler *s, task_group_context *context)) inline
Definition at line 38 of file scheduler_utility.h.
         : my_task( new(&s->allocate_task(sizeof(empty_task), __TBB_CONTEXT_ARG(NULL, context))) empty_task )
         , my_scheduler(s)
     {}
tbb::internal::auto_empty_task::~auto_empty_task () inline
Definition at line 43 of file scheduler_utility.h.
References tbb::internal::generic_scheduler::free_task(), and tbb::internal::small_local_task.
 { my_scheduler->free_task<small_local_task>(*my_task); }
Member Function Documentation
tbb::internal::auto_empty_task::operator task & () inline
Definition at line 45 of file scheduler_utility.h.
References my_task.
 { return *my_task; }
task* tbb::internal::auto_empty_task::operator& () inline
Definition at line 46 of file scheduler_utility.h.
References my_task.
 { return my_task; }
task_prefix& tbb::internal::auto_empty_task::prefix () inline
Definition at line 47 of file scheduler_utility.h.
References tbb::task::prefix().
Referenced by tbb::interface7::internal::task_arena_base::internal_execute(), and tbb::internal::generic_scheduler::local_spawn_root_and_wait().
 { return my_task->prefix(); }
Member Data Documentation
generic_scheduler* tbb::internal::auto_empty_task::my_scheduler private
Definition at line 36 of file scheduler_utility.h.
task* tbb::internal::auto_empty_task::my_task private
Definition at line 35 of file scheduler_utility.h.
Referenced by operator task &(), and operator&().
The documentation for this class was generated from the following file:
scheduler_utility.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.