Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::allocate_root_with_context_proxy Class Reference
tbb::internal::allocate_root_with_context_proxy Class Reference
#include <task.h>
Public Member Functions
allocate_root_with_context_proxy (task_group_context &ctx)
task &__TBB_EXPORTED_METHOD allocate (size_t size) const
void __TBB_EXPORTED_METHOD free (task &) const
Private Attributes
task_group_context & my_context
Detailed Description
Definition at line 140 of file task.h.
Constructor & Destructor Documentation
tbb::internal::allocate_root_with_context_proxy::allocate_root_with_context_proxy (task_group_context & ctx) inline
Definition at line 143 of file task.h.
References __TBB_EXPORTED_METHOD, tbb::internal::allocate_additional_child_of_proxy::allocate(), tbb::internal::allocate_additional_child_of_proxy::free(), and size.
 : my_context(ctx) {}
Member Function Documentation
task& __TBB_EXPORTED_METHOD tbb::internal::allocate_root_with_context_proxy::allocate (size_t size) const
Referenced by tbb::internal::allocate_root_proxy::free().
void __TBB_EXPORTED_METHOD tbb::internal::allocate_root_with_context_proxy::free (task &) const
Referenced by tbb::internal::allocate_root_proxy::free().
Member Data Documentation
task_group_context& tbb::internal::allocate_root_with_context_proxy::my_context private
Definition at line 141 of file task.h.
The documentation for this class was generated from the following file:
task.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.