Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::allocate_continuation_proxy Class Reference
tbb::internal::allocate_continuation_proxy Class Reference
#include <task.h>
Public Member Functions
task &__TBB_EXPORTED_METHOD allocate (size_t size) const
void __TBB_EXPORTED_METHOD free (task &) const
Detailed Description
Definition at line 155 of file task.h.
Member Function Documentation
task & tbb::internal::allocate_continuation_proxy::allocate (size_t size) const
Definition at line 100 of file task.cpp.
References __TBB_CONTEXT_ARG, tbb::internal::generic_scheduler::allocate_task(), tbb::internal::assert_task_valid(), tbb::internal::governor::local_scheduler_weak(), parent, tbb::task::parent(), tbb::task::prefix(), and s.
{
     task* t = (task*)this;
     assert_task_valid(t);
     generic_scheduler* s = governor::local_scheduler_weak();
     task* parent = t->parent();
     t->prefix().parent = NULL;
     return s->allocate_task( size, __TBB_CONTEXT_ARG(parent, t->prefix().context) );
 }
void tbb::internal::allocate_continuation_proxy::free (task & mytask) const
Definition at line 109 of file task.cpp.
References tbb::internal::generic_scheduler::free_task(), tbb::internal::governor::local_scheduler_weak(), tbb::internal::local_task, and tbb::task::parent().
{
     // Restore the parent as it was before the corresponding allocate was called.
     ((task*)this)->prefix().parent = mytask.parent();
     governor::local_scheduler_weak()->free_task<local_task>(mytask);
 }
The documentation for this class was generated from the following files:
task.h
task.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.