Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::concurrent_queue_iterator_base_v3 Class Reference
tbb::internal::concurrent_queue_iterator_base_v3 Class Reference
Containers
Type-independent portion of concurrent_queue_iterator.
#include <_concurrent_queue_impl.h>
Protected Member Functions
concurrent_queue_iterator_base_v3 ()
Default constructor.
concurrent_queue_iterator_base_v3 (const concurrent_queue_iterator_base_v3 &i)
Copy constructor.
__TBB_EXPORTED_METHOD concurrent_queue_iterator_base_v3 (const concurrent_queue_base_v3 &queue)
Obsolete entry point for constructing iterator pointing to head of queue.
__TBB_EXPORTED_METHOD concurrent_queue_iterator_base_v3 (const concurrent_queue_base_v3 &queue, size_t offset_of_data)
Construct iterator pointing to head of queue.
void __TBB_EXPORTED_METHOD assign (const concurrent_queue_iterator_base_v3 &i)
Assignment.
void __TBB_EXPORTED_METHOD advance ()
Advance iterator one step towards tail of queue.
__TBB_EXPORTED_METHOD ~concurrent_queue_iterator_base_v3 ()
Destructor.
Protected Attributes
void * my_item
Pointer to current item.
Private Member Functions
void initialize (const concurrent_queue_base_v3 &queue, size_t offset_of_data)
Private Attributes
concurrent_queue_iterator_rep * my_rep
concurrent_queue over which we are iterating.
Friends
template<typename C , typename T , typename U >
bool operator== (const concurrent_queue_iterator< C, T > &i, const concurrent_queue_iterator< C, U > &j)
template<typename C , typename T , typename U >
bool operator!= (const concurrent_queue_iterator< C, T > &i, const concurrent_queue_iterator< C, U > &j)
Detailed Description
Type-independent portion of concurrent_queue_iterator.
Definition at line 959 of file _concurrent_queue_impl.h.
Constructor & Destructor Documentation
tbb::internal::concurrent_queue_iterator_base_v3::concurrent_queue_iterator_base_v3 () inline protected
Default constructor.
Definition at line 976 of file _concurrent_queue_impl.h.
Referenced by initialize().
 : my_rep(NULL), my_item(NULL) {}
tbb::internal::concurrent_queue_iterator_base_v3::concurrent_queue_iterator_base_v3 (const concurrent_queue_iterator_base_v3 & i) inline protected
Copy constructor.
Definition at line 979 of file _concurrent_queue_impl.h.
References __TBB_EXPORTED_METHOD.
                                                                                     : my_rep(NULL), my_item(NULL) {
         assign(i);
     }
__TBB_EXPORTED_METHOD tbb::internal::concurrent_queue_iterator_base_v3::concurrent_queue_iterator_base_v3 (const concurrent_queue_base_v3 & queue) protected
Obsolete entry point for constructing iterator pointing to head of queue.
Does not work correctly for SSE types.
__TBB_EXPORTED_METHOD tbb::internal::concurrent_queue_iterator_base_v3::concurrent_queue_iterator_base_v3 (const concurrent_queue_base_v3 & queue, size_t offset_of_data) protected
Construct iterator pointing to head of queue.
tbb::internal::concurrent_queue_iterator_base_v3::~concurrent_queue_iterator_base_v3 () protected
Destructor.
Definition at line 666 of file concurrent_queue.cpp.
{
     //delete my_rep;
     cache_aligned_allocator<concurrent_queue_iterator_rep>().deallocate(my_rep, 1);
     my_rep = NULL;
 }
Member Function Documentation
void tbb::internal::concurrent_queue_iterator_base_v3::advance () protected
Advance iterator one step towards tail of queue.
Definition at line 647 of file concurrent_queue.cpp.
References __TBB_ASSERT, tbb::internal::concurrent_queue_rep::index(), tbb::internal::concurrent_queue_base_v3::items_per_page, tbb::internal::modulo_power_of_two(), tbb::internal::concurrent_queue_rep::n_queue, and tbb::internal::concurrent_queue_base_v3::page::next.
{
     __TBB_ASSERT( my_item, "attempt to increment iterator past end of queue" );
     size_t k = my_rep->head_counter;
     const concurrent_queue_base& queue = my_rep->my_queue;
 #if TBB_USE_ASSERT
     void* tmp;
     my_rep->get_item(tmp,k);
     __TBB_ASSERT( my_item==tmp, NULL );
 #endif /* TBB_USE_ASSERT */
     size_t i = modulo_power_of_two( k/concurrent_queue_rep::n_queue, queue.items_per_page );
     if( i==queue.items_per_page-1 ) {
         concurrent_queue_base::page*& root = my_rep->array[concurrent_queue_rep::index(k)];
         root = root->next;
     }
     // advance k
     my_rep->head_counter = ++k;
     if( !my_rep->get_item(my_item, k) ) advance();
 }
void tbb::internal::concurrent_queue_iterator_base_v3::assign (const concurrent_queue_iterator_base_v3 & i) protected
Assignment.
Definition at line 633 of file concurrent_queue.cpp.
References my_item, and my_rep.
{
     if( my_rep!=other.my_rep ) {
         if( my_rep ) {
             cache_aligned_allocator<concurrent_queue_iterator_rep>().deallocate(my_rep, 1);
             my_rep = NULL;
         }
         if( other.my_rep ) {
             my_rep = cache_aligned_allocator<concurrent_queue_iterator_rep>().allocate(1);
             new( my_rep ) concurrent_queue_iterator_rep( *other.my_rep );
         }
     }
     my_item = other.my_item;
 }
void tbb::internal::concurrent_queue_iterator_base_v3::initialize (const concurrent_queue_base_v3 & queue, size_t offset_of_data) private
Definition at line 618 of file concurrent_queue.cpp.
References concurrent_queue_iterator_base_v3(), and tbb::internal::concurrent_queue_iterator_rep::head_counter.
{
     my_rep = cache_aligned_allocator<concurrent_queue_iterator_rep>().allocate(1);
     new( my_rep ) concurrent_queue_iterator_rep(queue,offset_of_last);
     size_t k = my_rep->head_counter;
     if( !my_rep->get_item(my_item, k) ) advance();
 }
Friends And Related Function Documentation
template<typename C , typename T , typename U > bool operator!= (const concurrent_queue_iterator< C, T > & i, const concurrent_queue_iterator< C, U > & j) friend
Definition at line 1065 of file _concurrent_queue_impl.h.
{
     return i.my_item!=j.my_item;
 }
template<typename C , typename T , typename U > bool operator== (const concurrent_queue_iterator< C, T > & i, const concurrent_queue_iterator< C, U > & j) friend
Definition at line 1060 of file _concurrent_queue_impl.h.
{
     return i.my_item==j.my_item;
 }
Member Data Documentation
void* tbb::internal::concurrent_queue_iterator_base_v3::my_item protected
Pointer to current item.
Definition at line 973 of file _concurrent_queue_impl.h.
Referenced by assign(), tbb::internal::operator!=(), and tbb::internal::operator==().
concurrent_queue_iterator_rep* tbb::internal::concurrent_queue_iterator_base_v3::my_rep private
concurrent_queue over which we are iterating.
NULL if one past last element in queue.
Definition at line 962 of file _concurrent_queue_impl.h.
Referenced by assign().
The documentation for this class was generated from the following files:
_concurrent_queue_impl.h
concurrent_queue.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.