Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::cpu_ctl_env Class Reference
tbb::internal::cpu_ctl_env Class Reference
#include <gcc_ia32_common.h>
Public Member Functions
bool operator!= (const cpu_ctl_env &ctl) const
void get_env ()
void set_env () const
bool operator!= (const cpu_ctl_env &ctl) const
void get_env ()
void set_env () const
bool operator!= (const cpu_ctl_env &ctl) const
void get_env ()
void set_env () const
cpu_ctl_env ()
~cpu_ctl_env ()
cpu_ctl_env (const cpu_ctl_env &src)
cpu_ctl_env & operator= (const cpu_ctl_env &src)
bool operator!= (const cpu_ctl_env &ctl) const
void get_env ()
const cpu_ctl_env & set_env () const
Private Attributes
int mxcsr
short x87cw
unsigned int my_ctl
fenv_t * my_fenv_ptr
Static Private Attributes
static const int MXCSR_CONTROL_MASK = ~0x3f
Detailed Description
Definition at line 74 of file gcc_ia32_common.h.
Constructor & Destructor Documentation
tbb::internal::cpu_ctl_env::cpu_ctl_env () inline
Definition at line 411 of file scheduler_common.h.
 : my_fenv_ptr(NULL) {}
tbb::internal::cpu_ctl_env::~cpu_ctl_env () inline
Definition at line 412 of file scheduler_common.h.
References tbb::internal::NFS_Free().
                    {
         if ( my_fenv_ptr )
             tbb::internal::NFS_Free( (void*)my_fenv_ptr );
     }
tbb::internal::cpu_ctl_env::cpu_ctl_env (const cpu_ctl_env & src) inline
Definition at line 422 of file scheduler_common.h.
                                           : my_fenv_ptr(NULL) {
         *this = src;
     }
Member Function Documentation
void tbb::internal::cpu_ctl_env::get_env () inline
Definition at line 81 of file gcc_ia32_common.h.
References mxcsr, and x87cw.
Referenced by tbb::internal::generic_scheduler::free_task().
                    {
     #if __TBB_ICC_12_0_INL_ASM_FSTCW_BROKEN
         cpu_ctl_env loc_ctl;
         __asm__ __volatile__ (
                 "stmxcsr %0\n\t"
                 "fstcw %1"
                 : "=m"(loc_ctl.mxcsr), "=m"(loc_ctl.x87cw)
         );
         *this = loc_ctl;
     #else
         __asm__ __volatile__ (
                 "stmxcsr %0\n\t"
                 "fstcw %1"
                 : "=m"(mxcsr), "=m"(x87cw)
         );
     #endif
         mxcsr &= MXCSR_CONTROL_MASK;
     }
void tbb::internal::cpu_ctl_env::get_env () inline
Definition at line 125 of file msvc_armv7.h.
 { my_ctl = _control87(0, 0); }
void tbb::internal::cpu_ctl_env::get_env () inline
Definition at line 238 of file msvc_ia32_common.h.
References __TBB_get_cpu_ctl_env().
                    {
         __TBB_get_cpu_ctl_env( this );
         mxcsr &= MXCSR_CONTROL_MASK;
     }
void tbb::internal::cpu_ctl_env::get_env () inline
Definition at line 437 of file scheduler_common.h.
References tbb::internal::NFS_Allocate().
                     {
         if ( !my_fenv_ptr )
             my_fenv_ptr = (fenv_t*)tbb::internal::NFS_Allocate(1, sizeof(fenv_t), NULL);
         fegetenv( my_fenv_ptr );
     }
bool tbb::internal::cpu_ctl_env::operator!= (const cpu_ctl_env & ctl) const inline
Definition at line 80 of file gcc_ia32_common.h.
References mxcsr, and x87cw.
 { return mxcsr != ctl.mxcsr || x87cw != ctl.x87cw; }
bool tbb::internal::cpu_ctl_env::operator!= (const cpu_ctl_env & ctl) const inline
Definition at line 124 of file msvc_armv7.h.
References my_ctl.
 { return my_ctl != ctl.my_ctl; }
bool tbb::internal::cpu_ctl_env::operator!= (const cpu_ctl_env & ctl) const inline
Definition at line 237 of file msvc_ia32_common.h.
 { return mxcsr != ctl.mxcsr || x87cw != ctl.x87cw; }
bool tbb::internal::cpu_ctl_env::operator!= (const cpu_ctl_env & ctl) const inline
Definition at line 432 of file scheduler_common.h.
References __TBB_ASSERT, and my_fenv_ptr.
{
         __TBB_ASSERT( my_fenv_ptr, "cpu_ctl_env is not initialized." );
         __TBB_ASSERT( ctl.my_fenv_ptr, "cpu_ctl_env is not initialized." );
         return memcmp( (void*)my_fenv_ptr, (void*)ctl.my_fenv_ptr, sizeof(fenv_t) );
     }
cpu_ctl_env& tbb::internal::cpu_ctl_env::operator= (const cpu_ctl_env & src) inline
Definition at line 425 of file scheduler_common.h.
References __TBB_ASSERT, my_fenv_ptr, and tbb::internal::NFS_Allocate().
{
         __TBB_ASSERT( src.my_fenv_ptr, NULL );
         if ( !my_fenv_ptr )
             my_fenv_ptr = (fenv_t*)tbb::internal::NFS_Allocate(1, sizeof(fenv_t), NULL);
         *my_fenv_ptr = *src.my_fenv_ptr;
         return *this;
     }
void tbb::internal::cpu_ctl_env::set_env () const inline
Definition at line 99 of file gcc_ia32_common.h.
Referenced by tbb::internal::generic_scheduler::free_task().
{
         __asm__ __volatile__ (
                 "ldmxcsr %0\n\t"
                 "fldcw %1"
                 : : "m"(mxcsr), "m"(x87cw)
         );
     }
void tbb::internal::cpu_ctl_env::set_env () const inline
Definition at line 126 of file msvc_armv7.h.
 { _control87( my_ctl, ~0U ); }
void tbb::internal::cpu_ctl_env::set_env () const inline
Definition at line 242 of file msvc_ia32_common.h.
References __declspec(), and __TBB_set_cpu_ctl_env().
 { __TBB_set_cpu_ctl_env( this ); }
const cpu_ctl_env& tbb::internal::cpu_ctl_env::set_env () const inline
Definition at line 442 of file scheduler_common.h.
References __TBB_ASSERT.
{
         __TBB_ASSERT( my_fenv_ptr, "cpu_ctl_env is not initialized." );
         fesetenv( my_fenv_ptr );
         return *this;
     }
Member Data Documentation
int tbb::internal::cpu_ctl_env::mxcsr private
Definition at line 76 of file gcc_ia32_common.h.
Referenced by get_env(), and operator!=().
static const int tbb::internal::cpu_ctl_env::MXCSR_CONTROL_MASK = ~0x3f static private
Definition at line 78 of file gcc_ia32_common.h.
unsigned int tbb::internal::cpu_ctl_env::my_ctl private
Definition at line 122 of file msvc_armv7.h.
Referenced by operator!=().
fenv_t* tbb::internal::cpu_ctl_env::my_fenv_ptr private
Definition at line 409 of file scheduler_common.h.
Referenced by operator!=(), and operator=().
short tbb::internal::cpu_ctl_env::x87cw private
Definition at line 77 of file gcc_ia32_common.h.
Referenced by get_env(), and operator!=().
The documentation for this class was generated from the following files:
gcc_ia32_common.h
msvc_armv7.h
msvc_ia32_common.h
scheduler_common.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.