Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::control_storage Class Reference
tbb::internal::control_storage Class Reference abstract
Protected Member Functions
virtual size_t default_value () const =0
virtual void apply_active () const
virtual bool is_first_arg_preferred (size_t a, size_t b) const
virtual size_t active_value () const
Protected Attributes
size_t my_active_value
atomic< global_control * > my_head
spin_mutex my_list_mutex
Friends
class tbb::interface9::global_control
Detailed Description
Definition at line 429 of file tbb_main.cpp.
Member Function Documentation
virtual size_t tbb::internal::control_storage::active_value () const inline protected virtual
Reimplemented in tbb::internal::allowed_parallelism_control.
Definition at line 441 of file tbb_main.cpp.
Referenced by tbb::interface9::global_control::active_value().
{
         return my_head? my_active_value : default_value();
     }
virtual void tbb::internal::control_storage::apply_active () const inline protected virtual
Reimplemented in tbb::internal::stack_size_control, and tbb::internal::allowed_parallelism_control.
Definition at line 437 of file tbb_main.cpp.
Referenced by tbb::interface9::global_control::internal_create(), and tbb::interface9::global_control::internal_destroy().
 {}
virtual size_t tbb::internal::control_storage::default_value () const protected pure virtual
Implemented in tbb::internal::stack_size_control, and tbb::internal::allowed_parallelism_control.
Referenced by tbb::interface9::global_control::internal_destroy().
virtual bool tbb::internal::control_storage::is_first_arg_preferred (size_t a, size_t b) const inline protected virtual
Reimplemented in tbb::internal::allowed_parallelism_control.
Definition at line 438 of file tbb_main.cpp.
Referenced by tbb::interface9::global_control::internal_create(), and tbb::interface9::global_control::internal_destroy().
{
         return a>b; // prefer max by default
     }
Friends And Related Function Documentation
friend class tbb::interface9::global_control friend
Definition at line 430 of file tbb_main.cpp.
Member Data Documentation
size_t tbb::internal::control_storage::my_active_value protected
Definition at line 432 of file tbb_main.cpp.
Referenced by tbb::interface9::global_control::internal_create(), and tbb::interface9::global_control::internal_destroy().
atomic<global_control*> tbb::internal::control_storage::my_head protected
Definition at line 433 of file tbb_main.cpp.
Referenced by tbb::interface9::global_control::internal_create(), and tbb::interface9::global_control::internal_destroy().
spin_mutex tbb::internal::control_storage::my_list_mutex protected
Definition at line 434 of file tbb_main.cpp.
Referenced by tbb::interface9::global_control::internal_create(), and tbb::interface9::global_control::internal_destroy().
The documentation for this class was generated from the following file:
tbb_main.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.