Intel(R) Threading Building Blocks Doxygen Documentation: tbb::concurrent_bounded_queue< T, A > Class Template Reference
tbb::concurrent_bounded_queue< T, A > Class Template Reference
Containers
A high-performance thread-safe blocking concurrent bounded queue.
#include <concurrent_queue.h>
Classes
class destroyer
Class used to ensure exception-safety of method "pop".
Public Types
typedef T value_type
Element type in the queue.
typedef A allocator_type
Allocator type.
typedef T & reference
Reference type.
typedef const T & const_reference
Const reference type.
typedef std::ptrdiff_t size_type
Integral type for representing size of the queue.
typedef std::ptrdiff_t difference_type
Difference type for iterator.
typedef internal::concurrent_queue_iterator< concurrent_bounded_queue, T > iterator
typedef internal::concurrent_queue_iterator< concurrent_bounded_queue, const T > const_iterator
Public Member Functions
concurrent_bounded_queue (const allocator_type &a=allocator_type())
Construct empty queue.
concurrent_bounded_queue (const concurrent_bounded_queue &src, const allocator_type &a=allocator_type())
Copy constructor.
concurrent_bounded_queue (concurrent_bounded_queue &&src)
Move constructors.
concurrent_bounded_queue (concurrent_bounded_queue &&src, const allocator_type &a)
template<typename InputIterator >
concurrent_bounded_queue (InputIterator begin, InputIterator end, const allocator_type &a=allocator_type())
[begin,end) constructor
~concurrent_bounded_queue ()
Destroy queue.
void push (const T &source)
Enqueue an item at tail of queue.
void push (T &&source)
Move an item at tail of queue.
template<typename... Arguments>
void emplace (Arguments &&...args)
void pop (T &destination)
Dequeue item from head of queue.
bool try_push (const T &source)
Enqueue an item at tail of queue if queue is not already full.
bool try_push (T &&source)
Move an item at tail of queue if queue is not already full.
template<typename... Arguments>
bool try_emplace (Arguments &&...args)
bool try_pop (T &destination)
Attempt to dequeue an item from head of queue.
size_type size () const
Return number of pushes minus number of pops.
bool empty () const
Equivalent to size()<=0.
size_type capacity () const
Maximum number of allowed elements.
void set_capacity (size_type new_capacity)
Set the capacity.
allocator_type get_allocator () const
return allocator object
void clear ()
clear the queue. not thread-safe.
iterator unsafe_begin ()
iterator unsafe_end ()
const_iterator unsafe_begin () const
const_iterator unsafe_end () const
Private Types
typedef tbb::internal::allocator_rebind< A, char >::type page_allocator_type
typedef concurrent_queue_base_v3::padded_page< T > padded_page
typedef concurrent_queue_base_v3::copy_specifics copy_specifics
Private Member Functions
T & get_ref (page &p, size_t index)
virtual void copy_item (page &dst, size_t index, const void *src) __TBB_override
virtual void move_item (page &dst, size_t index, const void *src) __TBB_override
virtual void copy_page_item (page &dst, size_t dindex, const page &src, size_t sindex) __TBB_override
virtual void move_page_item (page &dst, size_t dindex, const page &src, size_t sindex) __TBB_override
virtual void assign_and_destroy_item (void *dst, page &src, size_t index) __TBB_override
virtual page * allocate_page () __TBB_override
custom allocator
virtual void deallocate_page (page *p) __TBB_override
custom de-allocator
Private Attributes
page_allocator_type my_allocator
Allocator type.
Friends
template<typename Container , typename Value >
class internal::concurrent_queue_iterator
Additional Inherited Members
Protected Types inherited from tbb::internal::concurrent_queue_base_v3
enum copy_specifics { copy, move }
Protected Member Functions inherited from tbb::internal::concurrent_queue_base_v8
concurrent_queue_base_v8 (size_t item_sz)
void __TBB_EXPORTED_METHOD move_content (concurrent_queue_base_v8 &src)
move items
bool __TBB_EXPORTED_METHOD internal_push_move_if_not_full (const void *src)
Attempt to enqueue item onto queue using move operation.
void __TBB_EXPORTED_METHOD internal_push_move (const void *src)
Enqueue item at tail of queue using move operation.
Protected Member Functions inherited from tbb::internal::concurrent_queue_base_v3
__TBB_EXPORTED_METHOD concurrent_queue_base_v3 (size_t item_size)
virtual __TBB_EXPORTED_METHOD ~concurrent_queue_base_v3 ()
void __TBB_EXPORTED_METHOD internal_push (const void *src)
Enqueue item at tail of queue using copy operation.
void __TBB_EXPORTED_METHOD internal_pop (void *dst)
Dequeue item from head of queue.
void __TBB_EXPORTED_METHOD internal_abort ()
Abort all pending queue operations.
bool __TBB_EXPORTED_METHOD internal_push_if_not_full (const void *src)
Attempt to enqueue item onto queue using copy operation.
bool __TBB_EXPORTED_METHOD internal_pop_if_present (void *dst)
Attempt to dequeue item from queue.
ptrdiff_t __TBB_EXPORTED_METHOD internal_size () const
Get size of queue.
bool __TBB_EXPORTED_METHOD internal_empty () const
Check if the queue is emtpy.
void __TBB_EXPORTED_METHOD internal_set_capacity (ptrdiff_t capacity, size_t element_size)
Set the queue capacity.
void __TBB_EXPORTED_METHOD internal_finish_clear ()
free any remaining pages
void __TBB_EXPORTED_METHOD internal_throw_exception () const
throw an exception
void __TBB_EXPORTED_METHOD assign (const concurrent_queue_base_v3 &src)
copy internal representation
void internal_swap (concurrent_queue_base_v3 &src)
swap queues
void internal_insert_item (const void *src, copy_specifics op_type)
Enqueues item at tail of queue using specified operation (copy or move)
bool internal_insert_if_not_full (const void *src, copy_specifics op_type)
Attempts to enqueue at tail of queue using specified operation (copy or move)
void internal_assign (const concurrent_queue_base_v3 &src, copy_specifics op_type)
Assigns one queue to another using specified operation (copy or move)
Protected Attributes inherited from tbb::internal::concurrent_queue_base_v3
ptrdiff_t my_capacity
Capacity of the queue.
size_t items_per_page
Always a power of 2.
size_t item_size
Size of an item.
Detailed Description
template<typename T, class A = cache_aligned_allocator<T>>
class tbb::concurrent_bounded_queue< T, A >
A high-performance thread-safe blocking concurrent bounded queue.
This is the pre-PPL TBB concurrent queue which supports boundedness and blocking semantics. Note that method names agree with the PPL-style concurrent queue. Multiple threads may each push and pop concurrently. Assignment construction is not allowed.
Definition at line 211 of file concurrent_queue.h.
Member Typedef Documentation
template<typename T , class A = cache_aligned_allocator<T>> typedef A tbb::concurrent_bounded_queue< T, A >::allocator_type
Allocator type.
Definition at line 286 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef internal::concurrent_queue_iterator<concurrent_bounded_queue,const T> tbb::concurrent_bounded_queue< T, A >::const_iterator
Definition at line 440 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef const T& tbb::concurrent_bounded_queue< T, A >::const_reference
Const reference type.
Definition at line 292 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef concurrent_queue_base_v3::copy_specifics tbb::concurrent_bounded_queue< T, A >::copy_specifics private
Definition at line 219 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef std::ptrdiff_t tbb::concurrent_bounded_queue< T, A >::difference_type
Difference type for iterator.
Definition at line 300 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef internal::concurrent_queue_iterator<concurrent_bounded_queue,T> tbb::concurrent_bounded_queue< T, A >::iterator
Definition at line 439 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef concurrent_queue_base_v3::padded_page<T> tbb::concurrent_bounded_queue< T, A >::padded_page private
Definition at line 218 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef tbb::internal::allocator_rebind<A, char>::type tbb::concurrent_bounded_queue< T, A >::page_allocator_type private
Definition at line 213 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef T& tbb::concurrent_bounded_queue< T, A >::reference
Reference type.
Definition at line 289 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef std::ptrdiff_t tbb::concurrent_bounded_queue< T, A >::size_type
Integral type for representing size of the queue.
Note that the size_type is a signed integral type. This is because the size can be negative if there are pending pops without corresponding pushes.
Definition at line 297 of file concurrent_queue.h.
template<typename T , class A = cache_aligned_allocator<T>> typedef T tbb::concurrent_bounded_queue< T, A >::value_type
Element type in the queue.
Definition at line 283 of file concurrent_queue.h.
Constructor & Destructor Documentation
template<typename T , class A = cache_aligned_allocator<T>> tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue (const allocator_type & a = allocator_type()) inline explicit
Construct empty queue.
Definition at line 303 of file concurrent_queue.h.
                                                                                   :
         concurrent_queue_base_v8( sizeof(T) ), my_allocator( a )
     {
     }
template<typename T , class A = cache_aligned_allocator<T>> tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue (const concurrent_bounded_queue< T, A > & src, const allocator_type & a = allocator_type()) inline
Copy constructor.
Definition at line 309 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::assign(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_swap(), tbb::move(), tbb::strict_ppl::concurrent_queue< T, A >::my_allocator, and tbb::concurrent_bounded_queue< T, A >::my_allocator.
         : concurrent_queue_base_v8( sizeof(T) ), my_allocator( a )
     {
         assign( src );
     }
template<typename T , class A = cache_aligned_allocator<T>> tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue (concurrent_bounded_queue< T, A > && src) inline
Move constructors.
Definition at line 317 of file concurrent_queue.h.
         : concurrent_queue_base_v8( sizeof(T) ), my_allocator( std::move(src.my_allocator) )
     {
         internal_swap( src );
     }
template<typename T , class A = cache_aligned_allocator<T>> tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue (concurrent_bounded_queue< T, A > && src, const allocator_type & a) inline
Definition at line 323 of file concurrent_queue.h.
References tbb::concurrent_bounded_queue< T, A >::clear(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_swap(), and tbb::concurrent_bounded_queue< T, A >::my_allocator.
         : concurrent_queue_base_v8( sizeof(T) ), my_allocator( a )
     {
         // checking that memory allocated by one instance of allocator can be deallocated
         // with another
         if( my_allocator == src.my_allocator) {
             this->internal_swap( src );
         } else {
             // allocators are different => performing per-element move
             this->move_content( src );
             src.clear();
         }
     }
template<typename T , class A = cache_aligned_allocator<T>> template<typename InputIterator > tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue (InputIterator begin, InputIterator end, const allocator_type & a = allocator_type()) inline
[begin,end) constructor
Definition at line 340 of file concurrent_queue.h.
References begin, and end.
         : concurrent_queue_base_v8( sizeof(T) ), my_allocator( a )
     {
         for( ; begin != end; ++begin )
             internal_push_if_not_full(&*begin);
     }
template<typename T , class A > tbb::concurrent_bounded_queue< T, A >::~concurrent_bounded_queue ()
Destroy queue.
Definition at line 462 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::clear(), and tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_finish_clear().
{
     clear();
     internal_finish_clear();
 }
Member Function Documentation
template<typename T , class A = cache_aligned_allocator<T>> virtual page* tbb::concurrent_bounded_queue< T, A >::allocate_page () inline private virtual
custom allocator
Implements tbb::internal::concurrent_queue_base_v3.
Definition at line 268 of file concurrent_queue.h.
References tbb::internal::eid_bad_alloc, p, and tbb::internal::throw_exception().
{
         size_t n = sizeof(padded_page) + (items_per_page-1)*sizeof(T);
         page *p = reinterpret_cast<page*>(my_allocator.allocate( n ));
         if( !p )
             internal::throw_exception(internal::eid_bad_alloc);
         return p;
     }
template<typename T , class A = cache_aligned_allocator<T>> virtual void tbb::concurrent_bounded_queue< T, A >::assign_and_destroy_item (void * dst, page & src, size_t index) inline private virtual
Implements tbb::internal::concurrent_queue_base_v3.
Definition at line 262 of file concurrent_queue.h.
References d, and tbb::move().
{
         T& from = get_ref(src,index);
         destroyer d(from);
         *static_cast<T*>(dst) = tbb::internal::move( from );
     }
template<typename T , class A = cache_aligned_allocator<T>> size_type tbb::concurrent_bounded_queue< T, A >::capacity () const inline
Maximum number of allowed elements.
Definition at line 422 of file concurrent_queue.h.
{
         return my_capacity;
     }
template<typename T , class A > void tbb::concurrent_bounded_queue< T, A >::clear ()
clear the queue. not thread-safe.
Definition at line 468 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::try_pop(), and value.
Referenced by tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue().
{
     T value;
     while( try_pop(value) ) /*noop*/;
 }
template<typename T , class A = cache_aligned_allocator<T>> virtual void tbb::concurrent_bounded_queue< T, A >::copy_item (page & dst, size_t index, const void * src) inline private virtual
Implements tbb::internal::concurrent_queue_base_v3.
Definition at line 234 of file concurrent_queue.h.
{
         new( &get_ref(dst,index) ) T(*static_cast<const T*>(src));
     }
template<typename T , class A = cache_aligned_allocator<T>> virtual void tbb::concurrent_bounded_queue< T, A >::copy_page_item (page & dst, size_t dindex, const page & src, size_t sindex) inline private virtual
Implements tbb::internal::concurrent_queue_base_v3.
Definition at line 248 of file concurrent_queue.h.
{
         new( &get_ref(dst,dindex) ) T( get_ref( const_cast<page&>(src), sindex ) );
     }
template<typename T , class A = cache_aligned_allocator<T>> virtual void tbb::concurrent_bounded_queue< T, A >::deallocate_page (page * p) inline private virtual
custom de-allocator
Implements tbb::internal::concurrent_queue_base_v3.
Definition at line 276 of file concurrent_queue.h.
References p.
{
         size_t n = sizeof(padded_page) + (items_per_page-1)*sizeof(T);
         my_allocator.deallocate( reinterpret_cast<char*>(p), n );
     }
template<typename T , class A = cache_aligned_allocator<T>> template<typename... Arguments> void tbb::concurrent_bounded_queue< T, A >::emplace (Arguments &&... args) inline
Definition at line 364 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::push().
{
         push( T(std::forward<Arguments>( args )...) );
     }
template<typename T , class A = cache_aligned_allocator<T>> bool tbb::concurrent_bounded_queue< T, A >::empty () const inline
Equivalent to size()<=0.
Definition at line 419 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_empty().
 {return internal_empty();}
template<typename T , class A = cache_aligned_allocator<T>> allocator_type tbb::concurrent_bounded_queue< T, A >::get_allocator () const inline
return allocator object
Definition at line 434 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::clear(), and tbb::strict_ppl::concurrent_queue< T, A >::my_allocator.
 { return this->my_allocator; }
template<typename T , class A = cache_aligned_allocator<T>> T& tbb::concurrent_bounded_queue< T, A >::get_ref (page & p, size_t index) inline private
Definition at line 229 of file concurrent_queue.h.
References __TBB_ASSERT, and tbb::internal::last().
{
         __TBB_ASSERT( index<items_per_page, NULL );
         return (&static_cast<padded_page*>(static_cast<void*>(&p))->last)[index];
     }
template<typename T , class A = cache_aligned_allocator<T>> virtual void tbb::concurrent_bounded_queue< T, A >::move_item (page & dst, size_t index, const void * src) inline private virtual
Implements tbb::internal::concurrent_queue_base_v8.
Definition at line 239 of file concurrent_queue.h.
References __TBB_ASSERT, __TBB_override, and tbb::move().
{
         new( &get_ref(dst,index) ) T( std::move(*static_cast<T*>(const_cast<void*>(src))) );
     }
template<typename T , class A = cache_aligned_allocator<T>> virtual void tbb::concurrent_bounded_queue< T, A >::move_page_item (page & dst, size_t dindex, const page & src, size_t sindex) inline private virtual
Implements tbb::internal::concurrent_queue_base_v8.
Definition at line 253 of file concurrent_queue.h.
References __TBB_ASSERT, __TBB_override, and tbb::move().
{
         new( &get_ref(dst,dindex) ) T( std::move(get_ref( const_cast<page&>(src), sindex )) );
     }
template<typename T , class A = cache_aligned_allocator<T>> void tbb::concurrent_bounded_queue< T, A >::pop (T & destination) inline
Dequeue item from head of queue.
Block until an item becomes available, and then dequeue it.
Definition at line 372 of file concurrent_queue.h.
{
         internal_pop( &destination );
     }
template<typename T , class A = cache_aligned_allocator<T>> void tbb::concurrent_bounded_queue< T, A >::push (const T & source) inline
Enqueue an item at tail of queue.
Definition at line 352 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_push(), and tbb::strict_ppl::concurrent_queue< T, A >::push().
{
         internal_push( &source );
     }
template<typename T , class A = cache_aligned_allocator<T>> void tbb::concurrent_bounded_queue< T, A >::push (T && source) inline
Move an item at tail of queue.
Definition at line 358 of file concurrent_queue.h.
{
         internal_push_move( &source );
     }
template<typename T , class A = cache_aligned_allocator<T>> void tbb::concurrent_bounded_queue< T, A >::set_capacity (size_type new_capacity) inline
Set the capacity.
Setting the capacity to 0 causes subsequent try_push operations to always fail, and subsequent push operations to block forever.
Definition at line 429 of file concurrent_queue.h.
{
         internal_set_capacity( new_capacity, sizeof(T) );
     }
template<typename T , class A = cache_aligned_allocator<T>> size_type tbb::concurrent_bounded_queue< T, A >::size () const inline
Return number of pushes minus number of pops.
Note that the result can be negative if there are pops waiting for the corresponding pushes. The result can also exceed capacity() if there are push operations in flight.
Definition at line 416 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_size().
 {return internal_size();}
template<typename T , class A = cache_aligned_allocator<T>> template<typename... Arguments> bool tbb::concurrent_bounded_queue< T, A >::try_emplace (Arguments &&... args) inline
Definition at line 399 of file concurrent_queue.h.
{
         return try_push( T(std::forward<Arguments>( args )...) );
     }
template<typename T , class A = cache_aligned_allocator<T>> bool tbb::concurrent_bounded_queue< T, A >::try_pop (T & destination) inline
Attempt to dequeue an item from head of queue.
Does not wait for item to become available. Returns true if successful; false otherwise.
Definition at line 408 of file concurrent_queue.h.
{
         return internal_pop_if_present( &destination );
     }
template<typename T , class A = cache_aligned_allocator<T>> bool tbb::concurrent_bounded_queue< T, A >::try_push (const T & source) inline
Enqueue an item at tail of queue if queue is not already full.
Does not wait for queue to become not full. Returns true if item is pushed; false if queue was already full.
Definition at line 386 of file concurrent_queue.h.
{
         return internal_push_if_not_full( &source );
     }
template<typename T , class A = cache_aligned_allocator<T>> bool tbb::concurrent_bounded_queue< T, A >::try_push (T && source) inline
Move an item at tail of queue if queue is not already full.
Does not wait for queue to become not full. Returns true if item is pushed; false if queue was already full.
Definition at line 394 of file concurrent_queue.h.
{
         return internal_push_move_if_not_full( &source );
     }
template<typename T , class A = cache_aligned_allocator<T>> iterator tbb::concurrent_bounded_queue< T, A >::unsafe_begin () inline
Definition at line 445 of file concurrent_queue.h.
 {return iterator(*this);}
template<typename T , class A = cache_aligned_allocator<T>> const_iterator tbb::concurrent_bounded_queue< T, A >::unsafe_begin () const inline
Definition at line 447 of file concurrent_queue.h.
 {return const_iterator(*this);}
template<typename T , class A = cache_aligned_allocator<T>> iterator tbb::concurrent_bounded_queue< T, A >::unsafe_end () inline
Definition at line 446 of file concurrent_queue.h.
 {return iterator();}
template<typename T , class A = cache_aligned_allocator<T>> const_iterator tbb::concurrent_bounded_queue< T, A >::unsafe_end () const inline
Definition at line 448 of file concurrent_queue.h.
 {return const_iterator();}
Friends And Related Function Documentation
template<typename T , class A = cache_aligned_allocator<T>> template<typename Container , typename Value > friend class internal::concurrent_queue_iterator friend
Definition at line 212 of file concurrent_queue.h.
Member Data Documentation
template<typename T , class A = cache_aligned_allocator<T>> page_allocator_type tbb::concurrent_bounded_queue< T, A >::my_allocator private
Allocator type.
Definition at line 216 of file concurrent_queue.h.
Referenced by tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue().
The documentation for this class was generated from the following file:
concurrent_queue.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.