Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::binary_semaphore Class Reference
tbb::internal::binary_semaphore Class Reference
binary_semaphore for concurrent monitor
#include <semaphore.h>
Public Member Functions
binary_semaphore ()
ctor
~binary_semaphore ()
dtor
void P ()
wait/acquire
void V ()
post/release
Private Attributes
sem_t my_sem
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
binary_semaphore for concurrent monitor
Definition at line 226 of file semaphore.h.
Constructor & Destructor Documentation
tbb::internal::binary_semaphore::binary_semaphore () inline
ctor
Definition at line 229 of file semaphore.h.
References __TBB_ASSERT_EX.
{
         int ret = sem_init( &my_sem, /*shared among threads*/ 0, 0 );
         __TBB_ASSERT_EX( !ret, NULL );
     }
tbb::internal::binary_semaphore::~binary_semaphore () inline
dtor
Definition at line 234 of file semaphore.h.
References __TBB_ASSERT_EX.
{
         int ret = sem_destroy( &my_sem );
         __TBB_ASSERT_EX( !ret, NULL );
     }
Member Function Documentation
void tbb::internal::binary_semaphore::P () inline
wait/acquire
Definition at line 239 of file semaphore.h.
References __TBB_ASSERT.
Referenced by tbb::internal::concurrent_monitor::commit_wait(), tbb::interface7::internal::task_arena_base::internal_wait(), and tbb::internal::concurrent_monitor::prepare_wait().
              {
         while( sem_wait( &my_sem )!=0 )
             __TBB_ASSERT( errno==EINTR, NULL );
     }
void tbb::internal::binary_semaphore::V () inline
post/release
Definition at line 244 of file semaphore.h.
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), tbb::interface7::internal::wait_task::execute(), tbb::internal::concurrent_monitor::notify_all_relaxed(), and tbb::internal::concurrent_monitor::notify_one_relaxed().
 { sem_post( &my_sem ); }
Member Data Documentation
sem_t tbb::internal::binary_semaphore::my_sem private
Definition at line 246 of file semaphore.h.
The documentation for this class was generated from the following file:
semaphore.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.