Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor Class Reference
tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor Class Reference
Combines data access, locking, and garbage collection.
#include <concurrent_hash_map.h>
Public Types
typedef const concurrent_hash_map::value_type value_type
Type of value.
Public Member Functions
bool empty () const
True if result is empty.
void release ()
Set to null.
const_reference operator* () const
Return reference to associated value in hash table.
const_pointer operator-> () const
Return pointer to associated value in hash table.
const_accessor ()
Create empty result.
~const_accessor ()
Destroy result after releasing the underlying reference.
Protected Member Functions
bool is_writer ()
Protected Attributes
node * my_node
hashcode_t my_hash
Friends
class concurrent_hash_map< Key, T, HashCompare, Allocator >
class accessor
Detailed Description
template<typename Key, typename T, typename HashCompare, typename Allocator>
class tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor
Combines data access, locking, and garbage collection.
Definition at line 699 of file concurrent_hash_map.h.
Member Typedef Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> typedef const concurrent_hash_map::value_type tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::value_type
Type of value.
Definition at line 704 of file concurrent_hash_map.h.
Constructor & Destructor Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::const_accessor () inline
Create empty result.
Definition at line 729 of file concurrent_hash_map.h.
 : my_node(NULL) {}
template<typename Key, typename T, typename HashCompare, typename Allocator> tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::~const_accessor () inline
Destroy result after releasing the underlying reference.
Definition at line 732 of file concurrent_hash_map.h.
References tbb::interface5::internal::hash_map_iterator< Container, Value >::my_node.
{
             my_node = NULL; // scoped lock's release() is called in its destructor
         }
Member Function Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> bool tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::empty () const inline
True if result is empty.
Definition at line 707 of file concurrent_hash_map.h.
References tbb::interface5::internal::hash_map_iterator< Container, Value >::my_node.
 { return !my_node; }
template<typename Key, typename T, typename HashCompare, typename Allocator> bool tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::is_writer () inline protected
Definition at line 736 of file concurrent_hash_map.h.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::exclude().
 { return node::scoped_t::is_writer; }
template<typename Key, typename T, typename HashCompare, typename Allocator> const_reference tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::operator* () const inline
Return reference to associated value in hash table.
Definition at line 718 of file concurrent_hash_map.h.
References __TBB_ASSERT, and tbb::interface5::internal::hash_map_iterator< Container, Value >::my_node.
{
             __TBB_ASSERT( my_node, "attempt to dereference empty accessor" );
             return my_node->item;
         }
template<typename Key, typename T, typename HashCompare, typename Allocator> const_pointer tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::operator-> () const inline
Return pointer to associated value in hash table.
Definition at line 724 of file concurrent_hash_map.h.
References tbb::interface5::internal::hash_map_iterator< Container, Value >::operator*().
{
             return &operator*();
         }
template<typename Key, typename T, typename HashCompare, typename Allocator> void tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::release () inline
Set to null.
Definition at line 710 of file concurrent_hash_map.h.
References tbb::interface5::internal::hash_map_iterator< Container, Value >::my_node, and tbb::release.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::exclude(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::find(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::generic_emplace(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::generic_move_insert(), and tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::insert().
{
             if( my_node ) {
                 node::scoped_t::release();
                 my_node = 0;
             }
         }
Friends And Related Function Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> friend class accessor friend
Definition at line 701 of file concurrent_hash_map.h.
template<typename Key, typename T, typename HashCompare, typename Allocator> friend class concurrent_hash_map< Key, T, HashCompare, Allocator > friend
Definition at line 700 of file concurrent_hash_map.h.
Member Data Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> hashcode_t tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::my_hash protected
Definition at line 738 of file concurrent_hash_map.h.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::exclude(), and tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::lookup().
template<typename Key, typename T, typename HashCompare, typename Allocator> node* tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::my_node protected
Definition at line 737 of file concurrent_hash_map.h.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::exclude(), and tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::lookup().
The documentation for this class was generated from the following file:
concurrent_hash_map.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.