Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > > Class Template Reference
tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > > Class Template Reference
#include <flow_graph.h>
Public Types
typedef tbb::flow::tuple< sender< OutputTypes > &... > output_ports_type
Public Member Functions
composite_node (graph &g)
template<typename T >
void set_external_ports (T &&output_ports_tuple)
template<typename... NodeTypes>
void add_visible_nodes (const NodeTypes &...n)
template<typename... NodeTypes>
void add_nodes (const NodeTypes &...n)
output_ports_type & output_ports ()
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Protected Member Functions
void reset_node (reset_flags) __TBB_override
Private Attributes
std::unique_ptr< output_ports_type > my_output_ports
Static Private Attributes
static const size_t NUM_OUTPUTS = sizeof...(OutputTypes)
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Detailed Description
template<typename... OutputTypes>
class tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >
Definition at line 3393 of file flow_graph.h.
Member Typedef Documentation
template<typename... OutputTypes> typedef tbb::flow::tuple< sender<OutputTypes>&... > tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::output_ports_type
Definition at line 3395 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename... OutputTypes> tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::composite_node (graph & g) inline
Definition at line 3411 of file flow_graph.h.
References tbb::internal::fgt_composite().
                                : graph_node(g) {
         tbb::internal::fgt_composite( this, &g );
     }
Member Function Documentation
template<typename... OutputTypes> template<typename... NodeTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::add_nodes (const NodeTypes &... n) inline
Definition at line 3429 of file flow_graph.h.
References __TBB_override, tbb::flow::interface10::internal::add_nodes_impl(), and tbb::internal::fgt_multiinput_multioutput_node_desc().
 { internal::add_nodes_impl(this, false, n...); }
template<typename... OutputTypes> template<typename... NodeTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::add_visible_nodes (const NodeTypes &... n) inline
Definition at line 3426 of file flow_graph.h.
References tbb::flow::interface10::internal::add_nodes_impl().
 { internal::add_nodes_impl(this, true, n...); }
template<typename... OutputTypes> output_ports_type& tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::output_ports () inline
Definition at line 3437 of file flow_graph.h.
References __TBB_ASSERT, and __TBB_override.
{
          __TBB_ASSERT(my_output_ports, "output ports not set, call set_external_ports to set output ports");
          return *my_output_ports;
     }
template<typename... OutputTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::reset_node (reset_flags) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 3402 of file flow_graph.h.
References tbb::internal::fgt_composite(), tbb::internal::fgt_multiinput_multioutput_node_desc(), and tbb::flow::interface10::graph_node::graph_node().
 {}
template<typename... OutputTypes> template<typename T > void tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::set_external_ports (T && output_ports_tuple) inline
Definition at line 3417 of file flow_graph.h.
References __TBB_STATIC_ASSERT, tbb::internal::fgt_internal_output_alias_helper< PortsTuple, N >::alias_port(), and value.
{
        __TBB_STATIC_ASSERT(NUM_OUTPUTS == tbb::flow::tuple_size<output_ports_type>::value, "number of arguments does not match number of output ports");
        my_output_ports = tbb::internal::make_unique<output_ports_type>(std::forward<T>(output_ports_tuple));
        tbb::internal::fgt_internal_output_alias_helper<T, NUM_OUTPUTS>::alias_port( this, std::forward<T>(output_ports_tuple));
    }
Member Data Documentation
template<typename... OutputTypes> std::unique_ptr<output_ports_type> tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::my_output_ports private
Definition at line 3398 of file flow_graph.h.
template<typename... OutputTypes> const size_t tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::NUM_OUTPUTS = sizeof...(OutputTypes) static private
Definition at line 3399 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.