Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::context_guard_helper< T > Struct Template Reference
tbb::internal::context_guard_helper< T > Struct Template Reference
#include <scheduler.h>
Public Member Functions
void set_ctx (__TBB_CONTEXT_ARG1(task_group_context *))
void restore_default ()
Detailed Description
template<bool T>
struct tbb::internal::context_guard_helper< T >
Definition at line 810 of file scheduler.h.
Member Function Documentation
template<bool T> void tbb::internal::context_guard_helper< T >::restore_default () inline
Definition at line 812 of file scheduler.h.
Referenced by tbb::interface7::internal::task_arena_base::internal_execute().
 {}
template<bool T> void tbb::internal::context_guard_helper< T >::set_ctx (__TBB_CONTEXT_ARG1(task_group_context *)) inline
Definition at line 811 of file scheduler.h.
Referenced by tbb::interface7::internal::task_arena_base::internal_execute(), and tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all().
 {}
The documentation for this struct was generated from the following file:
scheduler.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.