Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> > Class Template Reference
tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> > Class Template Reference
#include <flow_graph.h>
Public Types
typedef tbb::flow::tuple< receiver< InputTypes > &... > input_ports_type
Public Member Functions
composite_node (graph &g)
template<typename T >
void set_external_ports (T &&input_ports_tuple)
template<typename... NodeTypes>
void add_visible_nodes (const NodeTypes &...n)
template<typename... NodeTypes>
void add_nodes (const NodeTypes &...n)
input_ports_type & input_ports ()
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Protected Member Functions
void reset_node (reset_flags) __TBB_override
Private Attributes
std::unique_ptr< input_ports_type > my_input_ports
Static Private Attributes
static const size_t NUM_INPUTS = sizeof...(InputTypes)
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Detailed Description
template<typename... InputTypes>
class tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >
Definition at line 3334 of file flow_graph.h.
Member Typedef Documentation
template<typename... InputTypes> typedef tbb::flow::tuple< receiver<InputTypes>&... > tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::input_ports_type
Definition at line 3336 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename... InputTypes> tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::composite_node (graph & g) inline
Definition at line 3352 of file flow_graph.h.
References tbb::internal::fgt_composite().
                                : graph_node(g) {
         tbb::internal::fgt_composite( this, &g );
     }
Member Function Documentation
template<typename... InputTypes> template<typename... NodeTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::add_nodes (const NodeTypes &... n) inline
Definition at line 3370 of file flow_graph.h.
References __TBB_override, tbb::flow::interface10::internal::add_nodes_impl(), and tbb::internal::fgt_multiinput_multioutput_node_desc().
 { internal::add_nodes_impl(this, false, n...); }
template<typename... InputTypes> template<typename... NodeTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::add_visible_nodes (const NodeTypes &... n) inline
Definition at line 3367 of file flow_graph.h.
References tbb::flow::interface10::internal::add_nodes_impl().
 { internal::add_nodes_impl(this, true, n...); }
template<typename... InputTypes> input_ports_type& tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::input_ports () inline
Definition at line 3378 of file flow_graph.h.
References __TBB_ASSERT, and __TBB_override.
{
          __TBB_ASSERT(my_input_ports, "input ports not set, call set_external_ports to set input ports");
          return *my_input_ports;
     }
template<typename... InputTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::reset_node (reset_flags) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 3343 of file flow_graph.h.
References tbb::internal::fgt_composite(), tbb::internal::fgt_multiinput_multioutput_node_desc(), and tbb::flow::interface10::graph_node::graph_node().
 {}
template<typename... InputTypes> template<typename T > void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::set_external_ports (T && input_ports_tuple) inline
Definition at line 3358 of file flow_graph.h.
References __TBB_STATIC_ASSERT, tbb::internal::fgt_internal_input_alias_helper< PortsTuple, N >::alias_port(), and value.
{
        __TBB_STATIC_ASSERT(NUM_INPUTS == tbb::flow::tuple_size<input_ports_type>::value, "number of arguments does not match number of input ports");
        my_input_ports = tbb::internal::make_unique<input_ports_type>(std::forward<T>(input_ports_tuple));
        tbb::internal::fgt_internal_input_alias_helper<T, NUM_INPUTS>::alias_port( this, std::forward<T>(input_ports_tuple));
    }
Member Data Documentation
template<typename... InputTypes> std::unique_ptr<input_ports_type> tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::my_input_ports private
Definition at line 3339 of file flow_graph.h.
template<typename... InputTypes> const size_t tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::NUM_INPUTS = sizeof...(InputTypes) static private
Definition at line 3340 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.