Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::internal::broadcast_cache< T, M > Class Template Reference
tbb::flow::interface10::internal::broadcast_cache< T, M > Class Template Reference
A cache of successors that are broadcast to.
#include <flow_graph.h>
Public Member Functions
broadcast_cache ()
template<typename X >
task * try_put_task (const X &t)
Public Member Functions inherited from tbb::flow::interface10::internal::successor_cache< T, M >
successor_cache ()
void set_owner (owner_type *owner)
virtual ~successor_cache ()
void register_successor (successor_type &r)
void remove_successor (successor_type &r)
bool empty ()
void clear ()
Private Types
typedef M mutex_type
typedef successor_cache< T, M >::successors_type successors_type
Additional Inherited Members
Protected Types inherited from tbb::flow::interface10::internal::successor_cache< T, M >
typedef M mutex_type
typedef untyped_receiver successor_type
typedef untyped_receiver * pointer_type
typedef untyped_sender owner_type
typedef std::list< pointer_type > successors_type
Protected Attributes inherited from tbb::flow::interface10::internal::successor_cache< T, M >
mutex_type my_mutex
successors_type my_successors
owner_type * my_owner
Detailed Description
template<typename T, typename M = spin_rw_mutex>
class tbb::flow::interface10::internal::broadcast_cache< T, M >
A cache of successors that are broadcast to.
Definition at line 108 of file flow_graph.h.
Member Typedef Documentation
template<typename T, typename M = spin_rw_mutex> typedef M tbb::flow::interface10::internal::broadcast_cache< T, M >::mutex_type private
Definition at line 471 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> typedef successor_cache<T,M>::successors_type tbb::flow::interface10::internal::broadcast_cache< T, M >::successors_type private
Definition at line 472 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T, typename M = spin_rw_mutex> tbb::flow::interface10::internal::broadcast_cache< T, M >::broadcast_cache () inline
Definition at line 476 of file flow_graph.h.
 { return false; }
Member Function Documentation
template<typename T, typename M = spin_rw_mutex> template<typename X > task* tbb::flow::interface10::internal::broadcast_cache< T, M >::try_put_task (const X & t) inline
Definition at line 481 of file flow_graph.h.
Referenced by tbb::flow::interface10::source_node< Output >::apply_body_bypass(), tbb::flow::interface10::limiter_node< T >::forward_task(), tbb::flow::interface10::broadcast_node< T >::try_put_task(), and tbb::flow::interface10::limiter_node< T >::try_put_task().
                                 { return false; }
     virtual bool try_reserve( T & ) { return false; }
     virtual bool try_release( ) { return false; }
     virtual bool try_consume( ) { return false; }
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
     typedef typename  internal::edge_container<successor_type> built_successors_type;
     typedef typename  built_successors_type::edge_list_type successor_list_type;
     virtual built_successors_type &built_successors()                   = 0;
     virtual void    internal_add_built_successor( successor_type & )    = 0;
     virtual void    internal_delete_built_successor( successor_type & ) = 0;
     virtual void    copy_successors( successor_list_type &)             = 0;
     virtual size_t  successor_count()                                   = 0;
 #endif /* TBB_DEPRECATED_FLOW_NODE_EXTRACTION */
 };  // class sender<T>
 template< typename T >
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.