Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::broadcast_node< T > Class Template Reference
tbb::flow::interface10::broadcast_node< T > Class Template Reference
Forwards messages of type T to all successors.
#include <flow_graph.h>
Public Types
typedef T input_type
typedef T output_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
Public Types inherited from tbb::flow::interface10::receiver< T >
typedef T input_type
The input type of this receiver.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::sender< T >
typedef T output_type
The output type of this sender.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
broadcast_node (graph &g)
broadcast_node (const broadcast_node &src)
bool register_successor (successor_type &r) __TBB_override
Adds a successor.
bool remove_successor (successor_type &r) __TBB_override
Removes s as a successor.
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::receiver< T >
bool try_put (const typename internal::async_helpers< T >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< T >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
virtual bool register_predecessor (predecessor_type &)
Add a predecessor to the node.
virtual bool remove_predecessor (predecessor_type &)
Remove a predecessor from the node.
Public Member Functions inherited from tbb::flow::interface10::sender< T >
virtual bool try_get (T &)
Request an item from the sender.
virtual bool try_reserve (T &)
Reserves an item in the sender.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
virtual bool try_release ()
Releases the reserved item.
virtual bool try_consume ()
Consumes the reserved item.
Protected Member Functions
task * try_put_task (const T &t) __TBB_override
build a task to run the successor if possible. Default is old behavior.
graph & graph_reference () __TBB_override
void reset_receiver (reset_flags) __TBB_override
put receiver back in initial state
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::receiver< T >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Protected Member Functions inherited from tbb::flow::interface10::sender< T >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Private Attributes
internal::broadcast_cache< input_type > my_successors
Friends
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Detailed Description
template<typename T>
class tbb::flow::interface10::broadcast_node< T >
Forwards messages of type T to all successors.
Definition at line 1411 of file flow_graph.h.
Member Typedef Documentation
template<typename T > typedef T tbb::flow::interface10::broadcast_node< T >::input_type
Definition at line 1413 of file flow_graph.h.
template<typename T > typedef T tbb::flow::interface10::broadcast_node< T >::output_type
Definition at line 1414 of file flow_graph.h.
template<typename T > typedef receiver<input_type>::predecessor_type tbb::flow::interface10::broadcast_node< T >::predecessor_type
Definition at line 1415 of file flow_graph.h.
template<typename T > typedef sender<output_type>::successor_type tbb::flow::interface10::broadcast_node< T >::successor_type
Definition at line 1416 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T > tbb::flow::interface10::broadcast_node< T >::broadcast_node (graph & g) inline explicit
Definition at line 1429 of file flow_graph.h.
                                       : graph_node(g) {
         my_successors.set_owner( this );
         tbb::internal::fgt_node( tbb::internal::FLOW_BROADCAST_NODE, &this->my_graph,
                                  static_cast<receiver<input_type> *>(this), static_cast<sender<output_type> *>(this) );
     }
template<typename T > tbb::flow::interface10::broadcast_node< T >::broadcast_node (const broadcast_node< T > & src) inline
Definition at line 1436 of file flow_graph.h.
References __TBB_override, tbb::internal::fgt_node(), tbb::internal::fgt_node_desc(), tbb::flow::interface10::graph_node::my_graph, and tbb::flow::interface10::internal::successor_cache< T, M >::set_owner().
                                                 :
         graph_node(src.my_graph), receiver<T>(), sender<T>()
     {
         my_successors.set_owner( this );
         tbb::internal::fgt_node( tbb::internal::FLOW_BROADCAST_NODE, &this->my_graph,
                                  static_cast<receiver<input_type> *>(this), static_cast<sender<output_type> *>(this) );
     }
Member Function Documentation
template<typename T > graph& tbb::flow::interface10::broadcast_node< T >::graph_reference () inline protected virtual
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 1524 of file flow_graph.h.
References tbb::flow::interface10::graph_node::my_graph.
{
         return my_graph;
     }
template<typename T > bool tbb::flow::interface10::broadcast_node< T >::register_successor (successor_type & r) inline virtual
Adds a successor.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 1451 of file flow_graph.h.
References tbb::flow::interface10::internal::successor_cache< T, M >::register_successor().
{
         my_successors.register_successor( r );
         return true;
     }
template<typename T > bool tbb::flow::interface10::broadcast_node< T >::remove_successor (successor_type & r) inline virtual
Removes s as a successor.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 1457 of file flow_graph.h.
References __TBB_override, and tbb::flow::interface10::internal::successor_cache< T, M >::remove_successor().
{
         my_successors.remove_successor( r );
         return true;
     }
template<typename T > void tbb::flow::interface10::broadcast_node< T >::reset_node (reset_flags f) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 1530 of file flow_graph.h.
{
         if (f&rf_clear_edges) {
            my_successors.clear();
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
            my_built_predecessors.clear();
 #endif
         }
         __TBB_ASSERT(!(f & rf_clear_edges) || my_successors.empty(), "Error resetting broadcast_node");
     }
template<typename T > void tbb::flow::interface10::broadcast_node< T >::reset_receiver (reset_flags f) inline protected virtual
put receiver back in initial state
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 1528 of file flow_graph.h.
 {}
template<typename T > task* tbb::flow::interface10::broadcast_node< T >::try_put_task (const T & t) inline protected virtual
build a task to run the successor if possible. Default is old behavior.
Implements tbb::flow::interface10::receiver< T >.
Definition at line 1518 of file flow_graph.h.
References tbb::flow::internal::SUCCESSFULLY_ENQUEUED, and tbb::flow::interface10::internal::broadcast_cache< T, M >::try_put_task().
{
         task *new_task = my_successors.try_put_task(t);
         if (!new_task) new_task = SUCCESSFULLY_ENQUEUED;
         return new_task;
     }
Friends And Related Function Documentation
template<typename T > template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 1515 of file flow_graph.h.
template<typename T > template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 1516 of file flow_graph.h.
template<typename T > template<typename R , typename B > friend class run_and_put_task friend
Definition at line 1514 of file flow_graph.h.
Member Data Documentation
template<typename T > internal::broadcast_cache<input_type> tbb::flow::interface10::broadcast_node< T >::my_successors private
Definition at line 1422 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.