Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::circular_doubly_linked_list_with_sentinel Class Reference
tbb::internal::circular_doubly_linked_list_with_sentinel Class Reference
Circular doubly-linked list with sentinel.
#include <concurrent_monitor.h>
Classes
struct node_t
Public Member Functions
circular_doubly_linked_list_with_sentinel ()
~circular_doubly_linked_list_with_sentinel ()
size_t size () const
bool empty () const
node_t * front () const
node_t * last () const
node_t * begin () const
const node_t * end () const
void add (node_t *n)
add to the back of the list
void remove (node_t &n)
remove node 'n'
void flush_to (circular_doubly_linked_list_with_sentinel &lst)
move all elements to 'lst' and initialize the 'this' list
void clear ()
Private Attributes
__TBB_atomic size_t count
node_t head
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
Circular doubly-linked list with sentinel.
head.next points to the front and head.prev points to the back
Definition at line 37 of file concurrent_monitor.h.
Constructor & Destructor Documentation
tbb::internal::circular_doubly_linked_list_with_sentinel::circular_doubly_linked_list_with_sentinel () inline
Definition at line 46 of file concurrent_monitor.h.
References clear().
 {clear();}
tbb::internal::circular_doubly_linked_list_with_sentinel::~circular_doubly_linked_list_with_sentinel () inline
Definition at line 48 of file concurrent_monitor.h.
References __TBB_ASSERT, head, tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next, and tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::prev.
 {__TBB_ASSERT( head.next==&head && head.prev==&head, "the list is not empty" );}
Member Function Documentation
void tbb::internal::circular_doubly_linked_list_with_sentinel::add (node_t * n) inline
add to the back of the list
Definition at line 58 of file concurrent_monitor.h.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), count, head, tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next, and tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::prev.
Referenced by tbb::internal::concurrent_monitor::notify_relaxed(), and tbb::internal::concurrent_monitor::prepare_wait().
{
         __TBB_store_relaxed(count, __TBB_load_relaxed(count) + 1);
         n->prev = head.prev;
         n->next = &head;
         head.prev->next = n;
         head.prev = n;
     }
node_t* tbb::internal::circular_doubly_linked_list_with_sentinel::begin () const inline
Definition at line 54 of file concurrent_monitor.h.
References front().
 {return front();}
void tbb::internal::circular_doubly_linked_list_with_sentinel::clear () inline
Definition at line 86 of file concurrent_monitor.h.
References tbb::internal::__TBB_store_relaxed(), count, head, tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next, and tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::prev.
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), circular_doubly_linked_list_with_sentinel(), flush_to(), tbb::internal::concurrent_monitor::notify_all_relaxed(), and tbb::internal::concurrent_monitor::notify_relaxed().
 {head.next = head.prev = &head; __TBB_store_relaxed(count, 0);}
bool tbb::internal::circular_doubly_linked_list_with_sentinel::empty () const inline
Definition at line 51 of file concurrent_monitor.h.
References size().
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), tbb::internal::concurrent_monitor::notify_all_relaxed(), tbb::internal::concurrent_monitor::notify_one_relaxed(), and tbb::internal::concurrent_monitor::~concurrent_monitor().
 {return size()==0;}
const node_t* tbb::internal::circular_doubly_linked_list_with_sentinel::end () const inline
Definition at line 55 of file concurrent_monitor.h.
References head.
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), tbb::internal::concurrent_monitor::notify_all_relaxed(), tbb::internal::concurrent_monitor::notify_one_relaxed(), and tbb::internal::concurrent_monitor::notify_relaxed().
 {return &head;}
void tbb::internal::circular_doubly_linked_list_with_sentinel::flush_to (circular_doubly_linked_list_with_sentinel & lst) inline
move all elements to 'lst' and initialize the 'this' list
Definition at line 75 of file concurrent_monitor.h.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), clear(), count, head, tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next, and tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::prev.
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), and tbb::internal::concurrent_monitor::notify_all_relaxed().
{
         if( const size_t l_count = __TBB_load_relaxed(count) ) {
             __TBB_store_relaxed(lst.count, l_count);
             lst.head.next = head.next;
             lst.head.prev = head.prev;
             head.next->prev = &lst.head;
             head.prev->next = &lst.head;
             clear();
         }
     }
node_t* tbb::internal::circular_doubly_linked_list_with_sentinel::front () const inline
Definition at line 52 of file concurrent_monitor.h.
References head, and tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next.
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), begin(), tbb::internal::concurrent_monitor::notify_all_relaxed(), tbb::internal::concurrent_monitor::notify_one_relaxed(), and tbb::internal::concurrent_monitor::notify_relaxed().
 {return head.next;}
node_t* tbb::internal::circular_doubly_linked_list_with_sentinel::last () const inline
Definition at line 53 of file concurrent_monitor.h.
References head, and tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::prev.
 {return head.prev;}
void tbb::internal::circular_doubly_linked_list_with_sentinel::remove (node_t & n) inline
remove node 'n'
Definition at line 67 of file concurrent_monitor.h.
References __TBB_ASSERT, tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), and count.
Referenced by tbb::internal::concurrent_monitor::cancel_wait(), and tbb::internal::concurrent_monitor::notify_one_relaxed().
{
         __TBB_ASSERT( count > 0, "attempt to remove an item from an empty list" );
         __TBB_store_relaxed(count, __TBB_load_relaxed(count) - 1);
         n.prev->next = n.next;
         n.next->prev = n.prev;
     }
size_t tbb::internal::circular_doubly_linked_list_with_sentinel::size () const inline
Definition at line 50 of file concurrent_monitor.h.
References count.
Referenced by empty().
 {return count;}
Member Data Documentation
__TBB_atomic size_t tbb::internal::circular_doubly_linked_list_with_sentinel::count private
Definition at line 88 of file concurrent_monitor.h.
Referenced by add(), clear(), flush_to(), remove(), and size().
node_t tbb::internal::circular_doubly_linked_list_with_sentinel::head private
Definition at line 89 of file concurrent_monitor.h.
Referenced by add(), clear(), end(), flush_to(), front(), last(), and ~circular_doubly_linked_list_with_sentinel().
The documentation for this class was generated from the following file:
concurrent_monitor.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.