Intel(R) Threading Building Blocks Doxygen Documentation: internal::decrementer< T > Class Template Reference
internal::decrementer< T > Class Template Reference
#include <_flow_graph_body_impl.h>
Public Types
typedef continue_msg input_type
typedef continue_msg output_type
Public Member Functions
decrementer (int number_of_predecessors=0)
void set_owner (T *node)
Protected Member Functions
graph & graph_reference () __TBB_override
Private Member Functions
task * execute () __TBB_override
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
T * my_node
Detailed Description
template<typename T>
class internal::decrementer< T >
Definition at line 348 of file _flow_graph_body_impl.h.
Member Typedef Documentation
template<typename T > typedef continue_msg internal::decrementer< T >::input_type
Definition at line 364 of file _flow_graph_body_impl.h.
template<typename T > typedef continue_msg internal::decrementer< T >::output_type
Definition at line 365 of file _flow_graph_body_impl.h.
Constructor & Destructor Documentation
template<typename T > internal::decrementer< T >::decrementer (int number_of_predecessors = 0) inline
Definition at line 366 of file _flow_graph_body_impl.h.
         : continue_receiver(
             __TBB_FLOW_GRAPH_PRIORITY_ARG1(number_of_predecessors, tbb::flow::internal::no_priority)
         )
           // Since decrementer does not make use of possibly unconstructed owner inside its
           // constructor, my_node can be directly initialized with 'this' pointer passed from the
           // owner, hence making method 'set_owner' needless.
         , my_node(NULL)
     {}
Member Function Documentation
template<typename T > task* internal::decrementer< T >::execute () inline private
Definition at line 352 of file _flow_graph_body_impl.h.
{
         return my_node->decrement_counter();
     }
template<typename T > graph& internal::decrementer< T >::graph_reference () inline protected
Definition at line 358 of file _flow_graph_body_impl.h.
Referenced by tbb::flow::interface10::limiter_node< T >::forward_task(), tbb::flow::interface10::limiter_node< T >::register_predecessor(), and tbb::flow::interface10::limiter_node< T >::register_successor().
{
         return my_node->my_graph;
     }
template<typename T > void internal::decrementer< T >::set_owner (T * node) inline
Definition at line 375 of file _flow_graph_body_impl.h.
 { my_node = node; }
Member Data Documentation
template<typename T > T* internal::decrementer< T >::my_node private
Definition at line 350 of file _flow_graph_body_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_body_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.