Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor Class Reference
tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor Class Reference
bucket accessor is to find, rehash, acquire a lock, and access a bucket
#include <concurrent_hash_map.h>
Public Member Functions
bucket_accessor (concurrent_hash_map *base, const hashcode_t h, bool writer=false)
void acquire (concurrent_hash_map *base, const hashcode_t h, bool writer=false)
find a bucket by masked hashcode, optionally rehash, and acquire the lock
bool is_writer ()
check whether bucket is locked for write
bucket * operator() ()
get bucket pointer
Private Attributes
bucket * my_b
Detailed Description
template<typename Key, typename T, typename HashCompare, typename Allocator>
class tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor
bucket accessor is to find, rehash, acquire a lock, and access a bucket
Definition at line 630 of file concurrent_hash_map.h.
Constructor & Destructor Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::bucket_accessor (concurrent_hash_map * base, const hashcode_t h, bool writer = false) inline
Definition at line 633 of file concurrent_hash_map.h.
References tbb::acquire.
 { acquire( base, h, writer ); }
Member Function Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> void tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::acquire (concurrent_hash_map * base, const hashcode_t h, bool writer = false) inline
find a bucket by masked hashcode, optionally rehash, and acquire the lock
Definition at line 635 of file concurrent_hash_map.h.
References __TBB_ASSERT, tbb::spin_rw_mutex_v3::scoped_lock::acquire(), tbb::interface5::internal::hash_map_base::get_bucket(), tbb::internal::itt_load_word_with_acquire(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::rehash_bucket(), and tbb::interface5::internal::rehash_req.
{
             my_b = base->get_bucket( h );
             // TODO: actually, notification is unnecessary here, just hiding double-check
             if( itt_load_word_with_acquire(my_b->node_list) == internal::rehash_req
                 && try_acquire( my_b->mutex, /*write=*/true ) )
             {
                 if( my_b->node_list == internal::rehash_req ) base->rehash_bucket( my_b, h ); //recursive rehashing
             }
             else bucket::scoped_t::acquire( my_b->mutex, writer );
             __TBB_ASSERT( my_b->node_list != internal::rehash_req, NULL);
         }
template<typename Key, typename T, typename HashCompare, typename Allocator> bool tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::is_writer () inline
check whether bucket is locked for write
Definition at line 647 of file concurrent_hash_map.h.
References tbb::spin_rw_mutex_v3::scoped_lock::is_writer.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::erase(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::lookup(), and tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::rehash_bucket().
 { return bucket::scoped_t::is_writer; }
template<typename Key, typename T, typename HashCompare, typename Allocator> bucket* tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::operator() () inline
get bucket pointer
Definition at line 649 of file concurrent_hash_map.h.
 { return my_b; }
Member Data Documentation
template<typename Key, typename T, typename HashCompare, typename Allocator> bucket* tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::my_b private
Definition at line 631 of file concurrent_hash_map.h.
The documentation for this class was generated from the following file:
concurrent_hash_map.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.