Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator > Class Template Reference
tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator > Class Template Reference
#include <concurrent_unordered_map.h>
Public Types
typedef Key key_type
typedef base_type::value_type value_type
typedef T mapped_type
typedef Hasher hasher
typedef Key_equality key_equal
typedef hash_compare key_compare
typedef base_type::allocator_type allocator_type
typedef base_type::pointer pointer
typedef base_type::const_pointer const_pointer
typedef base_type::reference reference
typedef base_type::const_reference const_reference
typedef base_type::size_type size_type
typedef base_type::difference_type difference_type
typedef base_type::iterator iterator
typedef base_type::const_iterator const_iterator
typedef base_type::iterator local_iterator
typedef base_type::const_iterator const_local_iterator
Public Member Functions
concurrent_unordered_map (size_type n_of_buckets=base_type::initial_bucket_number, const hasher &a_hasher=hasher(), const key_equal &a_keyeq=key_equal(), const allocator_type &a=allocator_type())
concurrent_unordered_map (size_type n_of_buckets, const allocator_type &a)
concurrent_unordered_map (size_type n_of_buckets, const hasher &a_hasher, const allocator_type &a)
concurrent_unordered_map (const Allocator &a)
template<typename Iterator >
concurrent_unordered_map (Iterator first, Iterator last, size_type n_of_buckets=base_type::initial_bucket_number, const hasher &a_hasher=hasher(), const key_equal &a_keyeq=key_equal(), const allocator_type &a=allocator_type())
template<typename Iterator >
concurrent_unordered_map (Iterator first, Iterator last, size_type n_of_buckets, const allocator_type &a)
template<typename Iterator >
concurrent_unordered_map (Iterator first, Iterator last, size_type n_of_buckets, const hasher &a_hasher, const allocator_type &a)
concurrent_unordered_map (std::initializer_list< value_type > il, size_type n_of_buckets=base_type::initial_bucket_number, const hasher &a_hasher=hasher(), const key_equal &a_keyeq=key_equal(), const allocator_type &a=allocator_type())
Constructor from initializer_list.
concurrent_unordered_map (std::initializer_list< value_type > il, size_type n_of_buckets, const allocator_type &a)
concurrent_unordered_map (std::initializer_list< value_type > il, size_type n_of_buckets, const hasher &a_hasher, const allocator_type &a)
concurrent_unordered_map (concurrent_unordered_map &&table, const Allocator &a)
__TBB_IMPLICIT_MOVE_PRESENT
concurrent_unordered_map (const concurrent_unordered_map &table, const Allocator &a)
mapped_type & operator[] (const key_type &key)
mapped_type & at (const key_type &key)
const mapped_type & at (const key_type &key) const
Public Member Functions inherited from tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >
allocator_type get_allocator () const
bool empty () const
size_type size () const
size_type max_size () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
range_type range ()
const_range_type range () const
std::pair< iterator, bool > insert (const value_type &value)
iterator insert (const_iterator, const value_type &value)
std::pair< iterator, bool > insert (value_type &&value)
iterator insert (const_iterator, value_type &&value)
void insert (Iterator first, Iterator last)
void insert (std::initializer_list< value_type > il)
Insert initializer list.
std::pair< iterator, bool > emplace (Args &&...args)
iterator emplace_hint (const_iterator, Args &&...args)
iterator unsafe_erase (const_iterator where)
iterator unsafe_erase (const_iterator first, const_iterator last)
size_type unsafe_erase (const key_type &key)
void swap (concurrent_unordered_base &right)
hasher hash_function () const
key_equal key_eq () const
void clear ()
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
size_type count (const key_type &key) const
std::pair< iterator, iterator > equal_range (const key_type &key)
std::pair< const_iterator, const_iterator > equal_range (const key_type &key) const
size_type unsafe_bucket_count () const
size_type unsafe_max_bucket_count () const
size_type unsafe_bucket_size (size_type bucket)
size_type unsafe_bucket (const key_type &key) const
local_iterator unsafe_begin (size_type bucket)
const_local_iterator unsafe_begin (size_type bucket) const
local_iterator unsafe_end (size_type bucket)
const_local_iterator unsafe_end (size_type bucket) const
const_local_iterator unsafe_cbegin (size_type bucket) const
const_local_iterator unsafe_cend (size_type bucket) const
float load_factor () const
float max_load_factor () const
void max_load_factor (float newmax)
void rehash (size_type buckets)
Private Types
typedef internal::hash_compare< Key, Hasher, Key_equality > hash_compare
typedef concurrent_unordered_map_traits< Key, T, hash_compare, Allocator, false > traits_type
typedef internal::concurrent_unordered_base< traits_type > base_type
Additional Inherited Members
Protected Types inherited from tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >
typedef concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > > self_type
typedef concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::value_type value_type
typedef concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::key_type key_type
typedef concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::hash_compare hash_compare
typedef concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type allocator_type
typedef hash_compare::hasher hasher
typedef hash_compare::key_equal key_equal
typedef tbb::internal::allocator_traits< allocator_type >::size_type size_type
typedef tbb::internal::allocator_traits< allocator_type >::difference_type difference_type
typedef tbb::internal::allocator_traits< allocator_type >::pointer pointer
typedef tbb::internal::allocator_traits< allocator_type >::const_pointer const_pointer
typedef allocator_type::value_type & reference
typedef const allocator_type::value_type & const_reference
typedef split_ordered_list< value_type, typename concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type > solist_t
typedef solist_t::nodeptr_t nodeptr_t
typedef solist_t::raw_iterator raw_iterator
typedef solist_t::raw_const_iterator raw_const_iterator
typedef solist_t::iterator iterator
typedef solist_t::const_iterator const_iterator
typedef iterator local_iterator
typedef const_iterator const_local_iterator
Protected Types inherited from tbb::interface5::concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >
enum
typedef std::pair< const Key, T > value_type
typedef Key key_type
typedef internal::hash_compare< Key, Hasher, Key_equality > hash_compare
typedef tbb::internal::allocator_rebind< Allocator, value_type >::type allocator_type
Protected Member Functions inherited from tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >
concurrent_unordered_base (size_type n_of_buckets=initial_bucket_number, const hash_compare &hc=hash_compare(), const allocator_type &a=allocator_type())
concurrent_unordered_base (const concurrent_unordered_base &right, const allocator_type &a)
concurrent_unordered_base (const concurrent_unordered_base &right)
concurrent_unordered_base (concurrent_unordered_base &&right)
concurrent_unordered_base (concurrent_unordered_base &&right, const allocator_type &a)
concurrent_unordered_base & operator= (const concurrent_unordered_base &right)
concurrent_unordered_base & operator= (concurrent_unordered_base &&other)
concurrent_unordered_base & operator= (std::initializer_list< value_type > il)
assignment operator from initializer_list
~concurrent_unordered_base ()
Protected Member Functions inherited from tbb::interface5::concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >
concurrent_unordered_map_traits ()
concurrent_unordered_map_traits (const hash_compare &hc)
Static Protected Member Functions inherited from tbb::interface5::concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >
static const Key & get_key (const std::pair< Type1, Type2 > &value)
Protected Attributes inherited from tbb::interface5::concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >
hash_compare my_hash_compare
Static Protected Attributes inherited from tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >
static const size_type initial_bucket_number
Detailed Description
template<typename Key, typename T, typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >>
class tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >
Definition at line 60 of file concurrent_unordered_map.h.
Member Typedef Documentation
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::allocator_type tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::allocator_type
Definition at line 85 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef internal::concurrent_unordered_base< traits_type > tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::base_type private
Definition at line 67 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::const_iterator tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::const_iterator
Definition at line 95 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::const_iterator tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::const_local_iterator
Definition at line 97 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::const_pointer tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::const_pointer
Definition at line 87 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::const_reference tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::const_reference
Definition at line 89 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::difference_type tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::difference_type
Definition at line 92 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef internal::hash_compare<Key, Hasher, Key_equality> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::hash_compare private
Definition at line 65 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef Hasher tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::hasher
Definition at line 81 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::iterator tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::iterator
Definition at line 94 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef hash_compare tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::key_compare
Definition at line 83 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef Key_equality tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::key_equal
Definition at line 82 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef Key tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::key_type
Definition at line 78 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::iterator tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::local_iterator
Definition at line 96 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef T tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::mapped_type
Definition at line 80 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::pointer tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::pointer
Definition at line 86 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::reference tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::reference
Definition at line 88 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::size_type tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::size_type
Definition at line 91 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef concurrent_unordered_map_traits<Key, T, hash_compare, Allocator, false> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::traits_type private
Definition at line 66 of file concurrent_unordered_map.h.
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> typedef base_type::value_type tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::value_type
Definition at line 79 of file concurrent_unordered_map.h.
Constructor & Destructor Documentation
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (size_type n_of_buckets = base_type::initial_bucket_number, const hasher & a_hasher = hasher(), const key_equal & a_keyeq = key_equal(), const allocator_type & a = allocator_type()) inline explicit
Definition at line 100 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(a_hasher, a_keyeq), a)
     {}
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (size_type n_of_buckets, const allocator_type & a) inline
Definition at line 106 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(hasher(), key_equal()), a)
     {}
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (size_type n_of_buckets, const hasher & a_hasher, const allocator_type & a) inline
Definition at line 110 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(a_hasher, key_equal()), a)
     {}
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (const Allocator & a) inline explicit
Definition at line 114 of file concurrent_unordered_map.h.
                                                           : base_type(base_type::initial_bucket_number, key_compare(), a)
     {}
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> template<typename Iterator > tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (Iterator first, Iterator last, size_type n_of_buckets = base_type::initial_bucket_number, const hasher & a_hasher = hasher(), const key_equal & a_keyeq = key_equal(), const allocator_type & a = allocator_type()) inline
Definition at line 118 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(a_hasher, a_keyeq), a)
     {
         insert(first, last);
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> template<typename Iterator > tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (Iterator first, Iterator last, size_type n_of_buckets, const allocator_type & a) inline
Definition at line 127 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(hasher(), key_equal()), a)
     {
         insert(first, last);
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> template<typename Iterator > tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (Iterator first, Iterator last, size_type n_of_buckets, const hasher & a_hasher, const allocator_type & a) inline
Definition at line 134 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(a_hasher, key_equal()), a)
     {
         insert(first, last);
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (std::initializer_list< value_type > il, size_type n_of_buckets = base_type::initial_bucket_number, const hasher & a_hasher = hasher(), const key_equal & a_keyeq = key_equal(), const allocator_type & a = allocator_type()) inline
Constructor from initializer_list.
Definition at line 143 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(a_hasher, a_keyeq), a)
     {
         insert(il.begin(),il.end());
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (std::initializer_list< value_type > il, size_type n_of_buckets, const allocator_type & a) inline
Definition at line 151 of file concurrent_unordered_map.h.
         : base_type(n_of_buckets, key_compare(hasher(), key_equal()), a)
     {
         insert(il.begin(), il.end());
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (std::initializer_list< value_type > il, size_type n_of_buckets, const hasher & a_hasher, const allocator_type & a) inline
Definition at line 157 of file concurrent_unordered_map.h.
References tbb::move().
         : base_type(n_of_buckets, key_compare(a_hasher, key_equal()), a)
     {
         insert(il.begin(), il.end());
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator > && table, const Allocator & a) inline
__TBB_IMPLICIT_MOVE_PRESENT
Definition at line 187 of file concurrent_unordered_map.h.
                                                                                    : base_type(std::move(table), a)
     {}
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::concurrent_unordered_map (const concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator > & table, const Allocator & a) inline
Definition at line 191 of file concurrent_unordered_map.h.
         : base_type(table, a)
     {}
Member Function Documentation
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> mapped_type& tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::at (const key_type & key) inline
Definition at line 208 of file concurrent_unordered_map.h.
References tbb::internal::eid_invalid_key, end, and tbb::internal::throw_exception().
     {
         iterator where = find(key);
         if (where == end())
         {
             tbb::internal::throw_exception(tbb::internal::eid_invalid_key);
         }
         return ((*where).second);
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> const mapped_type& tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::at (const key_type & key) const inline
Definition at line 220 of file concurrent_unordered_map.h.
References tbb::internal::eid_invalid_key, end, and tbb::internal::throw_exception().
     {
         const_iterator where = find(key);
         if (where == end())
         {
             tbb::internal::throw_exception(tbb::internal::eid_invalid_key);
         }
         return ((*where).second);
     }
template<typename Key , typename T , typename Hasher = tbb::tbb_hash<Key>, typename Key_equality = std::equal_to<Key>, typename Allocator = tbb::tbb_allocator<std::pair<const Key, T> >> mapped_type& tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::operator[] (const key_type & key) inline
Definition at line 196 of file concurrent_unordered_map.h.
References end.
     {
         iterator where = find(key);
         if (where == end())
         {
             where = insert(std::pair<key_type, mapped_type>(key, mapped_type())).first;
         }
         return ((*where).second);
     }
The documentation for this class was generated from the following file:
concurrent_unordered_map.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.