Intel(R) Threading Building Blocks Doxygen Documentation: internal::continue_input< Output, Policy > Class Template Reference
internal::continue_input< Output, Policy > Class Template Reference abstract
Implements methods for an executable node that takes continue_msg as input.
#include <_flow_graph_node_impl.h>
Public Types
typedef continue_msg input_type
The input type of this receiver.
typedef Output output_type
The output type of this receiver.
typedef function_body< input_type, output_type > function_body_type
typedef continue_input< output_type, Policy > class_type
Public Member Functions
template<typename Body >
continue_input (graph &g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(Body &body, node_priority_t priority))
template<typename Body >
continue_input (graph &g, int number_of_predecessors,)
continue_input (const continue_input &src)
~continue_input ()
template<typename Body >
Body copy_function_object ()
void reset_receiver (reset_flags f) __TBB_override
Protected Member Functions
virtual broadcast_cache< output_type > & successors ()=0
task * apply_body_bypass (input_type)
Applies the body to the provided input.
task * execute () __TBB_override
graph & graph_reference () __TBB_override
Protected Attributes
graph & my_graph_ref
function_body_type * my_body
function_body_type * my_init_body
Friends
class apply_body_task_bypass< class_type, continue_msg >
Detailed Description
template<typename Output, typename Policy>
class internal::continue_input< Output, Policy >
Implements methods for an executable node that takes continue_msg as input.
Definition at line 682 of file _flow_graph_node_impl.h.
Member Typedef Documentation
template<typename Output , typename Policy > typedef continue_input<output_type, Policy> internal::continue_input< Output, Policy >::class_type
Definition at line 691 of file _flow_graph_node_impl.h.
template<typename Output , typename Policy > typedef function_body<input_type, output_type> internal::continue_input< Output, Policy >::function_body_type
Definition at line 690 of file _flow_graph_node_impl.h.
template<typename Output , typename Policy > typedef continue_msg internal::continue_input< Output, Policy >::input_type
The input type of this receiver.
Definition at line 686 of file _flow_graph_node_impl.h.
template<typename Output , typename Policy > typedef Output internal::continue_input< Output, Policy >::output_type
The output type of this receiver.
Definition at line 689 of file _flow_graph_node_impl.h.
Constructor & Destructor Documentation
template<typename Output , typename Policy > template<typename Body > internal::continue_input< Output, Policy >::continue_input (graph & g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(Body &body, node_priority_t priority)) inline
Definition at line 694 of file _flow_graph_node_impl.h.
             : continue_receiver(__TBB_FLOW_GRAPH_PRIORITY_ARG1(/*number_of_predecessors=*/0, priority))
             , my_graph_ref(g)
             , my_body( new internal::function_body_leaf< input_type, output_type, Body>(body) )
             , my_init_body( new internal::function_body_leaf< input_type, output_type, Body>(body) )
             { }
template<typename Output , typename Policy > template<typename Body > internal::continue_input< Output, Policy >::continue_input (graph & g, int number_of_predecessors) inline
Definition at line 702 of file _flow_graph_node_impl.h.
           : continue_receiver( __TBB_FLOW_GRAPH_PRIORITY_ARG1(number_of_predecessors, priority) )
           , my_graph_ref(g)
           , my_body( new internal::function_body_leaf< input_type, output_type, Body>(body) )
           , my_init_body( new internal::function_body_leaf< input_type, output_type, Body>(body) )
         { }
template<typename Output , typename Policy > internal::continue_input< Output, Policy >::continue_input (const continue_input< Output, Policy > & src) inline
Definition at line 710 of file _flow_graph_node_impl.h.
                                                     : continue_receiver(src),
             my_graph_ref(src.my_graph_ref),
             my_body( src.my_init_body->clone() ),
             my_init_body( src.my_init_body->clone() ) {}
template<typename Output , typename Policy > internal::continue_input< Output, Policy >::~continue_input () inline
Definition at line 715 of file _flow_graph_node_impl.h.
{
             delete my_body;
             delete my_init_body;
         }
Member Function Documentation
template<typename Output , typename Policy > task* internal::continue_input< Output, Policy >::apply_body_bypass (input_type) inline protected
Applies the body to the provided input.
Definition at line 746 of file _flow_graph_node_impl.h.
References tbb::internal::fgt_begin_body(), and tbb::internal::fgt_end_body().
{
             // There is an extra copied needed to capture the
             // body execution without the try_put
             tbb::internal::fgt_begin_body( my_body );
             output_type v = (*my_body)( continue_msg() );
             tbb::internal::fgt_end_body( my_body );
             return successors().try_put_task( v );
         }
template<typename Output , typename Policy > template<typename Body > Body internal::continue_input< Output, Policy >::copy_function_object () inline
Definition at line 721 of file _flow_graph_node_impl.h.
{
             function_body_type &body_ref = *my_body;
             return dynamic_cast< internal::function_body_leaf<input_type, output_type, Body> & >(body_ref).get_body();
         }
template<typename Output , typename Policy > task* internal::continue_input< Output, Policy >::execute () inline protected
Definition at line 755 of file _flow_graph_node_impl.h.
References __TBB_FLOW_GRAPH_PRIORITY_ARG1, and tbb::flow::interface10::internal::is_graph_active().
{
             if(!internal::is_graph_active(my_graph_ref)) {
                 return NULL;
             }
 #if _MSC_VER && !__INTEL_COMPILER
 #pragma warning (push)
 #pragma warning (disable: 4127)  /* suppress conditional expression is constant */
 #endif
             if(internal::has_policy<lightweight, Policy>::value) {
 #if _MSC_VER && !__INTEL_COMPILER
 #pragma warning (pop)
 #endif
                 return apply_body_bypass( continue_msg() );
             }
             else {
                 return new ( task::allocate_additional_child_of( *(my_graph_ref.root_task()) ) )
                        apply_body_task_bypass< class_type, continue_msg >(
                            *this, __TBB_FLOW_GRAPH_PRIORITY_ARG1(continue_msg(), my_priority) );
             }
         }
template<typename Output , typename Policy > graph& internal::continue_input< Output, Policy >::graph_reference () inline protected
Definition at line 776 of file _flow_graph_node_impl.h.
{
             return my_graph_ref;
         }
template<typename Output , typename Policy > void internal::continue_input< Output, Policy >::reset_receiver (reset_flags f) inline
Definition at line 726 of file _flow_graph_node_impl.h.
References tbb::flow::interface10::rf_reset_bodies.
{
             continue_receiver::reset_receiver(f);
             if(f & rf_reset_bodies) {
                 function_body_type *tmp = my_init_body->clone();
                 delete my_body;
                 my_body = tmp;
             }
         }
template<typename Output , typename Policy > virtual broadcast_cache<output_type >& internal::continue_input< Output, Policy >::successors () protected pure virtual
Friends And Related Function Documentation
template<typename Output , typename Policy > friend class apply_body_task_bypass< class_type, continue_msg > friend
Definition at line 743 of file _flow_graph_node_impl.h.
Member Data Documentation
template<typename Output , typename Policy > function_body_type* internal::continue_input< Output, Policy >::my_body protected
Definition at line 738 of file _flow_graph_node_impl.h.
template<typename Output , typename Policy > graph& internal::continue_input< Output, Policy >::my_graph_ref protected
Definition at line 737 of file _flow_graph_node_impl.h.
template<typename Output , typename Policy > function_body_type* internal::continue_input< Output, Policy >::my_init_body protected
Definition at line 739 of file _flow_graph_node_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_node_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.