Intel(R) Threading Building Blocks Doxygen Documentation: tbb::strict_ppl::concurrent_queue< T, A > Class Template Reference
tbb::strict_ppl::concurrent_queue< T, A > Class Template Reference
Containers
A high-performance thread-safe non-blocking concurrent queue.
#include <concurrent_queue.h>
Public Types
typedef T value_type
Element type in the queue.
typedef T & reference
Reference type.
typedef const T & const_reference
Const reference type.
typedef size_t size_type
Integral type for representing size of the queue.
typedef ptrdiff_t difference_type
Difference type for iterator.
typedef A allocator_type
Allocator type.
typedef internal::concurrent_queue_iterator< concurrent_queue, T > iterator
typedef internal::concurrent_queue_iterator< concurrent_queue, const T > const_iterator
Public Member Functions
concurrent_queue (const allocator_type &a=allocator_type())
Construct empty queue.
template<typename InputIterator >
concurrent_queue (InputIterator begin, InputIterator end, const allocator_type &a=allocator_type())
[begin,end) constructor
concurrent_queue (const concurrent_queue &src, const allocator_type &a=allocator_type())
Copy constructor.
concurrent_queue (concurrent_queue &&src)
Move constructors.
concurrent_queue (concurrent_queue &&src, const allocator_type &a)
~concurrent_queue ()
Destroy queue.
void push (const T &source)
Enqueue an item at tail of queue.
void push (T &&source)
template<typename... Arguments>
void emplace (Arguments &&...args)
bool try_pop (T &result)
Attempt to dequeue an item from head of queue.
size_type unsafe_size () const
Return the number of items in the queue; thread unsafe.
bool empty () const
Equivalent to size()==0.
void clear ()
Clear the queue. not thread-safe.
allocator_type get_allocator () const
Return allocator object.
iterator unsafe_begin ()
iterator unsafe_end ()
const_iterator unsafe_begin () const
const_iterator unsafe_end () const
Private Types
typedef tbb::internal::allocator_rebind< A, char >::type page_allocator_type
Allocator type.
Private Member Functions
virtual void * allocate_block (size_t n) __TBB_override
Allocates a block of size n (bytes)
virtual void deallocate_block (void *b, size_t n) __TBB_override
Deallocates block created by allocate_block.
Static Private Member Functions
static void copy_construct_item (T *location, const void *src)
static void move_construct_item (T *location, const void *src)
Private Attributes
page_allocator_type my_allocator
Friends
template<typename Container , typename Value >
class internal::concurrent_queue_iterator
Additional Inherited Members
Protected Types inherited from tbb::strict_ppl::internal::concurrent_queue_base_v3< T >
typedef concurrent_queue_rep< T >::page page
Protected Member Functions inherited from tbb::strict_ppl::internal::concurrent_queue_base_v3< T >
concurrent_queue_base_v3 ()
virtual ~concurrent_queue_base_v3 ()
void internal_push (const void *src, item_constructor_t construct_item)
Enqueue item at tail of queue.
bool internal_try_pop (void *dst)
Attempt to dequeue item from queue.
size_t internal_size () const
Get size of queue; result may be invalid if queue is modified concurrently.
bool internal_empty () const
check if the queue is empty; thread safe
void internal_finish_clear ()
free any remaining pages
void internal_throw_exception () const
Obsolete.
void assign (const concurrent_queue_base_v3 &src, item_constructor_t construct_item)
copy or move internal representation
void internal_swap (concurrent_queue_base_v3 &src)
swap internal representation
Protected Member Functions inherited from tbb::strict_ppl::internal::concurrent_queue_page_allocator
virtual ~concurrent_queue_page_allocator ()
Detailed Description
template<typename T, typename A = cache_aligned_allocator<T>>
class tbb::strict_ppl::concurrent_queue< T, A >
A high-performance thread-safe non-blocking concurrent queue.
Multiple threads may each push and pop concurrently. Assignment construction is not allowed.
Definition at line 36 of file concurrent_queue.h.
Member Typedef Documentation
template<typename T , typename A = cache_aligned_allocator<T>> typedef A tbb::strict_ppl::concurrent_queue< T, A >::allocator_type
Allocator type.
Definition at line 82 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef internal::concurrent_queue_iterator<concurrent_queue,const T> tbb::strict_ppl::concurrent_queue< T, A >::const_iterator
Definition at line 170 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef const T& tbb::strict_ppl::concurrent_queue< T, A >::const_reference
Const reference type.
Definition at line 73 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef ptrdiff_t tbb::strict_ppl::concurrent_queue< T, A >::difference_type
Difference type for iterator.
Definition at line 79 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef internal::concurrent_queue_iterator<concurrent_queue,T> tbb::strict_ppl::concurrent_queue< T, A >::iterator
Definition at line 169 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef tbb::internal::allocator_rebind<A, char>::type tbb::strict_ppl::concurrent_queue< T, A >::page_allocator_type private
Allocator type.
Definition at line 40 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef T& tbb::strict_ppl::concurrent_queue< T, A >::reference
Reference type.
Definition at line 70 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef size_t tbb::strict_ppl::concurrent_queue< T, A >::size_type
Integral type for representing size of the queue.
Definition at line 76 of file concurrent_queue.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef T tbb::strict_ppl::concurrent_queue< T, A >::value_type
Element type in the queue.
Definition at line 67 of file concurrent_queue.h.
Constructor & Destructor Documentation
template<typename T , typename A = cache_aligned_allocator<T>> tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue (const allocator_type & a = allocator_type()) inline explicit
Construct empty queue.
Definition at line 85 of file concurrent_queue.h.
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue(), and tbb::strict_ppl::concurrent_queue< T, A >::unsafe_end().
                                                                           :
         my_allocator( a )
     {
     }
template<typename T , typename A = cache_aligned_allocator<T>> template<typename InputIterator > tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue (InputIterator begin, InputIterator end, const allocator_type & a = allocator_type()) inline
[begin,end) constructor
Definition at line 92 of file concurrent_queue.h.
References begin, end, and tbb::strict_ppl::concurrent_queue< T, A >::push().
                                                                                                           :
         my_allocator( a )
     {
         for( ; begin != end; ++begin )
             this->push(*begin);
     }
template<typename T , typename A = cache_aligned_allocator<T>> tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue (const concurrent_queue< T, A > & src, const allocator_type & a = allocator_type()) inline
Copy constructor.
Definition at line 100 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::assign(), tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue(), tbb::strict_ppl::concurrent_queue< T, A >::copy_construct_item(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_swap(), tbb::move(), and tbb::strict_ppl::concurrent_queue< T, A >::my_allocator.
                                                                                                :
         internal::concurrent_queue_base_v3<T>(), my_allocator( a )
     {
         this->assign( src, copy_construct_item );
     }
template<typename T , typename A = cache_aligned_allocator<T>> tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue (concurrent_queue< T, A > && src) inline
Move constructors.
Definition at line 108 of file concurrent_queue.h.
                                                :
         internal::concurrent_queue_base_v3<T>(), my_allocator( std::move(src.my_allocator) )
     {
         this->internal_swap( src );
     }
template<typename T , typename A = cache_aligned_allocator<T>> tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue (concurrent_queue< T, A > && src, const allocator_type & a) inline
Definition at line 114 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::assign(), tbb::strict_ppl::concurrent_queue< T, A >::clear(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_swap(), tbb::strict_ppl::concurrent_queue< T, A >::move_construct_item(), tbb::strict_ppl::concurrent_queue< T, A >::my_allocator, and tbb::strict_ppl::concurrent_queue< T, A >::~concurrent_queue().
                                                                         :
         internal::concurrent_queue_base_v3<T>(), my_allocator( a )
     {
         // checking that memory allocated by one instance of allocator can be deallocated
         // with another
         if( my_allocator == src.my_allocator) {
             this->internal_swap( src );
         } else {
             // allocators are different => performing per-element move
             this->assign( src, move_construct_item );
             src.clear();
         }
     }
template<typename T , class A > tbb::strict_ppl::concurrent_queue< T, A >::~concurrent_queue ()
Destroy queue.
Definition at line 191 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::clear(), and tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_finish_clear().
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue().
{
     clear();
     this->internal_finish_clear();
 }
Member Function Documentation
template<typename T , typename A = cache_aligned_allocator<T>> virtual void* tbb::strict_ppl::concurrent_queue< T, A >::allocate_block (size_t n) inline private virtual
Allocates a block of size n (bytes)
Implements tbb::strict_ppl::internal::concurrent_queue_base_v3< T >.
Definition at line 44 of file concurrent_queue.h.
References tbb::internal::eid_bad_alloc, and tbb::internal::throw_exception().
{
         void *b = reinterpret_cast<void*>(my_allocator.allocate( n ));
         if( !b )
             internal::throw_exception(internal::eid_bad_alloc);
         return b;
     }
template<typename T , class A > void tbb::strict_ppl::concurrent_queue< T, A >::clear ()
Clear the queue. not thread-safe.
Definition at line 197 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::empty(), tbb::strict_ppl::concurrent_queue< T, A >::try_pop(), and value.
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue(), tbb::strict_ppl::concurrent_queue< T, A >::empty(), tbb::concurrent_bounded_queue< T, A >::get_allocator(), tbb::concurrent_bounded_queue< T, A >::~concurrent_bounded_queue(), and tbb::strict_ppl::concurrent_queue< T, A >::~concurrent_queue().
{
     T value;
     while( !empty() ) try_pop(value);
 }
template<typename T , typename A = cache_aligned_allocator<T>> static void tbb::strict_ppl::concurrent_queue< T, A >::copy_construct_item (T * location, const void * src) inline static private
Definition at line 56 of file concurrent_queue.h.
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue(), and tbb::strict_ppl::concurrent_queue< T, A >::push().
{
         new (location) T(*static_cast<const T*>(src));
     }
template<typename T , typename A = cache_aligned_allocator<T>> virtual void tbb::strict_ppl::concurrent_queue< T, A >::deallocate_block (void * b, size_t n) inline private virtual
Deallocates block created by allocate_block.
Implements tbb::strict_ppl::internal::concurrent_queue_base_v3< T >.
Definition at line 52 of file concurrent_queue.h.
{
         my_allocator.deallocate( reinterpret_cast<char*>(b), n );
     }
template<typename T , typename A = cache_aligned_allocator<T>> template<typename... Arguments> void tbb::strict_ppl::concurrent_queue< T, A >::emplace (Arguments &&... args) inline
Definition at line 144 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::push().
{
         push( T(std::forward<Arguments>( args )...) );
     }
template<typename T , typename A = cache_aligned_allocator<T>> bool tbb::strict_ppl::concurrent_queue< T, A >::empty () const inline
Equivalent to size()==0.
Definition at line 161 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::clear(), and tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_empty().
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::clear().
 {return this->internal_empty();}
template<typename T , typename A = cache_aligned_allocator<T>> allocator_type tbb::strict_ppl::concurrent_queue< T, A >::get_allocator () const inline
Return allocator object.
Definition at line 167 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::my_allocator.
 { return this->my_allocator; }
template<typename T , typename A = cache_aligned_allocator<T>> static void tbb::strict_ppl::concurrent_queue< T, A >::move_construct_item (T * location, const void * src) inline static private
Definition at line 61 of file concurrent_queue.h.
References tbb::move().
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue(), and tbb::strict_ppl::concurrent_queue< T, A >::push().
{
         new (location) T( std::move(*static_cast<T*>(const_cast<void*>(src))) );
     }
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::strict_ppl::concurrent_queue< T, A >::push (const T & source) inline
Enqueue an item at tail of queue.
Definition at line 133 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::copy_construct_item(), and tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_push().
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue(), tbb::strict_ppl::concurrent_queue< T, A >::emplace(), tbb::concurrent_bounded_queue< T, A >::emplace(), and tbb::concurrent_bounded_queue< T, A >::push().
{
         this->internal_push( &source, copy_construct_item );
     }
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::strict_ppl::concurrent_queue< T, A >::push (T && source) inline
Definition at line 138 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_push(), and tbb::strict_ppl::concurrent_queue< T, A >::move_construct_item().
{
         this->internal_push( &source, move_construct_item );
     }
template<typename T , typename A = cache_aligned_allocator<T>> bool tbb::strict_ppl::concurrent_queue< T, A >::try_pop (T & result) inline
Attempt to dequeue an item from head of queue.
Does not wait for item to become available. Returns true if successful; false otherwise.
Definition at line 153 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_try_pop().
Referenced by tbb::strict_ppl::concurrent_queue< T, A >::clear(), and tbb::concurrent_bounded_queue< T, A >::clear().
{
         return this->internal_try_pop( &result );
     }
template<typename T , typename A = cache_aligned_allocator<T>> iterator tbb::strict_ppl::concurrent_queue< T, A >::unsafe_begin () inline
Definition at line 175 of file concurrent_queue.h.
 {return iterator(*this);}
template<typename T , typename A = cache_aligned_allocator<T>> const_iterator tbb::strict_ppl::concurrent_queue< T, A >::unsafe_begin () const inline
Definition at line 177 of file concurrent_queue.h.
 {return const_iterator(*this);}
template<typename T , typename A = cache_aligned_allocator<T>> iterator tbb::strict_ppl::concurrent_queue< T, A >::unsafe_end () inline
Definition at line 176 of file concurrent_queue.h.
 {return iterator();}
template<typename T , typename A = cache_aligned_allocator<T>> const_iterator tbb::strict_ppl::concurrent_queue< T, A >::unsafe_end () const inline
Definition at line 178 of file concurrent_queue.h.
References tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue().
 {return const_iterator();}
template<typename T , typename A = cache_aligned_allocator<T>> size_type tbb::strict_ppl::concurrent_queue< T, A >::unsafe_size () const inline
Return the number of items in the queue; thread unsafe.
Definition at line 158 of file concurrent_queue.h.
References tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_size().
 {return this->internal_size();}
Friends And Related Function Documentation
template<typename T , typename A = cache_aligned_allocator<T>> template<typename Container , typename Value > friend class internal::concurrent_queue_iterator friend
Definition at line 37 of file concurrent_queue.h.
Member Data Documentation
template<typename T , typename A = cache_aligned_allocator<T>> page_allocator_type tbb::strict_ppl::concurrent_queue< T, A >::my_allocator private
Definition at line 41 of file concurrent_queue.h.
Referenced by tbb::concurrent_bounded_queue< T, A >::concurrent_bounded_queue(), tbb::strict_ppl::concurrent_queue< T, A >::concurrent_queue(), tbb::strict_ppl::concurrent_queue< T, A >::get_allocator(), and tbb::concurrent_bounded_queue< T, A >::get_allocator().
The documentation for this class was generated from the following file:
concurrent_queue.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.