Intel(R) Threading Building Blocks Doxygen Documentation: tbb::cache_aligned_allocator< T > Class Template Reference
tbb::cache_aligned_allocator< T > Class Template Reference
Memory Allocation
Meets "allocator" requirements of ISO C++ Standard, Section 20.1.5.
#include <cache_aligned_allocator.h>
Classes
struct rebind
Public Types
typedef internal::allocator_type< T >::value_type value_type
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef size_t size_type
typedef ptrdiff_t difference_type
Public Member Functions
cache_aligned_allocator () throw ()
cache_aligned_allocator (const cache_aligned_allocator &) throw ()
template<typename U >
cache_aligned_allocator (const cache_aligned_allocator< U > &) throw ()
pointer address (reference x) const
const_pointer address (const_reference x) const
pointer allocate (size_type n, const void *hint=0)
Allocate space for n objects, starting on a cache/sector line.
void deallocate (pointer p, size_type)
Free block of memory that starts on a cache line.
size_type max_size () const throw ()
Largest value for which method allocate might succeed.
template<typename U , typename... Args>
void construct (U *p, Args &&...args)
Copy-construct value at location pointed to by p.
void destroy (pointer p)
Destroy value at location pointed to by p.
Detailed Description
template<typename T>
class tbb::cache_aligned_allocator< T >
Meets "allocator" requirements of ISO C++ Standard, Section 20.1.5.
The members are ordered the same way they are in section 20.4.1 of the ISO C++ standard.
Definition at line 64 of file cache_aligned_allocator.h.
Member Typedef Documentation
template<typename T> typedef const value_type* tbb::cache_aligned_allocator< T >::const_pointer
Definition at line 68 of file cache_aligned_allocator.h.
template<typename T> typedef const value_type& tbb::cache_aligned_allocator< T >::const_reference
Definition at line 70 of file cache_aligned_allocator.h.
template<typename T> typedef ptrdiff_t tbb::cache_aligned_allocator< T >::difference_type
Definition at line 72 of file cache_aligned_allocator.h.
template<typename T> typedef value_type* tbb::cache_aligned_allocator< T >::pointer
Definition at line 67 of file cache_aligned_allocator.h.
template<typename T> typedef value_type& tbb::cache_aligned_allocator< T >::reference
Definition at line 69 of file cache_aligned_allocator.h.
template<typename T> typedef size_t tbb::cache_aligned_allocator< T >::size_type
Definition at line 71 of file cache_aligned_allocator.h.
template<typename T> typedef internal::allocator_type<T>::value_type tbb::cache_aligned_allocator< T >::value_type
Definition at line 66 of file cache_aligned_allocator.h.
Constructor & Destructor Documentation
template<typename T> tbb::cache_aligned_allocator< T >::cache_aligned_allocator () throw () inline
Definition at line 76 of file cache_aligned_allocator.h.
 {}
template<typename T> tbb::cache_aligned_allocator< T >::cache_aligned_allocator (const cache_aligned_allocator< T > &) throw () inline
Definition at line 77 of file cache_aligned_allocator.h.
 {}
template<typename T> template<typename U > tbb::cache_aligned_allocator< T >::cache_aligned_allocator (const cache_aligned_allocator< U > &) throw () inline
Definition at line 78 of file cache_aligned_allocator.h.
 {}
Member Function Documentation
template<typename T> pointer tbb::cache_aligned_allocator< T >::address (reference x) const inline
Definition at line 80 of file cache_aligned_allocator.h.
 {return &x;}
template<typename T> const_pointer tbb::cache_aligned_allocator< T >::address (const_reference x) const inline
Definition at line 81 of file cache_aligned_allocator.h.
 {return &x;}
template<typename T> pointer tbb::cache_aligned_allocator< T >::allocate (size_type n, const void * hint = 0) inline
Allocate space for n objects, starting on a cache/sector line.
Definition at line 84 of file cache_aligned_allocator.h.
References tbb::internal::NFS_Allocate().
Referenced by tbb::interface5::internal::hash_map_base::enable_segment().
{
         // The "hint" argument is always ignored in NFS_Allocate thus const_cast shouldn't hurt
         return pointer(internal::NFS_Allocate( n, sizeof(value_type), const_cast<void*>(hint) ));
     }
template<typename T> template<typename U , typename... Args> void tbb::cache_aligned_allocator< T >::construct (U * p, Args &&... args) inline
Copy-construct value at location pointed to by p.
Definition at line 102 of file cache_aligned_allocator.h.
References tbb::move(), p, and value.
         { ::new((void *)p) U(std::forward<Args>(args)...); }
template<typename T> void tbb::cache_aligned_allocator< T >::deallocate (pointer p, size_type) inline
Free block of memory that starts on a cache line.
Definition at line 90 of file cache_aligned_allocator.h.
References tbb::internal::NFS_Free().
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::clear().
{
         internal::NFS_Free(p);
     }
template<typename T> void tbb::cache_aligned_allocator< T >::destroy (pointer p) inline
Destroy value at location pointed to by p.
Definition at line 112 of file cache_aligned_allocator.h.
 {p->~value_type();}
template<typename T> size_type tbb::cache_aligned_allocator< T >::max_size () const throw () inline
Largest value for which method allocate might succeed.
Definition at line 95 of file cache_aligned_allocator.h.
References tbb::internal::NFS_MaxLineSize.
{
         return (~size_t(0)-internal::NFS_MaxLineSize)/sizeof(value_type);
     }
The documentation for this class was generated from the following file:
cache_aligned_allocator.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.