Intel(R) Threading Building Blocks Doxygen Documentation: tbb::blocked_range3d< PageValue, RowValue, ColValue > Class Template Reference
tbb::blocked_range3d< PageValue, RowValue, ColValue > Class Template Reference
Algorithms
A 3-dimensional range that models the Range concept.
#include <blocked_range3d.h>
Public Types
typedef blocked_range< PageValue > page_range_type
Type for size of an iteration range.
typedef blocked_range< RowValue > row_range_type
typedef blocked_range< ColValue > col_range_type
Public Member Functions
blocked_range3d (PageValue page_begin, PageValue page_end, RowValue row_begin, RowValue row_end, ColValue col_begin, ColValue col_end)
blocked_range3d (PageValue page_begin, PageValue page_end, typename page_range_type::size_type page_grainsize, RowValue row_begin, RowValue row_end, typename row_range_type::size_type row_grainsize, ColValue col_begin, ColValue col_end, typename col_range_type::size_type col_grainsize)
bool empty () const
True if range is empty.
bool is_divisible () const
True if range is divisible into two pieces.
blocked_range3d (blocked_range3d &r, split)
blocked_range3d (blocked_range3d &r, proportional_split &proportion)
const page_range_type & pages () const
The pages of the iteration space.
const row_range_type & rows () const
The rows of the iteration space.
const col_range_type & cols () const
The columns of the iteration space.
Static Public Attributes
static const bool is_splittable_in_proportion = true
Static field to support proportional split.
Private Member Functions
template<typename Split >
void do_split (blocked_range3d &r, Split &split_obj)
Private Attributes
page_range_type my_pages
row_range_type my_rows
col_range_type my_cols
Detailed Description
template<typename PageValue, typename RowValue = PageValue, typename ColValue = RowValue>
class tbb::blocked_range3d< PageValue, RowValue, ColValue >
A 3-dimensional range that models the Range concept.
Definition at line 32 of file blocked_range3d.h.
Member Typedef Documentation
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> typedef blocked_range<ColValue> tbb::blocked_range3d< PageValue, RowValue, ColValue >::col_range_type
Definition at line 37 of file blocked_range3d.h.
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> typedef blocked_range<PageValue> tbb::blocked_range3d< PageValue, RowValue, ColValue >::page_range_type
Type for size of an iteration range.
Definition at line 35 of file blocked_range3d.h.
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> typedef blocked_range<RowValue> tbb::blocked_range3d< PageValue, RowValue, ColValue >::row_range_type
Definition at line 36 of file blocked_range3d.h.
Constructor & Destructor Documentation
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> tbb::blocked_range3d< PageValue, RowValue, ColValue >::blocked_range3d (PageValue page_begin, PageValue page_end, RowValue row_begin, RowValue row_end, ColValue col_begin, ColValue col_end) inline
Definition at line 46 of file blocked_range3d.h.
                                                               :
         my_pages(page_begin,page_end),
         my_rows(row_begin,row_end),
         my_cols(col_begin,col_end)
     {}
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> tbb::blocked_range3d< PageValue, RowValue, ColValue >::blocked_range3d (PageValue page_begin, PageValue page_end, typename page_range_type::size_type page_grainsize, RowValue row_begin, RowValue row_end, typename row_range_type::size_type row_grainsize, ColValue col_begin, ColValue col_end, typename col_range_type::size_type col_grainsize) inline
Definition at line 54 of file blocked_range3d.h.
                                                                                                                 :
         my_pages(page_begin,page_end,page_grainsize),
         my_rows(row_begin,row_end,row_grainsize),
         my_cols(col_begin,col_end,col_grainsize)
     {}
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> tbb::blocked_range3d< PageValue, RowValue, ColValue >::blocked_range3d (blocked_range3d< PageValue, RowValue, ColValue > & r, split) inline
Definition at line 73 of file blocked_range3d.h.
References tbb::blocked_range3d< PageValue, RowValue, ColValue >::do_split(), and tbb::blocked_range3d< PageValue, RowValue, ColValue >::is_splittable_in_proportion.
                                                  :
         my_pages(r.my_pages),
         my_rows(r.my_rows),
         my_cols(r.my_cols)
     {
         split split_obj;
         do_split(r, split_obj);
     }
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> tbb::blocked_range3d< PageValue, RowValue, ColValue >::blocked_range3d (blocked_range3d< PageValue, RowValue, ColValue > & r, proportional_split & proportion) inline
Definition at line 86 of file blocked_range3d.h.
References tbb::blocked_range3d< PageValue, RowValue, ColValue >::do_split().
                                                                           :
         my_pages(r.my_pages),
         my_rows(r.my_rows),
         my_cols(r.my_cols)
     {
         do_split(r, proportion);
     }
Member Function Documentation
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> const col_range_type& tbb::blocked_range3d< PageValue, RowValue, ColValue >::cols () const inline
The columns of the iteration space.
Definition at line 102 of file blocked_range3d.h.
References tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_cols.
 {return my_cols;}
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> template<typename Split > void tbb::blocked_range3d< PageValue, RowValue, ColValue >::do_split (blocked_range3d< PageValue, RowValue, ColValue > & r, Split & split_obj) inline private
Definition at line 107 of file blocked_range3d.h.
References tbb::blocked_range< ColValue >::do_split(), tbb::blocked_range< PageValue >::do_split(), tbb::blocked_range< RowValue >::do_split(), tbb::blocked_range< Value >::grainsize(), tbb::blocked_range< Value >::my_begin, tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_cols, tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_pages, tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_rows, and tbb::blocked_range< Value >::size().
Referenced by tbb::blocked_range3d< PageValue, RowValue, ColValue >::blocked_range3d().
     {
         if ( my_pages.size()*double(my_rows.grainsize()) < my_rows.size()*double(my_pages.grainsize()) ) {
             if ( my_rows.size()*double(my_cols.grainsize()) < my_cols.size()*double(my_rows.grainsize()) ) {
                 my_cols.my_begin = col_range_type::do_split(r.my_cols, split_obj);
             } else {
                 my_rows.my_begin = row_range_type::do_split(r.my_rows, split_obj);
             }
         } else {
             if ( my_pages.size()*double(my_cols.grainsize()) < my_cols.size()*double(my_pages.grainsize()) ) {
                 my_cols.my_begin = col_range_type::do_split(r.my_cols, split_obj);
             } else {
                 my_pages.my_begin = page_range_type::do_split(r.my_pages, split_obj);
             }
         }
     }
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> bool tbb::blocked_range3d< PageValue, RowValue, ColValue >::empty () const inline
True if range is empty.
Definition at line 63 of file blocked_range3d.h.
References tbb::blocked_range< Value >::empty().
{
         // Range is empty if at least one dimension is empty.
         return my_pages.empty() || my_rows.empty() || my_cols.empty();
     }
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> bool tbb::blocked_range3d< PageValue, RowValue, ColValue >::is_divisible () const inline
True if range is divisible into two pieces.
Definition at line 69 of file blocked_range3d.h.
References tbb::blocked_range< Value >::is_divisible().
{
         return  my_pages.is_divisible() || my_rows.is_divisible() || my_cols.is_divisible();
     }
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> const page_range_type& tbb::blocked_range3d< PageValue, RowValue, ColValue >::pages () const inline
The pages of the iteration space.
Definition at line 96 of file blocked_range3d.h.
References tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_pages.
 {return my_pages;}
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> const row_range_type& tbb::blocked_range3d< PageValue, RowValue, ColValue >::rows () const inline
The rows of the iteration space.
Definition at line 99 of file blocked_range3d.h.
References tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_rows.
 {return my_rows;}
Member Data Documentation
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> const bool tbb::blocked_range3d< PageValue, RowValue, ColValue >::is_splittable_in_proportion = true static
Static field to support proportional split.
Definition at line 84 of file blocked_range3d.h.
Referenced by tbb::blocked_range3d< PageValue, RowValue, ColValue >::blocked_range3d().
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> col_range_type tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_cols private
Definition at line 42 of file blocked_range3d.h.
Referenced by tbb::blocked_range3d< PageValue, RowValue, ColValue >::cols(), and tbb::blocked_range3d< PageValue, RowValue, ColValue >::do_split().
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> page_range_type tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_pages private
Definition at line 40 of file blocked_range3d.h.
Referenced by tbb::blocked_range3d< PageValue, RowValue, ColValue >::do_split(), and tbb::blocked_range3d< PageValue, RowValue, ColValue >::pages().
template<typename PageValue , typename RowValue = PageValue, typename ColValue = RowValue> row_range_type tbb::blocked_range3d< PageValue, RowValue, ColValue >::my_rows private
Definition at line 41 of file blocked_range3d.h.
Referenced by tbb::blocked_range3d< PageValue, RowValue, ColValue >::do_split(), and tbb::blocked_range3d< PageValue, RowValue, ColValue >::rows().
The documentation for this class was generated from the following file:
blocked_range3d.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.