Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > > Class Template Reference
tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > > Class Template Reference
#include <flow_graph.h>
Public Types
typedef tbb::flow::tuple< receiver< InputTypes > &... > input_ports_type
typedef tbb::flow::tuple< sender< OutputTypes > &... > output_ports_type
Public Member Functions
composite_node (graph &g)
template<typename T1 , typename T2 >
void set_external_ports (T1 &&input_ports_tuple, T2 &&output_ports_tuple)
template<typename... NodeTypes>
void add_visible_nodes (const NodeTypes &...n)
template<typename... NodeTypes>
void add_nodes (const NodeTypes &...n)
input_ports_type & input_ports ()
output_ports_type & output_ports ()
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Protected Member Functions
void reset_node (reset_flags) __TBB_override
Private Attributes
std::unique_ptr< input_ports_type > my_input_ports
std::unique_ptr< output_ports_type > my_output_ports
Static Private Attributes
static const size_t NUM_INPUTS = sizeof...(InputTypes)
static const size_t NUM_OUTPUTS = sizeof...(OutputTypes)
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Detailed Description
template<typename... InputTypes, typename... OutputTypes>
class tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >
Definition at line 3264 of file flow_graph.h.
Member Typedef Documentation
template<typename... InputTypes, typename... OutputTypes> typedef tbb::flow::tuple< receiver<InputTypes>&... > tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::input_ports_type
Definition at line 3267 of file flow_graph.h.
template<typename... InputTypes, typename... OutputTypes> typedef tbb::flow::tuple< sender<OutputTypes>&... > tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::output_ports_type
Definition at line 3268 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename... InputTypes, typename... OutputTypes> tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::composite_node (graph & g) inline
Definition at line 3287 of file flow_graph.h.
References tbb::internal::fgt_multiinput_multioutput_node(), and tbb::flow::interface10::graph_node::my_graph.
                                : graph_node(g) {
         tbb::internal::fgt_multiinput_multioutput_node( tbb::internal::FLOW_COMPOSITE_NODE, this, &this->my_graph );
     }
Member Function Documentation
template<typename... InputTypes, typename... OutputTypes> template<typename... NodeTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::add_nodes (const NodeTypes &... n) inline
Definition at line 3307 of file flow_graph.h.
References __TBB_override, tbb::flow::interface10::internal::add_nodes_impl(), and tbb::internal::fgt_multiinput_multioutput_node_desc().
 { internal::add_nodes_impl(this, false, n...); }
template<typename... InputTypes, typename... OutputTypes> template<typename... NodeTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::add_visible_nodes (const NodeTypes &... n) inline
Definition at line 3304 of file flow_graph.h.
References tbb::flow::interface10::internal::add_nodes_impl().
 { internal::add_nodes_impl(this, true, n...); }
template<typename... InputTypes, typename... OutputTypes> input_ports_type& tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::input_ports () inline
Definition at line 3315 of file flow_graph.h.
References __TBB_ASSERT.
{
          __TBB_ASSERT(my_input_ports, "input ports not set, call set_external_ports to set input ports");
          return *my_input_ports;
     }
template<typename... InputTypes, typename... OutputTypes> output_ports_type& tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::output_ports () inline
Definition at line 3320 of file flow_graph.h.
References __TBB_ASSERT, and __TBB_override.
{
          __TBB_ASSERT(my_output_ports, "output ports not set, call set_external_ports to set output ports");
          return *my_output_ports;
     }
template<typename... InputTypes, typename... OutputTypes> void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::reset_node (reset_flags) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 3278 of file flow_graph.h.
References tbb::internal::fgt_multiinput_multioutput_node(), tbb::internal::fgt_multiinput_multioutput_node_desc(), tbb::flow::interface10::graph_node::graph_node(), and tbb::flow::interface10::graph_node::my_graph.
 {}
template<typename... InputTypes, typename... OutputTypes> template<typename T1 , typename T2 > void tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::set_external_ports (T1 && input_ports_tuple, T2 && output_ports_tuple) inline
Definition at line 3293 of file flow_graph.h.
References __TBB_STATIC_ASSERT, tbb::internal::fgt_internal_input_alias_helper< PortsTuple, N >::alias_port(), tbb::internal::fgt_internal_output_alias_helper< PortsTuple, N >::alias_port(), and value.
{
         __TBB_STATIC_ASSERT(NUM_INPUTS == tbb::flow::tuple_size<input_ports_type>::value, "number of arguments does not match number of input ports");
         __TBB_STATIC_ASSERT(NUM_OUTPUTS == tbb::flow::tuple_size<output_ports_type>::value, "number of arguments does not match number of output ports");
         my_input_ports = tbb::internal::make_unique<input_ports_type>(std::forward<T1>(input_ports_tuple));
         my_output_ports = tbb::internal::make_unique<output_ports_type>(std::forward<T2>(output_ports_tuple));
         tbb::internal::fgt_internal_input_alias_helper<T1, NUM_INPUTS>::alias_port( this, input_ports_tuple);
         tbb::internal::fgt_internal_output_alias_helper<T2, NUM_OUTPUTS>::alias_port( this, output_ports_tuple);
     }
Member Data Documentation
template<typename... InputTypes, typename... OutputTypes> std::unique_ptr<input_ports_type> tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::my_input_ports private
Definition at line 3271 of file flow_graph.h.
template<typename... InputTypes, typename... OutputTypes> std::unique_ptr<output_ports_type> tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::my_output_ports private
Definition at line 3272 of file flow_graph.h.
template<typename... InputTypes, typename... OutputTypes> const size_t tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::NUM_INPUTS = sizeof...(InputTypes) static private
Definition at line 3274 of file flow_graph.h.
template<typename... InputTypes, typename... OutputTypes> const size_t tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::NUM_OUTPUTS = sizeof...(OutputTypes) static private
Definition at line 3275 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.