Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::continue_node< Output, Policy > Class Template Reference
tbb::flow::interface10::continue_node< Output, Policy > Class Template Reference
Implements an executable node that supports continue_msg -> Output.
#include <flow_graph.h>
Public Types
typedef continue_msg input_type
typedef Output output_type
typedef internal::continue_input< Output, Policy > input_impl_type
typedef internal::function_output< output_type > fOutput_type
typedef input_impl_type::predecessor_type predecessor_type
typedef fOutput_type::successor_type successor_type
Public Types inherited from tbb::flow::interface10::internal::continue_input< Output, Policy >
typedef continue_msg input_type
The input type of this receiver.
typedef Output output_type
The output type of this receiver.
typedef function_body< input_type, output_type > function_body_type
typedef continue_input< output_type, Policy > class_type
Public Types inherited from tbb::flow::interface10::continue_receiver
typedef continue_msg input_type
The input type.
typedef receiver< input_type >::predecessor_type predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::receiver< continue_msg >
typedef continue_msg input_type
The input type of this receiver.
typedef internal::async_helpers< continue_msg >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::internal::function_output< Output >
typedef Output output_type
typedef sender< output_type >::successor_type successor_type
typedef broadcast_cache< output_type > broadcast_cache_type
Public Types inherited from tbb::flow::interface10::sender< Output >
typedef Output output_type
The output type of this sender.
typedef internal::async_helpers< Output >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
template<typename Body >
continue_node (graph &g,)
Constructor for executable node with continue_msg -> Output.
template<typename Body >
continue_node (graph &g, int number_of_predecessors,)
Constructor for executable node with continue_msg -> Output.
continue_node (const continue_node &src)
Copy constructor.
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::internal::continue_input< Output, Policy >
template<typename Body >
continue_input (graph &g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(Body &body, node_priority_t priority))
template<typename Body >
continue_input (graph &g, int number_of_predecessors,)
continue_input (const continue_input &src)
~continue_input ()
template<typename Body >
Body copy_function_object ()
void reset_receiver (reset_flags f) __TBB_override
put receiver back in initial state
Public Member Functions inherited from tbb::flow::interface10::continue_receiver
continue_receiver (__TBB_FLOW_GRAPH_PRIORITY_ARG1(int number_of_predecessors, node_priority_t priority))
Constructor.
continue_receiver (const continue_receiver &src)
Copy constructor.
bool register_predecessor (predecessor_type &) __TBB_override
Increments the trigger threshold.
bool remove_predecessor (predecessor_type &) __TBB_override
Decrements the trigger threshold.
Public Member Functions inherited from tbb::flow::interface10::receiver< continue_msg >
bool try_put (const typename internal::async_helpers< continue_msg >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< continue_msg >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
Public Member Functions inherited from tbb::flow::interface10::internal::function_output< Output >
function_output ()
function_output (const function_output &)
bool register_successor (successor_type &r) __TBB_override
Adds a new successor to this node.
bool remove_successor (successor_type &r) __TBB_override
Removes a successor from this node.
task * try_put_task (const output_type &i)
broadcast_cache_type & successors ()
Public Member Functions inherited from tbb::flow::interface10::sender< Output >
virtual bool try_get (Output &)
Request an item from the sender.
virtual bool try_reserve (Output &)
Reserves an item in the sender.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
virtual bool try_release ()
Releases the reserved item.
virtual bool try_consume ()
Consumes the reserved item.
Protected Member Functions
internal::broadcast_cache< output_type > & successors () __TBB_override
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::continue_input< Output, Policy >
task * apply_body_bypass (input_type)
Applies the body to the provided input.
task * execute () __TBB_override
Does whatever should happen when the threshold is reached.
graph & graph_reference () __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::continue_receiver
task * try_put_task (const input_type &) __TBB_override
Put item to successor; return task to run the successor if possible.
bool is_continue_receiver () __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::receiver< continue_msg >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
Protected Member Functions inherited from tbb::flow::interface10::sender< Output >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Friends
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Protected Attributes inherited from tbb::flow::interface10::internal::continue_input< Output, Policy >
graph & my_graph_ref
function_body_type * my_body
function_body_type * my_init_body
Protected Attributes inherited from tbb::flow::interface10::continue_receiver
spin_mutex my_mutex
int my_predecessor_count
int my_current_count
int my_initial_predecessor_count
Protected Attributes inherited from tbb::flow::interface10::internal::function_output< Output >
broadcast_cache_type my_successors
Detailed Description
template<typename Output, typename Policy = internal::Policy<void>>
class tbb::flow::interface10::continue_node< Output, Policy >
Implements an executable node that supports continue_msg -> Output.
Definition at line 1340 of file flow_graph.h.
Member Typedef Documentation
template<typename Output , typename Policy = internal::Policy<void>> typedef internal::function_output<output_type> tbb::flow::interface10::continue_node< Output, Policy >::fOutput_type
Definition at line 1346 of file flow_graph.h.
template<typename Output , typename Policy = internal::Policy<void>> typedef internal::continue_input<Output, Policy> tbb::flow::interface10::continue_node< Output, Policy >::input_impl_type
Definition at line 1345 of file flow_graph.h.
template<typename Output , typename Policy = internal::Policy<void>> typedef continue_msg tbb::flow::interface10::continue_node< Output, Policy >::input_type
Definition at line 1343 of file flow_graph.h.
template<typename Output , typename Policy = internal::Policy<void>> typedef Output tbb::flow::interface10::continue_node< Output, Policy >::output_type
Definition at line 1344 of file flow_graph.h.
template<typename Output , typename Policy = internal::Policy<void>> typedef input_impl_type::predecessor_type tbb::flow::interface10::continue_node< Output, Policy >::predecessor_type
Definition at line 1347 of file flow_graph.h.
template<typename Output , typename Policy = internal::Policy<void>> typedef fOutput_type::successor_type tbb::flow::interface10::continue_node< Output, Policy >::successor_type
Definition at line 1348 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename Output , typename Policy = internal::Policy<void>> template<typename Body > tbb::flow::interface10::continue_node< Output, Policy >::continue_node (graph & g) inline
Constructor for executable node with continue_msg -> Output.
Definition at line 1352 of file flow_graph.h.
References tbb::internal::fgt_node_with_body(), and tbb::flow::interface10::graph_node::my_graph.
       : graph_node(g), input_impl_type( g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(body, priority) ) {
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_CONTINUE_NODE, &this->my_graph,
                                            static_cast<receiver<input_type> *>(this),
                                            static_cast<sender<output_type> *>(this), this->my_body );
     }
template<typename Output , typename Policy = internal::Policy<void>> template<typename Body > tbb::flow::interface10::continue_node< Output, Policy >::continue_node (graph & g, int number_of_predecessors) inline
Constructor for executable node with continue_msg -> Output.
Definition at line 1363 of file flow_graph.h.
References tbb::internal::fgt_node_with_body(), and tbb::flow::interface10::graph_node::my_graph.
       : graph_node(g)
       , input_impl_type(g, number_of_predecessors, __TBB_FLOW_GRAPH_PRIORITY_ARG1(body, priority)) {
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_CONTINUE_NODE, &this->my_graph,
                                            static_cast<receiver<input_type> *>(this),
                                            static_cast<sender<output_type> *>(this), this->my_body );
     }
template<typename Output , typename Policy = internal::Policy<void>> tbb::flow::interface10::continue_node< Output, Policy >::continue_node (const continue_node< Output, Policy > & src) inline
Copy constructor.
Definition at line 1374 of file flow_graph.h.
References __TBB_override, tbb::internal::fgt_node_desc(), tbb::internal::fgt_node_with_body(), and tbb::flow::interface10::graph_node::my_graph.
                                               :
         graph_node(src.my_graph), input_impl_type(src),
         internal::function_output<Output>() {
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_CONTINUE_NODE, &this->my_graph,
                                            static_cast<receiver<input_type> *>(this),
                                            static_cast<sender<output_type> *>(this), this->my_body );
     }
Member Function Documentation
template<typename Output , typename Policy = internal::Policy<void>> void tbb::flow::interface10::continue_node< Output, Policy >::reset_node (reset_flags f) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 1402 of file flow_graph.h.
References __TBB_ASSERT, and internal::successor_cache< T, M >::empty().
{
         input_impl_type::reset_receiver(f);
         if(f & rf_clear_edges)successors().clear();
         __TBB_ASSERT(!(f & rf_clear_edges) || successors().empty(), "continue_node not reset");
     }
template<typename Output , typename Policy = internal::Policy<void>> internal::broadcast_cache<output_type>& tbb::flow::interface10::continue_node< Output, Policy >::successors () inline protected virtual
Implements tbb::flow::interface10::internal::continue_input< Output, Policy >.
Definition at line 1400 of file flow_graph.h.
 { return fOutput_type::my_successors; }
Friends And Related Function Documentation
template<typename Output , typename Policy = internal::Policy<void>> template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 1397 of file flow_graph.h.
template<typename Output , typename Policy = internal::Policy<void>> template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 1398 of file flow_graph.h.
template<typename Output , typename Policy = internal::Policy<void>> template<typename R , typename B > friend class run_and_put_task friend
Definition at line 1396 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.