Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::concurrent_queue_base_v8 Class Reference
tbb::internal::concurrent_queue_base_v8 Class Reference abstract
Containers
For internal use only.
#include <_concurrent_queue_impl.h>
Protected Member Functions
concurrent_queue_base_v8 (size_t item_sz)
void __TBB_EXPORTED_METHOD move_content (concurrent_queue_base_v8 &src)
move items
bool __TBB_EXPORTED_METHOD internal_push_move_if_not_full (const void *src)
Attempt to enqueue item onto queue using move operation.
void __TBB_EXPORTED_METHOD internal_push_move (const void *src)
Enqueue item at tail of queue using move operation.
Protected Member Functions inherited from tbb::internal::concurrent_queue_base_v3
__TBB_EXPORTED_METHOD concurrent_queue_base_v3 (size_t item_size)
virtual __TBB_EXPORTED_METHOD ~concurrent_queue_base_v3 ()
void __TBB_EXPORTED_METHOD internal_push (const void *src)
Enqueue item at tail of queue using copy operation.
void __TBB_EXPORTED_METHOD internal_pop (void *dst)
Dequeue item from head of queue.
void __TBB_EXPORTED_METHOD internal_abort ()
Abort all pending queue operations.
bool __TBB_EXPORTED_METHOD internal_push_if_not_full (const void *src)
Attempt to enqueue item onto queue using copy operation.
bool __TBB_EXPORTED_METHOD internal_pop_if_present (void *dst)
Attempt to dequeue item from queue.
ptrdiff_t __TBB_EXPORTED_METHOD internal_size () const
Get size of queue.
bool __TBB_EXPORTED_METHOD internal_empty () const
Check if the queue is emtpy.
void __TBB_EXPORTED_METHOD internal_set_capacity (ptrdiff_t capacity, size_t element_size)
Set the queue capacity.
virtual page * allocate_page ()=0
custom allocator
virtual void deallocate_page (page *p)=0
custom de-allocator
void __TBB_EXPORTED_METHOD internal_finish_clear ()
free any remaining pages
void __TBB_EXPORTED_METHOD internal_throw_exception () const
throw an exception
void __TBB_EXPORTED_METHOD assign (const concurrent_queue_base_v3 &src)
copy internal representation
void internal_swap (concurrent_queue_base_v3 &src)
swap queues
void internal_insert_item (const void *src, copy_specifics op_type)
Enqueues item at tail of queue using specified operation (copy or move)
bool internal_insert_if_not_full (const void *src, copy_specifics op_type)
Attempts to enqueue at tail of queue using specified operation (copy or move)
void internal_assign (const concurrent_queue_base_v3 &src, copy_specifics op_type)
Assigns one queue to another using specified operation (copy or move)
Private Member Functions
virtual void move_page_item (page &dst, size_t dindex, const page &src, size_t sindex)=0
virtual void move_item (page &dst, size_t index, const void *src)=0
Friends
struct micro_queue
Additional Inherited Members
Protected Types inherited from tbb::internal::concurrent_queue_base_v3
enum copy_specifics { copy, move }
Protected Attributes inherited from tbb::internal::concurrent_queue_base_v3
ptrdiff_t my_capacity
Capacity of the queue.
size_t items_per_page
Always a power of 2.
size_t item_size
Size of an item.
Detailed Description
For internal use only.
Backward compatible modification of concurrent_queue_base_v3
Definition at line 939 of file _concurrent_queue_impl.h.
Constructor & Destructor Documentation
tbb::internal::concurrent_queue_base_v8::concurrent_queue_base_v8 (size_t item_sz) inline protected
Definition at line 941 of file _concurrent_queue_impl.h.
References __TBB_EXPORTED_METHOD.
 : concurrent_queue_base_v3( item_sz ) {}
Member Function Documentation
void tbb::internal::concurrent_queue_base_v8::internal_push_move (const void * src) protected
Enqueue item at tail of queue using move operation.
Definition at line 371 of file concurrent_queue.cpp.
References tbb::move().
{
    internal_insert_item( src, move );
 }
bool tbb::internal::concurrent_queue_base_v8::internal_push_move_if_not_full (const void * src) protected
Attempt to enqueue item onto queue using move operation.
Definition at line 499 of file concurrent_queue.cpp.
References tbb::move().
{
     return internal_insert_if_not_full( src, move );
 }
void tbb::internal::concurrent_queue_base_v8::move_content (concurrent_queue_base_v8 & src) protected
move items
Definition at line 577 of file concurrent_queue.cpp.
References tbb::move().
{
     internal_assign( src, move );
 }
virtual void tbb::internal::concurrent_queue_base_v8::move_item (page & dst, size_t index, const void * src) private pure virtual
Implemented in tbb::concurrent_bounded_queue< T, A >.
virtual void tbb::internal::concurrent_queue_base_v8::move_page_item (page & dst, size_t dindex, const page & src, size_t sindex) private pure virtual
Implemented in tbb::concurrent_bounded_queue< T, A >.
Friends And Related Function Documentation
friend struct micro_queue friend
Definition at line 952 of file _concurrent_queue_impl.h.
The documentation for this class was generated from the following files:
_concurrent_queue_impl.h
concurrent_queue.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.