Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::critical_section_v4 Class Reference
tbb::internal::critical_section_v4 Class Reference
#include <critical_section.h>
Classes
class scoped_lock
Public Member Functions
void __TBB_EXPORTED_METHOD internal_construct ()
critical_section_v4 ()
~critical_section_v4 ()
void lock ()
bool try_lock ()
void unlock ()
Static Public Attributes
static const bool is_rw_mutex = false
static const bool is_recursive_mutex = false
static const bool is_fair_mutex = true
Private Attributes
pthread_mutex_t my_impl
tbb_thread::id my_tid
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
Definition at line 40 of file critical_section.h.
Constructor & Destructor Documentation
tbb::internal::critical_section_v4::critical_section_v4 () inline
Definition at line 51 of file critical_section.h.
References internal_construct().
{
 #if _WIN32||_WIN64
         InitializeCriticalSectionEx( &my_impl, 4000, 0 );
 #else
         pthread_mutex_init(&my_impl, NULL);
 #endif
         internal_construct();
     }
tbb::internal::critical_section_v4::~critical_section_v4 () inline
Definition at line 60 of file critical_section.h.
References __TBB_ASSERT, and id.
{
         __TBB_ASSERT(my_tid == tbb_thread::id(), "Destroying a still-held critical section");
 #if _WIN32||_WIN64
         DeleteCriticalSection(&my_impl);
 #else
         pthread_mutex_destroy(&my_impl);
 #endif
     }
Member Function Documentation
void tbb::internal::critical_section_v4::internal_construct ()
Definition at line 27 of file critical_section.cpp.
References _T, ITT_SYNC_CREATE, and my_impl.
Referenced by critical_section_v4().
{
     ITT_SYNC_CREATE(&my_impl, _T("ppl::critical_section"), _T(""));
 }
void tbb::internal::critical_section_v4::lock () inline
Definition at line 82 of file critical_section.h.
References __TBB_ASSERT, __TBB_ASSERT_EX, tbb::internal::eid_improper_lock, tbb::this_tbb_thread::get_id(), id, and tbb::internal::throw_exception().
Referenced by tbb::internal::critical_section_v4::scoped_lock::scoped_lock().
                 {
         tbb_thread::id local_tid = this_tbb_thread::get_id();
         if(local_tid == my_tid) throw_exception( eid_improper_lock );
 #if _WIN32||_WIN64
         EnterCriticalSection( &my_impl );
 #else
         int rval = pthread_mutex_lock(&my_impl);
         __TBB_ASSERT_EX(!rval, "critical_section::lock: pthread_mutex_lock failed");
 #endif
         __TBB_ASSERT(my_tid == tbb_thread::id(), NULL);
         my_tid = local_tid;
     }
bool tbb::internal::critical_section_v4::try_lock () inline
Definition at line 95 of file critical_section.h.
References __TBB_ASSERT, tbb::this_tbb_thread::get_id(), and id.
                     {
         bool gotlock;
         tbb_thread::id local_tid = this_tbb_thread::get_id();
         if(local_tid == my_tid) return false;
 #if _WIN32||_WIN64
         gotlock = TryEnterCriticalSection( &my_impl ) != 0;
 #else
         int rval = pthread_mutex_trylock(&my_impl);
         // valid returns are 0 (locked) and [EBUSY]
         __TBB_ASSERT(rval == 0 || rval == EBUSY, "critical_section::trylock: pthread_mutex_trylock failed");
         gotlock = rval == 0;
 #endif
         if(gotlock)  {
             my_tid = local_tid;
         }
         return gotlock;
     }
void tbb::internal::critical_section_v4::unlock () inline
Definition at line 113 of file critical_section.h.
References __TBB_ASSERT, __TBB_ASSERT_EX, tbb::this_tbb_thread::get_id(), and id.
Referenced by tbb::internal::critical_section_v4::scoped_lock::~scoped_lock().
                   {
         __TBB_ASSERT(this_tbb_thread::get_id() == my_tid, "thread unlocking critical_section is not thread that locked it");
         my_tid = tbb_thread::id();
 #if _WIN32||_WIN64
         LeaveCriticalSection( &my_impl );
 #else
         int rval = pthread_mutex_unlock(&my_impl);
         __TBB_ASSERT_EX(!rval, "critical_section::unlock: pthread_mutex_unlock failed");
 #endif
     }
Member Data Documentation
const bool tbb::internal::critical_section_v4::is_fair_mutex = true static
Definition at line 126 of file critical_section.h.
const bool tbb::internal::critical_section_v4::is_recursive_mutex = false static
Definition at line 125 of file critical_section.h.
const bool tbb::internal::critical_section_v4::is_rw_mutex = false static
Definition at line 124 of file critical_section.h.
pthread_mutex_t tbb::internal::critical_section_v4::my_impl private
Definition at line 44 of file critical_section.h.
Referenced by internal_construct().
tbb_thread::id tbb::internal::critical_section_v4::my_tid private
Definition at line 46 of file critical_section.h.
The documentation for this class was generated from the following files:
critical_section.h
critical_section.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.