Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::basic_tls< T > Class Template Reference
tbb::internal::basic_tls< T > Class Template Reference
Basic cross-platform wrapper class for TLS operations.
#include <tls.h>
Public Member Functions
int create ()
int destroy ()
void set (T value)
T get ()
Private Types
typedef DWORD tls_key_t
Private Attributes
tls_key_t my_key
Detailed Description
template<typename T>
class tbb::internal::basic_tls< T >
Basic cross-platform wrapper class for TLS operations.
Definition at line 38 of file tls.h.
Member Typedef Documentation
template<typename T> typedef DWORD tbb::internal::basic_tls< T >::tls_key_t private
Definition at line 49 of file tls.h.
Member Function Documentation
template<typename T> int tbb::internal::basic_tls< T >::create () inline
Definition at line 52 of file tls.h.
Referenced by tbb::internal::input_buffer::create_my_tls().
                  {
         tls_key_t tmp = TlsAlloc();
         if( tmp==TLS_OUT_OF_INDEXES )
             return TLS_OUT_OF_INDEXES;
         my_key = tmp;
         return 0;
     }
template<typename T> int tbb::internal::basic_tls< T >::destroy () inline
Definition at line 59 of file tls.h.
Referenced by tbb::internal::input_buffer::destroy_my_tls(), and tbb::internal::basic_tls< uintptr_t >::get().
 { TlsFree(my_key); my_key=0; return 0; }
template<typename T> T tbb::internal::basic_tls< T >::get () inline
Definition at line 61 of file tls.h.
Referenced by tbb::internal::governor::local_scheduler(), tbb::internal::governor::local_scheduler_if_initialized(), tbb::internal::governor::local_scheduler_weak(), and tbb::internal::input_buffer::my_tls_end_of_input().
 { return (T)TlsGetValue(my_key); }
template<typename T> void tbb::internal::basic_tls< T >::set (T value) inline
Definition at line 60 of file tls.h.
Referenced by tbb::internal::input_buffer::set_my_tls_end_of_input().
 { TlsSetValue(my_key, (LPVOID)value); }
Member Data Documentation
template<typename T> tls_key_t tbb::internal::basic_tls< T >::my_key private
Definition at line 76 of file tls.h.
Referenced by tbb::internal::basic_tls< uintptr_t >::create(), tbb::internal::basic_tls< uintptr_t >::destroy(), tbb::internal::basic_tls< uintptr_t >::get(), and tbb::internal::basic_tls< uintptr_t >::set().
The documentation for this class was generated from the following file:
tls.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.