Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::concurrent_monitor Class Reference
tbb::internal::concurrent_monitor Class Reference
concurrent_monitor
#include <concurrent_monitor.h>
Classes
class thread_context
Public Member Functions
concurrent_monitor ()
ctor
~concurrent_monitor ()
dtor
void prepare_wait (thread_context &thr, uintptr_t ctx=0)
prepare wait by inserting 'thr' into the wait queue
bool commit_wait (thread_context &thr)
Commit wait if event count has not changed; otherwise, cancel wait.
void cancel_wait (thread_context &thr)
Cancel the wait. Removes the thread from the wait queue if not removed yet.
template<typename WaitUntil , typename Context >
void wait (WaitUntil until, Context on)
Wait for a condition to be satisfied with waiting-on context.
void notify_one ()
Notify one thread about the event.
void notify_one_relaxed ()
Notify one thread about the event. Relaxed version.
void notify_all ()
Notify all waiting threads of the event.
void notify_all_relaxed ()
Notify all waiting threads of the event; Relaxed version.
template<typename P >
void notify (const P &predicate)
Notify waiting threads of the event that satisfies the given predicate.
template<typename P >
void notify_relaxed (const P &predicate)
Notify waiting threads of the event that satisfies the given predicate; Relaxed version.
void abort_all ()
Abort any sleeping threads at the time of the call.
void abort_all_relaxed ()
Abort any sleeping threads at the time of the call; Relaxed version.
Private Member Functions
thread_context * to_thread_context (waitset_node_t *n)
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
tbb::spin_mutex mutex_ec
waitset_t waitset_ec
__TBB_atomic unsigned epoch
Detailed Description
concurrent_monitor
fine-grained concurrent_monitor implementation
Definition at line 97 of file concurrent_monitor.h.
Constructor & Destructor Documentation
tbb::internal::concurrent_monitor::concurrent_monitor () inline
ctor
Definition at line 129 of file concurrent_monitor.h.
References tbb::internal::__TBB_store_relaxed().
 {__TBB_store_relaxed(epoch, 0);}
tbb::internal::concurrent_monitor::~concurrent_monitor ()
dtor
Definition at line 31 of file concurrent_monitor.cpp.
References __TBB_ASSERT, abort_all(), tbb::internal::circular_doubly_linked_list_with_sentinel::empty(), and waitset_ec.
{
     abort_all();
     __TBB_ASSERT( waitset_ec.empty(), "waitset not empty?" );
 }
Member Function Documentation
void tbb::internal::concurrent_monitor::abort_all () inline
Abort any sleeping threads at the time of the call.
Definition at line 179 of file concurrent_monitor.h.
References tbb::atomic_fence().
Referenced by tbb::internal::concurrent_queue_base_v3::internal_abort(), and ~concurrent_monitor().
 {atomic_fence(); abort_all_relaxed(); }
void tbb::internal::concurrent_monitor::abort_all_relaxed ()
Abort any sleeping threads at the time of the call; Relaxed version.
Definition at line 111 of file concurrent_monitor.cpp.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), tbb::internal::concurrent_monitor::thread_context::aborted, tbb::internal::circular_doubly_linked_list_with_sentinel::clear(), tbb::internal::circular_doubly_linked_list_with_sentinel::empty(), tbb::internal::circular_doubly_linked_list_with_sentinel::end(), end, tbb::internal::concurrent_monitor::thread_context::epoch, tbb::internal::circular_doubly_linked_list_with_sentinel::flush_to(), tbb::internal::circular_doubly_linked_list_with_sentinel::front(), tbb::internal::concurrent_monitor::thread_context::in_waitset, mutex_ec, tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next, tbb::internal::concurrent_monitor::thread_context::semaphore(), to_thread_context(), tbb::internal::binary_semaphore::V(), and waitset_ec.
{
     if( waitset_ec.empty() )
         return;
     waitset_t temp;
     const waitset_node_t* end;
     {
         tbb::spin_mutex::scoped_lock l( mutex_ec );
         __TBB_store_relaxed( epoch, __TBB_load_relaxed(epoch) + 1 );
         waitset_ec.flush_to( temp );
         end = temp.end();
         for( waitset_node_t* n=temp.front(); n!=end; n=n->next )
             to_thread_context(n)->in_waitset = false;
     }
     waitset_node_t* nxt;
     for( waitset_node_t* n=temp.front(); n!=end; n=nxt ) {
         nxt = n->next;
         to_thread_context(n)->aborted = true;
         to_thread_context(n)->semaphore().V();
     }
 #if TBB_USE_ASSERT
     temp.clear();
 #endif
 }
void tbb::internal::concurrent_monitor::cancel_wait (thread_context & thr)
Cancel the wait. Removes the thread from the wait queue if not removed yet.
Definition at line 54 of file concurrent_monitor.cpp.
References tbb::internal::concurrent_monitor::thread_context::in_waitset, mutex_ec, tbb::internal::circular_doubly_linked_list_with_sentinel::remove(), tbb::internal::concurrent_monitor::thread_context::skipped_wakeup, and waitset_ec.
Referenced by tbb::interface7::internal::task_arena_base::internal_execute(), tbb::internal::concurrent_queue_base_v3::internal_insert_item(), and tbb::internal::concurrent_queue_base_v3::internal_pop().
{
     // possible skipped wakeup will be pumped in the following prepare_wait()
     thr.skipped_wakeup = true;
     // try to remove node from waitset
     bool th_in_waitset = thr.in_waitset;
     if( th_in_waitset ) {
         tbb::spin_mutex::scoped_lock l( mutex_ec );
         if (thr.in_waitset) {
             waitset_ec.remove( (waitset_t::node_t&)thr );
             // node is removed from waitset, so there will be no wakeup
             thr.in_waitset = false;
             thr.skipped_wakeup = false;
         }
     }
 }
bool tbb::internal::concurrent_monitor::commit_wait (thread_context & thr) inline
Commit wait if event count has not changed; otherwise, cancel wait.
Returns true if committed, false if canceled.
Definition at line 139 of file concurrent_monitor.h.
References __TBB_ASSERT, tbb::internal::__TBB_load_relaxed(), tbb::internal::concurrent_monitor::thread_context::aborted, tbb::internal::eid_user_abort, tbb::internal::concurrent_monitor::thread_context::epoch, tbb::internal::concurrent_monitor::thread_context::in_waitset, tbb::internal::binary_semaphore::P(), tbb::internal::concurrent_monitor::thread_context::ready, tbb::internal::concurrent_monitor::thread_context::semaphore(), and tbb::internal::throw_exception().
Referenced by tbb::interface7::internal::task_arena_base::internal_execute(), tbb::internal::concurrent_queue_base_v3::internal_insert_item(), and tbb::internal::concurrent_queue_base_v3::internal_pop().
{
         const bool do_it = thr.epoch == __TBB_load_relaxed(epoch);
         // this check is just an optimization
         if( do_it ) {
             __TBB_ASSERT( thr.ready, "use of commit_wait() without prior prepare_wait()");
             thr.semaphore().P();
             __TBB_ASSERT( !thr.in_waitset, "still in the queue?" );
             if( thr.aborted )
                 throw_exception( eid_user_abort );
         } else {
             cancel_wait( thr );
         }
         return do_it;
     }
template<typename P > void tbb::internal::concurrent_monitor::notify (const P & predicate) inline
Notify waiting threads of the event that satisfies the given predicate.
Definition at line 173 of file concurrent_monitor.h.
References tbb::atomic_fence().
Referenced by tbb::internal::concurrent_queue_base_v3::internal_insert_if_not_full(), tbb::internal::concurrent_queue_base_v3::internal_insert_item(), tbb::internal::concurrent_queue_base_v3::internal_pop(), tbb::internal::concurrent_queue_base_v3::internal_pop_if_present(), and tbb::interface7::internal::delegated_task::~delegated_task().
 {atomic_fence(); notify_relaxed( predicate );}
void tbb::internal::concurrent_monitor::notify_all () inline
Notify all waiting threads of the event.
Definition at line 167 of file concurrent_monitor.h.
References tbb::atomic_fence().
 {atomic_fence(); notify_all_relaxed();}
void tbb::internal::concurrent_monitor::notify_all_relaxed ()
Notify all waiting threads of the event; Relaxed version.
Definition at line 88 of file concurrent_monitor.cpp.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), tbb::internal::circular_doubly_linked_list_with_sentinel::clear(), tbb::internal::circular_doubly_linked_list_with_sentinel::empty(), tbb::internal::circular_doubly_linked_list_with_sentinel::end(), end, tbb::internal::concurrent_monitor::thread_context::epoch, tbb::internal::circular_doubly_linked_list_with_sentinel::flush_to(), tbb::internal::circular_doubly_linked_list_with_sentinel::front(), tbb::internal::concurrent_monitor::thread_context::in_waitset, mutex_ec, tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next, tbb::internal::concurrent_monitor::thread_context::semaphore(), to_thread_context(), tbb::internal::binary_semaphore::V(), and waitset_ec.
{
     if( waitset_ec.empty() )
         return;
     waitset_t temp;
     const waitset_node_t* end;
     {
         tbb::spin_mutex::scoped_lock l( mutex_ec );
         __TBB_store_relaxed( epoch, __TBB_load_relaxed(epoch) + 1 );
         waitset_ec.flush_to( temp );
         end = temp.end();
         for( waitset_node_t* n=temp.front(); n!=end; n=n->next )
             to_thread_context(n)->in_waitset = false;
     }
     waitset_node_t* nxt;
     for( waitset_node_t* n=temp.front(); n!=end; n=nxt ) {
         nxt = n->next;
         to_thread_context(n)->semaphore().V();
     }
 #if TBB_USE_ASSERT
     temp.clear();
 #endif
 }
void tbb::internal::concurrent_monitor::notify_one () inline
Notify one thread about the event.
Definition at line 161 of file concurrent_monitor.h.
References tbb::atomic_fence().
Referenced by tbb::interface7::internal::task_arena_base::internal_execute(), and tbb::internal::generic_scheduler::nested_arena_exit().
 {atomic_fence(); notify_one_relaxed();}
void tbb::internal::concurrent_monitor::notify_one_relaxed ()
Notify one thread about the event. Relaxed version.
Definition at line 70 of file concurrent_monitor.cpp.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), tbb::internal::circular_doubly_linked_list_with_sentinel::empty(), tbb::internal::circular_doubly_linked_list_with_sentinel::end(), end, tbb::internal::concurrent_monitor::thread_context::epoch, tbb::internal::circular_doubly_linked_list_with_sentinel::front(), tbb::internal::concurrent_monitor::thread_context::in_waitset, mutex_ec, tbb::internal::circular_doubly_linked_list_with_sentinel::remove(), tbb::internal::concurrent_monitor::thread_context::semaphore(), to_thread_context(), tbb::internal::binary_semaphore::V(), and waitset_ec.
{
     if( waitset_ec.empty() )
         return;
     waitset_node_t* n;
     const waitset_node_t* end = waitset_ec.end();
     {
         tbb::spin_mutex::scoped_lock l( mutex_ec );
         __TBB_store_relaxed( epoch, __TBB_load_relaxed(epoch) + 1 );
         n = waitset_ec.front();
         if( n!=end ) {
             waitset_ec.remove( *n );
             to_thread_context(n)->in_waitset = false;
         }
     }
     if( n!=end )
         to_thread_context(n)->semaphore().V();
 }
template<typename P > void tbb::internal::concurrent_monitor::notify_relaxed (const P & predicate)
Notify waiting threads of the event that satisfies the given predicate; Relaxed version.
Definition at line 208 of file concurrent_monitor.h.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), tbb::internal::circular_doubly_linked_list_with_sentinel::add(), tbb::internal::circular_doubly_linked_list_with_sentinel::clear(), tbb::internal::concurrent_monitor::thread_context::context, tbb::internal::circular_doubly_linked_list_with_sentinel::end(), tbb::internal::circular_doubly_linked_list_with_sentinel::front(), tbb::internal::concurrent_monitor::thread_context::in_waitset, tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::next, and tbb::internal::circular_doubly_linked_list_with_sentinel::node_t::prev.
{
         if( waitset_ec.empty() )
             return;
         waitset_t temp;
         waitset_node_t* nxt;
         const waitset_node_t* end = waitset_ec.end();
         {
             tbb::spin_mutex::scoped_lock l( mutex_ec );
             __TBB_store_relaxed(epoch, __TBB_load_relaxed(epoch) + 1);
             for( waitset_node_t* n=waitset_ec.last(); n!=end; n=nxt ) {
                 nxt = n->prev;
                 thread_context* thr = to_thread_context( n );
                 if( predicate( thr->context ) ) {
                     waitset_ec.remove( *n );
                     thr->in_waitset = false;
                     temp.add( n );
                 }
             }
         }
         end = temp.end();
         for( waitset_node_t* n=temp.front(); n!=end; n=nxt ) {
             nxt = n->next;
             to_thread_context(n)->semaphore().V();
         }
 #if TBB_USE_ASSERT
         temp.clear();
 #endif
 }
void tbb::internal::concurrent_monitor::prepare_wait (thread_context & thr, uintptr_t ctx = 0)
prepare wait by inserting 'thr' into the wait queue
Definition at line 36 of file concurrent_monitor.cpp.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), tbb::internal::circular_doubly_linked_list_with_sentinel::add(), tbb::atomic_fence(), tbb::internal::concurrent_monitor::thread_context::context, tbb::internal::concurrent_monitor::thread_context::epoch, tbb::internal::concurrent_monitor::thread_context::in_waitset, mutex_ec, tbb::internal::binary_semaphore::P(), tbb::internal::concurrent_monitor::thread_context::ready, tbb::internal::concurrent_monitor::thread_context::semaphore(), tbb::internal::concurrent_monitor::thread_context::skipped_wakeup, and waitset_ec.
Referenced by tbb::interface7::internal::task_arena_base::internal_execute(), tbb::internal::concurrent_queue_base_v3::internal_insert_item(), and tbb::internal::concurrent_queue_base_v3::internal_pop().
{
     if( !thr.ready )
         thr.init();
     // this is good place to pump previous skipped wakeup
     else if( thr.skipped_wakeup ) {
         thr.skipped_wakeup = false;
         thr.semaphore().P();
     }
     thr.context = ctx;
     thr.in_waitset = true;
     {
         tbb::spin_mutex::scoped_lock l( mutex_ec );
         __TBB_store_relaxed( thr.epoch, __TBB_load_relaxed(epoch) );
         waitset_ec.add( (waitset_t::node_t*)&thr );
     }
     atomic_fence();
 }
thread_context* tbb::internal::concurrent_monitor::to_thread_context (waitset_node_t * n) inline private
Definition at line 188 of file concurrent_monitor.h.
Referenced by abort_all_relaxed(), notify_all_relaxed(), and notify_one_relaxed().
 { return static_cast<thread_context*>(n); }
template<typename WaitUntil , typename Context > void tbb::internal::concurrent_monitor::wait (WaitUntil until, Context on)
Wait for a condition to be satisfied with waiting-on context.
Definition at line 192 of file concurrent_monitor.h.
 {
     bool slept = false;
     thread_context thr_ctx;
     prepare_wait( thr_ctx, on() );
     while( !until() ) {
         if( (slept = commit_wait( thr_ctx ) )==true )
             if( until() ) break;
         slept = false;
         prepare_wait( thr_ctx, on() );
     }
     if( !slept )
         cancel_wait( thr_ctx );
 }
Member Data Documentation
__TBB_atomic unsigned tbb::internal::concurrent_monitor::epoch private
Definition at line 187 of file concurrent_monitor.h.
tbb::spin_mutex tbb::internal::concurrent_monitor::mutex_ec private
Definition at line 185 of file concurrent_monitor.h.
Referenced by abort_all_relaxed(), cancel_wait(), notify_all_relaxed(), notify_one_relaxed(), and prepare_wait().
waitset_t tbb::internal::concurrent_monitor::waitset_ec private
Definition at line 186 of file concurrent_monitor.h.
Referenced by abort_all_relaxed(), cancel_wait(), notify_all_relaxed(), notify_one_relaxed(), prepare_wait(), and ~concurrent_monitor().
The documentation for this class was generated from the following files:
concurrent_monitor.h
concurrent_monitor.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.