Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type Class Reference
tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type Class Reference
#include <_concurrent_unordered_impl.h>
Public Types
typedef concurrent_unordered_base::size_type size_type
Type for size of a range.
typedef concurrent_unordered_base::value_type value_type
typedef concurrent_unordered_base::reference reference
typedef concurrent_unordered_base::difference_type difference_type
typedef concurrent_unordered_base::const_iterator iterator
Public Member Functions
bool empty () const
True if range is empty.
bool is_divisible () const
True if range can be partitioned into two subranges.
const_range_type (const_range_type &r, split)
Split range.
const_range_type (const concurrent_unordered_base &a_table)
Init range with container and grainsize specified.
iterator begin () const
iterator end () const
size_type grainsize () const
The grain size for this range.
void set_midpoint () const
Set my_midpoint_node to point approximately half way between my_begin_node and my_end_node.
Private Attributes
const concurrent_unordered_base & my_table
raw_const_iterator my_begin_node
raw_const_iterator my_end_node
raw_const_iterator my_midpoint_node
Detailed Description
template<typename Traits>
class tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type
Definition at line 878 of file _concurrent_unordered_impl.h.
Member Typedef Documentation
template<typename Traits> typedef concurrent_unordered_base::difference_type tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::difference_type
Definition at line 888 of file _concurrent_unordered_impl.h.
template<typename Traits> typedef concurrent_unordered_base::const_iterator tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::iterator
Definition at line 889 of file _concurrent_unordered_impl.h.
template<typename Traits> typedef concurrent_unordered_base::reference tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::reference
Definition at line 887 of file _concurrent_unordered_impl.h.
template<typename Traits> typedef concurrent_unordered_base::size_type tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::size_type
Type for size of a range.
Definition at line 885 of file _concurrent_unordered_impl.h.
template<typename Traits> typedef concurrent_unordered_base::value_type tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::value_type
Definition at line 886 of file _concurrent_unordered_impl.h.
Constructor & Destructor Documentation
template<typename Traits> tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::const_range_type (const_range_type & r, split) inline
Split range.
Definition at line 899 of file _concurrent_unordered_impl.h.
References __TBB_ASSERT, tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::empty(), tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::my_end_node, tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::my_midpoint_node, and tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::set_midpoint().
                                                        :
             my_table(r.my_table), my_end_node(r.my_end_node)
         {
             r.my_end_node = my_begin_node = r.my_midpoint_node;
             __TBB_ASSERT( !empty(), "Splitting despite the range is not divisible" );
             __TBB_ASSERT( !r.empty(), "Splitting despite the range is not divisible" );
             set_midpoint();
             r.set_midpoint();
         }
template<typename Traits> tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::const_range_type (const concurrent_unordered_base & a_table) inline
Init range with container and grainsize specified.
Definition at line 909 of file _concurrent_unordered_impl.h.
                                                                      :
             my_table(a_table), my_begin_node(a_table.my_solist.begin()),
             my_end_node(a_table.my_solist.end())
         {
             set_midpoint();
         }
Member Function Documentation
template<typename Traits> iterator tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::begin () const inline
Definition at line 915 of file _concurrent_unordered_impl.h.
References tbb::interface5::internal::split_ordered_list< T, Allocator >::get_iterator(), and tbb::interface5::internal::concurrent_unordered_base< Traits >::my_solist.
 { return my_table.my_solist.get_iterator(my_begin_node); }
template<typename Traits> bool tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::empty () const inline
True if range is empty.
Definition at line 892 of file _concurrent_unordered_impl.h.
Referenced by tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::const_range_type().
 {return my_begin_node == my_end_node;}
template<typename Traits> iterator tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::end () const inline
Definition at line 916 of file _concurrent_unordered_impl.h.
References tbb::interface5::internal::split_ordered_list< T, Allocator >::get_iterator(), and tbb::interface5::internal::concurrent_unordered_base< Traits >::my_solist.
 { return my_table.my_solist.get_iterator(my_end_node); }
template<typename Traits> size_type tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::grainsize () const inline
The grain size for this range.
Definition at line 918 of file _concurrent_unordered_impl.h.
 { return 1; }
template<typename Traits> bool tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::is_divisible () const inline
True if range can be partitioned into two subranges.
Definition at line 895 of file _concurrent_unordered_impl.h.
{
             return my_midpoint_node != my_end_node;
         }
template<typename Traits> void tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::set_midpoint () const inline
Set my_midpoint_node to point approximately half way between my_begin_node and my_end_node.
Definition at line 921 of file _concurrent_unordered_impl.h.
References __TBB_ASSERT, __TBB_ReverseBits(), tbb::interface5::internal::split_ordered_list< T, Allocator >::first_real_iterator(), tbb::interface5::internal::concurrent_unordered_base< Traits >::get_bucket(), tbb::interface5::internal::concurrent_unordered_base< Traits >::get_parent(), tbb::interface5::internal::concurrent_unordered_base< Traits >::is_initialized(), tbb::interface5::internal::concurrent_unordered_base< Traits >::my_number_of_buckets, and tbb::interface5::internal::concurrent_unordered_base< Traits >::my_solist.
Referenced by tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::const_range_type().
{
             if( my_begin_node == my_end_node ) // not divisible
                 my_midpoint_node = my_end_node;
             else {
                 sokey_t begin_key = solist_t::get_safe_order_key(my_begin_node);
                 sokey_t end_key = solist_t::get_safe_order_key(my_end_node);
                 size_t mid_bucket = __TBB_ReverseBits( begin_key + (end_key-begin_key)/2 ) % my_table.my_number_of_buckets;
                 while ( !my_table.is_initialized(mid_bucket) ) mid_bucket = my_table.get_parent(mid_bucket);
                 if(__TBB_ReverseBits(mid_bucket) > begin_key) {
                     // found a dummy_node between begin and end
                     my_midpoint_node = my_table.my_solist.first_real_iterator(my_table.get_bucket( mid_bucket ));
                 }
                 else {
                     // didn't find a dummy node between begin and end.
                     my_midpoint_node = my_end_node;
                 }
 #if TBB_USE_ASSERT
                 {
                     sokey_t mid_key = solist_t::get_safe_order_key(my_midpoint_node);
                     __TBB_ASSERT( begin_key < mid_key, "my_begin_node is after my_midpoint_node" );
                     __TBB_ASSERT( mid_key <= end_key, "my_midpoint_node is after my_end_node" );
                 }
 #endif // TBB_USE_ASSERT
             }
         }
Member Data Documentation
template<typename Traits> raw_const_iterator tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::my_begin_node private
Definition at line 880 of file _concurrent_unordered_impl.h.
template<typename Traits> raw_const_iterator tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::my_end_node private
Definition at line 881 of file _concurrent_unordered_impl.h.
Referenced by tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::const_range_type().
template<typename Traits> raw_const_iterator tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::my_midpoint_node mutable private
Definition at line 882 of file _concurrent_unordered_impl.h.
Referenced by tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::const_range_type().
template<typename Traits> const concurrent_unordered_base& tbb::interface5::internal::concurrent_unordered_base< Traits >::const_range_type::my_table private
Definition at line 879 of file _concurrent_unordered_impl.h.
The documentation for this class was generated from the following file:
_concurrent_unordered_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.