Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::FastRandom Class Reference
tbb::internal::FastRandom Class Reference
A fast random number generator.
#include <tbb_misc.h>
Public Member Functions
unsigned short get ()
Get a random number.
unsigned short get (unsigned &seed)
Get a random number for the given seed; update the seed for next use.
FastRandom (void *unique_ptr)
Construct a random number generator.
FastRandom (uint32_t seed)
FastRandom (uint64_t seed)
template<typename T >
void init (T seed)
void init (uint64_t seed, int_to_type< 8 >)
void init (uint32_t seed, int_to_type< 4 >)
Private Attributes
unsigned x
unsigned c
Static Private Attributes
static const unsigned a = 0x9e3779b1
Detailed Description
A fast random number generator.
Uses linear congruential method.
Definition at line 131 of file tbb_misc.h.
Constructor & Destructor Documentation
tbb::internal::FastRandom::FastRandom (void * unique_ptr) inline
Construct a random number generator.
Definition at line 153 of file tbb_misc.h.
 { init(uintptr_t(unique_ptr)); }
tbb::internal::FastRandom::FastRandom (uint32_t seed) inline
Definition at line 154 of file tbb_misc.h.
 { init(seed); }
tbb::internal::FastRandom::FastRandom (uint64_t seed) inline
Definition at line 155 of file tbb_misc.h.
 { init(seed); }
Member Function Documentation
unsigned short tbb::internal::FastRandom::get () inline
Get a random number.
Definition at line 142 of file tbb_misc.h.
Referenced by tbb::internal::arena::occupy_free_slot_in_range(), tbb::internal::task_stream< num_priority_levels >::push(), and tbb::internal::generic_scheduler::steal_task().
{
         return get(x);
     }
unsigned short tbb::internal::FastRandom::get (unsigned & seed) inline
Get a random number for the given seed; update the seed for next use.
Definition at line 146 of file tbb_misc.h.
References __TBB_ASSERT.
{
         unsigned short r = (unsigned short)(seed>>16);
         __TBB_ASSERT(c&1, "c must be odd for big rng period");
         seed = seed*a+c;
         return r;
     }
template<typename T > void tbb::internal::FastRandom::init (T seed) inline
Definition at line 157 of file tbb_misc.h.
{
         init(seed,int_to_type<sizeof(seed)>());
     }
void tbb::internal::FastRandom::init (uint64_t seed, int_to_type< 8 >) inline
Definition at line 160 of file tbb_misc.h.
{
         init(uint32_t((seed>>32)+seed), int_to_type<4>());
     }
void tbb::internal::FastRandom::init (uint32_t seed, int_to_type< 4 >) inline
Definition at line 163 of file tbb_misc.h.
References tbb::internal::GetPrime().
{
 #if __TBB_OLD_PRIMES_RNG
         x = seed;
         a = GetPrime( seed );
 #else
         // threads use different seeds for unique sequences
         c = (seed|1)*0xba5703f5; // c must be odd, shuffle by a prime number
         x = c^(seed>>1); // also shuffle x for the first get() invocation
 #endif
     }
Member Data Documentation
const unsigned tbb::internal::FastRandom::a = 0x9e3779b1 static private
Definition at line 138 of file tbb_misc.h.
unsigned tbb::internal::FastRandom::c private
Definition at line 137 of file tbb_misc.h.
unsigned tbb::internal::FastRandom::x private
Definition at line 137 of file tbb_misc.h.
The documentation for this class was generated from the following file:
tbb_misc.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.