Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::fixed_pool Class Reference
tbb::interface6::fixed_pool Class Reference
#include <memory_pool.h>
Public Member Functions
fixed_pool (void *buf, size_t size)
construct pool with underlying allocator
~fixed_pool ()
destroy pool
Public Member Functions inherited from tbb::interface6::internal::pool_base
void recycle ()
Reset pool to reuse its memory (free all objects at once)
void * malloc (size_t size)
The "malloc" analogue to allocate block of memory of size bytes.
void free (void *ptr)
The "free" analogue to discard a previously allocated piece of memory.
void * realloc (void *ptr, size_t size)
The "realloc" analogue complementing pool_malloc.
Static Private Member Functions
static void * allocate_request (intptr_t pool_id, size_t &bytes)
Private Attributes
void * my_buffer
size_t my_size
Additional Inherited Members
Protected Member Functions inherited from tbb::interface6::internal::pool_base
void destroy ()
destroy pool - must be called in a child class
Protected Attributes inherited from tbb::interface6::internal::pool_base
rml::MemoryPool * my_pool
Detailed Description
Definition at line 206 of file memory_pool.h.
Constructor & Destructor Documentation
tbb::interface6::fixed_pool::fixed_pool (void * buf, size_t size) inline
construct pool with underlying allocator
Definition at line 255 of file memory_pool.h.
References allocate_request(), and tbb::internal::throw_exception().
                                                     : my_buffer(buf), my_size(size) {
     if (!buf || !size)
         // TODO: improve support for mode with exceptions disabled
         tbb::internal::throw_exception(std::invalid_argument("Zero in parameter is invalid"));
     rml::MemPoolPolicy args(allocate_request, 0, size, /*fixedPool=*/true);
     rml::MemPoolError res = rml::pool_create_v1(intptr_t(this), &args, &my_pool);
     if (res!=rml::POOL_OK)
         tbb::internal::throw_exception(std::runtime_error("Can't create pool"));
 }
tbb::interface6::fixed_pool::~fixed_pool () inline
destroy pool
Definition at line 215 of file memory_pool.h.
References tbb::interface6::internal::pool_base::destroy().
 { destroy(); }
Member Function Documentation
void * tbb::interface6::fixed_pool::allocate_request (intptr_t pool_id, size_t & bytes) inline static private
Definition at line 264 of file memory_pool.h.
References __TBBMALLOC_ASSERT, and my_size.
Referenced by fixed_pool().
{
     fixed_pool &self = *reinterpret_cast<fixed_pool*>(pool_id);
     __TBBMALLOC_ASSERT(0 != self.my_size, "The buffer must not be used twice.");
     bytes = self.my_size;
     self.my_size = 0; // remember that buffer has been used
     return self.my_buffer;
 }
Member Data Documentation
void* tbb::interface6::fixed_pool::my_buffer private
Definition at line 207 of file memory_pool.h.
size_t tbb::interface6::fixed_pool::my_size private
Definition at line 208 of file memory_pool.h.
Referenced by allocate_request().
The documentation for this class was generated from the following file:
memory_pool.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.