Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::fast_reverse_vector< T, max_segments > Class Template Reference
tbb::internal::fast_reverse_vector< T, max_segments > Class Template Reference
Vector that grows without reallocations, and stores items in the reverse order.
#include <scheduler_utility.h>
Public Member Functions
fast_reverse_vector (T *initial_segment, size_t segment_size)
~fast_reverse_vector ()
size_t size () const
void push_back (const T &val)
void copy_memory (T *dst) const
Copies the contents of the vector into the dst array.
Protected Attributes
T * m_cur_segment
The current (not completely filled) segment.
size_t m_cur_segment_size
Capacity of m_cur_segment.
size_t m_pos
Insertion position in m_cur_segment.
T * m_segments [max_segments]
Array of segments (has fixed size specified by the second template parameter)
size_t m_num_segments
Number of segments (the size of m_segments)
size_t m_size
Number of items in the segments in m_segments.
Detailed Description
template<typename T, size_t max_segments = 16>
class tbb::internal::fast_reverse_vector< T, max_segments >
Vector that grows without reallocations, and stores items in the reverse order.
Requires to initialize its first segment with a preallocated memory chunk (usually it is static array or an array allocated on the stack). The second template parameter specifies maximal number of segments. Each next segment is twice as large as the previous one.
Definition at line 60 of file scheduler_utility.h.
Constructor & Destructor Documentation
template<typename T, size_t max_segments = 16> tbb::internal::fast_reverse_vector< T, max_segments >::fast_reverse_vector (T * initial_segment, size_t segment_size) inline
Definition at line 63 of file scheduler_utility.h.
References __TBB_ASSERT.
         : m_cur_segment(initial_segment)
         , m_cur_segment_size(segment_size)
         , m_pos(segment_size)
         , m_num_segments(0)
         , m_size(0)
     {
         __TBB_ASSERT ( initial_segment && segment_size, "Nonempty initial segment must be supplied");
     }
template<typename T, size_t max_segments = 16> tbb::internal::fast_reverse_vector< T, max_segments >::~fast_reverse_vector () inline
Definition at line 73 of file scheduler_utility.h.
References tbb::internal::NFS_Free().
     {
         for ( size_t i = 1; i < m_num_segments; ++i )
             NFS_Free( m_segments[i] );
     }
Member Function Documentation
template<typename T, size_t max_segments = 16> void tbb::internal::fast_reverse_vector< T, max_segments >::copy_memory (T * dst) const inline
Copies the contents of the vector into the dst array.
Can only be used when T is a POD type, as copying does not invoke copy constructors.
Definition at line 96 of file scheduler_utility.h.
Referenced by tbb::internal::generic_scheduler::enqueue(), and tbb::internal::generic_scheduler::local_spawn().
     {
         size_t sz = m_cur_segment_size - m_pos;
         memcpy( dst, m_cur_segment + m_pos, sz * sizeof(T) );
         dst += sz;
         sz = m_cur_segment_size / 2;
         for ( long i = (long)m_num_segments - 2; i >= 0; --i ) {
             memcpy( dst, m_segments[i], sz * sizeof(T) );
             dst += sz;
             sz /= 2;
         }
     }
template<typename T, size_t max_segments = 16> void tbb::internal::fast_reverse_vector< T, max_segments >::push_back (const T & val) inline
Definition at line 81 of file scheduler_utility.h.
References __TBB_ASSERT, and tbb::internal::NFS_Allocate().
Referenced by tbb::internal::generic_scheduler::enqueue(), and tbb::internal::generic_scheduler::local_spawn().
     {
         if ( !m_pos ) {
             if ( !m_num_segments ) m_segments[m_num_segments++] = m_cur_segment;
             m_size += m_cur_segment_size;
             m_cur_segment_size *= 2;
             m_pos = m_cur_segment_size;
             m_segments[m_num_segments++] = m_cur_segment = (T*)NFS_Allocate( m_cur_segment_size, sizeof(T), NULL );
             __TBB_ASSERT ( m_num_segments < max_segments, "Maximal capacity exceeded" );
         }
         m_cur_segment[--m_pos] = val;
     }
template<typename T, size_t max_segments = 16> size_t tbb::internal::fast_reverse_vector< T, max_segments >::size () const inline
Definition at line 79 of file scheduler_utility.h.
Referenced by tbb::internal::generic_scheduler::enqueue(), and tbb::internal::generic_scheduler::local_spawn().
 { return m_size + m_cur_segment_size - m_pos; }
Member Data Documentation
template<typename T, size_t max_segments = 16> T* tbb::internal::fast_reverse_vector< T, max_segments >::m_cur_segment protected
The current (not completely filled) segment.
Definition at line 111 of file scheduler_utility.h.
template<typename T, size_t max_segments = 16> size_t tbb::internal::fast_reverse_vector< T, max_segments >::m_cur_segment_size protected
Capacity of m_cur_segment.
Definition at line 114 of file scheduler_utility.h.
template<typename T, size_t max_segments = 16> size_t tbb::internal::fast_reverse_vector< T, max_segments >::m_num_segments protected
Number of segments (the size of m_segments)
Definition at line 123 of file scheduler_utility.h.
template<typename T, size_t max_segments = 16> size_t tbb::internal::fast_reverse_vector< T, max_segments >::m_pos protected
Insertion position in m_cur_segment.
Definition at line 117 of file scheduler_utility.h.
template<typename T, size_t max_segments = 16> T* tbb::internal::fast_reverse_vector< T, max_segments >::m_segments[max_segments] protected
Array of segments (has fixed size specified by the second template parameter)
Definition at line 120 of file scheduler_utility.h.
template<typename T, size_t max_segments = 16> size_t tbb::internal::fast_reverse_vector< T, max_segments >::m_size protected
Number of items in the segments in m_segments.
Definition at line 126 of file scheduler_utility.h.
The documentation for this class was generated from the following file:
scheduler_utility.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.