Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::finish_reduce< Body > Class Template Reference
tbb::interface9::internal::finish_reduce< Body > Class Template Reference
Algorithms
Task type used to combine the partial results of parallel_reduce.
#include <parallel_reduce.h>
Private Member Functions
finish_reduce (reduction_context context_)
~finish_reduce ()
task * execute () __TBB_override
Should be overridden by derived classes.
Private Attributes
bool has_right_zombie
Pointer to body, or NULL if the left child has not yet finished.
const reduction_context my_context
Body * my_body
aligned_space< Body > zombie_space
Friends
template<typename Range , typename Body_ , typename Partitioner >
class start_reduce
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Public Member Functions inherited from tbb::interface9::internal::flag_task
flag_task ()
task * execute () __TBB_override
Should be overridden by derived classes.
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
virtual void __TBB_EXPORTED_METHOD note_affinity (affinity_id id)
Invoked by scheduler to notify task that it ran on unexpected thread.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions inherited from tbb::interface9::internal::flag_task
static void mark_task_stolen (task &t)
static bool is_peer_stolen (task &t)
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Public Attributes inherited from tbb::interface9::internal::flag_task
tbb::atomic< bool > my_child_stolen
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
template<typename Body>
class tbb::interface9::internal::finish_reduce< Body >
Task type used to combine the partial results of parallel_reduce.
Definition at line 49 of file parallel_reduce.h.
Constructor & Destructor Documentation
template<typename Body > tbb::interface9::internal::finish_reduce< Body >::finish_reduce (reduction_context context_) inline private
Definition at line 55 of file parallel_reduce.h.
                                                     :
             has_right_zombie(false), // TODO: substitute by flag_task::child_stolen?
             my_context(context_),
             my_body(NULL)
         {
         }
template<typename Body > tbb::interface9::internal::finish_reduce< Body >::~finish_reduce () inline private
Definition at line 61 of file parallel_reduce.h.
References tbb::aligned_space< T, N >::begin().
{
             if( has_right_zombie )
                 zombie_space.begin()->~Body();
         }
Member Function Documentation
template<typename Body > task* tbb::interface9::internal::finish_reduce< Body >::execute () inline private virtual
Should be overridden by derived classes.
Implements tbb::task.
Definition at line 65 of file parallel_reduce.h.
References tbb::aligned_space< T, N >::begin(), tbb::internal::itt_store_word_with_release(), tbb::interface9::internal::left_child, parent, and s.
{
             if( has_right_zombie ) {
                 // Right child was stolen.
                 Body* s = zombie_space.begin();
                 my_body->join( *s );
                 // Body::join() won't be called if canceled. Defer destruction to destructor
             }
             if( my_context==left_child )
                 itt_store_word_with_release( static_cast<finish_reduce*>(parent())->my_body, my_body );
             return NULL;
         }
Friends And Related Function Documentation
template<typename Body > template<typename Range , typename Body_ , typename Partitioner > friend class start_reduce friend
Definition at line 77 of file parallel_reduce.h.
Member Data Documentation
template<typename Body > bool tbb::interface9::internal::finish_reduce< Body >::has_right_zombie private
Pointer to body, or NULL if the left child has not yet finished.
Definition at line 51 of file parallel_reduce.h.
Referenced by tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::execute().
template<typename Body > Body* tbb::interface9::internal::finish_reduce< Body >::my_body private
Definition at line 53 of file parallel_reduce.h.
Referenced by tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::execute().
template<typename Body > const reduction_context tbb::interface9::internal::finish_reduce< Body >::my_context private
Definition at line 52 of file parallel_reduce.h.
template<typename Body > aligned_space<Body> tbb::interface9::internal::finish_reduce< Body >::zombie_space private
Definition at line 54 of file parallel_reduce.h.
Referenced by tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::execute().
The documentation for this class was generated from the following file:
parallel_reduce.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.