Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::function_node< Input, Output, Policy, Allocator > Class Template Reference
tbb::flow::interface10::function_node< Input, Output, Policy, Allocator > Class Template Reference
Implements a function node that supports Input -> Output.
#include <flow_graph.h>
Public Types
typedef Input input_type
typedef Output output_type
typedef internal::function_input< input_type, output_type, Policy, Allocator > input_impl_type
typedef internal::function_input_queue< input_type, Allocator > input_queue_type
typedef internal::function_output< output_type > fOutput_type
typedef input_impl_type::predecessor_type predecessor_type
typedef fOutput_type::successor_type successor_type
Public Types inherited from tbb::flow::interface10::internal::function_input< Input, Output, Policy, Allocator >
typedef Input input_type
typedef Output output_type
typedef function_body< input_type, output_type > function_body_type
typedef function_input< Input, Output, Policy, Allocator > my_class
typedef function_input_base< Input, Policy, Allocator, my_class > base_type
typedef function_input_queue< input_type, Allocator > input_queue_type
Public Types inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, function_input< Input, Output, Policy, Allocator > >
typedef Input input_type
The input type of this receiver.
typedef receiver< input_type >::predecessor_type predecessor_type
typedef predecessor_cache< input_type, null_mutex > predecessor_cache_type
typedef function_input_queue< input_type, Allocator > input_queue_type
typedef Allocator::template rebind< input_queue_type >::other queue_allocator_type
Public Types inherited from tbb::flow::interface10::receiver< Input >
typedef Input input_type
The input type of this receiver.
typedef internal::async_helpers< Input >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::internal::function_output< Output >
typedef Output output_type
typedef sender< output_type >::successor_type successor_type
typedef broadcast_cache< output_type > broadcast_cache_type
Public Types inherited from tbb::flow::interface10::sender< Output >
typedef Output output_type
The output type of this sender.
typedef internal::async_helpers< Output >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
template<typename Body >
function_node (graph &g, size_t concurrency,)
Constructor.
function_node (const function_node &src)
Copy constructor.
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::internal::function_input< Input, Output, Policy, Allocator >
function_input (graph &g, size_t max_concurrency,)
function_input (const function_input &src)
Copy constructor.
~function_input ()
Body copy_function_object ()
output_type apply_body_impl (const input_type &i)
task * apply_body_impl_bypass (const input_type &i)
Public Member Functions inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, function_input< Input, Output, Policy, Allocator > >
__TBB_STATIC_ASSERT (!((internal::has_policy< queueing, Policy >::value)&&(internal::has_policy< rejecting, Policy >::value)),"queueing and rejecting policies can't be specified simultaneously")
function_input_base (graph &g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(size_t max_concurrency, node_priority_t priority))
Constructor for function_input_base.
function_input_base (const function_input_base &src)
Copy constructor.
virtual ~function_input_base ()
Destructor.
task * try_put_task (const input_type &t) __TBB_override
Put item to successor; return task to run the successor if possible.
bool register_predecessor (predecessor_type &src) __TBB_override
Adds src to the list of cached predecessors.
bool remove_predecessor (predecessor_type &src) __TBB_override
Removes src from the list of cached predecessors.
Public Member Functions inherited from tbb::flow::interface10::receiver< Input >
bool try_put (const typename internal::async_helpers< Input >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< Input >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
Public Member Functions inherited from tbb::flow::interface10::internal::function_output< Output >
function_output ()
function_output (const function_output &)
bool register_successor (successor_type &r) __TBB_override
Adds a new successor to this node.
bool remove_successor (successor_type &r) __TBB_override
Removes a successor from this node.
task * try_put_task (const output_type &i)
broadcast_cache_type & successors ()
Public Member Functions inherited from tbb::flow::interface10::sender< Output >
virtual bool try_get (Output &)
Request an item from the sender.
virtual bool try_reserve (Output &)
Reserves an item in the sender.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
virtual bool try_release ()
Releases the reserved item.
virtual bool try_consume ()
Consumes the reserved item.
Protected Member Functions
internal::broadcast_cache< output_type > & successors () __TBB_override
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::function_input< Input, Output, Policy, Allocator >
void reset_function_input (reset_flags f)
Protected Member Functions inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, function_input< Input, Output, Policy, Allocator > >
void reset_function_input_base (reset_flags f)
void reset_receiver (reset_flags f) __TBB_override
put receiver back in initial state
graph & graph_reference () __TBB_override
task * try_get_postponed_task (const input_type &i)
Protected Member Functions inherited from tbb::flow::interface10::receiver< Input >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Protected Member Functions inherited from tbb::flow::interface10::sender< Output >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Friends
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Protected Attributes inherited from tbb::flow::interface10::internal::function_input< Input, Output, Policy, Allocator >
function_body_type * my_body
function_body_type * my_init_body
Protected Attributes inherited from tbb::flow::interface10::internal::function_input_base< Input, Policy, Allocator, function_input< Input, Output, Policy, Allocator > >
graph & my_graph_ref
const size_t my_max_concurrency
size_t my_concurrency
input_queue_type * my_queue
predecessor_cache< input_type, null_mutex > my_predecessors
Protected Attributes inherited from tbb::flow::interface10::internal::function_output< Output >
broadcast_cache_type my_successors
Detailed Description
template<typename Input, typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>>
class tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >
Implements a function node that supports Input -> Output.
Definition at line 1122 of file flow_graph.h.
Member Typedef Documentation
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> typedef internal::function_output<output_type> tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::fOutput_type
Definition at line 1128 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> typedef internal::function_input<input_type,output_type,Policy,Allocator> tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::input_impl_type
Definition at line 1126 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> typedef internal::function_input_queue<input_type, Allocator> tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::input_queue_type
Definition at line 1127 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> typedef Input tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::input_type
Definition at line 1124 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> typedef Output tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::output_type
Definition at line 1125 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> typedef input_impl_type::predecessor_type tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::predecessor_type
Definition at line 1129 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> typedef fOutput_type::successor_type tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::successor_type
Definition at line 1130 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> template<typename Body > tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::function_node (graph & g, size_t concurrency) inline
Constructor.
Definition at line 1142 of file flow_graph.h.
References tbb::internal::fgt_node_with_body(), and tbb::flow::interface10::graph_node::my_graph.
       : graph_node(g), input_impl_type(g, concurrency, __TBB_FLOW_GRAPH_PRIORITY_ARG1(body, priority)) {
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_FUNCTION_NODE, &this->my_graph,
                 static_cast<receiver<input_type> *>(this), static_cast<sender<output_type> *>(this), this->my_body );
     }
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::function_node (const function_node< Input, Output, Policy, Allocator > & src) inline
Copy constructor.
Definition at line 1151 of file flow_graph.h.
References __TBB_override, tbb::internal::fgt_node_desc(), tbb::internal::fgt_node_with_body(), tbb::flow::interface10::graph_node::my_graph, and name.
                                               :
         graph_node(src.my_graph),
         input_impl_type(src),
         fOutput_type() {
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_FUNCTION_NODE, &this->my_graph,
                 static_cast<receiver<input_type> *>(this), static_cast<sender<output_type> *>(this), this->my_body );
     }
Member Function Documentation
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> void tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::reset_node (reset_flags f) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 1180 of file flow_graph.h.
{
         input_impl_type::reset_function_input(f);
         // TODO: use clear() instead.
         if(f & rf_clear_edges) {
             successors().clear();
             my_predecessors.clear();
         }
         __TBB_ASSERT(!(f & rf_clear_edges) || successors().empty(), "function_node successors not empty");
         __TBB_ASSERT(this->my_predecessors.empty(), "function_node predecessors not empty");
     }
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> internal::broadcast_cache<output_type>& tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::successors () inline protected virtual
Implements tbb::flow::interface10::internal::function_input< Input, Output, Policy, Allocator >.
Definition at line 1178 of file flow_graph.h.
 { return fOutput_type::my_successors; }
Friends And Related Function Documentation
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 1174 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 1175 of file flow_graph.h.
template<typename Input , typename Output = continue_msg, typename Policy = queueing, typename Allocator = cache_aligned_allocator<Input>> template<typename R , typename B > friend class run_and_put_task friend
Definition at line 1173 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.