Intel(R) Threading Building Blocks Doxygen Documentation: internal::forwarding_base Struct Reference
internal::forwarding_base Struct Reference abstract
#include <_flow_graph_join_impl.h>
Public Member Functions
forwarding_base (graph &g)
virtual ~forwarding_base ()
virtual task * decrement_port_count (bool handle_task)=0
virtual void increment_port_count ()=0
Public Attributes
graph & graph_ref
Detailed Description
Definition at line 30 of file _flow_graph_join_impl.h.
Constructor & Destructor Documentation
internal::forwarding_base::forwarding_base (graph & g) inline
Definition at line 31 of file _flow_graph_join_impl.h.
 : graph_ref(g) {}
virtual internal::forwarding_base::~forwarding_base () inline virtual
Definition at line 32 of file _flow_graph_join_impl.h.
References decrement_port_count(), increment_port_count(), and task.
 {}
Member Function Documentation
virtual task* internal::forwarding_base::decrement_port_count (bool handle_task) pure virtual
Implemented in internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >, internal::join_node_FE< queueing, InputTuple, OutputTuple >, and internal::join_node_FE< reserving, InputTuple, OutputTuple >.
Referenced by ~forwarding_base().
virtual void internal::forwarding_base::increment_port_count () pure virtual
Implemented in internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >, internal::join_node_FE< queueing, InputTuple, OutputTuple >, and internal::join_node_FE< reserving, InputTuple, OutputTuple >.
Referenced by ~forwarding_base().
Member Data Documentation
graph& internal::forwarding_base::graph_ref
Definition at line 38 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< reserving, InputTuple, OutputTuple >::decrement_port_count(), internal::join_node_FE< queueing, InputTuple, OutputTuple >::decrement_port_count(), and internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::fill_output_buffer().
The documentation for this struct was generated from the following file:
_flow_graph_join_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.