Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::internal::filter_node Class Reference
tbb::interface6::internal::filter_node Class Reference abstract
Abstract base class that represents a node in a parse tree underlying a filter_t.
#include <pipeline.h>
Public Member Functions
virtual void add_to (pipeline &)=0
Add concrete_filter to pipeline.
void add_ref ()
Increment reference count.
void remove_ref ()
Decrement reference count and delete if it becomes zero.
virtual ~filter_node ()
Protected Member Functions
filter_node ()
Private Attributes
tbb::atomic< intptr_t > ref_count
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
Abstract base class that represents a node in a parse tree underlying a filter_t.
These nodes are always heap-allocated and can be shared by filter_t objects.
Definition at line 507 of file pipeline.h.
Constructor & Destructor Documentation
tbb::interface6::internal::filter_node::filter_node () inline protected
Definition at line 511 of file pipeline.h.
                   {
         ref_count = 0;
 #ifdef __TBB_TEST_FILTER_NODE_COUNT
         ++(__TBB_TEST_FILTER_NODE_COUNT);
 #endif
     }
virtual tbb::interface6::internal::filter_node::~filter_node () inline virtual
Definition at line 528 of file pipeline.h.
{
 #ifdef __TBB_TEST_FILTER_NODE_COUNT
         --(__TBB_TEST_FILTER_NODE_COUNT);
 #endif
     }
Member Function Documentation
void tbb::interface6::internal::filter_node::add_ref () inline
Increment reference count.
Definition at line 521 of file pipeline.h.
Referenced by tbb::interface6::internal::filter_node_join::filter_node_join().
 {++ref_count;}
virtual void tbb::interface6::internal::filter_node::add_to (pipeline &) pure virtual
Add concrete_filter to pipeline.
Implemented in tbb::interface6::internal::filter_node_join, and tbb::interface6::internal::filter_node_leaf< T, U, Body >.
Referenced by tbb::interface6::internal::filter_node_join::add_to().
void tbb::interface6::internal::filter_node::remove_ref () inline
Decrement reference count and delete if it becomes zero.
Definition at line 523 of file pipeline.h.
References __TBB_ASSERT.
Referenced by tbb::interface6::internal::filter_node_join::~filter_node_join().
                       {
         __TBB_ASSERT(ref_count>0,"ref_count underflow");
         if( --ref_count==0 )
             delete this;
     }
Member Data Documentation
tbb::atomic<intptr_t> tbb::interface6::internal::filter_node::ref_count private
Count must be atomic because it is hidden state for user, but might be shared by threads.
Definition at line 509 of file pipeline.h.
The documentation for this class was generated from the following file:
pipeline.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.