Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::internal::filter_node_join Class Reference
tbb::interface6::internal::filter_node_join Class Reference
Node in parse tree representing join of two filters.
#include <pipeline.h>
Public Member Functions
filter_node_join (filter_node &x, filter_node &y)
Public Member Functions inherited from tbb::interface6::internal::filter_node
void add_ref ()
Increment reference count.
void remove_ref ()
Decrement reference count and delete if it becomes zero.
virtual ~filter_node ()
Private Member Functions
~filter_node_join ()
void add_to (pipeline &p) __TBB_override
Add concrete_filter to pipeline.
Private Attributes
filter_node & left
filter_node & right
Friends
class filter_node
Additional Inherited Members
Protected Member Functions inherited from tbb::interface6::internal::filter_node
filter_node ()
Detailed Description
Node in parse tree representing join of two filters.
Definition at line 549 of file pipeline.h.
Constructor & Destructor Documentation
tbb::interface6::internal::filter_node_join::~filter_node_join () inline private
Definition at line 553 of file pipeline.h.
References tbb::interface6::internal::filter_node::remove_ref().
{
        left.remove_ref();
        right.remove_ref();
     }
tbb::interface6::internal::filter_node_join::filter_node_join (filter_node & x, filter_node & y) inline
Definition at line 562 of file pipeline.h.
References tbb::interface6::internal::filter_node::add_ref().
                                                        : left(x), right(y) {
        left.add_ref();
        right.add_ref();
     }
Member Function Documentation
void tbb::interface6::internal::filter_node_join::add_to (pipeline &) inline private virtual
Add concrete_filter to pipeline.
Implements tbb::interface6::internal::filter_node.
Definition at line 557 of file pipeline.h.
References tbb::interface6::internal::filter_node::add_to(), and p.
{
         left.add_to(p);
         right.add_to(p);
     }
Friends And Related Function Documentation
friend class filter_node friend
Definition at line 550 of file pipeline.h.
Member Data Documentation
filter_node& tbb::interface6::internal::filter_node_join::left private
Definition at line 551 of file pipeline.h.
filter_node& tbb::interface6::internal::filter_node_join::right private
Definition at line 552 of file pipeline.h.
The documentation for this class was generated from the following file:
pipeline.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.