Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_program< Factory >::file_reader Class Reference
tbb::flow::interface10::opencl_program< Factory >::file_reader Class Reference
Public Member Functions
file_reader (const std::string &filepath)
const char * content ()
size_t length ()
Private Attributes
std::string my_content
Detailed Description
template<typename Factory = opencl_info::default_opencl_factory>
class tbb::flow::interface10::opencl_program< Factory >::file_reader
Definition at line 1258 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::file_reader::file_reader (const std::string & filepath) inline
Definition at line 1260 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::opencl_buffer< T, Factory >::begin(), and length.
{
             std::ifstream file_descriptor( filepath, std::ifstream::binary );
             if ( !file_descriptor.is_open() ) {
                 std::string str = std::string( "Could not open file: " ) + filepath;
                 std::cerr << str << std::endl;
                 throw str;
             }
             file_descriptor.seekg( 0, file_descriptor.end );
             size_t length = size_t( file_descriptor.tellg() );
             file_descriptor.seekg( 0, file_descriptor.beg );
             my_content.resize( length );
             char* begin = &*my_content.begin();
             file_descriptor.read( begin, length );
             file_descriptor.close();
         }
Member Function Documentation
template<typename Factory = opencl_info::default_opencl_factory> const char* tbb::flow::interface10::opencl_program< Factory >::file_reader::content () inline
Definition at line 1275 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_program< Factory >::init().
 { return &*my_content.cbegin(); }
template<typename Factory = opencl_info::default_opencl_factory> size_t tbb::flow::interface10::opencl_program< Factory >::file_reader::length () inline
Definition at line 1276 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_program< Factory >::init().
 { return my_content.length(); }
Member Data Documentation
template<typename Factory = opencl_info::default_opencl_factory> std::string tbb::flow::interface10::opencl_program< Factory >::file_reader::my_content private
Definition at line 1278 of file flow_graph_opencl_node.h.
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.