Intel(R) Threading Building Blocks Doxygen Documentation: internal::function_input_queue< T, A > Class Template Reference
internal::function_input_queue< T, A > Class Template Reference
#include <_flow_graph_node_impl.h>
Public Member Functions
bool empty () const
const T & front () const
bool pop (T &t)
void pop ()
bool push (T &t)
Public Member Functions inherited from internal::item_buffer< T, A >
item_buffer ()
Constructor.
~item_buffer ()
void reset ()
Additional Inherited Members
Public Types inherited from internal::item_buffer< T, A >
enum buffer_item_state { no_item =0, has_item =1, reserved_item =2 }
typedef T item_type
Protected Types inherited from internal::item_buffer< T, A >
typedef size_t size_type
typedef aligned_pair< item_type, buffer_item_state >::type buffer_item_type
typedef A::template rebind< buffer_item_type >::other allocator_type
Protected Member Functions inherited from internal::item_buffer< T, A >
bool buffer_empty () const
buffer_item_type & item (size_type i)
const buffer_item_type & item (size_type i) const
bool my_item_valid (size_type i) const
bool my_item_reserved (size_type i) const
const item_type & get_my_item (size_t i) const
void set_my_item (size_t i, const item_type &o)
void fetch_item (size_t i, item_type &o)
void move_item (size_t to, size_t from)
bool place_item (size_t here, const item_type &me)
void swap_items (size_t i, size_t j)
void destroy_item (size_type i)
const item_type & front () const
const item_type & back () const
void reserve_item (size_type i)
void release_item (size_type i)
void destroy_front ()
void destroy_back ()
size_type size (size_t new_tail=0)
size_type capacity ()
bool buffer_full ()
void grow_my_array (size_t minimum_size)
Grows the internal array.
bool push_back (item_type &v)
bool pop_back (item_type &v)
bool pop_front (item_type &v)
void clean_up_buffer (bool reset_pointers)
Protected Attributes inherited from internal::item_buffer< T, A >
buffer_item_type * my_array
size_type my_array_size
size_type my_head
size_type my_tail
Static Protected Attributes inherited from internal::item_buffer< T, A >
static const size_type initial_buffer_size = 4
Detailed Description
template<typename T, typename A>
class internal::function_input_queue< T, A >
Definition at line 38 of file _flow_graph_node_impl.h.
Member Function Documentation
template<typename T , typename A > bool internal::function_input_queue< T, A >::empty () const inline
Definition at line 40 of file _flow_graph_node_impl.h.
References internal::item_buffer< T, A >::buffer_empty().
Referenced by internal::clear_element< N >::this_empty().
{
              return this->buffer_empty();
          }
template<typename T , typename A > const T& internal::function_input_queue< T, A >::front () const inline
Definition at line 44 of file _flow_graph_node_impl.h.
References internal::item_buffer< T, A >::front().
{
              return this->item_buffer<T, A>::front();
          }
template<typename T , typename A > bool internal::function_input_queue< T, A >::pop (T & t) inline
Definition at line 48 of file _flow_graph_node_impl.h.
References internal::item_buffer< T, A >::pop_front().
{
              return this->pop_front( t );
          }
template<typename T , typename A > void internal::function_input_queue< T, A >::pop () inline
Definition at line 52 of file _flow_graph_node_impl.h.
References internal::item_buffer< T, A >::destroy_front().
                     {
              this->destroy_front();
          }
template<typename T , typename A > bool internal::function_input_queue< T, A >::push (T & t) inline
Definition at line 56 of file _flow_graph_node_impl.h.
References internal::item_buffer< T, A >::push_back().
{
              return this->push_back( t );
          }
The documentation for this class was generated from the following file:
_flow_graph_node_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.