Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::final_sum< Range, Body > Class Template Reference
tbb::internal::final_sum< Range, Body > Class Template Reference
Algorithms
Performs final scan for a leaf.
#include <parallel_scan.h>
Public Member Functions
final_sum (Body &body_)
~final_sum ()
void finish_construction (const Range &range_, Body *stuff_last_)
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
virtual void __TBB_EXPORTED_METHOD note_affinity (affinity_id id)
Invoked by scheduler to notify task that it ran on unexpected thread.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Public Attributes
Body my_body
Private Member Functions
task * execute () __TBB_override
Should be overridden by derived classes.
Private Attributes
aligned_space< Range > my_range
Body * my_stuff_last
Where to put result of last subrange, or NULL if not last subrange.
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
template<typename Range, typename Body>
class tbb::internal::final_sum< Range, Body >
Performs final scan for a leaf.
Definition at line 51 of file parallel_scan.h.
Constructor & Destructor Documentation
template<typename Range , typename Body > tbb::internal::final_sum< Range, Body >::final_sum (Body & body_) inline
Definition at line 59 of file parallel_scan.h.
References tbb::internal::poison_pointer().
                                  :
             my_body(body_,split())
         {
             poison_pointer(my_stuff_last);
         }
template<typename Range , typename Body > tbb::internal::final_sum< Range, Body >::~final_sum () inline
Definition at line 64 of file parallel_scan.h.
References tbb::aligned_space< T, N >::begin().
                      {
             my_range.begin()->~Range();
         }
Member Function Documentation
template<typename Range , typename Body > task* tbb::internal::final_sum< Range, Body >::execute () inline private virtual
Should be overridden by derived classes.
Implements tbb::task.
Definition at line 72 of file parallel_scan.h.
References tbb::aligned_space< T, N >::begin().
{
             my_body( *my_range.begin(), final_scan_tag() );
             if( my_stuff_last )
                 my_stuff_last->assign(my_body);
             return NULL;
         }
template<typename Range , typename Body > void tbb::internal::final_sum< Range, Body >::finish_construction (const Range & range_, Body * stuff_last_) inline
Definition at line 67 of file parallel_scan.h.
References tbb::aligned_space< T, N >::begin().
Referenced by tbb::internal::sum_node< Range, Body >::create_child(), and tbb::internal::start_scan< Range, Body, Partitioner >::run().
{
             new( my_range.begin() ) Range(range_);
             my_stuff_last = stuff_last_;
         }
Member Data Documentation
template<typename Range , typename Body > Body tbb::internal::final_sum< Range, Body >::my_body
Definition at line 53 of file parallel_scan.h.
Referenced by tbb::internal::sum_node< Range, Body >::execute(), tbb::internal::finish_scan< Range, Body >::execute(), and tbb::internal::start_scan< Range, Body, Partitioner >::run().
template<typename Range , typename Body > aligned_space<Range> tbb::internal::final_sum< Range, Body >::my_range private
Definition at line 55 of file parallel_scan.h.
template<typename Range , typename Body > Body* tbb::internal::final_sum< Range, Body >::my_stuff_last private
Where to put result of last subrange, or NULL if not last subrange.
Definition at line 57 of file parallel_scan.h.
Referenced by tbb::internal::start_scan< Range, Body, Partitioner >::run().
The documentation for this class was generated from the following file:
parallel_scan.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.