Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface7::internal::delegated_function< F, R > Class Template Reference
tbb::interface7::internal::delegated_function< F, R > Class Template Reference
#include <task_arena.h>
Public Member Functions
delegated_function (F &f)
R consume_result () const
~delegated_function ()
Public Member Functions inherited from tbb::interface7::internal::delegate_base
virtual ~delegate_base ()
Private Member Functions
void operator() () const __TBB_override
Private Attributes
F & my_func
tbb::aligned_space< R > my_return_storage
Detailed Description
template<typename F, typename R>
class tbb::interface7::internal::delegated_function< F, R >
Definition at line 72 of file task_arena.h.
Constructor & Destructor Documentation
template<typename F, typename R> tbb::interface7::internal::delegated_function< F, R >::delegated_function (F & f) inline
Definition at line 80 of file task_arena.h.
 : my_func(f) {}
template<typename F, typename R> tbb::interface7::internal::delegated_function< F, R >::~delegated_function () inline
Definition at line 85 of file task_arena.h.
References tbb::aligned_space< T, N >::begin().
{
         my_return_storage.begin()->~R();
     }
Member Function Documentation
template<typename F, typename R> R tbb::interface7::internal::delegated_function< F, R >::consume_result () const inline
Definition at line 82 of file task_arena.h.
References tbb::aligned_space< T, N >::begin(), and tbb::move().
Referenced by tbb::interface7::internal::isolate_impl().
{
         return tbb::internal::move(*(my_return_storage.begin()));
     }
template<typename F, typename R> void tbb::interface7::internal::delegated_function< F, R >::operator() () const inline private virtual
Implements tbb::interface7::internal::delegate_base.
Definition at line 76 of file task_arena.h.
References tbb::aligned_space< T, N >::begin().
{
         new (my_return_storage.begin()) R(my_func());
     }
Member Data Documentation
template<typename F, typename R> F& tbb::interface7::internal::delegated_function< F, R >::my_func private
Definition at line 73 of file task_arena.h.
template<typename F, typename R> tbb::aligned_space<R> tbb::interface7::internal::delegated_function< F, R >::my_return_storage private
Definition at line 74 of file task_arena.h.
The documentation for this class was generated from the following file:
task_arena.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.