Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type > Class Template Reference
tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type > Class Template Reference
Containers
The enumerable_thread_specific container.
#include <enumerable_thread_specific.h>
Classes
class generic_range_type
A generic range, used to create range objects from the iterators.
Public Types
typedef Allocator allocator_type
Basic types.
typedef T value_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef internal_collection_type::size_type size_type
typedef internal_collection_type::difference_type difference_type
typedef internal::enumerable_thread_specific_iterator< internal_collection_type, value_type > iterator
typedef internal::enumerable_thread_specific_iterator< internal_collection_type, const value_type > const_iterator
typedef generic_range_type< iterator > range_type
typedef generic_range_type< const_iterator > const_range_type
Public Member Functions
enumerable_thread_specific ()
Default constructor. Each local instance of T is default constructed.
template<typename Finit , typename = typename internal::enable_if<internal::is_callable_no_args<typename internal::strip<Finit>::type>::value>::type>
enumerable_thread_specific (Finit finit)
Constructor with initializer functor. Each local instance of T is constructed by T(finit()).
enumerable_thread_specific (const T &exemplar)
Constructor with exemplar. Each local instance of T is copy-constructed from the exemplar.
enumerable_thread_specific (T &&exemplar)
template<typename P1 , typename... P, typename = typename internal::enable_if<!internal::is_callable_no_args<typename internal::strip<P1>::type>::value && !internal::is_compatible_ets<T, typename internal::strip<P1>::type>::value && !internal::is_same_type<T, typename internal::strip<P1>::type>::value >::type>
enumerable_thread_specific (P1 &&arg1, P &&...args)
Variadic constructor with initializer arguments. Each local instance of T is constructed by T(args...)
~enumerable_thread_specific ()
Destructor.
reference local ()
returns reference to local, discarding exists
reference local (bool &exists)
Returns reference to calling thread's local copy, creating one if necessary.
size_type size () const
Get the number of local copies.
bool empty () const
true if there have been no local copies created
iterator begin ()
begin iterator
iterator end ()
end iterator
const_iterator begin () const
begin const iterator
const_iterator end () const
end const iterator
range_type range (size_t grainsize=1)
Get range for parallel algorithms.
const_range_type range (size_t grainsize=1) const
Get const range for parallel algorithms.
void clear ()
Destroys local copies.
enumerable_thread_specific (const enumerable_thread_specific &other)
template<typename Alloc , ets_key_usage_type Cachetype>
enumerable_thread_specific (const enumerable_thread_specific< T, Alloc, Cachetype > &other)
enumerable_thread_specific (enumerable_thread_specific &&other)
template<typename Alloc , ets_key_usage_type Cachetype>
enumerable_thread_specific (enumerable_thread_specific< T, Alloc, Cachetype > &&other)
enumerable_thread_specific & operator= (const enumerable_thread_specific &other)
template<typename Alloc , ets_key_usage_type Cachetype>
enumerable_thread_specific & operator= (const enumerable_thread_specific< T, Alloc, Cachetype > &other)
enumerable_thread_specific & operator= (enumerable_thread_specific &&other)
template<typename Alloc , ets_key_usage_type Cachetype>
enumerable_thread_specific & operator= (enumerable_thread_specific< T, Alloc, Cachetype > &&other)
template<typename combine_func_t >
T combine (combine_func_t f_combine)
template<typename combine_func_t >
void combine_each (combine_func_t f_combine)
Private Types
typedef internal::padded< internal::ets_element< T > > padded_element
typedef Allocator::template rebind< padded_element >::other padded_allocator_type
typedef tbb::concurrent_vector< padded_element, padded_allocator_type > internal_collection_type
typedef Allocator::template rebind< uintptr_t >::other array_allocator_type
Private Member Functions
void * create_local () __TBB_override
void * create_array (size_t _size) __TBB_override
void free_array (void *_ptr, size_t _size) __TBB_override
template<typename A2 , ets_key_usage_type C2>
void internal_copy (const enumerable_thread_specific< T, A2, C2 > &other)
void internal_swap (enumerable_thread_specific &other)
template<typename A2 , ets_key_usage_type C2>
void internal_move (enumerable_thread_specific< T, A2, C2 > &&other)
Static Private Member Functions
static void * create_local_by_copy (internal::ets_base< ets_no_key > &base, void *p)
static void * create_local_by_move (internal::ets_base< ets_no_key > &base, void *p)
Private Attributes
internal::callback_base< T > * my_construct_callback
internal_collection_type my_locals
Friends
template<typename U , typename A , ets_key_usage_type C>
class enumerable_thread_specific
Detailed Description
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key>
class tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >
The enumerable_thread_specific container.
enumerable_thread_specific has the following properties:
thread-local copies are lazily created, with default, exemplar or function initialization.
thread-local copies do not move (during lifetime, and excepting clear()) so the address of a copy is invariant.
the contained objects need not have operator=() defined if combine is not used.
enumerable_thread_specific containers may be copy-constructed or assigned.
thread-local copies can be managed by hash-table, or can be accessed via TLS storage for speed.
outside of parallel contexts, the contents of all thread-local copies are accessible by iterator or using combine or combine_each methods
Segmented iterator
When the thread-local objects are containers with input_iterators defined, a segmented iterator may be used to iterate over all the elements of all thread-local copies.
combine and combine_each
Both methods are defined for enumerable_thread_specific.
combine() requires the type T have operator=() defined.
neither method modifies the contents of the object (though there is no guarantee that the applied methods do not modify the object.)
Both are evaluated in serial context (the methods are assumed to be non-benign.)
Definition at line 54 of file enumerable_thread_specific.h.
Member Typedef Documentation
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef Allocator tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::allocator_type
Basic types.
Definition at line 834 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef Allocator::template rebind< uintptr_t >::other tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::array_allocator_type private
Definition at line 818 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef internal::enumerable_thread_specific_iterator< internal_collection_type, const value_type > tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::const_iterator
Definition at line 845 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef const T* tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::const_pointer
Definition at line 839 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef generic_range_type< const_iterator > tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::const_range_type
Definition at line 849 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef const T& tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::const_reference
Definition at line 837 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef internal_collection_type::difference_type tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::difference_type
Definition at line 841 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef tbb::concurrent_vector< padded_element, padded_allocator_type > tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_collection_type private
Definition at line 788 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef internal::enumerable_thread_specific_iterator< internal_collection_type, value_type > tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::iterator
Definition at line 844 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef Allocator::template rebind< padded_element >::other tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::padded_allocator_type private
Definition at line 787 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef internal::padded< internal::ets_element<T> > tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::padded_element private
Definition at line 770 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef T* tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::pointer
Definition at line 838 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef generic_range_type< iterator > tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::range_type
Definition at line 848 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef T& tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::reference
Definition at line 836 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef internal_collection_type::size_type tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::size_type
Definition at line 840 of file enumerable_thread_specific.h.
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> typedef T tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::value_type
Definition at line 835 of file enumerable_thread_specific.h.
Constructor & Destructor Documentation
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific () inline
Default constructor. Each local instance of T is default constructed.
Definition at line 852 of file enumerable_thread_specific.h.
References type, and value.
                                      : my_construct_callback(
             internal::callback_leaf<T,internal::construct_by_default<T> >::make(/*dummy argument*/0)
         ){}
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename Finit , typename = typename internal::enable_if<internal::is_callable_no_args<typename internal::strip<Finit>::type>::value>::type> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (Finit finit) inline explicit
Constructor with initializer functor. Each local instance of T is constructed by T(finit()).
Definition at line 862 of file enumerable_thread_specific.h.
                                                            : my_construct_callback(
             internal::callback_leaf<T,internal::construct_by_finit<T,Finit> >::make( tbb::internal::move(finit) )
         ){}
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (const T & exemplar) inline explicit
Constructor with exemplar. Each local instance of T is copy-constructed from the exemplar.
Definition at line 867 of file enumerable_thread_specific.h.
                                                                  : my_construct_callback(
             internal::callback_leaf<T,internal::construct_by_exemplar<T> >::make( exemplar )
         ){}
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (T && exemplar) inline explicit
Definition at line 872 of file enumerable_thread_specific.h.
References type, and value.
                                                             : my_construct_callback(
             internal::callback_leaf<T,internal::construct_by_exemplar<T> >::make( std::move(exemplar) )
         ){}
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename P1 , typename... P, typename = typename internal::enable_if<!internal::is_callable_no_args<typename internal::strip<P1>::type>::value && !internal::is_compatible_ets<T, typename internal::strip<P1>::type>::value && !internal::is_same_type<T, typename internal::strip<P1>::type>::value >::type> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (P1 && arg1, P &&... args) inline
Variadic constructor with initializer arguments. Each local instance of T is constructed by T(args...)
Definition at line 882 of file enumerable_thread_specific.h.
                                                               : my_construct_callback(
             internal::callback_leaf<T,internal::construct_by_args<T,P1,P...> >::make( std::forward<P1>(arg1), std::forward<P>(args)... )
         ){}
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::~enumerable_thread_specific () inline
Destructor.
Definition at line 888 of file enumerable_thread_specific.h.
{
             if(my_construct_callback) my_construct_callback->destroy();
             // Deallocate the hash table before overridden free_array() becomes inaccessible
             this->internal::ets_base<ets_no_key>::table_clear();
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (const enumerable_thread_specific< T, Allocator, ETS_key_type > & other) inline
Definition at line 978 of file enumerable_thread_specific.h.
         : internal::ets_base<ETS_key_type>() /* prevents GCC warnings with -Wextra */
         {
             internal_copy(other);
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename Alloc , ets_key_usage_type Cachetype> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (const enumerable_thread_specific< T, Alloc, Cachetype > & other) inline
Definition at line 985 of file enumerable_thread_specific.h.
         {
             internal_copy(other);
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (enumerable_thread_specific< T, Allocator, ETS_key_type > && other) inline
Definition at line 991 of file enumerable_thread_specific.h.
                                                                          : my_construct_callback()
         {
             internal_swap(other);
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename Alloc , ets_key_usage_type Cachetype> tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::enumerable_thread_specific (enumerable_thread_specific< T, Alloc, Cachetype > && other) inline
Definition at line 997 of file enumerable_thread_specific.h.
References tbb::move().
                                                                                               : my_construct_callback()
         {
             internal_move(std::move(other));
         }
Member Function Documentation
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> iterator tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::begin () inline
begin iterator
Definition at line 913 of file enumerable_thread_specific.h.
 { return iterator( my_locals, 0 ); }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> const_iterator tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::begin () const inline
begin const iterator
Definition at line 918 of file enumerable_thread_specific.h.
 { return const_iterator(my_locals, 0); }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> void tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::clear () inline
Destroys local copies.
Definition at line 930 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::clear().
                      {
             my_locals.clear();
             this->table_clear();
             // callback is not destroyed
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename combine_func_t > T tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::combine (combine_func_t f_combine) inline
Definition at line 1044 of file enumerable_thread_specific.h.
References begin, and end.
{
             if(begin() == end()) {
                 internal::ets_element<T> location;
                 my_construct_callback->construct(location.value());
                 return *location.value_committed();
             }
             const_iterator ci = begin();
             T my_result = *ci;
             while(++ci != end())
                 my_result = f_combine( my_result, *ci );
             return my_result;
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename combine_func_t > void tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::combine_each (combine_func_t f_combine) inline
Definition at line 1059 of file enumerable_thread_specific.h.
References begin, and end.
{
             for(iterator ci = begin(); ci != end(); ++ci) {
                 f_combine( *ci );
             }
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> void* tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::create_array (size_t _size) inline private
Definition at line 821 of file enumerable_thread_specific.h.
{
             size_t nelements = (_size + sizeof(uintptr_t) -1) / sizeof(uintptr_t);
             return array_allocator_type().allocate(nelements);
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> void* tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::create_local () inline private
Definition at line 796 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::grow_by().
{
             padded_element& lref = *my_locals.grow_by(1);
             my_construct_callback->construct(lref.value());
             return lref.value_committed();
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> static void* tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::create_local_by_copy (internal::ets_base< ets_no_key > & base, void * p) inline static private
Definition at line 802 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::grow_by(), and tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::my_locals.
{
             enumerable_thread_specific& ets = static_cast<enumerable_thread_specific&>(base);
             padded_element& lref = *ets.my_locals.grow_by(1);
             new(lref.value()) T(*static_cast<T*>(p));
             return lref.value_committed();
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> static void* tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::create_local_by_move (internal::ets_base< ets_no_key > & base, void * p) inline static private
Definition at line 810 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::grow_by(), tbb::move(), and tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::my_locals.
{
             enumerable_thread_specific& ets = static_cast<enumerable_thread_specific&>(base);
             padded_element& lref = *ets.my_locals.grow_by(1);
             new(lref.value()) T(std::move(*static_cast<T*>(p)));
             return lref.value_committed();
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> bool tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::empty () const inline
true if there have been no local copies created
Definition at line 910 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::empty().
 { return my_locals.empty(); }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> iterator tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::end () inline
end iterator
Definition at line 915 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::size().
 { return iterator(my_locals, my_locals.size() ); }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> const_iterator tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::end () const inline
end const iterator
Definition at line 921 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::size().
 { return const_iterator(my_locals, my_locals.size()); }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> void tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::free_array (void * _ptr, size_t _size) inline private
Definition at line 826 of file enumerable_thread_specific.h.
{
             size_t nelements = (_size + sizeof(uintptr_t) -1) / sizeof(uintptr_t);
             array_allocator_type().deallocate( reinterpret_cast<uintptr_t *>(_ptr),nelements);
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename A2 , ets_key_usage_type C2> void tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_copy (const enumerable_thread_specific< T, A2, C2 > & other) inline private
Definition at line 939 of file enumerable_thread_specific.h.
References __TBB_ASSERT, __TBB_STATIC_ASSERT, tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::my_construct_callback, tbb::concurrent_vector< T, A >::reserve(), tbb::concurrent_vector< T, A >::size(), tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::size(), and type.
{
 #if __TBB_ETS_USE_CPP11 && TBB_USE_ASSERT
             // this tests is_compatible_ets
             __TBB_STATIC_ASSERT( (internal::is_compatible_ets<T, typename internal::strip<decltype(other)>::type>::value), "is_compatible_ets fails" );
 #endif
             // Initialize my_construct_callback first, so that it is valid even if rest of this routine throws an exception.
             my_construct_callback = other.my_construct_callback->clone();
             __TBB_ASSERT(my_locals.size()==0,NULL);
             my_locals.reserve(other.size());
             this->table_elementwise_copy( other, create_local_by_copy );
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename A2 , ets_key_usage_type C2> void tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_move (enumerable_thread_specific< T, A2, C2 > && other) inline private
Definition at line 963 of file enumerable_thread_specific.h.
References __TBB_ASSERT, __TBB_STATIC_ASSERT, tbb::concurrent_vector< T, A >::reserve(), tbb::concurrent_vector< T, A >::size(), and type.
{
 #if TBB_USE_ASSERT
             // this tests is_compatible_ets
             __TBB_STATIC_ASSERT( (internal::is_compatible_ets<T, typename internal::strip<decltype(other)>::type>::value), "is_compatible_ets fails" );
 #endif
             my_construct_callback = other.my_construct_callback;
             other.my_construct_callback = NULL;
             __TBB_ASSERT(my_locals.size()==0,NULL);
             my_locals.reserve(other.size());
             this->table_elementwise_copy( other, create_local_by_move );
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> void tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_swap (enumerable_thread_specific< T, Allocator, ETS_key_type > & other) inline private
Definition at line 951 of file enumerable_thread_specific.h.
References __TBB_ASSERT, tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::my_construct_callback, tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::my_locals, tbb::internal::swap(), and tbb::swap().
{
             using std::swap;
             __TBB_ASSERT( this!=&other, NULL );
             swap(my_construct_callback, other.my_construct_callback);
             // concurrent_vector::swap() preserves storage space,
             // so addresses to the vector kept in ETS hash table remain valid.
             swap(my_locals, other.my_locals);
             this->internal::ets_base<ETS_key_type>::table_swap(other);
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> reference tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::local () inline
returns reference to local, discarding exists
Definition at line 895 of file enumerable_thread_specific.h.
{
             bool exists;
             return local(exists);
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> reference tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::local (bool & exists) inline
Returns reference to calling thread's local copy, creating one if necessary.
Definition at line 901 of file enumerable_thread_specific.h.
{
             void* ptr = this->table_lookup(exists);
             return *(T*)ptr;
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> enumerable_thread_specific& tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::operator= (const enumerable_thread_specific< T, Allocator, ETS_key_type > & other) inline
Definition at line 1003 of file enumerable_thread_specific.h.
         {
             if( this != &other ) {
                 this->clear();
                 my_construct_callback->destroy();
                 internal_copy( other );
             }
             return *this;
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename Alloc , ets_key_usage_type Cachetype> enumerable_thread_specific& tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::operator= (const enumerable_thread_specific< T, Alloc, Cachetype > & other) inline
Definition at line 1014 of file enumerable_thread_specific.h.
References __TBB_ASSERT.
         {
             __TBB_ASSERT( static_cast<void*>(this)!=static_cast<const void*>(&other), NULL ); // Objects of different types
             this->clear();
             my_construct_callback->destroy();
             internal_copy(other);
             return *this;
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> enumerable_thread_specific& tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::operator= (enumerable_thread_specific< T, Allocator, ETS_key_type > && other) inline
Definition at line 1024 of file enumerable_thread_specific.h.
         {
             if( this != &other )
                 internal_swap(other);
             return *this;
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename Alloc , ets_key_usage_type Cachetype> enumerable_thread_specific& tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::operator= (enumerable_thread_specific< T, Alloc, Cachetype > && other) inline
Definition at line 1032 of file enumerable_thread_specific.h.
References __TBB_ASSERT, and tbb::move().
         {
             __TBB_ASSERT( static_cast<void*>(this)!=static_cast<const void*>(&other), NULL ); // Objects of different types
             this->clear();
             my_construct_callback->destroy();
             internal_move(std::move(other));
             return *this;
         }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> range_type tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::range (size_t grainsize = 1) inline
Get range for parallel algorithms.
Definition at line 924 of file enumerable_thread_specific.h.
References begin, and end.
 { return range_type( begin(), end(), grainsize ); }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> const_range_type tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::range (size_t grainsize = 1) const inline
Get const range for parallel algorithms.
Definition at line 927 of file enumerable_thread_specific.h.
References begin, and end.
 { return const_range_type( begin(), end(), grainsize ); }
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> size_type tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::size () const inline
Get the number of local copies.
Definition at line 907 of file enumerable_thread_specific.h.
References tbb::concurrent_vector< T, A >::size().
Referenced by tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_copy().
 { return my_locals.size(); }
Friends And Related Function Documentation
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> template<typename U , typename A , ets_key_usage_type C> friend class enumerable_thread_specific friend
Definition at line 768 of file enumerable_thread_specific.h.
Member Data Documentation
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> internal::callback_base<T>* tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::my_construct_callback private
Definition at line 790 of file enumerable_thread_specific.h.
Referenced by tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_copy(), and tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_swap().
template<typename T, typename Allocator = cache_aligned_allocator<T>, ets_key_usage_type ETS_key_type = ets_no_key> internal_collection_type tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::my_locals private
Definition at line 792 of file enumerable_thread_specific.h.
Referenced by tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::create_local_by_copy(), tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::create_local_by_move(), and tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_swap().
The documentation for this class was generated from the following file:
enumerable_thread_specific.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.