Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::flag_task Class Reference
tbb::interface9::internal::flag_task Class Reference
Join task node that contains shared flag for stealing feedback.
#include <partitioner.h>
Public Member Functions
flag_task ()
task * execute () __TBB_override
Should be overridden by derived classes.
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
virtual void __TBB_EXPORTED_METHOD note_affinity (affinity_id id)
Invoked by scheduler to notify task that it ran on unexpected thread.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions
static void mark_task_stolen (task &t)
static bool is_peer_stolen (task &t)
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Public Attributes
tbb::atomic< bool > my_child_stolen
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
Join task node that contains shared flag for stealing feedback.
Definition at line 129 of file partitioner.h.
Constructor & Destructor Documentation
tbb::interface9::internal::flag_task::flag_task () inline
Definition at line 132 of file partitioner.h.
 { my_child_stolen = false; }
Member Function Documentation
task* tbb::interface9::internal::flag_task::execute () inline virtual
Should be overridden by derived classes.
Implements tbb::task.
Definition at line 133 of file partitioner.h.
 { return NULL; }
static bool tbb::interface9::internal::flag_task::is_peer_stolen (task & t) inline static
Definition at line 143 of file partitioner.h.
References tbb::task::parent().
Referenced by tbb::interface9::internal::dynamic_grainsize_mode< linear_affinity_mode< affinity_partition_type > >::check_for_demand(), and tbb::interface9::internal::auto_partition_type::check_for_demand().
{
         return static_cast<flag_task*>(t.parent())->my_child_stolen;
     }
static void tbb::interface9::internal::flag_task::mark_task_stolen (task & t) inline static
Definition at line 134 of file partitioner.h.
References tbb::internal::atomic_impl< T >::fetch_and_store(), tbb::task::parent(), and tbb::release.
Referenced by tbb::interface9::internal::dynamic_grainsize_mode< linear_affinity_mode< affinity_partition_type > >::check_being_stolen().
{
         tbb::atomic<bool> &flag = static_cast<flag_task*>(t.parent())->my_child_stolen;
 #if TBB_USE_THREADING_TOOLS
         // Threading tools respect lock prefix but report false-positive data-race via plain store
         flag.fetch_and_store<release>(true);
 #else
         flag = true;
 #endif //TBB_USE_THREADING_TOOLS
     }
Member Data Documentation
tbb::atomic<bool> tbb::interface9::internal::flag_task::my_child_stolen
Definition at line 131 of file partitioner.h.
The documentation for this class was generated from the following file:
partitioner.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.