Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface9::gfx_async_msg< T > Class Template Reference
tbb::flow::interface9::gfx_async_msg< T > Class Template Reference
#include <gfx_factory.h>
Public Types
typedef gfx_offload::task_id_type kernel_id_type
Public Member Functions
gfx_async_msg ()
gfx_async_msg (const T &input_data)
T & data ()
const T & data () const
void set_task_id (kernel_id_type id)
kernel_id_type task_id () const
Private Attributes
T my_data
kernel_id_type my_task_id
Detailed Description
template<typename T>
class tbb::flow::interface9::gfx_async_msg< T >
Definition at line 142 of file gfx_factory.h.
Member Typedef Documentation
template<typename T> typedef gfx_offload::task_id_type tbb::flow::interface9::gfx_async_msg< T >::kernel_id_type
Definition at line 144 of file gfx_factory.h.
Constructor & Destructor Documentation
template<typename T> tbb::flow::interface9::gfx_async_msg< T >::gfx_async_msg () inline
Definition at line 146 of file gfx_factory.h.
 : my_task_id(0) {}
template<typename T> tbb::flow::interface9::gfx_async_msg< T >::gfx_async_msg (const T & input_data) inline
Definition at line 147 of file gfx_factory.h.
 : my_data(input_data), my_task_id(0) {}
Member Function Documentation
template<typename T> T& tbb::flow::interface9::gfx_async_msg< T >::data () inline
Definition at line 149 of file gfx_factory.h.
Referenced by tbb::flow::interface9::gfx_factory::receive_arg(), and tbb::flow::interface9::gfx_factory::send_arg().
 { return my_data; }
template<typename T> const T& tbb::flow::interface9::gfx_async_msg< T >::data () const inline
Definition at line 150 of file gfx_factory.h.
 { return my_data; }
template<typename T> void tbb::flow::interface9::gfx_async_msg< T >::set_task_id (kernel_id_type id) inline
Definition at line 152 of file gfx_factory.h.
References id.
Referenced by tbb::flow::interface9::gfx_factory::set_kernel_id_arg().
 { my_task_id = id; }
template<typename T> kernel_id_type tbb::flow::interface9::gfx_async_msg< T >::task_id () const inline
Definition at line 153 of file gfx_factory.h.
 { return my_task_id; }
Member Data Documentation
template<typename T> T tbb::flow::interface9::gfx_async_msg< T >::my_data private
Definition at line 156 of file gfx_factory.h.
template<typename T> kernel_id_type tbb::flow::interface9::gfx_async_msg< T >::my_task_id private
Definition at line 157 of file gfx_factory.h.
The documentation for this class was generated from the following file:
gfx_factory.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.