Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface9::gfx_factory Class Reference
tbb::flow::interface9::gfx_factory Class Reference
#include <gfx_factory.h>
Classes
struct device_type
class dummy_device_selector
class func_wrapper
Public Types
template<typename T >
using async_msg_type = gfx_async_msg< T >
typedef func_wrapper kernel_type
typedef gfx_offload::task_id_type kernel_id_type
Public Member Functions
gfx_factory (tbb::flow::graph &g)
template<typename... Args>
void send_data (device_type, Args &...args)
template<typename... Args>
void send_kernel (device_type, const kernel_type &kernel, Args &...args)
template<typename FinalizeFn , typename... Args>
void finalize (device_type, FinalizeFn fn, Args &...)
Private Member Functions
template<typename... Args>
void callback (kernel_id_type id, Args...args)
template<typename T >
void share_data (T)
template<typename T >
void share_data (gfx_buffer< T > &buffer)
template<typename T >
void send_arg (T)
template<typename T >
void send_arg (async_msg_type< T > &msg)
void send_data_impl ()
template<typename T , typename... Rest>
void send_data_impl (T &arg, Rest &...args)
template<typename T >
void set_kernel_id_arg (kernel_id_type, T)
template<typename T >
void set_kernel_id_arg (kernel_id_type id, async_msg_type< T > &msg)
void set_kernel_id (kernel_id_type)
template<typename T , typename... Rest>
void set_kernel_id (kernel_id_type id, T &arg, Rest &...args)
template<typename T >
void unshare_data (T)
template<typename T >
void unshare_data (gfx_buffer< T > &buffer)
template<typename T >
void receive_arg (T)
template<typename T >
void receive_arg (async_msg_type< T > &msg)
void receive_data ()
template<typename T , typename... Rest>
void receive_data (T &arg, Rest &...args)
Private Attributes
int current_task_id
std::future< void > callback_future
tbb::flow::graph & m_graph
std::mutex future_assignment_mutex
std::mutex task_wait_mutex
Detailed Description
Definition at line 160 of file gfx_factory.h.
Member Typedef Documentation
template<typename T > using tbb::flow::interface9::gfx_factory::async_msg_type = gfx_async_msg<T>
Definition at line 182 of file gfx_factory.h.
typedef gfx_offload::task_id_type tbb::flow::interface9::gfx_factory::kernel_id_type
Definition at line 190 of file gfx_factory.h.
typedef func_wrapper tbb::flow::interface9::gfx_factory::kernel_type
Definition at line 184 of file gfx_factory.h.
Constructor & Destructor Documentation
tbb::flow::interface9::gfx_factory::gfx_factory (tbb::flow::graph & g) inline
Definition at line 192 of file gfx_factory.h.
 : m_graph(g), current_task_id(0) {}
Member Function Documentation
template<typename... Args> void tbb::flow::interface9::gfx_factory::callback (kernel_id_type id, Args... args) inline private
Definition at line 241 of file gfx_factory.h.
References id, lock, and tbb::flow::interface9::gfx_offload::wait_for_task().
{
         // Waiting for specific tasks id to complete
         {
             std::lock_guard<std::mutex> lock(task_wait_mutex);
             if (current_task_id < id) {
                 gfx_offload::wait_for_task(id);
                 current_task_id = id;
             }
         }
         // Get result from device and set to async_msg (args)
         receive_data(args...);
         // Data was sent to the graph, release the reference
         m_graph.release_wait();
     }
template<typename FinalizeFn , typename... Args> void tbb::flow::interface9::gfx_factory::finalize (device_type , FinalizeFn fn, Args & ...) inline
Definition at line 221 of file gfx_factory.h.
References fn.
{
         fn();
     }
template<typename T > void tbb::flow::interface9::gfx_factory::receive_arg (T) inline private
Definition at line 322 of file gfx_factory.h.
 {}
template<typename T > void tbb::flow::interface9::gfx_factory::receive_arg (async_msg_type< T > & msg) inline private
Definition at line 325 of file gfx_factory.h.
References tbb::flow::interface9::gfx_async_msg< T >::data().
{
         unshare_data(msg.data());
         msg.set(msg.data());
     }
void tbb::flow::interface9::gfx_factory::receive_data () inline private
Definition at line 330 of file gfx_factory.h.
 {}
template<typename T , typename... Rest> void tbb::flow::interface9::gfx_factory::receive_data (T & arg, Rest &... args) inline private
Definition at line 333 of file gfx_factory.h.
{
         receive_arg(arg);
         receive_data(args...);
     }
template<typename T > void tbb::flow::interface9::gfx_factory::send_arg (T) inline private
Definition at line 272 of file gfx_factory.h.
 {}
template<typename T > void tbb::flow::interface9::gfx_factory::send_arg (async_msg_type< T > & msg) inline private
Definition at line 275 of file gfx_factory.h.
References tbb::flow::interface9::gfx_async_msg< T >::data().
{
         share_data(msg.data());
     }
template<typename... Args> void tbb::flow::interface9::gfx_factory::send_data (device_type , Args &... args) inline
Definition at line 196 of file gfx_factory.h.
{
         send_data_impl(args...);
     }
void tbb::flow::interface9::gfx_factory::send_data_impl () inline private
Definition at line 279 of file gfx_factory.h.
 {}
template<typename T , typename... Rest> void tbb::flow::interface9::gfx_factory::send_data_impl (T & arg, Rest &... args) inline private
Definition at line 282 of file gfx_factory.h.
{
         send_arg(arg);
         send_data_impl(args...);
     }
template<typename... Args> void tbb::flow::interface9::gfx_factory::send_kernel (device_type , const kernel_type & kernel, Args &... args) inline
Definition at line 202 of file gfx_factory.h.
References lock, and tbb::flow::interface9::gfx_offload::run_kernel().
{
         // Get packed T data from async_msg<T> and pass it to kernel
         kernel_id_type id = gfx_offload::run_kernel(kernel, args.data()...);
         // Set id to async_msg
         set_kernel_id(id, args...);
         // Extend the graph lifetime until the callback completion.
         m_graph.reserve_wait();
         // Mutex for future assignment
         std::lock_guard<std::mutex> lock(future_assignment_mutex);
         // Set callback that waits for kernel execution
         callback_future = std::async(std::launch::async, &gfx_factory::callback<Args...>, this, id, args...);
     }
void tbb::flow::interface9::gfx_factory::set_kernel_id (kernel_id_type) inline private
Definition at line 299 of file gfx_factory.h.
 {}
template<typename T , typename... Rest> void tbb::flow::interface9::gfx_factory::set_kernel_id (kernel_id_type id, T & arg, Rest &... args) inline private
Definition at line 302 of file gfx_factory.h.
{
         set_kernel_id_arg(id, arg);
         set_kernel_id(id, args...);
     }
template<typename T > void tbb::flow::interface9::gfx_factory::set_kernel_id_arg (kernel_id_type , T) inline private
Definition at line 292 of file gfx_factory.h.
 {}
template<typename T > void tbb::flow::interface9::gfx_factory::set_kernel_id_arg (kernel_id_type id, async_msg_type< T > & msg) inline private
Definition at line 295 of file gfx_factory.h.
References tbb::flow::interface9::gfx_async_msg< T >::set_task_id().
{
         msg.set_task_id(id);
     }
template<typename T > void tbb::flow::interface9::gfx_factory::share_data (T) inline private
Definition at line 264 of file gfx_factory.h.
 {}
template<typename T > void tbb::flow::interface9::gfx_factory::share_data (gfx_buffer< T > & buffer) inline private
Definition at line 267 of file gfx_factory.h.
References tbb::flow::interface9::gfx_buffer< T >::data(), tbb::flow::interface9::gfx_offload::share(), and tbb::flow::interface9::gfx_buffer< T >::size().
{
         gfx_offload::share(buffer.data(), buffer.size());
     }
template<typename T > void tbb::flow::interface9::gfx_factory::unshare_data (T) inline private
Definition at line 314 of file gfx_factory.h.
 {}
template<typename T > void tbb::flow::interface9::gfx_factory::unshare_data (gfx_buffer< T > & buffer) inline private
Definition at line 317 of file gfx_factory.h.
References tbb::flow::interface9::gfx_buffer< T >::data(), and tbb::flow::interface9::gfx_offload::unshare().
{
         gfx_offload::unshare(buffer.data());
     }
Member Data Documentation
std::future<void> tbb::flow::interface9::gfx_factory::callback_future private
Definition at line 341 of file gfx_factory.h.
int tbb::flow::interface9::gfx_factory::current_task_id private
Definition at line 339 of file gfx_factory.h.
std::mutex tbb::flow::interface9::gfx_factory::future_assignment_mutex private
Definition at line 344 of file gfx_factory.h.
tbb::flow::graph& tbb::flow::interface9::gfx_factory::m_graph private
Definition at line 342 of file gfx_factory.h.
std::mutex tbb::flow::interface9::gfx_factory::task_wait_mutex private
Definition at line 345 of file gfx_factory.h.
The documentation for this class was generated from the following file:
gfx_factory.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.