Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::intrusive_list_base< List, T > Class Template Reference
tbb::internal::intrusive_list_base< List, T > Class Template Reference
List of element of type T, where T is derived from intrusive_list_node.
#include <intrusive_list.h>
Classes
class const_iterator
class iterator
class iterator_impl
Public Member Functions
intrusive_list_base ()
bool empty () const
size_t size () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void push_front (T &val)
void remove (T &val)
iterator erase (iterator it)
Private Member Functions
void assert_ok () const
Static Private Member Functions
static intrusive_list_node & node (T &item)
static T & item (intrusive_list_node *node)
Private Attributes
intrusive_list_node my_head
Pointer to the head node.
size_t my_size
Number of list elements.
Detailed Description
template<class List, class T>
class tbb::internal::intrusive_list_base< List, T >
List of element of type T, where T is derived from intrusive_list_node.
The class is not thread safe.
Definition at line 45 of file intrusive_list.h.
Constructor & Destructor Documentation
template<class List, class T> tbb::internal::intrusive_list_base< List, T >::intrusive_list_base () inline
Definition at line 152 of file intrusive_list.h.
                            : my_size(0) {
         my_head.my_prev_node = &my_head;
         my_head.my_next_node = &my_head;
     }
Member Function Documentation
template<class List, class T> void tbb::internal::intrusive_list_base< List, T >::assert_ok () const inline private
Definition at line 114 of file intrusive_list.h.
{
         __TBB_ASSERT( (my_head.my_prev_node == &my_head && !my_size) ||
                       (my_head.my_next_node != &my_head && my_size >0), "intrusive_list_base corrupted" );
 #if TBB_USE_ASSERT >= 2
         size_t i = 0;
         for ( intrusive_list_node *n = my_head.my_next_node; n != &my_head; n = n->my_next_node )
             ++i;
         __TBB_ASSERT( my_size == i, "Wrong size" );
 #endif /* TBB_USE_ASSERT >= 2 */
     }
template<class List, class T> iterator tbb::internal::intrusive_list_base< List, T >::begin () inline
Definition at line 161 of file intrusive_list.h.
Referenced by tbb::internal::market::arena_in_need(), tbb::internal::market::insert_arena_into_list(), tbb::internal::market::is_arena_in_list(), tbb::internal::market::remove_arena_from_list(), tbb::internal::market::set_active_num_workers(), tbb::internal::market::try_destroy_arena(), and tbb::internal::market::update_allotment().
 { return iterator(my_head.my_next_node); }
template<class List, class T> const_iterator tbb::internal::intrusive_list_base< List, T >::begin () const inline
Definition at line 165 of file intrusive_list.h.
 { return const_iterator(my_head.my_next_node); }
template<class List, class T> bool tbb::internal::intrusive_list_base< List, T >::empty () const inline
Definition at line 157 of file intrusive_list.h.
Referenced by tbb::internal::market::arena_in_need(), and tbb::internal::market::process().
 { return my_head.my_next_node == &my_head; }
template<class List, class T> iterator tbb::internal::intrusive_list_base< List, T >::end () inline
Definition at line 163 of file intrusive_list.h.
Referenced by tbb::internal::market::arena_in_need(), tbb::internal::market::is_arena_in_list(), tbb::internal::market::remove_arena_from_list(), tbb::internal::market::set_active_num_workers(), tbb::internal::market::try_destroy_arena(), and tbb::internal::market::update_allotment().
 { return iterator(&my_head); }
template<class List, class T> const_iterator tbb::internal::intrusive_list_base< List, T >::end () const inline
Definition at line 167 of file intrusive_list.h.
 { return const_iterator(&my_head); }
template<class List, class T> iterator tbb::internal::intrusive_list_base< List, T >::erase (iterator it) inline
Definition at line 193 of file intrusive_list.h.
{
         T& val = *it;
         ++it;
         remove( val );
         return it;
     }
template<class List, class T> static T& tbb::internal::intrusive_list_base< List, T >::item (intrusive_list_node * node) inline static private
Definition at line 54 of file intrusive_list.h.
Referenced by tbb::internal::intrusive_list_base< List, T >::iterator_impl< const_iterator >::item().
 { return List::item(node); }
template<class List, class T> static intrusive_list_node& tbb::internal::intrusive_list_base< List, T >::node (T & item) inline static private
Definition at line 52 of file intrusive_list.h.
 { return List::node(item); }
template<class List, class T> void tbb::internal::intrusive_list_base< List, T >::push_front (T & val) inline
Definition at line 169 of file intrusive_list.h.
Referenced by tbb::internal::market::insert_arena_into_list().
{
         __TBB_ASSERT( node(val).my_prev_node == &node(val) && node(val).my_next_node == &node(val),
                     "Object with intrusive list node can be part of only one intrusive list simultaneously" );
         // An object can be part of only one intrusive list at the given moment via the given node member
         node(val).my_prev_node = &my_head;
         node(val).my_next_node = my_head.my_next_node;
         my_head.my_next_node->my_prev_node = &node(val);
         my_head.my_next_node = &node(val);
         ++my_size;
         assert_ok();
     }
template<class List, class T> void tbb::internal::intrusive_list_base< List, T >::remove (T & val) inline
Definition at line 181 of file intrusive_list.h.
Referenced by tbb::internal::market::remove_arena_from_list().
{
         __TBB_ASSERT( node(val).my_prev_node != &node(val) && node(val).my_next_node != &node(val), "Element to remove is not in the list" );
         __TBB_ASSERT( node(val).my_prev_node->my_next_node == &node(val) && node(val).my_next_node->my_prev_node == &node(val), "Element to remove is not in the list" );
         --my_size;
         node(val).my_next_node->my_prev_node = node(val).my_prev_node;
         node(val).my_prev_node->my_next_node = node(val).my_next_node;
 #if TBB_USE_ASSERT
         node(val).my_prev_node = node(val).my_next_node = &node(val);
 #endif
         assert_ok();
     }
template<class List, class T> size_t tbb::internal::intrusive_list_base< List, T >::size () const inline
Definition at line 159 of file intrusive_list.h.
Referenced by tbb::internal::market::insert_arena_into_list(), and tbb::internal::market::remove_arena_from_list().
 { return my_size; }
Member Data Documentation
template<class List, class T> intrusive_list_node tbb::internal::intrusive_list_base< List, T >::my_head private
Pointer to the head node.
Definition at line 47 of file intrusive_list.h.
template<class List, class T> size_t tbb::internal::intrusive_list_base< List, T >::my_size private
Number of list elements.
Definition at line 50 of file intrusive_list.h.
The documentation for this class was generated from the following file:
intrusive_list.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.