Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::tbb_thread_v3::id Class Reference
tbb::internal::tbb_thread_v3::id Class Reference
#include <tbb_thread.h>
Public Member Functions
id () __TBB_NOEXCEPT(true)
Private Member Functions
id (thread_id_type id_)
Private Attributes
thread_id_type my_id
Friends
class tbb_thread_v3
bool operator== (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator!= (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator< (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator<= (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator> (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator>= (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
template<class charT , class traits >
std::basic_ostream< charT, traits > & operator<< (std::basic_ostream< charT, traits > &out, tbb_thread_v3::id id)
tbb_thread_v3::id __TBB_EXPORTED_FUNC thread_get_id_v3 ()
size_t tbb_hasher (const tbb_thread_v3::id &id)
id atomic_compare_and_swap (id &location, const id &value, const id &comparand)
Detailed Description
Definition at line 223 of file tbb_thread.h.
Constructor & Destructor Documentation
tbb::internal::tbb_thread_v3::id::id (thread_id_type id_) inline private
Definition at line 225 of file tbb_thread.h.
 : my_id(id_) {}
tbb::internal::tbb_thread_v3::id::id () inline
Definition at line 229 of file tbb_thread.h.
References __TBB_NOEXCEPT, tbb::internal::operator!=(), tbb::internal::operator<(), tbb::internal::operator<=(), tbb::internal::operator==(), tbb::internal::operator>(), and tbb::internal::operator>=().
 : my_id(0) {}
Friends And Related Function Documentation
id atomic_compare_and_swap (id & location, const id & value, const id & comparand) friend
Definition at line 254 of file tbb_thread.h.
{
             return as_atomic(location.my_id).compare_and_swap(value.my_id, comparand.my_id);
         }
bool operator!= (tbb_thread_v3::id x, tbb_thread_v3::id y) friend
Definition at line 276 of file tbb_thread.h.
     {
         return x.my_id != y.my_id;
     }
bool operator< (tbb_thread_v3::id x, tbb_thread_v3::id y) friend
Definition at line 280 of file tbb_thread.h.
     {
         return x.my_id < y.my_id;
     }
template<class charT , class traits > std::basic_ostream<charT, traits>& operator<< (std::basic_ostream< charT, traits > & out, tbb_thread_v3::id id) friend
Definition at line 240 of file tbb_thread.h.
         {
             out << id.my_id;
             return out;
         }
bool operator<= (tbb_thread_v3::id x, tbb_thread_v3::id y) friend
Definition at line 284 of file tbb_thread.h.
     {
         return x.my_id <= y.my_id;
     }
bool operator== (tbb_thread_v3::id x, tbb_thread_v3::id y) friend
Definition at line 272 of file tbb_thread.h.
     {
         return x.my_id == y.my_id;
     }
bool operator> (tbb_thread_v3::id x, tbb_thread_v3::id y) friend
Definition at line 288 of file tbb_thread.h.
     {
         return x.my_id > y.my_id;
     }
bool operator>= (tbb_thread_v3::id x, tbb_thread_v3::id y) friend
Definition at line 292 of file tbb_thread.h.
     {
         return x.my_id >= y.my_id;
     }
size_t tbb_hasher (const tbb_thread_v3::id & id) friend
Definition at line 248 of file tbb_thread.h.
{
             __TBB_STATIC_ASSERT(sizeof(id.my_id) <= sizeof(size_t), "Implementaion assumes that thread_id_type fits into machine word");
             return tbb::tbb_hasher(id.my_id);
         }
friend class tbb_thread_v3 friend
Definition at line 227 of file tbb_thread.h.
tbb_thread_v3::id __TBB_EXPORTED_FUNC thread_get_id_v3 () friend
Definition at line 143 of file tbb_thread.cpp.
{
 #if _WIN32||_WIN64
     return tbb_thread_v3::id( GetCurrentThreadId() );
 #else
     return tbb_thread_v3::id( pthread_self() );
 #endif // _WIN32||_WIN64
 }
Member Data Documentation
thread_id_type tbb::internal::tbb_thread_v3::id::my_id private
Definition at line 224 of file tbb_thread.h.
The documentation for this class was generated from the following file:
tbb_thread.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.