Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::internal::hash_map_iterator< Container, Value > Class Template Reference
tbb::interface5::internal::hash_map_iterator< Container, Value > Class Template Reference
Containers
Meets requirements of a forward iterator for STL */.
#include <concurrent_hash_map.h>
Public Member Functions
hash_map_iterator ()
Construct undefined iterator.
hash_map_iterator (const hash_map_iterator< Container, typename Container::value_type > &other)
Value & operator* () const
Value * operator-> () const
hash_map_iterator & operator++ ()
hash_map_iterator operator++ (int)
Post increment.
Private Types
typedef Container map_type
typedef Container::node node
typedef hash_map_base::node_base node_base
typedef hash_map_base::bucket bucket
Private Member Functions
void advance_to_next_bucket ()
hash_map_iterator (const Container &map, size_t index, const bucket *b, node_base *n)
Private Attributes
const Container * my_map
concurrent_hash_map over which we are iterating.
size_t my_index
Index in hash table for current item.
const bucket * my_bucket
Pointer to bucket.
node * my_node
Pointer to node that has current item.
Friends
template<typename C , typename U >
class hash_map_iterator
template<typename I >
class hash_map_range
template<typename Key , typename T , typename HashCompare , typename A >
class interface5::concurrent_hash_map
template<typename C , typename T , typename U >
bool operator== (const hash_map_iterator< C, T > &i, const hash_map_iterator< C, U > &j)
template<typename C , typename T , typename U >
bool operator!= (const hash_map_iterator< C, T > &i, const hash_map_iterator< C, U > &j)
template<typename C , typename T , typename U >
ptrdiff_t operator- (const hash_map_iterator< C, T > &i, const hash_map_iterator< C, U > &j)
Detailed Description
template<typename Container, typename Value>
class tbb::interface5::internal::hash_map_iterator< Container, Value >
Meets requirements of a forward iterator for STL */.
Value is either the T or const T type of the container.
Definition at line 302 of file concurrent_hash_map.h.
Member Typedef Documentation
template<typename Container, typename Value> typedef hash_map_base::bucket tbb::interface5::internal::hash_map_iterator< Container, Value >::bucket private
Definition at line 308 of file concurrent_hash_map.h.
template<typename Container, typename Value> typedef Container tbb::interface5::internal::hash_map_iterator< Container, Value >::map_type private
Definition at line 305 of file concurrent_hash_map.h.
template<typename Container, typename Value> typedef Container::node tbb::interface5::internal::hash_map_iterator< Container, Value >::node private
Definition at line 306 of file concurrent_hash_map.h.
template<typename Container, typename Value> typedef hash_map_base::node_base tbb::interface5::internal::hash_map_iterator< Container, Value >::node_base private
Definition at line 307 of file concurrent_hash_map.h.
Constructor & Destructor Documentation
template<typename Container , typename Value > tbb::interface5::internal::hash_map_iterator< Container, Value >::hash_map_iterator (const Container & map, size_t index, const bucket * b, node_base * n) private
Definition at line 386 of file concurrent_hash_map.h.
References tbb::interface5::internal::hash_map_iterator< Container, Value >::advance_to_next_bucket(), and tbb::interface5::internal::hash_map_base::is_valid().
                                                                                                                              :
         my_map(&map),
         my_index(index),
         my_bucket(b),
         my_node( static_cast<node*>(n) )
     {
         if( b && !hash_map_base::is_valid(n) )
             advance_to_next_bucket();
     }
template<typename Container, typename Value> tbb::interface5::internal::hash_map_iterator< Container, Value >::hash_map_iterator () inline
Construct undefined iterator.
Definition at line 363 of file concurrent_hash_map.h.
 : my_map(), my_index(), my_bucket(), my_node() {}
template<typename Container, typename Value> tbb::interface5::internal::hash_map_iterator< Container, Value >::hash_map_iterator (const hash_map_iterator< Container, typename Container::value_type > & other) inline
Definition at line 364 of file concurrent_hash_map.h.
                                                                                                     :
             my_map(other.my_map),
             my_index(other.my_index),
             my_bucket(other.my_bucket),
             my_node(other.my_node)
         {}
Member Function Documentation
template<typename Container, typename Value> void tbb::interface5::internal::hash_map_iterator< Container, Value >::advance_to_next_bucket () inline private
Definition at line 325 of file concurrent_hash_map.h.
References __TBB_ASSERT, and tbb::interface5::internal::hash_map_base::is_valid().
Referenced by tbb::interface5::internal::hash_map_iterator< Container, Value >::hash_map_iterator(), and tbb::interface5::internal::hash_map_iterator< Container, Value >::operator++().
                                       { // TODO?: refactor to iterator_base class
             size_t k = my_index+1;
             __TBB_ASSERT( my_bucket, "advancing an invalid iterator?");
             while( k <= my_map->my_mask ) {
                 // Following test uses 2's-complement wizardry
                 if( k&(k-2) ) // not the beginning of a segment
                     ++my_bucket;
                 else my_bucket = my_map->get_bucket( k );
                 my_node = static_cast<node*>( my_bucket->node_list );
                 if( hash_map_base::is_valid(my_node) ) {
                     my_index = k; return;
                 }
                 ++k;
             }
             my_bucket = 0; my_node = 0; my_index = k; // the end
         }
template<typename Container, typename Value> Value& tbb::interface5::internal::hash_map_iterator< Container, Value >::operator* () const inline
Definition at line 370 of file concurrent_hash_map.h.
References __TBB_ASSERT, and tbb::interface5::internal::hash_map_base::is_valid().
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::operator->(), and tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::accessor::operator->().
{
             __TBB_ASSERT( hash_map_base::is_valid(my_node), "iterator uninitialized or at end of container?" );
             return my_node->item;
         }
template<typename Container , typename Value > hash_map_iterator< Container, Value > & tbb::interface5::internal::hash_map_iterator< Container, Value >::operator++ ()
Definition at line 397 of file concurrent_hash_map.h.
References tbb::interface5::internal::hash_map_iterator< Container, Value >::advance_to_next_bucket(), and tbb::interface5::internal::hash_map_iterator< Container, Value >::my_node.
{
         my_node = static_cast<node*>( my_node->next );
         if( !my_node ) advance_to_next_bucket();
         return *this;
     }
template<typename Container, typename Value> hash_map_iterator tbb::interface5::internal::hash_map_iterator< Container, Value >::operator++ (int) inline
Post increment.
Definition at line 378 of file concurrent_hash_map.h.
{
             hash_map_iterator old(*this);
             operator++();
             return old;
         }
template<typename Container, typename Value> Value* tbb::interface5::internal::hash_map_iterator< Container, Value >::operator-> () const inline
Definition at line 374 of file concurrent_hash_map.h.
 {return &operator*();}
Friends And Related Function Documentation
template<typename Container, typename Value> template<typename C , typename U > friend class hash_map_iterator friend
Definition at line 320 of file concurrent_hash_map.h.
template<typename Container, typename Value> template<typename I > friend class hash_map_range friend
Definition at line 323 of file concurrent_hash_map.h.
template<typename Container, typename Value> template<typename Key , typename T , typename HashCompare , typename A > friend class interface5::concurrent_hash_map friend
Definition at line 343 of file concurrent_hash_map.h.
template<typename Container, typename Value> template<typename C , typename T , typename U > bool operator!= (const hash_map_iterator< C, T > & i, const hash_map_iterator< C, U > & j) friend
template<typename Container, typename Value> template<typename C , typename T , typename U > ptrdiff_t operator- (const hash_map_iterator< C, T > & i, const hash_map_iterator< C, U > & j) friend
template<typename Container, typename Value> template<typename C , typename T , typename U > bool operator== (const hash_map_iterator< C, T > & i, const hash_map_iterator< C, U > & j) friend
Member Data Documentation
template<typename Container, typename Value> const bucket* tbb::interface5::internal::hash_map_iterator< Container, Value >::my_bucket private
Pointer to bucket.
Definition at line 354 of file concurrent_hash_map.h.
template<typename Container, typename Value> size_t tbb::interface5::internal::hash_map_iterator< Container, Value >::my_index private
Index in hash table for current item.
Definition at line 351 of file concurrent_hash_map.h.
template<typename Container, typename Value> const Container* tbb::interface5::internal::hash_map_iterator< Container, Value >::my_map private
concurrent_hash_map over which we are iterating.
Definition at line 348 of file concurrent_hash_map.h.
Referenced by tbb::interface5::internal::operator!=(), and tbb::interface5::internal::operator==().
template<typename Container, typename Value> node* tbb::interface5::internal::hash_map_iterator< Container, Value >::my_node private
Pointer to node that has current item.
Definition at line 357 of file concurrent_hash_map.h.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::empty(), tbb::interface5::internal::operator!=(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::operator*(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::accessor::operator*(), tbb::interface5::internal::hash_map_iterator< Container, Value >::operator++(), tbb::interface5::internal::operator==(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::release(), and tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::const_accessor::~const_accessor().
The documentation for this class was generated from the following file:
concurrent_hash_map.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.