Intel(R) Threading Building Blocks Doxygen Documentation: tbb::tick_count::interval_t Class Reference
tbb::tick_count::interval_t Class Reference
Relative time interval.
#include <tick_count.h>
Public Member Functions
interval_t ()
Construct a time interval representing zero time duration.
interval_t (double sec)
Construct a time interval representing sec seconds time duration.
double seconds () const
Return the length of a time interval in seconds.
interval_t & operator+= (const interval_t &i)
Accumulation operator.
interval_t & operator-= (const interval_t &i)
Subtraction operator.
Private Member Functions
interval_t (long long value_)
Static Private Member Functions
static long long ticks_per_second ()
Private Attributes
long long value
Friends
class tbb::tick_count
interval_t operator- (const tick_count &t1, const tick_count &t0)
Extract the intervals from the tick_counts and subtract them.
interval_t operator+ (const interval_t &i, const interval_t &j)
Add two intervals.
interval_t operator- (const interval_t &i, const interval_t &j)
Subtract two intervals.
Detailed Description
Relative time interval.
Definition at line 41 of file tick_count.h.
Constructor & Destructor Documentation
tbb::tick_count::interval_t::interval_t (long long value_) inline explicit private
Definition at line 43 of file tick_count.h.
 : value(value_) {}
tbb::tick_count::interval_t::interval_t () inline
Construct a time interval representing zero time duration.
Definition at line 46 of file tick_count.h.
References seconds().
 : value(0) {};
tbb::tick_count::interval_t::interval_t (double sec) inline explicit
Construct a time interval representing sec seconds time duration.
Definition at line 126 of file tick_count.h.
References ticks_per_second(), and value.
{
     value = static_cast<long long>(sec*interval_t::ticks_per_second());
 }
Member Function Documentation
interval_t& tbb::tick_count::interval_t::operator+= (const interval_t & i) inline
Accumulation operator.
Definition at line 70 of file tick_count.h.
References value.
 {value += i.value; return *this;}
interval_t& tbb::tick_count::interval_t::operator-= (const interval_t & i) inline
Subtraction operator.
Definition at line 73 of file tick_count.h.
References value.
 {value -= i.value; return *this;}
double tbb::tick_count::interval_t::seconds () const inline
Return the length of a time interval in seconds.
Definition at line 134 of file tick_count.h.
References tbb::tick_count::resolution(), and value.
Referenced by interval_t(), and tbb::internal::thread_sleep_v3().
{
     return value*tick_count::resolution();
 }
static long long tbb::tick_count::interval_t::ticks_per_second () inline static private
Definition at line 75 of file tick_count.h.
References __TBB_ASSERT_EX.
Referenced by interval_t(), and tbb::tick_count::resolution().
{
 #if _WIN32||_WIN64
             LARGE_INTEGER qpfreq;
             int rval = QueryPerformanceFrequency(&qpfreq);
             __TBB_ASSERT_EX(rval, "QueryPerformanceFrequency returned zero");
             return static_cast<long long>(qpfreq.QuadPart);
 #elif __linux__
             return static_cast<long long>(1E9);
 #else /* generic Unix */
             return static_cast<long long>(1E6);
 #endif /* (choice of OS) */
         }
Friends And Related Function Documentation
interval_t operator+ (const interval_t & i, const interval_t & j) friend
Add two intervals.
Definition at line 60 of file tick_count.h.
{
             return interval_t(i.value+j.value);
         }
interval_t operator- (const tick_count & t1, const tick_count & t0) friend
Extract the intervals from the tick_counts and subtract them.
Definition at line 130 of file tick_count.h.
Referenced by tbb::tick_count::tick_count().
{
     return tick_count::interval_t( t1.my_count-t0.my_count );
 }
interval_t operator- (const interval_t & i, const interval_t & j) friend
Subtract two intervals.
Definition at line 65 of file tick_count.h.
{
             return interval_t(i.value-j.value);
         }
friend class tbb::tick_count friend
Definition at line 54 of file tick_count.h.
Member Data Documentation
long long tbb::tick_count::interval_t::value private
Definition at line 42 of file tick_count.h.
Referenced by interval_t(), operator+=(), operator-=(), and seconds().
The documentation for this class was generated from the following file:
tick_count.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.