Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object Class Reference
tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object Class Reference
Public Member Functions
handle_object ()
handle_object (concurrent_lru_cache &cache_ref, typename map_storage_type::reference value_ref)
operator bool () const
handle_object (handle_object &&src)
handle_object & operator= (handle_object &&src)
value_type & value ()
~handle_object ()
Private Member Functions
void operator= (handle_object &)
handle_object (handle_object &)
Private Attributes
concurrent_lru_cache * my_cache_pointer
map_storage_type::pointer my_map_record_ptr
Friends
handle_object && move (handle_object &h)
Detailed Description
template<typename key_type, typename value_type, typename value_functor_type = value_type (*)(key_type)>
class tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object
Definition at line 114 of file concurrent_lru_cache.h.
Constructor & Destructor Documentation
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::handle_object () inline
Definition at line 118 of file concurrent_lru_cache.h.
 : my_cache_pointer(), my_map_record_ptr() {}
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::handle_object (concurrent_lru_cache & cache_ref, typename map_storage_type::reference value_ref) inline
Definition at line 119 of file concurrent_lru_cache.h.
 : my_cache_pointer(&cache_ref), my_map_record_ptr(&value_ref) {}
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::handle_object (handle_object && src) inline
Definition at line 125 of file concurrent_lru_cache.h.
References __TBB_ASSERT.
                                            : my_cache_pointer(src.my_cache_pointer), my_map_record_ptr(src.my_map_record_ptr) {
             __TBB_ASSERT((src.my_cache_pointer && src.my_map_record_ptr) || (!src.my_cache_pointer && !src.my_map_record_ptr), "invalid state of moving object?");
             src.my_cache_pointer = NULL;
             src.my_map_record_ptr = NULL;
         }
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::~handle_object () inline
Definition at line 160 of file concurrent_lru_cache.h.
References tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::signal_end_of_usage().
{
             if (my_cache_pointer){
                 my_cache_pointer->signal_end_of_usage(*my_map_record_ptr);
             }
         }
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::handle_object (handle_object &) private
Member Function Documentation
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::operator bool () const inline
Definition at line 120 of file concurrent_lru_cache.h.
{
             return (my_cache_pointer && my_map_record_ptr);
         }
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> handle_object& tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::operator= (handle_object && src) inline
Definition at line 130 of file concurrent_lru_cache.h.
References __TBB_ASSERT, tbb::move(), tbb::internal::no_assign::operator=(), and tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::signal_end_of_usage().
{
             __TBB_ASSERT((src.my_cache_pointer && src.my_map_record_ptr) || (!src.my_cache_pointer && !src.my_map_record_ptr), "invalid state of moving object?");
             if (my_cache_pointer) {
                 my_cache_pointer->signal_end_of_usage(*my_map_record_ptr);
             }
             my_cache_pointer = src.my_cache_pointer;
             my_map_record_ptr = src.my_map_record_ptr;
             src.my_cache_pointer = NULL;
             src.my_map_record_ptr = NULL;
             return *this;
         }
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> void tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::operator= (handle_object &) private
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> value_type& tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::value () inline
Definition at line 155 of file concurrent_lru_cache.h.
References __TBB_ASSERT.
{
             __TBB_ASSERT(my_cache_pointer,"get value from already moved object?");
             __TBB_ASSERT(my_map_record_ptr,"get value from an invalid or already moved object?");
             return my_map_record_ptr->second.my_value;
         }
Friends And Related Function Documentation
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> handle_object&& move (handle_object & h) friend
Definition at line 168 of file concurrent_lru_cache.h.
{
             return std::move(h);
         }
Member Data Documentation
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> concurrent_lru_cache* tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::my_cache_pointer private
Definition at line 115 of file concurrent_lru_cache.h.
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> map_storage_type::pointer tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_object::my_map_record_ptr private
Definition at line 116 of file concurrent_lru_cache.h.
The documentation for this class was generated from the following file:
concurrent_lru_cache.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.