Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface9::gfx_buffer< T > Class Template Reference
tbb::flow::interface9::gfx_buffer< T > Class Template Reference
#include <gfx_factory.h>
Public Types
typedef std::vector< T >::iterator iterator
typedef std::vector< T >::const_iterator const_iterator
typedef std::size_t size_type
Public Member Functions
gfx_buffer ()
gfx_buffer (size_type size)
T * data ()
const T * data () const
size_type size () const
const_iterator cbegin () const
const_iterator cend () const
iterator begin ()
iterator end ()
T & operator[] (size_type pos)
const T & operator[] (size_type pos) const
Private Attributes
std::shared_ptr< std::vector< T > > my_vector_ptr
Detailed Description
template<typename T>
class tbb::flow::interface9::gfx_buffer< T >
Definition at line 44 of file gfx_factory.h.
Member Typedef Documentation
template<typename T> typedef std::vector<T>::const_iterator tbb::flow::interface9::gfx_buffer< T >::const_iterator
Definition at line 117 of file gfx_factory.h.
template<typename T> typedef std::vector<T>::iterator tbb::flow::interface9::gfx_buffer< T >::iterator
Definition at line 116 of file gfx_factory.h.
template<typename T> typedef std::size_t tbb::flow::interface9::gfx_buffer< T >::size_type
Definition at line 119 of file gfx_factory.h.
Constructor & Destructor Documentation
template<typename T> tbb::flow::interface9::gfx_buffer< T >::gfx_buffer () inline
Definition at line 121 of file gfx_factory.h.
 : my_vector_ptr(std::make_shared< std::vector<T> >()) {}
template<typename T> tbb::flow::interface9::gfx_buffer< T >::gfx_buffer (size_type size) inline
Definition at line 122 of file gfx_factory.h.
 : my_vector_ptr(std::make_shared< std::vector<T> >(size)) {}
Member Function Documentation
template<typename T> iterator tbb::flow::interface9::gfx_buffer< T >::begin () inline
Definition at line 131 of file gfx_factory.h.
 { return my_vector_ptr->begin(); }
template<typename T> const_iterator tbb::flow::interface9::gfx_buffer< T >::cbegin () const inline
Definition at line 129 of file gfx_factory.h.
 { return my_vector_ptr->cbegin(); }
template<typename T> const_iterator tbb::flow::interface9::gfx_buffer< T >::cend () const inline
Definition at line 130 of file gfx_factory.h.
 { return my_vector_ptr->cend(); }
template<typename T> T* tbb::flow::interface9::gfx_buffer< T >::data () inline
Definition at line 124 of file gfx_factory.h.
Referenced by tbb::flow::interface9::gfx_offload::raw_data(), tbb::flow::interface9::gfx_factory::share_data(), and tbb::flow::interface9::gfx_factory::unshare_data().
 { return &(my_vector_ptr->front()); }
template<typename T> const T* tbb::flow::interface9::gfx_buffer< T >::data () const inline
Definition at line 125 of file gfx_factory.h.
 { return &(my_vector_ptr->front()); }
template<typename T> iterator tbb::flow::interface9::gfx_buffer< T >::end () inline
Definition at line 132 of file gfx_factory.h.
 { return my_vector_ptr->end(); }
template<typename T> T& tbb::flow::interface9::gfx_buffer< T >::operator[] (size_type pos) inline
Definition at line 134 of file gfx_factory.h.
 { return (*my_vector_ptr)[pos]; }
template<typename T> const T& tbb::flow::interface9::gfx_buffer< T >::operator[] (size_type pos) const inline
Definition at line 135 of file gfx_factory.h.
 { return (*my_vector_ptr)[pos]; }
template<typename T> size_type tbb::flow::interface9::gfx_buffer< T >::size () const inline
Definition at line 127 of file gfx_factory.h.
Referenced by tbb::flow::interface9::gfx_factory::share_data().
 { return my_vector_ptr->size(); }
Member Data Documentation
template<typename T> std::shared_ptr< std::vector<T> > tbb::flow::interface9::gfx_buffer< T >::my_vector_ptr private
Definition at line 138 of file gfx_factory.h.
The documentation for this class was generated from the following file:
gfx_factory.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.