Intel(R) Threading Building Blocks Doxygen Documentation: internal::indexer_node_base< InputTuple, OutputType, StructTypes > Class Template Reference
internal::indexer_node_base< InputTuple, OutputType, StructTypes > Class Template Reference
indexer_node_base
#include <_flow_graph_indexer_impl.h>
Classes
class indexer_node_base_operation
Public Types
typedef OutputType output_type
typedef StructTypes tuple_types
typedef sender< output_type >::successor_type successor_type
typedef indexer_node_FE< InputTuple, output_type, StructTypes > input_ports_type
Public Types inherited from internal::indexer_node_FE< InputTuple, OutputType, StructTypes >
typedef OutputType output_type
typedef InputTuple input_type
Public Member Functions
indexer_node_base (graph &g)
indexer_node_base (const indexer_node_base &other)
bool register_successor (successor_type &r) __TBB_override
bool remove_successor (successor_type &r) __TBB_override
task * try_put_task (output_type const *v)
Public Member Functions inherited from internal::indexer_node_FE< InputTuple, OutputType, StructTypes >
indexer_node_FE ()
input_type & input_ports ()
Static Public Attributes
static const size_t N = tbb::flow::tuple_size<InputTuple>::value
Static Public Attributes inherited from internal::indexer_node_FE< InputTuple, OutputType, StructTypes >
static const int N = tbb::flow::tuple_size<InputTuple>::value
Protected Member Functions
void reset_node (reset_flags f) __TBB_override
Private Types
enum op_type { reg_succ, rem_succ, try__put_task }
typedef indexer_node_base< InputTuple, output_type, StructTypes > class_type
typedef internal::aggregating_functor< class_type, indexer_node_base_operation > handler_type
Private Member Functions
void handle_operations (indexer_node_base_operation *op_list)
Private Attributes
aggregator< handler_type, indexer_node_base_operation > my_aggregator
broadcast_cache< output_type, null_rw_mutex > my_successors
Friends
class internal::aggregating_functor< class_type, indexer_node_base_operation >
Additional Inherited Members
Protected Attributes inherited from internal::indexer_node_FE< InputTuple, OutputType, StructTypes >
input_type my_inputs
Detailed Description
template<typename InputTuple, typename OutputType, typename StructTypes>
class internal::indexer_node_base< InputTuple, OutputType, StructTypes >
indexer_node_base
Definition at line 173 of file _flow_graph_indexer_impl.h.
Member Typedef Documentation
template<typename InputTuple , typename OutputType , typename StructTypes > typedef indexer_node_base<InputTuple,output_type,StructTypes> internal::indexer_node_base< InputTuple, OutputType, StructTypes >::class_type private
Definition at line 196 of file _flow_graph_indexer_impl.h.
template<typename InputTuple , typename OutputType , typename StructTypes > typedef internal::aggregating_functor<class_type, indexer_node_base_operation> internal::indexer_node_base< InputTuple, OutputType, StructTypes >::handler_type private
Definition at line 217 of file _flow_graph_indexer_impl.h.
template<typename InputTuple , typename OutputType , typename StructTypes > typedef indexer_node_FE<InputTuple, output_type,StructTypes> internal::indexer_node_base< InputTuple, OutputType, StructTypes >::input_ports_type
Definition at line 182 of file _flow_graph_indexer_impl.h.
template<typename InputTuple , typename OutputType , typename StructTypes > typedef OutputType internal::indexer_node_base< InputTuple, OutputType, StructTypes >::output_type
Definition at line 179 of file _flow_graph_indexer_impl.h.
template<typename InputTuple , typename OutputType , typename StructTypes > typedef sender<output_type>::successor_type internal::indexer_node_base< InputTuple, OutputType, StructTypes >::successor_type
Definition at line 181 of file _flow_graph_indexer_impl.h.
template<typename InputTuple , typename OutputType , typename StructTypes > typedef StructTypes internal::indexer_node_base< InputTuple, OutputType, StructTypes >::tuple_types
Definition at line 180 of file _flow_graph_indexer_impl.h.
Member Enumeration Documentation
template<typename InputTuple , typename OutputType , typename StructTypes > enum internal::indexer_node_base::op_type private
Enumerator
reg_succ
rem_succ
try__put_task
Definition at line 190 of file _flow_graph_indexer_impl.h.
                      { reg_succ, rem_succ, try__put_task
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
             , add_blt_succ, del_blt_succ,
              blt_succ_cnt, blt_succ_cpy
 #endif
         };
Constructor & Destructor Documentation
template<typename InputTuple , typename OutputType , typename StructTypes > internal::indexer_node_base< InputTuple, OutputType, StructTypes >::indexer_node_base (graph & g) inline
Definition at line 265 of file _flow_graph_indexer_impl.h.
References internal::indexer_helper< TupleTypes, N >::set_indexer_node_pointer().
                                     : graph_node(g), input_ports_type() {
             indexer_helper<StructTypes,N>::set_indexer_node_pointer(this->my_inputs, this, g);
             my_successors.set_owner(this);
             my_aggregator.initialize_handler(handler_type(this));
         }
template<typename InputTuple , typename OutputType , typename StructTypes > internal::indexer_node_base< InputTuple, OutputType, StructTypes >::indexer_node_base (const indexer_node_base< InputTuple, OutputType, StructTypes > & other) inline
Definition at line 271 of file _flow_graph_indexer_impl.h.
References internal::indexer_helper< TupleTypes, N >::set_indexer_node_pointer().
                                                           : graph_node(other.my_graph), input_ports_type(), sender<output_type>() {
             indexer_helper<StructTypes,N>::set_indexer_node_pointer(this->my_inputs, this, other.my_graph);
             my_successors.set_owner(this);
             my_aggregator.initialize_handler(handler_type(this));
         }
Member Function Documentation
template<typename InputTuple , typename OutputType , typename StructTypes > void internal::indexer_node_base< InputTuple, OutputType, StructTypes >::handle_operations (indexer_node_base_operation * op_list) inline private
Definition at line 221 of file _flow_graph_indexer_impl.h.
References tbb::internal::__TBB_store_with_release(), internal::indexer_node_base< InputTuple, OutputType, StructTypes >::indexer_node_base_operation::bypass_t, internal::indexer_node_base< InputTuple, OutputType, StructTypes >::indexer_node_base_operation::my_arg, internal::indexer_node_base< InputTuple, OutputType, StructTypes >::indexer_node_base_operation::my_succ, SUCCEEDED, and internal::indexer_node_base< InputTuple, OutputType, StructTypes >::indexer_node_base_operation::type.
{
             indexer_node_base_operation *current;
             while(op_list) {
                 current = op_list;
                 op_list = op_list->next;
                 switch(current->type) {
                 case reg_succ:
                     my_successors.register_successor(*(current->my_succ));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case rem_succ:
                     my_successors.remove_successor(*(current->my_succ));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case try__put_task: {
                         current->bypass_t = my_successors.try_put_task(*(current->my_arg));
                         __TBB_store_with_release(current->status, SUCCEEDED);  // return of try_put_task actual return value
                     }
                     break;
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
                 case add_blt_succ:
                     my_successors.internal_add_built_successor(*(current->my_succ));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case del_blt_succ:
                     my_successors.internal_delete_built_successor(*(current->my_succ));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case blt_succ_cnt:
                     current->cnt_val = my_successors.successor_count();
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case blt_succ_cpy:
                     my_successors.copy_successors(*(current->succv));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
 #endif  /* TBB_DEPRECATED_FLOW_NODE_EXTRACTION */
                 }
             }
         }
template<typename InputTuple , typename OutputType , typename StructTypes > bool internal::indexer_node_base< InputTuple, OutputType, StructTypes >::register_successor (successor_type & r) inline
Definition at line 277 of file _flow_graph_indexer_impl.h.
References SUCCEEDED.
{
             indexer_node_base_operation op_data(r, reg_succ);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
template<typename InputTuple , typename OutputType , typename StructTypes > bool internal::indexer_node_base< InputTuple, OutputType, StructTypes >::remove_successor (successor_type & r) inline
Definition at line 283 of file _flow_graph_indexer_impl.h.
References SUCCEEDED.
{
             indexer_node_base_operation op_data(r, rem_succ);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
template<typename InputTuple , typename OutputType , typename StructTypes > void internal::indexer_node_base< InputTuple, OutputType, StructTypes >::reset_node (reset_flags f) inline protected
Definition at line 326 of file _flow_graph_indexer_impl.h.
References internal::indexer_helper< TupleTypes, N >::reset_inputs(), and tbb::flow::interface10::rf_clear_edges.
{
             if(f & rf_clear_edges) {
                 my_successors.clear();
                 indexer_helper<StructTypes,N>::reset_inputs(this->my_inputs,f);
             }
         }
template<typename InputTuple , typename OutputType , typename StructTypes > task* internal::indexer_node_base< InputTuple, OutputType, StructTypes >::try_put_task (output_type const * v) inline
Definition at line 289 of file _flow_graph_indexer_impl.h.
References __TBB_override, and internal::indexer_node_base< InputTuple, OutputType, StructTypes >::indexer_node_base_operation::bypass_t.
                                                   { // not a virtual method in this class
             indexer_node_base_operation op_data(v, try__put_task);
             my_aggregator.execute(&op_data);
             return op_data.bypass_t;
         }
Friends And Related Function Documentation
template<typename InputTuple , typename OutputType , typename StructTypes > friend class internal::aggregating_functor< class_type, indexer_node_base_operation > friend
Definition at line 218 of file _flow_graph_indexer_impl.h.
Member Data Documentation
template<typename InputTuple , typename OutputType , typename StructTypes > aggregator<handler_type, indexer_node_base_operation> internal::indexer_node_base< InputTuple, OutputType, StructTypes >::my_aggregator private
Definition at line 219 of file _flow_graph_indexer_impl.h.
template<typename InputTuple , typename OutputType , typename StructTypes > broadcast_cache<output_type, null_rw_mutex> internal::indexer_node_base< InputTuple, OutputType, StructTypes >::my_successors private
Definition at line 334 of file _flow_graph_indexer_impl.h.
template<typename InputTuple , typename OutputType , typename StructTypes > const size_t internal::indexer_node_base< InputTuple, OutputType, StructTypes >::N = tbb::flow::tuple_size<InputTuple>::value static
Definition at line 178 of file _flow_graph_indexer_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_indexer_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.