Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::governor Class Reference
tbb::internal::governor Class Reference
The class handles access to the single instance of market, and to TLS to keep scheduler instances.
#include <governor.h>
Static Public Member Functions
static unsigned default_num_threads ()
static void one_time_init ()
static generic_scheduler * init_scheduler (int num_threads, stack_size_type stack_size, bool auto_init)
Processes scheduler initialization request (possibly nested) in a master thread.
static generic_scheduler * init_scheduler_weak ()
Automatic initialization of scheduler in a master thread with default settings without arena.
static bool terminate_scheduler (generic_scheduler *s, bool blocking)
Processes scheduler termination request (possibly nested) in a master thread.
static void sign_on (generic_scheduler *s)
Register TBB scheduler instance in thread-local storage.
static void sign_off (generic_scheduler *s)
Unregister TBB scheduler instance from thread-local storage.
static bool is_set (generic_scheduler *s)
Used to check validity of the local scheduler TLS contents.
static void assume_scheduler (generic_scheduler *s)
Temporarily set TLS slot to the given scheduler.
static uintptr_t tls_value_of (generic_scheduler *s)
Computes the value of the TLS.
static generic_scheduler * tls_scheduler_of (uintptr_t v)
Converts TLS value to the scheduler pointer.
static generic_scheduler * local_scheduler ()
Obtain the thread-local instance of the TBB scheduler.
static generic_scheduler * local_scheduler_weak ()
static generic_scheduler * local_scheduler_if_initialized ()
static void terminate_auto_initialized_scheduler ()
Undo automatic initialization if necessary; call when a thread exits.
static void print_version_info ()
static void initialize_rml_factory ()
static bool does_client_join_workers (const tbb::internal::rml::tbb_client &client)
static bool speculation_enabled ()
static bool rethrow_exception_broken ()
Static Private Member Functions
static void acquire_resources ()
Create key for thread-local storage and initialize RML.
static void release_resources ()
Destroy the thread-local storage key and deinitialize RML.
static rml::tbb_server * create_rml_server (rml::tbb_client &)
static void auto_terminate (void *scheduler)
The internal routine to undo automatic initialization.
Static Private Attributes
static basic_tls< uintptr_t > theTLS
TLS for scheduler instances associated with individual threads.
static unsigned DefaultNumberOfThreads
Caches the maximal level of parallelism supported by the hardware.
static rml::tbb_factory theRMLServerFactory
static bool UsePrivateRML
static bool is_speculation_enabled
static bool is_rethrow_broken
Friends
class __TBB_InitOnce
class market
Detailed Description
The class handles access to the single instance of market, and to TLS to keep scheduler instances.
It also supports automatic on-demand initialization of the TBB scheduler. The class contains only static data members and methods.
Definition at line 52 of file governor.h.
Member Function Documentation
void tbb::internal::governor::acquire_resources () static private
Create key for thread-local storage and initialize RML.
Definition at line 71 of file governor.cpp.
References tbb::internal::cpu_has_speculation(), tbb::internal::gcc_rethrow_exception_broken(), and tbb::internal::handle_perror().
Referenced by tbb::internal::__TBB_InitOnce::add_ref().
{
 #if USE_PTHREAD
     int status = theTLS.create(auto_terminate);
 #else
     int status = theTLS.create();
 #endif
     if( status )
         handle_perror(status, "TBB failed to initialize task scheduler TLS\n");
     is_speculation_enabled = cpu_has_speculation();
     is_rethrow_broken = gcc_rethrow_exception_broken();
 }
void tbb::internal::governor::assume_scheduler (generic_scheduler * s) static
Temporarily set TLS slot to the given scheduler.
Definition at line 120 of file governor.cpp.
Referenced by tbb::internal::market::cleanup(), tbb::internal::generic_scheduler::nested_arena_entry(), and tbb::internal::nested_arena_context::~nested_arena_context().
{
     theTLS.set( tls_value_of(s) );
 }
void tbb::internal::governor::auto_terminate (void * scheduler) static private
The internal routine to undo automatic initialization.
The signature is written with void* so that the routine can be the destructor argument to pthread_key_create.
Definition at line 217 of file governor.cpp.
References __TBB_ASSERT, tbb::internal::generic_scheduler::cleanup_master(), tbb::internal::generic_scheduler::my_auto_initialized, tbb::internal::generic_scheduler::my_ref_count, and s.
{
     generic_scheduler* s = tls_scheduler_of( uintptr_t(arg) ); // arg is equivalent to theTLS.get()
     if( s && s->my_auto_initialized ) {
         if( !--(s->my_ref_count) ) {
             // If the TLS slot is already cleared by OS or underlying concurrency
             // runtime, restore its value.
             if( !is_set(s) )
                 assume_scheduler(s);
             s->cleanup_master( /*blocking_terminate=*/false );
             __TBB_ASSERT( is_set(NULL), "cleanup_master has not cleared its TLS slot" );
         }
     }
 }
rml::tbb_server * tbb::internal::governor::create_rml_server (rml::tbb_client & client) static private
Definition at line 96 of file governor.cpp.
References __TBB_ASSERT, tbb::internal::rml::make_private_server(), and tbb::internal::runtime_warning().
Referenced by tbb::internal::market::market().
{
     rml::tbb_server* server = NULL;
     if( !UsePrivateRML ) {
         ::rml::factory::status_type status = theRMLServerFactory.make_server( server, client );
         if( status != ::rml::factory::st_success ) {
             UsePrivateRML = true;
             runtime_warning( "rml::tbb_factory::make_server failed with status %x, falling back on private rml", status );
         }
     }
     if ( !server ) {
         __TBB_ASSERT( UsePrivateRML, NULL );
         server = rml::make_private_server( client );
     }
     __TBB_ASSERT( server, "Failed to create RML server" );
     return server;
 }
static unsigned tbb::internal::governor::default_num_threads () inline static
Definition at line 85 of file governor.h.
References tbb::internal::AvailableHwConcurrency(), and s.
Referenced by tbb::internal::calc_workers_soft_limit(), tbb::internal::rml::private_server::default_concurrency(), tbb::task_scheduler_init::default_num_threads(), tbb::internal::allowed_parallelism_control::default_value(), tbb::internal::DoOneTimeInitializations(), tbb::internal::market::global_market(), tbb::internal::tbb_thread_v3::hardware_concurrency(), tbb::interface7::internal::task_arena_base::internal_initialize(), and tbb::interface7::internal::task_arena_base::internal_max_concurrency().
{
         // No memory fence required, because at worst each invoking thread calls AvailableHwConcurrency once.
         return DefaultNumberOfThreads ? DefaultNumberOfThreads :
                                         DefaultNumberOfThreads = AvailableHwConcurrency();
     }
bool tbb::internal::governor::does_client_join_workers (const tbb::internal::rml::tbb_client & client) static
Definition at line 296 of file market.cpp.
Referenced by tbb::internal::rml::private_worker::start_shutdown(), and tbb::internal::rml::private_worker::wake_or_launch().
{
     return ((const market&)client).must_join_workers();
 }
generic_scheduler * tbb::internal::governor::init_scheduler (int num_threads, stack_size_type stack_size, bool auto_init) static
Processes scheduler initialization request (possibly nested) in a master thread.
If necessary creates new instance of arena and/or local scheduler. The auto_init argument specifies if the call is due to automatic initialization.
Definition at line 176 of file governor.cpp.
References __TBB_ASSERT, tbb::internal::generic_scheduler::attach_arena(), tbb::task_scheduler_init::automatic, tbb::internal::market::create_arena(), tbb::internal::generic_scheduler::create_master(), tbb::internal::scheduler_state::my_arena, tbb::internal::scheduler_state::my_arena_index, tbb::internal::scheduler_state::my_arena_slot, tbb::internal::generic_scheduler::my_auto_initialized, tbb::internal::generic_scheduler::my_ref_count, tbb::internal::arena_slot_line1::my_scheduler, and s.
Referenced by tbb::task_scheduler_init::initialize().
{
     one_time_init();
     if ( uintptr_t v = theTLS.get() ) {
         generic_scheduler* s = tls_scheduler_of( v );
         if ( (v&1) == 0 ) { // TLS holds scheduler instance without arena
             __TBB_ASSERT( s->my_ref_count == 1, "weakly initialized scheduler must have refcount equal to 1" );
             __TBB_ASSERT( !s->my_arena, "weakly initialized scheduler  must have no arena" );
             __TBB_ASSERT( s->my_auto_initialized, "weakly initialized scheduler is supposed to be auto-initialized" );
             s->attach_arena( market::create_arena( default_num_threads(), 1, 0 ), 0, /*is_master*/true );
             __TBB_ASSERT( s->my_arena_index == 0, "Master thread must occupy the first slot in its arena" );
             s->my_arena_slot->my_scheduler = s;
             s->my_arena->my_default_ctx = s->default_context(); // it also transfers implied ownership
             // Mark the scheduler as fully initialized
             assume_scheduler( s );
         }
         // Increment refcount only for explicit instances of task_scheduler_init.
         if ( !auto_init ) s->my_ref_count += 1;
         __TBB_ASSERT( s->my_arena, "scheduler is not initialized fully" );
         return s;
     }
     // Create new scheduler instance with arena
     if( num_threads == task_scheduler_init::automatic )
         num_threads = default_num_threads();
     arena *a = market::create_arena( num_threads, 1, stack_size );
     generic_scheduler* s = generic_scheduler::create_master( a );
     __TBB_ASSERT(s, "Somehow a local scheduler creation for a master thread failed");
     __TBB_ASSERT( is_set(s), NULL );
     s->my_auto_initialized = auto_init;
     return s;
 }
generic_scheduler * tbb::internal::governor::init_scheduler_weak () static
Automatic initialization of scheduler in a master thread with default settings without arena.
Definition at line 168 of file governor.cpp.
References __TBB_ASSERT, tbb::internal::generic_scheduler::create_master(), tbb::internal::generic_scheduler::my_auto_initialized, and s.
{
     one_time_init();
     __TBB_ASSERT( is_set(NULL), "TLS contains a scheduler?" );
     generic_scheduler* s = generic_scheduler::create_master( NULL ); // without arena
     s->my_auto_initialized = true;
     return s;
 }
void tbb::internal::governor::initialize_rml_factory () static
Definition at line 244 of file governor.cpp.
References __TBB_ASSERT, CILK_TBB_STACK_ADOPT, CILK_TBB_STACK_ORPHAN, CILK_TBB_STACK_RELEASE, data, tbb::internal::runtime_warning(), and s.
Referenced by tbb::internal::DoOneTimeInitializations().
{
     ::rml::factory::status_type res = theRMLServerFactory.open();
     UsePrivateRML = res != ::rml::factory::st_success;
 }
bool tbb::internal::governor::is_set (generic_scheduler * s) static
Used to check validity of the local scheduler TLS contents.
Definition at line 124 of file governor.cpp.
Referenced by tbb::internal::generic_scheduler::cleanup_master(), tbb::internal::generic_scheduler::generic_scheduler(), tbb::internal::generic_scheduler::local_spawn(), tbb::internal::generic_scheduler::local_spawn_root_and_wait(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::internal::arena::process(), and tbb::internal::market::process().
{
     return theTLS.get() == tls_value_of(s);
 }
static generic_scheduler* tbb::internal::governor::local_scheduler () inline static
Obtain the thread-local instance of the TBB scheduler.
If the scheduler has not been initialized yet, initialization is done automatically. Note that auto-initialized scheduler instance is destroyed only when its thread terminates.
Definition at line 126 of file governor.h.
References tbb::task_scheduler_init::automatic, and tbb::internal::basic_tls< T >::get().
Referenced by tbb::internal::arena::advertise_new_work(), tbb::internal::generic_scheduler::enqueue(), tbb::internal::get_initial_auto_partitioner_divisor(), tbb::internal::affinity_partitioner_base_v3::resize(), tbb::internal::generic_scheduler::spawn(), tbb::task::spawn_and_wait_for_all(), tbb::internal::generic_scheduler::spawn_root_and_wait(), and tbb::internal::custom_scheduler< SchedulerTraits >::wait_for_all().
{
         uintptr_t v = theTLS.get();
         return (v&1) ? tls_scheduler_of(v) : init_scheduler( task_scheduler_init::automatic, 0, /*auto_init=*/true );
     }
static generic_scheduler* tbb::internal::governor::local_scheduler_if_initialized () inline static
Definition at line 136 of file governor.h.
References tbb::internal::basic_tls< T >::get().
Referenced by tbb::internal::market::adjust_demand(), tbb::internal::market::cleanup(), tbb::internal::market::create_one_job(), tbb::internal::arena::enqueue_task(), tbb::interface7::internal::wait_task::execute(), tbb::interface7::internal::task_arena_base::internal_attach(), tbb::interface7::internal::task_arena_base::internal_current_slot(), tbb::interface7::internal::task_arena_base::internal_enqueue(), tbb::interface7::internal::task_arena_base::internal_max_concurrency(), and tbb::internal::market::is_arena_in_list().
{
         return tls_scheduler_of( theTLS.get() );
     }
static generic_scheduler* tbb::internal::governor::local_scheduler_weak () inline static
Definition at line 131 of file governor.h.
References tbb::internal::basic_tls< T >::get().
Referenced by tbb::internal::allocate_additional_child_of_proxy::allocate(), tbb::internal::allocate_root_proxy::allocate(), tbb::internal::allocate_continuation_proxy::allocate(), tbb::internal::allocate_child_proxy::allocate(), tbb::interface5::internal::task_base::destroy(), tbb::internal::allocate_additional_child_of_proxy::free(), tbb::internal::allocate_root_proxy::free(), tbb::internal::allocate_continuation_proxy::free(), tbb::internal::allocate_child_proxy::free(), tbb::interface7::internal::task_arena_base::internal_current_slot(), tbb::interface7::internal::task_arena_base::internal_execute(), tbb::interface7::internal::task_arena_base::internal_initialize(), tbb::interface7::internal::task_arena_base::internal_wait(), tbb::task::note_affinity(), and tbb::task::self().
{
         uintptr_t v = theTLS.get();
         return v ? tls_scheduler_of(v) : init_scheduler_weak();
     }
void tbb::internal::governor::one_time_init () static
Definition at line 160 of file governor.cpp.
References tbb::internal::atomic_do_once(), tbb::internal::DoOneTimeInitializations(), and tbb::internal::__TBB_InitOnce::initialization_done().
Referenced by tbb::interface7::internal::task_arena_base::internal_initialize().
{
     if( !__TBB_InitOnce::initialization_done() )
         DoOneTimeInitializations();
 #if __TBB_SURVIVE_THREAD_SWITCH
     atomic_do_once( &initialize_cilk_interop, cilkrts_load_state );
 #endif /* __TBB_SURVIVE_THREAD_SWITCH */
 }
void tbb::internal::governor::print_version_info () static
Definition at line 231 of file governor.cpp.
References tbb::internal::PrintExtraVersionInfo(), and tbb::internal::PrintRMLVersionInfo().
Referenced by tbb::internal::DoOneTimeInitializations().
{
     if ( UsePrivateRML )
         PrintExtraVersionInfo( "RML", "private" );
     else {
         PrintExtraVersionInfo( "RML", "shared" );
         theRMLServerFactory.call_with_server_info( PrintRMLVersionInfo, (void*)"" );
     }
 #if __TBB_SURVIVE_THREAD_SWITCH
     if( watch_stack_handler )
         PrintExtraVersionInfo( "CILK", CILKLIB_NAME );
 #endif /* __TBB_SURVIVE_THREAD_SWITCH */
 }
void tbb::internal::governor::release_resources () static private
Destroy the thread-local storage key and deinitialize RML.
Definition at line 83 of file governor.cpp.
References tbb::internal::destroy_process_mask(), dynamic_unlink_all(), tbb::internal::__TBB_InitOnce::initialization_done(), and tbb::internal::runtime_warning().
Referenced by tbb::internal::__TBB_InitOnce::remove_ref().
{
     theRMLServerFactory.close();
     destroy_process_mask();
 #if TBB_USE_ASSERT
     if( __TBB_InitOnce::initialization_done() && theTLS.get() )
         runtime_warning( "TBB is unloaded while tbb::task_scheduler_init object is alive?" );
 #endif
     int status = theTLS.destroy();
     if( status )
         runtime_warning("failed to destroy task scheduler TLS: %s", strerror(status));
     dynamic_unlink_all();
 }
static bool tbb::internal::governor::rethrow_exception_broken () inline static
Definition at line 156 of file governor.h.
 { return is_rethrow_broken; }
void tbb::internal::governor::sign_off (generic_scheduler * s) static
Unregister TBB scheduler instance from thread-local storage.
Definition at line 149 of file governor.cpp.
References __TBB_ASSERT, __cilk_tbb_unwatch_thunk::data, __cilk_tbb_unwatch_thunk::routine, and tbb::internal::suppress_unused_warning().
Referenced by tbb::internal::generic_scheduler::free_scheduler().
{
     suppress_unused_warning(s);
     __TBB_ASSERT( is_set(s), "attempt to unregister a wrong scheduler instance" );
     assume_scheduler(NULL);
 #if __TBB_SURVIVE_THREAD_SWITCH
     __cilk_tbb_unwatch_thunk &ut = s->my_cilk_unwatch_thunk;
     if ( ut.routine )
        (*ut.routine)(ut.data);
 #endif /* __TBB_SURVIVE_THREAD_SWITCH */
 }
void tbb::internal::governor::sign_on (generic_scheduler * s) static
Register TBB scheduler instance in thread-local storage.
Definition at line 128 of file governor.cpp.
References __TBB_ASSERT, __cilk_tbb_stack_op_thunk::data, __cilk_tbb_stack_op_thunk::routine, and s.
Referenced by tbb::internal::generic_scheduler::create_master(), and tbb::internal::generic_scheduler::create_worker().
{
     __TBB_ASSERT( is_set(NULL) && s, NULL );
     assume_scheduler( s );
 #if __TBB_SURVIVE_THREAD_SWITCH
     if( watch_stack_handler ) {
         __cilk_tbb_stack_op_thunk o;
         o.routine = &stack_op_handler;
         o.data = s;
         if( (*watch_stack_handler)(&s->my_cilk_unwatch_thunk, o) ) {
             // Failed to register with cilkrts, make sure we are clean
             s->my_cilk_unwatch_thunk.routine = NULL;
         }
 #if TBB_USE_ASSERT
         else
             s->my_cilk_state = generic_scheduler::cs_running;
 #endif /* TBB_USE_ASSERT */
     }
 #endif /* __TBB_SURVIVE_THREAD_SWITCH */
     __TBB_ASSERT( is_set(s), NULL );
 }
static bool tbb::internal::governor::speculation_enabled () inline static
Definition at line 155 of file governor.h.
Referenced by tbb::mutex::internal_destroy().
 { return is_speculation_enabled; }
static void tbb::internal::governor::terminate_auto_initialized_scheduler () inline static
Undo automatic initialization if necessary; call when a thread exits.
Definition at line 141 of file governor.h.
Referenced by tbb::internal::DoOneTimeInitializations(), and tbb::internal::__TBB_InitOnce::~__TBB_InitOnce().
{
         auto_terminate( local_scheduler_if_initialized() );
     }
bool tbb::internal::governor::terminate_scheduler (generic_scheduler * s, bool blocking) static
Processes scheduler termination request (possibly nested) in a master thread.
Definition at line 207 of file governor.cpp.
References __TBB_ASSERT, tbb::internal::generic_scheduler::cleanup_master(), and tbb::internal::generic_scheduler::my_ref_count.
Referenced by tbb::task_scheduler_init::internal_terminate().
{
     bool ok = false;
     __TBB_ASSERT( is_set(s), "Attempt to terminate non-local scheduler instance" );
     if (0 == --(s->my_ref_count)) {
         ok = s->cleanup_master( blocking );
         __TBB_ASSERT( is_set(NULL), "cleanup_master has not cleared its TLS slot" );
     }
     return ok;
 }
static generic_scheduler* tbb::internal::governor::tls_scheduler_of (uintptr_t v) inline static
Converts TLS value to the scheduler pointer.
Definition at line 119 of file governor.h.
{
         return (generic_scheduler*)(v & ~uintptr_t(1));
     }
uintptr_t tbb::internal::governor::tls_value_of (generic_scheduler * s) static
Computes the value of the TLS.
Definition at line 114 of file governor.cpp.
References __TBB_ASSERT, tbb::internal::generic_scheduler::is_worker(), and tbb::internal::scheduler_state::my_arena.
{
     __TBB_ASSERT( (uintptr_t(s)&1) == 0, "Bad pointer to the scheduler" );
     // LSB marks the scheduler initialized with arena
     return uintptr_t(s) | uintptr_t((s && (s->my_arena || s->is_worker()))? 1 : 0);
 }
Friends And Related Function Documentation
friend class __TBB_InitOnce friend
Definition at line 54 of file governor.h.
friend class market friend
Definition at line 55 of file governor.h.
Member Data Documentation
unsigned tbb::internal::governor::DefaultNumberOfThreads static private
Caches the maximal level of parallelism supported by the hardware.
Definition at line 61 of file governor.h.
bool tbb::internal::governor::is_rethrow_broken static private
Definition at line 69 of file governor.h.
bool tbb::internal::governor::is_speculation_enabled static private
Definition at line 68 of file governor.h.
rml::tbb_factory tbb::internal::governor::theRMLServerFactory static private
Definition at line 63 of file governor.h.
basic_tls< uintptr_t > tbb::internal::governor::theTLS static private
TLS for scheduler instances associated with individual threads.
Definition at line 58 of file governor.h.
bool tbb::internal::governor::UsePrivateRML static private
Definition at line 65 of file governor.h.
Referenced by tbb::internal::market::global_market().
The documentation for this class was generated from the following files:
governor.h
governor.cpp
market.cpp
tbb_main.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.