Intel(R) Threading Building Blocks Doxygen Documentation: tbb::concurrent_vector< T, A >::internal_loop_guide Class Reference
tbb::concurrent_vector< T, A >::internal_loop_guide Class Reference
Exception-aware helper class for filling a segment by exception-danger operators of user class.
Public Member Functions
internal_loop_guide (size_type ntrials, void *ptr)
void init ()
void init (const void *src)
void copy (const void *src)
void assign (const void *src)
void move_assign (const void *src)
void move_construct (const void *src)
template<class I >
void iterate (I &src)
~internal_loop_guide ()
Static Public Member Functions
static const T * as_const_pointer (const void *ptr)
static T * as_pointer (const void *src)
Public Attributes
const pointer array
const size_type n
size_type i
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
template<typename T, class A>
class tbb::concurrent_vector< T, A >::internal_loop_guide
Exception-aware helper class for filling a segment by exception-danger operators of user class.
Definition at line 1099 of file concurrent_vector.h.
Constructor & Destructor Documentation
template<typename T, class A> tbb::concurrent_vector< T, A >::internal_loop_guide::internal_loop_guide (size_type ntrials, void * ptr) inline
Definition at line 1108 of file concurrent_vector.h.
             : array(as_pointer(ptr)), n(ntrials), i(0) {}
template<typename T, class A> tbb::concurrent_vector< T, A >::internal_loop_guide::~internal_loop_guide () inline
Definition at line 1124 of file concurrent_vector.h.
References tbb::internal::handle_unconstructed_elements().
{
             if(i < n) {// if an exception was raised, fill the rest of items with zeros
                 internal::handle_unconstructed_elements(array+i, n-i);
             }
         }
Member Function Documentation
template<typename T, class A> static const T* tbb::concurrent_vector< T, A >::internal_loop_guide::as_const_pointer (const void * ptr) inline static
Definition at line 1105 of file concurrent_vector.h.
 { return static_cast<const T *>(ptr); }
template<typename T, class A> static T* tbb::concurrent_vector< T, A >::internal_loop_guide::as_pointer (const void * src) inline static
Definition at line 1106 of file concurrent_vector.h.
 { return static_cast<T*>(const_cast<void *>(src)); }
template<typename T, class A> void tbb::concurrent_vector< T, A >::internal_loop_guide::assign (const void * src) inline
Definition at line 1113 of file concurrent_vector.h.
Referenced by tbb::concurrent_vector< T, A >::assign_array().
 { for(; i < n; ++i) array[i] = as_const_pointer(src)[i]; }
template<typename T, class A> void tbb::concurrent_vector< T, A >::internal_loop_guide::copy (const void * src) inline
Definition at line 1112 of file concurrent_vector.h.
Referenced by tbb::concurrent_vector< T, A >::copy_array().
 { for(; i < n; ++i) new( &array[i] ) T(as_const_pointer(src)[i]); }
template<typename T, class A> void tbb::concurrent_vector< T, A >::internal_loop_guide::init () inline
Definition at line 1110 of file concurrent_vector.h.
Referenced by tbb::concurrent_vector< T, A >::initialize_array(), and tbb::concurrent_vector< T, A >::initialize_array_by().
 {   for(; i < n; ++i) new( &array[i] ) T(); }
template<typename T, class A> void tbb::concurrent_vector< T, A >::internal_loop_guide::init (const void * src) inline
Definition at line 1111 of file concurrent_vector.h.
 { for(; i < n; ++i) new( &array[i] ) T(*as_const_pointer(src)); }
template<typename T, class A> template<class I > void tbb::concurrent_vector< T, A >::internal_loop_guide::iterate (I & src) inline
Definition at line 1123 of file concurrent_vector.h.
Referenced by tbb::concurrent_vector< T, A >::copy_range(), and tbb::concurrent_vector< T, A >::internal_assign_iterators().
 { for(; i < n; ++i, ++src) new( &array[i] ) T( *src ); }
template<typename T, class A> void tbb::concurrent_vector< T, A >::internal_loop_guide::move_assign (const void * src) inline
Definition at line 1115 of file concurrent_vector.h.
References tbb::move().
Referenced by tbb::concurrent_vector< T, A >::move_assign_array().
 { for(; i < n; ++i) array[i]         =  std::move(as_pointer(src)[i]);   }
template<typename T, class A> void tbb::concurrent_vector< T, A >::internal_loop_guide::move_construct (const void * src) inline
Definition at line 1116 of file concurrent_vector.h.
References tbb::move().
Referenced by tbb::concurrent_vector< T, A >::move_array().
 { for(; i < n; ++i) new( &array[i] ) T( std::move(as_pointer(src)[i]) ); }
Member Data Documentation
template<typename T, class A> const pointer tbb::concurrent_vector< T, A >::internal_loop_guide::array
Definition at line 1101 of file concurrent_vector.h.
template<typename T, class A> size_type tbb::concurrent_vector< T, A >::internal_loop_guide::i
Definition at line 1103 of file concurrent_vector.h.
template<typename T, class A> const size_type tbb::concurrent_vector< T, A >::internal_loop_guide::n
Definition at line 1102 of file concurrent_vector.h.
The documentation for this class was generated from the following file:
concurrent_vector.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.