Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::graph Class Reference
tbb::flow::interface10::graph Class Reference
The graph class.
#include <_flow_graph_impl.h>
Classes
class run_and_put_task
class run_task
class spawn_functor
A functor that spawns a task.
class wait_functor
Public Types
typedef graph_iterator< graph, graph_node > iterator
typedef graph_iterator< const graph, const graph_node > const_iterator
Public Member Functions
graph ()
Constructs a graph with isolated task_group_context.
graph (tbb::task_group_context &use_this_context)
Constructs a graph with use_this_context as context.
~graph ()
Destroys the graph.
void increment_wait_count ()
void decrement_wait_count ()
void reserve_wait () __TBB_override
Used to register that an external entity may still interact with the graph.
void release_wait () __TBB_override
Deregisters an external entity that may have interacted with the graph.
template<typename Receiver , typename Body >
void run (Receiver &r, Body body)
Spawns a task that runs a body and puts its output to a specific receiver.
template<typename Body >
void run (Body body)
Spawns a task that runs a function object.
void wait_for_all ()
Wait until graph is idle and decrement_wait_count calls equals increment_wait_count calls.
tbb::task * root_task ()
Returns the root task of the graph.
iterator begin ()
start iterator
iterator end ()
end iterator
const_iterator begin () const
start const iterator
const_iterator end () const
end const iterator
const_iterator cbegin () const
start const iterator
const_iterator cend () const
end const iterator
bool is_cancelled ()
return status of graph execution
bool exception_thrown ()
void reset (reset_flags f=rf_reset_protocol)
Private Types
typedef std::list< tbb::task * > task_list_type
Private Member Functions
void prepare_task_arena (bool reinit=false)
void register_node (graph_node *n)
void remove_node (graph_node *n)
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
tbb::task * my_root_task
tbb::task_group_context * my_context
bool own_context
bool cancelled
bool caught_exception
bool my_is_active
task_list_type my_reset_task_list
graph_node * my_nodes
graph_node * my_nodes_last
tbb::spin_mutex nodelist_mutex
tbb::task_arena * my_task_arena
internal::graph_task_priority_queue_t my_priority_queue
Friends
class graph_node
template<typename C , typename N >
class graph_iterator
template<typename Input , typename Output , typename Policy , typename Allocator >
class async_node
class tbb::interface7::internal::task_arena_base
void internal::activate_graph (graph &g)
void internal::deactivate_graph (graph &g)
bool internal::is_graph_active (graph &g)
void internal::spawn_in_graph_arena (graph &g, tbb::task &arena_task)
void internal::add_task_to_graph_reset_list (graph &g, tbb::task *tp)
template<typename F >
void internal::execute_in_graph_arena (graph &g, F &f)
Detailed Description
The graph class.
This class serves as a handle to the graph
Definition at line 200 of file _flow_graph_impl.h.
Member Typedef Documentation
typedef graph_iterator<const graph, const graph_node> tbb::flow::interface10::graph::const_iterator
Definition at line 367 of file _flow_graph_impl.h.
typedef graph_iterator<graph, graph_node> tbb::flow::interface10::graph::iterator
Definition at line 366 of file _flow_graph_impl.h.
typedef std::list<tbb::task *> tbb::flow::interface10::graph::task_list_type private
Definition at line 235 of file _flow_graph_impl.h.
Constructor & Destructor Documentation
tbb::flow::interface10::graph::graph () inline
Constructs a graph with isolated task_group_context.
Definition at line 745 of file flow_graph.h.
                     : my_nodes(NULL), my_nodes_last(NULL), my_task_arena(NULL) {
     prepare_task_arena();
     own_context = true;
     cancelled = false;
     caught_exception = false;
     my_context = new task_group_context(tbb::internal::FLOW_TASKS);
     my_root_task = (new (task::allocate_root(*my_context)) empty_task);
     my_root_task->set_ref_count(1);
     tbb::internal::fgt_graph(this);
     my_is_active = true;
 }
tbb::flow::interface10::graph::graph (tbb::task_group_context & use_this_context) inline explicit
Constructs a graph with use_this_context as context.
Definition at line 757 of file flow_graph.h.
                                                         :
     my_context(&use_this_context), my_nodes(NULL), my_nodes_last(NULL), my_task_arena(NULL) {
     prepare_task_arena();
     own_context = false;
     my_root_task = (new (task::allocate_root(*my_context)) empty_task);
     my_root_task->set_ref_count(1);
     tbb::internal::fgt_graph(this);
     my_is_active = true;
 }
tbb::flow::interface10::graph::~graph () inline
Destroys the graph.
Calls wait_for_all, then destroys the root task and context.
Definition at line 767 of file flow_graph.h.
References my_root_task, tbb::task::set_ref_count(), and wait_for_all().
                      {
     wait_for_all();
     my_root_task->set_ref_count(0);
     tbb::task::destroy(*my_root_task);
     if (own_context) delete my_context;
     delete my_task_arena;
 }
Member Function Documentation
graph::iterator tbb::flow::interface10::graph::begin () inline
start iterator
Definition at line 835 of file flow_graph.h.
Referenced by reset().
 { return iterator(this, true); }
graph::const_iterator tbb::flow::interface10::graph::begin () const inline
start const iterator
Definition at line 839 of file flow_graph.h.
 { return const_iterator(this, true); }
graph::const_iterator tbb::flow::interface10::graph::cbegin () const inline
start const iterator
Definition at line 843 of file flow_graph.h.
 { return const_iterator(this, true); }
graph::const_iterator tbb::flow::interface10::graph::cend () const inline
end const iterator
Definition at line 845 of file flow_graph.h.
 { return const_iterator(this, false); }
void tbb::flow::interface10::graph::decrement_wait_count () inline
Definition at line 288 of file _flow_graph_impl.h.
References __TBB_override.
{
         release_wait();
     }
graph::iterator tbb::flow::interface10::graph::end () inline
end iterator
Definition at line 837 of file flow_graph.h.
Referenced by reset().
 { return iterator(this, false); }
graph::const_iterator tbb::flow::interface10::graph::end () const inline
end const iterator
Definition at line 841 of file flow_graph.h.
 { return const_iterator(this, false); }
bool tbb::flow::interface10::graph::exception_thrown () inline
Definition at line 385 of file _flow_graph_impl.h.
References tbb::flow::interface10::rf_reset_protocol.
 { return caught_exception; }
void tbb::flow::interface10::graph::increment_wait_count () inline
Definition at line 284 of file _flow_graph_impl.h.
{
         reserve_wait();
     }
bool tbb::flow::interface10::graph::is_cancelled () inline
return status of graph execution
Definition at line 384 of file _flow_graph_impl.h.
 { return cancelled; }
void tbb::flow::interface10::graph::prepare_task_arena (bool reinit = false) inline private
Definition at line 254 of file _flow_graph_impl.h.
References __TBB_ASSERT, and name.
Referenced by reset(), and tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task().
{
         if (reinit) {
             __TBB_ASSERT(my_task_arena, "task arena is NULL");
             my_task_arena->terminate();
             my_task_arena->initialize(tbb::task_arena::attach());
         }
         else {
             __TBB_ASSERT(my_task_arena == NULL, "task arena is not NULL");
             my_task_arena = new tbb::task_arena(tbb::task_arena::attach());
         }
         if (!my_task_arena->is_active()) // failed to attach
             my_task_arena->initialize(); // create a new, default-initialized arena
         __TBB_ASSERT(my_task_arena->is_active(), "task arena is not active");
     }
void tbb::flow::interface10::graph::register_node (graph_node * n) inline private
Definition at line 789 of file flow_graph.h.
{
     n->next = NULL;
     {
         spin_mutex::scoped_lock lock(nodelist_mutex);
         n->prev = my_nodes_last;
         if (my_nodes_last) my_nodes_last->next = n;
         my_nodes_last = n;
         if (!my_nodes) my_nodes = n;
     }
 }
void tbb::flow::interface10::graph::release_wait () inline
Deregisters an external entity that may have interacted with the graph.
The graph will not return from wait_for_all until all the number of decrement_wait_count calls matches the number of increment_wait_count calls.
Definition at line 782 of file flow_graph.h.
{
     if (my_root_task) {
         tbb::internal::fgt_release_wait(this);
         my_root_task->decrement_ref_count();
     }
 }
void tbb::flow::interface10::graph::remove_node (graph_node * n) inline private
Definition at line 800 of file flow_graph.h.
{
     {
         spin_mutex::scoped_lock lock(nodelist_mutex);
         __TBB_ASSERT(my_nodes && my_nodes_last, "graph::remove_node: Error: no registered nodes");
         if (n->prev) n->prev->next = n->next;
         if (n->next) n->next->prev = n->prev;
         if (my_nodes_last == n) my_nodes_last = n->prev;
         if (my_nodes == n) my_nodes = n->next;
     }
     n->prev = n->next = NULL;
 }
void tbb::flow::interface10::graph::reserve_wait () inline
Used to register that an external entity may still interact with the graph.
The graph will not return from wait_for_all until a matching number of decrement_wait_count calls is made.
Definition at line 775 of file flow_graph.h.
{
     if (my_root_task) {
         my_root_task->increment_ref_count();
         tbb::internal::fgt_reserve_wait(this);
     }
 }
void tbb::flow::interface10::graph::reset (reset_flags f = rf_reset_protocol) inline
Definition at line 812 of file flow_graph.h.
References tbb::flow::interface10::internal::activate_graph(), begin(), cancelled, caught_exception, tbb::flow::interface10::internal::deactivate_graph(), end(), my_context, my_reset_task_list, prepare_task_arena(), tbb::task_group_context::reset(), tbb::flow::interface10::graph_node::reset_node(), and tbb::flow::interface10::internal::spawn_in_graph_arena().
{
     // reset context
     internal::deactivate_graph(*this);
     if(my_context) my_context->reset();
     cancelled = false;
     caught_exception = false;
     // reset all the nodes comprising the graph
     for(iterator ii = begin(); ii != end(); ++ii) {
         graph_node *my_p = &(*ii);
         my_p->reset_node(f);
     }
     // Reattach the arena. Might be useful to run the graph in a particular task_arena
     // while not limiting graph lifetime to a single task_arena::execute() call.
     prepare_task_arena( /*reinit=*/true );
     internal::activate_graph(*this);
     // now spawn the tasks necessary to start the graph
     for(task_list_type::iterator rti = my_reset_task_list.begin(); rti != my_reset_task_list.end(); ++rti) {
         internal::spawn_in_graph_arena(*this, *(*rti));
     }
     my_reset_task_list.clear();
 }
tbb::task* tbb::flow::interface10::graph::root_task () inline
Returns the root task of the graph.
Definition at line 357 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::source_node< Output >::create_put_task(), tbb::flow::interface10::limiter_node< T >::forward_task(), tbb::flow::interface10::limiter_node< T >::register_predecessor(), tbb::flow::interface10::limiter_node< T >::register_successor(), tbb::flow::interface10a::overwrite_node< T >::register_successor(), and tbb::flow::interface10::limiter_node< T >::try_put_task().
{
         return my_root_task;
     }
template<typename Receiver , typename Body > void tbb::flow::interface10::graph::run (Receiver & r, Body body) inline
Spawns a task that runs a body and puts its output to a specific receiver.
The task is spawned as a child of the graph. This is useful for running tasks that need to block a wait_for_all() on the graph. For example a one-off source.
Definition at line 306 of file _flow_graph_impl.h.
References tbb::flow::interface10::graph::run_and_put_task< Receiver, Body >::execute(), tbb::flow::interface10::internal::is_graph_active(), and tbb::interface9::internal::root_task.
{
         if (internal::is_graph_active(*this)) {
             task* rtask = new (task::allocate_additional_child_of(*root_task()))
                 run_and_put_task< Receiver, Body >(r, body);
             my_task_arena->execute(spawn_functor(*rtask));
         }
     }
template<typename Body > void tbb::flow::interface10::graph::run (Body body) inline
Spawns a task that runs a function object.
The task is spawned as a child of the graph. This is useful for running tasks that need to block a wait_for_all() on the graph. For example a one-off source.
Definition at line 318 of file _flow_graph_impl.h.
References tbb::flow::interface10::graph::run_task< Body >::execute(), tbb::flow::interface10::internal::is_graph_active(), and tbb::interface9::internal::root_task.
{
         if (internal::is_graph_active(*this)) {
             task* rtask = new (task::allocate_additional_child_of(*root_task())) run_task< Body >(body);
             my_task_arena->execute(spawn_functor(*rtask));
         }
     }
void tbb::flow::interface10::graph::wait_for_all () inline
Wait until graph is idle and decrement_wait_count calls equals increment_wait_count calls.
The waiting thread will go off and steal work while it is block in the wait_for_all.
Definition at line 327 of file _flow_graph_impl.h.
References tbb::task_group_context::concurrent_wait.
Referenced by ~graph().
{
         cancelled = false;
         caught_exception = false;
         if (my_root_task) {
 #if TBB_USE_EXCEPTIONS
             try {
 #endif
                 my_task_arena->execute(wait_functor(my_root_task));
                 cancelled = my_context->is_group_execution_cancelled();
 #if TBB_USE_EXCEPTIONS
             }
             catch (...) {
                 my_root_task->set_ref_count(1);
                 my_context->reset();
                 caught_exception = true;
                 cancelled = true;
                 throw;
             }
 #endif
             // TODO: the "if" condition below is just a work-around to support the concurrent wait
             // mode. The cancellation and exception mechanisms are still broken in this mode.
             // Consider using task group not to re-implement the same functionality.
             if (!(my_context->traits() & tbb::task_group_context::concurrent_wait)) {
                 my_context->reset();  // consistent with behavior in catch()
                 my_root_task->set_ref_count(1);
             }
         }
     }
Friends And Related Function Documentation
template<typename Input , typename Output , typename Policy , typename Allocator > friend class async_node friend
Definition at line 419 of file _flow_graph_impl.h.
template<typename C , typename N > friend class graph_iterator friend
Definition at line 363 of file _flow_graph_impl.h.
friend class graph_node friend
Definition at line 201 of file _flow_graph_impl.h.
void internal::activate_graph (graph & g) friend
void internal::add_task_to_graph_reset_list (graph & g, tbb::task * tp) friend
void internal::deactivate_graph (graph & g) friend
template<typename F > void internal::execute_in_graph_arena (graph & g, F & f) friend
bool internal::is_graph_active (graph & g) friend
void internal::spawn_in_graph_arena (graph & g, tbb::task & arena_task) friend
friend class tbb::interface7::internal::task_arena_base friend
Definition at line 422 of file _flow_graph_impl.h.
Member Data Documentation
bool tbb::flow::interface10::graph::cancelled private
Definition at line 394 of file _flow_graph_impl.h.
Referenced by reset().
bool tbb::flow::interface10::graph::caught_exception private
Definition at line 395 of file _flow_graph_impl.h.
Referenced by reset().
tbb::task_group_context* tbb::flow::interface10::graph::my_context private
Definition at line 392 of file _flow_graph_impl.h.
Referenced by reset(), and tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task().
bool tbb::flow::interface10::graph::my_is_active private
Definition at line 396 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::activate_graph(), tbb::flow::interface10::internal::deactivate_graph(), tbb::flow::interface10::internal::is_graph_active(), and tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task().
graph_node* tbb::flow::interface10::graph::my_nodes private
Definition at line 399 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::function_output< Output >::register_successor().
graph_node * tbb::flow::interface10::graph::my_nodes_last private
Definition at line 399 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::function_output< Output >::register_successor().
internal::graph_task_priority_queue_t tbb::flow::interface10::graph::my_priority_queue private
Definition at line 408 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::spawn_in_graph_arena().
task_list_type tbb::flow::interface10::graph::my_reset_task_list private
Definition at line 397 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::add_task_to_graph_reset_list(), and reset().
tbb::task* tbb::flow::interface10::graph::my_root_task private
Definition at line 391 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::key_matching_port< TraitsType >::key_matching_port(), tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task(), and ~graph().
tbb::task_arena* tbb::flow::interface10::graph::my_task_arena private
Definition at line 405 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::execute_in_graph_arena().
tbb::spin_mutex tbb::flow::interface10::graph::nodelist_mutex private
Definition at line 401 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::function_output< Output >::register_successor(), and tbb::flow::interface10::internal::key_matching_port< TraitsType >::set_join_node_pointer().
bool tbb::flow::interface10::graph::own_context private
Definition at line 393 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task().
The documentation for this class was generated from the following files:
_flow_graph_impl.h
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.