Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::memory_pool_allocator< T, P > Class Template Reference
tbb::interface6::memory_pool_allocator< T, P > Class Template Reference
Memory Allocation
Meets "allocator" requirements of ISO C++ Standard, Section 20.1.5.
#include <memory_pool.h>
Classes
struct rebind
Public Types
typedef tbb::internal::allocator_type< T >::value_type value_type
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef size_t size_type
typedef ptrdiff_t difference_type
Public Member Functions
memory_pool_allocator (pool_type &pool) throw ()
memory_pool_allocator (const memory_pool_allocator &src) throw ()
template<typename U >
memory_pool_allocator (const memory_pool_allocator< U, P > &src) throw ()
pointer address (reference x) const
const_pointer address (const_reference x) const
pointer allocate (size_type n, const void *=0)
Allocate space for n objects.
void deallocate (pointer p, size_type)
Free previously allocated block of memory.
size_type max_size () const throw ()
Largest value for which method allocate might succeed.
void construct (pointer p, value_type &&value)
Copy-construct value at location pointed to by p.
void construct (pointer p, const value_type &value)
void destroy (pointer p)
Destroy value at location pointed to by p.
Protected Types
typedef P pool_type
Protected Attributes
pool_type * my_pool
Friends
template<typename U , typename R >
class memory_pool_allocator
template<typename V , typename U , typename R >
bool operator== (const memory_pool_allocator< V, R > &a, const memory_pool_allocator< U, R > &b)
template<typename V , typename U , typename R >
bool operator!= (const memory_pool_allocator< V, R > &a, const memory_pool_allocator< U, R > &b)
Detailed Description
template<typename T, typename P = internal::pool_base>
class tbb::interface6::memory_pool_allocator< T, P >
Meets "allocator" requirements of ISO C++ Standard, Section 20.1.5.
Definition at line 88 of file memory_pool.h.
Member Typedef Documentation
template<typename T, typename P = internal::pool_base> typedef const value_type* tbb::interface6::memory_pool_allocator< T, P >::const_pointer
Definition at line 101 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> typedef const value_type& tbb::interface6::memory_pool_allocator< T, P >::const_reference
Definition at line 103 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> typedef ptrdiff_t tbb::interface6::memory_pool_allocator< T, P >::difference_type
Definition at line 105 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> typedef value_type* tbb::interface6::memory_pool_allocator< T, P >::pointer
Definition at line 100 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> typedef P tbb::interface6::memory_pool_allocator< T, P >::pool_type protected
Definition at line 90 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> typedef value_type& tbb::interface6::memory_pool_allocator< T, P >::reference
Definition at line 102 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> typedef size_t tbb::interface6::memory_pool_allocator< T, P >::size_type
Definition at line 104 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> typedef tbb::internal::allocator_type<T>::value_type tbb::interface6::memory_pool_allocator< T, P >::value_type
Definition at line 99 of file memory_pool.h.
Constructor & Destructor Documentation
template<typename T, typename P = internal::pool_base> tbb::interface6::memory_pool_allocator< T, P >::memory_pool_allocator (pool_type & pool) throw () inline explicit
Definition at line 110 of file memory_pool.h.
 : my_pool(&pool) {}
template<typename T, typename P = internal::pool_base> tbb::interface6::memory_pool_allocator< T, P >::memory_pool_allocator (const memory_pool_allocator< T, P > & src) throw () inline
Definition at line 111 of file memory_pool.h.
 : my_pool(src.my_pool) {}
template<typename T, typename P = internal::pool_base> template<typename U > tbb::interface6::memory_pool_allocator< T, P >::memory_pool_allocator (const memory_pool_allocator< U, P > & src) throw () inline
Definition at line 113 of file memory_pool.h.
 : my_pool(src.my_pool) {}
Member Function Documentation
template<typename T, typename P = internal::pool_base> pointer tbb::interface6::memory_pool_allocator< T, P >::address (reference x) const inline
Definition at line 115 of file memory_pool.h.
 { return &x; }
template<typename T, typename P = internal::pool_base> const_pointer tbb::interface6::memory_pool_allocator< T, P >::address (const_reference x) const inline
Definition at line 116 of file memory_pool.h.
 { return &x; }
template<typename T, typename P = internal::pool_base> pointer tbb::interface6::memory_pool_allocator< T, P >::allocate (size_type n, const void * = 0) inline
Allocate space for n objects.
Definition at line 119 of file memory_pool.h.
References p, and tbb::internal::throw_exception().
{
         pointer p = static_cast<pointer>( my_pool->malloc( n*sizeof(value_type) ) );
         if (!p)
             tbb::internal::throw_exception(std::bad_alloc());
         return p;
     }
template<typename T, typename P = internal::pool_base> void tbb::interface6::memory_pool_allocator< T, P >::construct (pointer p, value_type && value) inline
Copy-construct value at location pointed to by p.
Definition at line 141 of file memory_pool.h.
References tbb::move(), and value.
 {::new((void*)(p)) value_type(std::move(value));}
template<typename T, typename P = internal::pool_base> void tbb::interface6::memory_pool_allocator< T, P >::construct (pointer p, const value_type & value) inline
Definition at line 143 of file memory_pool.h.
 { ::new((void*)(p)) value_type(value); }
template<typename T, typename P = internal::pool_base> void tbb::interface6::memory_pool_allocator< T, P >::deallocate (pointer p, size_type) inline
Free previously allocated block of memory.
Definition at line 126 of file memory_pool.h.
{
         my_pool->free(p);
     }
template<typename T, typename P = internal::pool_base> void tbb::interface6::memory_pool_allocator< T, P >::destroy (pointer p) inline
Destroy value at location pointed to by p.
Definition at line 147 of file memory_pool.h.
 { p->~value_type(); }
template<typename T, typename P = internal::pool_base> size_type tbb::interface6::memory_pool_allocator< T, P >::max_size () const throw () inline
Largest value for which method allocate might succeed.
Definition at line 130 of file memory_pool.h.
References tbb::internal::max(), and p.
{
         size_type max = static_cast<size_type>(-1) / sizeof (value_type);
         return (max > 0 ? max : 1);
     }
Friends And Related Function Documentation
template<typename T, typename P = internal::pool_base> template<typename U , typename R > friend class memory_pool_allocator friend
Definition at line 93 of file memory_pool.h.
template<typename T, typename P = internal::pool_base> template<typename V , typename U , typename R > bool operator!= (const memory_pool_allocator< V, R > & a, const memory_pool_allocator< U, R > & b) friend
template<typename T, typename P = internal::pool_base> template<typename V , typename U , typename R > bool operator== (const memory_pool_allocator< V, R > & a, const memory_pool_allocator< U, R > & b) friend
Member Data Documentation
template<typename T, typename P = internal::pool_base> pool_type* tbb::interface6::memory_pool_allocator< T, P >::my_pool protected
Definition at line 91 of file memory_pool.h.
Referenced by tbb::interface6::operator!=(), and tbb::interface6::operator==().
The documentation for this class was generated from the following file:
memory_pool.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.