Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::micro_queue Struct Reference
tbb::internal::micro_queue Struct Reference
A queue using simple locking.
Public Types
typedef concurrent_queue_base::page page
Public Member Functions
void push (const void *item, ticket k, concurrent_queue_base &base, concurrent_queue_base::copy_specifics op_type)
void abort_push (ticket k, concurrent_queue_base &base)
bool pop (void *dst, ticket k, concurrent_queue_base &base)
micro_queue & assign (const micro_queue &src, concurrent_queue_base &base, concurrent_queue_base::copy_specifics op_type)
page * make_copy (concurrent_queue_base &base, const page *src_page, size_t begin_in_page, size_t end_in_page, ticket &g_index, concurrent_queue_base::copy_specifics op_type)
void make_invalid (ticket k)
Public Attributes
atomic< page * > head_page
atomic< ticket > head_counter
atomic< page * > tail_page
atomic< ticket > tail_counter
spin_mutex page_mutex
Friends
class micro_queue_pop_finalizer
Detailed Description
A queue using simple locking.
For efficiency, this class has no constructor. The caller is expected to zero-initialize it.
Definition at line 51 of file concurrent_queue.cpp.
Member Typedef Documentation
typedef concurrent_queue_base::page tbb::internal::micro_queue::page
Definition at line 52 of file concurrent_queue.cpp.
Member Function Documentation
void tbb::internal::micro_queue::abort_push (ticket k, concurrent_queue_base & base)
Definition at line 230 of file concurrent_queue.cpp.
References tbb::internal::concurrent_queue_base_v3::copy, and push().
Referenced by tbb::internal::concurrent_queue_base_v3::internal_insert_item().
{
     push(NULL, k, base, concurrent_queue_base::copy);
 }
micro_queue & tbb::internal::micro_queue::assign (const micro_queue & src, concurrent_queue_base & base, concurrent_queue_base::copy_specifics op_type)
Definition at line 257 of file concurrent_queue.cpp.
References __TBB_ASSERT, __TBB_CATCH, __TBB_RETHROW, __TBB_TRY, head_counter, head_page, tbb::internal::concurrent_queue_base_v3::items_per_page, make_copy(), make_invalid(), tbb::internal::modulo_power_of_two(), tbb::internal::concurrent_queue_rep::n_queue, tbb::internal::concurrent_queue_base_v3::page::next, tail_counter, and tail_page.
 {
     head_counter = src.head_counter;
     tail_counter = src.tail_counter;
     const page* srcp = src.head_page;
     if( srcp ) {
         ticket g_index = head_counter;
         __TBB_TRY {
             size_t n_items  = (tail_counter-head_counter)/concurrent_queue_rep::n_queue;
             size_t index = modulo_power_of_two( head_counter/concurrent_queue_rep::n_queue, base.items_per_page );
             size_t end_in_first_page = (index+n_items<base.items_per_page)?(index+n_items):base.items_per_page;
             head_page = make_copy( base, srcp, index, end_in_first_page, g_index, op_type );
             page* cur_page = head_page;
             if( srcp != src.tail_page ) {
                 for( srcp = srcp->next; srcp!=src.tail_page; srcp=srcp->next ) {
                     cur_page->next = make_copy( base, srcp, 0, base.items_per_page, g_index, op_type );
                     cur_page = cur_page->next;
                 }
                 __TBB_ASSERT( srcp==src.tail_page, NULL );
                 size_t last_index = modulo_power_of_two( tail_counter/concurrent_queue_rep::n_queue, base.items_per_page );
                 if( last_index==0 ) last_index = base.items_per_page;
                 cur_page->next = make_copy( base, srcp, 0, last_index, g_index, op_type );
                 cur_page = cur_page->next;
             }
             tail_page = cur_page;
         } __TBB_CATCH(...) {
             make_invalid( g_index );
             __TBB_RETHROW();
         }
     } else {
         head_page = tail_page = NULL;
     }
     return *this;
 }
concurrent_queue_base::page * tbb::internal::micro_queue::make_copy (concurrent_queue_base & base, const page * src_page, size_t begin_in_page, size_t end_in_page, ticket & g_index, concurrent_queue_base::copy_specifics op_type)
Definition at line 299 of file concurrent_queue.cpp.
References __TBB_ASSERT, tbb::internal::concurrent_queue_base_v3::allocate_page(), tbb::internal::concurrent_queue_base_v3::copy, tbb::internal::concurrent_queue_base_v3::copy_page_item(), tbb::internal::concurrent_queue_base_v3::page::mask, tbb::internal::concurrent_queue_base_v3::move, and tbb::internal::concurrent_queue_base_v3::page::next.
Referenced by assign().
 {
     page* new_page = base.allocate_page();
     new_page->next = NULL;
     new_page->mask = src_page->mask;
     for( ; begin_in_page!=end_in_page; ++begin_in_page, ++g_index )
         if( new_page->mask & uintptr_t(1)<<begin_in_page ) {
             if( concurrent_queue_base::copy == op_type ) {
                 base.copy_page_item( *new_page, begin_in_page, *src_page, begin_in_page );
             } else {
                 __TBB_ASSERT( concurrent_queue_base::move == op_type, NULL );
                 static_cast<concurrent_queue_base_v8&>(base).move_page_item( *new_page, begin_in_page, *src_page, begin_in_page );
             }
         }
     return new_page;
 }
void tbb::internal::micro_queue::make_invalid (ticket k)
Definition at line 318 of file concurrent_queue.cpp.
References head_page, lock, tbb::internal::concurrent_queue_rep::n_queue, page_mutex, tbb::internal::static_invalid_page, and tail_page.
Referenced by assign(), and push().
 {
     static concurrent_queue_base::page dummy = {static_cast<page*>((void*)1), 0};
     // mark it so that no more pushes are allowed.
     static_invalid_page = &dummy;
     {
         spin_mutex::scoped_lock lock( page_mutex );
         tail_counter = k+concurrent_queue_rep::n_queue+1;
         if( page* q = tail_page )
             q->next = static_cast<page*>(static_invalid_page);
         else
             head_page = static_cast<page*>(static_invalid_page);
         tail_page = static_cast<page*>(static_invalid_page);
     }
 }
bool tbb::internal::micro_queue::pop (void * dst, ticket k, concurrent_queue_base & base)
Definition at line 234 of file concurrent_queue.cpp.
References __TBB_ASSERT, tbb::internal::concurrent_queue_base_v3::assign_and_destroy_item(), head_counter, head_page, tbb::internal::concurrent_queue_base_v3::items_per_page, ITT_NOTIFY, tbb::internal::concurrent_queue_base_v3::page::mask, tbb::internal::modulo_power_of_two(), tbb::internal::concurrent_queue_base_v3::my_rep, tbb::internal::concurrent_queue_rep::n_invalid_entries, tbb::internal::concurrent_queue_rep::n_queue, p, tbb::internal::spin_wait_until_eq(), tbb::internal::spin_wait_while_eq(), and sync_releasing.
Referenced by tbb::internal::concurrent_queue_base_v3::internal_pop(), and tbb::internal::concurrent_queue_base_v3::internal_pop_if_present().
{
     k &= -concurrent_queue_rep::n_queue;
     spin_wait_until_eq( head_counter, k );
     spin_wait_while_eq( tail_counter, k );
     page *p = head_page;
     __TBB_ASSERT( p, NULL );
     size_t index = modulo_power_of_two( k/concurrent_queue_rep::n_queue, base.items_per_page );
     bool success = false;
     {
         micro_queue_pop_finalizer finalizer( *this, base, k+concurrent_queue_rep::n_queue, index==base.items_per_page-1 ? p : NULL );
         if( p->mask & uintptr_t(1)<<index ) {
             success = true;
             ITT_NOTIFY( sync_acquired, dst );
             ITT_NOTIFY( sync_acquired, head_page );
             base.assign_and_destroy_item( dst, *p, index );
             ITT_NOTIFY( sync_releasing, head_page );
         } else {
             --base.my_rep->n_invalid_entries;
         }
     }
     return success;
 }
void tbb::internal::micro_queue::push (const void * item, ticket k, concurrent_queue_base & base, concurrent_queue_base::copy_specifics op_type)
Definition at line 165 of file concurrent_queue.cpp.
References __TBB_ASSERT, __TBB_CATCH, __TBB_RETHROW, __TBB_TRY, tbb::internal::concurrent_queue_base_v3::allocate_page(), tbb::internal::concurrent_queue_base_v3::copy, tbb::internal::concurrent_queue_base_v3::copy_item(), tbb::internal::eid_bad_last_alloc, head_page, tbb::internal::concurrent_queue_base_v3::items_per_page, ITT_NOTIFY, lock, make_invalid(), tbb::internal::concurrent_queue_base_v3::page::mask, tbb::internal::modulo_power_of_two(), tbb::internal::concurrent_queue_base_v3::move, tbb::internal::concurrent_queue_base_v3::my_rep, tbb::internal::concurrent_queue_rep::n_invalid_entries, tbb::internal::concurrent_queue_rep::n_queue, tbb::internal::concurrent_queue_base_v3::page::next, p, page_mutex, tbb::internal::atomic_backoff::pause(), sync_releasing, tail, tail_counter, tail_page, and tbb::internal::throw_exception().
Referenced by abort_push(), tbb::internal::concurrent_queue_base_v3::internal_insert_if_not_full(), and tbb::internal::concurrent_queue_base_v3::internal_insert_item().
{
     k &= -concurrent_queue_rep::n_queue;
     page* p = NULL;
     // find index on page where we would put the data
     size_t index = modulo_power_of_two( k/concurrent_queue_rep::n_queue, base.items_per_page );
     if( !index ) {  // make a new page
         __TBB_TRY {
             p = base.allocate_page();
         } __TBB_CATCH(...) {
             ++base.my_rep->n_invalid_entries;
             make_invalid( k );
             __TBB_RETHROW();
         }
         p->mask = 0;
         p->next = NULL;
     }
     // wait for my turn
     if( tail_counter!=k ) // The developer insisted on keeping first check out of the backoff loop
         for( atomic_backoff b(true);;b.pause() ) {
             ticket tail = tail_counter;
             if( tail==k ) break;
             else if( tail&0x1 ) {
                 // no memory. throws an exception; assumes concurrent_queue_rep::n_queue>1
                 ++base.my_rep->n_invalid_entries;
                 throw_exception( eid_bad_last_alloc );
             }
         }
     if( p ) { // page is newly allocated; insert in micro_queue
         spin_mutex::scoped_lock lock( page_mutex );
         if( page* q = tail_page )
             q->next = p;
         else
             head_page = p;
         tail_page = p;
     }
     if (item) {
         p = tail_page;
         ITT_NOTIFY( sync_acquired, p );
         __TBB_TRY {
             if( concurrent_queue_base::copy == op_type ) {
                 base.copy_item( *p, index, item );
             } else {
                 __TBB_ASSERT( concurrent_queue_base::move == op_type, NULL );
                 static_cast<concurrent_queue_base_v8&>(base).move_item( *p, index, item );
             }
         }  __TBB_CATCH(...) {
             ++base.my_rep->n_invalid_entries;
             tail_counter += concurrent_queue_rep::n_queue;
             __TBB_RETHROW();
         }
         ITT_NOTIFY( sync_releasing, p );
         // If no exception was thrown, mark item as present.
         p->mask |= uintptr_t(1)<<index;
     }
     else // no item; this was called from abort_push
         ++base.my_rep->n_invalid_entries;
     tail_counter += concurrent_queue_rep::n_queue;
 }
Friends And Related Function Documentation
friend class micro_queue_pop_finalizer friend
Definition at line 54 of file concurrent_queue.cpp.
Member Data Documentation
atomic<ticket> tbb::internal::micro_queue::head_counter
Definition at line 57 of file concurrent_queue.cpp.
Referenced by assign(), pop(), and tbb::internal::micro_queue_pop_finalizer::~micro_queue_pop_finalizer().
atomic<page*> tbb::internal::micro_queue::head_page
Definition at line 56 of file concurrent_queue.cpp.
Referenced by assign(), tbb::internal::concurrent_queue_iterator_rep::concurrent_queue_iterator_rep(), make_invalid(), pop(), push(), and tbb::internal::micro_queue_pop_finalizer::~micro_queue_pop_finalizer().
spin_mutex tbb::internal::micro_queue::page_mutex
Definition at line 62 of file concurrent_queue.cpp.
Referenced by make_invalid(), push(), and tbb::internal::micro_queue_pop_finalizer::~micro_queue_pop_finalizer().
atomic<ticket> tbb::internal::micro_queue::tail_counter
Definition at line 60 of file concurrent_queue.cpp.
Referenced by assign(), and push().
atomic<page*> tbb::internal::micro_queue::tail_page
Definition at line 59 of file concurrent_queue.cpp.
Referenced by assign(), make_invalid(), push(), and tbb::internal::micro_queue_pop_finalizer::~micro_queue_pop_finalizer().
The documentation for this struct was generated from the following file:
concurrent_queue.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.