Intel(R) Threading Building Blocks Doxygen Documentation: internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple > Class Template Reference
internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple > Class Template Reference
#include <_flow_graph_join_impl.h>
Classes
class key_matching_FE_operation
Public Types
typedef OutputTuple output_type
typedef InputTuple input_type
typedef K key_type
typedef tbb::internal::strip< key_type >::type unref_key_type
typedef KHash key_hash_compare
typedef count_element< unref_key_type > count_element_type
typedef key_to_count_functor< unref_key_type > key_to_count_func
typedef internal::type_to_key_function_body< count_element_type, unref_key_type & > TtoK_function_body_type
typedef internal::type_to_key_function_body_leaf< count_element_type, unref_key_type &, key_to_count_func > TtoK_function_body_leaf_type
typedef hash_buffer< unref_key_type &, count_element_type, TtoK_function_body_type, key_hash_compare > key_to_count_buffer_type
typedef item_buffer< output_type > output_buffer_type
typedef join_node_base< key_matching< key_type, key_hash_compare >, InputTuple, OutputTuple > base_node_type
typedef matching_forwarding_base< key_type > forwarding_base_type
Public Types inherited from internal::matching_forwarding_base< KeyType >
typedef tbb::internal::strip< KeyType >::type current_key_type
Public Types inherited from hash_buffer< Key, ValueType, ValueToKey, HashCompare, Allocator >
typedef ValueType value_type
typedef buffer_element_type< value_type >::type element_type
typedef value_type * pointer_type
typedef element_type * list_array_type
typedef list_array_type * pointer_array_type
typedef Allocator::template rebind< list_array_type >::other pointer_array_allocator_type
typedef Allocator::template rebind< element_type >::other elements_array_allocator
typedef tbb::internal::strip< Key >::type Knoref
Public Types inherited from internal::item_buffer< T, A >
enum buffer_item_state { no_item =0, has_item =1, reserved_item =2 }
typedef T item_type
Public Member Functions
template<typename FunctionTuple >
join_node_FE (graph &g, FunctionTuple &TtoK_funcs)
join_node_FE (const join_node_FE &other)
void set_my_node (base_node_type *new_my_node)
void reset_port_count ()
task * increment_key_count (unref_key_type const &t, bool handle_task) __TBB_override
task * decrement_port_count (bool) __TBB_override
void increment_port_count () __TBB_override
input_type & input_ports ()
Public Member Functions inherited from internal::matching_forwarding_base< KeyType >
matching_forwarding_base (graph &g)
Public Member Functions inherited from internal::forwarding_base
forwarding_base (graph &g)
virtual ~forwarding_base ()
Public Member Functions inherited from hash_buffer< Key, ValueType, ValueToKey, HashCompare, Allocator >
hash_buffer ()
~hash_buffer ()
void reset ()
void set_key_func (ValueToKey *vtk)
ValueToKey * get_key_func ()
bool insert_with_key (const value_type &v)
bool find_ref_with_key (const Knoref &k, pointer_type &v)
bool find_with_key (const Knoref &k, value_type &v)
void delete_with_key (const Knoref &k)
Public Member Functions inherited from internal::item_buffer< T, A >
item_buffer ()
Constructor.
~item_buffer ()
void reset ()
Static Public Attributes
static const int N = tbb::flow::tuple_size<OutputTuple>::value
Static Public Attributes inherited from hash_buffer< Key, ValueType, ValueToKey, HashCompare, Allocator >
static const size_t INITIAL_SIZE = 8
Protected Member Functions
void reset (reset_flags f)
bool tuple_build_may_succeed ()
bool try_to_make_tuple (output_type &out)
void tuple_accepted ()
void tuple_rejected ()
Protected Member Functions inherited from internal::item_buffer< T, A >
bool buffer_empty () const
buffer_item_type & item (size_type i)
const buffer_item_type & item (size_type i) const
bool my_item_valid (size_type i) const
bool my_item_reserved (size_type i) const
const item_type & get_my_item (size_t i) const
void set_my_item (size_t i, const item_type &o)
void fetch_item (size_t i, item_type &o)
void move_item (size_t to, size_t from)
bool place_item (size_t here, const item_type &me)
void swap_items (size_t i, size_t j)
void destroy_item (size_type i)
const item_type & front () const
const item_type & back () const
void reserve_item (size_type i)
void release_item (size_type i)
void destroy_front ()
void destroy_back ()
size_type size (size_t new_tail=0)
size_type capacity ()
bool buffer_full ()
void grow_my_array (size_t minimum_size)
Grows the internal array.
bool push_back (item_type &v)
bool pop_back (item_type &v)
bool pop_front (item_type &v)
void clean_up_buffer (bool reset_pointers)
Protected Attributes
input_type my_inputs
base_node_type * my_node
Protected Attributes inherited from internal::item_buffer< T, A >
buffer_item_type * my_array
size_type my_array_size
size_type my_head
size_type my_tail
Private Types
enum op_type { res_count, inc_count, may_succeed, try_make }
enum op_stat { WAIT =0, SUCCEEDED, FAILED }
typedef join_node_FE< key_matching< key_type, key_hash_compare >, InputTuple, OutputTuple > class_type
typedef internal::aggregating_functor< class_type, key_matching_FE_operation > handler_type
Private Member Functions
task * fill_output_buffer (unref_key_type &t, bool should_enqueue, bool handle_task)
void handle_operations (key_matching_FE_operation *op_list)
Private Attributes
aggregator< handler_type, key_matching_FE_operation > my_aggregator
Friends
class internal::aggregating_functor< class_type, key_matching_FE_operation >
Additional Inherited Members
Public Attributes inherited from internal::matching_forwarding_base< KeyType >
current_key_type current_key
Public Attributes inherited from internal::forwarding_base
graph & graph_ref
Protected Types inherited from internal::item_buffer< T, A >
typedef size_t size_type
typedef aligned_pair< item_type, buffer_item_state >::type buffer_item_type
typedef A::template rebind< buffer_item_type >::other allocator_type
Static Protected Attributes inherited from internal::item_buffer< T, A >
static const size_type initial_buffer_size = 4
Detailed Description
template<typename InputTuple, typename OutputTuple, typename K, typename KHash>
class internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >
Definition at line 1033 of file _flow_graph_join_impl.h.
Member Typedef Documentation
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef join_node_base<key_matching<key_type,key_hash_compare>, InputTuple, OutputTuple> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::base_node_type
Definition at line 1062 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef join_node_FE<key_matching<key_type,key_hash_compare>, InputTuple, OutputTuple> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::class_type private
Definition at line 1071 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef count_element<unref_key_type> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::count_element_type
Definition at line 1052 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef matching_forwarding_base<key_type> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::forwarding_base_type
Definition at line 1063 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef internal::aggregating_functor<class_type, key_matching_FE_operation> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::handler_type private
Definition at line 1089 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef InputTuple internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::input_type
Definition at line 1047 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef KHash internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::key_hash_compare
Definition at line 1050 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef hash_buffer< unref_key_type&, count_element_type, TtoK_function_body_type, key_hash_compare > internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::key_to_count_buffer_type
Definition at line 1060 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef key_to_count_functor<unref_key_type> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::key_to_count_func
Definition at line 1054 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef K internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::key_type
Definition at line 1048 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef item_buffer<output_type> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::output_buffer_type
Definition at line 1061 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef OutputTuple internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::output_type
Definition at line 1046 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef internal::type_to_key_function_body_leaf<count_element_type, unref_key_type&, key_to_count_func> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::TtoK_function_body_leaf_type
Definition at line 1056 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef internal::type_to_key_function_body< count_element_type, unref_key_type&> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::TtoK_function_body_type
Definition at line 1055 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > typedef tbb::internal::strip<key_type>::type internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::unref_key_type
Definition at line 1049 of file _flow_graph_join_impl.h.
Member Enumeration Documentation
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > enum internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::op_stat private
Enumerator
WAIT
SUCCEEDED
FAILED
Definition at line 1070 of file _flow_graph_join_impl.h.
 {WAIT=0, SUCCEEDED, FAILED};
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > enum internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::op_type private
Enumerator
res_count
inc_count
may_succeed
try_make
Definition at line 1069 of file _flow_graph_join_impl.h.
 { res_count, inc_count, may_succeed, try_make };
Constructor & Destructor Documentation
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > template<typename FunctionTuple > internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::join_node_FE (graph & g, FunctionTuple & TtoK_funcs) inline
Definition at line 1174 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::set_join_node_pointer(), and internal::join_helper< N >::set_key_functors().
                                                           : forwarding_base_type(g), my_node(NULL) {
             join_helper<N>::set_join_node_pointer(my_inputs, this);
             join_helper<N>::set_key_functors(my_inputs, TtoK_funcs);
             my_aggregator.initialize_handler(handler_type(this));
                     TtoK_function_body_type *cfb = new TtoK_function_body_leaf_type(key_to_count_func());
             this->set_key_func(cfb);
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::join_node_FE (const join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple > & other) inline
Definition at line 1182 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::copy_key_functors(), and internal::join_helper< N >::set_join_node_pointer().
                                                 : forwarding_base_type((other.forwarding_base_type::graph_ref)), key_to_count_buffer_type(),
         output_buffer_type() {
             my_node = NULL;
             join_helper<N>::set_join_node_pointer(my_inputs, this);
             join_helper<N>::copy_key_functors(my_inputs, const_cast<input_type &>(other.my_inputs));
             my_aggregator.initialize_handler(handler_type(this));
             TtoK_function_body_type *cfb = new TtoK_function_body_leaf_type(key_to_count_func());
             this->set_key_func(cfb);
         }
Member Function Documentation
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > task* internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::decrement_port_count (bool) inline virtual
Implements internal::forwarding_base.
Definition at line 1209 of file _flow_graph_join_impl.h.
References __TBB_ASSERT.
 { __TBB_ASSERT(false, NULL); return NULL; }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > task* internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::fill_output_buffer (unref_key_type & t, bool should_enqueue, bool handle_task) inline private
Definition at line 1096 of file _flow_graph_join_impl.h.
References __TBB_ASSERT, internal::forwarding_base::graph_ref, tbb::flow::interface10::internal::is_graph_active(), internal::join_helper< N >::reset_ports(), tbb::flow::interface10::internal::spawn_in_graph_arena(), and task.
{
             output_type l_out;
             task *rtask = NULL;
             bool do_fwd = should_enqueue && this->buffer_empty() && internal::is_graph_active(this->graph_ref);
             this->current_key = t;
             this->delete_with_key(this->current_key);   // remove the key
             if(join_helper<N>::get_items(my_inputs, l_out)) {  //  <== call back
                 this->push_back(l_out);
                 if(do_fwd) {  // we enqueue if receiving an item from predecessor, not if successor asks for item
                     rtask = new ( task::allocate_additional_child_of( *(this->graph_ref.root_task()) ) )
                         forward_task_bypass<base_node_type>(*my_node);
                     if(handle_task) {
                         internal::spawn_in_graph_arena(this->graph_ref, *rtask);
                         rtask = NULL;
                     }
                     do_fwd = false;
                 }
                 // retire the input values
                 join_helper<N>::reset_ports(my_inputs);  //  <== call back
             }
             else {
                 __TBB_ASSERT(false, "should have had something to push");
             }
             return rtask;
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > void internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::handle_operations (key_matching_FE_operation * op_list) inline private
Definition at line 1122 of file _flow_graph_join_impl.h.
References __TBB_ASSERT, tbb::internal::__TBB_store_with_release(), internal::count_element< K >::my_key, internal::count_element< K >::my_value, p, SUCCEEDED, and task.
{
             key_matching_FE_operation *current;
             while(op_list) {
                 current = op_list;
                 op_list = op_list->next;
                 switch(current->type) {
                 case res_count:  // called from BE
                     {
                         this->destroy_front();
                         __TBB_store_with_release(current->status, SUCCEEDED);
                     }
                     break;
                 case inc_count: {  // called from input ports
                         count_element_type *p = 0;
                         unref_key_type &t = current->my_val;
                         bool do_enqueue = current->enqueue_task;
                         if(!(this->find_ref_with_key(t,p))) {
                             count_element_type ev;
                             ev.my_key = t;
                             ev.my_value = 0;
                             this->insert_with_key(ev);
                             if(!(this->find_ref_with_key(t,p))) {
                                 __TBB_ASSERT(false, "should find key after inserting it");
                             }
                         }
                         if(++(p->my_value) == size_t(N)) {
                             task *rtask = fill_output_buffer(t, true, do_enqueue);
                             __TBB_ASSERT(!rtask || !do_enqueue, "task should not be returned");
                             current->bypass_t = rtask;
                         }
                     }
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case may_succeed:  // called from BE
                     __TBB_store_with_release(current->status, this->buffer_empty() ? FAILED : SUCCEEDED);
                     break;
                 case try_make:  // called from BE
                     if(this->buffer_empty()) {
                         __TBB_store_with_release(current->status, FAILED);
                     }
                     else {
                         *(current->my_output) = this->front();
                         __TBB_store_with_release(current->status, SUCCEEDED);
                     }
                     break;
                 }
             }
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > task* internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::increment_key_count (unref_key_type const & t, bool handle_task) inline virtual
Implements internal::matching_forwarding_base< KeyType >.
Definition at line 1203 of file _flow_graph_join_impl.h.
                                                                                              {  // called from input_ports
             key_matching_FE_operation op_data(t, handle_task, inc_count);
             my_aggregator.execute(&op_data);
             return op_data.bypass_t;
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > void internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::increment_port_count () inline virtual
Implements internal::forwarding_base.
Definition at line 1211 of file _flow_graph_join_impl.h.
References __TBB_ASSERT.
 { __TBB_ASSERT(false, NULL); }  // should never be called
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > input_type& internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::input_ports () inline
Definition at line 1213 of file _flow_graph_join_impl.h.
 { return my_inputs; }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > void internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::reset (reset_flags f) inline protected
Definition at line 1217 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::reset_inputs().
{
             // called outside of parallel contexts
             join_helper<N>::reset_inputs(my_inputs, f);
             key_to_count_buffer_type::reset();
             output_buffer_type::reset();
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > void internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::reset_port_count () inline
Definition at line 1195 of file _flow_graph_join_impl.h.
                                 {  // called from BE
             key_matching_FE_operation op_data(res_count);
             my_aggregator.execute(&op_data);
             return;
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > void internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::set_my_node (base_node_type * new_my_node) inline
Definition at line 1193 of file _flow_graph_join_impl.h.
 { my_node = new_my_node; }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > bool internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::try_to_make_tuple (output_type & out) inline protected
Definition at line 1244 of file _flow_graph_join_impl.h.
References SUCCEEDED.
{
             key_matching_FE_operation op_data(&out,try_make);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > void internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::tuple_accepted () inline protected
Definition at line 1250 of file _flow_graph_join_impl.h.
{
             reset_port_count();  // reset current_key after ports reset.
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > bool internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::tuple_build_may_succeed () inline protected
Definition at line 1236 of file _flow_graph_join_impl.h.
References SUCCEEDED.
                                        {  // called from back-end
             key_matching_FE_operation op_data(may_succeed);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > void internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::tuple_rejected () inline protected
Definition at line 1254 of file _flow_graph_join_impl.h.
{
             // nothing to do.
         }
Friends And Related Function Documentation
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > friend class internal::aggregating_functor< class_type, key_matching_FE_operation > friend
Definition at line 1090 of file _flow_graph_join_impl.h.
Member Data Documentation
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > aggregator<handler_type, key_matching_FE_operation> internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::my_aggregator private
Definition at line 1091 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > input_type internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::my_inputs protected
Definition at line 1258 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > base_node_type* internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::my_node protected
Definition at line 1259 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple , typename K , typename KHash > const int internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::N = tbb::flow::tuple_size<OutputTuple>::value static
Definition at line 1045 of file _flow_graph_join_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_join_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.