Intel(R) Threading Building Blocks Doxygen Documentation: tbb::strict_ppl::internal::micro_queue< T > Class Template Reference
tbb::strict_ppl::internal::micro_queue< T > Class Template Reference
A queue using simple locking.
#include <_concurrent_queue_impl.h>
Classes
class destroyer
Class used to ensure exception-safety of method "pop".
struct padded_page
Public Types
typedef void(* item_constructor_t) (T *location, const void *src)
Public Member Functions
void push (const void *item, ticket k, concurrent_queue_base_v3< T > &base, item_constructor_t construct_item)
bool pop (void *dst, ticket k, concurrent_queue_base_v3< T > &base)
micro_queue & assign (const micro_queue &src, concurrent_queue_base_v3< T > &base, item_constructor_t construct_item)
page * make_copy (concurrent_queue_base_v3< T > &base, const page *src_page, size_t begin_in_page, size_t end_in_page, ticket &g_index, item_constructor_t construct_item)
void invalidate_page_and_rethrow (ticket k)
Static Public Member Functions
static T & get_ref (page &p, size_t index)
Public Attributes
atomic< page * > head_page
atomic< ticket > head_counter
atomic< page * > tail_page
atomic< ticket > tail_counter
spin_mutex page_mutex
Private Types
typedef concurrent_queue_rep_base::page page
Private Member Functions
void copy_item (page &dst, size_t dindex, const void *src, item_constructor_t construct_item)
void copy_item (page &dst, size_t dindex, const page &src, size_t sindex, item_constructor_t construct_item)
void assign_and_destroy_item (void *dst, page &src, size_t index)
void spin_wait_until_my_turn (atomic< ticket > &counter, ticket k, concurrent_queue_rep_base &rb) const
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Friends
class micro_queue_pop_finalizer< T >
Detailed Description
template<typename T>
class tbb::strict_ppl::internal::micro_queue< T >
A queue using simple locking.
For efficiency, this class has no constructor. The caller is expected to zero-initialize it.
Definition at line 62 of file _concurrent_queue_impl.h.
Member Typedef Documentation
template<typename T> typedef void(* tbb::strict_ppl::internal::micro_queue< T >::item_constructor_t) (T *location, const void *src)
Definition at line 137 of file _concurrent_queue_impl.h.
template<typename T> typedef concurrent_queue_rep_base::page tbb::strict_ppl::internal::micro_queue< T >::page private
Definition at line 139 of file _concurrent_queue_impl.h.
Member Function Documentation
template<typename T> micro_queue< T > & tbb::strict_ppl::internal::micro_queue< T >::assign (const micro_queue< T > & src, concurrent_queue_base_v3< T > & base, item_constructor_t construct_item)
Definition at line 290 of file _concurrent_queue_impl.h.
References __TBB_ASSERT, __TBB_CATCH, __TBB_TRY, tbb::strict_ppl::internal::micro_queue< T >::head_counter, tbb::strict_ppl::internal::micro_queue< T >::head_page, tbb::strict_ppl::internal::is_valid_page(), tbb::internal::modulo_power_of_two(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::my_rep, tbb::strict_ppl::internal::concurrent_queue_rep_base::page::next, tbb::strict_ppl::internal::micro_queue< T >::tail_counter, and tbb::strict_ppl::internal::micro_queue< T >::tail_page.
 {
     head_counter = src.head_counter;
     tail_counter = src.tail_counter;
     const page* srcp = src.head_page;
     if( is_valid_page(srcp) ) {
         ticket g_index = head_counter;
         __TBB_TRY {
             size_t n_items  = (tail_counter-head_counter)/concurrent_queue_rep_base::n_queue;
             size_t index = modulo_power_of_two( head_counter/concurrent_queue_rep_base::n_queue, base.my_rep->items_per_page );
             size_t end_in_first_page = (index+n_items<base.my_rep->items_per_page)?(index+n_items):base.my_rep->items_per_page;
             head_page = make_copy( base, srcp, index, end_in_first_page, g_index, construct_item );
             page* cur_page = head_page;
             if( srcp != src.tail_page ) {
                 for( srcp = srcp->next; srcp!=src.tail_page; srcp=srcp->next ) {
                     cur_page->next = make_copy( base, srcp, 0, base.my_rep->items_per_page, g_index, construct_item );
                     cur_page = cur_page->next;
                 }
                 __TBB_ASSERT( srcp==src.tail_page, NULL );
                 size_t last_index = modulo_power_of_two( tail_counter/concurrent_queue_rep_base::n_queue, base.my_rep->items_per_page );
                 if( last_index==0 ) last_index = base.my_rep->items_per_page;
                 cur_page->next = make_copy( base, srcp, 0, last_index, g_index, construct_item );
                 cur_page = cur_page->next;
             }
             tail_page = cur_page;
         } __TBB_CATCH (...) {
             invalidate_page_and_rethrow( g_index );
         }
     } else {
         head_page = tail_page = NULL;
     }
     return *this;
 }
template<typename T> void tbb::strict_ppl::internal::micro_queue< T >::assign_and_destroy_item (void * dst, page & src, size_t index) inline private
Definition at line 160 of file _concurrent_queue_impl.h.
{
         T& from = get_ref(src,index);
         destroyer d(from);
         *static_cast<T*>(dst) = tbb::internal::move( from );
     }
template<typename T> void tbb::strict_ppl::internal::micro_queue< T >::copy_item (page & dst, size_t dindex, const void * src, item_constructor_t construct_item) inline private
Definition at line 149 of file _concurrent_queue_impl.h.
{
         construct_item( &get_ref(dst, dindex), src );
     }
template<typename T> void tbb::strict_ppl::internal::micro_queue< T >::copy_item (page & dst, size_t dindex, const page & src, size_t sindex, item_constructor_t construct_item) inline private
Definition at line 153 of file _concurrent_queue_impl.h.
     {
         T& src_item = get_ref( const_cast<page&>(src), sindex );
         construct_item( &get_ref(dst, dindex), static_cast<const void*>(&src_item) );
     }
template<typename T> static T& tbb::strict_ppl::internal::micro_queue< T >::get_ref (page & p, size_t index) inline static
Definition at line 180 of file _concurrent_queue_impl.h.
{
         return (&static_cast<padded_page*>(static_cast<void*>(&p))->last)[index];
     }
template<typename T > void tbb::strict_ppl::internal::micro_queue< T >::invalidate_page_and_rethrow (ticket k)
Definition at line 331 of file _concurrent_queue_impl.h.
References __TBB_RETHROW, tbb::strict_ppl::internal::is_valid_page(), tbb::internal::itt_store_word_with_release(), lock, and tbb::strict_ppl::internal::concurrent_queue_rep_base::page::next.
{
     // Append an invalid page at address 1 so that no more pushes are allowed.
     page* invalid_page = (page*)uintptr_t(1);
     {
         spin_mutex::scoped_lock lock( page_mutex );
         itt_store_word_with_release(tail_counter, k+concurrent_queue_rep_base::n_queue+1);
         page* q = tail_page;
         if( is_valid_page(q) )
             q->next = invalid_page;
         else
             head_page = invalid_page;
         tail_page = invalid_page;
     }
     __TBB_RETHROW();
 }
template<typename T> concurrent_queue_rep_base::page * tbb::strict_ppl::internal::micro_queue< T >::make_copy (concurrent_queue_base_v3< T > & base, const page * src_page, size_t begin_in_page, size_t end_in_page, ticket & g_index, item_constructor_t construct_item)
Definition at line 348 of file _concurrent_queue_impl.h.
References tbb::strict_ppl::internal::concurrent_queue_page_allocator::allocate_page(), tbb::strict_ppl::internal::concurrent_queue_rep_base::page::mask, and tbb::strict_ppl::internal::concurrent_queue_rep_base::page::next.
 {
     concurrent_queue_page_allocator& pa = base;
     page* new_page = pa.allocate_page();
     new_page->next = NULL;
     new_page->mask = src_page->mask;
     for( ; begin_in_page!=end_in_page; ++begin_in_page, ++g_index )
         if( new_page->mask & uintptr_t(1)<<begin_in_page )
             copy_item( *new_page, begin_in_page, *src_page, begin_in_page, construct_item );
     return new_page;
 }
template<typename T> bool tbb::strict_ppl::internal::micro_queue< T >::pop (void * dst, ticket k, concurrent_queue_base_v3< T > & base)
Definition at line 267 of file _concurrent_queue_impl.h.
References __TBB_ASSERT, tbb::internal::acquired, tbb::internal::call_itt_notify(), tbb::strict_ppl::internal::concurrent_queue_rep_base::page::mask, tbb::internal::modulo_power_of_two(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::my_rep, p, tbb::internal::spin_wait_until_eq(), and tbb::internal::spin_wait_while_eq().
{
     k &= -concurrent_queue_rep_base::n_queue;
     if( head_counter!=k ) spin_wait_until_eq( head_counter, k );
     call_itt_notify(acquired, &head_counter);
     if( tail_counter==k ) spin_wait_while_eq( tail_counter, k );
     call_itt_notify(acquired, &tail_counter);
     page *p = head_page;
     __TBB_ASSERT( p, NULL );
     size_t index = modulo_power_of_two( k/concurrent_queue_rep_base::n_queue, base.my_rep->items_per_page );
     bool success = false;
     {
         micro_queue_pop_finalizer<T> finalizer( *this, base, k+concurrent_queue_rep_base::n_queue, index==base.my_rep->items_per_page-1 ? p : NULL );
         if( p->mask & uintptr_t(1)<<index ) {
             success = true;
             assign_and_destroy_item( dst, *p, index );
         } else {
             --base.my_rep->n_invalid_entries;
         }
     }
     return success;
 }
template<typename T> void tbb::strict_ppl::internal::micro_queue< T >::push (const void * item, ticket k, concurrent_queue_base_v3< T > & base, item_constructor_t construct_item)
Definition at line 219 of file _concurrent_queue_impl.h.
References __TBB_CATCH, __TBB_RETHROW, __TBB_TRY, tbb::internal::acquired, tbb::strict_ppl::internal::concurrent_queue_page_allocator::allocate_page(), tbb::internal::call_itt_notify(), tbb::strict_ppl::internal::is_valid_page(), tbb::internal::itt_hide_store_word(), lock, tbb::strict_ppl::internal::concurrent_queue_rep_base::page::mask, tbb::internal::modulo_power_of_two(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::my_rep, tbb::strict_ppl::internal::concurrent_queue_rep_base::page::next, p, and tbb::internal::releasing.
 {
     k &= -concurrent_queue_rep_base::n_queue;
     page* p = NULL;
     size_t index = modulo_power_of_two( k/concurrent_queue_rep_base::n_queue, base.my_rep->items_per_page);
     if( !index ) {
         __TBB_TRY {
             concurrent_queue_page_allocator& pa = base;
             p = pa.allocate_page();
         } __TBB_CATCH (...) {
             ++base.my_rep->n_invalid_entries;
             invalidate_page_and_rethrow( k );
         }
         p->mask = 0;
         p->next = NULL;
     }
     if( tail_counter != k ) spin_wait_until_my_turn( tail_counter, k, *base.my_rep );
     call_itt_notify(acquired, &tail_counter);
     if( p ) {
         spin_mutex::scoped_lock lock( page_mutex );
         page* q = tail_page;
         if( is_valid_page(q) )
             q->next = p;
         else
             head_page = p;
         tail_page = p;
     } else {
         p = tail_page;
     }
     __TBB_TRY {
         copy_item( *p, index, item, construct_item );
         // If no exception was thrown, mark item as present.
         itt_hide_store_word(p->mask,  p->mask | uintptr_t(1)<<index);
         call_itt_notify(releasing, &tail_counter);
         tail_counter += concurrent_queue_rep_base::n_queue;
     } __TBB_CATCH (...) {
         ++base.my_rep->n_invalid_entries;
         call_itt_notify(releasing, &tail_counter);
         tail_counter += concurrent_queue_rep_base::n_queue;
         __TBB_RETHROW();
     }
 }
template<typename T > void tbb::strict_ppl::internal::micro_queue< T >::spin_wait_until_my_turn (atomic< ticket > & counter, ticket k, concurrent_queue_rep_base & rb) const private
Definition at line 207 of file _concurrent_queue_impl.h.
References tbb::internal::eid_bad_last_alloc, tbb::strict_ppl::internal::concurrent_queue_rep_base::n_invalid_entries, tbb::internal::atomic_backoff::pause(), and tbb::internal::throw_exception().
{
     for( atomic_backoff b(true);;b.pause() ) {
         ticket c = counter;
         if( c==k ) return;
         else if( c&1 ) {
             ++rb.n_invalid_entries;
             throw_exception( eid_bad_last_alloc );
         }
     }
 }
Friends And Related Function Documentation
template<typename T> friend class micro_queue_pop_finalizer< T > friend
Definition at line 169 of file _concurrent_queue_impl.h.
Member Data Documentation
template<typename T> atomic<ticket> tbb::strict_ppl::internal::micro_queue< T >::head_counter
Definition at line 185 of file _concurrent_queue_impl.h.
Referenced by tbb::strict_ppl::internal::micro_queue< T >::assign().
template<typename T> atomic<page*> tbb::strict_ppl::internal::micro_queue< T >::head_page
Definition at line 184 of file _concurrent_queue_impl.h.
Referenced by tbb::strict_ppl::internal::micro_queue< T >::assign().
template<typename T> spin_mutex tbb::strict_ppl::internal::micro_queue< T >::page_mutex
Definition at line 190 of file _concurrent_queue_impl.h.
template<typename T> atomic<ticket> tbb::strict_ppl::internal::micro_queue< T >::tail_counter
Definition at line 188 of file _concurrent_queue_impl.h.
Referenced by tbb::strict_ppl::internal::micro_queue< T >::assign().
template<typename T> atomic<page*> tbb::strict_ppl::internal::micro_queue< T >::tail_page
Definition at line 187 of file _concurrent_queue_impl.h.
Referenced by tbb::strict_ppl::internal::micro_queue< T >::assign().
The documentation for this class was generated from the following file:
_concurrent_queue_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.