Intel(R) Threading Building Blocks Doxygen Documentation: internal::join_node_FE< queueing, InputTuple, OutputTuple > Class Template Reference
internal::join_node_FE< queueing, InputTuple, OutputTuple > Class Template Reference
#include <_flow_graph_join_impl.h>
Public Types
typedef OutputTuple output_type
typedef InputTuple input_type
typedef join_node_base< queueing, InputTuple, OutputTuple > base_node_type
Public Member Functions
join_node_FE (graph &g)
join_node_FE (const join_node_FE &other)
void set_my_node (base_node_type *new_my_node)
void reset_port_count ()
task * decrement_port_count (bool handle_task) __TBB_override
void increment_port_count () __TBB_override
input_type & input_ports ()
Public Member Functions inherited from internal::forwarding_base
forwarding_base (graph &g)
virtual ~forwarding_base ()
Static Public Attributes
static const int N = tbb::flow::tuple_size<OutputTuple>::value
Protected Member Functions
void reset (reset_flags f)
bool tuple_build_may_succeed ()
bool try_to_make_tuple (output_type &out)
void tuple_accepted ()
void tuple_rejected ()
Protected Attributes
input_type my_inputs
base_node_type * my_node
atomic< size_t > ports_with_no_items
Additional Inherited Members
Public Attributes inherited from internal::forwarding_base
graph & graph_ref
Detailed Description
template<typename InputTuple, typename OutputTuple>
class internal::join_node_FE< queueing, InputTuple, OutputTuple >
Definition at line 952 of file _flow_graph_join_impl.h.
Member Typedef Documentation
template<typename InputTuple , typename OutputTuple > typedef join_node_base<queueing, InputTuple, OutputTuple> internal::join_node_FE< queueing, InputTuple, OutputTuple >::base_node_type
Definition at line 957 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple > typedef InputTuple internal::join_node_FE< queueing, InputTuple, OutputTuple >::input_type
Definition at line 956 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple > typedef OutputTuple internal::join_node_FE< queueing, InputTuple, OutputTuple >::output_type
Definition at line 955 of file _flow_graph_join_impl.h.
Constructor & Destructor Documentation
template<typename InputTuple , typename OutputTuple > internal::join_node_FE< queueing, InputTuple, OutputTuple >::join_node_FE (graph & g) inline
Definition at line 959 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::set_join_node_pointer().
                                : forwarding_base(g), my_node(NULL) {
             ports_with_no_items = N;
             join_helper<N>::set_join_node_pointer(my_inputs, this);
         }
template<typename InputTuple , typename OutputTuple > internal::join_node_FE< queueing, InputTuple, OutputTuple >::join_node_FE (const join_node_FE< queueing, InputTuple, OutputTuple > & other) inline
Definition at line 964 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::set_join_node_pointer().
                                                 : forwarding_base((other.forwarding_base::graph_ref)), my_node(NULL) {
             ports_with_no_items = N;
             join_helper<N>::set_join_node_pointer(my_inputs, this);
         }
Member Function Documentation
template<typename InputTuple , typename OutputTuple > task* internal::join_node_FE< queueing, InputTuple, OutputTuple >::decrement_port_count (bool handle_task) inline virtual
Implements internal::forwarding_base.
Definition at line 977 of file _flow_graph_join_impl.h.
References internal::forwarding_base::graph_ref, tbb::flow::interface10::internal::is_graph_active(), tbb::flow::interface10::internal::spawn_in_graph_arena(), and task.
         {
             if(ports_with_no_items.fetch_and_decrement() == 1) {
                 if(internal::is_graph_active(this->graph_ref)) {
                     task *rtask = new ( task::allocate_additional_child_of( *(this->graph_ref.root_task()) ) )
                         forward_task_bypass <base_node_type>(*my_node);
                     if(!handle_task) return rtask;
                     internal::spawn_in_graph_arena(this->graph_ref, *rtask);
                 }
             }
             return NULL;
         }
template<typename InputTuple , typename OutputTuple > void internal::join_node_FE< queueing, InputTuple, OutputTuple >::increment_port_count () inline virtual
Implements internal::forwarding_base.
Definition at line 990 of file _flow_graph_join_impl.h.
References __TBB_ASSERT.
 { __TBB_ASSERT(false, NULL); }  // should never be called
template<typename InputTuple , typename OutputTuple > input_type& internal::join_node_FE< queueing, InputTuple, OutputTuple >::input_ports () inline
Definition at line 992 of file _flow_graph_join_impl.h.
 { return my_inputs; }
template<typename InputTuple , typename OutputTuple > void internal::join_node_FE< queueing, InputTuple, OutputTuple >::reset (reset_flags f) inline protected
Definition at line 996 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::reset_inputs().
{
             reset_port_count();
             join_helper<N>::reset_inputs(my_inputs, f );
         }
template<typename InputTuple , typename OutputTuple > void internal::join_node_FE< queueing, InputTuple, OutputTuple >::reset_port_count () inline
Definition at line 972 of file _flow_graph_join_impl.h.
{
             ports_with_no_items = N;
         }
template<typename InputTuple , typename OutputTuple > void internal::join_node_FE< queueing, InputTuple, OutputTuple >::set_my_node (base_node_type * new_my_node) inline
Definition at line 970 of file _flow_graph_join_impl.h.
 { my_node = new_my_node; }
template<typename InputTuple , typename OutputTuple > bool internal::join_node_FE< queueing, InputTuple, OutputTuple >::try_to_make_tuple (output_type & out) inline protected
Definition at line 1013 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::get_items().
{
             if(ports_with_no_items) return false;
             return join_helper<N>::get_items(my_inputs, out);
         }
template<typename InputTuple , typename OutputTuple > void internal::join_node_FE< queueing, InputTuple, OutputTuple >::tuple_accepted () inline protected
Definition at line 1018 of file _flow_graph_join_impl.h.
References internal::join_helper< N >::reset_ports().
{
             reset_port_count();
             join_helper<N>::reset_ports(my_inputs);
         }
template<typename InputTuple , typename OutputTuple > bool internal::join_node_FE< queueing, InputTuple, OutputTuple >::tuple_build_may_succeed () inline protected
Definition at line 1009 of file _flow_graph_join_impl.h.
{
             return !ports_with_no_items;
         }
template<typename InputTuple , typename OutputTuple > void internal::join_node_FE< queueing, InputTuple, OutputTuple >::tuple_rejected () inline protected
Definition at line 1022 of file _flow_graph_join_impl.h.
{
             // nothing to do.
         }
Member Data Documentation
template<typename InputTuple , typename OutputTuple > input_type internal::join_node_FE< queueing, InputTuple, OutputTuple >::my_inputs protected
Definition at line 1026 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple > base_node_type* internal::join_node_FE< queueing, InputTuple, OutputTuple >::my_node protected
Definition at line 1027 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple > const int internal::join_node_FE< queueing, InputTuple, OutputTuple >::N = tbb::flow::tuple_size<OutputTuple>::value static
Definition at line 954 of file _flow_graph_join_impl.h.
template<typename InputTuple , typename OutputTuple > atomic<size_t> internal::join_node_FE< queueing, InputTuple, OutputTuple >::ports_with_no_items protected
Definition at line 1028 of file _flow_graph_join_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_join_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.