Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::internal::key_matching_port< TraitsType > Class Template Reference
tbb::flow::interface10::internal::key_matching_port< TraitsType > Class Template Reference
#include <flow_graph.h>
Classes
class key_matching_port_operation
Public Types
typedef TraitsType traits
typedef key_matching_port< traits > class_type
typedef TraitsType::T input_type
typedef TraitsType::K key_type
typedef tbb::internal::strip< key_type >::type noref_key_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef TraitsType::TtoK type_to_key_func_type
typedef TraitsType::KHash hash_compare_type
typedef hash_buffer< key_type, input_type, type_to_key_func_type, hash_compare_type > buffer_type
Public Types inherited from tbb::flow::interface10::receiver< TraitsType::T >
typedef TraitsType::T input_type
The input type of this receiver.
typedef internal::async_helpers< TraitsType::T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::internal::hash_buffer< TraitsType::K, TraitsType::T, TraitsType::TtoK, TraitsType::KHash >
typedef TraitsType::T value_type
typedef buffer_element_type< value_type >::type element_type
typedef value_type * pointer_type
typedef element_type * list_array_type
typedef list_array_type * pointer_array_type
typedef tbb::cache_aligned_allocator< typename aligned_pair< TraitsType::T, void * >::type >::template rebind< list_array_type >::other pointer_array_allocator_type
typedef tbb::cache_aligned_allocator< typename aligned_pair< TraitsType::T, void * >::type >::template rebind< element_type >::other elements_array_allocator
typedef tbb::internal::strip< TraitsType::K >::type Knoref
Public Member Functions
key_matching_port ()
key_matching_port (const key_matching_port &)
~key_matching_port ()
void set_join_node_pointer (forwarding_base *join)
void set_my_key_func (type_to_key_func_type *f)
type_to_key_func_type * get_my_key_func ()
bool get_item (input_type &v)
void reset_port ()
void reset_receiver (reset_flags f) __TBB_override
put receiver back in initial state
Public Member Functions inherited from tbb::flow::interface10::receiver< TraitsType::T >
bool try_put (const typename internal::async_helpers< TraitsType::T >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< TraitsType::T >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
virtual bool register_predecessor (predecessor_type &)
Add a predecessor to the node.
virtual bool remove_predecessor (predecessor_type &)
Remove a predecessor from the node.
Public Member Functions inherited from tbb::flow::interface10::internal::hash_buffer< TraitsType::K, TraitsType::T, TraitsType::TtoK, TraitsType::KHash >
hash_buffer ()
~hash_buffer ()
void reset ()
void set_key_func (TraitsType::TtoK *vtk)
TraitsType::TtoK * get_key_func ()
bool insert_with_key (const value_type &v)
bool find_ref_with_key (const Knoref &k, pointer_type &v)
bool find_with_key (const Knoref &k, value_type &v)
void delete_with_key (const Knoref &k)
Protected Member Functions
task * try_put_task (const input_type &v) __TBB_override
Put item to successor; return task to run the successor if possible.
graph & graph_reference () __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::receiver< TraitsType::T >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Private Types
enum op_type { try__put, get__item, res_port }
enum op_stat { WAIT =0, SUCCEEDED, FAILED }
typedef internal::aggregating_functor< class_type, key_matching_port_operation > handler_type
Private Member Functions
void handle_operations (key_matching_port_operation *op_list)
Private Attributes
aggregator< handler_type, key_matching_port_operation > my_aggregator
matching_forwarding_base< key_type > * my_join
Friends
class internal::aggregating_functor< class_type, key_matching_port_operation >
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Additional Inherited Members
Static Public Attributes inherited from tbb::flow::interface10::internal::hash_buffer< TraitsType::K, TraitsType::T, TraitsType::TtoK, TraitsType::KHash >
static const size_t INITIAL_SIZE
Detailed Description
template<class TraitsType>
class tbb::flow::interface10::internal::key_matching_port< TraitsType >
Definition at line 656 of file flow_graph.h.
Member Typedef Documentation
template<class TraitsType > typedef hash_buffer< key_type, input_type, type_to_key_func_type, hash_compare_type > tbb::flow::interface10::internal::key_matching_port< TraitsType >::buffer_type
Definition at line 669 of file flow_graph.h.
template<class TraitsType > typedef key_matching_port<traits> tbb::flow::interface10::internal::key_matching_port< TraitsType >::class_type
Definition at line 662 of file flow_graph.h.
template<class TraitsType > typedef internal::aggregating_functor<class_type, key_matching_port_operation> tbb::flow::interface10::internal::key_matching_port< TraitsType >::handler_type private
Definition at line 704 of file flow_graph.h.
template<class TraitsType > typedef TraitsType::KHash tbb::flow::interface10::internal::key_matching_port< TraitsType >::hash_compare_type
Definition at line 668 of file flow_graph.h.
template<class TraitsType > typedef TraitsType::T tbb::flow::interface10::internal::key_matching_port< TraitsType >::input_type
Definition at line 663 of file flow_graph.h.
template<class TraitsType > typedef TraitsType::K tbb::flow::interface10::internal::key_matching_port< TraitsType >::key_type
Definition at line 664 of file flow_graph.h.
template<class TraitsType > typedef tbb::internal::strip<key_type>::type tbb::flow::interface10::internal::key_matching_port< TraitsType >::noref_key_type
Definition at line 665 of file flow_graph.h.
template<class TraitsType > typedef receiver<input_type>::predecessor_type tbb::flow::interface10::internal::key_matching_port< TraitsType >::predecessor_type
Definition at line 666 of file flow_graph.h.
template<class TraitsType > typedef TraitsType tbb::flow::interface10::internal::key_matching_port< TraitsType >::traits
Definition at line 661 of file flow_graph.h.
template<class TraitsType > typedef TraitsType::TtoK tbb::flow::interface10::internal::key_matching_port< TraitsType >::type_to_key_func_type
Definition at line 667 of file flow_graph.h.
Member Enumeration Documentation
template<class TraitsType > enum tbb::flow::interface10::internal::key_matching_port::op_stat private
Enumerator
WAIT
SUCCEEDED
FAILED
Definition at line 682 of file flow_graph.h.
template<class TraitsType > enum tbb::flow::interface10::internal::key_matching_port::op_type private
Enumerator
try__put
get__item
res_port
Definition at line 677 of file flow_graph.h.
Constructor & Destructor Documentation
template<class TraitsType > tbb::flow::interface10::internal::key_matching_port< TraitsType >::key_matching_port () inline
Definition at line 776 of file flow_graph.h.
References tbb::internal::fgt_reserve_wait(), tbb::task::increment_ref_count(), and tbb::flow::interface10::graph::my_root_task.
                       {
         my_root_task->increment_ref_count();
         tbb::internal::fgt_reserve_wait(this);
     }
template<class TraitsType > tbb::flow::interface10::internal::key_matching_port< TraitsType >::key_matching_port (const key_matching_port< TraitsType > &) inline
Definition at line 782 of file flow_graph.h.
{
     if (my_root_task) {
         tbb::internal::fgt_release_wait(this);
         my_root_task->decrement_ref_count();
template<class TraitsType > tbb::flow::interface10::internal::key_matching_port< TraitsType >::~key_matching_port () inline
Definition at line 787 of file flow_graph.h.
Member Function Documentation
template<class TraitsType > bool tbb::flow::interface10::internal::key_matching_port< TraitsType >::get_item (input_type & v) inline
Definition at line 797 of file flow_graph.h.
{
     {
         spin_mutex::scoped_lock lock(nodelist_mutex);
template<class TraitsType > type_to_key_func_type* tbb::flow::interface10::internal::key_matching_port< TraitsType >::get_my_key_func () inline
Definition at line 795 of file flow_graph.h.
template<class TraitsType > graph& tbb::flow::interface10::internal::key_matching_port< TraitsType >::graph_reference () inline protected virtual
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 770 of file flow_graph.h.
template<class TraitsType > void tbb::flow::interface10::internal::key_matching_port< TraitsType >::handle_operations (key_matching_port_operation * op_list) inline private
Definition at line 708 of file flow_graph.h.
               {
 namespace flow {
 namespace interface10 {
 #include "internal/_flow_graph_body_impl.h"
 #include "internal/_flow_graph_cache_impl.h"
 #include "internal/_flow_graph_types_impl.h"
 #if __TBB_PREVIEW_ASYNC_MSG
 #include "internal/_flow_graph_async_msg_impl.h"
 #endif
 using namespace internal::graph_policy_namespace;
 template <typename C, typename N>
 graph_iterator<C,N>::graph_iterator(C *g, bool begin) : my_graph(g), current_node(NULL)
 {
     if (begin) current_node = my_graph->my_nodes;
     //else it is an end iterator by default
 }
 template <typename C, typename N>
 typename graph_iterator<C,N>::reference graph_iterator<C,N>::operator*() const {
     __TBB_ASSERT(current_node, "graph_iterator at end");
     return *operator->();
 }
 template <typename C, typename N>
 typename graph_iterator<C,N>::pointer graph_iterator<C,N>::operator->() const {
     return current_node;
 }
 template <typename C, typename N>
 void graph_iterator<C,N>::internal_forward() {
     if (current_node) current_node = current_node->next;
 }
 inline graph::graph() : my_nodes(NULL), my_nodes_last(NULL), my_task_arena(NULL) {
     prepare_task_arena();
     own_context = true;
     cancelled = false;
     caught_exception = false;
     my_context = new task_group_context(tbb::internal::FLOW_TASKS);
     my_root_task = (new (task::allocate_root(*my_context)) empty_task);
     my_root_task->set_ref_count(1);
template<class TraitsType > void tbb::flow::interface10::internal::key_matching_port< TraitsType >::reset_port () inline
Definition at line 834 of file flow_graph.h.
                                   { return iterator(this, true); }
 inline graph::iterator graph::end() { return iterator(this, false); }
template<class TraitsType > void tbb::flow::interface10::internal::key_matching_port< TraitsType >::reset_receiver (reset_flags f) inline virtual
put receiver back in initial state
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 846 of file flow_graph.h.
{
     tbb::internal::fgt_graph_desc(this, name);
 }
 #endif
 inline graph_node::graph_node(graph& g) : my_graph(g) {
template<class TraitsType > void tbb::flow::interface10::internal::key_matching_port< TraitsType >::set_join_node_pointer (forwarding_base * join) inline
Definition at line 789 of file flow_graph.h.
References lock, tbb::flow::interface10::graph_node::next, and tbb::flow::interface10::graph::nodelist_mutex.
{
     n->next = NULL;
     {
template<class TraitsType > void tbb::flow::interface10::internal::key_matching_port< TraitsType >::set_my_key_func (type_to_key_func_type * f) inline
Definition at line 793 of file flow_graph.h.
template<class TraitsType > task* tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task (const input_type & t) inline protected virtual
Put item to successor; return task to run the successor if possible.
Implements tbb::flow::interface10::receiver< TraitsType::T >.
Definition at line 758 of file flow_graph.h.
References tbb::task::allocate_root(), tbb::internal::fgt_graph(), tbb::flow::interface10::graph::my_context, tbb::flow::interface10::graph::my_is_active, tbb::flow::interface10::graph::my_root_task, tbb::flow::interface10::graph::own_context, tbb::flow::interface10::graph::prepare_task_arena(), and tbb::task::set_ref_count().
{
     prepare_task_arena();
     own_context = false;
     my_root_task = (new (task::allocate_root(*my_context)) empty_task);
     my_root_task->set_ref_count(1);
     tbb::internal::fgt_graph(this);
     my_is_active = true;
 }
 inline graph::~graph() {
     wait_for_all();
Friends And Related Function Documentation
template<class TraitsType > friend class internal::aggregating_functor< class_type, key_matching_port_operation > friend
Definition at line 705 of file flow_graph.h.
template<class TraitsType > template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 756 of file flow_graph.h.
template<class TraitsType > template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 757 of file flow_graph.h.
template<class TraitsType > template<typename R , typename B > friend class run_and_put_task friend
Definition at line 755 of file flow_graph.h.
Member Data Documentation
template<class TraitsType > aggregator<handler_type, key_matching_port_operation> tbb::flow::interface10::internal::key_matching_port< TraitsType >::my_aggregator private
Definition at line 706 of file flow_graph.h.
template<class TraitsType > matching_forwarding_base<key_type>* tbb::flow::interface10::internal::key_matching_port< TraitsType >::my_join private
Definition at line 858 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.