Intel(R) Threading Building Blocks Doxygen Documentation: internal::join_node_base< JP, InputTuple, OutputTuple > Class Template Reference
internal::join_node_base< JP, InputTuple, OutputTuple > Class Template Reference
join_node_base
#include <_flow_graph_join_impl.h>
Classes
class join_node_base_operation
Public Types
typedef OutputTuple output_type
typedef sender< output_type >::successor_type successor_type
typedef join_node_FE< JP, InputTuple, OutputTuple > input_ports_type
Public Types inherited from tbb::flow::interface10::sender< OutputTuple >
typedef OutputTuple output_type
The output type of this sender.
typedef internal::async_helpers< OutputTuple >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
join_node_base (graph &g)
join_node_base (const join_node_base &other)
template<typename FunctionTuple >
join_node_base (graph &g, FunctionTuple f)
bool register_successor (successor_type &r) __TBB_override
Add a new successor to this node.
bool remove_successor (successor_type &r) __TBB_override
Removes a successor from this node.
bool try_get (output_type &v) __TBB_override
Request an item from the sender.
Public Member Functions inherited from tbb::flow::interface10::sender< OutputTuple >
virtual bool try_reserve (OutputTuple &)
Reserves an item in the sender.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
virtual bool try_release ()
Releases the reserved item.
virtual bool try_consume ()
Consumes the reserved item.
Protected Member Functions
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::sender< OutputTuple >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Private Types
enum op_type {
reg_succ, rem_succ, try__get, do_fwrd,
do_fwrd_bypass
}
enum op_stat { WAIT =0, SUCCEEDED, FAILED }
typedef join_node_base< JP, InputTuple, OutputTuple > class_type
typedef internal::aggregating_functor< class_type, join_node_base_operation > handler_type
Private Member Functions
void handle_operations (join_node_base_operation *op_list)
task * forward_task ()
Private Attributes
bool forwarder_busy
aggregator< handler_type, join_node_base_operation > my_aggregator
broadcast_cache< output_type, null_rw_mutex > my_successors
Friends
class internal::aggregating_functor< class_type, join_node_base_operation >
class forward_task_bypass< join_node_base< JP, InputTuple, OutputTuple > >
Detailed Description
template<typename JP, typename InputTuple, typename OutputTuple>
class internal::join_node_base< JP, InputTuple, OutputTuple >
join_node_base
Definition at line 867 of file _flow_graph_join_impl.h.
Member Typedef Documentation
template<typename JP , typename InputTuple , typename OutputTuple > typedef join_node_base<JP,InputTuple,OutputTuple> internal::join_node_base< JP, InputTuple, OutputTuple >::class_type private
Definition at line 1290 of file _flow_graph_join_impl.h.
template<typename JP , typename InputTuple , typename OutputTuple > typedef internal::aggregating_functor<class_type, join_node_base_operation> internal::join_node_base< JP, InputTuple, OutputTuple >::handler_type private
Definition at line 1311 of file _flow_graph_join_impl.h.
template<typename JP , typename InputTuple , typename OutputTuple > typedef join_node_FE<JP, InputTuple, OutputTuple> internal::join_node_base< JP, InputTuple, OutputTuple >::input_ports_type
Definition at line 1272 of file _flow_graph_join_impl.h.
template<typename JP , typename InputTuple , typename OutputTuple > typedef OutputTuple internal::join_node_base< JP, InputTuple, OutputTuple >::output_type
Definition at line 1269 of file _flow_graph_join_impl.h.
template<typename JP , typename InputTuple , typename OutputTuple > typedef sender<output_type>::successor_type internal::join_node_base< JP, InputTuple, OutputTuple >::successor_type
Definition at line 1271 of file _flow_graph_join_impl.h.
Member Enumeration Documentation
template<typename JP , typename InputTuple , typename OutputTuple > enum internal::join_node_base::op_stat private
Enumerator
WAIT
SUCCEEDED
FAILED
Definition at line 1289 of file _flow_graph_join_impl.h.
 {WAIT=0, SUCCEEDED, FAILED};
template<typename JP , typename InputTuple , typename OutputTuple > enum internal::join_node_base::op_type private
Enumerator
reg_succ
rem_succ
try__get
do_fwrd
do_fwrd_bypass
Definition at line 1284 of file _flow_graph_join_impl.h.
                      { reg_succ, rem_succ, try__get, do_fwrd, do_fwrd_bypass
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
             , add_blt_succ, del_blt_succ, blt_succ_cnt, blt_succ_cpy
 #endif
         };
Constructor & Destructor Documentation
template<typename JP , typename InputTuple , typename OutputTuple > internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base (graph & g) inline
Definition at line 1396 of file _flow_graph_join_impl.h.
                                  : graph_node(g), input_ports_type(g), forwarder_busy(false) {
             my_successors.set_owner(this);
             input_ports_type::set_my_node(this);
             my_aggregator.initialize_handler(handler_type(this));
         }
template<typename JP , typename InputTuple , typename OutputTuple > internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base (const join_node_base< JP, InputTuple, OutputTuple > & other) inline
Definition at line 1402 of file _flow_graph_join_impl.h.
                                                     :
             graph_node(other.graph_node::my_graph), input_ports_type(other),
             sender<OutputTuple>(), forwarder_busy(false), my_successors() {
             my_successors.set_owner(this);
             input_ports_type::set_my_node(this);
             my_aggregator.initialize_handler(handler_type(this));
         }
template<typename JP , typename InputTuple , typename OutputTuple > template<typename FunctionTuple > internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base (graph & g, FunctionTuple f) inline
Definition at line 1411 of file _flow_graph_join_impl.h.
                                                   : graph_node(g), input_ports_type(g, f), forwarder_busy(false) {
             my_successors.set_owner(this);
             input_ports_type::set_my_node(this);
             my_aggregator.initialize_handler(handler_type(this));
         }
Member Function Documentation
template<typename JP , typename InputTuple , typename OutputTuple > task* internal::join_node_base< JP, InputTuple, OutputTuple >::forward_task () inline private
Definition at line 1479 of file _flow_graph_join_impl.h.
References internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base_operation::bypass_t.
{
             join_node_base_operation op_data(do_fwrd_bypass);
             my_aggregator.execute(&op_data);
             return op_data.bypass_t;
         }
template<typename JP , typename InputTuple , typename OutputTuple > void internal::join_node_base< JP, InputTuple, OutputTuple >::handle_operations (join_node_base_operation * op_list) inline private
Definition at line 1316 of file _flow_graph_join_impl.h.
References tbb::internal::__TBB_store_with_release(), internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base_operation::bypass_t, tbb::flow::interface10::combine_tasks(), tbb::flow::interface10::internal::is_graph_active(), internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base_operation::my_arg, internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base_operation::my_succ, tbb::flow::interface10::internal::spawn_in_graph_arena(), SUCCEEDED, task, and internal::join_node_base< JP, InputTuple, OutputTuple >::join_node_base_operation::type.
{
             join_node_base_operation *current;
             while(op_list) {
                 current = op_list;
                 op_list = op_list->next;
                 switch(current->type) {
                 case reg_succ: {
                         my_successors.register_successor(*(current->my_succ));
                         if(tuple_build_may_succeed() && !forwarder_busy && internal::is_graph_active(my_graph)) {
                             task *rtask = new ( task::allocate_additional_child_of(*(my_graph.root_task())) )
                                     forward_task_bypass
                                     <join_node_base<JP,InputTuple,OutputTuple> >(*this);
                             internal::spawn_in_graph_arena(my_graph, *rtask);
                             forwarder_busy = true;
                         }
                         __TBB_store_with_release(current->status, SUCCEEDED);
                     }
                     break;
                 case rem_succ:
                     my_successors.remove_successor(*(current->my_succ));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case try__get:
                     if(tuple_build_may_succeed()) {
                         if(try_to_make_tuple(*(current->my_arg))) {
                             tuple_accepted();
                             __TBB_store_with_release(current->status, SUCCEEDED);
                         }
                         else __TBB_store_with_release(current->status, FAILED);
                     }
                     else __TBB_store_with_release(current->status, FAILED);
                     break;
                 case do_fwrd_bypass: {
                         bool build_succeeded;
                         task *last_task = NULL;
                         output_type out;
                         if(tuple_build_may_succeed()) {  // checks output queue of FE
                             do {
                                 build_succeeded = try_to_make_tuple(out);  // fetch front_end of queue
                                 if(build_succeeded) {
                                     task *new_task = my_successors.try_put_task(out);
                                     last_task = combine_tasks(my_graph, last_task, new_task);
                                     if(new_task) {
                                         tuple_accepted();
                                     }
                                     else {
                                         tuple_rejected();
                                         build_succeeded = false;
                                     }
                                 }
                             } while(build_succeeded);
                         }
                         current->bypass_t = last_task;
                         __TBB_store_with_release(current->status, SUCCEEDED);
                         forwarder_busy = false;
                     }
                     break;
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
                 case add_blt_succ:
                     my_successors.internal_add_built_successor(*(current->my_succ));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case del_blt_succ:
                     my_successors.internal_delete_built_successor(*(current->my_succ));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case blt_succ_cnt:
                     current->cnt_val = my_successors.successor_count();
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case blt_succ_cpy:
                     my_successors.copy_successors(*(current->slist));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
 #endif  /* TBB_DEPRECATED_FLOW_NODE_EXTRACTION */
                 }
             }
         }
template<typename JP , typename InputTuple , typename OutputTuple > bool internal::join_node_base< JP, InputTuple, OutputTuple >::register_successor (successor_type & r) inline virtual
Add a new successor to this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 1417 of file _flow_graph_join_impl.h.
References SUCCEEDED.
{
             join_node_base_operation op_data(r, reg_succ);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
template<typename JP , typename InputTuple , typename OutputTuple > bool internal::join_node_base< JP, InputTuple, OutputTuple >::remove_successor (successor_type & r) inline virtual
Removes a successor from this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 1423 of file _flow_graph_join_impl.h.
References SUCCEEDED.
{
             join_node_base_operation op_data(r, rem_succ);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
template<typename JP , typename InputTuple , typename OutputTuple > void internal::join_node_base< JP, InputTuple, OutputTuple >::reset_node (reset_flags f) inline protected
Definition at line 1470 of file _flow_graph_join_impl.h.
References tbb::flow::interface10::rf_clear_edges.
{
             input_ports_type::reset(f);
             if(f & rf_clear_edges) my_successors.clear();
         }
template<typename JP , typename InputTuple , typename OutputTuple > bool internal::join_node_base< JP, InputTuple, OutputTuple >::try_get (output_type &) inline virtual
Request an item from the sender.
Reimplemented from tbb::flow::interface10::sender< OutputTuple >.
Definition at line 1429 of file _flow_graph_join_impl.h.
References __TBB_override, and SUCCEEDED.
{
             join_node_base_operation op_data(v, try__get);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
Friends And Related Function Documentation
template<typename JP , typename InputTuple , typename OutputTuple > friend class forward_task_bypass< join_node_base< JP, InputTuple, OutputTuple > > friend
Definition at line 1478 of file _flow_graph_join_impl.h.
template<typename JP , typename InputTuple , typename OutputTuple > friend class internal::aggregating_functor< class_type, join_node_base_operation > friend
Definition at line 1312 of file _flow_graph_join_impl.h.
Member Data Documentation
template<typename JP , typename InputTuple , typename OutputTuple > bool internal::join_node_base< JP, InputTuple, OutputTuple >::forwarder_busy private
Definition at line 1313 of file _flow_graph_join_impl.h.
template<typename JP , typename InputTuple , typename OutputTuple > aggregator<handler_type, join_node_base_operation> internal::join_node_base< JP, InputTuple, OutputTuple >::my_aggregator private
Definition at line 1314 of file _flow_graph_join_impl.h.
template<typename JP , typename InputTuple , typename OutputTuple > broadcast_cache<output_type, null_rw_mutex> internal::join_node_base< JP, InputTuple, OutputTuple >::my_successors private
Definition at line 1476 of file _flow_graph_join_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_join_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.