Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::mail_inbox Class Reference
tbb::internal::mail_inbox Class Reference
Class representing source of mail.
#include <mailbox.h>
Public Member Functions
mail_inbox ()
Construct unattached inbox.
void attach (mail_outbox &putter)
Attach inbox to a corresponding outbox.
void detach ()
Detach inbox from its outbox.
task_proxy * pop (__TBB_ISOLATION_EXPR(isolation_tag isolation))
Get next piece of mail, or NULL if mailbox is empty.
bool empty ()
Return true if mailbox is empty.
void set_is_idle (bool value)
Indicate whether thread that reads this mailbox is idle.
bool is_idle_state (bool value) const
Indicate whether thread that reads this mailbox is idle.
Private Attributes
mail_outbox * my_putter
Corresponding sink where mail that we receive will be put.
Detailed Description
Class representing source of mail.
Definition at line 189 of file mailbox.h.
Constructor & Destructor Documentation
tbb::internal::mail_inbox::mail_inbox () inline
Construct unattached inbox.
Definition at line 194 of file mailbox.h.
 : my_putter(NULL) {}
Member Function Documentation
void tbb::internal::mail_inbox::attach (mail_outbox & putter) inline
Attach inbox to a corresponding outbox.
Definition at line 197 of file mailbox.h.
{
         my_putter = &putter;
     }
void tbb::internal::mail_inbox::detach () inline
Detach inbox from its outbox.
Definition at line 201 of file mailbox.h.
References __TBB_ASSERT.
Referenced by tbb::internal::arena::process().
                   {
         __TBB_ASSERT(my_putter,"not attached");
         my_putter = NULL;
     }
bool tbb::internal::mail_inbox::empty () inline
Return true if mailbox is empty.
Definition at line 210 of file mailbox.h.
References tbb::internal::mail_outbox::empty().
                  {
         return my_putter->empty();
     }
bool tbb::internal::mail_inbox::is_idle_state (bool value) const inline
Indicate whether thread that reads this mailbox is idle.
Definition at line 222 of file mailbox.h.
References tbb::internal::unpadded_mail_outbox::my_is_idle, tbb::internal::task_proxy::outbox, and value.
Referenced by tbb::internal::generic_scheduler::attach_arena(), and tbb::internal::arena::process().
{
         return !my_putter || my_putter->my_is_idle == value;
     }
task_proxy* tbb::internal::mail_inbox::pop (__TBB_ISOLATION_EXPR(isolation_tag isolation)) inline
Get next piece of mail, or NULL if mailbox is empty.
Definition at line 206 of file mailbox.h.
References __TBB_ISOLATION_EXPR, and tbb::internal::mail_outbox::internal_pop().
Referenced by tbb::internal::generic_scheduler::get_mailbox_task().
{
         return my_putter->internal_pop( __TBB_ISOLATION_EXPR( isolation ) );
     }
void tbb::internal::mail_inbox::set_is_idle (bool value) inline
Indicate whether thread that reads this mailbox is idle.
Raises assertion failure if mailbox is redundantly marked as not idle.
Definition at line 215 of file mailbox.h.
References __TBB_ASSERT, tbb::internal::unpadded_mail_outbox::my_is_idle, and value.
Referenced by tbb::internal::generic_scheduler::attach_arena().
{
         if( my_putter ) {
             __TBB_ASSERT( my_putter->my_is_idle || value, "attempt to redundantly mark mailbox as not idle" );
             my_putter->my_is_idle = value;
         }
     }
Member Data Documentation
mail_outbox* tbb::internal::mail_inbox::my_putter private
Corresponding sink where mail that we receive will be put.
Definition at line 191 of file mailbox.h.
The documentation for this class was generated from the following file:
mailbox.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.