Intel(R) Threading Building Blocks Doxygen Documentation: internal::join_helper< N > Struct Template Reference
internal::join_helper< N > Struct Template Reference
#include <_flow_graph_join_impl.h>
Static Public Member Functions
template<typename TupleType , typename PortType >
static void set_join_node_pointer (TupleType &my_input, PortType *port)
template<typename TupleType >
static void consume_reservations (TupleType &my_input)
template<typename TupleType >
static void release_my_reservation (TupleType &my_input)
template<typename TupleType >
static void release_reservations (TupleType &my_input)
template<typename InputTuple , typename OutputTuple >
static bool reserve (InputTuple &my_input, OutputTuple &out)
template<typename InputTuple , typename OutputTuple >
static bool get_my_item (InputTuple &my_input, OutputTuple &out)
template<typename InputTuple , typename OutputTuple >
static bool get_items (InputTuple &my_input, OutputTuple &out)
template<typename InputTuple >
static void reset_my_port (InputTuple &my_input)
template<typename InputTuple >
static void reset_ports (InputTuple &my_input)
template<typename InputTuple , typename KeyFuncTuple >
static void set_key_functors (InputTuple &my_input, KeyFuncTuple &my_key_funcs)
template<typename KeyFuncTuple >
static void copy_key_functors (KeyFuncTuple &my_inputs, KeyFuncTuple &other_inputs)
template<typename InputTuple >
static void reset_inputs (InputTuple &my_input, reset_flags f)
Detailed Description
template<int N>
struct internal::join_helper< N >
Definition at line 52 of file _flow_graph_join_impl.h.
Member Function Documentation
template<int N> template<typename TupleType > static void internal::join_helper< N >::consume_reservations (TupleType & my_input) inline static
Definition at line 60 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< reserving, InputTuple, OutputTuple >::tuple_accepted().
{
             tbb::flow::get<N-1>( my_input ).consume();
             join_helper<N-1>::consume_reservations( my_input );
         }
template<int N> template<typename KeyFuncTuple > static void internal::join_helper< N >::copy_key_functors (KeyFuncTuple & my_inputs, KeyFuncTuple & other_inputs) inline static
Definition at line 116 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::join_node_FE().
{
             if(tbb::flow::get<N-1>(other_inputs).get_my_key_func()) {
                 tbb::flow::get<N-1>(my_inputs).set_my_key_func(tbb::flow::get<N-1>(other_inputs).get_my_key_func()->clone());
             }
             join_helper<N-1>::copy_key_functors(my_inputs, other_inputs);
         }
template<int N> template<typename InputTuple , typename OutputTuple > static bool internal::join_helper< N >::get_items (InputTuple & my_input, OutputTuple & out) inline static
Definition at line 93 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< queueing, InputTuple, OutputTuple >::try_to_make_tuple().
{
             return get_my_item(my_input, out);
         }
template<int N> template<typename InputTuple , typename OutputTuple > static bool internal::join_helper< N >::get_my_item (InputTuple & my_input, OutputTuple & out) inline static
Definition at line 87 of file _flow_graph_join_impl.h.
{
             bool res = tbb::flow::get<N-1>(my_input).get_item(tbb::flow::get<N-1>(out) ); // may fail
             return join_helper<N-1>::get_my_item(my_input, out) && res;       // do get on other inputs before returning
         }
template<int N> template<typename TupleType > static void internal::join_helper< N >::release_my_reservation (TupleType & my_input) inline static
Definition at line 66 of file _flow_graph_join_impl.h.
References tbb::release.
{
             tbb::flow::get<N-1>( my_input ).release();
         }
template<int N> template<typename TupleType > static void internal::join_helper< N >::release_reservations (TupleType & my_input) inline static
Definition at line 71 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< reserving, InputTuple, OutputTuple >::tuple_rejected().
{
             join_helper<N-1>::release_reservations(my_input);
             release_my_reservation(my_input);
         }
template<int N> template<typename InputTuple , typename OutputTuple > static bool internal::join_helper< N >::reserve (InputTuple & my_input, OutputTuple & out) inline static
Definition at line 77 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< reserving, InputTuple, OutputTuple >::try_to_make_tuple().
{
             if ( !tbb::flow::get<N-1>( my_input ).reserve( tbb::flow::get<N-1>( out ) ) ) return false;
             if ( !join_helper<N-1>::reserve( my_input, out ) ) {
                 release_my_reservation( my_input );
                 return false;
             }
             return true;
         }
template<int N> template<typename InputTuple > static void internal::join_helper< N >::reset_inputs (InputTuple & my_input, reset_flags f) inline static
Definition at line 124 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< reserving, InputTuple, OutputTuple >::reset(), internal::join_node_FE< queueing, InputTuple, OutputTuple >::reset(), and internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::reset().
{
             join_helper<N-1>::reset_inputs(my_input, f);
             tbb::flow::get<N-1>(my_input).reset_receiver(f);
         }
template<int N> template<typename InputTuple > static void internal::join_helper< N >::reset_my_port (InputTuple & my_input) inline static
Definition at line 98 of file _flow_graph_join_impl.h.
{
             join_helper<N-1>::reset_my_port(my_input);
             tbb::flow::get<N-1>(my_input).reset_port();
         }
template<int N> template<typename InputTuple > static void internal::join_helper< N >::reset_ports (InputTuple & my_input) inline static
Definition at line 104 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::fill_output_buffer(), and internal::join_node_FE< queueing, InputTuple, OutputTuple >::tuple_accepted().
{
             reset_my_port(my_input);
         }
template<int N> template<typename TupleType , typename PortType > static void internal::join_helper< N >::set_join_node_pointer (TupleType & my_input, PortType * port) inline static
Definition at line 55 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< reserving, InputTuple, OutputTuple >::join_node_FE(), internal::join_node_FE< queueing, InputTuple, OutputTuple >::join_node_FE(), and internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::join_node_FE().
{
             tbb::flow::get<N-1>( my_input ).set_join_node_pointer(port);
             join_helper<N-1>::set_join_node_pointer( my_input, port );
         }
template<int N> template<typename InputTuple , typename KeyFuncTuple > static void internal::join_helper< N >::set_key_functors (InputTuple & my_input, KeyFuncTuple & my_key_funcs) inline static
Definition at line 109 of file _flow_graph_join_impl.h.
Referenced by internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::join_node_FE().
{
             tbb::flow::get<N-1>(my_input).set_my_key_func(tbb::flow::get<N-1>(my_key_funcs));
             tbb::flow::get<N-1>(my_key_funcs) = NULL;
             join_helper<N-1>::set_key_functors(my_input, my_key_funcs);
         }
The documentation for this struct was generated from the following file:
_flow_graph_join_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.