Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::machine_load_store< T, S > Struct Template Reference
tbb::internal::machine_load_store< T, S > Struct Template Reference
#include <icc_generic.h>
Static Public Member Functions
static T load_with_acquire (const volatile T &location)
static void store_with_release (volatile T &location, T value)
Detailed Description
template<typename T, size_t S>
struct tbb::internal::machine_load_store< T, S >
Definition at line 98 of file icc_generic.h.
Member Function Documentation
template<typename T, size_t S> static T tbb::internal::machine_load_store< T, S >::load_with_acquire (const volatile T & location) inline static
Definition at line 99 of file icc_generic.h.
References tbb::internal::memory_order_acquire.
Referenced by tbb::internal::__TBB_FetchAndStoreGeneric(), and __TBB_machine_unlock_byte().
{
         return __atomic_load_explicit(&location, memory_order_acquire);
     }
template<typename T, size_t S> static void tbb::internal::machine_load_store< T, S >::store_with_release (volatile T & location, T value) inline static
Definition at line 102 of file icc_generic.h.
References tbb::internal::icc_intrinsics_port::convert_argument(), and tbb::internal::memory_order_release.
Referenced by tbb::internal::__TBB_FetchAndStoreGeneric(), and __TBB_machine_unlock_byte().
{
         __atomic_store_explicit(&location, icc_intrinsics_port::convert_argument(value), memory_order_release);
     }
The documentation for this struct was generated from the following file:
icc_generic.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.