Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::memory_pool< Alloc > Class Template Reference
tbb::interface6::memory_pool< Alloc > Class Template Reference
Thread-safe growable pool allocator for variable-size requests.
#include <memory_pool.h>
Public Member Functions
memory_pool (const Alloc &src=Alloc())
construct pool with underlying allocator
~memory_pool ()
destroy pool
Public Member Functions inherited from tbb::interface6::internal::pool_base
void recycle ()
Reset pool to reuse its memory (free all objects at once)
void * malloc (size_t size)
The "malloc" analogue to allocate block of memory of size bytes.
void free (void *ptr)
The "free" analogue to discard a previously allocated piece of memory.
void * realloc (void *ptr, size_t size)
The "realloc" analogue complementing pool_malloc.
Static Private Member Functions
static void * allocate_request (intptr_t pool_id, size_t &bytes)
static int deallocate_request (intptr_t pool_id, void *, size_t raw_bytes)
Private Attributes
Alloc my_alloc
Additional Inherited Members
Protected Member Functions inherited from tbb::interface6::internal::pool_base
void destroy ()
destroy pool - must be called in a child class
Protected Attributes inherited from tbb::interface6::internal::pool_base
rml::MemoryPool * my_pool
Detailed Description
template<typename Alloc>
class tbb::interface6::memory_pool< Alloc >
Thread-safe growable pool allocator for variable-size requests.
Definition at line 192 of file memory_pool.h.
Constructor & Destructor Documentation
template<typename Alloc > tbb::interface6::memory_pool< Alloc >::memory_pool (const Alloc & src = Alloc()) explicit
construct pool with underlying allocator
Definition at line 221 of file memory_pool.h.
References tbb::interface6::memory_pool< Alloc >::allocate_request(), tbb::interface6::memory_pool< Alloc >::deallocate_request(), and tbb::internal::throw_exception().
                                                 : my_alloc(src) {
     rml::MemPoolPolicy args(allocate_request, deallocate_request,
                             sizeof(typename Alloc::value_type));
     rml::MemPoolError res = rml::pool_create_v1(intptr_t(this), &args, &my_pool);
     if (res!=rml::POOL_OK)
         tbb::internal::throw_exception(std::runtime_error("Can't create pool"));
 }
template<typename Alloc> tbb::interface6::memory_pool< Alloc >::~memory_pool () inline
destroy pool
Definition at line 202 of file memory_pool.h.
References tbb::interface6::internal::pool_base::destroy().
 { destroy(); } // call the callbacks first and destroy my_alloc latter
Member Function Documentation
template<typename Alloc > void * tbb::interface6::memory_pool< Alloc >::allocate_request (intptr_t pool_id, size_t & bytes) static private
Definition at line 229 of file memory_pool.h.
References __TBB_CATCH, __TBB_TRY, and __TBBMALLOC_ASSERT.
Referenced by tbb::interface6::memory_pool< Alloc >::memory_pool().
{
     memory_pool<Alloc> &self = *reinterpret_cast<memory_pool<Alloc>*>(pool_id);
     const size_t unit_size = sizeof(typename Alloc::value_type);
     __TBBMALLOC_ASSERT( 0 == bytes%unit_size, NULL);
     void *ptr;
     __TBB_TRY { ptr = self.my_alloc.allocate( bytes/unit_size ); }
     __TBB_CATCH(...) { return 0; }
     return ptr;
 }
template<typename Alloc > int tbb::interface6::memory_pool< Alloc >::deallocate_request (intptr_t pool_id, void * raw_ptr, size_t raw_bytes) static private
Definition at line 245 of file memory_pool.h.
References __TBBMALLOC_ASSERT.
Referenced by tbb::interface6::memory_pool< Alloc >::memory_pool().
{
     memory_pool<Alloc> &self = *reinterpret_cast<memory_pool<Alloc>*>(pool_id);
     const size_t unit_size = sizeof(typename Alloc::value_type);
     __TBBMALLOC_ASSERT( 0 == raw_bytes%unit_size, NULL);
     self.my_alloc.deallocate( static_cast<typename Alloc::value_type*>(raw_ptr), raw_bytes/unit_size );
     return 0;
 }
Member Data Documentation
template<typename Alloc> Alloc tbb::interface6::memory_pool< Alloc >::my_alloc private
Definition at line 193 of file memory_pool.h.
The documentation for this class was generated from the following file:
memory_pool.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.