Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::limiter_node< T > Class Template Reference
tbb::flow::interface10::limiter_node< T > Class Template Reference
Forwards messages only if the threshold has not been reached.
#include <flow_graph.h>
Public Types
typedef T input_type
typedef T output_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
Public Types inherited from tbb::flow::interface10::receiver< T >
typedef T input_type
The input type of this receiver.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::sender< T >
typedef T output_type
The output type of this sender.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
limiter_node (graph &g, size_t threshold, int num_decrement_predecessors=0)
Constructor.
limiter_node (const limiter_node &src)
Copy constructor.
bool register_successor (successor_type &r) __TBB_override
Replace the current successor with this new successor.
bool remove_successor (successor_type &r) __TBB_override
Removes a successor from this node.
bool register_predecessor (predecessor_type &src) __TBB_override
Adds src to the list of cached predecessors.
bool remove_predecessor (predecessor_type &src) __TBB_override
Removes src from the list of cached predecessors.
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::receiver< T >
bool try_put (const typename internal::async_helpers< T >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< T >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
Public Member Functions inherited from tbb::flow::interface10::sender< T >
virtual bool try_get (T &)
Request an item from the sender.
virtual bool try_reserve (T &)
Reserves an item in the sender.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
virtual bool try_release ()
Releases the reserved item.
virtual bool try_consume ()
Consumes the reserved item.
Public Attributes
internal::decrementer< limiter_node< T > > decrement
The internal receiver< continue_msg > that decrements the count.
Protected Member Functions
task * try_put_task (const T &t) __TBB_override
Puts an item to this receiver.
graph & graph_reference () __TBB_override
void reset_receiver (reset_flags) __TBB_override
put receiver back in initial state
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::receiver< T >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Protected Member Functions inherited from tbb::flow::interface10::sender< T >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Private Member Functions
bool check_conditions ()
task * forward_task ()
void forward ()
task * decrement_counter ()
Private Attributes
size_t my_threshold
size_t my_count
size_t my_tries
internal::reservable_predecessor_cache< T, spin_mutex > my_predecessors
spin_mutex my_mutex
internal::broadcast_cache< T > my_successors
int init_decrement_predecessors
Friends
class internal::forward_task_bypass< limiter_node< T > >
class internal::decrementer< limiter_node< T > >
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Detailed Description
template<typename T>
class tbb::flow::interface10::limiter_node< T >
Forwards messages only if the threshold has not been reached.
This node forwards items until its threshold is reached. It contains no buffering. If the downstream node rejects, the message is dropped.
Definition at line 102 of file flow_graph.h.
Member Typedef Documentation
template<typename T > typedef T tbb::flow::interface10::limiter_node< T >::input_type
Definition at line 2406 of file flow_graph.h.
template<typename T > typedef T tbb::flow::interface10::limiter_node< T >::output_type
Definition at line 2407 of file flow_graph.h.
template<typename T > typedef receiver<input_type>::predecessor_type tbb::flow::interface10::limiter_node< T >::predecessor_type
Definition at line 2408 of file flow_graph.h.
template<typename T > typedef sender<output_type>::successor_type tbb::flow::interface10::limiter_node< T >::successor_type
Definition at line 2409 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T > tbb::flow::interface10::limiter_node< T >::limiter_node (graph & g, size_t threshold, int num_decrement_predecessors = 0) inline
Constructor.
Definition at line 2508 of file flow_graph.h.
References tbb::internal::fgt_node(), tbb::flow::interface10::graph_node::my_graph, tbb::flow::interface10::internal::predecessor_cache< T, M >::set_owner(), tbb::flow::interface10::internal::successor_cache< T, M >::set_owner(), and tbb::flow::interface10::internal::decrementer< T >::set_owner().
                                                                                :
         graph_node(g), my_threshold(threshold), my_count(0), my_tries(0),
         init_decrement_predecessors(num_decrement_predecessors),
         decrement(num_decrement_predecessors)
     {
         my_predecessors.set_owner(this);
         my_successors.set_owner(this);
         decrement.set_owner(this);
         tbb::internal::fgt_node( tbb::internal::FLOW_LIMITER_NODE, &this->my_graph,
                                  static_cast<receiver<input_type> *>(this), static_cast<receiver<continue_msg> *>(&decrement),
                                  static_cast<sender<output_type> *>(this) );
     }
template<typename T > tbb::flow::interface10::limiter_node< T >::limiter_node (const limiter_node< T > & src) inline
Copy constructor.
Definition at line 2522 of file flow_graph.h.
References __TBB_override, tbb::internal::fgt_node(), tbb::internal::fgt_node_desc(), tbb::flow::interface10::graph_node::my_graph, tbb::flow::interface10::internal::predecessor_cache< T, M >::set_owner(), tbb::flow::interface10::internal::successor_cache< T, M >::set_owner(), and tbb::flow::interface10::internal::decrementer< T >::set_owner().
                                             :
         graph_node(src.my_graph), receiver<T>(), sender<T>(),
         my_threshold(src.my_threshold), my_count(0), my_tries(0),
         init_decrement_predecessors(src.init_decrement_predecessors),
         decrement(src.init_decrement_predecessors)
     {
         my_predecessors.set_owner(this);
         my_successors.set_owner(this);
         decrement.set_owner(this);
         tbb::internal::fgt_node( tbb::internal::FLOW_LIMITER_NODE, &this->my_graph,
                                  static_cast<receiver<input_type> *>(this), static_cast<receiver<continue_msg> *>(&decrement),
                                  static_cast<sender<output_type> *>(this) );
     }
Member Function Documentation
template<typename T > bool tbb::flow::interface10::limiter_node< T >::check_conditions () inline private
Definition at line 2432 of file flow_graph.h.
References tbb::flow::interface10::internal::node_cache< untyped_sender, M >::empty(), and tbb::flow::interface10::internal::successor_cache< T, M >::empty().
                             {  // always called under lock
         return ( my_count + my_tries < my_threshold && !my_predecessors.empty() && !my_successors.empty() );
     }
template<typename T > task* tbb::flow::interface10::limiter_node< T >::decrement_counter () inline private
Definition at line 2495 of file flow_graph.h.
References lock.
{
         {
             spin_mutex::scoped_lock lock(my_mutex);
             if(my_count) --my_count;
         }
         return forward_task();
     }
template<typename T > void tbb::flow::interface10::limiter_node< T >::forward () inline private
Definition at line 2490 of file flow_graph.h.
References __TBB_ASSERT.
                    {
         __TBB_ASSERT(false, "Should never be called");
         return;
     }
template<typename T > task* tbb::flow::interface10::limiter_node< T >::forward_task () inline private
Definition at line 2437 of file flow_graph.h.
References __TBB_ASSERT, internal::decrementer< T >::graph_reference(), tbb::flow::interface10::internal::is_graph_active(), lock, tbb::flow::interface10::graph_node::my_graph, tbb::flow::interface10::graph::root_task(), tbb::flow::interface10::internal::spawn_in_graph_arena(), tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::try_consume(), tbb::flow::interface10::internal::broadcast_cache< T, M >::try_put_task(), tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::try_release(), and tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::try_reserve().
{
         input_type v;
         task *rval = NULL;
         bool reserved = false;
             {
                 spin_mutex::scoped_lock lock(my_mutex);
                 if ( check_conditions() )
                     ++my_tries;
                 else
                     return NULL;
             }
         //SUCCESS
         // if we can reserve and can put, we consume the reservation
         // we increment the count and decrement the tries
         if ( (my_predecessors.try_reserve(v)) == true ){
             reserved=true;
             if ( (rval = my_successors.try_put_task(v)) != NULL ){
                 {
                     spin_mutex::scoped_lock lock(my_mutex);
                     ++my_count;
                     --my_tries;
                     my_predecessors.try_consume();
                     if ( check_conditions() ) {
                         if ( internal::is_graph_active(this->my_graph) ) {
                             task *rtask = new ( task::allocate_additional_child_of( *(this->my_graph.root_task()) ) )
                                 internal::forward_task_bypass< limiter_node<T> >( *this );
                             internal::spawn_in_graph_arena(graph_reference(), *rtask);
                         }
                     }
                 }
                 return rval;
             }
         }
         //FAILURE
         //if we can't reserve, we decrement the tries
         //if we can reserve but can't put, we decrement the tries and release the reservation
         {
             spin_mutex::scoped_lock lock(my_mutex);
             --my_tries;
             if (reserved) my_predecessors.try_release();
             if ( check_conditions() ) {
                 if ( internal::is_graph_active(this->my_graph) ) {
                     task *rtask = new ( task::allocate_additional_child_of( *(this->my_graph.root_task()) ) )
                         internal::forward_task_bypass< limiter_node<T> >( *this );
                     __TBB_ASSERT(!rval, "Have two tasks to handle");
                     return rtask;
                 }
             }
             return rval;
         }
     }
template<typename T > graph& tbb::flow::interface10::limiter_node< T >::graph_reference () inline protected virtual
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 2657 of file flow_graph.h.
References tbb::flow::interface10::graph_node::my_graph.
{
         return my_graph;
     }
template<typename T > bool tbb::flow::interface10::limiter_node< T >::register_predecessor (predecessor_type & src) inline virtual
Adds src to the list of cached predecessors.
Reimplemented from tbb::flow::interface10::internal::untyped_receiver.
Definition at line 2607 of file flow_graph.h.
References tbb::flow::interface10::internal::node_cache< untyped_sender, M >::add(), tbb::flow::interface10::internal::successor_cache< T, M >::empty(), internal::decrementer< T >::graph_reference(), tbb::flow::interface10::internal::is_graph_active(), lock, tbb::flow::interface10::graph_node::my_graph, tbb::flow::interface10::graph::root_task(), and tbb::flow::interface10::internal::spawn_in_graph_arena().
{
         spin_mutex::scoped_lock lock(my_mutex);
         my_predecessors.add( src );
         if ( my_count + my_tries < my_threshold && !my_successors.empty() && internal::is_graph_active(this->my_graph) ) {
             task* task = new ( task::allocate_additional_child_of( *(this->my_graph.root_task()) ) )
                         internal::forward_task_bypass < limiter_node<T> >( *this );
             internal::spawn_in_graph_arena(graph_reference(), *task);
         }
         return true;
     }
template<typename T > bool tbb::flow::interface10::limiter_node< T >::register_successor (successor_type & r) inline virtual
Replace the current successor with this new successor.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 2543 of file flow_graph.h.
References tbb::flow::interface10::internal::node_cache< untyped_sender, M >::empty(), tbb::flow::interface10::internal::successor_cache< T, M >::empty(), internal::decrementer< T >::graph_reference(), tbb::flow::interface10::internal::is_graph_active(), lock, tbb::flow::interface10::graph_node::my_graph, tbb::flow::interface10::internal::successor_cache< T, M >::register_successor(), tbb::flow::interface10::graph::root_task(), and tbb::flow::interface10::internal::spawn_in_graph_arena().
{
         spin_mutex::scoped_lock lock(my_mutex);
         bool was_empty = my_successors.empty();
         my_successors.register_successor(r);
         //spawn a forward task if this is the only successor
         if ( was_empty && !my_predecessors.empty() && my_count + my_tries < my_threshold ) {
             if ( internal::is_graph_active(this->my_graph) ) {
                 task* task = new ( task::allocate_additional_child_of( *(this->my_graph.root_task()) ) )
                             internal::forward_task_bypass < limiter_node<T> >( *this );
                 internal::spawn_in_graph_arena(graph_reference(), *task);
             }
         }
         return true;
     }
template<typename T > bool tbb::flow::interface10::limiter_node< T >::remove_predecessor (predecessor_type & src) inline virtual
Removes src from the list of cached predecessors.
Reimplemented from tbb::flow::interface10::internal::untyped_receiver.
Definition at line 2619 of file flow_graph.h.
References tbb::flow::interface10::internal::node_cache< untyped_sender, M >::remove().
{
         my_predecessors.remove( src );
         return true;
     }
template<typename T > bool tbb::flow::interface10::limiter_node< T >::remove_successor (successor_type & r) inline virtual
Removes a successor from this node.
r.remove_predecessor(*this) is also called.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 2560 of file flow_graph.h.
References __TBB_override, tbb::flow::interface10::internal::untyped_receiver::remove_predecessor(), and tbb::flow::interface10::internal::successor_cache< T, M >::remove_successor().
{
         r.remove_predecessor(*this);
         my_successors.remove_successor(r);
         return true;
     }
template<typename T > void tbb::flow::interface10::limiter_node< T >::reset_node (reset_flags f) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 2665 of file flow_graph.h.
References tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::clear(), tbb::flow::interface10::internal::successor_cache< T, M >::clear(), tbb::flow::interface10::internal::input_port(), tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::reset(), and tbb::flow::interface10::continue_receiver::reset_receiver().
{
         my_count = 0;
         if(f & rf_clear_edges) {
             my_predecessors.clear();
             my_successors.clear();
         }
         else
         {
             my_predecessors.reset( );
         }
         decrement.reset_receiver(f);
     }
template<typename T > void tbb::flow::interface10::limiter_node< T >::reset_receiver (reset_flags f) inline protected virtual
put receiver back in initial state
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 2661 of file flow_graph.h.
References __TBB_ASSERT.
{
         __TBB_ASSERT(false,NULL);  // should never be called
     }
template<typename T > task* tbb::flow::interface10::limiter_node< T >::try_put_task (const T & t) inline protected virtual
Puts an item to this receiver.
Implements tbb::flow::interface10::receiver< T >.
Definition at line 2630 of file flow_graph.h.
References tbb::flow::interface10::internal::is_graph_active(), lock, tbb::flow::interface10::graph_node::my_graph, tbb::flow::interface10::graph::root_task(), and tbb::flow::interface10::internal::broadcast_cache< T, M >::try_put_task().
{
         {
             spin_mutex::scoped_lock lock(my_mutex);
             if ( my_count + my_tries >= my_threshold )
                 return NULL;
             else
                 ++my_tries;
         }
         task * rtask = my_successors.try_put_task(t);
         if ( !rtask ) {  // try_put_task failed.
             spin_mutex::scoped_lock lock(my_mutex);
             --my_tries;
             if (check_conditions() && internal::is_graph_active(this->my_graph)) {
                 rtask = new ( task::allocate_additional_child_of( *(this->my_graph.root_task()) ) )
                     internal::forward_task_bypass< limiter_node<T> >( *this );
             }
         }
         else {
             spin_mutex::scoped_lock lock(my_mutex);
             ++my_count;
             --my_tries;
              }
         return rtask;
     }
Friends And Related Function Documentation
template<typename T > template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 2627 of file flow_graph.h.
template<typename T > friend class internal::decrementer< limiter_node< T > > friend
Definition at line 2430 of file flow_graph.h.
template<typename T > friend class internal::forward_task_bypass< limiter_node< T > > friend
Definition at line 2427 of file flow_graph.h.
template<typename T > template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 2628 of file flow_graph.h.
template<typename T > template<typename R , typename B > friend class run_and_put_task friend
Definition at line 2626 of file flow_graph.h.
Member Data Documentation
template<typename T > internal::decrementer< limiter_node<T> > tbb::flow::interface10::limiter_node< T >::decrement
The internal receiver< continue_msg > that decrements the count.
Definition at line 2505 of file flow_graph.h.
template<typename T > int tbb::flow::interface10::limiter_node< T >::init_decrement_predecessors private
Definition at line 2425 of file flow_graph.h.
template<typename T > size_t tbb::flow::interface10::limiter_node< T >::my_count private
Definition at line 2420 of file flow_graph.h.
template<typename T > spin_mutex tbb::flow::interface10::limiter_node< T >::my_mutex private
Definition at line 2423 of file flow_graph.h.
template<typename T > internal::reservable_predecessor_cache< T, spin_mutex > tbb::flow::interface10::limiter_node< T >::my_predecessors private
Definition at line 2422 of file flow_graph.h.
template<typename T > internal::broadcast_cache< T > tbb::flow::interface10::limiter_node< T >::my_successors private
Definition at line 2424 of file flow_graph.h.
template<typename T > size_t tbb::flow::interface10::limiter_node< T >::my_threshold private
Definition at line 2419 of file flow_graph.h.
template<typename T > size_t tbb::flow::interface10::limiter_node< T >::my_tries private
Definition at line 2421 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.