Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::mail_outbox Class Reference
tbb::internal::mail_outbox Class Reference
Class representing where mail is put.
#include <mailbox.h>
Public Member Functions
void push (task_proxy *t)
Push task_proxy onto the mailbox queue of another thread.
bool empty ()
Return true if mailbox is empty.
void construct ()
Construct *this as a mailbox from zeroed memory.
intptr_t drain ()
Drain the mailbox.
bool recipient_is_idle ()
True if thread that owns this mailbox is looking for work.
Private Member Functions
task_proxy * internal_pop (__TBB_ISOLATION_EXPR(isolation_tag isolation))
Friends
class mail_inbox
Additional Inherited Members
Private Types inherited from tbb::internal::unpadded_mail_outbox
typedef task_proxy *__TBB_atomic proxy_ptr
Private Attributes inherited from tbb::internal::padded_base< unpadded_mail_outbox, NFS_MaxLineSize, sizeof(unpadded_mail_outbox)%NFS_MaxLineSize >
char pad [S-R]
Private Attributes inherited from tbb::internal::unpadded_mail_outbox
proxy_ptr my_first
Pointer to first task_proxy in mailbox, or NULL if box is empty.
proxy_ptr *__TBB_atomic my_last
Pointer to pointer that will point to next item in the queue. Never NULL.
bool my_is_idle
Owner of mailbox is not executing a task, and has drained its own task pool.
Detailed Description
Class representing where mail is put.
Padded to occupy a cache line.
Definition at line 100 of file mailbox.h.
Member Function Documentation
void tbb::internal::mail_outbox::construct () inline
Construct *this as a mailbox from zeroed memory.
Raise assertion if *this is not previously zeroed, or sizeof(this) is wrong. This method is provided instead of a full constructor since we know the object will be constructed in zeroed memory.
Definition at line 162 of file mailbox.h.
References __TBB_ASSERT, tbb::internal::NFS_MaxLineSize, and tbb::internal::suppress_unused_warning().
                      {
         __TBB_ASSERT( sizeof(*this)==NFS_MaxLineSize, NULL );
         __TBB_ASSERT( !my_first, NULL );
         __TBB_ASSERT( !my_last, NULL );
         __TBB_ASSERT( !my_is_idle, NULL );
         my_last=&my_first;
         suppress_unused_warning(pad);
     }
intptr_t tbb::internal::mail_outbox::drain () inline
Drain the mailbox.
Definition at line 172 of file mailbox.h.
References tbb::internal::task_proxy::next_in_mailbox, tbb::internal::NFS_Free(), and tbb::internal::task_prefix_reservation_size.
                      {
         intptr_t k = 0;
         // No fences here because other threads have already quit.
         for( ; task_proxy* t = my_first; ++k ) {
             my_first = t->next_in_mailbox;
             NFS_Free((char*)t - task_prefix_reservation_size);
         }
         return k;
     }
bool tbb::internal::mail_outbox::empty () inline
Return true if mailbox is empty.
Definition at line 154 of file mailbox.h.
References tbb::internal::__TBB_load_relaxed().
Referenced by tbb::internal::mail_inbox::empty().
                  {
         return __TBB_load_relaxed(my_first) == NULL;
     }
task_proxy* tbb::internal::mail_outbox::internal_pop (__TBB_ISOLATION_EXPR(isolation_tag isolation)) inline private
Definition at line 102 of file mailbox.h.
References __TBB_ASSERT, __TBB_control_consistency_helper, tbb::internal::__TBB_load_relaxed(), tbb::internal::as_atomic(), tbb::internal::task_proxy::next_in_mailbox, tbb::internal::no_isolation, and tbb::internal::atomic_backoff::pause().
Referenced by tbb::internal::mail_inbox::pop().
{
         task_proxy* curr = __TBB_load_relaxed( my_first );
         if ( !curr )
             return NULL;
         task_proxy **prev_ptr = &my_first;
 #if __TBB_TASK_ISOLATION
         if ( isolation != no_isolation ) {
             while ( curr->prefix().isolation != isolation ) {
                 prev_ptr = &curr->next_in_mailbox;
                 curr = curr->next_in_mailbox;
                 if ( !curr )
                     return NULL;
             }
         }
 #endif /* __TBB_TASK_ISOLATION */
         __TBB_control_consistency_helper(); // on my_first
         // There is a first item in the mailbox.  See if there is a second.
         if ( task_proxy* second = curr->next_in_mailbox ) {
             // There are at least two items, so first item can be popped easily.
             *prev_ptr = second;
         } else {
             // There is only one item.  Some care is required to pop it.
             *prev_ptr = NULL;
             if ( as_atomic( my_last ).compare_and_swap( prev_ptr, &curr->next_in_mailbox ) == &curr->next_in_mailbox ) {
                 // Successfully transitioned mailbox from having one item to having none.
                 __TBB_ASSERT( !curr->next_in_mailbox, NULL );
             } else {
                 // Some other thread updated my_last but has not filled in first->next_in_mailbox
                 // Wait until first item points to second item.
                 atomic_backoff backoff;
                 while ( !(second = curr->next_in_mailbox) ) backoff.pause();
                 *prev_ptr = second;
             }
         }
         __TBB_ASSERT( curr, NULL );
         return curr;
     }
void tbb::internal::mail_outbox::push (task_proxy * t) inline
Push task_proxy onto the mailbox queue of another thread.
Implementation is wait-free.
Definition at line 144 of file mailbox.h.
References __TBB_ASSERT, tbb::internal::__TBB_store_relaxed(), and tbb::internal::task_proxy::next_in_mailbox.
Referenced by tbb::internal::generic_scheduler::prepare_for_spawning().
{
         __TBB_ASSERT(t, NULL);
         t->next_in_mailbox = NULL;
         proxy_ptr * const link = (proxy_ptr *)__TBB_FetchAndStoreW(&my_last,(intptr_t)&t->next_in_mailbox);
         // No release fence required for the next store, because there are no memory operations
         // between the previous fully fenced atomic operation and the store.
         __TBB_store_relaxed(*link, t);
     }
bool tbb::internal::mail_outbox::recipient_is_idle () inline
True if thread that owns this mailbox is looking for work.
Definition at line 183 of file mailbox.h.
Referenced by tbb::internal::generic_scheduler::steal_task_from().
{
         return my_is_idle;
     }
Friends And Related Function Documentation
friend class mail_inbox friend
Definition at line 140 of file mailbox.h.
The documentation for this class was generated from the following file:
mailbox.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.