Intel(R) Threading Building Blocks Doxygen Documentation: tbb::parallel_while< Body > Class Template Reference
tbb::parallel_while< Body > Class Template Reference
Algorithms
Parallel iteration over a stream, with optional addition of more work.
#include <parallel_while.h>
Public Types
typedef Body::argument_type value_type
Type of items.
Public Member Functions
parallel_while ()
Construct empty non-running parallel while.
~parallel_while ()
Destructor cleans up data members before returning.
template<typename Stream >
void run (Stream &stream, const Body &body)
Apply body.apply to each item in the stream.
void add (const value_type &item)
Add a work item while running.
Private Attributes
const Body * my_body
empty_task * my_barrier
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
template<typename Body>
class tbb::parallel_while< Body >
Parallel iteration over a stream, with optional addition of more work.
The Body b has the requirement:
"b(v)"
"b.argument_type"
where v is an argument_type
Definition at line 30 of file parallel_while.h.
Member Typedef Documentation
template<typename Body > typedef Body::argument_type tbb::parallel_while< Body >::value_type
Type of items.
Definition at line 143 of file parallel_while.h.
Constructor & Destructor Documentation
template<typename Body > tbb::parallel_while< Body >::parallel_while () inline
Construct empty non-running parallel while.
Definition at line 132 of file parallel_while.h.
 : my_body(NULL), my_barrier(NULL) {}
template<typename Body > tbb::parallel_while< Body >::~parallel_while () inline
Destructor cleans up data members before returning.
Definition at line 135 of file parallel_while.h.
                       {
         if( my_barrier ) {
             my_barrier->destroy(*my_barrier);
             my_barrier = NULL;
         }
     }
Member Function Documentation
template<typename Body > void tbb::parallel_while< Body >::add (const value_type & item)
Add a work item while running.
Should be executed only by body.apply or a thread spawned therefrom.
Definition at line 177 of file parallel_while.h.
References __TBB_ASSERT, tbb::internal::while_iteration_task< Body >::my_body, and tbb::task::self().
{
     __TBB_ASSERT(my_barrier,"attempt to add to parallel_while that is not running");
     typedef internal::while_iteration_task<Body> iteration_type;
     iteration_type& i = *new( task::allocate_additional_child_of(*my_barrier) ) iteration_type(item,*my_body);
     task::self().spawn( i );
 }
template<typename Body > template<typename Stream > void tbb::parallel_while< Body >::run (Stream & stream, const Body & body)
Apply body.apply to each item in the stream.
A Stream s has the requirements
"S::value_type"
"s.pop_if_present(value) is convertible to bool
Definition at line 163 of file parallel_while.h.
References tbb::task::allocate_root(), tbb::internal::while_iteration_task< Body >::my_body, tbb::task::set_ref_count(), and tbb::task::spawn_and_wait_for_all().
{
     using namespace internal;
     empty_task& barrier = *new( task::allocate_root() ) empty_task();
     my_body = &body;
     my_barrier = &barrier;
     my_barrier->set_ref_count(2);
     while_task<Stream,Body>& w = *new( my_barrier->allocate_child() ) while_task<Stream,Body>( stream, body, barrier );
     my_barrier->spawn_and_wait_for_all(w);
     my_barrier->destroy(*my_barrier);
     my_barrier = NULL;
     my_body = NULL;
 }
Member Data Documentation
template<typename Body > empty_task* tbb::parallel_while< Body >::my_barrier private
Definition at line 158 of file parallel_while.h.
template<typename Body > const Body* tbb::parallel_while< Body >::my_body private
Definition at line 157 of file parallel_while.h.
The documentation for this class was generated from the following file:
parallel_while.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.