Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_device_list Class Reference
tbb::flow::interface10::opencl_device_list Class Reference
#include <flow_graph_opencl_node.h>
Public Types
typedef container_type::iterator iterator
typedef container_type::const_iterator const_iterator
typedef container_type::size_type size_type
Public Member Functions
opencl_device_list ()
opencl_device_list (std::initializer_list< opencl_device > il)
void add (opencl_device d)
size_type size () const
bool empty () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
Private Types
typedef std::vector< opencl_device > container_type
Private Attributes
container_type my_container
Detailed Description
Definition at line 257 of file flow_graph_opencl_node.h.
Member Typedef Documentation
typedef container_type::const_iterator tbb::flow::interface10::opencl_device_list::const_iterator
Definition at line 261 of file flow_graph_opencl_node.h.
typedef std::vector<opencl_device> tbb::flow::interface10::opencl_device_list::container_type private
Definition at line 258 of file flow_graph_opencl_node.h.
typedef container_type::iterator tbb::flow::interface10::opencl_device_list::iterator
Definition at line 260 of file flow_graph_opencl_node.h.
typedef container_type::size_type tbb::flow::interface10::opencl_device_list::size_type
Definition at line 262 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
tbb::flow::interface10::opencl_device_list::opencl_device_list () inline
Definition at line 264 of file flow_graph_opencl_node.h.
 {}
tbb::flow::interface10::opencl_device_list::opencl_device_list (std::initializer_list< opencl_device > il) inline
Definition at line 265 of file flow_graph_opencl_node.h.
 : my_container( il ) {}
Member Function Documentation
void tbb::flow::interface10::opencl_device_list::add (opencl_device d) inline
Definition at line 267 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::internal::find_available_devices(), and tbb::flow::interface10::opencl_info::default_device_filter::operator()().
 { my_container.push_back( d ); }
iterator tbb::flow::interface10::opencl_device_list::begin () inline
Definition at line 270 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder::opencl_program_builder(), and tbb::flow::interface10::opencl_info::default_device_filter::operator()().
 { return my_container.begin(); }
const_iterator tbb::flow::interface10::opencl_device_list::begin () const inline
Definition at line 272 of file flow_graph_opencl_node.h.
 { return my_container.begin(); }
const_iterator tbb::flow::interface10::opencl_device_list::cbegin () const inline
Definition at line 274 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_info::default_device_filter::operator()().
 { return my_container.cbegin(); }
const_iterator tbb::flow::interface10::opencl_device_list::cend () const inline
Definition at line 275 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_info::default_device_filter::operator()().
 { return my_container.cend(); }
bool tbb::flow::interface10::opencl_device_list::empty () const inline
Definition at line 269 of file flow_graph_opencl_node.h.
 { return my_container.empty(); }
iterator tbb::flow::interface10::opencl_device_list::end () inline
Definition at line 271 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder::opencl_program_builder().
 { return my_container.end(); }
const_iterator tbb::flow::interface10::opencl_device_list::end () const inline
Definition at line 273 of file flow_graph_opencl_node.h.
 { return my_container.end(); }
size_type tbb::flow::interface10::opencl_device_list::size () const inline
Definition at line 268 of file flow_graph_opencl_node.h.
 { return my_container.size(); }
Member Data Documentation
container_type tbb::flow::interface10::opencl_device_list::my_container private
Definition at line 278 of file flow_graph_opencl_node.h.
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.