Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory > Class Template Reference
tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory > Class Template Reference
#include <flow_graph_opencl_node.h>
Public Types
typedef base_type::kernel_type kernel_type
Public Member Functions
opencl_node (graph &g, const kernel_type &kernel)
opencl_node (graph &g, const kernel_type &kernel, Factory &f)
template<typename DeviceSelector >
opencl_node (graph &g, const kernel_type &kernel, DeviceSelector d, Factory &f)
Private Types
typedef streaming_node< tuple< Ports... >, JP, Factory > base_type
Detailed Description
template<typename JP, typename Factory, typename... Ports>
class tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory >
Definition at line 1409 of file flow_graph_opencl_node.h.
Member Typedef Documentation
template<typename JP , typename Factory , typename... Ports> typedef streaming_node< tuple<Ports...>, JP, Factory > tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory >::base_type private
Definition at line 1410 of file flow_graph_opencl_node.h.
template<typename JP , typename Factory , typename... Ports> typedef base_type::kernel_type tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory >::kernel_type
Definition at line 1412 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename JP , typename Factory , typename... Ports> tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory >::opencl_node (graph & g, const kernel_type & kernel) inline
Definition at line 1414 of file flow_graph_opencl_node.h.
References tbb::internal::fgt_multiinput_multioutput_node().
         : base_type( g, kernel, opencl_info::default_device_selector< opencl_info::default_opencl_factory >(), opencl_info::default_factory() )
     {
         tbb::internal::fgt_multiinput_multioutput_node( tbb::internal::FLOW_OPENCL_NODE, this, &this->my_graph );
     }
template<typename JP , typename Factory , typename... Ports> tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory >::opencl_node (graph & g, const kernel_type & kernel, Factory & f) inline
Definition at line 1420 of file flow_graph_opencl_node.h.
References tbb::internal::fgt_multiinput_multioutput_node().
         : base_type( g, kernel, opencl_info::default_device_selector <Factory >(), f )
     {
         tbb::internal::fgt_multiinput_multioutput_node( tbb::internal::FLOW_OPENCL_NODE, this, &this->my_graph );
     }
template<typename JP , typename Factory , typename... Ports> template<typename DeviceSelector > tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory >::opencl_node (graph & g, const kernel_type & kernel, DeviceSelector d, Factory & f) inline
Definition at line 1427 of file flow_graph_opencl_node.h.
References tbb::internal::fgt_multiinput_multioutput_node().
         : base_type( g, kernel, d, f)
     {
         tbb::internal::fgt_multiinput_multioutput_node( tbb::internal::FLOW_OPENCL_NODE, this, &this->my_graph );
     }
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.