Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::nested_arena_context Class Reference
tbb::internal::nested_arena_context Class Reference
Public Member Functions
nested_arena_context (generic_scheduler *s, arena *a, size_t slot_index, bool type, bool same)
~nested_arena_context ()
Private Member Functions
void mimic_outermost_level (arena *a, bool type)
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
generic_scheduler & my_scheduler
scheduler_state my_orig_state
task_group_context * my_orig_ctx
const bool same_arena
Detailed Description
Definition at line 627 of file arena.cpp.
Constructor & Destructor Documentation
tbb::internal::nested_arena_context::nested_arena_context (generic_scheduler * s, arena * a, size_t slot_index, bool type, bool same) inline
Definition at line 629 of file arena.cpp.
References tbb::internal::generic_scheduler::nested_arena_entry(), and s.
         : my_scheduler(*s), my_orig_ctx(NULL), same_arena(same) {
         if (same_arena) {
             my_orig_state.my_properties = my_scheduler.my_properties;
             my_orig_state.my_innermost_running_task = my_scheduler.my_innermost_running_task;
             mimic_outermost_level(a, type);
         } else {
             my_orig_state = *s;
             mimic_outermost_level(a, type);
             s->nested_arena_entry(a, slot_index);
         }
     }
tbb::internal::nested_arena_context::~nested_arena_context () inline
Definition at line 641 of file arena.cpp.
References tbb::internal::governor::assume_scheduler().
{
 #if __TBB_TASK_GROUP_CONTEXT
         my_scheduler.my_dummy_task->prefix().context = my_orig_ctx; // restore context of dummy task
 #endif
         if (same_arena) {
             my_scheduler.my_properties = my_orig_state.my_properties;
             my_scheduler.my_innermost_running_task = my_orig_state.my_innermost_running_task;
         } else {
             my_scheduler.nested_arena_exit();
             static_cast<scheduler_state&>(my_scheduler) = my_orig_state; // restore arena settings
 #if __TBB_TASK_PRIORITY
             my_scheduler.my_local_reload_epoch = *my_orig_state.my_ref_reload_epoch;
 #endif
             governor::assume_scheduler(&my_scheduler);
         }
     }
Member Function Documentation
void tbb::internal::nested_arena_context::mimic_outermost_level (arena * a, bool type) inline private
Definition at line 664 of file arena.cpp.
References tbb::internal::generic_scheduler::my_dummy_task, tbb::internal::scheduler_state::my_innermost_running_task, tbb::internal::scheduler_state::my_properties, tbb::internal::scheduler_properties::outermost, tbb::task::prefix(), tbb::internal::scheduler_properties::type, and type.
{
         my_scheduler.my_properties.outermost = true;
         my_scheduler.my_properties.type = type;
         my_scheduler.my_innermost_running_task = my_scheduler.my_dummy_task;
 #if __TBB_PREVIEW_CRITICAL_TASKS
         my_scheduler.my_properties.has_taken_critical_task = false;
 #endif
 #if __TBB_TASK_GROUP_CONTEXT
         // Save dummy's context and replace it by arena's context
         my_orig_ctx = my_scheduler.my_dummy_task->prefix().context;
         my_scheduler.my_dummy_task->prefix().context = a->my_default_ctx;
 #endif
     }
Member Data Documentation
task_group_context* tbb::internal::nested_arena_context::my_orig_ctx private
Definition at line 661 of file arena.cpp.
scheduler_state tbb::internal::nested_arena_context::my_orig_state private
Definition at line 660 of file arena.cpp.
generic_scheduler& tbb::internal::nested_arena_context::my_scheduler private
Definition at line 659 of file arena.cpp.
const bool tbb::internal::nested_arena_context::same_arena private
Definition at line 662 of file arena.cpp.
The documentation for this class was generated from the following file:
arena.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.