Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::parallel_do_feeder_impl< Body, Item > Class Template Reference
tbb::interface9::internal::parallel_do_feeder_impl< Body, Item > Class Template Reference
Algorithms
For internal use only.
#include <parallel_do.h>
Public Member Functions
parallel_do_feeder_impl ()
parallel_do_feeder_impl (tbb::task_group_context &context)
~parallel_do_feeder_impl ()
Public Member Functions inherited from tbb::interface9::parallel_do_feeder< Item >
void add (const Item &item)
Add a work item to a running parallel_do.
void add (Item &&item)
Public Attributes
const Body * my_body
empty_task * my_barrier
Private Member Functions
void internal_add_copy_impl (std::true_type, const Item &item)
void internal_add_copy_impl (std::false_type, const Item &)
void internal_add_copy (const Item &item) __TBB_override
void internal_add_move (Item &&item) __TBB_override
Detailed Description
template<class Body, typename Item>
class tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >
For internal use only.
Implements new task adding procedure.
Definition at line 34 of file parallel_do.h.
Constructor & Destructor Documentation
template<class Body, typename Item> tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::parallel_do_feeder_impl () inline
Definition at line 187 of file parallel_do.h.
References __TBB_ASSERT, and tbb::task::allocate_root().
         {
             my_barrier = new( task::allocate_root() ) empty_task();
             __TBB_ASSERT(my_barrier, "root task allocation failed");
         }
template<class Body, typename Item> tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::parallel_do_feeder_impl (tbb::task_group_context & context) inline
Definition at line 194 of file parallel_do.h.
References __TBB_ASSERT, and tbb::task::allocate_root().
         {
             my_barrier = new( task::allocate_root(context) ) empty_task();
             __TBB_ASSERT(my_barrier, "root task allocation failed");
         }
template<class Body, typename Item> tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::~parallel_do_feeder_impl () inline
Definition at line 201 of file parallel_do.h.
         {
             my_barrier->destroy(*my_barrier);
         }
Member Function Documentation
template<class Body, typename Item> void tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::internal_add_copy (const Item & item) inline private virtual
Implements tbb::interface9::parallel_do_feeder< Item >.
Definition at line 162 of file parallel_do.h.
References type.
         {
 #if __TBB_CPP11_IS_COPY_CONSTRUCTIBLE_PRESENT
             internal_add_copy_impl(typename std::is_copy_constructible<Item>::type(), item);
 #else
             internal_add_copy_impl(std::true_type(), item);
 #endif
         }
template<class Body, typename Item> void tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::internal_add_copy_impl (std::true_type , const Item & item) inline private
Definition at line 154 of file parallel_do.h.
{
             typedef do_iteration_task<Body, Item> iteration_type;
             iteration_type& t = *new (task::allocate_additional_child_of(*my_barrier)) iteration_type(item, *this);
             task::spawn(t);
         }
template<class Body, typename Item> void tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::internal_add_copy_impl (std::false_type , const Item &) inline private
Definition at line 159 of file parallel_do.h.
References __TBB_ASSERT.
{
             __TBB_ASSERT(false, "Overloading for r-value reference doesn't work or it's not movable and not copyable object");
         }
template<class Body, typename Item> void tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::internal_add_move (Item && item) inline private virtual
Implements tbb::interface9::parallel_do_feeder< Item >.
Definition at line 170 of file parallel_do.h.
References __TBB_override, and tbb::move().
         {
             typedef do_iteration_task<Body, Item> iteration_type;
             iteration_type& t = *new (task::allocate_additional_child_of(*my_barrier)) iteration_type(std::move(item), *this);
             task::spawn(t);
         }
Member Data Documentation
template<class Body, typename Item> empty_task* tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::my_barrier
Definition at line 185 of file parallel_do.h.
Referenced by tbb::interface9::internal::do_task_iter< Iterator, Body, Item >::run_for_forward_iterator(), tbb::interface9::internal::do_task_iter< Iterator, Body, Item >::run_for_input_iterator(), and tbb::interface9::internal::run_parallel_do().
template<class Body, typename Item> const Body* tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::my_body
Definition at line 184 of file parallel_do.h.
Referenced by tbb::interface9::internal::do_iteration_task< Body, Item >::execute(), tbb::interface9::internal::do_iteration_task_iter< Iterator, Body, Item >::execute(), and tbb::interface9::internal::run_parallel_do().
The documentation for this class was generated from the following file:
parallel_do.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.