Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10a::overwrite_node< T > Class Template Reference
tbb::flow::interface10a::overwrite_node< T > Class Template Reference
#include <flow_graph.h>
Classes
struct register_predecessor_task
Breaks an infinite loop between the node reservation and register_successor call.
Public Types
typedef T input_type
typedef T output_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
Public Types inherited from tbb::flow::interface10::receiver< T >
typedef T input_type
The input type of this receiver.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::sender< T >
typedef T output_type
The output type of this sender.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
overwrite_node (graph &g)
overwrite_node (const overwrite_node &src)
Copy constructor; doesn't take anything from src; default won't work.
~overwrite_node ()
bool register_successor (successor_type &s) __TBB_override
Add a new successor to this node.
bool remove_successor (successor_type &s) __TBB_override
Removes a successor from this node.
bool try_get (input_type &v) __TBB_override
Request an item from the sender.
bool try_reserve (T &v) __TBB_override
Reserves an item.
bool try_release () __TBB_override
Releases the reserved item.
bool try_consume () __TBB_override
Consumes the reserved item.
bool is_valid ()
void clear ()
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::receiver< T >
bool try_put (const typename internal::async_helpers< T >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< T >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
virtual bool register_predecessor (predecessor_type &)
Add a predecessor to the node.
virtual bool remove_predecessor (predecessor_type &)
Remove a predecessor from the node.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
Protected Member Functions
task * try_put_task (const input_type &v) __TBB_override
Put item to successor; return task to run the successor if possible.
task * try_put_task_impl (const input_type &v)
graph & graph_reference () __TBB_override
void reset_receiver (reset_flags) __TBB_override
put receiver back in initial state
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::receiver< T >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Protected Member Functions inherited from tbb::flow::interface10::sender< T >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Protected Attributes
spin_mutex my_mutex
internal::broadcast_cache< input_type, null_rw_mutex > my_successors
input_type my_buffer
bool my_buffer_is_valid
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Friends
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Detailed Description
template<typename T>
class tbb::flow::interface10a::overwrite_node< T >
Definition at line 3656 of file flow_graph.h.
Member Typedef Documentation
template<typename T > typedef T tbb::flow::interface10a::overwrite_node< T >::input_type
Definition at line 3658 of file flow_graph.h.
template<typename T > typedef T tbb::flow::interface10a::overwrite_node< T >::output_type
Definition at line 3659 of file flow_graph.h.
template<typename T > typedef receiver<input_type>::predecessor_type tbb::flow::interface10a::overwrite_node< T >::predecessor_type
Definition at line 3660 of file flow_graph.h.
template<typename T > typedef sender<output_type>::successor_type tbb::flow::interface10a::overwrite_node< T >::successor_type
Definition at line 3661 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T > tbb::flow::interface10a::overwrite_node< T >::overwrite_node (graph & g) inline explicit
Definition at line 3669 of file flow_graph.h.
References tbb::internal::fgt_node(), tbb::flow::interface10::graph_node::my_graph, and tbb::flow::interface10::internal::successor_cache< T, M >::set_owner().
                                       : graph_node(g), my_buffer_is_valid(false) {
         my_successors.set_owner( this );
         tbb::internal::fgt_node( tbb::internal::FLOW_OVERWRITE_NODE, &this->my_graph,
                                  static_cast<receiver<input_type> *>(this), static_cast<sender<output_type> *>(this) );
     }
template<typename T > tbb::flow::interface10a::overwrite_node< T >::overwrite_node (const overwrite_node< T > & src) inline
Copy constructor; doesn't take anything from src; default won't work.
Definition at line 3676 of file flow_graph.h.
References tbb::internal::fgt_node(), tbb::flow::interface10::graph_node::my_graph, and tbb::flow::interface10::internal::successor_cache< T, M >::set_owner().
                                                 :
         graph_node(src.my_graph), receiver<T>(), sender<T>(), my_buffer_is_valid(false)
     {
         my_successors.set_owner( this );
         tbb::internal::fgt_node( tbb::internal::FLOW_OVERWRITE_NODE, &this->my_graph,
                                  static_cast<receiver<input_type> *>(this), static_cast<sender<output_type> *>(this) );
     }
template<typename T > tbb::flow::interface10a::overwrite_node< T >::~overwrite_node () inline
Definition at line 3684 of file flow_graph.h.
References __TBB_override, and tbb::internal::fgt_node_desc().
 {}
Member Function Documentation
template<typename T > void tbb::flow::interface10a::overwrite_node< T >::clear () inline
Definition at line 3799 of file flow_graph.h.
                  {
        spin_mutex::scoped_lock l( my_mutex );
        my_buffer_is_valid = false;
     }
template<typename T > graph& tbb::flow::interface10a::overwrite_node< T >::graph_reference () inline protected virtual
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 3822 of file flow_graph.h.
References tbb::flow::interface10::graph_node::my_graph.
{
         return my_graph;
     }
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::is_valid () inline
Definition at line 3794 of file flow_graph.h.
                     {
        spin_mutex::scoped_lock l( my_mutex );
        return my_buffer_is_valid;
     }
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::register_successor (successor_type & r) inline virtual
Add a new successor to this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 3692 of file flow_graph.h.
References tbb::flow::interface10::internal::is_graph_active(), tbb::flow::interface10::graph_node::my_graph, tbb::flow::interface10::internal::successor_cache< T, M >::register_successor(), tbb::flow::interface10::graph::root_task(), and tbb::flow::interface10::internal::spawn_in_graph_arena().
{
         spin_mutex::scoped_lock l( my_mutex );
         if (my_buffer_is_valid && internal::is_graph_active( my_graph )) {
             // We have a valid value that must be forwarded immediately.
             bool ret = s.try_put( my_buffer );
             if ( ret ) {
                 // We add the successor that accepted our put
                 my_successors.register_successor( s );
             } else {
                 // In case of reservation a race between the moment of reservation and register_successor can appear,
                 // because failed reserve does not mean that register_successor is not ready to put a message immediately.
                 // We have some sort of infinite loop: reserving node tries to set pull state for the edge,
                 // but overwrite_node tries to return push state back. That is why we have to break this loop with task creation.
                 task *rtask = new ( task::allocate_additional_child_of( *( my_graph.root_task() ) ) )
                     register_predecessor_task( *this, s );
                 internal::spawn_in_graph_arena( my_graph, *rtask );
             }
         } else {
             // No valid value yet, just add as successor
             my_successors.register_successor( s );
         }
         return true;
     }
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::remove_successor (successor_type & r) inline virtual
Removes a successor from this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 3716 of file flow_graph.h.
References __TBB_override, and tbb::flow::interface10::internal::successor_cache< T, M >::remove_successor().
{
         spin_mutex::scoped_lock l( my_mutex );
         my_successors.remove_successor(s);
         return true;
     }
template<typename T > void tbb::flow::interface10a::overwrite_node< T >::reset_node (reset_flags f) inline protected virtual
Implements tbb::flow::interface10::graph_node.
Definition at line 3852 of file flow_graph.h.
References tbb::flow::interface10::internal::successor_cache< T, M >::clear().
{
         my_buffer_is_valid = false;
        if (f&rf_clear_edges) {
            my_successors.clear();
        }
     }
template<typename T > void tbb::flow::interface10a::overwrite_node< T >::reset_receiver (reset_flags f) inline protected virtual
put receiver back in initial state
Implements tbb::flow::interface10::internal::untyped_receiver.
Definition at line 3850 of file flow_graph.h.
 {}
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::try_consume () inline virtual
Consumes the reserved item.
Reimplemented from tbb::flow::interface10::internal::untyped_sender.
Definition at line 3792 of file flow_graph.h.
 { return true; }
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::try_get (input_type &) inline virtual
Request an item from the sender.
Reimplemented from tbb::flow::interface10::sender< T >.
Definition at line 3774 of file flow_graph.h.
{
         spin_mutex::scoped_lock l( my_mutex );
         if ( my_buffer_is_valid ) {
             v = my_buffer;
             return true;
         }
         return false;
     }
template<typename T > task* tbb::flow::interface10a::overwrite_node< T >::try_put_task (const input_type & t) inline protected virtual
Put item to successor; return task to run the successor if possible.
Implements tbb::flow::interface10::receiver< T >.
Reimplemented in tbb::flow::interface10a::write_once_node< T >.
Definition at line 3809 of file flow_graph.h.
{
         spin_mutex::scoped_lock l( my_mutex );
         return try_put_task_impl(v);
     }
template<typename T > task* tbb::flow::interface10a::overwrite_node< T >::try_put_task_impl (const input_type & v) inline protected
Definition at line 3814 of file flow_graph.h.
References tbb::flow::internal::SUCCESSFULLY_ENQUEUED, and tbb::flow::interface10::internal::round_robin_cache< T, M >::try_put_task().
{
         my_buffer = v;
         my_buffer_is_valid = true;
         task * rtask = my_successors.try_put_task(v);
         if (!rtask) rtask = SUCCESSFULLY_ENQUEUED;
         return rtask;
     }
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::try_release () inline virtual
Releases the reserved item.
Reimplemented from tbb::flow::interface10::internal::untyped_sender.
Definition at line 3789 of file flow_graph.h.
 { return true; }
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::try_reserve (T & v) inline virtual
Reserves an item.
Reimplemented from tbb::flow::interface10::sender< T >.
Definition at line 3784 of file flow_graph.h.
{
         return try_get(v);
     }
Friends And Related Function Documentation
template<typename T > template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 3807 of file flow_graph.h.
template<typename T > template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 3808 of file flow_graph.h.
template<typename T > template<typename R , typename B > friend class run_and_put_task friend
Definition at line 3806 of file flow_graph.h.
Member Data Documentation
template<typename T > input_type tbb::flow::interface10a::overwrite_node< T >::my_buffer protected
Definition at line 3848 of file flow_graph.h.
template<typename T > bool tbb::flow::interface10a::overwrite_node< T >::my_buffer_is_valid protected
Definition at line 3849 of file flow_graph.h.
template<typename T > spin_mutex tbb::flow::interface10a::overwrite_node< T >::my_mutex protected
Definition at line 3843 of file flow_graph.h.
template<typename T > internal::broadcast_cache< input_type, null_rw_mutex > tbb::flow::interface10a::overwrite_node< T >::my_successors protected
Definition at line 3844 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.