Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_async_msg< T, Factory > Class Template Reference
tbb::flow::interface10::opencl_async_msg< T, Factory > Class Template Reference
#include <flow_graph_opencl_node.h>
Public Types
typedef T value_type
Public Types inherited from tbb::flow::interface10::async_msg< T >
typedef T async_msg_data_type
Public Member Functions
opencl_async_msg ()
opencl_async_msg (const T &data)
opencl_async_msg (const T &data, cl_event event)
T & data (bool wait=true)
const T & data (bool wait=true) const
opencl_async_msg (const opencl_async_msg &dmsg)
opencl_async_msg (opencl_async_msg &&dmsg)
opencl_async_msg & operator= (const opencl_async_msg &dmsg)
~opencl_async_msg ()
cl_event const * get_event () const
void set_event (cl_event e) const
void clear_event () const
template<typename Callback >
void register_callback (Callback c) const
operator T & ()
operator const T & () const
Public Member Functions inherited from tbb::flow::interface10::async_msg< T >
async_msg ()
async_msg (const T &t)
async_msg (T &&t)
virtual ~async_msg ()
void set (const T &t)
void set (T &&t)
Protected Member Functions
void finalize () const __TBB_override
Static Private Member Functions
static void CL_CALLBACK register_callback_func (cl_event, cl_int event_command_exec_status, void *data)
Private Attributes
T my_data
cl_event my_event
bool my_is_event = false
std::shared_ptr< tbb::atomic< bool > > my_callback_flag_ptr
Detailed Description
template<typename T, typename Factory = opencl_info::default_opencl_factory>
class tbb::flow::interface10::opencl_async_msg< T, Factory >
Definition at line 355 of file flow_graph_opencl_node.h.
Member Typedef Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> typedef T tbb::flow::interface10::opencl_async_msg< T, Factory >::value_type
Definition at line 357 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::opencl_async_msg () inline
Definition at line 359 of file flow_graph_opencl_node.h.
References tbb::relaxed.
                        : my_callback_flag_ptr( std::make_shared< tbb::atomic<bool>>() ) {
         my_callback_flag_ptr->store<tbb::relaxed>(false);
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::opencl_async_msg (const T & data) inline explicit
Definition at line 363 of file flow_graph_opencl_node.h.
References tbb::relaxed.
                                                : my_data(data), my_callback_flag_ptr( std::make_shared<tbb::atomic<bool>>() ) {
         my_callback_flag_ptr->store<tbb::relaxed>(false);
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::opencl_async_msg (const T & data, cl_event event) inline
Definition at line 367 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode(), and tbb::relaxed.
                                                       : my_data(data), my_event(event), my_is_event(true), my_callback_flag_ptr( std::make_shared<tbb::atomic<bool>>() ) {
         my_callback_flag_ptr->store<tbb::relaxed>(false);
         enforce_cl_retcode( clRetainEvent( my_event ), "Failed to retain an event" );
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::opencl_async_msg (const opencl_async_msg< T, Factory > & dmsg) inline
Definition at line 390 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
                                                      : async_msg<T>(dmsg),
         my_data(dmsg.my_data), my_event(dmsg.my_event), my_is_event( dmsg.my_is_event ),
         my_callback_flag_ptr(dmsg.my_callback_flag_ptr)
     {
         if ( my_is_event )
             enforce_cl_retcode( clRetainEvent( my_event ), "Failed to retain an event" );
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::opencl_async_msg (opencl_async_msg< T, Factory > && dmsg) inline
Definition at line 398 of file flow_graph_opencl_node.h.
                                                 : async_msg<T>(std::move(dmsg)),
         my_data(std::move(dmsg.my_data)), my_event(dmsg.my_event), my_is_event(dmsg.my_is_event),
         my_callback_flag_ptr( std::move(dmsg.my_callback_flag_ptr) )
     {
         dmsg.my_is_event = false;
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::~opencl_async_msg () inline
Definition at line 424 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
{
         if ( my_is_event )
             enforce_cl_retcode( clReleaseEvent( my_event ), "Failed to release an event" );
     }
Member Function Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> void tbb::flow::interface10::opencl_async_msg< T, Factory >::clear_event () const inline
Definition at line 442 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
Referenced by tbb::flow::interface10::opencl_buffer< T, Factory >::receive(), and tbb::flow::interface10::opencl_buffer< T, Factory >::send().
{
         if ( my_is_event ) {
             enforce_cl_retcode( clFlush( event_info<cl_command_queue>( my_event, CL_EVENT_COMMAND_QUEUE ) ), "Failed to flush an OpenCL command queue" );
             enforce_cl_retcode( clReleaseEvent( my_event ), "Failed to release an event" );
         }
         my_is_event = false;
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> T& tbb::flow::interface10::opencl_async_msg< T, Factory >::data (bool wait = true) inline
Definition at line 372 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_map_buffer(), tbb::flow::interface10::opencl_memory< Factory >::get_host_ptr(), tbb::flow::interface10::key_from_message(), tbb::flow::interface10::opencl_factory< default_device_filter >::process_one_arg(), tbb::flow::interface10::opencl_memory< Factory >::receive(), tbb::flow::interface10::opencl_buffer< T, Factory >::receive(), tbb::flow::interface10::receive_if_memory_object(), tbb::flow::interface10::opencl_buffer< T, Factory >::send(), and tbb::flow::interface10::send_if_memory_object().
{
         if ( my_is_event && wait ) {
             enforce_cl_retcode( clWaitForEvents( 1, &my_event ), "Failed to wait for an event" );
             enforce_cl_retcode( clReleaseEvent( my_event ), "Failed to release an event" );
             my_is_event = false;
         }
         return my_data;
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> const T& tbb::flow::interface10::opencl_async_msg< T, Factory >::data (bool wait = true) const inline
Definition at line 381 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
{
         if ( my_is_event && wait ) {
             enforce_cl_retcode( clWaitForEvents( 1, &my_event ), "Failed to wait for an event" );
             enforce_cl_retcode( clReleaseEvent( my_event ), "Failed to release an event" );
             my_is_event = false;
         }
         return my_data;
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> void tbb::flow::interface10::opencl_async_msg< T, Factory >::finalize () const inline protected virtual
Reimplemented from tbb::flow::interface10::async_msg< T >.
Definition at line 462 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::receive_if_memory_object(), and tbb::flow::interface10::async_msg< T >::set().
{
         receive_if_memory_object(*this);
         if (! my_callback_flag_ptr->fetch_and_store(true)) {
             opencl_async_msg a(*this);
             if (my_is_event) {
                 register_callback([a](const T& t) mutable {
                     a.set(t);
                 });
             }
             else {
                 a.set(my_data);
             }
         }
         clear_event();
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> cl_event const* tbb::flow::interface10::opencl_async_msg< T, Factory >::get_event () const inline
Definition at line 429 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_map_buffer(), tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_unmap_buffer(), tbb::flow::interface10::opencl_factory< default_device_filter >::get_event_from_one_arg(), tbb::flow::interface10::opencl_factory< default_device_filter >::process_one_arg(), tbb::flow::interface10::opencl_buffer< T, Factory >::receive(), tbb::flow::interface10::receive_if_memory_object(), tbb::flow::interface10::opencl_memory< Factory >::send(), tbb::flow::interface10::opencl_buffer< T, Factory >::send(), and tbb::flow::interface10::send_if_memory_object().
 { return my_is_event ? &my_event : NULL; }
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::operator const T & () const inline
Definition at line 457 of file flow_graph_opencl_node.h.
References data.
 { return data(); }
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_async_msg< T, Factory >::operator T & () inline
Definition at line 456 of file flow_graph_opencl_node.h.
References data.
 { return data(); }
template<typename T, typename Factory = opencl_info::default_opencl_factory> opencl_async_msg& tbb::flow::interface10::opencl_async_msg< T, Factory >::operator= (const opencl_async_msg< T, Factory > & dmsg) inline
Definition at line 405 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode(), tbb::flow::interface10::opencl_async_msg< T, Factory >::my_callback_flag_ptr, tbb::flow::interface10::opencl_async_msg< T, Factory >::my_data, tbb::flow::interface10::opencl_async_msg< T, Factory >::my_event, and tbb::flow::interface10::opencl_async_msg< T, Factory >::my_is_event.
{
         async_msg<T>::operator =(dmsg);
         // Release original event
         if ( my_is_event )
             enforce_cl_retcode( clReleaseEvent( my_event ), "Failed to retain an event" );
         my_data = dmsg.my_data;
         my_event = dmsg.my_event;
         my_is_event = dmsg.my_is_event;
         // Retain copied event
         if ( my_is_event )
             enforce_cl_retcode( clRetainEvent( my_event ), "Failed to retain an event" );
         my_callback_flag_ptr = dmsg.my_callback_flag_ptr;
         return *this;
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> template<typename Callback > void tbb::flow::interface10::opencl_async_msg< T, Factory >::register_callback (Callback c) const inline
Definition at line 451 of file flow_graph_opencl_node.h.
References __TBB_ASSERT, and tbb::flow::interface10::enforce_cl_retcode().
{
         __TBB_ASSERT( my_is_event, "The OpenCL event is not set" );
         enforce_cl_retcode( clSetEventCallback( my_event, CL_COMPLETE, register_callback_func, new callback<Callback, T>( c, my_data ) ), "Failed to set an OpenCL callback" );
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> static void CL_CALLBACK tbb::flow::interface10::opencl_async_msg< T, Factory >::register_callback_func (cl_event , cl_int event_command_exec_status, void * data) inline static private
Definition at line 479 of file flow_graph_opencl_node.h.
References __TBB_ASSERT, tbb::flow::interface10::callback_base::call(), data, and tbb::internal::suppress_unused_warning().
{
         tbb::internal::suppress_unused_warning( event_command_exec_status );
         __TBB_ASSERT( event_command_exec_status == CL_COMPLETE, NULL );
         __TBB_ASSERT( data, NULL );
         callback_base *c = static_cast<callback_base*>(data);
         c->call();
         delete c;
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> void tbb::flow::interface10::opencl_async_msg< T, Factory >::set_event (cl_event e) const inline
Definition at line 430 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_map_buffer(), tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_unmap_buffer(), tbb::flow::interface10::opencl_buffer< T, Factory >::receive(), tbb::flow::interface10::receive_if_memory_object(), tbb::flow::interface10::opencl_buffer< T, Factory >::send(), tbb::flow::interface10::send_if_memory_object(), and tbb::flow::interface10::opencl_factory< default_device_filter >::update_one_arg().
{
         if ( my_is_event ) {
             cl_command_queue cq = event_info<cl_command_queue>( my_event, CL_EVENT_COMMAND_QUEUE );
             if ( cq != event_info<cl_command_queue>( e, CL_EVENT_COMMAND_QUEUE ) )
                 enforce_cl_retcode( clFlush( cq ), "Failed to flush an OpenCL command queue" );
             enforce_cl_retcode( clReleaseEvent( my_event ), "Failed to release an event" );
         }
         my_is_event = true;
         my_event = e;
         clRetainEvent( my_event );
     }
Member Data Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> std::shared_ptr< tbb::atomic<bool> > tbb::flow::interface10::opencl_async_msg< T, Factory >::my_callback_flag_ptr private
Definition at line 492 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_async_msg< T, Factory >::operator=().
template<typename T, typename Factory = opencl_info::default_opencl_factory> T tbb::flow::interface10::opencl_async_msg< T, Factory >::my_data private
Definition at line 488 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_async_msg< T, Factory >::operator=().
template<typename T, typename Factory = opencl_info::default_opencl_factory> cl_event tbb::flow::interface10::opencl_async_msg< T, Factory >::my_event mutable private
Definition at line 489 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_async_msg< T, Factory >::operator=().
template<typename T, typename Factory = opencl_info::default_opencl_factory> bool tbb::flow::interface10::opencl_async_msg< T, Factory >::my_is_event = false mutable private
Definition at line 490 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_async_msg< T, Factory >::operator=().
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.