Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_memory< Factory > Class Template Reference
tbb::flow::interface10::opencl_memory< Factory > Class Template Reference abstract
#include <flow_graph_opencl_node.h>
Public Member Functions
opencl_memory ()
opencl_memory (Factory &f)
~opencl_memory ()
cl_mem get_cl_mem () const
void * get_host_ptr ()
Factory * factory () const
opencl_async_msg< void *, Factory > receive (const cl_event *e)
opencl_async_msg< void *, Factory > send (opencl_device device, const cl_event *e)
virtual void map_memory (opencl_device, opencl_async_msg< void *, Factory > &)=0
Protected Attributes
cl_mem my_cl_mem
tbb::atomic< opencl_device::device_id_type > my_curr_device_id
void * my_host_ptr
Factory * my_factory
tbb::spin_mutex my_sending_lock
bool my_sending_event_present
cl_event my_sending_event
Detailed Description
template<typename Factory>
class tbb::flow::interface10::opencl_memory< Factory >
Definition at line 504 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename Factory> tbb::flow::interface10::opencl_memory< Factory >::opencl_memory () inline
Definition at line 506 of file flow_graph_opencl_node.h.
 {}
template<typename Factory> tbb::flow::interface10::opencl_memory< Factory >::opencl_memory (Factory & f) inline
Definition at line 507 of file flow_graph_opencl_node.h.
                                 : my_host_ptr( NULL ), my_factory( &f ), my_sending_event_present( false ) {
         my_curr_device_id = my_factory->devices().begin()->my_device_id;
     }
template<typename Factory> tbb::flow::interface10::opencl_memory< Factory >::~opencl_memory () inline
Definition at line 511 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
                      {
         if ( my_sending_event_present ) enforce_cl_retcode( clReleaseEvent( my_sending_event ), "Failed to release an event for the OpenCL buffer" );
         enforce_cl_retcode( clReleaseMemObject( my_cl_mem ), "Failed to release an memory object" );
     }
Member Function Documentation
template<typename Factory> Factory* tbb::flow::interface10::opencl_memory< Factory >::factory () const inline
Definition at line 529 of file flow_graph_opencl_node.h.
 { return my_factory; }
template<typename Factory> cl_mem tbb::flow::interface10::opencl_memory< Factory >::get_cl_mem () const inline
Definition at line 516 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_map_buffer(), and tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_unmap_buffer().
{
         return my_cl_mem;
     }
template<typename Factory> void* tbb::flow::interface10::opencl_memory< Factory >::get_host_ptr () inline
Definition at line 520 of file flow_graph_opencl_node.h.
References __TBB_ASSERT, and tbb::flow::interface10::opencl_async_msg< T, Factory >::data().
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_unmap_buffer().
{
         if ( !my_host_ptr ) {
             opencl_async_msg<void*, Factory> d = receive( NULL );
             d.data();
             __TBB_ASSERT( d.data() == my_host_ptr, NULL );
         }
         return my_host_ptr;
     }
template<typename Factory> virtual void tbb::flow::interface10::opencl_memory< Factory >::map_memory (opencl_device , opencl_async_msg< void *, Factory > &) pure virtual
Implemented in tbb::flow::interface10::opencl_buffer_impl< Factory >.
template<typename Factory> opencl_async_msg<void*, Factory> tbb::flow::interface10::opencl_memory< Factory >::receive (const cl_event * e) inline
Definition at line 531 of file flow_graph_opencl_node.h.
References d, tbb::flow::interface10::opencl_async_msg< T, Factory >::data(), tbb::flow::interface10::enforce_cl_retcode(), tbb::flow::interface10::opencl_device::host, and tbb::relaxed.
{
         opencl_async_msg<void*, Factory> d;
         if (e) {
             d = opencl_async_msg<void*, Factory>(my_host_ptr, *e);
         } else {
             d = opencl_async_msg<void*, Factory>(my_host_ptr);
         }
         // Concurrent receives are prohibited so we do not worry about synchronization.
         if (my_curr_device_id.load<tbb::relaxed>() != opencl_device::host) {
             map_memory(*my_factory->devices().begin(), d);
             my_curr_device_id.store<tbb::relaxed>(opencl_device::host);
             my_host_ptr = d.data(false);
         }
         // Release the sending event
         if (my_sending_event_present) {
             enforce_cl_retcode(clReleaseEvent(my_sending_event), "Failed to release an event");
             my_sending_event_present = false;
         }
         return d;
     }
template<typename Factory> opencl_async_msg<void*, Factory> tbb::flow::interface10::opencl_memory< Factory >::send (opencl_device device, const cl_event * e) inline
Definition at line 553 of file flow_graph_opencl_node.h.
References __TBB_ASSERT, tbb::acquire, d, tbb::flow::interface10::enforce_cl_retcode(), tbb::flow::interface10::opencl_async_msg< T, Factory >::get_event(), lock, tbb::flow::interface10::opencl_device::my_device_id, tbb::relaxed, and tbb::release.
{
         opencl_device::device_id_type device_id = device.my_device_id;
         if (!my_factory->is_same_context(my_curr_device_id.load<tbb::acquire>(), device_id)) {
             {
                 tbb::spin_mutex::scoped_lock lock(my_sending_lock);
                 if (!my_factory->is_same_context(my_curr_device_id.load<tbb::relaxed>(), device_id)) {
                     __TBB_ASSERT(my_host_ptr, "The buffer has not been mapped");
                     opencl_async_msg<void*, Factory> d(my_host_ptr);
                     my_factory->enqueue_unmap_buffer(device, *this, d);
                     my_sending_event = *d.get_event();
                     my_sending_event_present = true;
                     enforce_cl_retcode(clRetainEvent(my_sending_event), "Failed to retain an event");
                     my_host_ptr = NULL;
                     my_curr_device_id.store<tbb::release>(device_id);
                 }
             }
             __TBB_ASSERT(my_sending_event_present, NULL);
         }
         // !e means that buffer has come from the host
         if (!e && my_sending_event_present) e = &my_sending_event;
         __TBB_ASSERT(!my_host_ptr, "The buffer has not been unmapped");
         return e ? opencl_async_msg<void*, Factory>(NULL, *e) : opencl_async_msg<void*, Factory>(NULL);
     }
Member Data Documentation
template<typename Factory> cl_mem tbb::flow::interface10::opencl_memory< Factory >::my_cl_mem protected
Definition at line 581 of file flow_graph_opencl_node.h.
template<typename Factory> tbb::atomic<opencl_device::device_id_type> tbb::flow::interface10::opencl_memory< Factory >::my_curr_device_id protected
Definition at line 582 of file flow_graph_opencl_node.h.
template<typename Factory> Factory* tbb::flow::interface10::opencl_memory< Factory >::my_factory protected
Definition at line 584 of file flow_graph_opencl_node.h.
template<typename Factory> void* tbb::flow::interface10::opencl_memory< Factory >::my_host_ptr protected
Definition at line 583 of file flow_graph_opencl_node.h.
template<typename Factory> cl_event tbb::flow::interface10::opencl_memory< Factory >::my_sending_event protected
Definition at line 588 of file flow_graph_opencl_node.h.
template<typename Factory> bool tbb::flow::interface10::opencl_memory< Factory >::my_sending_event_present protected
Definition at line 587 of file flow_graph_opencl_node.h.
template<typename Factory> tbb::spin_mutex tbb::flow::interface10::opencl_memory< Factory >::my_sending_lock protected
Definition at line 586 of file flow_graph_opencl_node.h.
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.