Intel(R) Threading Building Blocks Doxygen Documentation: tbb::mutex Class Reference
tbb::mutex Class Reference
Synchronization
Wrapper around the platform's native lock.
#include <mutex.h>
Classes
class scoped_lock
The scoped locking pattern.
Public Types
enum state_t { INITIALIZED =0x1234, DESTROYED =0x789A, HELD =0x56CD }
typedef pthread_mutex_t * native_handle_type
Return native_handle.
Public Member Functions
mutex ()
Construct unacquired mutex.
~mutex ()
void lock ()
Acquire lock.
bool try_lock ()
Try acquiring lock (non-blocking)
void unlock ()
Release lock.
native_handle_type native_handle ()
Static Public Attributes
static const bool is_rw_mutex = false
static const bool is_recursive_mutex = false
static const bool is_fair_mutex = false
Private Member Functions
void __TBB_EXPORTED_METHOD internal_construct ()
All checks from mutex constructor using mutex.state were moved here.
void __TBB_EXPORTED_METHOD internal_destroy ()
All checks from mutex destructor using mutex.state were moved here.
Private Attributes
pthread_mutex_t impl
Friends
class scoped_lock
Detailed Description
Wrapper around the platform's native lock.
Definition at line 39 of file mutex.h.
Member Typedef Documentation
typedef pthread_mutex_t* tbb::mutex::native_handle_type
Return native_handle.
Definition at line 199 of file mutex.h.
Member Enumeration Documentation
enum tbb::mutex::state_t
Enumerator
INITIALIZED
DESTROYED
HELD
Definition at line 203 of file mutex.h.
                  {
         INITIALIZED=0x1234,
         DESTROYED=0x789A,
         HELD=0x56CD
     };
Constructor & Destructor Documentation
tbb::mutex::mutex () inline
Construct unacquired mutex.
Definition at line 42 of file mutex.h.
References tbb::internal::handle_perror(), impl, and internal_construct().
             {
 #if TBB_USE_ASSERT || TBB_USE_THREADING_TOOLS
     internal_construct();
 #else
   #if _WIN32||_WIN64
         InitializeCriticalSectionEx(&impl, 4000, 0);
   #else
         int error_code = pthread_mutex_init(&impl,NULL);
         if( error_code )
             tbb::internal::handle_perror(error_code,"mutex: pthread_mutex_init failed");
   #endif /* _WIN32||_WIN64*/
 #endif /* TBB_USE_ASSERT */
     };
tbb::mutex::~mutex () inline
Definition at line 56 of file mutex.h.
References impl, and internal_destroy().
              {
 #if TBB_USE_ASSERT
         internal_destroy();
 #else
   #if _WIN32||_WIN64
         DeleteCriticalSection(&impl);
   #else
         pthread_mutex_destroy(&impl);
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     };
Member Function Documentation
void tbb::mutex::internal_construct () private
All checks from mutex constructor using mutex.state were moved here.
Definition at line 116 of file mutex.cpp.
References _T, tbb::internal::handle_perror(), impl, INITIALIZED, and ITT_SYNC_CREATE.
Referenced by mutex().
{
 #if _WIN32||_WIN64
     InitializeCriticalSectionEx(&impl, 4000, 0);
     state = INITIALIZED;
 #else
     int error_code = pthread_mutex_init(&impl,NULL);
     if( error_code )
         tbb::internal::handle_perror(error_code,"mutex: pthread_mutex_init failed");
 #endif /* _WIN32||_WIN64*/
     ITT_SYNC_CREATE(&impl, _T("tbb::mutex"), _T(""));
 }
void tbb::mutex::internal_destroy () private
All checks from mutex destructor using mutex.state were moved here.
Definition at line 128 of file mutex.cpp.
References __TBB_ASSERT, __TBB_ASSERT_EX, DESTROYED, impl, INITIALIZED, and tbb::internal::governor::speculation_enabled().
Referenced by ~mutex().
{
 #if _WIN32||_WIN64
     switch( state ) {
       case INITIALIZED:
         DeleteCriticalSection(&impl);
        break;
       case DESTROYED:
         __TBB_ASSERT(false,"mutex: already destroyed");
         break;
       default:
         __TBB_ASSERT(false,"mutex: illegal state for destruction");
         break;
     }
     state = DESTROYED;
 #else
     int error_code = pthread_mutex_destroy(&impl);
 #if __TBB_TSX_AVAILABLE
     // For processors with speculative execution, skip the error code check due to glibc bug #16657
     if( tbb::internal::governor::speculation_enabled() ) return;
 #endif
     __TBB_ASSERT_EX(!error_code,"mutex: pthread_mutex_destroy failed");
 #endif /* _WIN32||_WIN64 */
 }
void tbb::mutex::lock () inline
Acquire lock.
Definition at line 147 of file mutex.h.
References tbb::aligned_space< T, N >::begin(), tbb::internal::handle_perror(), impl, and tbb::mutex::scoped_lock::scoped_lock().
Referenced by tbb::mutex::scoped_lock::acquire().
                 {
 #if TBB_USE_ASSERT
         aligned_space<scoped_lock> tmp;
         new(tmp.begin()) scoped_lock(*this);
 #else
   #if _WIN32||_WIN64
         EnterCriticalSection(&impl);
   #else
         int error_code = pthread_mutex_lock(&impl);
         if( error_code )
             tbb::internal::handle_perror(error_code,"mutex: pthread_mutex_lock failed");
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     }
native_handle_type tbb::mutex::native_handle () inline
Definition at line 201 of file mutex.h.
References impl.
 { return (native_handle_type) &impl; }
bool tbb::mutex::try_lock () inline
Try acquiring lock (non-blocking)
Return true if lock acquired; false otherwise.
Definition at line 164 of file mutex.h.
References tbb::aligned_space< T, N >::begin(), impl, tbb::mutex::scoped_lock::internal_try_acquire(), tbb::mutex::scoped_lock::my_mutex, and s.
Referenced by tbb::mutex::scoped_lock::try_acquire().
                     {
 #if TBB_USE_ASSERT
         aligned_space<scoped_lock> tmp;
         scoped_lock& s = *tmp.begin();
         s.my_mutex = NULL;
         return s.internal_try_acquire(*this);
 #else
   #if _WIN32||_WIN64
         return TryEnterCriticalSection(&impl)!=0;
   #else
         return pthread_mutex_trylock(&impl)==0;
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     }
void tbb::mutex::unlock () inline
Release lock.
Definition at line 180 of file mutex.h.
References tbb::aligned_space< T, N >::begin(), impl, tbb::mutex::scoped_lock::internal_release(), tbb::mutex::scoped_lock::my_mutex, and s.
Referenced by tbb::mutex::scoped_lock::release().
                   {
 #if TBB_USE_ASSERT
         aligned_space<scoped_lock> tmp;
         scoped_lock& s = *tmp.begin();
         s.my_mutex = this;
         s.internal_release();
 #else
   #if _WIN32||_WIN64
         LeaveCriticalSection(&impl);
   #else
         pthread_mutex_unlock(&impl);
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     }
Friends And Related Function Documentation
friend class scoped_lock friend
Definition at line 69 of file mutex.h.
Member Data Documentation
pthread_mutex_t tbb::mutex::impl private
Definition at line 213 of file mutex.h.
Referenced by tbb::mutex::scoped_lock::internal_acquire(), internal_construct(), internal_destroy(), tbb::mutex::scoped_lock::internal_release(), tbb::mutex::scoped_lock::internal_try_acquire(), lock(), mutex(), native_handle(), try_lock(), unlock(), and ~mutex().
const bool tbb::mutex::is_fair_mutex = false static
Definition at line 142 of file mutex.h.
const bool tbb::mutex::is_recursive_mutex = false static
Definition at line 141 of file mutex.h.
const bool tbb::mutex::is_rw_mutex = false static
Definition at line 140 of file mutex.h.
The documentation for this class was generated from the following files:
mutex.h
mutex.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.