Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder Class Reference
tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder Class Reference
Public Types
typedef void(CL_CALLBACK * cl_callback_type) (cl_program, void *)
Public Member Functions
opencl_program_builder (Factory &f, const std::string &name, cl_program program, cl_uint num_devices, cl_device_id *device_list, const char *options, cl_callback_type callback, void *user_data)
Detailed Description
template<typename Factory = opencl_info::default_opencl_factory>
class tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder
Definition at line 1281 of file flow_graph_opencl_node.h.
Member Typedef Documentation
template<typename Factory = opencl_info::default_opencl_factory> typedef void(CL_CALLBACK * tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder::cl_callback_type) (cl_program, void *)
Definition at line 1283 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder::opencl_program_builder (Factory & f, const std::string & name, cl_program program, cl_uint num_devices, cl_device_id * device_list, const char * options, cl_callback_type callback, void * user_data) inline
Definition at line 1284 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::opencl_device_list::begin(), d, tbb::flow::interface10::opencl_device_list::end(), tbb::flow::interface10::enforce_cl_retcode(), and name.
{
             cl_int err = clBuildProgram( program, num_devices, device_list, options,
                                          callback, user_data );
             if( err == CL_SUCCESS )
                 return;
             std::string str = std::string( "Failed to build program: " ) + name;
             if ( err == CL_BUILD_PROGRAM_FAILURE ) {
                 const opencl_device_list &devices = f.devices();
                 for ( auto d = devices.begin(); d != devices.end(); ++d ) {
                     std::cerr << "Build log for device: " << (*d).name() << std::endl;
                     size_t log_size;
                     cl_int query_err = clGetProgramBuildInfo(
                         program, (*d).my_cl_device_id, CL_PROGRAM_BUILD_LOG, 0, NULL,
                         &log_size );
                     enforce_cl_retcode( query_err, "Failed to get build log size" );
                     if( log_size ) {
                         std::vector<char> output;
                         output.resize( log_size );
                         query_err = clGetProgramBuildInfo(
                             program, (*d).my_cl_device_id, CL_PROGRAM_BUILD_LOG,
                             output.size(), output.data(), NULL );
                         enforce_cl_retcode( query_err, "Failed to get build output" );
                         std::cerr << output.data() << std::endl;
                     } else {
                         std::cerr << "No build log available" << std::endl;
                     }
                 }
             }
             enforce_cl_retcode( err, str );
         }
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.