Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_buffer< T, Factory > Class Template Reference
tbb::flow::interface10::opencl_buffer< T, Factory > Class Template Reference
#include <flow_graph_opencl_node.h>
Public Types
typedef cl_mem native_object_type
typedef opencl_buffer memory_object_type
typedef Factory opencl_factory_type
template<access_type a>
using iterator = T *
Public Member Functions
template<access_type a>
iterator< a > access () const
T * data () const
template<access_type a = read_write>
iterator< a > begin () const
template<access_type a = read_write>
iterator< a > end () const
size_t size () const
T & operator[] (ptrdiff_t k)
opencl_buffer ()
opencl_buffer (size_t size)
opencl_buffer (Factory &f, size_t size)
cl_mem native_object () const
const opencl_buffer & memory_object () const
void send (opencl_device device, opencl_async_msg< opencl_buffer, Factory > &dependency) const
void receive (const opencl_async_msg< opencl_buffer, Factory > &dependency) const
opencl_subbuffer< T, Factory > subbuffer (size_t index, size_t size) const
Private Types
typedef opencl_buffer_impl< Factory > impl_type
Private Member Functions
opencl_buffer (Factory &f, cl_mem m, size_t index, size_t size)
Private Attributes
std::shared_ptr< impl_type > my_impl
Friends
template<typename >
class opencl_factory
template<typename , typename >
class opencl_subbuffer
bool operator== (const opencl_buffer< T, Factory > &lhs, const opencl_buffer< T, Factory > &rhs)
Detailed Description
template<typename T, typename Factory = opencl_info::default_opencl_factory>
class tbb::flow::interface10::opencl_buffer< T, Factory >
Definition at line 633 of file flow_graph_opencl_node.h.
Member Typedef Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> typedef opencl_buffer_impl<Factory> tbb::flow::interface10::opencl_buffer< T, Factory >::impl_type private
Definition at line 692 of file flow_graph_opencl_node.h.
template<typename T, typename Factory = opencl_info::default_opencl_factory> template<access_type a> using tbb::flow::interface10::opencl_buffer< T, Factory >::iterator = T*
Definition at line 639 of file flow_graph_opencl_node.h.
template<typename T, typename Factory = opencl_info::default_opencl_factory> typedef opencl_buffer tbb::flow::interface10::opencl_buffer< T, Factory >::memory_object_type
Definition at line 636 of file flow_graph_opencl_node.h.
template<typename T, typename Factory = opencl_info::default_opencl_factory> typedef cl_mem tbb::flow::interface10::opencl_buffer< T, Factory >::native_object_type
Definition at line 635 of file flow_graph_opencl_node.h.
template<typename T, typename Factory = opencl_info::default_opencl_factory> typedef Factory tbb::flow::interface10::opencl_buffer< T, Factory >::opencl_factory_type
Definition at line 637 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_buffer< T, Factory >::opencl_buffer () inline
Definition at line 660 of file flow_graph_opencl_node.h.
References size.
 {}
template<typename T , typename Factory > tbb::flow::interface10::opencl_buffer< T, Factory >::opencl_buffer (size_t size)
Definition at line 1212 of file flow_graph_opencl_node.h.
 : my_impl( std::make_shared<impl_type>( size*sizeof(T), opencl_info::default_factory() ) ) {}
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_buffer< T, Factory >::opencl_buffer (Factory & f, size_t size) inline
Definition at line 662 of file flow_graph_opencl_node.h.
 : my_impl( std::make_shared<impl_type>( size*sizeof(T), f ) ) {}
template<typename T, typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_buffer< T, Factory >::opencl_buffer (Factory & f, cl_mem m, size_t index, size_t size) inline private
Definition at line 690 of file flow_graph_opencl_node.h.
 : my_impl( std::make_shared<impl_type>( m, index*sizeof(T), size*sizeof(T), f ) ) {}
Member Function Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> template<access_type a> iterator<a> tbb::flow::interface10::opencl_buffer< T, Factory >::access () const inline
Definition at line 642 of file flow_graph_opencl_node.h.
References __TBB_ASSERT.
{
         T* ptr = (T*)my_impl->get_host_ptr();
         __TBB_ASSERT( ptr, NULL );
         return iterator<a>( ptr );
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> template<access_type a = read_write> iterator<a> tbb::flow::interface10::opencl_buffer< T, Factory >::begin () const inline
Definition at line 651 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_program< Factory >::file_reader::file_reader().
 { return access<a>(); }
template<typename T, typename Factory = opencl_info::default_opencl_factory> T* tbb::flow::interface10::opencl_buffer< T, Factory >::data () const inline
Definition at line 648 of file flow_graph_opencl_node.h.
 { return &access<read_write>()[0]; }
template<typename T, typename Factory = opencl_info::default_opencl_factory> template<access_type a = read_write> iterator<a> tbb::flow::interface10::opencl_buffer< T, Factory >::end () const inline
Definition at line 654 of file flow_graph_opencl_node.h.
 { return access<a>()+my_impl->size()/sizeof(T); }
template<typename T, typename Factory = opencl_info::default_opencl_factory> const opencl_buffer& tbb::flow::interface10::opencl_buffer< T, Factory >::memory_object () const inline
Definition at line 668 of file flow_graph_opencl_node.h.
{
         return *this;
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> cl_mem tbb::flow::interface10::opencl_buffer< T, Factory >::native_object () const inline
Definition at line 664 of file flow_graph_opencl_node.h.
{
         return my_impl->get_cl_mem();
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> T& tbb::flow::interface10::opencl_buffer< T, Factory >::operator[] (ptrdiff_t k) inline
Definition at line 658 of file flow_graph_opencl_node.h.
References begin.
 { return begin()[k]; }
template<typename T, typename Factory = opencl_info::default_opencl_factory> void tbb::flow::interface10::opencl_buffer< T, Factory >::receive (const opencl_async_msg< opencl_buffer< T, Factory >, Factory > & dependency) const inline
Definition at line 679 of file flow_graph_opencl_node.h.
References __TBB_ASSERT, tbb::flow::interface10::opencl_async_msg< T, Factory >::clear_event(), tbb::flow::interface10::opencl_async_msg< T, Factory >::data(), tbb::flow::interface10::opencl_async_msg< T, Factory >::get_event(), and tbb::flow::interface10::opencl_async_msg< T, Factory >::set_event().
{
         __TBB_ASSERT( dependency.data( /*wait = */false ) == *this, NULL );
         opencl_async_msg<void*, Factory> d = my_impl->receive( dependency.get_event() );
         const cl_event *e = d.get_event();
         if ( e ) dependency.set_event( *e );
         else dependency.clear_event();
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> void tbb::flow::interface10::opencl_buffer< T, Factory >::send (opencl_device device, opencl_async_msg< opencl_buffer< T, Factory >, Factory > & dependency) const inline
Definition at line 672 of file flow_graph_opencl_node.h.
References __TBB_ASSERT, tbb::flow::interface10::opencl_async_msg< T, Factory >::clear_event(), tbb::flow::interface10::opencl_async_msg< T, Factory >::data(), tbb::flow::interface10::opencl_async_msg< T, Factory >::get_event(), and tbb::flow::interface10::opencl_async_msg< T, Factory >::set_event().
{
         __TBB_ASSERT( dependency.data( /*wait = */false ) == *this, NULL );
         opencl_async_msg<void*, Factory> d = my_impl->send( device, dependency.get_event() );
         const cl_event *e = d.get_event();
         if ( e ) dependency.set_event( *e );
         else dependency.clear_event();
     }
template<typename T, typename Factory = opencl_info::default_opencl_factory> size_t tbb::flow::interface10::opencl_buffer< T, Factory >::size () const inline
Definition at line 656 of file flow_graph_opencl_node.h.
 { return my_impl->size()/sizeof(T); }
template<typename T , typename Factory > opencl_subbuffer< T, Factory > tbb::flow::interface10::opencl_buffer< T, Factory >::subbuffer (size_t index, size_t size) const
Definition at line 716 of file flow_graph_opencl_node.h.
References size.
{
     return opencl_subbuffer<T, Factory>( *this, index, size );
 }
Friends And Related Function Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> template<typename > friend class opencl_factory friend
Definition at line 701 of file flow_graph_opencl_node.h.
template<typename T, typename Factory = opencl_info::default_opencl_factory> template<typename , typename > friend class opencl_subbuffer friend
Definition at line 703 of file flow_graph_opencl_node.h.
template<typename T, typename Factory = opencl_info::default_opencl_factory> bool operator== (const opencl_buffer< T, Factory > & lhs, const opencl_buffer< T, Factory > & rhs) friend
Definition at line 696 of file flow_graph_opencl_node.h.
{
         return lhs.my_impl == rhs.my_impl;
     }
Member Data Documentation
template<typename T, typename Factory = opencl_info::default_opencl_factory> std::shared_ptr<impl_type> tbb::flow::interface10::opencl_buffer< T, Factory >::my_impl private
Definition at line 694 of file flow_graph_opencl_node.h.
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.