Intel(R) Threading Building Blocks Doxygen Documentation: internal::node_cache< T, M > Class Template Reference
internal::node_cache< T, M > Class Template Reference
A node_cache maintains a std::queue of elements of type T. Each operation is protected by a lock.
#include <_flow_graph_cache_impl.h>
Public Types
typedef size_t size_type
Public Member Functions
bool empty ()
void add (T &n)
void remove (T &n)
void clear ()
Protected Types
typedef M mutex_type
Protected Member Functions
bool internal_empty ()
size_type internal_size ()
void internal_push (T &n)
T & internal_pop ()
Protected Attributes
mutex_type my_mutex
std::queue< T * > my_q
Detailed Description
template<typename T, typename M = spin_mutex>
class internal::node_cache< T, M >
A node_cache maintains a std::queue of elements of type T. Each operation is protected by a lock.
Definition at line 34 of file _flow_graph_cache_impl.h.
Member Typedef Documentation
template<typename T, typename M = spin_mutex> typedef M internal::node_cache< T, M >::mutex_type protected
Definition at line 93 of file _flow_graph_cache_impl.h.
template<typename T, typename M = spin_mutex> typedef size_t internal::node_cache< T, M >::size_type
Definition at line 37 of file _flow_graph_cache_impl.h.
Member Function Documentation
template<typename T, typename M = spin_mutex> void internal::node_cache< T, M >::add (T & n) inline
Definition at line 44 of file _flow_graph_cache_impl.h.
Referenced by internal::predecessor_cache< input_type, null_mutex >::get_item(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::handle_operations(), and internal::reservable_predecessor_cache< T, null_mutex >::try_reserve().
                      {
         typename mutex_type::scoped_lock lock( my_mutex );
         internal_push(n);
     }
template<typename T, typename M = spin_mutex> void internal::node_cache< T, M >::clear () inline
Definition at line 58 of file _flow_graph_cache_impl.h.
Referenced by internal::reservable_predecessor_cache< T, null_mutex >::clear(), and internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::reset_receiver().
                  {
         while( !my_q.empty()) (void)my_q.pop();
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
         my_built_predecessors.clear();
 #endif
     }
template<typename T, typename M = spin_mutex> bool internal::node_cache< T, M >::empty () inline
Definition at line 39 of file _flow_graph_cache_impl.h.
Referenced by internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::reset_receiver().
                  {
         typename mutex_type::scoped_lock lock( my_mutex );
         return internal_empty();
     }
template<typename T, typename M = spin_mutex> bool internal::node_cache< T, M >::internal_empty () inline protected
Definition at line 101 of file _flow_graph_cache_impl.h.
Referenced by internal::node_cache< sender< T >, M >::empty(), internal::predecessor_cache< input_type, null_mutex >::get_item(), internal::predecessor_cache< input_type, null_mutex >::reset(), and internal::reservable_predecessor_cache< T, null_mutex >::try_reserve().
{
         return my_q.empty();
     }
template<typename T, typename M = spin_mutex> T& internal::node_cache< T, M >::internal_pop () inline protected
Definition at line 116 of file _flow_graph_cache_impl.h.
Referenced by internal::predecessor_cache< input_type, null_mutex >::get_item(), internal::node_cache< sender< T >, M >::remove(), internal::predecessor_cache< input_type, null_mutex >::reset(), and internal::reservable_predecessor_cache< T, null_mutex >::try_reserve().
{
         T *v = my_q.front();
         my_q.pop();
         return *v;
     }
template<typename T, typename M = spin_mutex> void internal::node_cache< T, M >::internal_push (T & n) inline protected
Definition at line 111 of file _flow_graph_cache_impl.h.
Referenced by internal::node_cache< sender< T >, M >::add(), and internal::node_cache< sender< T >, M >::remove().
{
         my_q.push(&n);
     }
template<typename T, typename M = spin_mutex> size_type internal::node_cache< T, M >::internal_size () inline protected
Definition at line 106 of file _flow_graph_cache_impl.h.
Referenced by internal::node_cache< sender< T >, M >::remove().
{
         return my_q.size();
     }
template<typename T, typename M = spin_mutex> void internal::node_cache< T, M >::remove (T & n) inline
Definition at line 49 of file _flow_graph_cache_impl.h.
Referenced by internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::handle_operations().
{
         typename mutex_type::scoped_lock lock( my_mutex );
         for ( size_t i = internal_size(); i != 0; --i ) {
             T &s = internal_pop();
             if ( &s == &n )  return;  // only remove one predecessor per request
             internal_push(s);
         }
     }
Member Data Documentation
template<typename T, typename M = spin_mutex> mutex_type internal::node_cache< T, M >::my_mutex protected
Definition at line 94 of file _flow_graph_cache_impl.h.
Referenced by internal::node_cache< sender< T >, M >::add(), internal::node_cache< sender< T >, M >::clear(), internal::node_cache< sender< T >, M >::empty(), internal::predecessor_cache< input_type, null_mutex >::get_item(), internal::node_cache< sender< T >, M >::remove(), internal::round_robin_cache< T, M >::size(), internal::broadcast_cache< output_type >::try_put_task(), internal::round_robin_cache< T, M >::try_put_task(), and internal::reservable_predecessor_cache< T, null_mutex >::try_reserve().
template<typename T, typename M = spin_mutex> std::queue< T * > internal::node_cache< T, M >::my_q protected
Definition at line 95 of file _flow_graph_cache_impl.h.
Referenced by internal::node_cache< sender< T >, M >::clear().
The documentation for this class was generated from the following file:
_flow_graph_cache_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.