Intel(R) Threading Building Blocks Doxygen Documentation: internal::multifunction_input< Input, OutputPortSet, Policy, A > Class Template Reference
internal::multifunction_input< Input, OutputPortSet, Policy, A > Class Template Reference
Implements methods for a function node that takes a type Input as input.
#include <_flow_graph_node_impl.h>
Public Types
typedef Input input_type
typedef OutputPortSet output_ports_type
typedef multifunction_body< input_type, output_ports_type > multifunction_body_type
typedef multifunction_input< Input, OutputPortSet, Policy, A > my_class
typedef function_input_base< Input, Policy, A, my_class > base_type
typedef function_input_queue< input_type, A > input_queue_type
Public Types inherited from internal::function_input_base< Input, Policy, A, ImplType >
typedef Input input_type
The input type of this receiver.
typedef receiver< input_type >::predecessor_type predecessor_type
typedef predecessor_cache< input_type, null_mutex > predecessor_cache_type
typedef function_input_queue< input_type, A > input_queue_type
typedef A::template rebind< input_queue_type >::other queue_allocator_type
Public Types inherited from tbb::flow::interface10::receiver< Input >
typedef Input input_type
The input type of this receiver.
typedef internal::async_helpers< Input >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Member Functions
template<typename Body >
multifunction_input (graph &g, size_t max_concurrency,)
multifunction_input (const multifunction_input &src)
Copy constructor.
~multifunction_input ()
template<typename Body >
Body copy_function_object ()
task * apply_body_impl_bypass (const input_type &i)
output_ports_type & output_ports ()
Public Member Functions inherited from internal::function_input_base< Input, Policy, A, ImplType >
__TBB_STATIC_ASSERT (!((internal::has_policy< queueing, Policy >::value)&&(internal::has_policy< rejecting, Policy >::value)),"queueing and rejecting policies can't be specified simultaneously")
function_input_base (graph &g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(size_t max_concurrency, node_priority_t priority))
Constructor for function_input_base.
function_input_base (const function_input_base &src)
Copy constructor.
virtual ~function_input_base ()
Destructor.
task * try_put_task (const input_type &t) __TBB_override
Put item to successor; return task to run the successor if possible.
bool register_predecessor (predecessor_type &src) __TBB_override
Adds src to the list of cached predecessors.
bool remove_predecessor (predecessor_type &src) __TBB_override
Removes src from the list of cached predecessors.
Public Member Functions inherited from tbb::flow::interface10::receiver< Input >
bool try_put (const typename internal::async_helpers< Input >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< Input >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
Static Public Attributes
static const int N = tbb::flow::tuple_size<OutputPortSet>::value
Protected Member Functions
void reset (reset_flags f)
Protected Member Functions inherited from internal::function_input_base< Input, Policy, A, ImplType >
void reset_function_input_base (reset_flags f)
void reset_receiver (reset_flags f) __TBB_override
graph & graph_reference () __TBB_override
task * try_get_postponed_task (const input_type &i)
Protected Member Functions inherited from tbb::flow::interface10::receiver< Input >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual void reset_receiver (reset_flags f=rf_reset_protocol)=0
put receiver back in initial state
virtual bool is_continue_receiver ()
Protected Attributes
multifunction_body_type * my_body
multifunction_body_type * my_init_body
output_ports_type my_output_ports
Protected Attributes inherited from internal::function_input_base< Input, Policy, A, ImplType >
graph & my_graph_ref
const size_t my_max_concurrency
size_t my_concurrency
input_queue_type * my_queue
predecessor_cache< input_type, null_mutex > my_predecessors
Detailed Description
template<typename Input, typename OutputPortSet, typename Policy, typename A>
class internal::multifunction_input< Input, OutputPortSet, Policy, A >
Implements methods for a function node that takes a type Input as input.
Definition at line 569 of file _flow_graph_node_impl.h.
Member Typedef Documentation
template<typename Input , typename OutputPortSet , typename Policy , typename A > typedef function_input_base<Input, Policy, A, my_class> internal::multifunction_input< Input, OutputPortSet, Policy, A >::base_type
Definition at line 576 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > typedef function_input_queue<input_type, A> internal::multifunction_input< Input, OutputPortSet, Policy, A >::input_queue_type
Definition at line 577 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > typedef Input internal::multifunction_input< Input, OutputPortSet, Policy, A >::input_type
Definition at line 572 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > typedef multifunction_body<input_type, output_ports_type> internal::multifunction_input< Input, OutputPortSet, Policy, A >::multifunction_body_type
Definition at line 574 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > typedef multifunction_input<Input, OutputPortSet, Policy, A> internal::multifunction_input< Input, OutputPortSet, Policy, A >::my_class
Definition at line 575 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > typedef OutputPortSet internal::multifunction_input< Input, OutputPortSet, Policy, A >::output_ports_type
Definition at line 573 of file _flow_graph_node_impl.h.
Constructor & Destructor Documentation
template<typename Input , typename OutputPortSet , typename Policy , typename A > template<typename Body > internal::multifunction_input< Input, OutputPortSet, Policy, A >::multifunction_input (graph & g, size_t max_concurrency) inline
Definition at line 581 of file _flow_graph_node_impl.h.
           : base_type(g, __TBB_FLOW_GRAPH_PRIORITY_ARG1(max_concurrency, priority))
           , my_body( new internal::multifunction_body_leaf<input_type, output_ports_type, Body>(body) )
           , my_init_body( new internal::multifunction_body_leaf<input_type, output_ports_type, Body>(body) ) {
         }
template<typename Input , typename OutputPortSet , typename Policy , typename A > internal::multifunction_input< Input, OutputPortSet, Policy, A >::multifunction_input (const multifunction_input< Input, OutputPortSet, Policy, A > & src) inline
Copy constructor.
Definition at line 589 of file _flow_graph_node_impl.h.
                                                               :
                 base_type(src),
                 my_body( src.my_init_body->clone() ),
                 my_init_body(src.my_init_body->clone() ) {
         }
template<typename Input , typename OutputPortSet , typename Policy , typename A > internal::multifunction_input< Input, OutputPortSet, Policy, A >::~multifunction_input () inline
Definition at line 595 of file _flow_graph_node_impl.h.
{
             delete my_body;
             delete my_init_body;
         }
Member Function Documentation
template<typename Input , typename OutputPortSet , typename Policy , typename A > task* internal::multifunction_input< Input, OutputPortSet, Policy, A >::apply_body_impl_bypass (const input_type & i) inline
Definition at line 609 of file _flow_graph_node_impl.h.
References tbb::internal::fgt_begin_body(), tbb::internal::fgt_end_body(), tbb::flow::internal::SUCCESSFULLY_ENQUEUED, and task.
{
             tbb::internal::fgt_begin_body( my_body );
             (*my_body)(i, my_output_ports);
             tbb::internal::fgt_end_body( my_body );
             task* ttask = NULL;
             if(base_type::my_max_concurrency != 0) {
                 ttask = base_type::try_get_postponed_task(i);
             }
             return ttask ? ttask : SUCCESSFULLY_ENQUEUED;
         }
template<typename Input , typename OutputPortSet , typename Policy , typename A > template<typename Body > Body internal::multifunction_input< Input, OutputPortSet, Policy, A >::copy_function_object () inline
Definition at line 601 of file _flow_graph_node_impl.h.
{
             multifunction_body_type &body_ref = *this->my_body;
             return *static_cast<Body*>(dynamic_cast< internal::multifunction_body_leaf<input_type, output_ports_type, Body> & >(body_ref).get_body_ptr());
         }
template<typename Input , typename OutputPortSet , typename Policy , typename A > output_ports_type& internal::multifunction_input< Input, OutputPortSet, Policy, A >::output_ports () inline
Definition at line 620 of file _flow_graph_node_impl.h.
 { return my_output_ports; }
template<typename Input , typename OutputPortSet , typename Policy , typename A > void internal::multifunction_input< Input, OutputPortSet, Policy, A >::reset (reset_flags f) inline protected
Definition at line 629 of file _flow_graph_node_impl.h.
References __TBB_ASSERT, internal::clear_element< N >::clear_this(), tbb::flow::interface10::rf_clear_edges, and tbb::flow::interface10::rf_reset_bodies.
{
             base_type::reset_function_input_base(f);
             if(f & rf_clear_edges)clear_element<N>::clear_this(my_output_ports);
             if(f & rf_reset_bodies) {
                 multifunction_body_type *tmp = my_init_body->clone();
                 delete my_body;
                 my_body = tmp;
             }
             __TBB_ASSERT(!(f & rf_clear_edges) || clear_element<N>::this_empty(my_output_ports), "multifunction_node reset failed");
         }
Member Data Documentation
template<typename Input , typename OutputPortSet , typename Policy , typename A > multifunction_body_type* internal::multifunction_input< Input, OutputPortSet, Policy, A >::my_body protected
Definition at line 640 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > multifunction_body_type* internal::multifunction_input< Input, OutputPortSet, Policy, A >::my_init_body protected
Definition at line 641 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > output_ports_type internal::multifunction_input< Input, OutputPortSet, Policy, A >::my_output_ports protected
Definition at line 642 of file _flow_graph_node_impl.h.
template<typename Input , typename OutputPortSet , typename Policy , typename A > const int internal::multifunction_input< Input, OutputPortSet, Policy, A >::N = tbb::flow::tuple_size<OutputPortSet>::value static
Definition at line 571 of file _flow_graph_node_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_node_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.