Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_buffer_impl< Factory > Class Template Reference
tbb::flow::interface10::opencl_buffer_impl< Factory > Class Template Reference
#include <flow_graph_opencl_node.h>
Public Member Functions
opencl_buffer_impl (size_t size, Factory &f)
opencl_buffer_impl (cl_mem m, size_t index, size_t size, Factory &f)
size_t size () const
void map_memory (opencl_device device, opencl_async_msg< void *, Factory > &dmsg) __TBB_override
Public Member Functions inherited from tbb::flow::interface10::opencl_memory< Factory >
opencl_memory ()
opencl_memory (Factory &f)
~opencl_memory ()
cl_mem get_cl_mem () const
void * get_host_ptr ()
Factory * factory () const
opencl_async_msg< void *, Factory > receive (const cl_event *e)
opencl_async_msg< void *, Factory > send (opencl_device device, const cl_event *e)
Private Attributes
size_t my_size
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::opencl_memory< Factory >
cl_mem my_cl_mem
tbb::atomic< opencl_device::device_id_type > my_curr_device_id
void * my_host_ptr
Factory * my_factory
tbb::spin_mutex my_sending_lock
bool my_sending_event_present
cl_event my_sending_event
Detailed Description
template<typename Factory>
class tbb::flow::interface10::opencl_buffer_impl< Factory >
Definition at line 592 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename Factory> tbb::flow::interface10::opencl_buffer_impl< Factory >::opencl_buffer_impl (size_t size, Factory & f) inline
Definition at line 595 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode(), and size.
                                                   : opencl_memory<Factory>( f ), my_size( size ) {
         cl_int err;
         this->my_cl_mem = clCreateBuffer( this->my_factory->context(), CL_MEM_ALLOC_HOST_PTR, size, NULL, &err );
         enforce_cl_retcode( err, "Failed to create an OpenCL buffer" );
     }
template<typename Factory> tbb::flow::interface10::opencl_buffer_impl< Factory >::opencl_buffer_impl (cl_mem m, size_t index, size_t size, Factory & f) inline
Definition at line 602 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
                                                                           : opencl_memory<Factory>( f ), my_size( size ) {
         cl_int err;
         cl_buffer_region region = { index, size };
         this->my_cl_mem = clCreateSubBuffer( m, 0, CL_BUFFER_CREATE_TYPE_REGION, &region, &err );
         enforce_cl_retcode( err, "Failed to create an OpenCL subbuffer" );
     }
Member Function Documentation
template<typename Factory> void tbb::flow::interface10::opencl_buffer_impl< Factory >::map_memory (opencl_device device, opencl_async_msg< void *, Factory > & dmsg) inline virtual
Implements tbb::flow::interface10::opencl_memory< Factory >.
Definition at line 613 of file flow_graph_opencl_node.h.
{
         this->my_factory->enqueue_map_buffer( device, *this, dmsg );
     }
template<typename Factory> size_t tbb::flow::interface10::opencl_buffer_impl< Factory >::size () const inline
Definition at line 609 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_map_buffer().
{
         return my_size;
     }
Member Data Documentation
template<typename Factory> size_t tbb::flow::interface10::opencl_buffer_impl< Factory >::my_size private
Definition at line 593 of file flow_graph_opencl_node.h.
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.