Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::opencl_program< Factory > Class Template Reference
tbb::flow::interface10::opencl_program< Factory > Class Template Reference
#include <flow_graph_opencl_node.h>
Classes
class file_reader
class opencl_device_filter
class opencl_program_builder
Public Types
typedef Factory::kernel_type kernel_type
Public Member Functions
opencl_program (Factory &factory, opencl_program_type type, const std::string &program_name)
opencl_program (Factory &factory, const char *program_name)
opencl_program (Factory &factory, const std::string &program_name)
opencl_program (opencl_program_type type, const std::string &program_name)
opencl_program (const char *program_name)
opencl_program (const std::string &program_name)
opencl_program (opencl_program_type type)
opencl_program (const opencl_program &src)
kernel_type get_kernel (const std::string &k) const
Private Member Functions
opencl_program (Factory &factory, cl_program program)
cl_kernel get_cl_kernel (const std::string &k) const
void init (const std::string &) const
Private Attributes
Factory & my_factory
opencl_program_type my_type
std::string my_arg_str
cl_program my_cl_program
std::once_flag my_do_once_flag
Friends
template<typename DeviceFilter >
class opencl_factory
template<typename DeviceFilter >
class opencl_factory< DeviceFilter >::kernel
Detailed Description
template<typename Factory = opencl_info::default_opencl_factory>
class tbb::flow::interface10::opencl_program< Factory >
Definition at line 56 of file flow_graph_opencl_node.h.
Member Typedef Documentation
template<typename Factory = opencl_info::default_opencl_factory> typedef Factory::kernel_type tbb::flow::interface10::opencl_program< Factory >::kernel_type
Definition at line 1224 of file flow_graph_opencl_node.h.
Constructor & Destructor Documentation
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (Factory & factory, opencl_program_type type, const std::string & program_name) inline
Definition at line 1226 of file flow_graph_opencl_node.h.
 : my_factory( factory ), my_type(type) , my_arg_str( program_name) {}
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (Factory & factory, const char * program_name) inline
Definition at line 1227 of file flow_graph_opencl_node.h.
 : opencl_program( factory, std::string( program_name ) ) {}
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (Factory & factory, const std::string & program_name) inline
Definition at line 1228 of file flow_graph_opencl_node.h.
 : opencl_program( factory, opencl_program_type::SOURCE, program_name ) {}
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (opencl_program_type type, const std::string & program_name) inline
Definition at line 1230 of file flow_graph_opencl_node.h.
 : opencl_program( opencl_info::default_factory(), type, program_name ) {}
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (const char * program_name) inline
Definition at line 1231 of file flow_graph_opencl_node.h.
 : opencl_program( opencl_info::default_factory(), program_name ) {}
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (const std::string & program_name) inline
Definition at line 1232 of file flow_graph_opencl_node.h.
 : opencl_program( opencl_info::default_factory(), program_name ) {}
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (opencl_program_type type) inline
Definition at line 1233 of file flow_graph_opencl_node.h.
 : opencl_program( opencl_info::default_factory(), type ) {}
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (const opencl_program< Factory > & src) inline
Definition at line 1235 of file flow_graph_opencl_node.h.
                                                 : my_factory( src.my_factory ), my_type( src.type ), my_arg_str( src.my_arg_str ), my_cl_program( src.my_cl_program ) {
         // Set my_do_once_flag to the called state.
         std::call_once( my_do_once_flag, [](){} );
     }
template<typename Factory = opencl_info::default_opencl_factory> tbb::flow::interface10::opencl_program< Factory >::opencl_program (Factory & factory, cl_program program) inline private
Definition at line 1245 of file flow_graph_opencl_node.h.
                                                            : my_factory( factory ), my_cl_program( program ) {
         // Set my_do_once_flag to the called state.
         std::call_once( my_do_once_flag, [](){} );
     }
Member Function Documentation
template<typename Factory = opencl_info::default_opencl_factory> cl_kernel tbb::flow::interface10::opencl_program< Factory >::get_cl_kernel (const std::string & k) const inline private
Definition at line 1250 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::enforce_cl_retcode().
{
         std::call_once( my_do_once_flag, [this, &k](){ this->init( k ); } );
         cl_int err;
         cl_kernel kernel = clCreateKernel( my_cl_program, k.c_str(), &err );
         enforce_cl_retcode( err, std::string( "Failed to create kernel: " ) + k );
         return kernel;
     }
template<typename Factory = opencl_info::default_opencl_factory> kernel_type tbb::flow::interface10::opencl_program< Factory >::get_kernel (const std::string & k) const inline
Definition at line 1240 of file flow_graph_opencl_node.h.
{
         return kernel_type( get_cl_kernel(k), my_factory );
     }
template<typename Factory = opencl_info::default_opencl_factory> void tbb::flow::interface10::opencl_program< Factory >::init (const std::string &) const inline private
Definition at line 1333 of file flow_graph_opencl_node.h.
References __TBB_ASSERT, tbb::flow::interface10::opencl_device::compiler_available(), tbb::flow::interface10::opencl_program< Factory >::file_reader::content(), tbb::flow::interface10::enforce_cl_retcode(), tbb::flow::interface10::opencl_program< Factory >::file_reader::length(), tbb::flow::interface10::opencl_device::linker_available(), tbb::flow::interface10::PRECOMPILED, s, tbb::flow::interface10::SOURCE, and tbb::flow::interface10::SPIR.
{
         cl_uint num_devices;
         enforce_cl_retcode( clGetContextInfo( my_factory.context(), CL_CONTEXT_NUM_DEVICES, sizeof( num_devices ), &num_devices, NULL ),
             "Failed to get OpenCL context info" );
         if ( !num_devices )
             enforce_cl_retcode( CL_DEVICE_NOT_FOUND, "No supported devices found" );
         cl_device_id *device_list = (cl_device_id *)alloca( num_devices*sizeof( cl_device_id ) );
         enforce_cl_retcode( clGetContextInfo( my_factory.context(), CL_CONTEXT_DEVICES, num_devices*sizeof( cl_device_id ), device_list, NULL ),
             "Failed to get OpenCL context info" );
         const char *options = NULL;
         switch ( my_type ) {
         case opencl_program_type::SOURCE: {
             file_reader fr( my_arg_str );
             const char *s[] = { fr.content() };
             const size_t l[] = { fr.length() };
             cl_int err;
             my_cl_program = clCreateProgramWithSource( my_factory.context(), 1, s, l, &err );
             enforce_cl_retcode( err, std::string( "Failed to create program: " ) + my_arg_str );
             opencl_device_filter(
                 num_devices, device_list,
                 []( const opencl_device& d ) -> bool {
                     return !d.compiler_available() || !d.linker_available();
                 }, "No one device supports building program from sources" );
             opencl_program_builder(
                 my_factory, my_arg_str, my_cl_program, num_devices, device_list,
                 options, /*callback*/ NULL, /*user data*/NULL );
             break;
         }
         case opencl_program_type::SPIR:
             options = "-x spir";
         case opencl_program_type::PRECOMPILED: {
             file_reader fr( my_arg_str );
             std::vector<const unsigned char*> s(
                 num_devices, reinterpret_cast<const unsigned char*>(fr.content()) );
             std::vector<size_t> l( num_devices, fr.length() );
             std::vector<cl_int> bin_statuses( num_devices, -1 );
             cl_int err;
             my_cl_program = clCreateProgramWithBinary( my_factory.context(), num_devices,
                                                        device_list, l.data(), s.data(),
                                                        bin_statuses.data(), &err );
             if( err != CL_SUCCESS ) {
                 std::string statuses_str;
                 for (auto st = bin_statuses.begin(); st != bin_statuses.end(); ++st) {
                     statuses_str += std::to_string((*st));
                 }
                 enforce_cl_retcode( err, std::string( "Failed to create program, error " + std::to_string( err ) + " : " ) + my_arg_str +
                                     std::string( ", binary_statuses = " ) + statuses_str );
             }
             opencl_program_builder(
                 my_factory, my_arg_str, my_cl_program, num_devices, device_list,
                 options, /*callback*/ NULL, /*user data*/NULL );
             break;
         }
         default:
             __TBB_ASSERT( false, "Unsupported program type" );
         }
     }
Friends And Related Function Documentation
template<typename Factory = opencl_info::default_opencl_factory> template<typename DeviceFilter > friend class opencl_factory friend
Definition at line 1399 of file flow_graph_opencl_node.h.
template<typename Factory = opencl_info::default_opencl_factory> template<typename DeviceFilter > friend class opencl_factory< DeviceFilter >::kernel friend
Definition at line 1402 of file flow_graph_opencl_node.h.
Member Data Documentation
template<typename Factory = opencl_info::default_opencl_factory> std::string tbb::flow::interface10::opencl_program< Factory >::my_arg_str private
Definition at line 1394 of file flow_graph_opencl_node.h.
template<typename Factory = opencl_info::default_opencl_factory> cl_program tbb::flow::interface10::opencl_program< Factory >::my_cl_program mutable private
Definition at line 1395 of file flow_graph_opencl_node.h.
template<typename Factory = opencl_info::default_opencl_factory> std::once_flag tbb::flow::interface10::opencl_program< Factory >::my_do_once_flag mutable private
Definition at line 1396 of file flow_graph_opencl_node.h.
template<typename Factory = opencl_info::default_opencl_factory> Factory& tbb::flow::interface10::opencl_program< Factory >::my_factory private
Definition at line 1392 of file flow_graph_opencl_node.h.
template<typename Factory = opencl_info::default_opencl_factory> opencl_program_type tbb::flow::interface10::opencl_program< Factory >::my_type private
Definition at line 1393 of file flow_graph_opencl_node.h.
The documentation for this class was generated from the following file:
flow_graph_opencl_node.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.