Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::reader_writer_lock Class Reference
tbb::interface5::reader_writer_lock Class Reference
Synchronization
Writer-preference reader-writer lock with local-only spinning on readers.
#include <reader_writer_lock.h>
Classes
class scoped_lock
The scoped lock pattern for write locks.
class scoped_lock_read
The scoped lock pattern for read locks.
Public Types
enum status_t { waiting_nonblocking, waiting, active, invalid }
Status type for nodes associated with lock instances.
Public Member Functions
reader_writer_lock ()
Constructs a new reader_writer_lock.
~reader_writer_lock ()
Destructs a reader_writer_lock object.
void __TBB_EXPORTED_METHOD lock ()
Acquires the reader_writer_lock for write.
bool __TBB_EXPORTED_METHOD try_lock ()
Tries to acquire the reader_writer_lock for write.
void __TBB_EXPORTED_METHOD lock_read ()
Acquires the reader_writer_lock for read.
bool __TBB_EXPORTED_METHOD try_lock_read ()
Tries to acquire the reader_writer_lock for read.
void __TBB_EXPORTED_METHOD unlock ()
Releases the reader_writer_lock.
Private Member Functions
void __TBB_EXPORTED_METHOD internal_construct ()
void __TBB_EXPORTED_METHOD internal_destroy ()
bool start_write (scoped_lock *)
Attempts to acquire write lock.
void set_next_writer (scoped_lock *w)
Sets writer_head to w and attempts to unblock.
void end_write (scoped_lock *)
Relinquishes write lock to next waiting writer or group of readers.
bool is_current_writer ()
Checks if current thread holds write lock.
void start_read (scoped_lock_read *)
Attempts to acquire read lock.
void unblock_readers ()
Unblocks pending readers.
void end_read ()
Relinquishes read lock by decrementing counter; last reader wakes pending writer.
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
atomic< scoped_lock_read * > reader_head
The list of pending readers.
atomic< scoped_lock * > writer_head
The list of pending writers.
atomic< scoped_lock * > writer_tail
The last node in the list of pending writers.
tbb_thread::id my_current_writer
Writer that owns the mutex; tbb_thread::id() otherwise.
atomic< uintptr_t > rdr_count_and_flags
Status of mutex.
Friends
class scoped_lock
class scoped_lock_read
Detailed Description
Writer-preference reader-writer lock with local-only spinning on readers.
Loosely adapted from Mellor-Crummey and Scott pseudocode at http://www.cs.rochester.edu/research/synchronization/pseudocode/rw.html#s_wp
Definition at line 34 of file reader_writer_lock.h.
Member Enumeration Documentation
enum tbb::interface5::reader_writer_lock::status_t
Status type for nodes associated with lock instances.
waiting_nonblocking: the wait state for nonblocking lock instances; for writes, these transition straight to active states; for reads, these are unused.
waiting: the start and spin state for all lock instances; these will transition to active state when appropriate. Non-blocking write locks transition from this state to waiting_nonblocking immediately.
active: the active state means that the lock instance holds the lock; it will transition to invalid state during node deletion
invalid: the end state for all nodes; this is set in the destructor so if we encounter this state, we are looking at memory that has already been freed
The state diagrams below describe the status transitions. Single arrows indicate that the thread that owns the node is responsible for the transition; double arrows indicate that any thread could make the transition.
State diagram for scoped_lock status:
waiting -------—> waiting_nonblocking | _____________/ | V V V active --------------—> invalid
State diagram for scoped_lock_read status:
waiting | V active --------------—>invalid
Enumerator
waiting_nonblocking
waiting
active
invalid
Definition at line 74 of file reader_writer_lock.h.
 { waiting_nonblocking, waiting, active, invalid };
Constructor & Destructor Documentation
tbb::interface5::reader_writer_lock::reader_writer_lock () inline
Constructs a new reader_writer_lock.
Definition at line 77 of file reader_writer_lock.h.
References internal_construct().
{
         internal_construct();
     }
tbb::interface5::reader_writer_lock::~reader_writer_lock () inline
Destructs a reader_writer_lock object.
Definition at line 82 of file reader_writer_lock.h.
References internal_destroy().
{
         internal_destroy();
     }
Member Function Documentation
void tbb::interface5::reader_writer_lock::end_read () private
Relinquishes read lock by decrementing counter; last reader wakes pending writer.
Definition at line 286 of file reader_writer_lock.cpp.
References __TBB_ASSERT, ITT_NOTIFY, tbb::interface5::RC_INCR, rdr_count_and_flags, and sync_releasing.
Referenced by unlock().
{
     ITT_NOTIFY(sync_releasing, this);
     __TBB_ASSERT(rdr_count_and_flags >= RC_INCR, "unlock() called but no readers hold the lock.");
     rdr_count_and_flags -= RC_INCR;
 }
void tbb::interface5::reader_writer_lock::end_write (scoped_lock * I) private
Relinquishes write lock to next waiting writer or group of readers.
Definition at line 264 of file reader_writer_lock.cpp.
References __TBB_ASSERT, active, tbb::interface5::fetch_and_and(), id, ITT_NOTIFY, my_current_writer, tbb::interface5::reader_writer_lock::scoped_lock::next, rdr_count_and_flags, set_next_writer(), tbb::internal::spin_wait_while_eq(), sync_releasing, unblock_readers(), writer_head, and writer_tail.
Referenced by unlock().
{
     __TBB_ASSERT(I==writer_head, "Internal error: can't unlock a thread that is not holding the lock.");
     my_current_writer = tbb_thread::id();
     ITT_NOTIFY(sync_releasing, this);
     if (I->next) { // potentially more writers
         writer_head = I->next;
         writer_head->status = active;
     }
     else { // No more writers; clear writer flag, test reader interest flag
         __TBB_ASSERT(writer_head, NULL);
         if (fetch_and_and(rdr_count_and_flags, ~(WFLAG1+WFLAG2)) & RFLAG) {
             unblock_readers();
         }
         writer_head.fetch_and_store(NULL);
         if (I != writer_tail.compare_and_swap(NULL, I)) { // an incoming writer is in the process of being added
             spin_wait_while_eq(I->next, (scoped_lock *)NULL);  // wait for new writer to be added
             __TBB_ASSERT(I->next, "There should be a node following the last writer.");
             set_next_writer(I->next);
         }
     }
 }
void tbb::interface5::reader_writer_lock::internal_construct () private
Definition at line 75 of file reader_writer_lock.cpp.
References _T, id, ITT_SYNC_CREATE, my_current_writer, rdr_count_and_flags, reader_head, writer_head, and writer_tail.
Referenced by reader_writer_lock().
{
     reader_head = NULL;
     writer_head = NULL;
     writer_tail = NULL;
     rdr_count_and_flags = 0;
     my_current_writer = tbb_thread::id();
 #if TBB_USE_THREADING_TOOLS
     ITT_SYNC_CREATE(this, _T("tbb::reader_writer_lock"), _T(""));
 #endif /* TBB_USE_THREADING_TOOLS */
 }
void tbb::interface5::reader_writer_lock::internal_destroy () private
Definition at line 86 of file reader_writer_lock.cpp.
References __TBB_ASSERT, rdr_count_and_flags, reader_head, writer_head, and writer_tail.
Referenced by ~reader_writer_lock().
{
     __TBB_ASSERT(rdr_count_and_flags==0, "reader_writer_lock destroyed with pending readers/writers.");
     __TBB_ASSERT(reader_head==NULL, "reader_writer_lock destroyed with pending readers.");
     __TBB_ASSERT(writer_tail==NULL, "reader_writer_lock destroyed with pending writers.");
     __TBB_ASSERT(writer_head==NULL, "reader_writer_lock destroyed with pending/active writers.");
 }
bool tbb::interface5::reader_writer_lock::is_current_writer () inline private
Checks if current thread holds write lock.
Definition at line 292 of file reader_writer_lock.cpp.
References tbb::this_tbb_thread::get_id(), and my_current_writer.
Referenced by lock(), lock_read(), try_lock(), try_lock_read(), and unlock().
{
     return my_current_writer==this_tbb_thread::get_id();
 }
void tbb::interface5::reader_writer_lock::lock ()
Acquires the reader_writer_lock for write.
If the lock is currently held in write mode by another context, the writer will block by spinning on a local variable. Exceptions thrown: improper_lock The context tries to acquire a reader_writer_lock that it already has write ownership of.
Definition at line 97 of file reader_writer_lock.cpp.
References tbb::internal::eid_improper_lock, is_current_writer(), scoped_lock, start_write(), tbb::internal::throw_exception(), and void.
Referenced by tbb::interface5::reader_writer_lock::scoped_lock::internal_construct(), and tbb::interface5::reader_writer_lock::scoped_lock_read::internal_construct().
{
     if (is_current_writer()) { // recursive lock attempt
         // we don't support recursive writer locks; throw exception
         tbb::internal::throw_exception(tbb::internal::eid_improper_lock);
     }
     else {
         scoped_lock *a_writer_lock = new scoped_lock();
         (void) start_write(a_writer_lock);
     }
 }
void tbb::interface5::reader_writer_lock::lock_read ()
Acquires the reader_writer_lock for read.
If the lock is currently held by a writer, this reader will block and wait until the writers are done. Exceptions thrown: improper_lock The context tries to acquire a reader_writer_lock that it already has write ownership of.
Definition at line 184 of file reader_writer_lock.cpp.
References tbb::internal::eid_improper_lock, is_current_writer(), start_read(), and tbb::internal::throw_exception().
{
     if (is_current_writer()) { // recursive lock attempt
         // we don't support writer->reader downgrade; throw exception
         tbb::internal::throw_exception(tbb::internal::eid_improper_lock);
     }
     else {
         scoped_lock_read a_reader_lock;
         start_read(&a_reader_lock);
     }
 }
void tbb::interface5::reader_writer_lock::set_next_writer (scoped_lock * w) private
Sets writer_head to w and attempts to unblock.
Definition at line 161 of file reader_writer_lock.cpp.
References __TBB_AtomicOR(), active, tbb::internal::atomic_impl< T >::compare_and_swap(), tbb::interface5::fetch_and_or(), rdr_count_and_flags, tbb::interface5::RFLAG, tbb::interface5::spin_wait_until_and(), tbb::interface5::spin_wait_while_geq(), tbb::interface5::reader_writer_lock::scoped_lock::status, waiting_nonblocking, and writer_head.
Referenced by end_write(), and start_write().
{
     writer_head = W;
     if (W->status == waiting_nonblocking) {
         if (rdr_count_and_flags.compare_and_swap(WFLAG1+WFLAG2, 0) == 0) {
             W->status = active;
         }
     }
     else {
         if (fetch_and_or(rdr_count_and_flags, WFLAG1) & RFLAG) { // reader present
             spin_wait_until_and(rdr_count_and_flags, WFLAG2); // block until readers set WFLAG2
         }
         else { // no reader in timing window
             __TBB_AtomicOR(&rdr_count_and_flags, WFLAG2);
         }
         spin_wait_while_geq(rdr_count_and_flags, RC_INCR); // block until readers finish
         W->status = active;
    }
 }
void tbb::interface5::reader_writer_lock::start_read (scoped_lock_read * I) private
Attempts to acquire read lock.
If unavailable, spins in blocking case, returns false in non-blocking case.
Definition at line 213 of file reader_writer_lock.cpp.
References __TBB_ASSERT, active, tbb::interface5::fetch_and_or(), ITT_NOTIFY, tbb::interface5::reader_writer_lock::scoped_lock_read::next, tbb::interface5::RC_INCR, rdr_count_and_flags, reader_head, tbb::internal::spin_wait_while_eq(), tbb::interface5::reader_writer_lock::scoped_lock_read::status, unblock_readers(), and waiting.
Referenced by lock_read().
{
     ITT_NOTIFY(sync_prepare, this);
     I->next = reader_head.fetch_and_store(I);
     if (!I->next) { // first arriving reader in my group; set RFLAG, test writer flags
         // unblock and/or update statuses of non-blocking readers
         if (!(fetch_and_or(rdr_count_and_flags, RFLAG) & (WFLAG1+WFLAG2))) { // no writers
             unblock_readers();
         }
     }
     __TBB_ASSERT(I->status == waiting || I->status == active, "Lock requests should be waiting or active before blocking.");
     spin_wait_while_eq(I->status, waiting); // block
     if (I->next) {
         __TBB_ASSERT(I->next->status == waiting, NULL);
         rdr_count_and_flags += RC_INCR;
         I->next->status = active; // wake successor
     }
     ITT_NOTIFY(sync_acquired, this);
 }
bool tbb::interface5::reader_writer_lock::start_write (scoped_lock * I) private
Attempts to acquire write lock.
If unavailable, spins in blocking case, returns false in non-blocking case.
Definition at line 122 of file reader_writer_lock.cpp.
References __TBB_ASSERT, tbb::this_tbb_thread::get_id(), id, ITT_NOTIFY, my_current_writer, tbb::interface5::reader_writer_lock::scoped_lock::next, set_next_writer(), tbb::internal::spin_wait_while_eq(), tbb::interface5::reader_writer_lock::scoped_lock::status, waiting, waiting_nonblocking, writer_head, and writer_tail.
Referenced by lock(), and try_lock().
{
     tbb_thread::id id = this_tbb_thread::get_id();
     scoped_lock *pred = NULL;
     if (I->status == waiting_nonblocking) {
         if ((pred = writer_tail.compare_and_swap(I, NULL)) != NULL) {
             delete I;
             return false;
         }
     }
     else {
         ITT_NOTIFY(sync_prepare, this);
         pred = writer_tail.fetch_and_store(I);
     }
     if (pred)
         pred->next = I;
     else {
         set_next_writer(I);
         if (I->status == waiting_nonblocking) {
             if (I->next) { // potentially more writers
                 set_next_writer(I->next);
             }
             else { // no more writers
                 writer_head.fetch_and_store(NULL);
                 if (I != writer_tail.compare_and_swap(NULL, I)) { // an incoming writer is in the process of being added
                     spin_wait_while_eq(I->next, (scoped_lock *)NULL);  // wait for new writer to be added
                     __TBB_ASSERT(I->next, "There should be a node following the last writer.");
                     set_next_writer(I->next);
                 }
             }
             delete I;
             return false;
         }
     }
     spin_wait_while_eq(I->status, waiting);
     ITT_NOTIFY(sync_acquired, this);
     my_current_writer = id;
     return true;
 }
bool tbb::interface5::reader_writer_lock::try_lock ()
Tries to acquire the reader_writer_lock for write.
This function does not block. Return Value: True or false, depending on whether the lock is acquired or not. If the lock is already held by this acquiring context, try_lock() returns false.
Definition at line 111 of file reader_writer_lock.cpp.
References is_current_writer(), scoped_lock, start_write(), tbb::interface5::reader_writer_lock::scoped_lock::status, and waiting_nonblocking.
{
     if (is_current_writer()) { // recursive lock attempt
         return false;
     }
     else {
         scoped_lock *a_writer_lock = new scoped_lock();
         a_writer_lock->status = waiting_nonblocking;
         return start_write(a_writer_lock);
     }
 }
bool tbb::interface5::reader_writer_lock::try_lock_read ()
Tries to acquire the reader_writer_lock for read.
This function does not block. Return Value: True or false, depending on whether the lock is acquired or not.
Definition at line 197 of file reader_writer_lock.cpp.
References is_current_writer(), ITT_NOTIFY, tbb::interface5::RC_INCR, rdr_count_and_flags, and tbb::interface5::WFLAG2.
{
     if (is_current_writer()) { // recursive lock attempt
         return false;
     }
     else {
         if (rdr_count_and_flags.fetch_and_add(RC_INCR) & (WFLAG1+WFLAG2)) { // writers present
             rdr_count_and_flags -= RC_INCR;
             return false;
         }
         else { // no writers
             ITT_NOTIFY(sync_acquired, this);
             return true;
         }
     }
 }
void tbb::interface5::reader_writer_lock::unblock_readers () private
Unblocks pending readers.
Definition at line 232 of file reader_writer_lock.cpp.
References __TBB_ASSERT, __TBB_AtomicOR(), active, head, rdr_count_and_flags, reader_head, tbb::interface5::RFLAG, tbb::interface5::reader_writer_lock::scoped_lock_read::status, and waiting.
Referenced by end_write(), and start_read().
{
     // clear rdr interest flag, increment rdr count
     __TBB_ASSERT(rdr_count_and_flags&RFLAG, NULL);
     rdr_count_and_flags += RC_INCR-RFLAG;
     __TBB_ASSERT(rdr_count_and_flags >= RC_INCR, NULL);
     // indicate clear of window
     if (rdr_count_and_flags & WFLAG1 && !(rdr_count_and_flags & WFLAG2)) {
         __TBB_AtomicOR(&rdr_count_and_flags, WFLAG2);
     }
     // unblock waiting readers
     scoped_lock_read *head = reader_head.fetch_and_store(NULL);
     __TBB_ASSERT(head, NULL);
     __TBB_ASSERT(head->status == waiting, NULL);
     head->status = active;
 }
void tbb::interface5::reader_writer_lock::unlock ()
Releases the reader_writer_lock.
Definition at line 249 of file reader_writer_lock.cpp.
References __TBB_ASSERT, active, end_read(), end_write(), id, is_current_writer(), my_current_writer, and writer_head.
{
     if( my_current_writer!=tbb_thread::id() ) {
         // A writer owns the lock
         __TBB_ASSERT(is_current_writer(), "caller of reader_writer_lock::unlock() does not own the lock.");
         __TBB_ASSERT(writer_head, NULL);
         __TBB_ASSERT(writer_head->status==active, NULL);
         scoped_lock *a_writer_lock = writer_head;
         end_write(a_writer_lock);
         __TBB_ASSERT(a_writer_lock != writer_head, "Internal error: About to turn writer_head into dangling reference.");
         delete a_writer_lock;
     } else {
         end_read();
     }
 }
Friends And Related Function Documentation
friend class scoped_lock friend
Definition at line 36 of file reader_writer_lock.h.
Referenced by lock(), and try_lock().
friend class scoped_lock_read friend
Definition at line 37 of file reader_writer_lock.h.
Member Data Documentation
tbb_thread::id tbb::interface5::reader_writer_lock::my_current_writer private
Writer that owns the mutex; tbb_thread::id() otherwise.
Definition at line 221 of file reader_writer_lock.h.
Referenced by end_write(), internal_construct(), is_current_writer(), start_write(), and unlock().
atomic<uintptr_t> tbb::interface5::reader_writer_lock::rdr_count_and_flags private
Status of mutex.
Definition at line 223 of file reader_writer_lock.h.
Referenced by end_read(), end_write(), internal_construct(), internal_destroy(), set_next_writer(), start_read(), try_lock_read(), and unblock_readers().
atomic<scoped_lock_read*> tbb::interface5::reader_writer_lock::reader_head private
The list of pending readers.
Definition at line 215 of file reader_writer_lock.h.
Referenced by internal_construct(), internal_destroy(), start_read(), and unblock_readers().
atomic<scoped_lock*> tbb::interface5::reader_writer_lock::writer_head private
The list of pending writers.
Definition at line 217 of file reader_writer_lock.h.
Referenced by end_write(), internal_construct(), internal_destroy(), set_next_writer(), start_write(), and unlock().
atomic<scoped_lock*> tbb::interface5::reader_writer_lock::writer_tail private
The last node in the list of pending writers.
Definition at line 219 of file reader_writer_lock.h.
Referenced by end_write(), internal_construct(), internal_destroy(), and start_write().
The documentation for this class was generated from the following files:
reader_writer_lock.h
reader_writer_lock.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.