Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::concurrent_vector_base_v3::segment_t Class Reference
tbb::internal::concurrent_vector_base_v3::segment_t Class Reference
#include <concurrent_vector.h>
Public Member Functions
segment_t ()
segment_t (segment_t const &rhs)
void swap (segment_t &rhs)
segment_t & operator= (segment_t const &rhs)
template<memory_semantics M>
segment_value_t load () const
template<memory_semantics M>
void store (segment_not_used)
template<memory_semantics M>
void store (segment_allocation_failed)
template<memory_semantics M>
void store (void *allocated_segment_pointer) __TBB_NOEXCEPT(true)
Private Attributes
atomic< void * > array
Detailed Description
Definition at line 129 of file concurrent_vector.h.
Constructor & Destructor Documentation
tbb::internal::concurrent_vector_base_v3::segment_t::segment_t () inline
Definition at line 132 of file concurrent_vector.h.
 { store<relaxed>(segment_not_used());}
tbb::internal::concurrent_vector_base_v3::segment_t::segment_t (segment_t const & rhs) inline
Definition at line 136 of file concurrent_vector.h.
References array, tbb::internal::atomic_impl< T >::load(), tbb::relaxed, and tbb::internal::atomic_impl< T >::store().
 { array.store<relaxed>(rhs.array.load<relaxed>());}
Member Function Documentation
template<memory_semantics M> segment_value_t tbb::internal::concurrent_vector_base_v3::segment_t::load () const inline
Definition at line 148 of file concurrent_vector.h.
References tbb::internal::atomic_impl< T >::load().
Referenced by tbb::internal::concurrent_vector_base_v3::helper::acquire_segment(), tbb::internal::concurrent_vector_base_v3::helper::cleanup(), tbb::internal::concurrent_vector_base_v3::helper::enable_segment(), tbb::internal::concurrent_vector_base_v3::helper::extend_segment_table(), tbb::internal::concurrent_vector_base_v3::helper::get_segment_value(), tbb::internal::concurrent_vector_base_v3::internal_compact(), tbb::concurrent_vector< T, A >::internal_free_segments(), tbb::internal::concurrent_vector_base_v3::internal_grow_to_at_least_with_result(), tbb::internal::concurrent_vector_base_v3::internal_push_back(), tbb::internal::concurrent_vector_base_v3::helper::segment_not_used_predicate::operator()(), tbb::internal::concurrent_vector_base_v3::helper::safe_init_body::operator()(), and tbb::internal::concurrent_vector_base_v3::helper::destroy_body::operator()().
 { return segment_value_t(array.load<M>());}
segment_t& tbb::internal::concurrent_vector_base_v3::segment_t::operator= (segment_t const & rhs) inline
Definition at line 142 of file concurrent_vector.h.
References array, tbb::internal::atomic_impl< T >::load(), tbb::relaxed, and tbb::internal::atomic_impl< T >::store().
{
                 array.store<relaxed>(rhs.array.load<relaxed>());
                 return *this;
             }
template<memory_semantics M> void tbb::internal::concurrent_vector_base_v3::segment_t::store (segment_not_used) inline
Definition at line 151 of file concurrent_vector.h.
References tbb::internal::atomic_impl< T >::store().
Referenced by tbb::internal::concurrent_vector_base_v3::internal_compact(), tbb::concurrent_vector< T, A >::internal_free_segments(), and tbb::internal::concurrent_vector_base_v3::helper::publish_segment().
{
                 array.store<M>(0);
             }
template<memory_semantics M> void tbb::internal::concurrent_vector_base_v3::segment_t::store (segment_allocation_failed) inline
Definition at line 156 of file concurrent_vector.h.
References __TBB_ASSERT, tbb::internal::atomic_impl< T >::store(), and tbb::internal::vector_allocation_error_flag.
{
                 __TBB_ASSERT(load<relaxed>() != segment_allocated(),"transition from \"allocated\" to \"allocation failed\" state looks non-logical");
                 array.store<M>(internal::vector_allocation_error_flag);
             }
template<memory_semantics M> void tbb::internal::concurrent_vector_base_v3::segment_t::store (void * allocated_segment_pointer) inline
Definition at line 162 of file concurrent_vector.h.
References __TBB_ASSERT, __TBB_NOEXCEPT, tbb::internal::atomic_impl< T >::store(), and tbb::internal::concurrent_vector_base_v3::swap.
{
                 __TBB_ASSERT(segment_value_t(allocated_segment_pointer) == segment_allocated(),
                      "other overloads of store should be used for marking segment as not_used or allocation_failed" );
                 array.store<M>(allocated_segment_pointer);
             }
void tbb::internal::concurrent_vector_base_v3::segment_t::swap (segment_t & rhs) inline
Definition at line 138 of file concurrent_vector.h.
References array.
{
                 tbb::internal::swap<relaxed>(array, rhs.array);
             }
Member Data Documentation
atomic<void*> tbb::internal::concurrent_vector_base_v3::segment_t::array private
Definition at line 130 of file concurrent_vector.h.
Referenced by operator=(), segment_t(), and swap().
The documentation for this class was generated from the following file:
concurrent_vector.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.