Intel(R) Threading Building Blocks Doxygen Documentation: internal::predecessor_cache< T, M > Class Template Reference
internal::predecessor_cache< T, M > Class Template Reference
A cache of predecessors that only supports try_get.
#include <_flow_graph_cache_impl.h>
Public Types
typedef M mutex_type
typedef T output_type
typedef sender< output_type > predecessor_type
typedef receiver< output_type > successor_type
Public Types inherited from internal::node_cache< T, M >
typedef size_t size_type
Public Member Functions
predecessor_cache ()
void set_owner (successor_type *owner)
bool get_item (output_type &v)
void reset ()
Public Member Functions inherited from internal::node_cache< T, M >
bool empty ()
void add (T &n)
void remove (T &n)
void clear ()
Protected Attributes
successor_type * my_owner
Protected Attributes inherited from internal::node_cache< T, M >
mutex_type my_mutex
std::queue< T * > my_q
Additional Inherited Members
Protected Types inherited from internal::node_cache< T, M >
typedef M mutex_type
Protected Member Functions inherited from internal::node_cache< T, M >
bool internal_empty ()
size_type internal_size ()
void internal_push (T &n)
T & internal_pop ()
Detailed Description
template<typename T, typename M = spin_mutex>
class internal::predecessor_cache< T, M >
A cache of predecessors that only supports try_get.
Definition at line 130 of file _flow_graph_cache_impl.h.
Member Typedef Documentation
template<typename T, typename M = spin_mutex> typedef M internal::predecessor_cache< T, M >::mutex_type
Definition at line 133 of file _flow_graph_cache_impl.h.
template<typename T, typename M = spin_mutex> typedef T internal::predecessor_cache< T, M >::output_type
Definition at line 134 of file _flow_graph_cache_impl.h.
template<typename T, typename M = spin_mutex> typedef sender<output_type> internal::predecessor_cache< T, M >::predecessor_type
Definition at line 139 of file _flow_graph_cache_impl.h.
template<typename T, typename M = spin_mutex> typedef receiver<output_type> internal::predecessor_cache< T, M >::successor_type
Definition at line 140 of file _flow_graph_cache_impl.h.
Constructor & Destructor Documentation
template<typename T, typename M = spin_mutex> internal::predecessor_cache< T, M >::predecessor_cache () inline
Definition at line 143 of file _flow_graph_cache_impl.h.
 : my_owner( NULL ) { }
Member Function Documentation
template<typename T, typename M = spin_mutex> bool internal::predecessor_cache< T, M >::get_item (output_type & v) inline
Definition at line 147 of file _flow_graph_cache_impl.h.
Referenced by internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::perform_queued_requests().
{
         bool msg = false;
         do {
             predecessor_type *src;
             {
                 typename mutex_type::scoped_lock lock(this->my_mutex);
                 if ( this->internal_empty() ) {
                     break;
                 }
                 src = &this->internal_pop();
             }
             // Try to get from this sender
             msg = src->try_get( v );
             if (msg == false) {
                 // Relinquish ownership of the edge
                 if (my_owner)
                     src->register_successor( *my_owner );
             } else {
                 // Retain ownership of the edge
                 this->add(*src);
             }
         } while ( msg == false );
         return msg;
     }
template<typename T, typename M = spin_mutex> void internal::predecessor_cache< T, M >::reset () inline
Definition at line 177 of file _flow_graph_cache_impl.h.
Referenced by internal::reservable_predecessor_cache< T, null_mutex >::reset(), and internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::reset_receiver().
                  {
         if (my_owner) {
             for(;;) {
                 predecessor_type *src;
                 {
                     if (this->internal_empty()) break;
                     src = &this->internal_pop();
                 }
                 src->register_successor( *my_owner );
             }
         }
     }
template<typename T, typename M = spin_mutex> void internal::predecessor_cache< T, M >::set_owner (successor_type * owner) inline
Definition at line 145 of file _flow_graph_cache_impl.h.
 { my_owner = owner; }
Member Data Documentation
template<typename T, typename M = spin_mutex> successor_type* internal::predecessor_cache< T, M >::my_owner protected
Definition at line 195 of file _flow_graph_cache_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_cache_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.