Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::internal::reservable_predecessor_cache< T, M > Class Template Reference
tbb::flow::interface10::internal::reservable_predecessor_cache< T, M > Class Template Reference
An cache of predecessors that supports requests and reservations.
#include <flow_graph.h>
Public Types
typedef M mutex_type
typedef T output_type
typedef untyped_sender predecessor_type
typedef untyped_receiver successor_type
Public Types inherited from tbb::flow::interface10::internal::predecessor_cache< T, M >
typedef M mutex_type
typedef T output_type
typedef untyped_sender predecessor_type
typedef untyped_receiver successor_type
Public Types inherited from tbb::flow::interface10::internal::node_cache< untyped_sender, M >
typedef size_t size_type
Public Member Functions
reservable_predecessor_cache ()
bool try_reserve (output_type &v)
bool try_release ()
bool try_consume ()
void reset ()
void clear ()
Public Member Functions inherited from tbb::flow::interface10::internal::predecessor_cache< T, M >
predecessor_cache ()
void set_owner (successor_type *owner)
bool get_item (output_type &v)
void reset ()
Public Member Functions inherited from tbb::flow::interface10::internal::node_cache< untyped_sender, M >
bool empty ()
void add (untyped_sender &n)
void remove (untyped_sender &n)
void clear ()
Private Attributes
predecessor_type * reserved_src
Additional Inherited Members
Protected Types inherited from tbb::flow::interface10::internal::node_cache< untyped_sender, M >
typedef M mutex_type
Protected Member Functions inherited from tbb::flow::interface10::internal::node_cache< untyped_sender, M >
bool internal_empty ()
size_type internal_size ()
void internal_push (untyped_sender &n)
untyped_sender & internal_pop ()
Protected Attributes inherited from tbb::flow::interface10::internal::predecessor_cache< T, M >
successor_type * my_owner
Protected Attributes inherited from tbb::flow::interface10::internal::node_cache< untyped_sender, M >
mutex_type my_mutex
std::queue< untyped_sender * > my_q
Detailed Description
template<typename T, typename M = spin_mutex>
class tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >
An cache of predecessors that supports requests and reservations.
Definition at line 111 of file flow_graph.h.
Member Typedef Documentation
template<typename T, typename M = spin_mutex> typedef M tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::mutex_type
Definition at line 204 of file flow_graph.h.
template<typename T, typename M = spin_mutex> typedef T tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::output_type
Definition at line 205 of file flow_graph.h.
template<typename T, typename M = spin_mutex> typedef untyped_sender tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::predecessor_type
Definition at line 207 of file flow_graph.h.
template<typename T, typename M = spin_mutex> typedef untyped_receiver tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::successor_type
Definition at line 208 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T, typename M = spin_mutex> tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::reservable_predecessor_cache () inline
Definition at line 214 of file flow_graph.h.
 {
Member Function Documentation
template<typename T, typename M = spin_mutex> void tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::clear () inline
Definition at line 265 of file flow_graph.h.
Referenced by tbb::flow::interface10::limiter_node< T >::reset_node().
              {
             // This (T) is async and incoming 'X t' is NOT async
             // Create async_msg for X
template<typename T, typename M = spin_mutex> void tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::reset () inline
Definition at line 260 of file flow_graph.h.
Referenced by tbb::flow::interface10::limiter_node< T >::reset_node().
{
         if (is_async) {
             // Both are async
template<typename T, typename M = spin_mutex> bool tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::try_consume () inline
Definition at line 254 of file flow_graph.h.
Referenced by tbb::flow::interface10::limiter_node< T >::forward_task().
{
         return *static_cast<T*>(static_cast<async_msg<filtered_type>*>(p));
     }
template<typename T, typename M = spin_mutex> bool tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::try_release () inline
Definition at line 247 of file flow_graph.h.
Referenced by tbb::flow::interface10::limiter_node< T >::forward_task().
{
         return static_cast<void*>(&static_cast<async_msg<filtered_type>&>(t));
     }
     // Sender-classes use non-const interfaces
template<typename T, typename M = spin_mutex> bool tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::try_reserve (output_type & v) inline
Definition at line 217 of file flow_graph.h.
Referenced by tbb::flow::interface10::limiter_node< T >::forward_task().
{
         if (is_async) {
             // This (T) is NOT async and incoming 'A<X> t' IS async
             // Get data from async_msg
             const async_msg<filtered_type>& msg = async_helpers< async_msg<filtered_type> >::from_void_ptr(p);
             task* const new_task = msg.my_storage->subscribe(*this_recv, this_recv->graph_reference());
             // finalize() must be called after subscribe() because set() can be called in finalize()
             // and 'this_recv' client must be subscribed by this moment
             msg.finalize();
             return new_task;
         }
         else {
             // Incoming 't' is NOT async
             return this_recv->try_put_task(from_void_ptr(p));
         }
     }
 };
 template< typename T >
 struct async_helpers< T, typename std::enable_if< std::is_base_of<async_msg<typename T::async_msg_data_type>, T>::value >::type > {
     typedef T async_type;
     typedef typename T::async_msg_data_type filtered_type;
     static const bool is_async_type = true;
     // Receiver-classes use const interfaces
     static const void* to_void_ptr(const T& t) {
         return static_cast<const void*>(&static_cast<const async_msg<filtered_type>&>(t));
Member Data Documentation
template<typename T, typename M = spin_mutex> predecessor_type* tbb::flow::interface10::internal::reservable_predecessor_cache< T, M >::reserved_src private
Definition at line 271 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.