Intel(R) Threading Building Blocks Doxygen Documentation: internal::reservable_item_buffer< T, A > Class Template Reference
internal::reservable_item_buffer< T, A > Class Template Reference
item_buffer with reservable front-end. NOTE: if reserving, do not
#include <_flow_graph_item_buffer_impl.h>
Public Member Functions
reservable_item_buffer ()
void reset ()
Public Member Functions inherited from internal::item_buffer< T, A >
item_buffer ()
Constructor.
~item_buffer ()
void reset ()
Protected Member Functions
bool reserve_front (T &v)
void consume_front ()
void release_front ()
Protected Member Functions inherited from internal::item_buffer< T, A >
bool buffer_empty () const
buffer_item_type & item (size_type i)
const buffer_item_type & item (size_type i) const
bool my_item_valid (size_type i) const
bool my_item_reserved (size_type i) const
const item_type & get_my_item (size_t i) const
void set_my_item (size_t i, const item_type &o)
void fetch_item (size_t i, item_type &o)
void move_item (size_t to, size_t from)
bool place_item (size_t here, const item_type &me)
void swap_items (size_t i, size_t j)
void destroy_item (size_type i)
const item_type & front () const
const item_type & back () const
void reserve_item (size_type i)
void release_item (size_type i)
void destroy_front ()
void destroy_back ()
size_type size (size_t new_tail=0)
size_type capacity ()
bool buffer_full ()
void grow_my_array (size_t minimum_size)
Grows the internal array.
bool push_back (item_type &v)
bool pop_back (item_type &v)
bool pop_front (item_type &v)
void clean_up_buffer (bool reset_pointers)
Protected Attributes
bool my_reserved
Protected Attributes inherited from internal::item_buffer< T, A >
buffer_item_type * my_array
size_type my_array_size
size_type my_head
size_type my_tail
Additional Inherited Members
Public Types inherited from internal::item_buffer< T, A >
enum buffer_item_state { no_item =0, has_item =1, reserved_item =2 }
typedef T item_type
Protected Types inherited from internal::item_buffer< T, A >
typedef size_t size_type
typedef aligned_pair< item_type, buffer_item_state >::type buffer_item_type
typedef A::template rebind< buffer_item_type >::other allocator_type
Static Protected Attributes inherited from internal::item_buffer< T, A >
static const size_type initial_buffer_size = 4
Detailed Description
template<typename T, typename A = cache_aligned_allocator<T>>
class internal::reservable_item_buffer< T, A >
item_buffer with reservable front-end. NOTE: if reserving, do not
Definition at line 252 of file _flow_graph_item_buffer_impl.h.
Constructor & Destructor Documentation
template<typename T , typename A = cache_aligned_allocator<T>> internal::reservable_item_buffer< T, A >::reservable_item_buffer () inline
Definition at line 258 of file _flow_graph_item_buffer_impl.h.
 : item_buffer<T, A>(), my_reserved(false) {}
Member Function Documentation
template<typename T , typename A = cache_aligned_allocator<T>> void internal::reservable_item_buffer< T, A >::consume_front () inline protected
Definition at line 271 of file _flow_graph_item_buffer_impl.h.
References __TBB_ASSERT, and internal::item_buffer< T, A >::destroy_front().
{
             __TBB_ASSERT(my_reserved, "Attempt to consume a non-reserved item");
             this->destroy_front();
             my_reserved = false;
         }
template<typename T , typename A = cache_aligned_allocator<T>> void internal::reservable_item_buffer< T, A >::release_front () inline protected
Definition at line 277 of file _flow_graph_item_buffer_impl.h.
References __TBB_ASSERT, internal::item_buffer< T, A >::my_head, and internal::item_buffer< T, A >::release_item().
{
             __TBB_ASSERT(my_reserved, "Attempt to release a non-reserved item");
             this->release_item(this->my_head);
             my_reserved = false;
         }
template<typename T , typename A = cache_aligned_allocator<T>> bool internal::reservable_item_buffer< T, A >::reserve_front (T & v) inline protected
Definition at line 262 of file _flow_graph_item_buffer_impl.h.
References internal::item_buffer< T, A >::front(), internal::item_buffer< T, A >::my_head, internal::item_buffer< T, A >::my_item_valid(), and internal::item_buffer< T, A >::reserve_item().
{
             if(my_reserved || !my_item_valid(this->my_head)) return false;
             my_reserved = true;
             // reserving the head
             v = this->front();
             this->reserve_item(this->my_head);
             return true;
         }
template<typename T , typename A = cache_aligned_allocator<T>> void internal::reservable_item_buffer< T, A >::reset () inline
Definition at line 259 of file _flow_graph_item_buffer_impl.h.
References internal::item_buffer< T, A >::reset().
 {my_reserved = false; item_buffer<T,A>::reset(); }
Member Data Documentation
template<typename T , typename A = cache_aligned_allocator<T>> bool internal::reservable_item_buffer< T, A >::my_reserved protected
Definition at line 283 of file _flow_graph_item_buffer_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_item_buffer_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.