Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::concurrent_vector_base_v3::helper::segment_not_used_predicate Struct Reference
tbb::internal::concurrent_vector_base_v3::helper::segment_not_used_predicate Struct Reference
Public Member Functions
segment_not_used_predicate (segment_t &segment)
bool operator() () const
Public Attributes
segment_t & s
Detailed Description
Definition at line 103 of file concurrent_vector.cpp.
Constructor & Destructor Documentation
tbb::internal::concurrent_vector_base_v3::helper::segment_not_used_predicate::segment_not_used_predicate (segment_t & segment) inline
Definition at line 105 of file concurrent_vector.cpp.
Referenced by tbb::internal::concurrent_vector_base_v3::helper::acquire_segment(), tbb::internal::concurrent_vector_base_v3::helper::enable_segment(), and tbb::internal::concurrent_vector_base_v3::helper::get_segment_value().
 : s(segment) {}
Member Function Documentation
bool tbb::internal::concurrent_vector_base_v3::helper::segment_not_used_predicate::operator() () const inline
Definition at line 106 of file concurrent_vector.cpp.
References tbb::internal::concurrent_vector_base_v3::segment_t::load(), and tbb::relaxed.
 { return s.load<relaxed>() == segment_not_used ();}
Member Data Documentation
segment_t& tbb::internal::concurrent_vector_base_v3::helper::segment_not_used_predicate::s
Definition at line 104 of file concurrent_vector.cpp.
Referenced by tbb::internal::concurrent_vector_base_v3::helper::acquire_segment(), tbb::internal::concurrent_vector_base_v3::helper::enable_segment(), tbb::internal::concurrent_vector_base_v3::helper::get_segment_value(), tbb::internal::concurrent_vector_base_v3::internal_compact(), tbb::internal::concurrent_vector_base_v3::internal_grow_to_at_least_with_result(), tbb::internal::concurrent_vector_base_v3::internal_push_back(), and tbb::internal::concurrent_vector_base_v3::~concurrent_vector_base_v3().
The documentation for this struct was generated from the following file:
concurrent_vector.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.