Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::semaphore Class Reference
tbb::internal::semaphore Class Reference
Edsger Dijkstra's counting semaphore.
#include <semaphore.h>
Public Member Functions
semaphore (int start_cnt_=0)
ctor
~semaphore ()
dtor
void P ()
wait/acquire
void V ()
post/release
Private Member Functions
void init_semaphore (int start_cnt_)
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
sem_t sem
Detailed Description
Edsger Dijkstra's counting semaphore.
Definition at line 98 of file semaphore.h.
Constructor & Destructor Documentation
tbb::internal::semaphore::semaphore (int start_cnt_ = 0) inline
ctor
Definition at line 101 of file semaphore.h.
References init_semaphore().
 { init_semaphore( start_cnt_ ); }
tbb::internal::semaphore::~semaphore () inline
dtor
Definition at line 104 of file semaphore.h.
References __TBB_ASSERT_EX.
                  {
         int ret = sem_destroy( &sem );
         __TBB_ASSERT_EX( !ret, NULL );
     }
Member Function Documentation
void tbb::internal::semaphore::init_semaphore (int start_cnt_) inline private
Definition at line 117 of file semaphore.h.
References __TBB_ASSERT, __TBB_ASSERT_EX, h, lock, P(), s, and V().
Referenced by semaphore().
{
         int ret = sem_init( &sem, /*shared among threads*/ 0, start_cnt_ );
         __TBB_ASSERT_EX( !ret, NULL );
     }
void tbb::internal::semaphore::P () inline
wait/acquire
Definition at line 109 of file semaphore.h.
References __TBB_ASSERT.
Referenced by init_semaphore(), tbb::internal::input_buffer::sema_P(), and tbb::internal::concurrent_monitor::thread_context::~thread_context().
              {
         while( sem_wait( &sem )!=0 )
             __TBB_ASSERT( errno==EINTR, NULL );
     }
void tbb::internal::semaphore::V () inline
post/release
Definition at line 114 of file semaphore.h.
Referenced by init_semaphore(), and tbb::internal::input_buffer::sema_V().
 { sem_post( &sem ); }
Member Data Documentation
sem_t tbb::internal::semaphore::sem private
Definition at line 116 of file semaphore.h.
The documentation for this class was generated from the following file:
semaphore.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.