Intel(R) Threading Building Blocks Doxygen Documentation: tbb::queuing_mutex::scoped_lock Class Reference
tbb::queuing_mutex::scoped_lock Class Reference
The scoped locking pattern.
#include <queuing_mutex.h>
Public Member Functions
scoped_lock ()
Construct lock that has not acquired a mutex.
scoped_lock (queuing_mutex &m)
Acquire lock on given mutex.
~scoped_lock ()
Release lock (if lock is held).
void __TBB_EXPORTED_METHOD acquire (queuing_mutex &m)
Acquire lock on given mutex.
bool __TBB_EXPORTED_METHOD try_acquire (queuing_mutex &m)
Acquire lock on given mutex if free (i.e. non-blocking)
void __TBB_EXPORTED_METHOD release ()
Release lock.
Private Member Functions
void initialize ()
Initialize fields to mean "no lock held".
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
queuing_mutex * mutex
The pointer to the mutex owned, or NULL if not holding a mutex.
scoped_lock * next
The pointer to the next competitor for a mutex.
uintptr_t going
The local spin-wait variable.
Detailed Description
The scoped locking pattern.
It helps to avoid the common problem of forgetting to release lock. It also nicely provides the "node" for queuing locks.
Definition at line 45 of file queuing_mutex.h.
Constructor & Destructor Documentation
tbb::queuing_mutex::scoped_lock::scoped_lock () inline
Construct lock that has not acquired a mutex.
Equivalent to zero-initialization of *this.
Definition at line 58 of file queuing_mutex.h.
References initialize().
 {initialize();}
tbb::queuing_mutex::scoped_lock::scoped_lock (queuing_mutex & m) inline
Acquire lock on given mutex.
Definition at line 61 of file queuing_mutex.h.
References acquire(), and initialize().
{
             initialize();
             acquire(m);
         }
tbb::queuing_mutex::scoped_lock::~scoped_lock () inline
Release lock (if lock is held).
Definition at line 67 of file queuing_mutex.h.
References __TBB_EXPORTED_METHOD, acquire(), release(), and try_acquire().
{
             if( mutex ) release();
         }
Member Function Documentation
void tbb::queuing_mutex::scoped_lock::acquire (queuing_mutex & m)
Acquire lock on given mutex.
A method to acquire queuing_mutex lock.
Definition at line 32 of file queuing_mutex.cpp.
References __TBB_ASSERT, __TBB_control_consistency_helper, tbb::internal::__TBB_load_with_acquire(), ITT_NOTIFY, next, tbb::queuing_mutex::q_tail, tbb::release, and tbb::internal::spin_wait_while_eq().
Referenced by scoped_lock(), and ~scoped_lock().
 {
     __TBB_ASSERT( !this->mutex, "scoped_lock is already holding a mutex");
     // Must set all fields before the fetch_and_store, because once the
     // fetch_and_store executes, *this becomes accessible to other threads.
     mutex = &m;
     next  = NULL;
     going = 0;
     // The fetch_and_store must have release semantics, because we are
     // "sending" the fields initialized above to other processors.
     scoped_lock* pred = m.q_tail.fetch_and_store<tbb::release>(this);
     if( pred ) {
         ITT_NOTIFY(sync_prepare, mutex);
 #if TBB_USE_ASSERT
         __TBB_control_consistency_helper(); // on "m.q_tail"
         __TBB_ASSERT( !pred->next, "the predecessor has another successor!");
 #endif
         pred->next = this;
         spin_wait_while_eq( going, 0ul );
     }
     ITT_NOTIFY(sync_acquired, mutex);
     // Force acquire so that user's critical section receives correct values
     // from processor that was previously in the user's critical section.
     __TBB_load_with_acquire(going);
 }
void tbb::queuing_mutex::scoped_lock::initialize () inline private
Initialize fields to mean "no lock held".
Definition at line 47 of file queuing_mutex.h.
References going, next, and tbb::internal::poison_pointer().
Referenced by scoped_lock().
{
             mutex = NULL;
             going = 0;
 #if TBB_USE_ASSERT
             internal::poison_pointer(next);
 #endif /* TBB_USE_ASSERT */
         }
void tbb::queuing_mutex::scoped_lock::release ()
Release lock.
A method to release queuing_mutex lock.
Definition at line 85 of file queuing_mutex.cpp.
References __TBB_ASSERT, tbb::internal::__TBB_store_with_release(), ITT_NOTIFY, tbb::release, tbb::internal::spin_wait_while_eq(), and sync_releasing.
Referenced by ~scoped_lock().
 {
     __TBB_ASSERT(this->mutex!=NULL, "no lock acquired");
     ITT_NOTIFY(sync_releasing, mutex);
     if( !next ) {
         if( this == mutex->q_tail.compare_and_swap<tbb::release>(NULL, this) ) {
             // this was the only item in the queue, and the queue is now empty.
             goto done;
         }
         // Someone in the queue
         spin_wait_while_eq( next, (scoped_lock*)0 );
     }
     __TBB_ASSERT(next,NULL);
     __TBB_store_with_release(next->going, 1);
 done:
     initialize();
 }
bool tbb::queuing_mutex::scoped_lock::try_acquire (queuing_mutex & m)
Acquire lock on given mutex if free (i.e. non-blocking)
A method to acquire queuing_mutex if it is free.
Definition at line 62 of file queuing_mutex.cpp.
References __TBB_ASSERT, tbb::internal::__TBB_load_with_acquire(), ITT_NOTIFY, tbb::queuing_mutex::q_tail, and tbb::release.
Referenced by ~scoped_lock().
 {
     __TBB_ASSERT( !this->mutex, "scoped_lock is already holding a mutex");
     // Must set all fields before the fetch_and_store, because once the
     // fetch_and_store executes, *this becomes accessible to other threads.
     next  = NULL;
     going = 0;
     // The CAS must have release semantics, because we are
     // "sending" the fields initialized above to other processors.
     if( m.q_tail.compare_and_swap<tbb::release>(this, NULL) )
         return false;
     // Force acquire so that user's critical section receives correct values
     // from processor that was previously in the user's critical section.
     __TBB_load_with_acquire(going);
     mutex = &m;
     ITT_NOTIFY(sync_acquired, mutex);
     return true;
 }
Member Data Documentation
uintptr_t tbb::queuing_mutex::scoped_lock::going private
The local spin-wait variable.
Inverted (0 - blocked, 1 - acquired the mutex) for the sake of zero-initialization. Defining it as an entire word instead of a byte seems to help performance slightly.
Definition at line 91 of file queuing_mutex.h.
Referenced by initialize().
queuing_mutex* tbb::queuing_mutex::scoped_lock::mutex private
The pointer to the mutex owned, or NULL if not holding a mutex.
Definition at line 82 of file queuing_mutex.h.
scoped_lock* tbb::queuing_mutex::scoped_lock::next private
The pointer to the next competitor for a mutex.
Definition at line 85 of file queuing_mutex.h.
Referenced by acquire(), and initialize().
The documentation for this class was generated from the following files:
queuing_mutex.h
queuing_mutex.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.