Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::queue_and_mutex< T, mutex_t > Struct Template Reference
tbb::internal::queue_and_mutex< T, mutex_t > Struct Template Reference
Essentially, this is just a pair of a queue and a mutex to protect the queue.
#include <task_stream.h>
Public Types
typedef std::deque< T, tbb_allocator< T > > queue_base_t
typedef std::deque< T, tbb_allocator< T > > queue_base_t
Public Member Functions
queue_and_mutex ()
~queue_and_mutex ()
queue_and_mutex ()
~queue_and_mutex ()
Public Attributes
queue_base_t my_queue
mutex_t my_mutex
Detailed Description
template<typename T, typename mutex_t>
struct tbb::internal::queue_and_mutex< T, mutex_t >
Essentially, this is just a pair of a queue and a mutex to protect the queue.
The reason std::pair is not used is that the code would look less clean if field names were replaced with 'first' and 'second'.
Definition at line 40 of file task_stream.h.
Member Typedef Documentation
template<typename T , typename mutex_t > typedef std::deque< T, tbb_allocator<T> > tbb::internal::queue_and_mutex< T, mutex_t >::queue_base_t
Definition at line 41 of file task_stream.h.
template<typename T , typename mutex_t > typedef std::deque< T, tbb_allocator<T> > tbb::internal::queue_and_mutex< T, mutex_t >::queue_base_t
Definition at line 57 of file task_stream_extended.h.
Constructor & Destructor Documentation
template<typename T , typename mutex_t > tbb::internal::queue_and_mutex< T, mutex_t >::queue_and_mutex () inline
Definition at line 46 of file task_stream.h.
 : my_queue(), my_mutex() {}
template<typename T , typename mutex_t > tbb::internal::queue_and_mutex< T, mutex_t >::~queue_and_mutex () inline
Definition at line 47 of file task_stream.h.
 {}
template<typename T , typename mutex_t > tbb::internal::queue_and_mutex< T, mutex_t >::queue_and_mutex () inline
Definition at line 62 of file task_stream_extended.h.
 : my_queue(), my_mutex() {}
template<typename T , typename mutex_t > tbb::internal::queue_and_mutex< T, mutex_t >::~queue_and_mutex () inline
Definition at line 63 of file task_stream_extended.h.
References __TBB_ASSERT, __TBB_AtomicAND(), __TBB_AtomicOR(), tbb::internal::clear_one_bit(), tbb::internal::is_bit_set(), tbb::internal::one, and tbb::internal::set_one_bit().
 {}
Member Data Documentation
template<typename T , typename mutex_t > mutex_t tbb::internal::queue_and_mutex< T, mutex_t >::my_mutex
Definition at line 44 of file task_stream.h.
Referenced by tbb::internal::task_stream< num_priority_levels >::drain(), tbb::internal::task_stream< num_priority_levels >::pop(), tbb::internal::task_stream< num_priority_levels >::pop_specific(), and tbb::internal::task_stream< num_priority_levels >::try_pop().
template<typename T , typename mutex_t > queue_base_t tbb::internal::queue_and_mutex< T, mutex_t >::my_queue
Definition at line 43 of file task_stream.h.
Referenced by tbb::internal::task_stream< num_priority_levels >::drain(), tbb::internal::task_stream< num_priority_levels >::pop(), tbb::internal::task_stream< num_priority_levels >::pop_specific(), and tbb::internal::task_stream< num_priority_levels >::try_pop().
The documentation for this struct was generated from the following files:
task_stream.h
task_stream_extended.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.