Intel(R) Threading Building Blocks Doxygen Documentation: tbb::spin_mutex::scoped_lock Class Reference
tbb::spin_mutex::scoped_lock Class Reference
Represents acquisition of a mutex.
#include <spin_mutex.h>
Public Member Functions
scoped_lock ()
Construct without acquiring a mutex.
scoped_lock (spin_mutex &m)
Construct and acquire lock on a mutex.
void acquire (spin_mutex &m)
Acquire lock.
bool try_acquire (spin_mutex &m)
Try acquiring lock (non-blocking)
void release ()
Release lock.
~scoped_lock ()
Destroy lock. If holding a lock, releases the lock first.
Private Member Functions
void __TBB_EXPORTED_METHOD internal_acquire (spin_mutex &m)
Like acquire, but with ITT instrumentation.
bool __TBB_EXPORTED_METHOD internal_try_acquire (spin_mutex &m)
Like try_acquire, but with ITT instrumentation.
void __TBB_EXPORTED_METHOD internal_release ()
Like release, but with ITT instrumentation.
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
spin_mutex * my_mutex
Points to currently held mutex, or NULL if no lock is held.
__TBB_Flag my_unlock_value
Value to store into spin_mutex::flag to unlock the mutex.
Friends
class spin_mutex
Detailed Description
Represents acquisition of a mutex.
Definition at line 54 of file spin_mutex.h.
Constructor & Destructor Documentation
tbb::spin_mutex::scoped_lock::scoped_lock () inline
Construct without acquiring a mutex.
Definition at line 78 of file spin_mutex.h.
Referenced by tbb::spin_mutex::lock().
 : my_mutex(NULL), my_unlock_value(0) {}
tbb::spin_mutex::scoped_lock::scoped_lock (spin_mutex & m) inline
Construct and acquire lock on a mutex.
Definition at line 81 of file spin_mutex.h.
References __TBB_LockByte(), tbb::spin_mutex::flag, internal_acquire(), and tbb::internal::suppress_unused_warning().
                                      : my_unlock_value(0) {
             internal::suppress_unused_warning(my_unlock_value);
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
             my_mutex=NULL;
             internal_acquire(m);
 #else
             my_mutex=&m;
             __TBB_LockByte(m.flag);
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT*/
         }
tbb::spin_mutex::scoped_lock::~scoped_lock () inline
Destroy lock. If holding a lock, releases the lock first.
Definition at line 126 of file spin_mutex.h.
References __TBB_EXPORTED_METHOD, __TBB_UnlockByte, tbb::spin_mutex::flag, tbb::spin_mutex::internal_construct(), and internal_release().
{
             if( my_mutex ) {
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
                 internal_release();
 #else
                 __TBB_UnlockByte(my_mutex->flag);
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT */
             }
         }
Member Function Documentation
void tbb::spin_mutex::scoped_lock::acquire (spin_mutex & m) inline
Acquire lock.
Definition at line 93 of file spin_mutex.h.
References __TBB_LockByte(), tbb::spin_mutex::flag, and internal_acquire().
Referenced by tbb::internal::generic_scheduler::init_stack_info().
{
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
             internal_acquire(m);
 #else
             my_mutex = &m;
             __TBB_LockByte(m.flag);
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT*/
         }
void tbb::spin_mutex::scoped_lock::internal_acquire (spin_mutex & m) private
Like acquire, but with ITT instrumentation.
Definition at line 28 of file spin_mutex.cpp.
References __TBB_ASSERT, __TBB_LockByte(), tbb::spin_mutex::flag, ITT_NOTIFY, and my_mutex.
Referenced by acquire(), and scoped_lock().
{
     __TBB_ASSERT( !my_mutex, "already holding a lock on a spin_mutex" );
     ITT_NOTIFY(sync_prepare, &m);
     __TBB_LockByte(m.flag);
     my_mutex = &m;
     ITT_NOTIFY(sync_acquired, &m);
 }
void tbb::spin_mutex::scoped_lock::internal_release () private
Like release, but with ITT instrumentation.
Definition at line 36 of file spin_mutex.cpp.
References __TBB_ASSERT, __TBB_UnlockByte, tbb::spin_mutex::flag, ITT_NOTIFY, my_mutex, and sync_releasing.
Referenced by release(), tbb::spin_mutex::unlock(), and ~scoped_lock().
{
     __TBB_ASSERT( my_mutex, "release on spin_mutex::scoped_lock that is not holding a lock" );
     ITT_NOTIFY(sync_releasing, my_mutex);
     __TBB_UnlockByte(my_mutex->flag);
     my_mutex = NULL;
 }
bool tbb::spin_mutex::scoped_lock::internal_try_acquire (spin_mutex & m) private
Like try_acquire, but with ITT instrumentation.
Definition at line 44 of file spin_mutex.cpp.
References __TBB_ASSERT, __TBB_TryLockByte(), tbb::spin_mutex::flag, ITT_NOTIFY, and my_mutex.
Referenced by try_acquire().
{
     __TBB_ASSERT( !my_mutex, "already holding a lock on a spin_mutex" );
     bool result = bool( __TBB_TryLockByte(m.flag) );
     if( result ) {
         my_mutex = &m;
         ITT_NOTIFY(sync_acquired, &m);
     }
     return result;
 }
void tbb::spin_mutex::scoped_lock::release () inline
Release lock.
Definition at line 116 of file spin_mutex.h.
References __TBB_UnlockByte, tbb::spin_mutex::flag, and internal_release().
{
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
             internal_release();
 #else
             __TBB_UnlockByte(my_mutex->flag);
             my_mutex = NULL;
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT */
         }
bool tbb::spin_mutex::scoped_lock::try_acquire (spin_mutex & m) inline
Try acquiring lock (non-blocking)
Return true if lock acquired; false otherwise.
Definition at line 104 of file spin_mutex.h.
References __TBB_TryLockByte(), tbb::spin_mutex::flag, and internal_try_acquire().
Referenced by tbb::internal::task_stream< num_priority_levels >::pop(), tbb::internal::task_stream< num_priority_levels >::pop_specific(), tbb::internal::task_stream< num_priority_levels >::push(), tbb::internal::task_stream< num_priority_levels >::try_pop(), and tbb::internal::task_stream< num_priority_levels >::try_push().
{
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
             return internal_try_acquire(m);
 #else
             bool result = __TBB_TryLockByte(m.flag);
             if( result )
                 my_mutex = &m;
             return result;
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT*/
         }
Friends And Related Function Documentation
friend class spin_mutex friend
Definition at line 74 of file spin_mutex.h.
Member Data Documentation
spin_mutex* tbb::spin_mutex::scoped_lock::my_mutex private
Points to currently held mutex, or NULL if no lock is held.
Definition at line 57 of file spin_mutex.h.
Referenced by internal_acquire(), internal_release(), internal_try_acquire(), and tbb::spin_mutex::unlock().
__TBB_Flag tbb::spin_mutex::scoped_lock::my_unlock_value private
Value to store into spin_mutex::flag to unlock the mutex.
This variable is no longer used. Instead, 0 and 1 are used to represent that the lock is free and acquired, respectively. We keep the member variable here to ensure backward compatibility
Definition at line 63 of file spin_mutex.h.
The documentation for this class was generated from the following files:
spin_mutex.h
spin_mutex.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.