Intel(R) Threading Building Blocks Doxygen Documentation: tbb::proportional_split Class Reference
tbb::proportional_split Class Reference
Type enables transmission of splitting proportion from partitioners to range objects.
#include <tbb_stddef.h>
Public Member Functions
proportional_split (size_t _left=1, size_t _right=1)
size_t left () const
size_t right () const
operator split () const
Private Attributes
size_t my_left
size_t my_right
Detailed Description
Type enables transmission of splitting proportion from partitioners to range objects.
In order to make use of such facility Range objects must implement splitting constructor with this type passed and initialize static constant boolean field 'is_splittable_in_proportion' with the value of 'true'
Definition at line 409 of file tbb_stddef.h.
Constructor & Destructor Documentation
tbb::proportional_split::proportional_split (size_t _left = 1, size_t _right = 1) inline
Definition at line 411 of file tbb_stddef.h.
 : my_left(_left), my_right(_right) { }
Member Function Documentation
size_t tbb::proportional_split::left () const inline
Definition at line 413 of file tbb_stddef.h.
Referenced by tbb::blocked_range< I >::do_split(), and tbb::interface9::internal::proportional_mode< static_partition_type >::do_split().
 { return my_left; }
tbb::proportional_split::operator split () const inline
Definition at line 417 of file tbb_stddef.h.
 { return split(); }
size_t tbb::proportional_split::right () const inline
Definition at line 414 of file tbb_stddef.h.
Referenced by tbb::blocked_range< I >::do_split(), and tbb::interface9::internal::proportional_mode< static_partition_type >::do_split().
 { return my_right; }
Member Data Documentation
size_t tbb::proportional_split::my_left private
Definition at line 426 of file tbb_stddef.h.
size_t tbb::proportional_split::my_right private
Definition at line 426 of file tbb_stddef.h.
The documentation for this class was generated from the following file:
tbb_stddef.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.