Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::reader_writer_lock::scoped_lock Class Reference
tbb::interface5::reader_writer_lock::scoped_lock Class Reference
The scoped lock pattern for write locks.
#include <reader_writer_lock.h>
Public Member Functions
scoped_lock (reader_writer_lock &lock)
Construct with blocking attempt to acquire write lock on the passed-in lock.
~scoped_lock ()
Destructor, releases the write lock.
void * operator new (size_t s)
void operator delete (void *p)
Private Member Functions
scoped_lock ()
Construct scoped_lock that is not holding lock.
void __TBB_EXPORTED_METHOD internal_construct (reader_writer_lock &)
void __TBB_EXPORTED_METHOD internal_destroy ()
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
reader_writer_lock * mutex
The pointer to the mutex to lock.
scoped_lock * next
The next queued competitor for the mutex.
atomic< status_t > status
Status flag of the thread associated with this node.
Friends
class reader_writer_lock
Detailed Description
The scoped lock pattern for write locks.
Scoped locks help avoid the common problem of forgetting to release the lock. This type also serves as the node for queuing locks.
Definition at line 89 of file reader_writer_lock.h.
Constructor & Destructor Documentation
tbb::interface5::reader_writer_lock::scoped_lock::scoped_lock (reader_writer_lock & lock) inline
Construct with blocking attempt to acquire write lock on the passed-in lock.
Definition at line 94 of file reader_writer_lock.h.
References internal_construct().
{
             internal_construct(lock);
         }
tbb::interface5::reader_writer_lock::scoped_lock::~scoped_lock () inline
Destructor, releases the write lock.
Definition at line 99 of file reader_writer_lock.h.
References internal_destroy().
{
             internal_destroy();
         }
tbb::interface5::reader_writer_lock::scoped_lock::scoped_lock () inline private
Construct scoped_lock that is not holding lock.
Definition at line 310 of file reader_writer_lock.cpp.
References status, and tbb::interface5::reader_writer_lock::waiting.
                                                   : mutex(NULL), next(NULL) {
     status = waiting;
 }
Member Function Documentation
void tbb::interface5::reader_writer_lock::scoped_lock::internal_construct (reader_writer_lock & lock) private
Definition at line 297 of file reader_writer_lock.cpp.
References tbb::internal::eid_improper_lock, tbb::interface5::reader_writer_lock::lock(), tbb::internal::throw_exception(), void, and tbb::interface5::reader_writer_lock::waiting.
Referenced by scoped_lock(), and tbb::interface5::reader_writer_lock::scoped_lock_read::scoped_lock_read().
{
     mutex = &lock;
     next = NULL;
     status = waiting;
     if (mutex->is_current_writer()) { // recursive lock attempt
         // we don't support recursive writer locks; throw exception
         tbb::internal::throw_exception(tbb::internal::eid_improper_lock);
     }
     else { // this thread holds no locks
         (void) mutex->start_write(this);
     }
 }
void tbb::interface5::reader_writer_lock::scoped_lock::internal_destroy () private
Definition at line 332 of file reader_writer_lock.cpp.
References __TBB_ASSERT, tbb::interface5::reader_writer_lock::invalid, and tbb::interface5::reader_writer_lock::scoped_lock_read::status.
Referenced by ~scoped_lock(), and tbb::interface5::reader_writer_lock::scoped_lock_read::~scoped_lock_read().
{
     if (mutex) {
         __TBB_ASSERT(mutex->is_current_writer(), "~scoped_lock() destroyed by thread different than thread that holds lock.");
         mutex->end_write(this);
     }
     status = invalid;
 }
void tbb::interface5::reader_writer_lock::scoped_lock::operator delete (void * p) inline
Definition at line 106 of file reader_writer_lock.h.
References tbb::internal::deallocate_via_handler_v3(), and p.
{
             tbb::internal::deallocate_via_handler_v3(p);
         }
void* tbb::interface5::reader_writer_lock::scoped_lock::operator new (size_t s) inline
Definition at line 103 of file reader_writer_lock.h.
References tbb::internal::allocate_via_handler_v3(), and s.
{
             return tbb::internal::allocate_via_handler_v3(s);
         }
Friends And Related Function Documentation
friend class reader_writer_lock friend
Definition at line 91 of file reader_writer_lock.h.
Member Data Documentation
reader_writer_lock* tbb::interface5::reader_writer_lock::scoped_lock::mutex private
The pointer to the mutex to lock.
Definition at line 112 of file reader_writer_lock.h.
scoped_lock* tbb::interface5::reader_writer_lock::scoped_lock::next private
The next queued competitor for the mutex.
Definition at line 114 of file reader_writer_lock.h.
Referenced by tbb::interface5::reader_writer_lock::end_write(), tbb::interface5::reader_writer_lock::scoped_lock_read::internal_construct(), and tbb::interface5::reader_writer_lock::start_write().
atomic<status_t> tbb::interface5::reader_writer_lock::scoped_lock::status private
Status flag of the thread associated with this node.
Definition at line 116 of file reader_writer_lock.h.
Referenced by tbb::interface5::reader_writer_lock::scoped_lock_read::internal_construct(), scoped_lock(), tbb::interface5::reader_writer_lock::set_next_writer(), tbb::interface5::reader_writer_lock::start_write(), and tbb::interface5::reader_writer_lock::try_lock().
The documentation for this class was generated from the following files:
reader_writer_lock.h
reader_writer_lock.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.