Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5::reader_writer_lock::scoped_lock_read Class Reference
tbb::interface5::reader_writer_lock::scoped_lock_read Class Reference
The scoped lock pattern for read locks.
#include <reader_writer_lock.h>
Public Member Functions
scoped_lock_read (reader_writer_lock &lock)
Construct with blocking attempt to acquire read lock on the passed-in lock.
~scoped_lock_read ()
Destructor, releases the read lock.
void * operator new (size_t s)
void operator delete (void *p)
Private Member Functions
scoped_lock_read ()
Construct scoped_lock_read that is not holding lock.
void __TBB_EXPORTED_METHOD internal_construct (reader_writer_lock &)
void __TBB_EXPORTED_METHOD internal_destroy ()
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
reader_writer_lock * mutex
The pointer to the mutex to lock.
scoped_lock_read * next
The next queued competitor for the mutex.
atomic< status_t > status
Status flag of the thread associated with this node.
Friends
class reader_writer_lock
Detailed Description
The scoped lock pattern for read locks.
Definition at line 126 of file reader_writer_lock.h.
Constructor & Destructor Documentation
tbb::interface5::reader_writer_lock::scoped_lock_read::scoped_lock_read (reader_writer_lock & lock) inline
Construct with blocking attempt to acquire read lock on the passed-in lock.
Definition at line 131 of file reader_writer_lock.h.
References tbb::interface5::reader_writer_lock::scoped_lock::internal_construct().
{
             internal_construct(lock);
         }
tbb::interface5::reader_writer_lock::scoped_lock_read::~scoped_lock_read () inline
Destructor, releases the read lock.
Definition at line 136 of file reader_writer_lock.h.
References tbb::interface5::reader_writer_lock::scoped_lock::internal_destroy().
{
             internal_destroy();
         }
tbb::interface5::reader_writer_lock::scoped_lock_read::scoped_lock_read () inline private
Construct scoped_lock_read that is not holding lock.
Definition at line 328 of file reader_writer_lock.cpp.
References status, and tbb::interface5::reader_writer_lock::waiting.
                                                             : mutex(NULL), next(NULL) {
     status = waiting;
 }
Member Function Documentation
void tbb::interface5::reader_writer_lock::scoped_lock_read::internal_construct (reader_writer_lock & lock) private
Definition at line 315 of file reader_writer_lock.cpp.
References tbb::internal::eid_improper_lock, tbb::interface5::reader_writer_lock::lock(), tbb::interface5::reader_writer_lock::scoped_lock::next, tbb::interface5::reader_writer_lock::scoped_lock::status, tbb::internal::throw_exception(), and tbb::interface5::reader_writer_lock::waiting.
{
     mutex = &lock;
     next = NULL;
     status = waiting;
     if (mutex->is_current_writer()) { // recursive lock attempt
         // we don't support writer->reader downgrade; throw exception
         tbb::internal::throw_exception(tbb::internal::eid_improper_lock);
     }
     else { // this thread holds no locks
         mutex->start_read(this);
     }
 }
void tbb::interface5::reader_writer_lock::scoped_lock_read::internal_destroy () private
Definition at line 340 of file reader_writer_lock.cpp.
References tbb::interface5::reader_writer_lock::invalid, and status.
{
     if (mutex)
         mutex->end_read();
     status = invalid;
 }
void tbb::interface5::reader_writer_lock::scoped_lock_read::operator delete (void * p) inline
Definition at line 143 of file reader_writer_lock.h.
References tbb::internal::deallocate_via_handler_v3(), and p.
{
             tbb::internal::deallocate_via_handler_v3(p);
         }
void* tbb::interface5::reader_writer_lock::scoped_lock_read::operator new (size_t s) inline
Definition at line 140 of file reader_writer_lock.h.
References tbb::internal::allocate_via_handler_v3(), and s.
{
             return tbb::internal::allocate_via_handler_v3(s);
         }
Friends And Related Function Documentation
friend class reader_writer_lock friend
Definition at line 128 of file reader_writer_lock.h.
Member Data Documentation
reader_writer_lock* tbb::interface5::reader_writer_lock::scoped_lock_read::mutex private
The pointer to the mutex to lock.
Definition at line 149 of file reader_writer_lock.h.
scoped_lock_read* tbb::interface5::reader_writer_lock::scoped_lock_read::next private
The next queued competitor for the mutex.
Definition at line 151 of file reader_writer_lock.h.
Referenced by tbb::interface5::reader_writer_lock::start_read().
atomic<status_t> tbb::interface5::reader_writer_lock::scoped_lock_read::status private
Status flag of the thread associated with this node.
Definition at line 153 of file reader_writer_lock.h.
Referenced by tbb::interface5::reader_writer_lock::scoped_lock::internal_destroy(), internal_destroy(), scoped_lock_read(), tbb::interface5::reader_writer_lock::start_read(), and tbb::interface5::reader_writer_lock::unblock_readers().
The documentation for this class was generated from the following files:
reader_writer_lock.h
reader_writer_lock.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.