Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::range_vector< T, MaxCapacity > Class Template Reference
tbb::interface9::internal::range_vector< T, MaxCapacity > Class Template Reference
Range pool stores ranges of type T in a circular buffer with MaxCapacity.
#include <partitioner.h>
Public Member Functions
range_vector (const T &elem)
initialize via first range in pool
~range_vector ()
bool empty () const
depth_t size () const
void split_to_fill (depth_t max_depth)
void pop_back ()
void pop_front ()
T & back ()
T & front ()
depth_t front_depth ()
similarly to front(), returns depth of the first range in the pool
depth_t back_depth ()
bool is_divisible (depth_t max_depth)
Private Attributes
depth_t my_head
depth_t my_tail
depth_t my_size
depth_t my_depth [MaxCapacity]
tbb::aligned_space< T, MaxCapacity > my_pool
Detailed Description
template<typename T, depth_t MaxCapacity>
class tbb::interface9::internal::range_vector< T, MaxCapacity >
Range pool stores ranges of type T in a circular buffer with MaxCapacity.
Definition at line 155 of file partitioner.h.
Constructor & Destructor Documentation
template<typename T , depth_t MaxCapacity> tbb::interface9::internal::range_vector< T, MaxCapacity >::range_vector (const T & elem) inline
initialize via first range in pool
Definition at line 164 of file partitioner.h.
References tbb::aligned_space< T, N >::begin().
                                 : my_head(0), my_tail(0), my_size(1) {
         my_depth[0] = 0;
         new( static_cast<void *>(my_pool.begin()) ) T(elem);//TODO: std::move?
     }
template<typename T , depth_t MaxCapacity> tbb::interface9::internal::range_vector< T, MaxCapacity >::~range_vector () inline
Definition at line 168 of file partitioner.h.
                     {
         while( !empty() ) pop_back();
     }
Member Function Documentation
template<typename T , depth_t MaxCapacity> T& tbb::interface9::internal::range_vector< T, MaxCapacity >::back () inline
Definition at line 198 of file partitioner.h.
References __TBB_ASSERT, and tbb::aligned_space< T, N >::begin().
               {
         __TBB_ASSERT(my_size > 0, "range_vector::back() with empty size");
         return my_pool.begin()[my_head];
     }
template<typename T , depth_t MaxCapacity> depth_t tbb::interface9::internal::range_vector< T, MaxCapacity >::back_depth () inline
Definition at line 211 of file partitioner.h.
References __TBB_ASSERT.
{
         __TBB_ASSERT(my_size > 0, "range_vector::back_depth() with empty size");
         return my_depth[my_head];
     }
template<typename T , depth_t MaxCapacity> bool tbb::interface9::internal::range_vector< T, MaxCapacity >::empty () const inline
Definition at line 171 of file partitioner.h.
 { return my_size == 0; }
template<typename T , depth_t MaxCapacity> T& tbb::interface9::internal::range_vector< T, MaxCapacity >::front () inline
Definition at line 202 of file partitioner.h.
References __TBB_ASSERT, and tbb::aligned_space< T, N >::begin().
                {
         __TBB_ASSERT(my_size > 0, "range_vector::front() with empty size");
         return my_pool.begin()[my_tail];
     }
template<typename T , depth_t MaxCapacity> depth_t tbb::interface9::internal::range_vector< T, MaxCapacity >::front_depth () inline
similarly to front(), returns depth of the first range in the pool
Definition at line 207 of file partitioner.h.
References __TBB_ASSERT.
{
         __TBB_ASSERT(my_size > 0, "range_vector::front_depth() with empty size");
         return my_depth[my_tail];
     }
template<typename T , depth_t MaxCapacity> bool tbb::interface9::internal::range_vector< T, MaxCapacity >::is_divisible (depth_t max_depth) inline
Definition at line 215 of file partitioner.h.
{
         return back_depth() < max_depth && back().is_divisible();
     }
template<typename T , depth_t MaxCapacity> void tbb::interface9::internal::range_vector< T, MaxCapacity >::pop_back () inline
Definition at line 186 of file partitioner.h.
References __TBB_ASSERT, and tbb::aligned_space< T, N >::begin().
                     {
         __TBB_ASSERT(my_size > 0, "range_vector::pop_back() with empty size");
         my_pool.begin()[my_head].~T();
         my_size--;
         my_head = (my_head + MaxCapacity - 1) % MaxCapacity;
     }
template<typename T , depth_t MaxCapacity> void tbb::interface9::internal::range_vector< T, MaxCapacity >::pop_front () inline
Definition at line 192 of file partitioner.h.
References __TBB_ASSERT, and tbb::aligned_space< T, N >::begin().
                      {
         __TBB_ASSERT(my_size > 0, "range_vector::pop_front() with empty size");
         my_pool.begin()[my_tail].~T();
         my_size--;
         my_tail = (my_tail + 1) % MaxCapacity;
     }
template<typename T , depth_t MaxCapacity> depth_t tbb::interface9::internal::range_vector< T, MaxCapacity >::size () const inline
Definition at line 172 of file partitioner.h.
 { return my_size; }
template<typename T , depth_t MaxCapacity> void tbb::interface9::internal::range_vector< T, MaxCapacity >::split_to_fill (depth_t max_depth) inline
Populates range pool via ranges up to max depth or while divisible max_depth starts from 0, e.g. value 2 makes 3 ranges in the pool up to two 1/4 pieces
Definition at line 175 of file partitioner.h.
References tbb::aligned_space< T, N >::begin().
{
         while( my_size < MaxCapacity && is_divisible(max_depth) ) {
             depth_t prev = my_head;
             my_head = (my_head + 1) % MaxCapacity;
             new(my_pool.begin()+my_head) T(my_pool.begin()[prev]); // copy TODO: std::move?
             my_pool.begin()[prev].~T(); // instead of assignment
             new(my_pool.begin()+prev) T(my_pool.begin()[my_head], split()); // do 'inverse' split
             my_depth[my_head] = ++my_depth[prev];
             my_size++;
         }
     }
Member Data Documentation
template<typename T , depth_t MaxCapacity> depth_t tbb::interface9::internal::range_vector< T, MaxCapacity >::my_depth[MaxCapacity] private
Definition at line 159 of file partitioner.h.
template<typename T , depth_t MaxCapacity> depth_t tbb::interface9::internal::range_vector< T, MaxCapacity >::my_head private
Definition at line 156 of file partitioner.h.
template<typename T , depth_t MaxCapacity> tbb::aligned_space<T, MaxCapacity> tbb::interface9::internal::range_vector< T, MaxCapacity >::my_pool private
Definition at line 160 of file partitioner.h.
template<typename T , depth_t MaxCapacity> depth_t tbb::interface9::internal::range_vector< T, MaxCapacity >::my_size private
Definition at line 158 of file partitioner.h.
template<typename T , depth_t MaxCapacity> depth_t tbb::interface9::internal::range_vector< T, MaxCapacity >::my_tail private
Definition at line 157 of file partitioner.h.
The documentation for this class was generated from the following file:
partitioner.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.