Intel(R) Threading Building Blocks Doxygen Documentation: tbb::recursive_mutex Class Reference
tbb::recursive_mutex Class Reference
Synchronization
Mutex that allows recursive mutex acquisition.
#include <recursive_mutex.h>
Classes
class scoped_lock
The scoped locking pattern.
Public Types
typedef pthread_mutex_t * native_handle_type
Return native_handle.
Public Member Functions
recursive_mutex ()
Construct unacquired recursive_mutex.
~recursive_mutex ()
void lock ()
Acquire lock.
bool try_lock ()
Try acquiring lock (non-blocking)
void unlock ()
Release lock.
native_handle_type native_handle ()
Static Public Attributes
static const bool is_rw_mutex = false
static const bool is_recursive_mutex = true
static const bool is_fair_mutex = false
Private Member Functions
void __TBB_EXPORTED_METHOD internal_construct ()
All checks from mutex constructor using mutex.state were moved here.
void __TBB_EXPORTED_METHOD internal_destroy ()
All checks from mutex destructor using mutex.state were moved here.
Private Attributes
pthread_mutex_t impl
Friends
class scoped_lock
Detailed Description
Mutex that allows recursive mutex acquisition.
Mutex that allows recursive mutex acquisition.
Definition at line 39 of file recursive_mutex.h.
Member Typedef Documentation
typedef pthread_mutex_t* tbb::recursive_mutex::native_handle_type
Return native_handle.
Definition at line 208 of file recursive_mutex.h.
Constructor & Destructor Documentation
tbb::recursive_mutex::recursive_mutex () inline
Construct unacquired recursive_mutex.
Definition at line 42 of file recursive_mutex.h.
References tbb::internal::handle_perror(), impl, and internal_construct().
                       {
 #if TBB_USE_ASSERT || TBB_USE_THREADING_TOOLS
         internal_construct();
 #else
   #if _WIN32||_WIN64
         InitializeCriticalSectionEx(&impl, 4000, 0);
   #else
         pthread_mutexattr_t mtx_attr;
         int error_code = pthread_mutexattr_init( &mtx_attr );
         if( error_code )
             tbb::internal::handle_perror(error_code,"recursive_mutex: pthread_mutexattr_init failed");
         pthread_mutexattr_settype( &mtx_attr, PTHREAD_MUTEX_RECURSIVE );
         error_code = pthread_mutex_init( &impl, &mtx_attr );
         if( error_code )
             tbb::internal::handle_perror(error_code,"recursive_mutex: pthread_mutex_init failed");
         pthread_mutexattr_destroy( &mtx_attr );
   #endif /* _WIN32||_WIN64*/
 #endif /* TBB_USE_ASSERT */
     };
tbb::recursive_mutex::~recursive_mutex () inline
Definition at line 64 of file recursive_mutex.h.
References impl, and internal_destroy().
{
 #if TBB_USE_ASSERT
         internal_destroy();
 #else
   #if _WIN32||_WIN64
         DeleteCriticalSection(&impl);
   #else
         pthread_mutex_destroy(&impl);
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     };
Member Function Documentation
void tbb::recursive_mutex::internal_construct () private
All checks from mutex constructor using mutex.state were moved here.
Definition at line 97 of file recursive_mutex.cpp.
References _T, tbb::internal::handle_perror(), impl, and ITT_SYNC_CREATE.
Referenced by recursive_mutex().
{
 #if _WIN32||_WIN64
     InitializeCriticalSectionEx(&impl, 4000, 0);
     state = INITIALIZED;
 #else
     pthread_mutexattr_t mtx_attr;
     int error_code = pthread_mutexattr_init( &mtx_attr );
     if( error_code )
         tbb::internal::handle_perror(error_code,"recursive_mutex: pthread_mutexattr_init failed");
     pthread_mutexattr_settype( &mtx_attr, PTHREAD_MUTEX_RECURSIVE );
     error_code = pthread_mutex_init( &impl, &mtx_attr );
     if( error_code )
         tbb::internal::handle_perror(error_code,"recursive_mutex: pthread_mutex_init failed");
     pthread_mutexattr_destroy( &mtx_attr );
 #endif /* _WIN32||_WIN64*/
     ITT_SYNC_CREATE(&impl, _T("tbb::recursive_mutex"), _T(""));
 }
void tbb::recursive_mutex::internal_destroy () private
All checks from mutex destructor using mutex.state were moved here.
Definition at line 116 of file recursive_mutex.cpp.
References __TBB_ASSERT, __TBB_ASSERT_EX, and impl.
Referenced by ~recursive_mutex().
{
 #if _WIN32||_WIN64
     switch( state ) {
       case INITIALIZED:
         DeleteCriticalSection(&impl);
         break;
       case DESTROYED:
         __TBB_ASSERT(false,"recursive_mutex: already destroyed");
         break;
       default:
         __TBB_ASSERT(false,"recursive_mutex: illegal state for destruction");
         break;
     }
     state = DESTROYED;
 #else
     int error_code = pthread_mutex_destroy(&impl);
     __TBB_ASSERT_EX(!error_code,"recursive_mutex: pthread_mutex_destroy failed");
 #endif /* _WIN32||_WIN64 */
 }
void tbb::recursive_mutex::lock () inline
Acquire lock.
Definition at line 158 of file recursive_mutex.h.
References tbb::aligned_space< T, N >::begin(), tbb::internal::handle_perror(), impl, and tbb::recursive_mutex::scoped_lock::scoped_lock().
Referenced by tbb::recursive_mutex::scoped_lock::acquire().
                 {
 #if TBB_USE_ASSERT
         aligned_space<scoped_lock> tmp;
         new(tmp.begin()) scoped_lock(*this);
 #else
   #if _WIN32||_WIN64
         EnterCriticalSection(&impl);
   #else
         int error_code = pthread_mutex_lock(&impl);
         if( error_code )
             tbb::internal::handle_perror(error_code,"recursive_mutex: pthread_mutex_lock failed");
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     }
native_handle_type tbb::recursive_mutex::native_handle () inline
Definition at line 210 of file recursive_mutex.h.
References impl.
 { return (native_handle_type) &impl; }
bool tbb::recursive_mutex::try_lock () inline
Try acquiring lock (non-blocking)
Return true if lock acquired; false otherwise.
Definition at line 175 of file recursive_mutex.h.
References tbb::aligned_space< T, N >::begin(), and impl.
Referenced by tbb::recursive_mutex::scoped_lock::try_acquire().
                     {
 #if TBB_USE_ASSERT
         aligned_space<scoped_lock> tmp;
         return (new(tmp.begin()) scoped_lock)->internal_try_acquire(*this);
 #else
   #if _WIN32||_WIN64
         return TryEnterCriticalSection(&impl)!=0;
   #else
         return pthread_mutex_trylock(&impl)==0;
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     }
void tbb::recursive_mutex::unlock () inline
Release lock.
Definition at line 189 of file recursive_mutex.h.
References tbb::aligned_space< T, N >::begin(), impl, tbb::recursive_mutex::scoped_lock::internal_release(), tbb::recursive_mutex::scoped_lock::my_mutex, and s.
Referenced by tbb::recursive_mutex::scoped_lock::release().
                   {
 #if TBB_USE_ASSERT
         aligned_space<scoped_lock> tmp;
         scoped_lock& s = *tmp.begin();
         s.my_mutex = this;
         s.internal_release();
 #else
   #if _WIN32||_WIN64
         LeaveCriticalSection(&impl);
   #else
         pthread_mutex_unlock(&impl);
   #endif /* _WIN32||_WIN64 */
 #endif /* TBB_USE_ASSERT */
     }
Friends And Related Function Documentation
friend class scoped_lock friend
Definition at line 77 of file recursive_mutex.h.
Member Data Documentation
pthread_mutex_t tbb::recursive_mutex::impl private
Definition at line 220 of file recursive_mutex.h.
Referenced by tbb::recursive_mutex::scoped_lock::internal_acquire(), internal_construct(), internal_destroy(), tbb::recursive_mutex::scoped_lock::internal_release(), tbb::recursive_mutex::scoped_lock::internal_try_acquire(), lock(), native_handle(), recursive_mutex(), try_lock(), unlock(), and ~recursive_mutex().
const bool tbb::recursive_mutex::is_fair_mutex = false static
Definition at line 153 of file recursive_mutex.h.
const bool tbb::recursive_mutex::is_recursive_mutex = true static
Definition at line 152 of file recursive_mutex.h.
const bool tbb::recursive_mutex::is_rw_mutex = false static
Definition at line 151 of file recursive_mutex.h.
The documentation for this class was generated from the following files:
recursive_mutex.h
recursive_mutex.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.