Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::rml::private_worker Class Reference
tbb::internal::rml::private_worker Class Reference
Protected Member Functions
private_worker (private_server &server, tbb_client &client, const size_t i)
Private Types
enum state_t { st_init, st_starting, st_normal, st_quit }
State in finite-state machine that controls the worker.
Private Member Functions
void run ()
Actions executed by the associated thread.
void wake_or_launch ()
Wake up associated thread (or launch a thread if there is none)
void start_shutdown ()
Called by a thread (usually not the associated thread) to commence termination.
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Static Private Member Functions
static __RML_DECL_THREAD_ROUTINE thread_routine (void *arg)
static void release_handle (thread_handle my_handle, bool join)
Private Attributes
atomic< state_t > my_state
private_server & my_server
Associated server.
tbb_client & my_client
Associated client.
const size_t my_index
index used for avoiding the 64K aliasing problem
thread_monitor my_thread_monitor
Monitor for sleeping when there is no work to do.
thread_handle my_handle
Handle of the OS thread associated with this worker.
private_worker * my_next
Link for list of workers that are sleeping or have no associated thread.
Friends
class private_server
Detailed Description
Definition at line 39 of file private_server.cpp.
Member Enumeration Documentation
enum tbb::internal::rml::private_worker::state_t private
State in finite-state machine that controls the worker.
State diagram: init –> starting –> normal | | | | V | ---—> quit <---—/
Enumerator
st_init
*this is initialized
st_starting
*this has associated thread that is starting up.
st_normal
Associated thread is doing normal life sequence.
st_quit
Associated thread has ended normal life sequence and promises to never touch *this again.
Definition at line 48 of file private_server.cpp.
                  {
         st_init,
         st_starting,
         st_normal,
         st_quit
     };
Constructor & Destructor Documentation
tbb::internal::rml::private_worker::private_worker (private_server & server, tbb_client & client, const size_t i) inline protected
Definition at line 96 of file private_server.cpp.
References st_init.
                                                                                  :
         my_server(server), my_client(client), my_index(i),
         my_thread_monitor(), my_handle(), my_next()
     {
         my_state = st_init;
     }
Member Function Documentation
void tbb::internal::rml::private_worker::release_handle (thread_handle my_handle, bool join) static private
Definition at line 230 of file private_server.cpp.
Referenced by start_shutdown(), and wake_or_launch().
{
     if (join)
         thread_monitor::join(handle);
     else
         thread_monitor::detach_thread(handle);
 }
void tbb::internal::rml::private_worker::run () private
Actions executed by the associated thread.
Definition at line 260 of file private_server.cpp.
References __TBB_ASSERT, my_client, my_next, my_server, tbb::internal::rml::private_server::my_slack, my_state, my_thread_monitor, tbb::internal::rml::private_server::propagate_chain_reaction(), tbb::internal::rml::private_server::remove_server_ref(), st_quit, and tbb::internal::rml::private_server::try_insert_in_asleep_list().
{
     my_server.propagate_chain_reaction();
     // Transiting to st_normal here would require setting my_handle,
     // which would create race with the launching thread and
     // complications in handle management on Windows.
     ::rml::job& j = *my_client.create_one_job();
     while( my_state!=st_quit ) {
         if( my_server.my_slack>=0 ) {
             my_client.process(j);
         } else {
             thread_monitor::cookie c;
             // Prepare to wait
             my_thread_monitor.prepare_wait(c);
             // Check/set the invariant for sleeping
             if( my_state!=st_quit && my_server.try_insert_in_asleep_list(*this) ) {
                 my_thread_monitor.commit_wait(c);
                 __TBB_ASSERT( my_state==st_quit || !my_next, "Thread monitor missed a spurious wakeup?" );
                 my_server.propagate_chain_reaction();
             } else {
                 // Invariant broken
                 my_thread_monitor.cancel_wait();
             }
         }
     }
     my_client.cleanup(j);
     ++my_server.my_slack;
     my_server.remove_server_ref();
 }
void tbb::internal::rml::private_worker::start_shutdown () private
Called by a thread (usually not the associated thread) to commence termination.
Definition at line 237 of file private_server.cpp.
References __TBB_ASSERT, tbb::internal::atomic_impl< T >::compare_and_swap(), tbb::internal::governor::does_client_join_workers(), my_client, my_handle, my_server, my_state, my_thread_monitor, release_handle(), tbb::internal::rml::private_server::remove_server_ref(), s, st_init, st_normal, st_quit, and st_starting.
Referenced by tbb::internal::rml::private_server::request_close_connection().
{
     state_t s;
     do {
         s = my_state;
         __TBB_ASSERT( s!=st_quit, NULL );
     } while( my_state.compare_and_swap( st_quit, s )!=s );
     if( s==st_normal || s==st_starting ) {
         // May have invalidated invariant for sleeping, so wake up the thread.
         // Note that the notify() here occurs without maintaining invariants for my_slack.
         // It does not matter, because my_state==st_quit overrides checking of my_slack.
         my_thread_monitor.notify();
         // Do not need release handle in st_init state,
         // because in this case the thread wasn't started yet.
         // For st_starting release is done at launch site.
         if (s==st_normal)
             release_handle(my_handle, governor::does_client_join_workers(my_client));
     } else if( s==st_init ) {
         // Perform action that otherwise would be performed by associated thread when it quits.
         my_server.remove_server_ref();
     }
 }
__RML_DECL_THREAD_ROUTINE tbb::internal::rml::private_worker::thread_routine (void * arg) static private
Definition at line 220 of file private_server.cpp.
Referenced by wake_or_launch().
{
     private_worker* self = static_cast<private_worker*>(arg);
     AVOID_64K_ALIASING( self->my_index );
     self->run();
     return 0;
 }
void tbb::internal::rml::private_worker::wake_or_launch () inline private
Wake up associated thread (or launch a thread if there is none)
Definition at line 292 of file private_server.cpp.
References __TBB_ASSERT, tbb::internal::atomic_impl< T >::compare_and_swap(), tbb::internal::governor::does_client_join_workers(), my_client, my_handle, my_next, my_server, tbb::internal::rml::private_server::my_stack_size, my_state, my_thread_monitor, tbb::internal::affinity_helper::protect_affinity_mask(), release_handle(), s, st_init, st_normal, st_quit, st_starting, and thread_routine().
Referenced by tbb::internal::rml::private_server::wake_some().
{
     if( my_state==st_init && my_state.compare_and_swap( st_starting, st_init )==st_init ) {
         // after this point, remove_server_ref() must be done by created thread
 #if USE_WINTHREAD
         my_handle = thread_monitor::launch( thread_routine, this, my_server.my_stack_size, &this->my_index );
 #elif USE_PTHREAD
         {
         affinity_helper fpa;
         fpa.protect_affinity_mask( /*restore_process_mask=*/true );
         my_handle = thread_monitor::launch( thread_routine, this, my_server.my_stack_size );
         // Implicit destruction of fpa resets original affinity mask.
         }
 #endif /* USE_PTHREAD */
         state_t s = my_state.compare_and_swap( st_normal, st_starting );
         if (st_starting != s) {
             // Do shutdown during startup. my_handle can't be released
             // by start_shutdown, because my_handle value might be not set yet
             // at time of transition from st_starting to st_quit.
             __TBB_ASSERT( s==st_quit, NULL );
             release_handle(my_handle, governor::does_client_join_workers(my_client));
         }
     }
     else {
         __TBB_ASSERT( !my_next, "Should not wake a thread while it's still in asleep list" );
         my_thread_monitor.notify();
     }
 }
Friends And Related Function Documentation
friend class private_server friend
Definition at line 80 of file private_server.cpp.
Member Data Documentation
tbb_client& tbb::internal::rml::private_worker::my_client private
Associated client.
Definition at line 64 of file private_server.cpp.
Referenced by run(), start_shutdown(), and wake_or_launch().
thread_handle tbb::internal::rml::private_worker::my_handle private
Handle of the OS thread associated with this worker.
Definition at line 75 of file private_server.cpp.
Referenced by start_shutdown(), and wake_or_launch().
const size_t tbb::internal::rml::private_worker::my_index private
index used for avoiding the 64K aliasing problem
Definition at line 67 of file private_server.cpp.
private_worker* tbb::internal::rml::private_worker::my_next private
Link for list of workers that are sleeping or have no associated thread.
Definition at line 78 of file private_server.cpp.
Referenced by tbb::internal::rml::private_server::private_server(), run(), tbb::internal::rml::private_server::try_insert_in_asleep_list(), wake_or_launch(), and tbb::internal::rml::private_server::wake_some().
private_server& tbb::internal::rml::private_worker::my_server private
Associated server.
Definition at line 61 of file private_server.cpp.
Referenced by run(), start_shutdown(), and wake_or_launch().
atomic<state_t> tbb::internal::rml::private_worker::my_state private
Definition at line 58 of file private_server.cpp.
Referenced by run(), start_shutdown(), and wake_or_launch().
thread_monitor tbb::internal::rml::private_worker::my_thread_monitor private
Monitor for sleeping when there is no work to do.
The invariant that holds for sleeping workers is: "my_slack<=0 && my_state==st_normal && I am on server's list of asleep threads"
Definition at line 72 of file private_server.cpp.
Referenced by run(), start_shutdown(), and wake_or_launch().
The documentation for this class was generated from the following file:
private_server.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.