Intel(R) Threading Building Blocks Doxygen Documentation: tbb::mutex::scoped_lock Class Reference
tbb::mutex::scoped_lock Class Reference
The scoped locking pattern.
#include <mutex.h>
Public Member Functions
scoped_lock ()
Construct lock that has not acquired a mutex.
scoped_lock (mutex &mutex)
Acquire lock on given mutex.
~scoped_lock ()
Release lock (if lock is held).
void acquire (mutex &mutex)
Acquire lock on given mutex.
bool try_acquire (mutex &mutex)
Try acquire lock on given mutex.
void release ()
Release lock.
Private Member Functions
void __TBB_EXPORTED_METHOD internal_acquire (mutex &m)
All checks from acquire using mutex.state were moved here.
bool __TBB_EXPORTED_METHOD internal_try_acquire (mutex &m)
All checks from try_acquire using mutex.state were moved here.
void __TBB_EXPORTED_METHOD internal_release ()
All checks from release using mutex.state were moved here.
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
mutex * my_mutex
The pointer to the current mutex to work.
Friends
class mutex
Detailed Description
The scoped locking pattern.
It helps to avoid the common problem of forgetting to release lock. It also nicely provides the "node" for queuing locks.
Definition at line 75 of file mutex.h.
Constructor & Destructor Documentation
tbb::mutex::scoped_lock::scoped_lock () inline
Construct lock that has not acquired a mutex.
Definition at line 78 of file mutex.h.
Referenced by tbb::mutex::lock().
 : my_mutex(NULL) {};
tbb::mutex::scoped_lock::scoped_lock (mutex & mutex) inline
Acquire lock on given mutex.
Definition at line 81 of file mutex.h.
References acquire().
{
             acquire( mutex );
         }
tbb::mutex::scoped_lock::~scoped_lock () inline
Release lock (if lock is held).
Definition at line 86 of file mutex.h.
References my_mutex, and release().
{
             if( my_mutex )
                 release();
         }
Member Function Documentation
void tbb::mutex::scoped_lock::acquire (mutex & mutex) inline
Acquire lock on given mutex.
Definition at line 92 of file mutex.h.
References internal_acquire(), tbb::mutex::lock(), mutex, and my_mutex.
Referenced by scoped_lock().
{
 #if TBB_USE_ASSERT
             internal_acquire(mutex);
 #else
             mutex.lock();
             my_mutex = &mutex;
 #endif /* TBB_USE_ASSERT */
         }
void tbb::mutex::scoped_lock::internal_acquire (mutex & m) private
All checks from acquire using mutex.state were moved here.
Definition at line 31 of file mutex.cpp.
References __TBB_ASSERT, tbb::mutex::DESTROYED, tbb::internal::handle_perror(), tbb::mutex::HELD, tbb::mutex::impl, tbb::mutex::INITIALIZED, and my_mutex.
Referenced by acquire().
{
 #if _WIN32||_WIN64
         switch( m.state ) {
         case INITIALIZED:
         case HELD:
             EnterCriticalSection( &m.impl );
             // If a thread comes here, and another thread holds the lock, it will block
             // in EnterCriticalSection.  When it returns from EnterCriticalSection,
             // m.state must be set to INITIALIZED.  If the same thread tries to acquire a lock it
             // already holds, the lock is in HELD state, thus will cause throwing the exception.
             if (m.state==HELD)
                 tbb::internal::handle_perror(EDEADLK,"mutex::scoped_lock: deadlock caused by attempt to reacquire held mutex");
             m.state = HELD;
             break;
         case DESTROYED:
             __TBB_ASSERT(false,"mutex::scoped_lock: mutex already destroyed");
             break;
         default:
             __TBB_ASSERT(false,"mutex::scoped_lock: illegal mutex state");
             break;
         }
 #else
         int error_code = pthread_mutex_lock(&m.impl);
         if( error_code )
             tbb::internal::handle_perror(error_code,"mutex::scoped_lock: pthread_mutex_lock failed");
 #endif /* _WIN32||_WIN64 */
         my_mutex = &m;
     }
void tbb::mutex::scoped_lock::internal_release () private
All checks from release using mutex.state were moved here.
Definition at line 61 of file mutex.cpp.
References __TBB_ASSERT, __TBB_ASSERT_EX, tbb::mutex::DESTROYED, tbb::mutex::HELD, tbb::mutex::impl, tbb::mutex::INITIALIZED, and my_mutex.
Referenced by release(), and tbb::mutex::unlock().
{
     __TBB_ASSERT( my_mutex, "mutex::scoped_lock: not holding a mutex" );
 #if _WIN32||_WIN64
      switch( my_mutex->state ) {
         case INITIALIZED:
             __TBB_ASSERT(false,"mutex::scoped_lock: try to release the lock without acquisition");
             break;
         case HELD:
             my_mutex->state = INITIALIZED;
             LeaveCriticalSection(&my_mutex->impl);
             break;
         case DESTROYED:
             __TBB_ASSERT(false,"mutex::scoped_lock: mutex already destroyed");
             break;
         default:
             __TBB_ASSERT(false,"mutex::scoped_lock: illegal mutex state");
             break;
     }
 #else
      int error_code = pthread_mutex_unlock(&my_mutex->impl);
      __TBB_ASSERT_EX(!error_code, "mutex::scoped_lock: pthread_mutex_unlock failed");
 #endif /* _WIN32||_WIN64 */
      my_mutex = NULL;
 }
bool tbb::mutex::scoped_lock::internal_try_acquire (mutex & m) private
All checks from try_acquire using mutex.state were moved here.
Definition at line 86 of file mutex.cpp.
References __TBB_ASSERT, tbb::mutex::DESTROYED, tbb::mutex::HELD, tbb::mutex::impl, tbb::mutex::INITIALIZED, and my_mutex.
Referenced by try_acquire(), and tbb::mutex::try_lock().
{
 #if _WIN32||_WIN64
     switch( m.state ) {
         case INITIALIZED:
         case HELD:
             break;
         case DESTROYED:
             __TBB_ASSERT(false,"mutex::scoped_lock: mutex already destroyed");
             break;
         default:
             __TBB_ASSERT(false,"mutex::scoped_lock: illegal mutex state");
             break;
     }
 #endif /* _WIN32||_WIN64 */
     bool result;
 #if _WIN32||_WIN64
     result = TryEnterCriticalSection(&m.impl)!=0;
     if( result ) {
         __TBB_ASSERT(m.state!=HELD, "mutex::scoped_lock: deadlock caused by attempt to reacquire held mutex");
         m.state = HELD;
     }
 #else
     result = pthread_mutex_trylock(&m.impl)==0;
 #endif /* _WIN32||_WIN64 */
     if( result )
         my_mutex = &m;
     return result;
 }
void tbb::mutex::scoped_lock::release () inline
Release lock.
Definition at line 114 of file mutex.h.
References internal_release(), my_mutex, and tbb::mutex::unlock().
Referenced by ~scoped_lock().
{
 #if TBB_USE_ASSERT
             internal_release ();
 #else
             my_mutex->unlock();
             my_mutex = NULL;
 #endif /* TBB_USE_ASSERT */
         }
bool tbb::mutex::scoped_lock::try_acquire (mutex & mutex) inline
Try acquire lock on given mutex.
Definition at line 102 of file mutex.h.
References internal_try_acquire(), mutex, my_mutex, and tbb::mutex::try_lock().
{
 #if TBB_USE_ASSERT
             return internal_try_acquire (mutex);
 #else
             bool result = mutex.try_lock();
             if( result )
                 my_mutex = &mutex;
             return result;
 #endif /* TBB_USE_ASSERT */
         }
Friends And Related Function Documentation
friend class mutex friend
Definition at line 136 of file mutex.h.
Referenced by acquire(), and try_acquire().
Member Data Documentation
mutex* tbb::mutex::scoped_lock::my_mutex private
The pointer to the current mutex to work.
Definition at line 125 of file mutex.h.
Referenced by acquire(), internal_acquire(), internal_release(), internal_try_acquire(), release(), try_acquire(), tbb::mutex::try_lock(), tbb::mutex::unlock(), and ~scoped_lock().
The documentation for this class was generated from the following files:
mutex.h
mutex.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.