Intel(R) Threading Building Blocks Doxygen Documentation: internal::queueing_port< T > Class Template Reference
internal::queueing_port< T > Class Template Reference
queueing join_port
#include <_flow_graph_join_impl.h>
Classes
class queueing_port_operation
Public Types
typedef T input_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef queueing_port< T > class_type
Public Types inherited from internal::item_buffer< T, A >
enum buffer_item_state { no_item =0, has_item =1, reserved_item =2 }
typedef T item_type
Public Member Functions
queueing_port ()
Constructor.
queueing_port (const queueing_port &)
copy constructor
void set_join_node_pointer (forwarding_base *join)
record parent for tallying available items
bool get_item (T &v)
void reset_port ()
void reset_receiver (reset_flags f) __TBB_override
Public Member Functions inherited from internal::item_buffer< T, A >
item_buffer ()
Constructor.
~item_buffer ()
void reset ()
Protected Member Functions
task * try_put_task (const T &v) __TBB_override
graph & graph_reference () __TBB_override
Protected Member Functions inherited from internal::item_buffer< T, A >
bool buffer_empty () const
buffer_item_type & item (size_type i)
const buffer_item_type & item (size_type i) const
bool my_item_valid (size_type i) const
bool my_item_reserved (size_type i) const
const item_type & get_my_item (size_t i) const
void set_my_item (size_t i, const item_type &o)
void fetch_item (size_t i, item_type &o)
void move_item (size_t to, size_t from)
bool place_item (size_t here, const item_type &me)
void swap_items (size_t i, size_t j)
void destroy_item (size_type i)
const item_type & front () const
const item_type & back () const
void reserve_item (size_type i)
void release_item (size_type i)
void destroy_front ()
void destroy_back ()
size_type size (size_t new_tail=0)
size_type capacity ()
bool buffer_full ()
void grow_my_array (size_t minimum_size)
Grows the internal array.
bool push_back (item_type &v)
bool pop_back (item_type &v)
bool pop_front (item_type &v)
void clean_up_buffer (bool reset_pointers)
Private Types
enum op_type { get__item, res_port, try__put_task }
enum op_stat { WAIT =0, SUCCEEDED, FAILED }
typedef internal::aggregating_functor< class_type, queueing_port_operation > handler_type
Private Member Functions
void handle_operations (queueing_port_operation *op_list)
Private Attributes
aggregator< handler_type, queueing_port_operation > my_aggregator
forwarding_base * my_join
Friends
class internal::aggregating_functor< class_type, queueing_port_operation >
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Additional Inherited Members
Protected Types inherited from internal::item_buffer< T, A >
typedef size_t size_type
typedef aligned_pair< item_type, buffer_item_state >::type buffer_item_type
typedef A::template rebind< buffer_item_type >::other allocator_type
Protected Attributes inherited from internal::item_buffer< T, A >
buffer_item_type * my_array
size_type my_array_size
size_type my_head
size_type my_tail
Static Protected Attributes inherited from internal::item_buffer< T, A >
static const size_type initial_buffer_size = 4
Detailed Description
template<typename T>
class internal::queueing_port< T >
queueing join_port
Definition at line 431 of file _flow_graph_join_impl.h.
Member Typedef Documentation
template<typename T > typedef queueing_port<T> internal::queueing_port< T >::class_type
Definition at line 435 of file _flow_graph_join_impl.h.
template<typename T > typedef internal::aggregating_functor<class_type, queueing_port_operation> internal::queueing_port< T >::handler_type private
Definition at line 477 of file _flow_graph_join_impl.h.
template<typename T > typedef T internal::queueing_port< T >::input_type
Definition at line 433 of file _flow_graph_join_impl.h.
template<typename T > typedef receiver<input_type>::predecessor_type internal::queueing_port< T >::predecessor_type
Definition at line 434 of file _flow_graph_join_impl.h.
Member Enumeration Documentation
template<typename T > enum internal::queueing_port::op_stat private
Enumerator
WAIT
SUCCEEDED
FAILED
Definition at line 448 of file _flow_graph_join_impl.h.
 {WAIT=0, SUCCEEDED, FAILED};
template<typename T > enum internal::queueing_port::op_type private
Enumerator
get__item
res_port
try__put_task
Definition at line 443 of file _flow_graph_join_impl.h.
                      { get__item, res_port, try__put_task
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
             , add_blt_pred, del_blt_pred, blt_pred_cnt, blt_pred_cpy
 #endif
         };
Constructor & Destructor Documentation
template<typename T > internal::queueing_port< T >::queueing_port () inline
Constructor.
Definition at line 558 of file _flow_graph_join_impl.h.
                         : item_buffer<T>() {
             my_join = NULL;
             my_aggregator.initialize_handler(handler_type(this));
         }
template<typename T > internal::queueing_port< T >::queueing_port (const queueing_port< T > &) inline
copy constructor
Definition at line 564 of file _flow_graph_join_impl.h.
                                               : receiver<T>(), item_buffer<T>() {
             my_join = NULL;
             my_aggregator.initialize_handler(handler_type(this));
         }
Member Function Documentation
template<typename T > bool internal::queueing_port< T >::get_item (T & v) inline
Definition at line 574 of file _flow_graph_join_impl.h.
References SUCCEEDED.
{
             queueing_port_operation op_data(&v, get__item);
             my_aggregator.execute(&op_data);
             return op_data.status == SUCCEEDED;
         }
template<typename T > graph& internal::queueing_port< T >::graph_reference () inline protected
Definition at line 551 of file _flow_graph_join_impl.h.
{
             return my_join->graph_ref;
         }
template<typename T > void internal::queueing_port< T >::handle_operations (queueing_port_operation * op_list) inline private
Definition at line 481 of file _flow_graph_join_impl.h.
References __TBB_ASSERT, tbb::internal::__TBB_store_with_release(), internal::queueing_port< T >::queueing_port_operation::bypass_t, internal::queueing_port< T >::queueing_port_operation::my_arg, internal::queueing_port< T >::queueing_port_operation::my_val, SUCCEEDED, tbb::flow::internal::SUCCESSFULLY_ENQUEUED, task, internal::queueing_port< T >::queueing_port_operation::type, and void.
{
             queueing_port_operation *current;
             bool was_empty;
             while(op_list) {
                 current = op_list;
                 op_list = op_list->next;
                 switch(current->type) {
                 case try__put_task: {
                         task *rtask = NULL;
                         was_empty = this->buffer_empty();
                         this->push_back(current->my_val);
                         if (was_empty) rtask = my_join->decrement_port_count(false);
                         else
                             rtask = SUCCESSFULLY_ENQUEUED;
                         current->bypass_t = rtask;
                         __TBB_store_with_release(current->status, SUCCEEDED);
                     }
                     break;
                 case get__item:
                     if(!this->buffer_empty()) {
                         *(current->my_arg) = this->front();
                         __TBB_store_with_release(current->status, SUCCEEDED);
                     }
                     else {
                         __TBB_store_with_release(current->status, FAILED);
                     }
                     break;
                 case res_port:
                     __TBB_ASSERT(this->my_item_valid(this->my_head), "No item to reset");
                     this->destroy_front();
                     if(this->my_item_valid(this->my_head)) {
                         (void)my_join->decrement_port_count(true);
                     }
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
                 case add_blt_pred:
                     my_built_predecessors.add_edge(*(current->pred));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case del_blt_pred:
                     my_built_predecessors.delete_edge(*(current->pred));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case blt_pred_cnt:
                     current->cnt_val = my_built_predecessors.edge_count();
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
                 case blt_pred_cpy:
                     my_built_predecessors.copy_edges(*(current->plist));
                     __TBB_store_with_release(current->status, SUCCEEDED);
                     break;
 #endif  /* TBB_DEPRECATED_FLOW_NODE_EXTRACTION */
                 }
             }
         }
template<typename T > void internal::queueing_port< T >::reset_port () inline
Definition at line 582 of file _flow_graph_join_impl.h.
References __TBB_override, p, and internal::item_buffer< T, A >::reset().
{
             queueing_port_operation op_data(res_port);
             my_aggregator.execute(&op_data);
             return;
         }
template<typename T > void internal::queueing_port< T >::reset_receiver (reset_flags f) inline
Definition at line 621 of file _flow_graph_join_impl.h.
References internal::item_buffer< T, A >::reset(), tbb::flow::interface10::rf_clear_edges, and tbb::internal::suppress_unused_warning().
{
             tbb::internal::suppress_unused_warning(f);
             item_buffer<T>::reset();
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
             if (f & rf_clear_edges)
                 my_built_predecessors.clear();
 #endif
         }
template<typename T > void internal::queueing_port< T >::set_join_node_pointer (forwarding_base * join) inline
record parent for tallying available items
Definition at line 570 of file _flow_graph_join_impl.h.
{
             my_join = join;
         }
template<typename T > task* internal::queueing_port< T >::try_put_task (const T & v) inline protected
Definition at line 543 of file _flow_graph_join_impl.h.
References __TBB_ASSERT, internal::queueing_port< T >::queueing_port_operation::bypass_t, SUCCEEDED, and tbb::flow::internal::SUCCESSFULLY_ENQUEUED.
{
             queueing_port_operation op_data(v, try__put_task);
             my_aggregator.execute(&op_data);
             __TBB_ASSERT(op_data.status == SUCCEEDED || !op_data.bypass_t, "inconsistent return from aggregator");
             if(!op_data.bypass_t) return SUCCESSFULLY_ENQUEUED;
             return op_data.bypass_t;
         }
Friends And Related Function Documentation
template<typename T > friend class internal::aggregating_functor< class_type, queueing_port_operation > friend
Definition at line 478 of file _flow_graph_join_impl.h.
template<typename T > template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 541 of file _flow_graph_join_impl.h.
template<typename T > template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 542 of file _flow_graph_join_impl.h.
template<typename T > template<typename R , typename B > friend class run_and_put_task friend
Definition at line 540 of file _flow_graph_join_impl.h.
Member Data Documentation
template<typename T > aggregator<handler_type, queueing_port_operation> internal::queueing_port< T >::my_aggregator private
Definition at line 479 of file _flow_graph_join_impl.h.
template<typename T > forwarding_base* internal::queueing_port< T >::my_join private
Definition at line 631 of file _flow_graph_join_impl.h.
The documentation for this class was generated from the following file:
_flow_graph_join_impl.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.