Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation Struct Reference
tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation Struct Reference
Public Member Functions
retrieve_aggregator_operation (key_type key)
void handle (self_type &container)
map_storage_type::reference result ()
bool is_new_value_needed ()
Public Member Functions inherited from tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::aggregator_operation
aggregator_operation (e_op_type operation_type)
void cast_and_handle (self_type &container)
Public Attributes
key_type my_key
map_storage_type::pointer my_result_map_record_pointer
bool my_is_new_value_needed
Public Attributes inherited from tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::aggregator_operation
e_op_type my_operation_type
Additional Inherited Members
Public Types inherited from tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::aggregator_operation
enum e_op_type { op_retive, op_signal_end_of_usage }
Detailed Description
template<typename key_type, typename value_type, typename value_functor_type = value_type (*)(key_type)>
struct tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation
Definition at line 210 of file concurrent_lru_cache.h.
Constructor & Destructor Documentation
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation::retrieve_aggregator_operation (key_type key) inline
Definition at line 214 of file concurrent_lru_cache.h.
 :aggregator_operation(aggregator_operation::op_retive),my_key(key),my_is_new_value_needed(false){}
Member Function Documentation
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> void tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation::handle (self_type & container) inline
Definition at line 215 of file concurrent_lru_cache.h.
References tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_serial().
{
             my_result_map_record_pointer = & container.retrieve_serial(my_key,my_is_new_value_needed);
         }
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> bool tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation::is_new_value_needed () inline
Definition at line 219 of file concurrent_lru_cache.h.
Referenced by tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::operator[]().
 {return my_is_new_value_needed;}
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> map_storage_type::reference tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation::result () inline
Definition at line 218 of file concurrent_lru_cache.h.
Referenced by tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::operator[]().
 { return * my_result_map_record_pointer; }
Member Data Documentation
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> bool tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation::my_is_new_value_needed
Definition at line 213 of file concurrent_lru_cache.h.
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> key_type tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation::my_key
Definition at line 211 of file concurrent_lru_cache.h.
template<typename key_type , typename value_type , typename value_functor_type = value_type (*)(key_type)> map_storage_type::pointer tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::retrieve_aggregator_operation::my_result_map_record_pointer
Definition at line 212 of file concurrent_lru_cache.h.
The documentation for this struct was generated from the following file:
concurrent_lru_cache.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.