Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare > Class Template Reference
tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare > Class Template Reference
Algorithms
Body class used to test if elements in a range are presorted.
#include <parallel_sort.h>
Public Member Functions
quick_sort_pretest_body (const Compare &_comp)
void operator() (const blocked_range< RandomAccessIterator > &range) const
Private Attributes
const Compare & comp
Detailed Description
template<typename RandomAccessIterator, typename Compare>
class tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >
Body class used to test if elements in a range are presorted.
Definition at line 125 of file parallel_sort.h.
Constructor & Destructor Documentation
template<typename RandomAccessIterator , typename Compare > tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >::quick_sort_pretest_body (const Compare & _comp) inline
Definition at line 129 of file parallel_sort.h.
 : comp(_comp) {}
Member Function Documentation
template<typename RandomAccessIterator , typename Compare > void tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >::operator() (const blocked_range< RandomAccessIterator > & range) const inline
Definition at line 131 of file parallel_sort.h.
References tbb::blocked_range< Value >::begin(), tbb::task::cancel_group_execution(), tbb::interface9::internal::quick_sort_range< RandomAccessIterator, Compare >::comp, tbb::blocked_range< Value >::end(), tbb::task::is_cancelled(), and tbb::task::self().
{
         task &my_task = task::self();
         RandomAccessIterator my_end = range.end();
         int i = 0;
         for (RandomAccessIterator k = range.begin(); k != my_end; ++k, ++i) {
             if ( i%64 == 0 && my_task.is_cancelled() ) break;
             // The k-1 is never out-of-range because the first chunk starts at begin+serial_cutoff+1
             if ( comp( *(k), *(k-1) ) ) {
                 my_task.cancel_group_execution();
                 break;
             }
         }
     }
Member Data Documentation
template<typename RandomAccessIterator , typename Compare > const Compare& tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >::comp private
Definition at line 126 of file parallel_sort.h.
The documentation for this class was generated from the following file:
parallel_sort.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.