Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::queue_node< T, A > Class Template Reference
tbb::flow::interface10::queue_node< T, A > Class Template Reference
Forwards messages in FIFO order.
#include <flow_graph.h>
Public Types
typedef T input_type
typedef T output_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
Public Types inherited from tbb::flow::interface10::buffer_node< T, A >
typedef T input_type
typedef T output_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
typedef buffer_node< T, A > class_type
Public Types inherited from tbb::flow::interface10::internal::item_buffer< T, A >
enum buffer_item_state { no_item =0, has_item =1, reserved_item =2 }
typedef T item_type
Public Types inherited from tbb::flow::interface10::receiver< T >
typedef T input_type
The input type of this receiver.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::sender< T >
typedef T output_type
The output type of this sender.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
queue_node (graph &g)
Constructor.
queue_node (const queue_node &src)
Copy constructor.
Public Member Functions inherited from tbb::flow::interface10::buffer_node< T, A >
buffer_node (graph &g)
Constructor.
buffer_node (const buffer_node &src)
Copy constructor.
bool register_successor (successor_type &r) __TBB_override
Adds a new successor.
bool remove_successor (successor_type &r) __TBB_override
Removes a successor.
bool try_get (T &v) __TBB_override
Request an item from the buffer_node.
bool try_reserve (T &v) __TBB_override
Reserves an item.
bool try_release () __TBB_override
Release a reserved item.
bool try_consume () __TBB_override
Consumes a reserved item.
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::internal::reservable_item_buffer< T, A >
reservable_item_buffer ()
void reset ()
Public Member Functions inherited from tbb::flow::interface10::internal::item_buffer< T, A >
item_buffer ()
Constructor.
~item_buffer ()
void reset ()
Public Member Functions inherited from tbb::flow::interface10::receiver< T >
bool try_put (const typename internal::async_helpers< T >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< T >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
virtual bool register_predecessor (predecessor_type &)
Add a predecessor to the node.
virtual bool remove_predecessor (predecessor_type &)
Remove a predecessor from the node.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
Protected Types
typedef buffer_node< T, A > base_type
typedef base_type::size_type size_type
typedef base_type::buffer_operation queue_operation
typedef queue_node class_type
Protected Types inherited from tbb::flow::interface10::buffer_node< T, A >
enum op_type {
reg_succ, rem_succ, req_item, res_item,
rel_res, con_res, put_item, try_fwd_task
}
typedef size_t size_type
typedef internal::aggregating_functor< class_type, buffer_operation > handler_type
Protected Types inherited from tbb::flow::interface10::internal::item_buffer< T, A >
typedef size_t size_type
typedef aligned_pair< item_type, buffer_item_state >::type buffer_item_type
typedef A::template rebind< buffer_item_type >::other allocator_type
Protected Member Functions
void internal_forward_task (queue_operation *op) __TBB_override
Tries to forward valid items to successors.
void internal_pop (queue_operation *op) __TBB_override
void internal_reserve (queue_operation *op) __TBB_override
void internal_consume (queue_operation *op) __TBB_override
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::buffer_node< T, A >
virtual void handle_operations (buffer_operation *op_list)
template<typename derived_type >
void handle_operations_impl (buffer_operation *op_list, derived_type *derived)
task * grab_forwarding_task (buffer_operation &op_data)
bool enqueue_forwarding_task (buffer_operation &op_data)
virtual task * forward_task ()
This is executed by an enqueued task, the "forwarder".
virtual void internal_reg_succ (buffer_operation *op)
Register successor.
virtual void internal_rem_succ (buffer_operation *op)
Remove successor.
template<typename derived_type >
void internal_forward_task_impl (buffer_operation *op, derived_type *derived)
virtual bool internal_push (buffer_operation *op)
virtual void internal_release (buffer_operation *op)
task * try_put_task (const T &t) __TBB_override
receive an item, return a task *if possible
graph & graph_reference () __TBB_override
void reset_receiver (reset_flags) __TBB_override
put receiver back in initial state
Protected Member Functions inherited from tbb::flow::interface10::internal::reservable_item_buffer< T, A >
bool reserve_front (T &v)
void consume_front ()
void release_front ()
Protected Member Functions inherited from tbb::flow::interface10::internal::item_buffer< T, A >
bool buffer_empty () const
buffer_item_type & item (size_type i)
const buffer_item_type & item (size_type i) const
bool my_item_valid (size_type i) const
bool my_item_reserved (size_type i) const
const item_type & get_my_item (size_t i) const
void set_my_item (size_t i, const item_type &o)
void fetch_item (size_t i, item_type &o)
void move_item (size_t to, size_t from)
bool place_item (size_t here, const item_type &me)
void swap_items (size_t i, size_t j)
void destroy_item (size_type i)
const item_type & front () const
const item_type & back () const
void reserve_item (size_type i)
void release_item (size_type i)
void destroy_front ()
void destroy_back ()
size_type size (size_t new_tail=0)
size_type capacity ()
bool buffer_full ()
void grow_my_array (size_t minimum_size)
Grows the internal array.
bool push_back (item_type &v)
bool pop_back (item_type &v)
bool pop_front (item_type &v)
void clean_up_buffer (bool reset_pointers)
Protected Member Functions inherited from tbb::flow::interface10::receiver< T >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Protected Member Functions inherited from tbb::flow::interface10::sender< T >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Private Member Functions
bool is_item_valid ()
void try_put_and_add_task (task *&last_task)
Friends
template<typename , typename >
class buffer_node
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::buffer_node< T, A >
internal::round_robin_cache< T, null_rw_mutex > my_successors
bool forwarder_busy
internal::aggregator< handler_type, buffer_operation > my_aggregator
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Protected Attributes inherited from tbb::flow::interface10::internal::reservable_item_buffer< T, A >
bool my_reserved
Protected Attributes inherited from tbb::flow::interface10::internal::item_buffer< T, A >
buffer_item_type * my_array
size_type my_array_size
size_type my_head
size_type my_tail
Static Protected Attributes inherited from tbb::flow::interface10::internal::item_buffer< T, A >
static const size_type initial_buffer_size = 4
Detailed Description
template<typename T, typename A = cache_aligned_allocator<T>>
class tbb::flow::interface10::queue_node< T, A >
Forwards messages in FIFO order.
Definition at line 2038 of file flow_graph.h.
Member Typedef Documentation
template<typename T , typename A = cache_aligned_allocator<T>> typedef buffer_node<T, A> tbb::flow::interface10::queue_node< T, A >::base_type protected
Definition at line 2040 of file flow_graph.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef queue_node tbb::flow::interface10::queue_node< T, A >::class_type protected
Definition at line 2043 of file flow_graph.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef T tbb::flow::interface10::queue_node< T, A >::input_type
Definition at line 2091 of file flow_graph.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef T tbb::flow::interface10::queue_node< T, A >::output_type
Definition at line 2092 of file flow_graph.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef receiver<input_type>::predecessor_type tbb::flow::interface10::queue_node< T, A >::predecessor_type
Definition at line 2093 of file flow_graph.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef base_type::buffer_operation tbb::flow::interface10::queue_node< T, A >::queue_operation protected
Definition at line 2042 of file flow_graph.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef base_type::size_type tbb::flow::interface10::queue_node< T, A >::size_type protected
Definition at line 2041 of file flow_graph.h.
template<typename T , typename A = cache_aligned_allocator<T>> typedef sender<output_type>::successor_type tbb::flow::interface10::queue_node< T, A >::successor_type
Definition at line 2094 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T , typename A = cache_aligned_allocator<T>> tbb::flow::interface10::queue_node< T, A >::queue_node (graph & g) inline explicit
Constructor.
Definition at line 2097 of file flow_graph.h.
References tbb::internal::fgt_node(), and tbb::flow::interface10::graph_node::my_graph.
                                     : base_type(g) {
         tbb::internal::fgt_node( tbb::internal::FLOW_QUEUE_NODE, &(this->my_graph),
                                  static_cast<receiver<input_type> *>(this),
                                  static_cast<sender<output_type> *>(this) );
     }
template<typename T , typename A = cache_aligned_allocator<T>> tbb::flow::interface10::queue_node< T, A >::queue_node (const queue_node< T, A > & src) inline
Copy constructor.
Definition at line 2104 of file flow_graph.h.
References __TBB_override, tbb::internal::fgt_node(), tbb::internal::fgt_node_desc(), and tbb::flow::interface10::graph_node::my_graph.
                                        : base_type(src) {
         tbb::internal::fgt_node( tbb::internal::FLOW_QUEUE_NODE, &(this->my_graph),
                                  static_cast<receiver<input_type> *>(this),
                                  static_cast<sender<output_type> *>(this) );
     }
Member Function Documentation
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::flow::interface10::queue_node< T, A >::internal_consume (queue_operation * op) inline protected virtual
Reimplemented from tbb::flow::interface10::buffer_node< T, A >.
Definition at line 2085 of file flow_graph.h.
References tbb::internal::__TBB_store_with_release(), and tbb::flow::interface10::internal::SUCCEEDED.
{
         this->consume_front();
         __TBB_store_with_release(op->status, internal::SUCCEEDED);
     }
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::flow::interface10::queue_node< T, A >::internal_forward_task (queue_operation * op) inline protected virtual
Tries to forward valid items to successors.
Reimplemented from tbb::flow::interface10::buffer_node< T, A >.
Definition at line 2063 of file flow_graph.h.
{
         this->internal_forward_task_impl(op, this);
     }
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::flow::interface10::queue_node< T, A >::internal_pop (queue_operation * op) inline protected virtual
Reimplemented from tbb::flow::interface10::buffer_node< T, A >.
Definition at line 2067 of file flow_graph.h.
References tbb::internal::__TBB_store_with_release(), tbb::flow::interface10::internal::FAILED, and tbb::flow::interface10::internal::SUCCEEDED.
{
         if ( this->my_reserved || !this->my_item_valid(this->my_head)){
             __TBB_store_with_release(op->status, internal::FAILED);
         }
         else {
             this->pop_front(*(op->elem));
             __TBB_store_with_release(op->status, internal::SUCCEEDED);
         }
     }
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::flow::interface10::queue_node< T, A >::internal_reserve (queue_operation * op) inline protected virtual
Reimplemented from tbb::flow::interface10::buffer_node< T, A >.
Definition at line 2076 of file flow_graph.h.
References tbb::internal::__TBB_store_with_release(), tbb::flow::interface10::internal::FAILED, and tbb::flow::interface10::internal::SUCCEEDED.
{
         if (this->my_reserved || !this->my_item_valid(this->my_head)) {
             __TBB_store_with_release(op->status, internal::FAILED);
         }
         else {
             this->reserve_front(*(op->elem));
             __TBB_store_with_release(op->status, internal::SUCCEEDED);
         }
     }
template<typename T , typename A = cache_aligned_allocator<T>> bool tbb::flow::interface10::queue_node< T, A >::is_item_valid () inline private
Definition at line 2048 of file flow_graph.h.
{
         return this->my_item_valid(this->my_head);
     }
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::flow::interface10::queue_node< T, A >::reset_node (reset_flags f) inline protected virtual
Reimplemented from tbb::flow::interface10::buffer_node< T, A >.
Definition at line 2117 of file flow_graph.h.
{
         base_type::reset_node(f);
     }
template<typename T , typename A = cache_aligned_allocator<T>> void tbb::flow::interface10::queue_node< T, A >::try_put_and_add_task (task *& last_task) inline private
Definition at line 2052 of file flow_graph.h.
References tbb::flow::interface10::combine_tasks(), and tbb::flow::interface10::internal::round_robin_cache< T, M >::try_put_task().
{
         task *new_task = this->my_successors.try_put_task(this->front());
         if (new_task) {
             // workaround for icc bug
             graph& graph_ref = this->graph_reference();
             last_task = combine_tasks(graph_ref, last_task, new_task);
             this->destroy_front();
         }
     }
Friends And Related Function Documentation
template<typename T , typename A = cache_aligned_allocator<T>> template<typename , typename > friend class buffer_node friend
Definition at line 2046 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.