Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::rml::private_server Class Reference
tbb::internal::rml::private_server Class Reference
Public Member Functions
private_server (tbb_client &client)
version_type version () const __TBB_override
void request_close_connection (bool) __TBB_override
void yield () __TBB_override
void independent_thread_number_changed (int) __TBB_override
unsigned default_concurrency () const __TBB_override
void adjust_job_count_estimate (int delta) __TBB_override
Private Types
typedef scheduler_mutex_type asleep_list_mutex_type
Protects my_asleep_list_root.
Private Member Functions
void propagate_chain_reaction ()
Wake up to two sleeping workers, if there are any sleeping.
bool try_insert_in_asleep_list (private_worker &t)
Try to add t to list of sleeping workers.
void wake_some (int additional_slack)
Equivalent of adding additional_slack to my_slack and waking up to 2 threads if my_slack permits.
virtual ~private_server ()
void remove_server_ref ()
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Private Attributes
tbb_client & my_client
const tbb_client::size_type my_n_thread
Maximum number of threads to be created.
const size_t my_stack_size
Stack size for each thread. */.
atomic< int > my_slack
Number of jobs that could use their associated thread minus number of active threads.
atomic< int > my_ref_count
Counter used to determine when to delete this.
padded_private_worker * my_thread_array
tbb::atomic< private_worker * > my_asleep_list_root
List of workers that are asleep or committed to sleeping until notified by another thread.
asleep_list_mutex_type my_asleep_list_mutex
Friends
class private_worker
Detailed Description
Definition at line 122 of file private_server.cpp.
Member Typedef Documentation
typedef scheduler_mutex_type tbb::internal::rml::private_server::asleep_list_mutex_type private
Protects my_asleep_list_root.
Definition at line 148 of file private_server.cpp.
Constructor & Destructor Documentation
tbb::internal::rml::private_server::~private_server () private virtual
Definition at line 343 of file private_server.cpp.
References __TBB_ASSERT, my_n_thread, my_thread_array, and tbb::internal::poison_pointer().
{
     __TBB_ASSERT( my_net_slack_requests==0, NULL );
     for( size_t i=my_n_thread; i--; )
         my_thread_array[i].~padded_private_worker();
     tbb::cache_aligned_allocator<padded_private_worker>().deallocate( my_thread_array, my_n_thread );
     tbb::internal::poison_pointer( my_thread_array );
 }
tbb::internal::rml::private_server::private_server (tbb_client & client)
Definition at line 323 of file private_server.cpp.
References my_asleep_list_root, my_n_thread, tbb::internal::rml::private_worker::my_next, my_ref_count, my_slack, and my_thread_array.
Referenced by tbb::internal::rml::make_private_server().
                                                    :
     my_client(client),
     my_n_thread(client.max_job_count()),
     my_stack_size(client.min_stack_size()),
     my_thread_array(NULL)
 {
     my_ref_count = my_n_thread+1;
     my_slack = 0;
 #if TBB_USE_ASSERT
     my_net_slack_requests = 0;
 #endif /* TBB_USE_ASSERT */
     my_asleep_list_root = NULL;
     my_thread_array = tbb::cache_aligned_allocator<padded_private_worker>().allocate( my_n_thread );
     for( size_t i=0; i<my_n_thread; ++i ) {
         private_worker* t = new( &my_thread_array[i] ) padded_private_worker( *this, client, i );
         t->my_next = my_asleep_list_root;
         my_asleep_list_root = t;
     }
 }
Member Function Documentation
void tbb::internal::rml::private_server::adjust_job_count_estimate (int delta)
Definition at line 403 of file private_server.cpp.
References my_slack, and wake_some().
{
 #if TBB_USE_ASSERT
     my_net_slack_requests+=delta;
 #endif /* TBB_USE_ASSERT */
     if( delta<0 ) {
         my_slack+=delta;
     } else if( delta>0 ) {
         wake_some( delta );
     }
 }
unsigned tbb::internal::rml::private_server::default_concurrency () const inline
Definition at line 198 of file private_server.cpp.
References __TBB_override, and tbb::internal::governor::default_num_threads().
 { return governor::default_num_threads() - 1; }
void tbb::internal::rml::private_server::independent_thread_number_changed (int) inline
Definition at line 196 of file private_server.cpp.
References __TBB_ASSERT.
 {__TBB_ASSERT(false,NULL);}
void tbb::internal::rml::private_server::propagate_chain_reaction () inline private
Wake up to two sleeping workers, if there are any sleeping.
The call is used to propagate a chain reaction where each thread wakes up two threads, which in turn each wake up two threads, etc.
Definition at line 158 of file private_server.cpp.
Referenced by tbb::internal::rml::private_worker::run().
{
         // First test of a double-check idiom.  Second test is inside wake_some(0).
         if( my_asleep_list_root )
             wake_some(0);
     }
void tbb::internal::rml::private_server::remove_server_ref () inline private
Definition at line 172 of file private_server.cpp.
Referenced by tbb::internal::rml::private_worker::run(), and tbb::internal::rml::private_worker::start_shutdown().
{
         if( --my_ref_count==0 ) {
             my_client.acknowledge_close_connection();
             this->~private_server();
             tbb::cache_aligned_allocator<private_server>().deallocate( this, 1 );
         }
     }
void tbb::internal::rml::private_server::request_close_connection (bool) inline
Definition at line 188 of file private_server.cpp.
References tbb::internal::rml::private_worker::start_shutdown().
{
         for( size_t i=0; i<my_n_thread; ++i )
             my_thread_array[i].start_shutdown();
         remove_server_ref();
     }
bool tbb::internal::rml::private_server::try_insert_in_asleep_list (private_worker & t) inline private
Try to add t to list of sleeping workers.
Definition at line 351 of file private_server.cpp.
References lock, my_asleep_list_mutex, my_asleep_list_root, tbb::internal::rml::private_worker::my_next, and my_slack.
Referenced by tbb::internal::rml::private_worker::run().
{
     asleep_list_mutex_type::scoped_lock lock;
     if( !lock.try_acquire(my_asleep_list_mutex) )
         return false;
     // Contribute to slack under lock so that if another takes that unit of slack,
     // it sees us sleeping on the list and wakes us up.
     int k = ++my_slack;
     if( k<=0 ) {
         t.my_next = my_asleep_list_root;
         my_asleep_list_root = &t;
         return true;
     } else {
         --my_slack;
         return false;
     }
 }
version_type tbb::internal::rml::private_server::version () const inline
Definition at line 184 of file private_server.cpp.
{
         return 0;
     }
void tbb::internal::rml::private_server::wake_some (int additional_slack) private
Equivalent of adding additional_slack to my_slack and waking up to 2 threads if my_slack permits.
Definition at line 368 of file private_server.cpp.
References __TBB_ASSERT, tbb::internal::atomic_impl< T >::compare_and_swap(), lock, my_asleep_list_mutex, my_asleep_list_root, tbb::internal::rml::private_worker::my_next, my_slack, and tbb::internal::rml::private_worker::wake_or_launch().
Referenced by adjust_job_count_estimate().
{
     __TBB_ASSERT( additional_slack>=0, NULL );
     private_worker* wakee[2];
     private_worker**w = wakee;
     {
         asleep_list_mutex_type::scoped_lock lock(my_asleep_list_mutex);
         while( my_asleep_list_root && w<wakee+2 ) {
             if( additional_slack>0 ) {
                 if (additional_slack+my_slack<=0) // additional demand does not exceed surplus supply
                     break;
                 --additional_slack;
             } else {
                 // Chain reaction; Try to claim unit of slack
                 int old;
                 do {
                     old = my_slack;
                     if( old<=0 ) goto done;
                 } while( my_slack.compare_and_swap(old-1,old)!=old );
             }
             // Pop sleeping worker to combine with claimed unit of slack
             my_asleep_list_root = (*w++ = my_asleep_list_root)->my_next;
         }
         if( additional_slack ) {
             // Contribute our unused slack to my_slack.
             my_slack += additional_slack;
         }
     }
 done:
     while( w>wakee ) {
         private_worker* ww = *--w;
         ww->my_next = NULL;
         ww->wake_or_launch();
     }
 }
void tbb::internal::rml::private_server::yield () inline
Definition at line 194 of file private_server.cpp.
References __TBB_Yield.
 {__TBB_Yield();}
Friends And Related Function Documentation
friend class private_worker friend
Definition at line 180 of file private_server.cpp.
Member Data Documentation
asleep_list_mutex_type tbb::internal::rml::private_server::my_asleep_list_mutex private
Definition at line 149 of file private_server.cpp.
Referenced by try_insert_in_asleep_list(), and wake_some().
tbb::atomic<private_worker*> tbb::internal::rml::private_server::my_asleep_list_root private
List of workers that are asleep or committed to sleeping until notified by another thread.
Definition at line 145 of file private_server.cpp.
Referenced by private_server(), try_insert_in_asleep_list(), and wake_some().
tbb_client& tbb::internal::rml::private_server::my_client private
Definition at line 124 of file private_server.cpp.
const tbb_client::size_type tbb::internal::rml::private_server::my_n_thread private
Maximum number of threads to be created.
Threads are created lazily, so maximum might not actually be reached.
Definition at line 127 of file private_server.cpp.
Referenced by private_server(), and ~private_server().
atomic<int> tbb::internal::rml::private_server::my_ref_count private
Counter used to determine when to delete this.
Definition at line 140 of file private_server.cpp.
Referenced by private_server().
atomic<int> tbb::internal::rml::private_server::my_slack private
Number of jobs that could use their associated thread minus number of active threads.
If negative, indicates oversubscription. If positive, indicates that more threads should run. Can be lowered asynchronously, but must be raised only while holding my_asleep_list_mutex, because raising it impacts the invariant for sleeping threads.
Definition at line 137 of file private_server.cpp.
Referenced by adjust_job_count_estimate(), private_server(), tbb::internal::rml::private_worker::run(), try_insert_in_asleep_list(), and wake_some().
const size_t tbb::internal::rml::private_server::my_stack_size private
Stack size for each thread. */.
Definition at line 130 of file private_server.cpp.
Referenced by tbb::internal::rml::private_worker::wake_or_launch().
padded_private_worker* tbb::internal::rml::private_server::my_thread_array private
Definition at line 142 of file private_server.cpp.
Referenced by private_server(), and ~private_server().
The documentation for this class was generated from the following file:
private_server.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.