Intel(R) Threading Building Blocks Doxygen Documentation: tbb::spin_rw_mutex_v3::scoped_lock Class Reference
tbb::spin_rw_mutex_v3::scoped_lock Class Reference
The scoped locking pattern.
#include <spin_rw_mutex.h>
Public Member Functions
scoped_lock ()
Construct lock that has not acquired a mutex.
scoped_lock (spin_rw_mutex &m, bool write=true)
Acquire lock on given mutex.
~scoped_lock ()
Release lock (if lock is held).
void acquire (spin_rw_mutex &m, bool write=true)
Acquire lock on given mutex.
bool upgrade_to_writer ()
Upgrade reader to become a writer.
void release ()
Release lock.
bool downgrade_to_reader ()
Downgrade writer to become a reader.
bool try_acquire (spin_rw_mutex &m, bool write=true)
Try acquire lock on given mutex.
Protected Attributes
spin_rw_mutex * mutex
The pointer to the current mutex that is held, or NULL if no mutex is held.
bool is_writer
If mutex!=NULL, then is_writer is true if holding a writer lock, false if holding a reader lock.
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
The scoped locking pattern.
It helps to avoid the common problem of forgetting to release lock. It also nicely provides the "node" for queuing locks.
Definition at line 90 of file spin_rw_mutex.h.
Constructor & Destructor Documentation
tbb::spin_rw_mutex_v3::scoped_lock::scoped_lock () inline
Construct lock that has not acquired a mutex.
Equivalent to zero-initialization of *this.
Definition at line 97 of file spin_rw_mutex.h.
 : mutex(NULL), is_writer(false) {}
tbb::spin_rw_mutex_v3::scoped_lock::scoped_lock (spin_rw_mutex & m, bool write = true) inline
Acquire lock on given mutex.
Definition at line 100 of file spin_rw_mutex.h.
References tbb::acquire.
                                                            : mutex(NULL) {
             acquire(m, write);
         }
tbb::spin_rw_mutex_v3::scoped_lock::~scoped_lock () inline
Release lock (if lock is held).
Definition at line 105 of file spin_rw_mutex.h.
References tbb::release.
{
             if( mutex ) release();
         }
Member Function Documentation
void tbb::spin_rw_mutex_v3::scoped_lock::acquire (spin_rw_mutex & m, bool write = true) inline
Acquire lock on given mutex.
Definition at line 110 of file spin_rw_mutex.h.
References __TBB_ASSERT.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::acquire().
{
             __TBB_ASSERT( !mutex, "holding mutex already" );
             is_writer = write;
             mutex = &m;
             if( write ) mutex->internal_acquire_writer();
             else        mutex->internal_acquire_reader();
         }
bool tbb::spin_rw_mutex_v3::scoped_lock::downgrade_to_reader () inline
Downgrade writer to become a reader.
Definition at line 142 of file spin_rw_mutex.h.
References __TBB_ASSERT.
{
             __TBB_ASSERT( mutex, "mutex is not acquired" );
             __TBB_ASSERT( is_writer, "not a writer" );
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
             mutex->internal_downgrade();
 #else
             __TBB_FetchAndAddW( &mutex->state, ((intptr_t)ONE_READER-WRITER));
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT */
             is_writer = false;
             return true;
         }
void tbb::spin_rw_mutex_v3::scoped_lock::release () inline
Release lock.
Definition at line 128 of file spin_rw_mutex.h.
References __TBB_ASSERT, __TBB_AtomicAND(), __TBB_FetchAndAddWrelease, tbb::spin_rw_mutex_v3::internal_release_reader(), tbb::spin_rw_mutex_v3::internal_release_writer(), and tbb::spin_rw_mutex_v3::state.
{
             __TBB_ASSERT( mutex, "mutex is not acquired" );
             spin_rw_mutex *m = mutex;
             mutex = NULL;
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
             if( is_writer ) m->internal_release_writer();
             else            m->internal_release_reader();
 #else
             if( is_writer ) __TBB_AtomicAND( &m->state, READERS );
             else            __TBB_FetchAndAddWrelease( &m->state, -(intptr_t)ONE_READER);
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT */
         }
bool tbb::spin_rw_mutex_v3::scoped_lock::try_acquire (spin_rw_mutex & m, bool write = true) inline
Try acquire lock on given mutex.
Definition at line 155 of file spin_rw_mutex.h.
References __TBB_ASSERT, tbb::spin_rw_mutex_v3::internal_try_acquire_reader(), and tbb::spin_rw_mutex_v3::internal_try_acquire_writer().
{
             __TBB_ASSERT( !mutex, "holding mutex already" );
             bool result;
             is_writer = write;
             result = write? m.internal_try_acquire_writer()
                           : m.internal_try_acquire_reader();
             if( result )
                 mutex = &m;
             return result;
         }
bool tbb::spin_rw_mutex_v3::scoped_lock::upgrade_to_writer () inline
Upgrade reader to become a writer.
Returns whether the upgrade happened without releasing and re-acquiring the lock
Definition at line 120 of file spin_rw_mutex.h.
References __TBB_ASSERT.
{
             __TBB_ASSERT( mutex, "mutex is not acquired" );
             __TBB_ASSERT( !is_writer, "not a reader" );
             is_writer = true;
             return mutex->internal_upgrade();
         }
Member Data Documentation
bool tbb::spin_rw_mutex_v3::scoped_lock::is_writer protected
If mutex!=NULL, then is_writer is true if holding a writer lock, false if holding a reader lock.
Not defined if not holding a lock.
Definition at line 173 of file spin_rw_mutex.h.
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::is_writer().
spin_rw_mutex* tbb::spin_rw_mutex_v3::scoped_lock::mutex protected
The pointer to the current mutex that is held, or NULL if no mutex is held.
Definition at line 169 of file spin_rw_mutex.h.
The documentation for this class was generated from the following file:
spin_rw_mutex.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.