Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::internal::round_robin_cache< T, M > Class Template Reference
tbb::flow::interface10::internal::round_robin_cache< T, M > Class Template Reference
A cache of successors that are put in a round-robin fashion.
#include <flow_graph.h>
Public Member Functions
round_robin_cache ()
size_type size ()
template<typename X >
task * try_put_task (const X &t)
Public Member Functions inherited from tbb::flow::interface10::internal::successor_cache< T, M >
successor_cache ()
void set_owner (owner_type *owner)
virtual ~successor_cache ()
void register_successor (successor_type &r)
void remove_successor (successor_type &r)
bool empty ()
void clear ()
Private Types
typedef size_t size_type
typedef M mutex_type
typedef successor_cache< T, M >::successors_type successors_type
Additional Inherited Members
Protected Types inherited from tbb::flow::interface10::internal::successor_cache< T, M >
typedef M mutex_type
typedef untyped_receiver successor_type
typedef untyped_receiver * pointer_type
typedef untyped_sender owner_type
typedef std::list< pointer_type > successors_type
Protected Attributes inherited from tbb::flow::interface10::internal::successor_cache< T, M >
mutex_type my_mutex
successors_type my_successors
owner_type * my_owner
Detailed Description
template<typename T, typename M = spin_rw_mutex>
class tbb::flow::interface10::internal::round_robin_cache< T, M >
A cache of successors that are put in a round-robin fashion.
Definition at line 109 of file flow_graph.h.
Member Typedef Documentation
template<typename T, typename M = spin_rw_mutex> typedef M tbb::flow::interface10::internal::round_robin_cache< T, M >::mutex_type private
Definition at line 519 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> typedef size_t tbb::flow::interface10::internal::round_robin_cache< T, M >::size_type private
Definition at line 518 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> typedef successor_cache<T,M>::successors_type tbb::flow::interface10::internal::round_robin_cache< T, M >::successors_type private
Definition at line 520 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T, typename M = spin_rw_mutex> tbb::flow::interface10::internal::round_robin_cache< T, M >::round_robin_cache () inline
Definition at line 524 of file flow_graph.h.
Member Function Documentation
template<typename T, typename M = spin_rw_mutex> size_type tbb::flow::interface10::internal::round_robin_cache< T, M >::size () inline
Definition at line 526 of file flow_graph.h.
          :
     template< typename R, typename B > friend class run_and_put_task;
template<typename T, typename M = spin_rw_mutex> template<typename X > task* tbb::flow::interface10::internal::round_robin_cache< T, M >::try_put_task (const X & t) inline
Definition at line 533 of file flow_graph.h.
Referenced by tbb::flow::interface10::queue_node< T, A >::try_put_and_add_task(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::try_put_and_add_task(), and tbb::flow::interface10a::overwrite_node< T >::try_put_task_impl().
       :
     // NOTE: Following part of PUBLIC and PROTECTED sections is copy-pasted in receiver<T> under #if __TBB_PREVIEW_ASYNC_MSG
     virtual bool register_predecessor( predecessor_type & ) { return false; }
     virtual bool remove_predecessor( predecessor_type & ) { return false; }
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
     typedef typename internal::edge_container<predecessor_type> built_predecessors_type;
     typedef typename built_predecessors_type::edge_list_type predecessor_list_type;
     virtual built_predecessors_type &built_predecessors()                  = 0;
     virtual void   internal_add_built_predecessor( predecessor_type & )    = 0;
     virtual void   internal_delete_built_predecessor( predecessor_type & ) = 0;
     virtual void   copy_predecessors( predecessor_list_type & )            = 0;
     virtual size_t predecessor_count()                                     = 0;
 #endif /* TBB_DEPRECATED_FLOW_NODE_EXTRACTION */
 protected:
     template<typename U> friend class limiter_node;
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.