Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::source_node< Output > Class Template Reference
tbb::flow::interface10::source_node< Output > Class Template Reference
An executable node that acts as a source, i.e. it has no predecessors.
#include <flow_graph.h>
Public Types
typedef Output output_type
The type of the output message, which is complete.
typedef sender< output_type >::successor_type successor_type
The type of successors of this node.
typedef null_type input_type
Public Types inherited from tbb::flow::interface10::sender< Output >
typedef Output output_type
The output type of this sender.
typedef internal::async_helpers< Output >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
template<typename Body >
source_node (graph &g, Body body, bool is_active=true)
Constructor for a node with a successor.
source_node (const source_node &src)
Copy constructor.
~source_node ()
The destructor.
bool register_successor (successor_type &r) __TBB_override
Add a new successor to this node.
bool remove_successor (successor_type &r) __TBB_override
Removes a successor from this node.
bool try_get (output_type &v) __TBB_override
Request an item from the node.
bool try_reserve (output_type &v) __TBB_override
Reserves an item.
bool try_release () __TBB_override
Release a reserved item.
bool try_consume () __TBB_override
Consumes a reserved item.
void activate ()
Activates a node that was created in the inactive state.
template<typename Body >
Body copy_function_object ()
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
Protected Member Functions
void reset_node (reset_flags f) __TBB_override
resets the source_node to its initial state
Protected Member Functions inherited from tbb::flow::interface10::sender< Output >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Private Member Functions
bool try_reserve_apply_body (output_type &v)
task * create_put_task ()
void spawn_put ()
Spawns a task that applies the body.
task * apply_body_bypass ()
Applies the body. Returning SUCCESSFULLY_ENQUEUED okay; forward_task_bypass will handle it.
Private Attributes
spin_mutex my_mutex
bool my_active
bool init_my_active
internal::source_body< output_type > * my_body
internal::source_body< output_type > * my_init_body
internal::broadcast_cache< output_type > my_successors
bool my_reserved
bool my_has_cached_item
output_type my_cached_item
Friends
class internal::source_task_bypass< source_node< output_type > >
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Detailed Description
template<typename Output>
class tbb::flow::interface10::source_node< Output >
An executable node that acts as a source, i.e. it has no predecessors.
Definition at line 865 of file flow_graph.h.
Member Typedef Documentation
template<typename Output > typedef null_type tbb::flow::interface10::source_node< Output >::input_type
Definition at line 874 of file flow_graph.h.
template<typename Output > typedef Output tbb::flow::interface10::source_node< Output >::output_type
The type of the output message, which is complete.
Definition at line 868 of file flow_graph.h.
template<typename Output > typedef sender<output_type>::successor_type tbb::flow::interface10::source_node< Output >::successor_type
The type of successors of this node.
Definition at line 871 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename Output > template<typename Body > tbb::flow::interface10::source_node< Output >::source_node (graph & g, Body body, bool is_active = true) inline
Constructor for a node with a successor.
Definition at line 883 of file flow_graph.h.
         : graph_node(g), my_active(is_active), init_my_active(is_active),
         my_body( new internal::source_body_leaf< output_type, Body>(body) ),
         my_init_body( new internal::source_body_leaf< output_type, Body>(body) ),
         my_reserved(false), my_has_cached_item(false)
     {
         my_successors.set_owner(this);
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_SOURCE_NODE, &this->my_graph,
                                            static_cast<sender<output_type> *>(this), this->my_body );
     }
template<typename Output > tbb::flow::interface10::source_node< Output >::source_node (const source_node< Output > & src) inline
Copy constructor.
Definition at line 895 of file flow_graph.h.
                                           :
         graph_node(src.my_graph), sender<Output>(),
         my_active(src.init_my_active),
         init_my_active(src.init_my_active), my_body( src.my_init_body->clone() ), my_init_body(src.my_init_body->clone() ),
         my_reserved(false), my_has_cached_item(false)
     {
         my_successors.set_owner(this);
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_SOURCE_NODE, &this->my_graph,
                                            static_cast<sender<output_type> *>(this), this->my_body );
     }
template<typename Output > tbb::flow::interface10::source_node< Output >::~source_node () inline
The destructor.
Definition at line 907 of file flow_graph.h.
 { delete my_body; delete my_init_body; }
Member Function Documentation
template<typename Output > void tbb::flow::interface10::source_node< Output >::activate () inline
Activates a node that was created in the inactive state.
Definition at line 1013 of file flow_graph.h.
                     {
         spin_mutex::scoped_lock lock(my_mutex);
         my_active = true;
         if (!my_successors.empty())
             spawn_put();
     }
template<typename Output > task* tbb::flow::interface10::source_node< Output >::apply_body_bypass () inline private
Applies the body. Returning SUCCESSFULLY_ENQUEUED okay; forward_task_bypass will handle it.
Definition at line 1106 of file flow_graph.h.
References tbb::flow::interface10::internal::broadcast_cache< T, M >::try_put_task().
{
         output_type v;
         if ( !try_reserve_apply_body(v) )
             return NULL;
         task *last_task = my_successors.try_put_task(v);
         if ( last_task )
             try_consume();
         else
             try_release();
         return last_task;
     }
template<typename Output > template<typename Body > Body tbb::flow::interface10::source_node< Output >::copy_function_object () inline
Definition at line 1021 of file flow_graph.h.
{
         internal::source_body<output_type> &body_ref = *this->my_body;
         return dynamic_cast< internal::source_body_leaf<output_type, Body> & >(body_ref).get_body();
     }
template<typename Output > task* tbb::flow::interface10::source_node< Output >::create_put_task () inline private
Definition at line 1092 of file flow_graph.h.
References tbb::flow::interface10::graph_node::my_graph, and tbb::flow::interface10::graph::root_task().
{
         return ( new ( task::allocate_additional_child_of( *(this->my_graph.root_task()) ) )
                         internal:: source_task_bypass < source_node< output_type > >( *this ) );
     }
template<typename Output > bool tbb::flow::interface10::source_node< Output >::register_successor (successor_type & r) inline virtual
Add a new successor to this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 916 of file flow_graph.h.
References lock.
{
         spin_mutex::scoped_lock lock(my_mutex);
         my_successors.register_successor(r);
         if ( my_active )
             spawn_put();
         return true;
     }
template<typename Output > bool tbb::flow::interface10::source_node< Output >::remove_successor (successor_type & r) inline virtual
Removes a successor from this node.
Implements tbb::flow::interface10::internal::untyped_sender.
Definition at line 925 of file flow_graph.h.
References lock.
{
         spin_mutex::scoped_lock lock(my_mutex);
         my_successors.remove_successor(r);
         return true;
     }
template<typename Output > void tbb::flow::interface10::source_node< Output >::reset_node (reset_flags f) inline protected virtual
resets the source_node to its initial state
Implements tbb::flow::interface10::graph_node.
Definition at line 1038 of file flow_graph.h.
References tbb::flow::interface10::rf_clear_edges.
{
         my_active = init_my_active;
         my_reserved =false;
         if(my_has_cached_item) {
             my_has_cached_item = false;
         }
         if(f & rf_clear_edges) my_successors.clear();
         if(f & rf_reset_bodies) {
             internal::source_body<output_type> *tmp = my_init_body->clone();
             delete my_body;
             my_body = tmp;
         }
         if(my_active)
             internal::add_task_to_graph_reset_list(this->my_graph, create_put_task());
     }
template<typename Output > void tbb::flow::interface10::source_node< Output >::spawn_put () inline private
Spawns a task that applies the body.
Definition at line 1098 of file flow_graph.h.
References tbb::flow::interface10::internal::is_graph_active(), tbb::flow::interface10::graph_node::my_graph, and tbb::flow::interface10::internal::spawn_in_graph_arena().
                       {
         if(internal::is_graph_active(this->my_graph)) {
             internal::spawn_in_graph_arena(this->my_graph, *create_put_task());
         }
     }
template<typename Output > bool tbb::flow::interface10::source_node< Output >::try_consume () inline virtual
Consumes a reserved item.
Reimplemented from tbb::flow::interface10::internal::untyped_sender.
Definition at line 1001 of file flow_graph.h.
References __TBB_ASSERT, and lock.
{
         spin_mutex::scoped_lock lock(my_mutex);
         __TBB_ASSERT( my_reserved && my_has_cached_item, "consuming non-existent reservation" );
         my_reserved = false;
         my_has_cached_item = false;
         if ( !my_successors.empty() ) {
             spawn_put();
         }
         return true;
     }
template<typename Output > bool tbb::flow::interface10::source_node< Output >::try_get (output_type & v) inline virtual
Request an item from the node.
Reimplemented from tbb::flow::interface10::sender< Output >.
Definition at line 957 of file flow_graph.h.
References lock.
{
         spin_mutex::scoped_lock lock(my_mutex);
         if ( my_reserved )
             return false;
         if ( my_has_cached_item ) {
             v = my_cached_item;
             my_has_cached_item = false;
             return true;
         }
         // we've been asked to provide an item, but we have none.  enqueue a task to
         // provide one.
         spawn_put();
         return false;
     }
template<typename Output > bool tbb::flow::interface10::source_node< Output >::try_release () inline virtual
Release a reserved item.
true = item has been released and so remains in sender, dest must request or reserve future items
Reimplemented from tbb::flow::interface10::internal::untyped_sender.
Definition at line 991 of file flow_graph.h.
{
         spin_mutex::scoped_lock lock(my_mutex);
         __TBB_ASSERT( my_reserved && my_has_cached_item, "releasing non-existent reservation" );
         my_reserved = false;
         if(!my_successors.empty())
             spawn_put();
         return true;
     }
template<typename Output > bool tbb::flow::interface10::source_node< Output >::try_reserve (output_type & v) inline virtual
Reserves an item.
Reimplemented from tbb::flow::interface10::sender< Output >.
Definition at line 974 of file flow_graph.h.
References lock.
{
         spin_mutex::scoped_lock lock(my_mutex);
         if ( my_reserved ) {
             return false;
         }
         if ( my_has_cached_item ) {
             v = my_cached_item;
             my_reserved = true;
             return true;
         } else {
             return false;
         }
     }
template<typename Output > bool tbb::flow::interface10::source_node< Output >::try_reserve_apply_body (output_type & v) inline private
Definition at line 1066 of file flow_graph.h.
References lock.
{
         spin_mutex::scoped_lock lock(my_mutex);
         if ( my_reserved ) {
             return false;
         }
         if ( !my_has_cached_item ) {
             tbb::internal::fgt_begin_body( my_body );
             bool r = (*my_body)(my_cached_item);
             tbb::internal::fgt_end_body( my_body );
             if (r) {
                 my_has_cached_item = true;
             }
         }
         if ( my_has_cached_item ) {
             v = my_cached_item;
             my_reserved = true;
             return true;
         } else {
             return false;
         }
     }
Friends And Related Function Documentation
template<typename Output > friend class internal::source_task_bypass< source_node< output_type > > friend
Definition at line 1104 of file flow_graph.h.
Member Data Documentation
template<typename Output > bool tbb::flow::interface10::source_node< Output >::init_my_active private
Definition at line 1057 of file flow_graph.h.
template<typename Output > bool tbb::flow::interface10::source_node< Output >::my_active private
Definition at line 1056 of file flow_graph.h.
template<typename Output > internal::source_body<output_type>* tbb::flow::interface10::source_node< Output >::my_body private
Definition at line 1058 of file flow_graph.h.
template<typename Output > output_type tbb::flow::interface10::source_node< Output >::my_cached_item private
Definition at line 1063 of file flow_graph.h.
template<typename Output > bool tbb::flow::interface10::source_node< Output >::my_has_cached_item private
Definition at line 1062 of file flow_graph.h.
template<typename Output > internal::source_body<output_type>* tbb::flow::interface10::source_node< Output >::my_init_body private
Definition at line 1059 of file flow_graph.h.
template<typename Output > spin_mutex tbb::flow::interface10::source_node< Output >::my_mutex private
Definition at line 1055 of file flow_graph.h.
template<typename Output > bool tbb::flow::interface10::source_node< Output >::my_reserved private
Definition at line 1061 of file flow_graph.h.
template<typename Output > internal::broadcast_cache< output_type > tbb::flow::interface10::source_node< Output >::my_successors private
Definition at line 1060 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.