Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::task_proxy Struct Reference
tbb::internal::task_proxy Struct Reference
#include <mailbox.h>
Public Member Functions
template<intptr_t from_bit>
task * extract_task ()
Returns a pointer to the encapsulated task or NULL, and frees proxy if necessary.
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
virtual task * execute ()=0
Should be overridden by derived classes.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
virtual void __TBB_EXPORTED_METHOD note_affinity (affinity_id id)
Invoked by scheduler to notify task that it ran on unexpected thread.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions
static bool is_shared (intptr_t tat)
True if the proxy is stored both in its sender's pool and in the destination mailbox.
static task * task_ptr (intptr_t tat)
Returns a pointer to the encapsulated task or NULL.
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Public Attributes
intptr_t task_and_tag
task_proxy *__TBB_atomic next_in_mailbox
Pointer to next task_proxy in a mailbox.
mail_outbox * outbox
Mailbox to which this was mailed.
Static Public Attributes
static const intptr_t pool_bit = 1<<0
static const intptr_t mailbox_bit = 1<<1
static const intptr_t location_mask = pool_bit | mailbox_bit
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
Definition at line 33 of file mailbox.h.
Member Function Documentation
template<intptr_t from_bit> task* tbb::internal::task_proxy::extract_task () inline
Returns a pointer to the encapsulated task or NULL, and frees proxy if necessary.
Definition at line 61 of file mailbox.h.
References __TBB_ASSERT, tbb::internal::__TBB_load_with_acquire(), tbb::internal::as_atomic(), tbb::internal::es_task_proxy, is_shared(), tbb::task::prefix(), and task_ptr().
Referenced by tbb::internal::generic_scheduler::get_task(), and tbb::internal::generic_scheduler::steal_task().
{
         __TBB_ASSERT( prefix().extra_state == es_task_proxy, "Normal task misinterpreted as a proxy?" );
         intptr_t tat = __TBB_load_with_acquire(task_and_tag);
         __TBB_ASSERT( tat == from_bit || (is_shared(tat) && task_ptr(tat)),
             "Proxy's tag cannot specify both locations if the proxy "
             "was retrieved from one of its original locations" );
         if ( tat != from_bit ) {
             const intptr_t cleaner_bit = location_mask & ~from_bit;
             // Attempt to transition the proxy to the "empty" state with
             // cleaner_bit specifying entity responsible for its eventual freeing.
             // Explicit cast to void* is to work around a seeming ICC 11.1 bug.
             if ( as_atomic(task_and_tag).compare_and_swap(cleaner_bit, tat) == tat ) {
                 // Successfully grabbed the task, and left new owner with the job of freeing the proxy
                 return task_ptr(tat);
             }
         }
         // Proxied task has already been claimed from another proxy location.
         __TBB_ASSERT( task_and_tag == from_bit, "Empty proxy cannot contain non-zero task pointer" );
         return NULL;
     }
static bool tbb::internal::task_proxy::is_shared (intptr_t tat) inline static
True if the proxy is stored both in its sender's pool and in the destination mailbox.
Definition at line 50 of file mailbox.h.
References location_mask.
Referenced by extract_task(), and tbb::internal::generic_scheduler::steal_task_from().
{
         return (tat & location_mask) == location_mask;
     }
static task* tbb::internal::task_proxy::task_ptr (intptr_t tat) inline static
Returns a pointer to the encapsulated task or NULL.
Definition at line 55 of file mailbox.h.
Referenced by extract_task().
{
         return (task*)(tat & ~location_mask);
     }
Member Data Documentation
const intptr_t tbb::internal::task_proxy::location_mask = pool_bit | mailbox_bit static
Definition at line 36 of file mailbox.h.
Referenced by is_shared(), and tbb::internal::generic_scheduler::prepare_for_spawning().
const intptr_t tbb::internal::task_proxy::mailbox_bit = 1<<1 static
Definition at line 35 of file mailbox.h.
Referenced by tbb::internal::generic_scheduler::get_mailbox_task().
task_proxy* __TBB_atomic tbb::internal::task_proxy::next_in_mailbox
Pointer to next task_proxy in a mailbox.
Definition at line 44 of file mailbox.h.
Referenced by tbb::internal::mail_outbox::drain(), tbb::internal::mail_outbox::internal_pop(), and tbb::internal::mail_outbox::push().
mail_outbox* tbb::internal::task_proxy::outbox
Mailbox to which this was mailed.
Definition at line 47 of file mailbox.h.
Referenced by tbb::internal::mail_inbox::is_idle_state(), tbb::internal::generic_scheduler::prepare_for_spawning(), and tbb::internal::generic_scheduler::steal_task_from().
const intptr_t tbb::internal::task_proxy::pool_bit = 1<<0 static
Definition at line 34 of file mailbox.h.
Referenced by tbb::internal::generic_scheduler::get_task(), and tbb::internal::generic_scheduler::steal_task().
intptr_t tbb::internal::task_proxy::task_and_tag
Definition at line 41 of file mailbox.h.
Referenced by tbb::internal::generic_scheduler::prepare_for_spawning(), and tbb::internal::generic_scheduler::steal_task_from().
The documentation for this struct was generated from the following file:
mailbox.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.