Intel(R) Threading Building Blocks Doxygen Documentation: tbb::spin_mutex Class Reference
tbb::spin_mutex Class Reference
Synchronization
A lock that occupies a single byte.
#include <spin_mutex.h>
Classes
class scoped_lock
Represents acquisition of a mutex.
Public Member Functions
spin_mutex ()
Construct unacquired lock.
void __TBB_EXPORTED_METHOD internal_construct ()
Internal constructor with ITT instrumentation.
void lock ()
Acquire lock.
bool try_lock ()
Try acquiring lock (non-blocking)
void unlock ()
Release lock.
Static Public Attributes
static const bool is_rw_mutex = false
static const bool is_recursive_mutex = false
static const bool is_fair_mutex = false
Private Attributes
__TBB_atomic_flag flag
0 if lock is released, 1 if lock is acquired.
Friends
class scoped_lock
Detailed Description
A lock that occupies a single byte.
A spin_mutex is a spin mutex that fits in a single byte. It should be used only for locking short critical sections (typically less than 20 instructions) when fairness is not an issue. If zero-initialized, the mutex is considered unheld.
Definition at line 40 of file spin_mutex.h.
Constructor & Destructor Documentation
tbb::spin_mutex::spin_mutex () inline
Construct unacquired lock.
Equivalent to zero-initialization of *this.
Definition at line 47 of file spin_mutex.h.
References internal_construct().
                  : flag(0) {
 #if TBB_USE_THREADING_TOOLS
         internal_construct();
 #endif
     }
Member Function Documentation
void tbb::spin_mutex::internal_construct ()
Internal constructor with ITT instrumentation.
Definition at line 54 of file spin_mutex.cpp.
References _T, and ITT_SYNC_CREATE.
Referenced by spin_mutex(), and tbb::spin_mutex::scoped_lock::~scoped_lock().
{
     ITT_SYNC_CREATE(this, _T("tbb::spin_mutex"), _T(""));
 }
void tbb::spin_mutex::lock () inline
Acquire lock.
Definition at line 148 of file spin_mutex.h.
References __TBB_LockByte(), tbb::aligned_space< T, N >::begin(), and tbb::spin_mutex::scoped_lock::scoped_lock().
                 {
 #if TBB_USE_THREADING_TOOLS
         aligned_space<scoped_lock> tmp;
         new(tmp.begin()) scoped_lock(*this);
 #else
         __TBB_LockByte(flag);
 #endif /* TBB_USE_THREADING_TOOLS*/
     }
bool tbb::spin_mutex::try_lock () inline
Try acquiring lock (non-blocking)
Return true if lock acquired; false otherwise.
Definition at line 159 of file spin_mutex.h.
References __TBB_TryLockByte(), and tbb::aligned_space< T, N >::begin().
                     {
 #if TBB_USE_THREADING_TOOLS
         aligned_space<scoped_lock> tmp;
         return (new(tmp.begin()) scoped_lock)->internal_try_acquire(*this);
 #else
         return __TBB_TryLockByte(flag);
 #endif /* TBB_USE_THREADING_TOOLS*/
     }
void tbb::spin_mutex::unlock () inline
Release lock.
Definition at line 169 of file spin_mutex.h.
References __TBB_UnlockByte, tbb::aligned_space< T, N >::begin(), tbb::spin_mutex::scoped_lock::internal_release(), tbb::spin_mutex::scoped_lock::my_mutex, and s.
                   {
 #if TBB_USE_THREADING_TOOLS
         aligned_space<scoped_lock> tmp;
         scoped_lock& s = *tmp.begin();
         s.my_mutex = this;
         s.internal_release();
 #else
         __TBB_UnlockByte(flag);
 #endif /* TBB_USE_THREADING_TOOLS */
     }
Friends And Related Function Documentation
friend class scoped_lock friend
Definition at line 180 of file spin_mutex.h.
Member Data Documentation
__TBB_atomic_flag tbb::spin_mutex::flag private
0 if lock is released, 1 if lock is acquired.
Definition at line 42 of file spin_mutex.h.
Referenced by tbb::spin_mutex::scoped_lock::acquire(), tbb::spin_mutex::scoped_lock::internal_acquire(), tbb::spin_mutex::scoped_lock::internal_release(), tbb::spin_mutex::scoped_lock::internal_try_acquire(), tbb::spin_mutex::scoped_lock::release(), tbb::spin_mutex::scoped_lock::scoped_lock(), tbb::spin_mutex::scoped_lock::try_acquire(), and tbb::spin_mutex::scoped_lock::~scoped_lock().
const bool tbb::spin_mutex::is_fair_mutex = false static
Definition at line 143 of file spin_mutex.h.
const bool tbb::spin_mutex::is_recursive_mutex = false static
Definition at line 142 of file spin_mutex.h.
const bool tbb::spin_mutex::is_rw_mutex = false static
Definition at line 141 of file spin_mutex.h.
The documentation for this class was generated from the following files:
spin_mutex.h
spin_mutex.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.