Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner > Class Template Reference
tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner > Class Template Reference
Algorithms
Task type used to split the work of parallel_deterministic_reduce.
#include <parallel_reduce.h>
Public Member Functions
void offer_work (typename Partitioner::split_type &split_obj)
void run_body (Range &r)
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
virtual void __TBB_EXPORTED_METHOD note_affinity (affinity_id id)
Invoked by scheduler to notify task that it ran on unexpected thread.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions
static void run (const Range &range, Body &body, Partitioner &partitioner)
static void run (const Range &range, Body &body, Partitioner &partitioner, task_group_context &context)
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Private Types
typedef finish_deterministic_reduce< Body > finish_type
Private Member Functions
task * execute () __TBB_override
Should be overridden by derived classes.
start_deterministic_reduce (const Range &range, Body &body, Partitioner &partitioner)
Constructor used for root task.
start_deterministic_reduce (start_deterministic_reduce &parent_, finish_type &c, typename Partitioner::split_type &split_obj)
Splitting constructor used to generate children.
Private Attributes
Body & my_body
Range my_range
Partitioner::task_partition_type my_partition
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
template<typename Range, typename Body, typename Partitioner>
class tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >
Task type used to split the work of parallel_deterministic_reduce.
Definition at line 223 of file parallel_reduce.h.
Member Typedef Documentation
template<typename Range , typename Body , typename Partitioner > typedef finish_deterministic_reduce<Body> tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::finish_type private
Definition at line 224 of file parallel_reduce.h.
Constructor & Destructor Documentation
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::start_deterministic_reduce (const Range & range, Body & body, Partitioner & partitioner) inline private
Constructor used for root task.
Definition at line 231 of file parallel_reduce.h.
                                                                                                :
             my_body( body ),
             my_range( range ),
             my_partition( partitioner )
         {
         }
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::start_deterministic_reduce (start_deterministic_reduce< Range, Body, Partitioner > & parent_, finish_type & c, typename Partitioner::split_type & split_obj) inline private
Splitting constructor used to generate children.
parent_ becomes left child. Newly constructed object is right child.
Definition at line 239 of file parallel_reduce.h.
                                                                                                                                      :
             my_body( c.my_right_body ),
             my_range( parent_.my_range, split_obj ),
             my_partition( parent_.my_partition, split_obj )
         {
         }
Member Function Documentation
template<typename Range , typename Body , typename Partitioner > task * tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::execute () private virtual
Should be overridden by derived classes.
Implements tbb::task.
Definition at line 278 of file parallel_reduce.h.
References tbb::task::execute().
{
         my_partition.execute(*this, my_range);
         return NULL;
     }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::offer_work (typename Partitioner::split_type & split_obj) inline
Definition at line 266 of file parallel_reduce.h.
References tbb::interface9::internal::allocate_sibling().
{
             task* tasks[2];
             allocate_sibling(static_cast<task*>(this), tasks, sizeof(start_deterministic_reduce), sizeof(finish_type));
             new((void*)tasks[0]) finish_type(my_body);
             new((void*)tasks[1]) start_deterministic_reduce(*this, *static_cast<finish_type*>(tasks[0]), split_obj);
             spawn(*tasks[1]);
         }
template<typename Range , typename Body , typename Partitioner > static void tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run (const Range & range, Body & body, Partitioner & partitioner) inline static
Definition at line 247 of file parallel_reduce.h.
References tbb::task::allocate_root(), and tbb::task::spawn_root_and_wait().
Referenced by tbb::parallel_deterministic_reduce().
{
             if( !range.empty() ) {
 #if !__TBB_TASK_GROUP_CONTEXT || TBB_JOIN_OUTER_TASK_GROUP
                 task::spawn_root_and_wait( *new(task::allocate_root()) start_deterministic_reduce(range,&body,partitioner) );
 #else
                 // Bound context prevents exceptions from body to affect nesting or sibling algorithms,
                 // and allows users to handle exceptions safely by wrapping parallel_for in the try-block.
                 task_group_context context(PARALLEL_REDUCE);
                 task::spawn_root_and_wait( *new(task::allocate_root(context)) start_deterministic_reduce(range,body,partitioner) );
 #endif /* __TBB_TASK_GROUP_CONTEXT && !TBB_JOIN_OUTER_TASK_GROUP */
             }
         }
template<typename Range , typename Body , typename Partitioner > static void tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run (const Range & range, Body & body, Partitioner & partitioner, task_group_context & context) inline static
Definition at line 260 of file parallel_reduce.h.
References tbb::task::allocate_root(), and tbb::task::spawn_root_and_wait().
{
             if( !range.empty() )
                 task::spawn_root_and_wait( *new(task::allocate_root(context)) start_deterministic_reduce(range,body,partitioner) );
         }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run_body (Range & r) inline
Definition at line 274 of file parallel_reduce.h.
 { my_body(r); }
Member Data Documentation
template<typename Range , typename Body , typename Partitioner > Body& tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::my_body private
Definition at line 225 of file parallel_reduce.h.
template<typename Range , typename Body , typename Partitioner > Partitioner::task_partition_type tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::my_partition private
Definition at line 227 of file parallel_reduce.h.
template<typename Range , typename Body , typename Partitioner > Range tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::my_range private
Definition at line 226 of file parallel_reduce.h.
The documentation for this class was generated from the following file:
parallel_reduce.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.