Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::task_scheduler_observer_v3 Class Reference
tbb::internal::task_scheduler_observer_v3 Class Reference
#include <task_scheduler_observer.h>
Public Member Functions
void __TBB_EXPORTED_METHOD observe (bool state=true)
Enable or disable observation.
bool is_observing () const
Returns true if observation is enabled, false otherwise.
task_scheduler_observer_v3 ()
Construct observer with observation disabled.
virtual void on_scheduler_entry (bool)
Entry notification.
virtual void on_scheduler_exit (bool)
Exit notification.
virtual ~task_scheduler_observer_v3 ()
Destructor automatically switches observation off if it is enabled.
Private Attributes
observer_proxy * my_proxy
Pointer to the proxy holding this observer.
atomic< intptr_t > my_busy_count
Counter preventing the observer from being destroyed while in use by the scheduler.
Friends
class observer_proxy
class observer_list
class interface6::task_scheduler_observer
Detailed Description
Definition at line 40 of file task_scheduler_observer.h.
Constructor & Destructor Documentation
tbb::internal::task_scheduler_observer_v3::task_scheduler_observer_v3 () inline
Construct observer with observation disabled.
Definition at line 65 of file task_scheduler_observer.h.
References tbb::relaxed, and tbb::internal::atomic_impl< T >::store().
 : my_proxy(NULL) { my_busy_count.store<relaxed>(0); }
virtual tbb::internal::task_scheduler_observer_v3::~task_scheduler_observer_v3 () inline virtual
Destructor automatically switches observation off if it is enabled.
Definition at line 86 of file task_scheduler_observer.h.
References __TBB_ASSERT, __TBB_ASSERT_EX, my_busy_count, my_proxy, observe(), tbb::relaxed, and tbb::internal::atomic_impl< T >::store().
 { if(my_proxy) observe(false);}
Member Function Documentation
bool tbb::internal::task_scheduler_observer_v3::is_observing () const inline
Returns true if observation is enabled, false otherwise.
Definition at line 62 of file task_scheduler_observer.h.
 {return my_proxy!=NULL;}
void __TBB_EXPORTED_METHOD tbb::internal::task_scheduler_observer_v3::observe (bool state = true)
Enable or disable observation.
For local observers the method can be used only when the current thread has the task scheduler initialized or is attached to an arena.
Repeated calls with the same state are no-ops.
Referenced by ~task_scheduler_observer_v3().
virtual void tbb::internal::task_scheduler_observer_v3::on_scheduler_entry (bool) inline virtual
Entry notification.
Invoked from inside observe(true) call and whenever a worker enters the arena this observer is associated with. If a thread is already in the arena when the observer is activated, the entry notification is called before it executes the first stolen task.
Obsolete semantics. For global observers it is called by a thread before the first steal since observation became enabled.
Definition at line 75 of file task_scheduler_observer.h.
 {}
virtual void tbb::internal::task_scheduler_observer_v3::on_scheduler_exit (bool) inline virtual
Exit notification.
Invoked from inside observe(false) call and whenever a worker leaves the arena this observer is associated with.
Obsolete semantics. For global observers it is called by a thread before the first steal since observation became enabled.
Definition at line 83 of file task_scheduler_observer.h.
 {}
Friends And Related Function Documentation
friend class interface6::task_scheduler_observer friend
Definition at line 43 of file task_scheduler_observer.h.
friend class observer_list friend
Definition at line 42 of file task_scheduler_observer.h.
friend class observer_proxy friend
Definition at line 41 of file task_scheduler_observer.h.
Member Data Documentation
atomic<intptr_t> tbb::internal::task_scheduler_observer_v3::my_busy_count private
Counter preventing the observer from being destroyed while in use by the scheduler.
Valid only when observation is on.
Definition at line 51 of file task_scheduler_observer.h.
Referenced by ~task_scheduler_observer_v3().
observer_proxy* tbb::internal::task_scheduler_observer_v3::my_proxy private
Pointer to the proxy holding this observer.
Observers are proxied by the scheduler to maintain persistent lists of them.
Definition at line 47 of file task_scheduler_observer.h.
Referenced by ~task_scheduler_observer_v3().
The documentation for this class was generated from the following file:
task_scheduler_observer.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.