Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::stored_pack< T, Types... > Struct Template Reference
tbb::internal::stored_pack< T, Types... > Struct Template Reference
#include <_template_helpers.h>
Public Types
typedef stored_pack< T, Types... > pack_type
typedef stored_pack< Types... > pack_remainder
Public Member Functions
stored_pack (T &&t, Types &&...types)
Public Attributes
strip< T >::type leftmost_value
Static Protected Member Functions
template<typename Ret , typename F , typename... Preceding>
static Ret call (F &&f, pack_type &pack, Preceding &&...params)
template<typename Ret , typename F , typename... Preceding>
static Ret call (F &&f, const pack_type &pack, Preceding &&...params)
template<typename Ret , typename F , typename... Preceding>
static Ret call (F &&f, pack_type &&pack, Preceding &&...params)
Friends
template<typename F , typename Pack >
void call (F &&f, Pack &&p)
Calls the given function with arguments taken from a stored_pack.
template<typename Ret , typename F , typename Pack >
Ret call_and_return (F &&f, Pack &&p)
Detailed Description
template<typename T, typename... Types>
struct tbb::internal::stored_pack< T, Types... >
Definition at line 119 of file _template_helpers.h.
Member Typedef Documentation
template<typename T , typename... Types> typedef stored_pack<Types...> tbb::internal::stored_pack< T, Types... >::pack_remainder
Definition at line 122 of file _template_helpers.h.
template<typename T , typename... Types> typedef stored_pack<T, Types...> tbb::internal::stored_pack< T, Types... >::pack_type
Definition at line 121 of file _template_helpers.h.
Constructor & Destructor Documentation
template<typename T , typename... Types> tbb::internal::stored_pack< T, Types... >::stored_pack (T && t, Types &&... types) inline
Definition at line 129 of file _template_helpers.h.
References tbb::internal::call(), tbb::internal::call_and_return(), and p.
     : pack_remainder(std::forward<Types>(types)...), leftmost_value(std::forward<T>(t)) {}
Member Function Documentation
template<typename T , typename... Types> template<typename Ret , typename F , typename... Preceding> static Ret tbb::internal::stored_pack< T, Types... >::call (F && f, pack_type & pack, Preceding &&... params) inline static protected
Definition at line 138 of file _template_helpers.h.
References leftmost_value.
{
         return pack_remainder::template call<Ret>(
             std::forward<F>(f), static_cast<pack_remainder&>(pack),
             std::forward<Preceding>(params)... , pack.leftmost_value
         );
     }
template<typename T , typename... Types> template<typename Ret , typename F , typename... Preceding> static Ret tbb::internal::stored_pack< T, Types... >::call (F && f, const pack_type & pack, Preceding &&... params) inline static protected
Definition at line 145 of file _template_helpers.h.
References leftmost_value.
{
         return pack_remainder::template call<Ret>(
             std::forward<F>(f), static_cast<const pack_remainder&>(pack),
             std::forward<Preceding>(params)... , pack.leftmost_value
         );
     }
template<typename T , typename... Types> template<typename Ret , typename F , typename... Preceding> static Ret tbb::internal::stored_pack< T, Types... >::call (F && f, pack_type && pack, Preceding &&... params) inline static protected
Definition at line 152 of file _template_helpers.h.
References tbb::move().
{
         return pack_remainder::template call<Ret>(
             std::forward<F>(f), static_cast<pack_remainder&&>(pack),
             std::forward<Preceding>(params)... , std::move(pack.leftmost_value)
         );
     }
Friends And Related Function Documentation
template<typename T , typename... Types> template<typename F , typename Pack > void call (F && f, Pack && p) friend
Calls the given function with arguments taken from a stored_pack.
Definition at line 162 of file _template_helpers.h.
{
     strip<Pack>::type::template call<void>( std::forward<F>(f), std::forward<Pack>(p) );
 }
template<typename T , typename... Types> template<typename Ret , typename F , typename Pack > Ret call_and_return (F && f, Pack && p) friend
Definition at line 167 of file _template_helpers.h.
{
     return strip<Pack>::type::template call<Ret>( std::forward<F>(f), std::forward<Pack>(p) );
 }
Member Data Documentation
template<typename T , typename... Types> strip<T>::type tbb::internal::stored_pack< T, Types... >::leftmost_value
Definition at line 125 of file _template_helpers.h.
Referenced by call().
The documentation for this struct was generated from the following file:
_template_helpers.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.