Intel(R) Threading Building Blocks Doxygen Documentation: tbb::tbb_allocator< T > Class Template Reference
tbb::tbb_allocator< T > Class Template Reference
Memory Allocation
Meets "allocator" requirements of ISO C++ Standard, Section 20.1.5.
#include <tbb_allocator.h>
Classes
struct rebind
Public Types
enum malloc_type { scalable, standard }
Specifies current allocator.
typedef internal::allocator_type< T >::value_type value_type
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef size_t size_type
typedef ptrdiff_t difference_type
Public Member Functions
tbb_allocator () throw ()
tbb_allocator (const tbb_allocator &) throw ()
template<typename U >
tbb_allocator (const tbb_allocator< U > &) throw ()
pointer address (reference x) const
const_pointer address (const_reference x) const
pointer allocate (size_type n, const void *=0)
Allocate space for n objects.
void deallocate (pointer p, size_type)
Free previously allocated block of memory.
size_type max_size () const throw ()
Largest value for which method allocate might succeed.
template<typename U , typename... Args>
void construct (U *p, Args &&...args)
Copy-construct value at location pointed to by p.
void destroy (pointer p)
Destroy value at location pointed to by p.
Static Public Member Functions
static malloc_type allocator_type ()
Returns current allocator.
Detailed Description
template<typename T>
class tbb::tbb_allocator< T >
Meets "allocator" requirements of ISO C++ Standard, Section 20.1.5.
The class selects the best memory allocation mechanism available from scalable_malloc and standard malloc. The members are ordered the same way they are in section 20.4.1 of the ISO C++ standard.
Definition at line 62 of file tbb_allocator.h.
Member Typedef Documentation
template<typename T> typedef const value_type* tbb::tbb_allocator< T >::const_pointer
Definition at line 66 of file tbb_allocator.h.
template<typename T> typedef const value_type& tbb::tbb_allocator< T >::const_reference
Definition at line 68 of file tbb_allocator.h.
template<typename T> typedef ptrdiff_t tbb::tbb_allocator< T >::difference_type
Definition at line 70 of file tbb_allocator.h.
template<typename T> typedef value_type* tbb::tbb_allocator< T >::pointer
Definition at line 65 of file tbb_allocator.h.
template<typename T> typedef value_type& tbb::tbb_allocator< T >::reference
Definition at line 67 of file tbb_allocator.h.
template<typename T> typedef size_t tbb::tbb_allocator< T >::size_type
Definition at line 69 of file tbb_allocator.h.
template<typename T> typedef internal::allocator_type<T>::value_type tbb::tbb_allocator< T >::value_type
Definition at line 64 of file tbb_allocator.h.
Member Enumeration Documentation
template<typename T> enum tbb::tbb_allocator::malloc_type
Specifies current allocator.
Enumerator
scalable
standard
Definition at line 76 of file tbb_allocator.h.
                      {
         scalable,
         standard
     };
Constructor & Destructor Documentation
template<typename T> tbb::tbb_allocator< T >::tbb_allocator () throw () inline
Definition at line 81 of file tbb_allocator.h.
 {}
template<typename T> tbb::tbb_allocator< T >::tbb_allocator (const tbb_allocator< T > &) throw () inline
Definition at line 82 of file tbb_allocator.h.
 {}
template<typename T> template<typename U > tbb::tbb_allocator< T >::tbb_allocator (const tbb_allocator< U > &) throw () inline
Definition at line 83 of file tbb_allocator.h.
 {}
Member Function Documentation
template<typename T> pointer tbb::tbb_allocator< T >::address (reference x) const inline
Definition at line 85 of file tbb_allocator.h.
 {return &x;}
template<typename T> const_pointer tbb::tbb_allocator< T >::address (const_reference x) const inline
Definition at line 86 of file tbb_allocator.h.
 {return &x;}
template<typename T> pointer tbb::tbb_allocator< T >::allocate (size_type n, const void * = 0) inline
Allocate space for n objects.
Definition at line 89 of file tbb_allocator.h.
References tbb::internal::allocate_via_handler_v3().
{
         return pointer(internal::allocate_via_handler_v3( n * sizeof(value_type) ));
     }
template<typename T> static malloc_type tbb::tbb_allocator< T >::allocator_type () inline static
Returns current allocator.
Definition at line 120 of file tbb_allocator.h.
References tbb::internal::is_malloc_used_v3().
{
         return internal::is_malloc_used_v3() ? standard : scalable;
     }
template<typename T> template<typename U , typename... Args> void tbb::tbb_allocator< T >::construct (U * p, Args &&... args) inline
Copy-construct value at location pointed to by p.
Definition at line 107 of file tbb_allocator.h.
References tbb::move(), p, and value.
         { ::new((void *)p) U(std::forward<Args>(args)...); }
template<typename T> void tbb::tbb_allocator< T >::deallocate (pointer p, size_type) inline
Free previously allocated block of memory.
Definition at line 94 of file tbb_allocator.h.
References tbb::internal::deallocate_via_handler_v3().
{
         internal::deallocate_via_handler_v3(p);
     }
template<typename T> void tbb::tbb_allocator< T >::destroy (pointer p) inline
Destroy value at location pointed to by p.
Definition at line 117 of file tbb_allocator.h.
 {p->~value_type();}
template<typename T> size_type tbb::tbb_allocator< T >::max_size () const throw () inline
Largest value for which method allocate might succeed.
Definition at line 99 of file tbb_allocator.h.
References tbb::internal::max().
{
         size_type max = static_cast<size_type>(-1) / sizeof (value_type);
         return (max > 0 ? max : 1);
     }
The documentation for this class was generated from the following file:
tbb_allocator.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.