Intel(R) Threading Building Blocks Doxygen Documentation: tbb::task Class Reference
tbb::task Class Reference abstract
Task Scheduling
Base class for user-defined tasks.
#include <task.h>
Public Types
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Public Member Functions
virtual ~task ()
Destructor.
virtual task * execute ()=0
Should be overridden by derived classes.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
virtual void __TBB_EXPORTED_METHOD note_affinity (affinity_id id)
Invoked by scheduler to notify task that it ran on unexpected thread.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Protected Member Functions
task ()
Default constructor.
Private Member Functions
void __TBB_EXPORTED_METHOD internal_set_ref_count (int count)
Set reference count.
internal::reference_count __TBB_EXPORTED_METHOD internal_decrement_ref_count ()
Decrement reference count and return its new value.
internal::task_prefix & prefix (internal::version_tag *=NULL) const
Get reference to corresponding task_prefix.
Friends
class interface5::internal::task_base
class task_list
class internal::scheduler
class internal::allocate_root_proxy
class internal::allocate_root_with_context_proxy
class internal::allocate_continuation_proxy
class internal::allocate_child_proxy
class internal::allocate_additional_child_of_proxy
void internal::make_critical (task &)
bool internal::is_critical (task &)
Detailed Description
Base class for user-defined tasks.
Definition at line 592 of file task.h.
Member Typedef Documentation
typedef internal::affinity_id tbb::task::affinity_id
An id as used for specifying affinity.
Guaranteed to be integral type. Value of 0 means no affinity.
Definition at line 879 of file task.h.
Member Enumeration Documentation
enum tbb::task::state_type
Enumeration of task states that the scheduler considers.
Enumerator
executing
task is running, and will be destroyed after method execute() completes.
reexecute
task to be rescheduled.
ready
task is in ready pool, or is going to be put there, or was just taken off.
allocated
task object is freshly allocated or recycled.
freed
task object is on free list, or is going to be put there, or was just taken off.
recycle
task to be recycled as continuation
Definition at line 612 of file task.h.
                     {
         executing,
         reexecute,
         ready,
         allocated,
         freed,
         recycle
 #if __TBB_RECYCLE_TO_ENQUEUE
         ,to_enqueue
 #endif
     };
Constructor & Destructor Documentation
tbb::task::task () inline protected
Default constructor.
Definition at line 602 of file task.h.
 {prefix().extra_state=1;}
virtual tbb::task::~task () inline virtual
Destructor.
Definition at line 606 of file task.h.
Referenced by tbb::interface5::internal::task_base::destroy().
 {}
Member Function Documentation
int tbb::task::add_ref_count (int count) inline
Atomically adds to reference count and returns its new value.
Has release-acquire semantics
Definition at line 750 of file task.h.
References __TBB_ASSERT, tbb::internal::acquired, tbb::internal::call_itt_notify(), int, and tbb::internal::releasing.
{
         internal::call_itt_notify( internal::releasing, &prefix().ref_count );
         internal::reference_count k = count+__TBB_FetchAndAddW( &prefix().ref_count, count );
         __TBB_ASSERT( k>=0, "task's reference count underflowed" );
         if( k==0 )
             internal::call_itt_notify( internal::acquired, &prefix().ref_count );
         return int(k);
     }
affinity_id tbb::task::affinity () const inline
Current affinity of this task.
Definition at line 885 of file task.h.
References __TBB_EXPORTED_METHOD.
 {return prefix().affinity;}
internal::allocate_child_proxy& tbb::task::allocate_child () inline
Returns proxy for overloaded new that allocates a child task of *this.
Definition at line 654 of file task.h.
References __TBB_EXPORTED_METHOD.
Referenced by tbb::interface9::internal::allocate_sibling(), tbb::internal::while_group_task< Body >::execute(), and tbb::interface9::internal::do_task_iter< Iterator, Body, Item >::run_for_random_access_iterator().
{
         return *reinterpret_cast<internal::allocate_child_proxy*>(this);
     }
internal::allocate_continuation_proxy& tbb::task::allocate_continuation () inline
Returns proxy for overloaded new that allocates a continuation task of *this.
The continuation's parent becomes the parent of *this.
Definition at line 649 of file task.h.
Referenced by tbb::interface9::internal::allocate_sibling(), and tbb::flow::interface10::internal::spawn_in_graph_arena().
{
         return *reinterpret_cast<internal::allocate_continuation_proxy*>(this);
     }
static internal::allocate_root_proxy tbb::task::allocate_root () inline static
Returns proxy for overloaded new that allocates a root task.
Definition at line 636 of file task.h.
Referenced by tbb::interface7::task_arena::enqueue_impl(), tbb::internal::start_scan< Range, Body, Partitioner >::execute(), tbb::interface7::internal::task_arena_base::internal_execute(), tbb::interface7::internal::task_arena_base::internal_wait(), tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::parallel_do_feeder_impl(), tbb::interface9::internal::start_for< Range, Body, Partitioner >::run(), tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run(), tbb::parallel_while< Body >::run(), tbb::internal::start_scan< Range, Body, Partitioner >::run(), tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run(), tbb::pipeline::run(), tbb::internal::task_group_base::task_group_base(), and tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task().
{
         return internal::allocate_root_proxy();
     }
static internal::allocate_root_with_context_proxy tbb::task::allocate_root (task_group_context & ctx) inline static
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
Definition at line 642 of file task.h.
{
         return internal::allocate_root_with_context_proxy(ctx);
     }
bool tbb::task::cancel_group_execution () inline
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
Returns
false if cancellation has already been requested, true otherwise.
Definition at line 910 of file task.h.
Referenced by tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >::operator()().
 { return prefix().context->cancel_group_execution(); }
void __TBB_EXPORTED_METHOD tbb::task::change_group (task_group_context & ctx)
Moves this task from its current group into another one.
Argument ctx specifies the new group.
The primary purpose of this method is to associate unique task group context with a task allocated for subsequent enqueuing. In contrast to spawned tasks enqueued ones normally outlive the scope where they were created. This makes traditional usage model where task group context are allocated locally on the stack inapplicable. Dynamic allocation of context objects is performance inefficient. Method change_group() allows to make task group context object a member of the task class, and then associate it with its containing task object in the latter's constructor.
Referenced by note_affinity().
task_group_context* tbb::task::context () inline
This method is deprecated and will be removed in the future.
Use method group() instead.
Definition at line 843 of file task.h.
Referenced by tbb::strict_ppl::parallel_for(), tbb::internal::generic_scheduler::prepare_for_spawning(), recycle_as_child_of(), and tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
 {return prefix().context;}
int tbb::task::decrement_ref_count () inline
Atomically decrement reference count and returns its new value.
Has release semantics.
Definition at line 761 of file task.h.
References __TBB_FetchAndDecrementWrelease, and int.
Referenced by tbb::internal::task_group_base::ref_count_guard::~ref_count_guard().
{
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
         return int(internal_decrement_ref_count());
 #else
         return int(__TBB_FetchAndDecrementWrelease( &prefix().ref_count ))-1;
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT */
     }
static void tbb::task::enqueue (task & t) inline static
Enqueue task for starvation-resistant execution.
The task will be enqueued on the normal priority level disregarding the priority of its task group.
The rationale of such semantics is that priority of an enqueued task is statically fixed at the moment of its enqueuing, while task group priority is dynamic. Thus automatic priority inheritance would be generally a subject to the race, which may result in unexpected behavior.
Use enqueue() overload with explicit priority value and task::group_priority() method to implement such priority inheritance when it is really necessary.
Definition at line 809 of file task.h.
References __TBB_ASSERT, __TBB_EXPORTED_FUNC, p, prefix(), tbb::internal::priority_critical, tbb::priority_high, tbb::priority_low, and tbb::priority_normal.
{
         t.prefix().owner->enqueue( t, NULL );
     }
static void tbb::task::enqueue (task & t, priority_t p) inline static
Enqueue task for starvation-resistant execution on the specified priority level.
Definition at line 815 of file task.h.
{
 #if __TBB_PREVIEW_CRITICAL_TASKS
         __TBB_ASSERT(p == priority_low || p == priority_normal || p == priority_high
                      || p == internal::priority_critical, "Invalid priority level value");
 #else
         __TBB_ASSERT(p == priority_low || p == priority_normal || p == priority_high, "Invalid priority level value");
 #endif
         t.prefix().owner->enqueue( t, (void*)p );
     }
virtual task* tbb::task::execute () pure virtual
Should be overridden by derived classes.
Implemented in tbb::flow::interface10a::overwrite_node< T >::register_predecessor_task, tbb::internal::function_task< F >, tbb::interface7::internal::wait_task, tbb::empty_task, tbb::interface7::internal::delegated_task, tbb::internal::pipeline_root_task, tbb::flow::interface10::internal::source_task_bypass< NodeType >, tbb::interface9::internal::do_task_iter< Iterator, Body, Item >, tbb::flow::interface10::internal::apply_body_task_bypass< NodeType, Input >, tbb::flow::interface10::internal::forward_task_bypass< NodeType >, tbb::internal::stage_task, tbb::interface9::internal::do_group_task_input< Body, Item >, tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >, tbb::interface9::internal::do_group_task_forward< Iterator, Body, Item >, tbb::flow::interface10::graph::run_and_put_task< Receiver, Body >, tbb::flow::interface10::graph::run_task< Body >, tbb::interface9::internal::finish_deterministic_reduce< Body >, tbb::internal::start_scan< Range, Body, Partitioner >, tbb::flow::interface10::internal::priority_task_selector, tbb::internal::finish_scan< Range, Body >, tbb::interface9::internal::do_iteration_task_iter< Iterator, Body, Item >, tbb::interface9::internal::flag_task, tbb::internal::sum_node< Range, Body >, tbb::interface9::internal::do_iteration_task< Body, Item >, tbb::interface9::internal::start_reduce< Range, Body, Partitioner >, tbb::internal::while_task< Stream, Body >, tbb::internal::task_handle_task< F >, tbb::internal::final_sum< Range, Body >, tbb::internal::spawner< N, function1, function2, function3 >, tbb::interface9::internal::finish_reduce< Body >, tbb::internal::while_group_task< Body >, tbb::internal::function_invoker< function >, tbb::interface9::internal::start_for< Range, Body, Partitioner >, and tbb::internal::while_iteration_task< Body >.
Referenced by tbb::flow::interface10::internal::priority_task_selector::execute(), tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::execute(), and tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all().
task_group_context* tbb::task::group () inline
Pointer to the task group descriptor.
Definition at line 846 of file task.h.
 { return prefix().context; }
priority_t tbb::task::group_priority () const inline
Retrieves current priority of the task group this task belongs to.
Definition at line 923 of file task.h.
 { return prefix().context->priority(); }
void tbb::task::increment_ref_count () inline
Atomically increment reference count.
Has acquire semantics
Definition at line 744 of file task.h.
References __TBB_FetchAndIncrementWacquire.
Referenced by tbb::flow::interface10::internal::key_matching_port< TraitsType >::key_matching_port(), and tbb::internal::task_group_base::ref_count_guard::ref_count_guard().
{
         __TBB_FetchAndIncrementWacquire( &prefix().ref_count );
     }
internal::reference_count tbb::task::internal_decrement_ref_count () private
Decrement reference count and return its new value.
Definition at line 196 of file task.cpp.
References __TBB_ASSERT, __TBB_FetchAndDecrementWrelease, ITT_NOTIFY, and sync_releasing.
{
     ITT_NOTIFY( sync_releasing, &prefix().ref_count );
     internal::reference_count k = __TBB_FetchAndDecrementWrelease( &prefix().ref_count );
     __TBB_ASSERT( k>=1, "task's reference count underflowed" );
     if( k==1 )
         ITT_NOTIFY( sync_acquired, &prefix().ref_count );
     return k-1;
 }
void tbb::task::internal_set_ref_count (int count) private
Set reference count.
Definition at line 187 of file task.cpp.
References __TBB_ASSERT, count, tbb::internal::es_ref_count_active, tbb::internal::task_prefix::extra_state, ITT_NOTIFY, p, tbb::internal::task_prefix::ref_count, tbb::internal::task_prefix::state, and sync_releasing.
{
     __TBB_ASSERT( count>=0, "count must not be negative" );
     task_prefix &p = prefix();
     __TBB_ASSERT(p.ref_count==1 && p.state==allocated && self().parent()==this
         || !(p.extra_state & es_ref_count_active), "ref_count race detected");
     ITT_NOTIFY(sync_releasing, &p.ref_count);
     p.ref_count = count;
 }
bool tbb::task::is_cancelled () const inline
Returns true if the context has received cancellation request.
Definition at line 913 of file task.h.
Referenced by tbb::is_current_task_group_canceling(), tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >::operator()(), and tbb::internal::pipeline_cleaner::~pipeline_cleaner().
 { return prefix().context->is_group_execution_cancelled(); }
bool tbb::task::is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
Definition at line 212 of file task.cpp.
{
     return true;
 }
bool tbb::task::is_stolen_task () const inline
True if task was stolen from the task pool of another thread.
Definition at line 850 of file task.h.
Referenced by tbb::interface9::internal::dynamic_grainsize_mode< linear_affinity_mode< affinity_partition_type > >::check_being_stolen(), and tbb::interface9::internal::old_auto_partition_type::should_execute_range().
{
         return (prefix().extra_state & 0x80)!=0;
     }
void tbb::task::note_affinity (affinity_id id) virtual
Invoked by scheduler to notify task that it ran on unexpected thread.
Invoked before method execute() runs, if task is stolen, or task has affinity but will be executed on another thread.
The default action does nothing.
Defined out of line so that compiler does not replicate task's vtable. It's pointless to define it inline anyway, because all call sites to it are virtual calls that the compiler is unlikely to optimize.
Reimplemented in tbb::interface9::internal::start_reduce< Range, Body, Partitioner >, and tbb::interface9::internal::start_for< Range, Body, Partitioner >.
Definition at line 249 of file task.cpp.
References tbb::internal::__TBB_load_relaxed(), tbb::internal::__TBB_store_relaxed(), tbb::task_group_context::bind_to(), tbb::task_group_context::binding_required, change_group(), tbb::task_group_context::copy_fp_settings(), tbb::task_group_context::fp_settings, tbb::task_group_context::isolated, tbb::task_group_context::itt_caller, ITT_STACK_CREATE, tbb::internal::governor::local_scheduler_weak(), tbb::task_group_context::my_kind, tbb::task_group_context::my_version_and_traits, and s.
Referenced by tbb::internal::generic_scheduler::enqueue(), tbb::internal::generic_scheduler::get_task(), and tbb::internal::generic_scheduler::steal_task().
{
 }
task* tbb::task::parent () const inline
task on whose behalf this task is working, or NULL if this is a root.
Definition at line 830 of file task.h.
References parent().
Referenced by tbb::internal::allocate_continuation_proxy::allocate(), tbb::interface9::internal::dynamic_grainsize_mode< linear_affinity_mode< affinity_partition_type > >::check_being_stolen(), tbb::interface5::internal::task_base::destroy(), tbb::internal::arena::enqueue_task(), tbb::internal::allocate_continuation_proxy::free(), tbb::interface9::internal::flag_task::is_peer_stolen(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::interface9::internal::flag_task::mark_task_stolen(), parent(), and tbb::internal::generic_scheduler::prepare_for_spawning().
 {return prefix().parent;}
internal::task_prefix& tbb::task::prefix (internal::version_tag * = NULL) const inline private
Get reference to corresponding task_prefix.
Version tag prevents loader on Linux from using the wrong symbol in debug builds.
Definition at line 941 of file task.h.
References tbb::internal::is_critical(), and tbb::internal::make_critical().
Referenced by tbb::internal::allocate_continuation_proxy::allocate(), tbb::internal::allocate_child_proxy::allocate(), tbb::internal::generic_scheduler::allocate_task(), tbb::internal::assert_task_valid(), tbb::internal::generic_scheduler::attach_arena(), tbb::internal::generic_scheduler::create_master(), tbb::internal::generic_scheduler::create_worker(), tbb::internal::generic_scheduler::deallocate_task(), tbb::interface5::internal::task_base::destroy(), tbb::internal::generic_scheduler::enqueue(), enqueue(), tbb::internal::arena::enqueue_task(), tbb::internal::task_proxy::extract_task(), tbb::internal::generic_scheduler::free_nonlocal_small_task(), tbb::internal::generic_scheduler::free_scheduler(), tbb::internal::generic_scheduler::free_task(), tbb::internal::generic_scheduler::generic_scheduler(), tbb::internal::generic_scheduler::get_task(), tbb::interface7::internal::task_arena_base::internal_current_slot(), tbb::interface7::internal::task_arena_base::internal_enqueue(), tbb::internal::is_critical(), tbb::internal::generic_scheduler::is_proxy(), tbb::internal::generic_scheduler::is_version_3_task(), tbb::internal::generic_scheduler::local_spawn(), tbb::internal::generic_scheduler::local_spawn_root_and_wait(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::internal::task_stream< num_priority_levels >::look_specific(), tbb::internal::make_critical(), tbb::internal::nested_arena_context::mimic_outermost_level(), tbb::internal::auto_empty_task::prefix(), tbb::internal::generic_scheduler::prepare_for_spawning(), tbb::internal::arena::process(), tbb::task_list::push_back(), recycle_as_child_of(), tbb::internal::reset_extra_state(), set_parent(), tbb::interface5::internal::task_base::spawn(), spawn_and_wait_for_all(), spawn_root_and_wait(), tbb::internal::generic_scheduler::steal_task(), tbb::internal::generic_scheduler::steal_task_from(), tbb::internal::custom_scheduler< SchedulerTraits >::tally_completion_of_predecessor(), tbb::internal::generic_scheduler::wait_until_empty(), tbb::internal::generic_scheduler::worker_outermost_level(), and tbb::interface7::internal::delegated_task::~delegated_task().
{
         return reinterpret_cast<internal::task_prefix*>(const_cast<task*>(this))[-1];
     }
void tbb::task::recycle_as_child_of (task & new_parent) inline
Change this to be a child of new_parent.
Definition at line 698 of file task.h.
References __TBB_ASSERT, context(), p, and prefix().
Referenced by tbb::internal::sum_node< Range, Body >::create_child().
{
         internal::task_prefix& p = prefix();
         __TBB_ASSERT( prefix().state==executing||prefix().state==allocated, "execute not running, or already recycled" );
         __TBB_ASSERT( prefix().ref_count==0, "no child tasks allowed when recycled as a child" );
         __TBB_ASSERT( p.parent==NULL, "parent must be null" );
         __TBB_ASSERT( new_parent.prefix().state<=recycle, "corrupt parent's state" );
         __TBB_ASSERT( new_parent.prefix().state!=freed, "parent already freed" );
         p.state = allocated;
         p.parent = &new_parent;
 #if __TBB_TASK_GROUP_CONTEXT
         p.context = new_parent.prefix().context;
 #endif /* __TBB_TASK_GROUP_CONTEXT */
     }
void tbb::task::recycle_as_continuation () inline
Change this to be a continuation of its former self.
The caller must guarantee that the task's refcount does not become zero until after the method execute() returns. Typically, this is done by having method execute() return a pointer to a child of the task. If the guarantee cannot be made, use method recycle_as_safe_continuation instead.
Because of the hazard, this method may be deprecated in the future.
Definition at line 684 of file task.h.
References __TBB_ASSERT.
{
         __TBB_ASSERT( prefix().state==executing, "execute not running?" );
         prefix().state = allocated;
     }
void tbb::task::recycle_as_safe_continuation () inline
Recommended to use, safe variant of recycle_as_continuation.
For safety, it requires additional increment of ref_count. With no descendants and ref_count of 1, it has the semantics of recycle_to_reexecute.
Definition at line 692 of file task.h.
References __TBB_ASSERT.
{
         __TBB_ASSERT( prefix().state==executing, "execute not running?" );
         prefix().state = recycle;
     }
void tbb::task::recycle_to_reexecute () inline
Schedule this for reexecution after current execute() returns.
Made obsolete by recycle_as_safe_continuation; may become deprecated.
Definition at line 714 of file task.h.
References __TBB_ASSERT.
Referenced by tbb::internal::while_task< Stream, Body >::execute().
{
         __TBB_ASSERT( prefix().state==executing, "execute not running, or already recycled" );
         __TBB_ASSERT( prefix().ref_count==0, "no child tasks allowed when recycled for reexecution" );
         prefix().state = reexecute;
     }
int tbb::task::ref_count () const inline
The internal reference count.
Definition at line 862 of file task.h.
References __TBB_ASSERT, __TBB_EXPORTED_METHOD, and int.
Referenced by tbb::interface9::internal::dynamic_grainsize_mode< linear_affinity_mode< affinity_partition_type > >::check_being_stolen(), tbb::internal::finish_scan< Range, Body >::execute(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::interface7::internal::delegated_task::~delegated_task(), and tbb::internal::task_group_base::~task_group_base().
{
 #if TBB_USE_ASSERT
         internal::reference_count ref_count_ = prefix().ref_count;
         __TBB_ASSERT( ref_count_==int(ref_count_), "integer overflow error");
 #endif
         return int(prefix().ref_count);
     }
task & tbb::task::self () static
The innermost task being executed or destroyed by the current thread at the moment.
Definition at line 205 of file task.cpp.
References __TBB_ASSERT, tbb::internal::generic_scheduler::assert_task_pool_valid(), tbb::internal::governor::local_scheduler_weak(), and tbb::internal::scheduler_state::my_innermost_running_task.
Referenced by tbb::parallel_while< Body >::add(), tbb::is_current_task_group_canceling(), and tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >::operator()().
                  {
     generic_scheduler *v = governor::local_scheduler_weak();
     v->assert_task_pool_valid();
     __TBB_ASSERT( v->my_innermost_running_task, NULL );
     return *v->my_innermost_running_task;
 }
void tbb::task::set_affinity (affinity_id id) inline
Set affinity for this task.
Definition at line 882 of file task.h.
References id.
Referenced by tbb::interface9::internal::linear_affinity_mode< static_partition_type >::set_affinity(), and tbb::interface9::internal::affinity_partition_type::set_affinity().
 {prefix().affinity = id;}
void tbb::task::set_group_priority (priority_t p) inline
Changes priority of the task group this task belongs to.
Definition at line 920 of file task.h.
 {  prefix().context->set_priority(p); }
void tbb::task::set_parent (task * p) inline
sets parent task pointer to specified value
Definition at line 833 of file task.h.
References __TBB_ASSERT, p, and prefix().
Referenced by tbb::interface9::internal::allocate_sibling().
{
 #if __TBB_TASK_GROUP_CONTEXT
         __TBB_ASSERT(!p || prefix().context == p->prefix().context, "The tasks must be in the same context");
 #endif
         prefix().parent = p;
     }
void tbb::task::set_ref_count (int count) inline
Set reference count.
Definition at line 734 of file task.h.
References count.
Referenced by tbb::interface9::internal::allocate_sibling(), tbb::internal::while_group_task< Body >::execute(), tbb::parallel_while< Body >::run(), tbb::interface9::internal::do_task_iter< Iterator, Body, Item >::run_for_random_access_iterator(), tbb::internal::task_group_base::task_group_base(), tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task(), and tbb::flow::interface10::graph::~graph().
{
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
         internal_set_ref_count(count);
 #else
         prefix().ref_count = count;
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT */
     }
void tbb::task::spawn_and_wait_for_all (task & child) inline
Similar to spawn followed by wait_for_all, but more efficient.
Definition at line 773 of file task.h.
References __TBB_EXPORTED_METHOD.
Referenced by tbb::internal::while_group_task< Body >::execute(), and tbb::parallel_while< Body >::run().
{
         prefix().owner->wait_for_all( *this, &child );
     }
void tbb::task::spawn_and_wait_for_all (task_list & list)
Similar to spawn followed by wait_for_all, but more efficient.
Definition at line 235 of file task.cpp.
References tbb::task_list::clear(), tbb::task_list::first, tbb::internal::governor::local_scheduler(), tbb::internal::generic_scheduler::local_spawn(), tbb::internal::generic_scheduler::local_wait_for_all(), tbb::task_list::next_ptr, prefix(), and s.
{
     generic_scheduler* s = governor::local_scheduler();
     task* t = list.first;
     if( t ) {
         if( &t->prefix().next!=list.next_ptr )
             s->local_spawn( t->prefix().next, *list.next_ptr );
         list.clear();
     }
     s->local_wait_for_all( *this, t );
 }
static void tbb::task::spawn_root_and_wait (task & root) inline static
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
Definition at line 781 of file task.h.
References prefix().
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::run(), tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run(), tbb::internal::start_scan< Range, Body, Partitioner >::run(), tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run(), and tbb::pipeline::run().
{
         root.prefix().owner->spawn_root_and_wait( root, root.prefix().next );
     }
void tbb::task::spawn_root_and_wait (task_list & root_list) inline static
Spawn root tasks on list and wait for all of them to finish.
If there are more tasks than worker threads, the tasks are spawned in order of front to back.
Definition at line 1051 of file task.h.
References tbb::task_list::clear(), tbb::task_list::first, and tbb::task_list::next_ptr.
{
     if( task* t = root_list.first ) {
         t->prefix().owner->spawn_root_and_wait( *t, *root_list.next_ptr );
         root_list.clear();
     }
 }
state_type tbb::task::state () const inline
Current execution state.
Definition at line 859 of file task.h.
Referenced by tbb::internal::generic_scheduler::allocate_task(), tbb::interface5::internal::task_base::destroy(), tbb::internal::arena::enqueue_task(), tbb::internal::generic_scheduler::free_nonlocal_small_task(), tbb::internal::generic_scheduler::free_task(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), and tbb::internal::generic_scheduler::prepare_for_spawning().
 {return state_type(prefix().state);}
void tbb::task::wait_for_all () inline
Wait for reference count to become one, and set reference count to zero.
Works on tasks while waiting.
Definition at line 792 of file task.h.
Referenced by tbb::flow::interface10::graph::wait_functor::operator()(), tbb::internal::task_group_base::wait(), and tbb::internal::task_group_base::~task_group_base().
{
         prefix().owner->wait_for_all( *this, NULL );
     }
Friends And Related Function Documentation
friend class interface5::internal::task_base friend
Definition at line 928 of file task.h.
friend class internal::allocate_additional_child_of_proxy friend
Definition at line 937 of file task.h.
friend class internal::allocate_child_proxy friend
Definition at line 936 of file task.h.
friend class internal::allocate_continuation_proxy friend
Definition at line 935 of file task.h.
friend class internal::allocate_root_proxy friend
Definition at line 931 of file task.h.
friend class internal::allocate_root_with_context_proxy friend
Definition at line 933 of file task.h.
bool internal::is_critical (task &) friend
void internal::make_critical (task &) friend
friend class internal::scheduler friend
Definition at line 930 of file task.h.
friend class task_list friend
Definition at line 929 of file task.h.
The documentation for this class was generated from the following files:
task.h
task.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.