Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::task_group_base Class Reference
tbb::internal::task_group_base Class Reference
#include <task_group.h>
Classes
class ref_count_guard
Public Member Functions
task_group_base (uintptr_t traits=0)
~task_group_base () __TBB_NOEXCEPT(false)
template<typename F >
void run (task_handle< F > &h)
task_group_status wait ()
bool is_canceling ()
void cancel ()
Protected Member Functions
task & owner ()
template<typename F >
task_group_status internal_run_and_wait (F &f)
template<typename Task , typename F >
void internal_run (__TBB_FORWARDING_REF(F) f)
Protected Attributes
empty_task * my_root
task_group_context my_context
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
Definition at line 84 of file task_group.h.
Constructor & Destructor Documentation
tbb::internal::task_group_base::task_group_base (uintptr_t traits = 0) inline
Definition at line 122 of file task_group.h.
References tbb::task::allocate_root(), and tbb::task::set_ref_count().
         : my_context(task_group_context::bound, task_group_context::default_traits | traits)
     {
         my_root = new( task::allocate_root(my_context) ) empty_task;
         my_root->set_ref_count(1);
     }
tbb::internal::task_group_base::~task_group_base () inline
Definition at line 129 of file task_group.h.
References __TBB_CATCH, __TBB_RETHROW, __TBB_TRY, tbb::internal::cancel, tbb::internal::eid_missing_wait, tbb::task::ref_count(), tbb::internal::throw_exception(), and tbb::task::wait_for_all().
{
         if( my_root->ref_count() > 1 ) {
 #if __TBB_CPP17_UNCAUGHT_EXCEPTIONS_PRESENT
             bool stack_unwinding_in_progress = std::uncaught_exceptions() > 0;
 #else
             bool stack_unwinding_in_progress = std::uncaught_exception();
 #endif
             // Always attempt to do proper cleanup to avoid inevitable memory corruption
             // in case of missing wait (for the sake of better testability & debuggability)
             if ( !is_canceling() )
                 cancel();
             __TBB_TRY {
                 my_root->wait_for_all();
             } __TBB_CATCH (...) {
                 task::destroy(*my_root);
                 __TBB_RETHROW();
             }
             task::destroy(*my_root);
             if ( !stack_unwinding_in_progress )
                 internal::throw_exception( internal::eid_missing_wait );
         }
         else {
             task::destroy(*my_root);
         }
     }
Member Function Documentation
void tbb::internal::task_group_base::cancel () inline
Definition at line 179 of file task_group.h.
References tbb::task_group_context::cancel_group_execution().
                   {
         my_context.cancel_group_execution();
     }
template<typename Task , typename F > void tbb::internal::task_group_base::internal_run (__TBB_FORWARDING_REF(F) f) inline protected
Definition at line 117 of file task_group.h.
{
         owner().spawn( *new( owner().allocate_additional_child_of(*my_root) ) Task( internal::forward<F>(f) ));
     }
template<typename F > task_group_status tbb::internal::task_group_base::internal_run_and_wait (F & f) inline protected
Definition at line 102 of file task_group.h.
References __TBB_CATCH, __TBB_TRY, tbb::task_group_context::is_group_execution_cancelled(), and tbb::task_group_context::register_pending_exception().
{
         __TBB_TRY {
             if ( !my_context.is_group_execution_cancelled() ) {
                 // We need to increase the reference count of the root task to notify waiters that
                 // this task group has some work in progress.
                 ref_count_guard guard(*my_root);
                 f();
             }
         } __TBB_CATCH( ... ) {
             my_context.register_pending_exception();
         }
         return wait();
     }
bool tbb::internal::task_group_base::is_canceling () inline
Definition at line 175 of file task_group.h.
References tbb::task_group_context::is_group_execution_cancelled().
{
         return my_context.is_group_execution_cancelled();
     }
task& tbb::internal::task_group_base::owner () inline protected
Definition at line 99 of file task_group.h.
 { return *my_root; }
template<typename F > void tbb::internal::task_group_base::run (task_handle< F > & h) inline
Definition at line 156 of file task_group.h.
References h.
Referenced by tbb::task_group::task_group().
{
         internal_run< internal::task_handle_task<F> >( h );
     }
task_group_status tbb::internal::task_group_base::wait () inline
Definition at line 160 of file task_group.h.
References __TBB_CATCH, __TBB_RETHROW, __TBB_TRY, tbb::canceled, tbb::complete, tbb::task_group_context::is_group_execution_cancelled(), tbb::task_group_context::reset(), and tbb::task::wait_for_all().
Referenced by tbb::structured_task_group::wait().
{
         __TBB_TRY {
             my_root->wait_for_all();
         } __TBB_CATCH( ... ) {
             my_context.reset();
             __TBB_RETHROW();
         }
         if ( my_context.is_group_execution_cancelled() ) {
             // TODO: the reset method is not thread-safe. Ensure the correct behavior.
             my_context.reset();
             return canceled;
         }
         return complete;
     }
Member Data Documentation
task_group_context tbb::internal::task_group_base::my_context protected
Definition at line 97 of file task_group.h.
empty_task* tbb::internal::task_group_base::my_root protected
Definition at line 96 of file task_group.h.
The documentation for this class was generated from the following file:
task_group.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.