Intel(R) Threading Building Blocks Doxygen Documentation: tbb::task_list Class Reference
tbb::task_list Class Reference
Task Scheduling
A list of children.
#include <task.h>
Public Member Functions
task_list ()
Construct empty list.
~task_list ()
Destroys the list, but does not destroy the task objects.
bool empty () const
True if list if empty; false otherwise.
void push_back (task &task)
Push task onto back of list.
task & pop_front ()
Pop the front task from the list.
void clear ()
Clear the list.
Private Attributes
task * first
task ** next_ptr
Friends
class task
class interface5::internal::task_base
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
A list of children.
Used for method task::spawn_children
Definition at line 990 of file task.h.
Constructor & Destructor Documentation
tbb::task_list::task_list () inline
Construct empty list.
Definition at line 998 of file task.h.
 : first(NULL), next_ptr(&first) {}
tbb::task_list::~task_list () inline
Destroys the list, but does not destroy the task objects.
Definition at line 1001 of file task.h.
 {}
Member Function Documentation
void tbb::task_list::clear () inline
Clear the list.
Definition at line 1034 of file task.h.
References tbb::internal::first().
Referenced by tbb::interface5::internal::task_base::spawn(), tbb::task::spawn_and_wait_for_all(), and tbb::task::spawn_root_and_wait().
                  {
         first=NULL;
         next_ptr=&first;
     }
bool tbb::task_list::empty () const inline
True if list if empty; false otherwise.
Definition at line 1004 of file task.h.
References tbb::internal::first().
 {return !first;}
task& tbb::task_list::pop_front () inline
Pop the front task from the list.
Definition at line 1025 of file task.h.
                       {
         __TBB_ASSERT( !empty(), "attempt to pop item from empty task_list" );
         task* result = first;
         first = result->prefix().next;
         if( !first ) next_ptr = &first;
         return *result;
     }
void tbb::task_list::push_back (task & task) inline
Push task onto back of list.
Definition at line 1007 of file task.h.
References __TBB_ASSERT, tbb::internal::first(), tbb::task::prefix(), and task.
Referenced by tbb::internal::while_group_task< Body >::execute(), tbb::interface9::internal::do_group_task_forward< Iterator, Body, Item >::execute(), tbb::interface9::internal::do_group_task_input< Body, Item >::execute(), and tbb::interface9::internal::do_task_iter< Iterator, Body, Item >::run_for_random_access_iterator().
{
         task.prefix().next = NULL;
         *next_ptr = &task;
         next_ptr = &task.prefix().next;
     }
Friends And Related Function Documentation
friend class interface5::internal::task_base friend
Definition at line 995 of file task.h.
friend class task friend
Definition at line 994 of file task.h.
Member Data Documentation
task* tbb::task_list::first private
Definition at line 992 of file task.h.
Referenced by tbb::interface5::internal::task_base::spawn(), tbb::task::spawn_and_wait_for_all(), and tbb::task::spawn_root_and_wait().
task** tbb::task_list::next_ptr private
Definition at line 993 of file task.h.
Referenced by tbb::interface5::internal::task_base::spawn(), tbb::task::spawn_and_wait_for_all(), and tbb::task::spawn_root_and_wait().
The documentation for this class was generated from the following file:
task.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.