Intel(R) Threading Building Blocks Doxygen Documentation: tbb::spin_rw_mutex_v3 Class Reference
tbb::spin_rw_mutex_v3 Class Reference
Synchronization
Fast, unfair, spinning reader-writer lock with backoff and writer-preference.
#include <spin_rw_mutex.h>
Classes
class scoped_lock
The scoped locking pattern.
Public Member Functions
spin_rw_mutex_v3 ()
Construct unacquired mutex.
void lock ()
Acquire writer lock.
bool try_lock ()
Try acquiring writer lock (non-blocking)
void unlock ()
Release lock.
void lock_read ()
Acquire reader lock.
bool try_lock_read ()
Try acquiring reader lock (non-blocking)
Static Public Attributes
static const bool is_rw_mutex = true
static const bool is_recursive_mutex = false
static const bool is_fair_mutex = false
Protected Types
typedef intptr_t state_t
Protected Attributes
state_t state
State of lock.
Static Protected Attributes
static const state_t WRITER = 1
static const state_t WRITER_PENDING = 2
static const state_t READERS = ~(WRITER | WRITER_PENDING)
static const state_t ONE_READER = 4
static const state_t BUSY = WRITER | READERS
Private Member Functions
bool __TBB_EXPORTED_METHOD internal_acquire_writer ()
Internal acquire write lock.
void __TBB_EXPORTED_METHOD internal_release_writer ()
Out of line code for releasing a write lock.
void __TBB_EXPORTED_METHOD internal_acquire_reader ()
Internal acquire read lock.
bool __TBB_EXPORTED_METHOD internal_upgrade ()
Internal upgrade reader to become a writer.
void __TBB_EXPORTED_METHOD internal_downgrade ()
Out of line code for downgrading a writer to a reader.
void __TBB_EXPORTED_METHOD internal_release_reader ()
Internal release read lock.
bool __TBB_EXPORTED_METHOD internal_try_acquire_writer ()
Internal try_acquire write lock.
bool __TBB_EXPORTED_METHOD internal_try_acquire_reader ()
Internal try_acquire read lock.
void __TBB_EXPORTED_METHOD internal_construct ()
Detailed Description
Fast, unfair, spinning reader-writer lock with backoff and writer-preference.
Definition at line 42 of file spin_rw_mutex.h.
Member Typedef Documentation
typedef intptr_t tbb::spin_rw_mutex_v3::state_t protected
Definition at line 211 of file spin_rw_mutex.h.
Constructor & Destructor Documentation
tbb::spin_rw_mutex_v3::spin_rw_mutex_v3 () inline
Construct unacquired mutex.
Definition at line 74 of file spin_rw_mutex.h.
References __TBB_ASSERT.
                        : state(0) {
 #if TBB_USE_THREADING_TOOLS
         internal_construct();
 #endif
     }
Member Function Documentation
void tbb::spin_rw_mutex_v3::internal_acquire_reader () private
Internal acquire read lock.
Acquire read lock on given mutex.
Definition at line 66 of file spin_rw_mutex.cpp.
References __TBB_ASSERT, ITT_NOTIFY, ONE_READER, READERS, s, state, WRITER, and WRITER_PENDING.
 {
     ITT_NOTIFY(sync_prepare, this);
     for( internal::atomic_backoff b;;b.pause() ){
         state_t s = const_cast<volatile state_t&>(state); // ensure reloading
         if( !(s & (WRITER|WRITER_PENDING)) ) { // no writer or write requests
             state_t t = (state_t)__TBB_FetchAndAddW( &state, (intptr_t) ONE_READER );
             if( !( t&WRITER ))
                 break; // successfully stored increased number of readers
             // writer got there first, undo the increment
             __TBB_FetchAndAddW( &state, -(intptr_t)ONE_READER );
         }
     }
     ITT_NOTIFY(sync_acquired, this);
     __TBB_ASSERT( state & READERS, "invalid state of a read lock: no readers" );
 }
bool tbb::spin_rw_mutex_v3::internal_acquire_writer () private
Internal acquire write lock.
Acquire write lock on the given mutex.
Definition at line 41 of file spin_rw_mutex.cpp.
References __TBB_AtomicOR(), BUSY, tbb::CAS(), ITT_NOTIFY, s, state, WRITER, and WRITER_PENDING.
Referenced by internal_upgrade().
 {
     ITT_NOTIFY(sync_prepare, this);
     for( internal::atomic_backoff backoff;;backoff.pause() ){
         state_t s = const_cast<volatile state_t&>(state); // ensure reloading
         if( !(s & BUSY) ) { // no readers, no writers
             if( CAS(state, WRITER, s)==s )
                 break; // successfully stored writer flag
             backoff.reset(); // we could be very close to complete op.
         } else if( !(s & WRITER_PENDING) ) { // no pending writers
             __TBB_AtomicOR(&state, WRITER_PENDING);
         }
     }
     ITT_NOTIFY(sync_acquired, this);
     return false;
 }
void tbb::spin_rw_mutex_v3::internal_construct () private
Definition at line 156 of file spin_rw_mutex.cpp.
References _T, and ITT_SYNC_CREATE.
{
     ITT_SYNC_CREATE(this, _T("tbb::spin_rw_mutex"), _T(""));
 }
void tbb::spin_rw_mutex_v3::internal_downgrade () private
Out of line code for downgrading a writer to a reader.
Downgrade writer to a reader.
This code has debug checking and instrumentation for Intel(R) Thread Checker and Intel(R) Thread Profiler.
Definition at line 112 of file spin_rw_mutex.cpp.
References __TBB_ASSERT, ITT_NOTIFY, ONE_READER, READERS, state, sync_releasing, and WRITER.
{
     ITT_NOTIFY(sync_releasing, this);
     __TBB_FetchAndAddW( &state, (intptr_t)(ONE_READER-WRITER));
     __TBB_ASSERT( state & READERS, "invalid state after downgrade: no readers" );
 }
void tbb::spin_rw_mutex_v3::internal_release_reader () private
Internal release read lock.
Release read lock on the given mutex.
Definition at line 119 of file spin_rw_mutex.cpp.
References __TBB_ASSERT, __TBB_FetchAndAddWrelease, ITT_NOTIFY, ONE_READER, READERS, state, and sync_releasing.
Referenced by internal_upgrade(), and tbb::spin_rw_mutex_v3::scoped_lock::release().
 {
     __TBB_ASSERT( state & READERS, "invalid state of a read lock: no readers" );
     ITT_NOTIFY(sync_releasing, this); // release reader
     __TBB_FetchAndAddWrelease( &state,-(intptr_t)ONE_READER);
 }
void tbb::spin_rw_mutex_v3::internal_release_writer () private
Out of line code for releasing a write lock.
Release writer lock on the given mutex.
This code has debug checking and instrumentation for Intel(R) Thread Checker and Intel(R) Thread Profiler.
Definition at line 59 of file spin_rw_mutex.cpp.
References __TBB_AtomicAND(), ITT_NOTIFY, READERS, state, and sync_releasing.
Referenced by tbb::spin_rw_mutex_v3::scoped_lock::release().
 {
     ITT_NOTIFY(sync_releasing, this);
     __TBB_AtomicAND( &state, READERS );
 }
bool tbb::spin_rw_mutex_v3::internal_try_acquire_reader () private
Internal try_acquire read lock.
Try to acquire read lock on the given mutex.
Definition at line 140 of file spin_rw_mutex.cpp.
References ITT_NOTIFY, ONE_READER, s, state, WRITER, and WRITER_PENDING.
Referenced by tbb::spin_rw_mutex_v3::scoped_lock::try_acquire().
 {
     // for a reader: acquire if no active or waiting writers
     state_t s = state;
     if( !(s & (WRITER|WRITER_PENDING)) ) { // no writers
         state_t t = (state_t)__TBB_FetchAndAddW( &state, (intptr_t) ONE_READER );
         if( !( t&WRITER )) {  // got the lock
             ITT_NOTIFY(sync_acquired, this);
             return true; // successfully stored increased number of readers
         }
         // writer got there first, undo the increment
         __TBB_FetchAndAddW( &state, -(intptr_t)ONE_READER );
     }
     return false;
 }
bool tbb::spin_rw_mutex_v3::internal_try_acquire_writer () private
Internal try_acquire write lock.
Try to acquire write lock on the given mutex.
Definition at line 127 of file spin_rw_mutex.cpp.
References BUSY, tbb::CAS(), ITT_NOTIFY, s, state, and WRITER.
Referenced by tbb::spin_rw_mutex_v3::scoped_lock::try_acquire().
 {
     // for a writer: only possible to acquire if no active readers or writers
     state_t s = state;
     if( !(s & BUSY) ) // no readers, no writers; mask is 1..1101
         if( CAS(state, WRITER, s)==s ) {
             ITT_NOTIFY(sync_acquired, this);
             return true; // successfully stored writer flag
         }
     return false;
 }
bool tbb::spin_rw_mutex_v3::internal_upgrade () private
Internal upgrade reader to become a writer.
Upgrade reader to become a writer.
Returns whether the upgrade happened without releasing and re-acquiring the lock
Definition at line 86 of file spin_rw_mutex.cpp.
References __TBB_ASSERT, tbb::CAS(), internal_acquire_writer(), internal_release_reader(), ITT_NOTIFY, ONE_READER, READERS, s, state, WRITER, and WRITER_PENDING.
 {
     state_t s = state;
     __TBB_ASSERT( s & READERS, "invalid state before upgrade: no readers " );
     // check and set writer-pending flag
     // required conditions: either no pending writers, or we are the only reader
     // (with multiple readers and pending writer, another upgrade could have been requested)
     while( (s & READERS)==ONE_READER || !(s & WRITER_PENDING) ) {
         state_t old_s = s;
         if( (s=CAS(state, s | WRITER | WRITER_PENDING, s))==old_s ) {
             ITT_NOTIFY(sync_prepare, this);
             internal::atomic_backoff backoff;
             while( (state & READERS) != ONE_READER ) backoff.pause();
             __TBB_ASSERT((state&(WRITER_PENDING|WRITER))==(WRITER_PENDING|WRITER),"invalid state when upgrading to writer");
             // both new readers and writers are blocked at this time
             __TBB_FetchAndAddW( &state,  - (intptr_t)(ONE_READER+WRITER_PENDING));
             ITT_NOTIFY(sync_acquired, this);
             return true; // successfully upgraded
         }
     }
     // slow reacquire
     internal_release_reader();
     return internal_acquire_writer(); // always returns false
 }
void tbb::spin_rw_mutex_v3::lock () inline
Acquire writer lock.
Definition at line 184 of file spin_rw_mutex.h.
Referenced by tbb::internal::market::adjust_demand(), and tbb::internal::market::try_destroy_arena().
 {internal_acquire_writer();}
void tbb::spin_rw_mutex_v3::lock_read () inline
Acquire reader lock.
Definition at line 204 of file spin_rw_mutex.h.
 {internal_acquire_reader();}
bool tbb::spin_rw_mutex_v3::try_lock () inline
Try acquiring writer lock (non-blocking)
Return true if lock acquired; false otherwise.
Definition at line 188 of file spin_rw_mutex.h.
 {return internal_try_acquire_writer();}
bool tbb::spin_rw_mutex_v3::try_lock_read () inline
Try acquiring reader lock (non-blocking)
Return true if reader lock acquired; false otherwise.
Definition at line 208 of file spin_rw_mutex.h.
 {return internal_try_acquire_reader();}
void tbb::spin_rw_mutex_v3::unlock () inline
Release lock.
Definition at line 191 of file spin_rw_mutex.h.
References __TBB_AtomicAND(), and __TBB_FetchAndAddWrelease.
Referenced by tbb::internal::market::adjust_demand(), and tbb::internal::market::try_destroy_arena().
                   {
 #if TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT
         if( state&WRITER ) internal_release_writer();
         else               internal_release_reader();
 #else
         if( state&WRITER ) __TBB_AtomicAND( &state, READERS );
         else               __TBB_FetchAndAddWrelease( &state, -(intptr_t)ONE_READER);
 #endif /* TBB_USE_THREADING_TOOLS||TBB_USE_ASSERT */
     }
Member Data Documentation
const state_t tbb::spin_rw_mutex_v3::BUSY = WRITER | READERS static protected
Definition at line 216 of file spin_rw_mutex.h.
Referenced by internal_acquire_writer(), and internal_try_acquire_writer().
const bool tbb::spin_rw_mutex_v3::is_fair_mutex = false static
Definition at line 179 of file spin_rw_mutex.h.
const bool tbb::spin_rw_mutex_v3::is_recursive_mutex = false static
Definition at line 178 of file spin_rw_mutex.h.
const bool tbb::spin_rw_mutex_v3::is_rw_mutex = true static
Definition at line 177 of file spin_rw_mutex.h.
const state_t tbb::spin_rw_mutex_v3::ONE_READER = 4 static protected
Definition at line 215 of file spin_rw_mutex.h.
Referenced by internal_acquire_reader(), internal_downgrade(), internal_release_reader(), internal_try_acquire_reader(), and internal_upgrade().
const state_t tbb::spin_rw_mutex_v3::READERS = ~(WRITER | WRITER_PENDING) static protected
Definition at line 214 of file spin_rw_mutex.h.
Referenced by internal_acquire_reader(), internal_downgrade(), internal_release_reader(), internal_release_writer(), and internal_upgrade().
state_t tbb::spin_rw_mutex_v3::state protected
State of lock.
Bit 0 = writer is holding lock Bit 1 = request by a writer to acquire lock (hint to readers to wait) Bit 2..N = number of readers holding lock
Definition at line 221 of file spin_rw_mutex.h.
Referenced by internal_acquire_reader(), internal_acquire_writer(), internal_downgrade(), internal_release_reader(), internal_release_writer(), internal_try_acquire_reader(), internal_try_acquire_writer(), internal_upgrade(), and tbb::spin_rw_mutex_v3::scoped_lock::release().
const state_t tbb::spin_rw_mutex_v3::WRITER = 1 static protected
Definition at line 212 of file spin_rw_mutex.h.
Referenced by internal_acquire_reader(), internal_acquire_writer(), internal_downgrade(), internal_try_acquire_reader(), internal_try_acquire_writer(), and internal_upgrade().
const state_t tbb::spin_rw_mutex_v3::WRITER_PENDING = 2 static protected
Definition at line 213 of file spin_rw_mutex.h.
Referenced by internal_acquire_reader(), internal_acquire_writer(), internal_try_acquire_reader(), and internal_upgrade().
The documentation for this class was generated from the following files:
spin_rw_mutex.h
spin_rw_mutex.cpp
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.