Intel(R) Threading Building Blocks Doxygen Documentation: tbb::task_handle< F > Class Template Reference
tbb::task_handle< F > Class Template Reference
#include <task_group.h>
Public Member Functions
task_handle (const F &f)
task_handle (F &&f)
void operator() () const
Private Member Functions
void mark_scheduled ()
Private Attributes
F my_func
intptr_t my_state
Static Private Attributes
static const intptr_t scheduled = 0x1
Friends
template<typename _F >
class internal::task_handle_task
class task_group
class structured_task_group
Detailed Description
template<typename F>
class tbb::task_handle< F >
Definition at line 40 of file task_group.h.
Constructor & Destructor Documentation
template<typename F> tbb::task_handle< F >::task_handle (const F & f) inline
Definition at line 57 of file task_group.h.
 : my_func(f), my_state(0) {}
template<typename F> tbb::task_handle< F >::task_handle (F && f) inline
Definition at line 59 of file task_group.h.
 : my_func( std::move(f)), my_state(0) {}
Member Function Documentation
template<typename F> void tbb::task_handle< F >::mark_scheduled () inline private
Definition at line 50 of file task_group.h.
References tbb::internal::eid_invalid_multiple_scheduling, and tbb::internal::throw_exception().
Referenced by tbb::task_group::run_and_wait(), tbb::structured_task_group::run_and_wait(), and tbb::internal::task_handle_task< F >::task_handle_task().
{
         // The check here is intentionally lax to avoid the impact of interlocked operation
         if ( my_state & scheduled )
             internal::throw_exception( internal::eid_invalid_multiple_scheduling );
         my_state |= scheduled;
     }
template<typename F> void tbb::task_handle< F >::operator() () const inline
Definition at line 62 of file task_group.h.
 { my_func(); }
Friends And Related Function Documentation
template<typename F> template<typename _F > friend class internal::task_handle_task friend
Definition at line 41 of file task_group.h.
template<typename F> friend class structured_task_group friend
Definition at line 43 of file task_group.h.
template<typename F> friend class task_group friend
Definition at line 42 of file task_group.h.
Member Data Documentation
template<typename F> F tbb::task_handle< F >::my_func private
Definition at line 47 of file task_group.h.
template<typename F> intptr_t tbb::task_handle< F >::my_state private
Definition at line 48 of file task_group.h.
template<typename F> const intptr_t tbb::task_handle< F >::scheduled = 0x1 static private
Definition at line 45 of file task_group.h.
The documentation for this class was generated from the following file:
task_group.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.