Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::start_reduce< Range, Body, Partitioner > Class Template Reference
tbb::interface9::internal::start_reduce< Range, Body, Partitioner > Class Template Reference
Algorithms
Task type used to split the work of parallel_reduce.
#include <parallel_reduce.h>
Public Member Functions
start_reduce (const Range &range, Body *body, Partitioner &partitioner)
Constructor used for root task.
start_reduce (start_reduce &parent_, typename Partitioner::split_type &split_obj)
Splitting constructor used to generate children.
start_reduce (start_reduce &parent_, const Range &r, depth_t d)
Construct right child from the given range as response to the demand.
void run_body (Range &r)
Run body for range.
void offer_work (typename Partitioner::split_type &split_obj)
spawn right task, serves as callback for partitioner
void offer_work (const Range &r, depth_t d=0)
spawn right task, serves as callback for partitioner
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions
static void run (const Range &range, Body &body, Partitioner &partitioner)
static void run (const Range &range, Body &body, Partitioner &partitioner, task_group_context &context)
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Private Types
typedef finish_reduce< Body > finish_type
Private Member Functions
task * execute () __TBB_override
Should be overridden by derived classes.
void note_affinity (affinity_id id) __TBB_override
Update affinity info, if any.
Private Attributes
Body * my_body
Range my_range
Partitioner::task_partition_type my_partition
reduction_context my_context
Friends
template<typename Body_ >
class finish_reduce
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
template<typename Range, typename Body, typename Partitioner>
class tbb::interface9::internal::start_reduce< Range, Body, Partitioner >
Task type used to split the work of parallel_reduce.
Definition at line 86 of file parallel_reduce.h.
Member Typedef Documentation
template<typename Range , typename Body , typename Partitioner > typedef finish_reduce<Body> tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::finish_type private
Definition at line 87 of file parallel_reduce.h.
Constructor & Destructor Documentation
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::start_reduce (const Range & range, Body * body, Partitioner & partitioner) inline
Constructor used for root task.
Definition at line 102 of file parallel_reduce.h.
                                                                                  :
             my_body(body),
             my_range(range),
             my_partition(partitioner),
             my_context(root_task)
         {
         }
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::start_reduce (start_reduce< Range, Body, Partitioner > & parent_, typename Partitioner::split_type & split_obj) inline
Splitting constructor used to generate children.
parent_ becomes left child. Newly constructed object is right child.
Definition at line 111 of file parallel_reduce.h.
References tbb::interface9::internal::left_child, and tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::my_context.
                                                                                          :
             my_body(parent_.my_body),
             my_range(parent_.my_range, split_obj),
             my_partition(parent_.my_partition, split_obj),
             my_context(right_child)
         {
             my_partition.set_affinity(*this);
             parent_.my_context = left_child;
         }
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::start_reduce (start_reduce< Range, Body, Partitioner > & parent_, const Range & r, depth_t d) inline
Construct right child from the given range as response to the demand.
parent_ remains left child. Newly constructed object is right child.
Definition at line 122 of file parallel_reduce.h.
References tbb::interface9::internal::left_child, and tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::my_context.
                                                                          :
             my_body(parent_.my_body),
             my_range(r),
             my_partition(parent_.my_partition, split()),
             my_context(right_child)
         {
             my_partition.set_affinity(*this);
             my_partition.align_depth( d ); // TODO: move into constructor of partitioner
             parent_.my_context = left_child;
         }
Member Function Documentation
template<typename Range , typename Body , typename Partitioner > task * tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::execute () private virtual
Should be overridden by derived classes.
Implements tbb::task.
Definition at line 182 of file parallel_reduce.h.
References __TBB_ASSERT, tbb::aligned_space< T, N >::begin(), tbb::interface9::internal::finish_reduce< Body >::has_right_zombie, tbb::internal::itt_load_word_with_acquire(), tbb::internal::itt_store_word_with_release(), tbb::interface9::internal::left_child, tbb::interface9::internal::finish_reduce< Body >::my_body, parent, tbb::interface9::internal::root_task, and tbb::interface9::internal::finish_reduce< Body >::zombie_space.
{
         my_partition.check_being_stolen( *this );
         if( my_context==right_child ) {
             finish_type* parent_ptr = static_cast<finish_type*>(parent());
             if( !itt_load_word_with_acquire(parent_ptr->my_body) ) { // TODO: replace by is_stolen_task() or by parent_ptr->ref_count() == 2???
                 my_body = new( parent_ptr->zombie_space.begin() ) Body(*my_body,split());
                 parent_ptr->has_right_zombie = true;
             }
         } else __TBB_ASSERT(my_context==root_task,NULL);// because left leaf spawns right leafs without recycling
         my_partition.execute(*this, my_range);
         if( my_context==left_child ) {
             finish_type* parent_ptr = static_cast<finish_type*>(parent());
             __TBB_ASSERT(my_body!=parent_ptr->zombie_space.begin(),NULL);
             itt_store_word_with_release(parent_ptr->my_body, my_body );
         }
         return NULL;
     }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::note_affinity (affinity_id id) inline private virtual
Update affinity info, if any.
Reimplemented from tbb::task.
Definition at line 94 of file parallel_reduce.h.
{
             my_partition.note_affinity( id );
         }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::offer_work (typename Partitioner::split_type & split_obj) inline
spawn right task, serves as callback for partitioner
Definition at line 155 of file parallel_reduce.h.
References tbb::interface9::internal::allocate_sibling().
{
             task *tasks[2];
             allocate_sibling(static_cast<task*>(this), tasks, sizeof(start_reduce), sizeof(finish_type));
             new((void*)tasks[0]) finish_type(my_context);
             new((void*)tasks[1]) start_reduce(*this, split_obj);
             spawn(*tasks[1]);
         }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::offer_work (const Range & r, depth_t d = 0) inline
spawn right task, serves as callback for partitioner
Definition at line 163 of file parallel_reduce.h.
References tbb::interface9::internal::allocate_sibling(), and d.
{
             task *tasks[2];
             allocate_sibling(static_cast<task*>(this), tasks, sizeof(start_reduce), sizeof(finish_type));
             new((void*)tasks[0]) finish_type(my_context);
             new((void*)tasks[1]) start_reduce(*this, r, d);
             spawn(*tasks[1]);
         }
template<typename Range , typename Body , typename Partitioner > static void tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run (const Range & range, Body & body, Partitioner & partitioner) inline static
Definition at line 132 of file parallel_reduce.h.
References tbb::task::allocate_root(), and tbb::task::spawn_root_and_wait().
Referenced by tbb::parallel_reduce().
{
             if( !range.empty() ) {
 #if !__TBB_TASK_GROUP_CONTEXT || TBB_JOIN_OUTER_TASK_GROUP
                 task::spawn_root_and_wait( *new(task::allocate_root()) start_reduce(range,&body,partitioner) );
 #else
                 // Bound context prevents exceptions from body to affect nesting or sibling algorithms,
                 // and allows users to handle exceptions safely by wrapping parallel_for in the try-block.
                 task_group_context context(PARALLEL_REDUCE);
                 task::spawn_root_and_wait( *new(task::allocate_root(context)) start_reduce(range,&body,partitioner) );
 #endif /* __TBB_TASK_GROUP_CONTEXT && !TBB_JOIN_OUTER_TASK_GROUP */
             }
         }
template<typename Range , typename Body , typename Partitioner > static void tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run (const Range & range, Body & body, Partitioner & partitioner, task_group_context & context) inline static
Definition at line 145 of file parallel_reduce.h.
References tbb::task::allocate_root(), and tbb::task::spawn_root_and_wait().
{
             if( !range.empty() )
                 task::spawn_root_and_wait( *new(task::allocate_root(context)) start_reduce(range,&body,partitioner) );
         }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run_body (Range & r) inline
Run body for range.
Definition at line 151 of file parallel_reduce.h.
 { (*my_body)( r ); }
Friends And Related Function Documentation
template<typename Range , typename Body , typename Partitioner > template<typename Body_ > friend class finish_reduce friend
Definition at line 98 of file parallel_reduce.h.
Member Data Documentation
template<typename Range , typename Body , typename Partitioner > Body* tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::my_body private
Definition at line 88 of file parallel_reduce.h.
template<typename Range , typename Body , typename Partitioner > reduction_context tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::my_context private
Definition at line 91 of file parallel_reduce.h.
Referenced by tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::start_reduce().
template<typename Range , typename Body , typename Partitioner > Partitioner::task_partition_type tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::my_partition private
Definition at line 90 of file parallel_reduce.h.
template<typename Range , typename Body , typename Partitioner > Range tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::my_range private
Definition at line 89 of file parallel_reduce.h.
The documentation for this class was generated from the following file:
parallel_reduce.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.