Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::internal::successor_cache< T, M > Class Template Reference
tbb::flow::interface10::internal::successor_cache< T, M > Class Template Reference
An abstract cache of successors.
#include <flow_graph.h>
Public Member Functions
successor_cache ()
void set_owner (owner_type *owner)
virtual ~successor_cache ()
void register_successor (successor_type &r)
void remove_successor (successor_type &r)
bool empty ()
void clear ()
Protected Types
typedef M mutex_type
typedef untyped_receiver successor_type
typedef untyped_receiver * pointer_type
typedef untyped_sender owner_type
typedef std::list< pointer_type > successors_type
Protected Attributes
mutex_type my_mutex
successors_type my_successors
owner_type * my_owner
Additional Inherited Members
Private Member Functions inherited from tbb::internal::no_copy
no_copy ()
Allow default construction.
Detailed Description
template<typename T, typename M = spin_rw_mutex>
class tbb::flow::interface10::internal::successor_cache< T, M >
An abstract cache of successors.
Definition at line 107 of file flow_graph.h.
Member Typedef Documentation
template<typename T, typename M = spin_rw_mutex> typedef M tbb::flow::interface10::internal::successor_cache< T, M >::mutex_type protected
Definition at line 281 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> typedef untyped_sender tbb::flow::interface10::internal::successor_cache< T, M >::owner_type protected
Definition at line 287 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> typedef untyped_receiver* tbb::flow::interface10::internal::successor_cache< T, M >::pointer_type protected
Definition at line 286 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> typedef untyped_receiver tbb::flow::interface10::internal::successor_cache< T, M >::successor_type protected
Definition at line 285 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> typedef std::list< pointer_type > tbb::flow::interface10::internal::successor_cache< T, M >::successors_type protected
Definition at line 293 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T, typename M = spin_rw_mutex> tbb::flow::interface10::internal::successor_cache< T, M >::successor_cache () inline
Definition at line 329 of file flow_graph.h.
 {
template<typename T, typename M = spin_rw_mutex> virtual tbb::flow::interface10::internal::successor_cache< T, M >::~successor_cache () inline virtual
Definition at line 333 of file flow_graph.h.
Member Function Documentation
template<typename T, typename M = spin_rw_mutex> void tbb::flow::interface10::internal::successor_cache< T, M >::clear () inline
Definition at line 356 of file flow_graph.h.
Referenced by tbb::flow::interface10::internal::key_from_message_body< K &, T >::operator()(), tbb::flow::interface10::buffer_node< T, A >::reset_node(), tbb::flow::interface10::limiter_node< T >::reset_node(), and tbb::flow::interface10a::overwrite_node< T >::reset_node().
                                                             { return false; }
template<typename T, typename M = spin_rw_mutex> bool tbb::flow::interface10::internal::successor_cache< T, M >::empty () inline
Definition at line 351 of file flow_graph.h.
Referenced by tbb::flow::interface10::limiter_node< T >::check_conditions(), tbb::flow::interface10::internal::key_from_message_body< K &, T >::operator()(), tbb::flow::interface10::limiter_node< T >::register_predecessor(), and tbb::flow::interface10::limiter_node< T >::register_successor().
                                                             { return false; }
template<typename T, typename M = spin_rw_mutex> void tbb::flow::interface10::internal::successor_cache< T, M >::register_successor (successor_type & r) inline
Definition at line 335 of file flow_graph.h.
Referenced by tbb::flow::interface10::broadcast_node< T >::register_successor(), tbb::flow::interface10::limiter_node< T >::register_successor(), tbb::flow::interface10a::overwrite_node< T >::register_successor(), and tbb::flow::interface10::internal::unfolded_join_node< 5, key_matching_port, OutputTuple, key_matching< K, KHash > >::unfolded_join_node().
       :
template<typename T, typename M = spin_rw_mutex> void tbb::flow::interface10::internal::successor_cache< T, M >::remove_successor (successor_type & r) inline
Definition at line 340 of file flow_graph.h.
Referenced by tbb::flow::interface10::broadcast_node< T >::remove_successor(), tbb::flow::interface10::limiter_node< T >::remove_successor(), and tbb::flow::interface10a::overwrite_node< T >::remove_successor().
       :
     typedef untyped_sender predecessor_type;
     virtual ~untyped_receiver() {}
     template<typename X>
template<typename T, typename M = spin_rw_mutex> void tbb::flow::interface10::internal::successor_cache< T, M >::set_owner (owner_type * owner) inline
Definition at line 331 of file flow_graph.h.
Referenced by tbb::flow::interface10::broadcast_node< T >::broadcast_node(), tbb::flow::interface10::buffer_node< T, A >::buffer_node(), tbb::flow::interface10::limiter_node< T >::limiter_node(), tbb::flow::interface10a::overwrite_node< T >::overwrite_node(), and tbb::flow::interface10::internal::join_node_base< JP, InputTuple, OutputTuple >::try_get().
Member Data Documentation
template<typename T, typename M = spin_rw_mutex> mutex_type tbb::flow::interface10::internal::successor_cache< T, M >::my_mutex protected
Definition at line 282 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> owner_type* tbb::flow::interface10::internal::successor_cache< T, M >::my_owner protected
Definition at line 299 of file flow_graph.h.
template<typename T, typename M = spin_rw_mutex> successors_type tbb::flow::interface10::internal::successor_cache< T, M >::my_successors protected
Definition at line 297 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.