Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface9::internal::start_for< Range, Body, Partitioner > Class Template Reference
tbb::interface9::internal::start_for< Range, Body, Partitioner > Class Template Reference
Algorithms
Task type used in parallel_for.
#include <parallel_for.h>
Public Member Functions
start_for (const Range &range, const Body &body, Partitioner &partitioner)
Constructor for root task.
start_for (start_for &parent_, typename Partitioner::split_type &split_obj)
Splitting constructor used to generate children.
start_for (start_for &parent_, const Range &r, depth_t d)
Construct right child from the given range as response to the demand.
void run_body (Range &r)
Run body for range, serves as callback for partitioner.
void offer_work (typename Partitioner::split_type &split_obj)
spawn right task, serves as callback for partitioner
void offer_work (const Range &r, depth_t d=0)
spawn right task, serves as callback for partitioner
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions
static void run (const Range &range, const Body &body, Partitioner &partitioner)
static void run (const Range &range, const Body &body, Partitioner &partitioner, task_group_context &context)
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Private Member Functions
task * execute () __TBB_override
execute task for parallel_for
void note_affinity (affinity_id id) __TBB_override
Update affinity info, if any.
Private Attributes
Range my_range
const Body my_body
Partitioner::task_partition_type my_partition
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
template<typename Range, typename Body, typename Partitioner>
class tbb::interface9::internal::start_for< Range, Body, Partitioner >
Task type used in parallel_for.
Definition at line 43 of file tbb/parallel_for.h.
Constructor & Destructor Documentation
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for (const Range & range, const Body & body, Partitioner & partitioner) inline
Constructor for root task.
Definition at line 56 of file tbb/parallel_for.h.
References tbb::internal::fgt_algorithm().
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::offer_work(), and tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
                                                                                     :
             my_range(range),
             my_body(body),
             my_partition(partitioner)
         {
             tbb::internal::fgt_algorithm(tbb::internal::PARALLEL_FOR_TASK, this, NULL);
         }
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for (start_for< Range, Body, Partitioner > & parent_, typename Partitioner::split_type & split_obj) inline
Splitting constructor used to generate children.
parent_ becomes left child. Newly constructed object is right child.
Definition at line 65 of file tbb/parallel_for.h.
References tbb::internal::fgt_algorithm().
                                                                                   :
             my_range(parent_.my_range, split_obj),
             my_body(parent_.my_body),
             my_partition(parent_.my_partition, split_obj)
         {
             my_partition.set_affinity(*this);
             tbb::internal::fgt_algorithm(tbb::internal::PARALLEL_FOR_TASK, this, (void *)&parent_);
         }
template<typename Range , typename Body , typename Partitioner > tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for (start_for< Range, Body, Partitioner > & parent_, const Range & r, depth_t d) inline
Construct right child from the given range as response to the demand.
parent_ remains left child. Newly constructed object is right child.
Definition at line 75 of file tbb/parallel_for.h.
References tbb::internal::fgt_algorithm().
                                                                    :
             my_range(r),
             my_body(parent_.my_body),
             my_partition(parent_.my_partition, split())
         {
             my_partition.set_affinity(*this);
             my_partition.align_depth( d );
             tbb::internal::fgt_algorithm(tbb::internal::PARALLEL_FOR_TASK, this, (void *)&parent_);
         }
Member Function Documentation
template<typename Range , typename Body , typename Partitioner > task * tbb::interface9::internal::start_for< Range, Body, Partitioner >::execute () private virtual
execute task for parallel_for
Implements tbb::task.
Definition at line 141 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::my_partition, and tbb::interface9::internal::start_for< Range, Body, Partitioner >::my_range.
{
         my_partition.check_being_stolen( *this );
         my_partition.execute(*this, my_range);
         return NULL;
     }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_for< Range, Body, Partitioner >::note_affinity (affinity_id id) inline private virtual
Update affinity info, if any.
Reimplemented from tbb::task.
Definition at line 50 of file tbb/parallel_for.h.
{
             my_partition.note_affinity( id );
         }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_for< Range, Body, Partitioner >::offer_work (typename Partitioner::split_type & split_obj) inline
spawn right task, serves as callback for partitioner
Definition at line 121 of file tbb/parallel_for.h.
References tbb::interface9::internal::allocate_sibling(), and tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for().
{
             spawn( *new( allocate_sibling(static_cast<task*>(this), sizeof(start_for)) ) start_for(*this, split_obj) );
         }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_for< Range, Body, Partitioner >::offer_work (const Range & r, depth_t d = 0) inline
spawn right task, serves as callback for partitioner
Definition at line 125 of file tbb/parallel_for.h.
References tbb::interface9::internal::allocate_sibling(), d, and tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for().
{
             spawn( *new( allocate_sibling(static_cast<task*>(this), sizeof(start_for)) ) start_for(*this, r, d) );
         }
template<typename Range , typename Body , typename Partitioner > static void tbb::interface9::internal::start_for< Range, Body, Partitioner >::run (const Range & range, const Body & body, Partitioner & partitioner) inline static
Definition at line 84 of file tbb/parallel_for.h.
References tbb::task::allocate_root(), tbb::task::context(), tbb::internal::fgt_begin_algorithm(), tbb::internal::fgt_end_algorithm(), tbb::task::spawn_root_and_wait(), and tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for().
Referenced by tbb::parallel_for().
{
             if( !range.empty() ) {
 #if !__TBB_TASK_GROUP_CONTEXT || TBB_JOIN_OUTER_TASK_GROUP
                 start_for& a = *new(task::allocate_root()) start_for(range,body,partitioner);
 #else
                 // Bound context prevents exceptions from body to affect nesting or sibling algorithms,
                 // and allows users to handle exceptions safely by wrapping parallel_for in the try-block.
                 task_group_context context(PARALLEL_FOR);
                 start_for& a = *new(task::allocate_root(context)) start_for(range,body,partitioner);
 #endif /* __TBB_TASK_GROUP_CONTEXT && !TBB_JOIN_OUTER_TASK_GROUP */
                 // REGION BEGIN
                 fgt_begin_algorithm( tbb::internal::PARALLEL_FOR_TASK, (void*)&context );
                 task::spawn_root_and_wait(a);
                 fgt_end_algorithm( (void*)&context );
                 // REGION END
             }
         }
template<typename Range , typename Body , typename Partitioner > static void tbb::interface9::internal::start_for< Range, Body, Partitioner >::run (const Range & range, const Body & body, Partitioner & partitioner, task_group_context & context) inline static
Definition at line 102 of file tbb/parallel_for.h.
References tbb::task::allocate_root(), tbb::internal::fgt_alg_begin_body(), tbb::internal::fgt_alg_end_body(), tbb::internal::fgt_begin_algorithm(), tbb::internal::fgt_end_algorithm(), tbb::interface9::internal::start_for< Range, Body, Partitioner >::my_body, tbb::interface9::internal::start_for< Range, Body, Partitioner >::run_body(), tbb::task::spawn_root_and_wait(), and tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for().
{
             if( !range.empty() ) {
                 start_for& a = *new(task::allocate_root(context)) start_for(range,body,partitioner);
                 // REGION BEGIN
                 fgt_begin_algorithm( tbb::internal::PARALLEL_FOR_TASK, (void*)&context );
                 task::spawn_root_and_wait(a);
                 fgt_end_algorithm( (void*)&context );
                 // END REGION
             }
         }
template<typename Range , typename Body , typename Partitioner > void tbb::interface9::internal::start_for< Range, Body, Partitioner >::run_body (Range & r) inline
Run body for range, serves as callback for partitioner.
Definition at line 114 of file tbb/parallel_for.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
             fgt_alg_begin_body( tbb::internal::PARALLEL_FOR_TASK, (void *)const_cast<Body*>(&(this->my_body)), (void*)this );
             my_body( r );
             fgt_alg_end_body( (void *)const_cast<Body*>(&(this->my_body)) );
         }
Member Data Documentation
template<typename Range , typename Body , typename Partitioner > const Body tbb::interface9::internal::start_for< Range, Body, Partitioner >::my_body private
Definition at line 45 of file tbb/parallel_for.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
template<typename Range , typename Body , typename Partitioner > Partitioner::task_partition_type tbb::interface9::internal::start_for< Range, Body, Partitioner >::my_partition private
Definition at line 46 of file tbb/parallel_for.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::execute().
template<typename Range , typename Body , typename Partitioner > Range tbb::interface9::internal::start_for< Range, Body, Partitioner >::my_range private
Definition at line 44 of file tbb/parallel_for.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::execute().
The documentation for this class was generated from the following file:
tbb/parallel_for.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.