Intel(R) Threading Building Blocks Doxygen Documentation: tbb::tick_count Class Reference
tbb::tick_count Class Reference
Timing
Absolute timestamp.
#include <tick_count.h>
Classes
class interval_t
Relative time interval.
Public Member Functions
tick_count ()
Construct an absolute timestamp initialized to zero.
Static Public Member Functions
static tick_count now ()
Return current time.
static double resolution ()
Return the resolution of the clock in seconds per tick.
Private Attributes
long long my_count
Friends
interval_t operator- (const tick_count &t1, const tick_count &t0)
Subtract two timestamps to get the time interval between.
Detailed Description
Absolute timestamp.
Definition at line 38 of file tick_count.h.
Constructor & Destructor Documentation
tbb::tick_count::tick_count () inline
Construct an absolute timestamp initialized to zero.
Definition at line 90 of file tick_count.h.
References now(), and tbb::tick_count::interval_t::operator-.
 : my_count(0) {};
Member Function Documentation
tick_count tbb::tick_count::now () inline static
Return current time.
Definition at line 105 of file tick_count.h.
References __TBB_ASSERT_EX, and my_count.
Referenced by tbb::internal::thread_sleep_v3(), and tick_count().
{
     tick_count result;
 #if _WIN32||_WIN64
     LARGE_INTEGER qpcnt;
     int rval = QueryPerformanceCounter(&qpcnt);
     __TBB_ASSERT_EX(rval, "QueryPerformanceCounter failed");
     result.my_count = qpcnt.QuadPart;
 #elif __linux__
     struct timespec ts;
     int status = clock_gettime( CLOCK_REALTIME, &ts );
     __TBB_ASSERT_EX( status==0, "CLOCK_REALTIME not supported" );
     result.my_count = static_cast<long long>(1000000000UL)*static_cast<long long>(ts.tv_sec) + static_cast<long long>(ts.tv_nsec);
 #else /* generic Unix */
     struct timeval tv;
     int status = gettimeofday(&tv, NULL);
     __TBB_ASSERT_EX( status==0, "gettimeofday failed" );
     result.my_count = static_cast<long long>(1000000)*static_cast<long long>(tv.tv_sec) + static_cast<long long>(tv.tv_usec);
 #endif /*(choice of OS) */
     return result;
 }
static double tbb::tick_count::resolution () inline static
Return the resolution of the clock in seconds per tick.
Definition at line 99 of file tick_count.h.
References tbb::tick_count::interval_t::ticks_per_second().
Referenced by tbb::tick_count::interval_t::seconds().
 { return 1.0 / interval_t::ticks_per_second(); }
Friends And Related Function Documentation
interval_t operator- (const tick_count & t1, const tick_count & t0) friend
Subtract two timestamps to get the time interval between.
Definition at line 130 of file tick_count.h.
{
     return tick_count::interval_t( t1.my_count-t0.my_count );
 }
Member Data Documentation
long long tbb::tick_count::my_count private
Definition at line 102 of file tick_count.h.
Referenced by now(), and tbb::operator-().
The documentation for this class was generated from the following file:
tick_count.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.