Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal::while_group_task< Body > Class Template Reference
tbb::internal::while_group_task< Body > Class Template Reference
Algorithms
For internal use only.
#include <parallel_while.h>
Private Member Functions
while_group_task (const Body &body)
task * execute () __TBB_override
Should be overridden by derived classes.
Private Attributes
const Body & my_body
size_t size
Body::argument_type my_arg [max_arg_size]
Static Private Attributes
static const size_t max_arg_size = 4
Friends
template<typename Stream , typename Body_ >
class while_task
Additional Inherited Members
Public Types inherited from tbb::task
enum state_type {
executing, reexecute, ready, allocated,
freed, recycle
}
Enumeration of task states that the scheduler considers.
typedef internal::affinity_id affinity_id
An id as used for specifying affinity.
Public Member Functions inherited from tbb::task
virtual ~task ()
Destructor.
internal::allocate_continuation_proxy & allocate_continuation ()
Returns proxy for overloaded new that allocates a continuation task of *this.
internal::allocate_child_proxy & allocate_child ()
Returns proxy for overloaded new that allocates a child task of *this.
void recycle_as_continuation ()
Change this to be a continuation of its former self.
void recycle_as_safe_continuation ()
Recommended to use, safe variant of recycle_as_continuation.
void recycle_as_child_of (task &new_parent)
Change this to be a child of new_parent.
void recycle_to_reexecute ()
Schedule this for reexecution after current execute() returns.
void set_ref_count (int count)
Set reference count.
void increment_ref_count ()
Atomically increment reference count.
int add_ref_count (int count)
Atomically adds to reference count and returns its new value.
int decrement_ref_count ()
Atomically decrement reference count and returns its new value.
void spawn_and_wait_for_all (task &child)
Similar to spawn followed by wait_for_all, but more efficient.
void __TBB_EXPORTED_METHOD spawn_and_wait_for_all (task_list &list)
Similar to spawn followed by wait_for_all, but more efficient.
void wait_for_all ()
Wait for reference count to become one, and set reference count to zero.
task * parent () const
task on whose behalf this task is working, or NULL if this is a root.
void set_parent (task *p)
sets parent task pointer to specified value
task_group_context * context ()
This method is deprecated and will be removed in the future.
task_group_context * group ()
Pointer to the task group descriptor.
bool is_stolen_task () const
True if task was stolen from the task pool of another thread.
state_type state () const
Current execution state.
int ref_count () const
The internal reference count.
bool __TBB_EXPORTED_METHOD is_owned_by_current_thread () const
Obsolete, and only retained for the sake of backward compatibility. Always returns true.
void set_affinity (affinity_id id)
Set affinity for this task.
affinity_id affinity () const
Current affinity of this task.
virtual void __TBB_EXPORTED_METHOD note_affinity (affinity_id id)
Invoked by scheduler to notify task that it ran on unexpected thread.
void __TBB_EXPORTED_METHOD change_group (task_group_context &ctx)
Moves this task from its current group into another one.
bool cancel_group_execution ()
Initiates cancellation of all tasks in this cancellation group and its subordinate groups.
bool is_cancelled () const
Returns true if the context has received cancellation request.
void set_group_priority (priority_t p)
Changes priority of the task group this task belongs to.
priority_t group_priority () const
Retrieves current priority of the task group this task belongs to.
Static Public Member Functions inherited from tbb::task
static internal::allocate_root_proxy allocate_root ()
Returns proxy for overloaded new that allocates a root task.
static internal::allocate_root_with_context_proxy allocate_root (task_group_context &ctx)
Returns proxy for overloaded new that allocates a root task associated with user supplied context.
static void spawn_root_and_wait (task &root)
Spawn task allocated by allocate_root, wait for it to complete, and deallocate it.
static void spawn_root_and_wait (task_list &root_list)
Spawn root tasks on list and wait for all of them to finish.
static void enqueue (task &t)
Enqueue task for starvation-resistant execution.
static void enqueue (task &t, priority_t p)
Enqueue task for starvation-resistant execution on the specified priority level.
static task &__TBB_EXPORTED_FUNC self ()
The innermost task being executed or destroyed by the current thread at the moment.
Protected Member Functions inherited from tbb::task
task ()
Default constructor.
Detailed Description
template<typename Body>
class tbb::internal::while_group_task< Body >
For internal use only.
Unpacks a block of iterations.
Definition at line 59 of file parallel_while.h.
Constructor & Destructor Documentation
template<typename Body > tbb::internal::while_group_task< Body >::while_group_task (const Body & body) inline private
Definition at line 64 of file parallel_while.h.
 : my_body(body), size(0) {}
Member Function Documentation
template<typename Body > task* tbb::internal::while_group_task< Body >::execute () inline private virtual
Should be overridden by derived classes.
Implements tbb::task.
Definition at line 65 of file parallel_while.h.
References __TBB_ASSERT, tbb::task::allocate_child(), tbb::task_list::push_back(), tbb::task::set_ref_count(), and tbb::task::spawn_and_wait_for_all().
{
             typedef while_iteration_task<Body> iteration_type;
             __TBB_ASSERT( size>0, NULL );
             task_list list;
             task* t;
             size_t k=0;
             for(;;) {
                 t = new( allocate_child() ) iteration_type(my_arg[k],my_body);
                 if( ++k==size ) break;
                 list.push_back(*t);
             }
             set_ref_count(int(k+1));
             spawn(list);
             spawn_and_wait_for_all(*t);
             return NULL;
         }
Friends And Related Function Documentation
template<typename Body > template<typename Stream , typename Body_ > friend class while_task friend
Definition at line 81 of file parallel_while.h.
Member Data Documentation
template<typename Body > const size_t tbb::internal::while_group_task< Body >::max_arg_size = 4 static private
Definition at line 60 of file parallel_while.h.
template<typename Body > Body::argument_type tbb::internal::while_group_task< Body >::my_arg[max_arg_size] private
Definition at line 63 of file parallel_while.h.
template<typename Body > const Body& tbb::internal::while_group_task< Body >::my_body private
Definition at line 61 of file parallel_while.h.
template<typename Body > size_t tbb::internal::while_group_task< Body >::size private
Definition at line 62 of file parallel_while.h.
The documentation for this class was generated from the following file:
parallel_while.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.