Intel(R) Threading Building Blocks Doxygen Documentation: gcc_generic.h File Reference
gcc_generic.h File Reference
#include <stdint.h>
#include <unistd.h>
Namespaces
tbb
The graph class.
tbb::internal
Identifiers declared inside namespace internal should never be used directly by client code.
tbb::internal::gcc_builtins
Macros
#define __TBB_WORDSIZE __SIZEOF_POINTER__
#define __TBB_ENDIANNESS __TBB_ENDIAN_DETECT
#define __TBB_acquire_consistency_helper() __sync_synchronize()
#define __TBB_release_consistency_helper() __sync_synchronize()
#define __TBB_full_memory_fence() __sync_synchronize()
#define __TBB_control_consistency_helper() __sync_synchronize()
#define __TBB_MACHINE_DEFINE_ATOMICS(S, T)
#define __TBB_USE_GENERIC_FETCH_STORE 1
#define __TBB_USE_GENERIC_HALF_FENCED_LOAD_STORE 1
#define __TBB_USE_GENERIC_RELAXED_LOAD_STORE 1
#define __TBB_USE_GENERIC_SEQUENTIAL_CONSISTENCY_LOAD_STORE 1
#define __TBB_AtomicOR(P, V) __TBB_machine_or(P,V)
#define __TBB_AtomicAND(P, V) __TBB_machine_and(P,V)
#define __TBB_TryLockByte __TBB_machine_try_lock_byte
#define __TBB_UnlockByte __TBB_machine_unlock_byte
#define __TBB_Log2(V) __TBB_machine_lg(V)
Typedefs
typedef unsigned char __TBB_Flag
typedef __TBB_atomic __TBB_Flag __TBB_atomic_flag
Functions
static void __TBB_machine_or (volatile void *ptr, uintptr_t addend)
static void __TBB_machine_and (volatile void *ptr, uintptr_t addend)
bool __TBB_machine_try_lock_byte (__TBB_atomic_flag &flag)
void __TBB_machine_unlock_byte (__TBB_atomic_flag &flag)
int tbb::internal::gcc_builtins::clz (unsigned int x)
int tbb::internal::gcc_builtins::clz (unsigned long int x)
int tbb::internal::gcc_builtins::clz (unsigned long long int x)
static intptr_t __TBB_machine_lg (uintptr_t x)
Macro Definition Documentation
#define __TBB_acquire_consistency_helper () __sync_synchronize()
As this generic implementation has absolutely no information about underlying hardware, its performance most likely will be sub-optimal because of full memory fence usages where a more lightweight synchronization means (or none at all) could suffice. Thus if you use this header to enable TBB on a new platform, consider forking it and relaxing below helpers as appropriate.
Definition at line 61 of file gcc_generic.h.
Referenced by tbb::internal::__TBB_FetchAndStoreGeneric().
#define __TBB_AtomicAND (P, V) __TBB_machine_and(P,V)
Definition at line 212 of file gcc_generic.h.
#define __TBB_AtomicOR (P, V) __TBB_machine_or(P,V)
Definition at line 211 of file gcc_generic.h.
#define __TBB_control_consistency_helper () __sync_synchronize()
Definition at line 64 of file gcc_generic.h.
Referenced by tbb::queuing_mutex::scoped_lock::acquire(), tbb::queuing_rw_mutex::scoped_lock::acquire(), tbb::internal::generic_scheduler::get_task(), tbb::internal::mail_outbox::internal_pop(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::internal::custom_scheduler< SchedulerTraits >::receive_or_steal_task(), tbb::internal::generic_scheduler::steal_task_from(), tbb::internal::custom_scheduler< SchedulerTraits >::tally_completion_of_predecessor(), and tbb::queuing_rw_mutex::scoped_lock::upgrade_to_writer().
#define __TBB_ENDIANNESS __TBB_ENDIAN_DETECT
FPU control setting not available for non-Intel architectures on Android
Definition at line 50 of file gcc_generic.h.
#define __TBB_full_memory_fence () __sync_synchronize()
Definition at line 63 of file gcc_generic.h.
Referenced by tbb::internal::__TBB_FetchAndStoreGeneric(), and tbb::atomic_fence().
#define __TBB_Log2 (V) __TBB_machine_lg(V)
Definition at line 229 of file gcc_generic.h.
#define __TBB_MACHINE_DEFINE_ATOMICS (S, T)
Value:
inline T __TBB_machine_cmpswp##S(volatile void *ptr, T value, T comparand) {                    \
    return __sync_val_compare_and_swap(reinterpret_cast<volatile T *>(ptr),comparand,value);      \
}                                                                                                 \
inline T __TBB_machine_fetchadd##S(volatile void *ptr, T value) {                               \
    return __sync_fetch_and_add(reinterpret_cast<volatile T *>(ptr),value);                       \
}
Definition at line 66 of file gcc_generic.h.
#define __TBB_release_consistency_helper () __sync_synchronize()
Definition at line 62 of file gcc_generic.h.
Referenced by tbb::internal::__TBB_FetchAndStoreGeneric().
#define __TBB_TryLockByte __TBB_machine_try_lock_byte
Definition at line 214 of file gcc_generic.h.
#define __TBB_UnlockByte __TBB_machine_unlock_byte
Definition at line 215 of file gcc_generic.h.
Referenced by tbb::spin_mutex::scoped_lock::internal_release(), tbb::spin_mutex::scoped_lock::release(), tbb::internal::__TBB_InitOnce::unlock(), tbb::spin_mutex::unlock(), and tbb::spin_mutex::scoped_lock::~scoped_lock().
#define __TBB_USE_GENERIC_FETCH_STORE 1
Definition at line 74 of file gcc_generic.h.
#define __TBB_USE_GENERIC_HALF_FENCED_LOAD_STORE 1
Definition at line 116 of file gcc_generic.h.
#define __TBB_USE_GENERIC_RELAXED_LOAD_STORE 1
Definition at line 117 of file gcc_generic.h.
#define __TBB_USE_GENERIC_SEQUENTIAL_CONSISTENCY_LOAD_STORE 1
Definition at line 118 of file gcc_generic.h.
#define __TBB_WORDSIZE __SIZEOF_POINTER__
Definition at line 30 of file gcc_generic.h.
Typedef Documentation
typedef __TBB_atomic __TBB_Flag __TBB_atomic_flag
Definition at line 110 of file gcc_generic.h.
typedef unsigned char __TBB_Flag
Definition at line 109 of file gcc_generic.h.
Function Documentation
static void __TBB_machine_and (volatile void * ptr, uintptr_t addend) inline static
Definition at line 124 of file gcc_generic.h.
Referenced by __TBB_machine_unlock_byte().
{
     __sync_fetch_and_and(reinterpret_cast<volatile uintptr_t *>(ptr),addend);
 }
static intptr_t __TBB_machine_lg (uintptr_t x) inline static
Definition at line 224 of file gcc_generic.h.
References tbb::internal::gcc_builtins::clz().
{
     // If P is a power of 2 and x<P, then (P-1)-x == (P-1) XOR x
     return (sizeof(x)*8 - 1) ^ tbb::internal::gcc_builtins::clz(x);
 }
static void __TBB_machine_or (volatile void * ptr, uintptr_t addend) inline static
Definition at line 120 of file gcc_generic.h.
Referenced by __TBB_machine_unlock_byte().
{
     __sync_fetch_and_or(reinterpret_cast<volatile uintptr_t *>(ptr),addend);
 }
bool __TBB_machine_try_lock_byte (__TBB_atomic_flag & flag) inline
Definition at line 128 of file gcc_generic.h.
Referenced by __TBB_machine_unlock_byte().
{
     return __sync_lock_test_and_set(&flag,1)==0;
 }
void __TBB_machine_unlock_byte (__TBB_atomic_flag & flag) inline
Definition at line 132 of file gcc_generic.h.
References __TBB_compiler_fence, __TBB_machine_and(), __TBB_machine_or(), __TBB_machine_try_lock_byte(), tbb::load(), tbb::internal::machine_load_store< T, S >::load_with_acquire(), tbb::store(), tbb::internal::machine_load_store< T, S >::store_with_release(), and value.
{
     __sync_lock_release(&flag);
 }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.