Intel(R) Threading Building Blocks Doxygen Documentation: _flow_graph_node_impl.h File Reference
_flow_graph_node_impl.h File Reference
#include "_flow_graph_item_buffer_impl.h"
Classes
class internal::function_input_queue< T, A >
class internal::function_input_base< Input, Policy, A, ImplType >
Input and scheduling for a function node that takes a type Input as input.
class internal::function_input_base< Input, Policy, A, ImplType >::operation_type
class internal::function_input< Input, Output, Policy, A >
Implements methods for a function node that takes a type Input as input and sends.
struct internal::clear_element< N >
struct internal::clear_element< 1 >
class internal::multifunction_input< Input, OutputPortSet, Policy, A >
Implements methods for a function node that takes a type Input as input.
struct internal::emit_element< N >
struct internal::emit_element< 1 >
class internal::continue_input< Output, Policy >
Implements methods for an executable node that takes continue_msg as input.
class internal::function_output< Output >
Implements methods for both executable and function nodes that puts Output to its successors.
class internal::multifunction_output< Output >
Namespaces
internal
Macros
#define __TBB__flow_graph_node_impl_H
Functions
template<size_t N, typename MOP >
tbb::flow::tuple_element< N, typename MOP::output_ports_type >::type & output_port (MOP &op)
void check_task_and_spawn (graph &g, task *t)
template<typename CompositeType >
void add_nodes_impl (CompositeType *, bool)
template<typename CompositeType , typename NodeType1 , typename... NodeTypes>
void add_nodes_impl (CompositeType *c_node, bool visible, const NodeType1 &n1, const NodeTypes &...n)
Macro Definition Documentation
#define __TBB__flow_graph_node_impl_H
Definition at line 23 of file flow_graph.h.
Function Documentation
template<typename CompositeType > void internal::add_nodes_impl (CompositeType * , bool)
Definition at line 883 of file _flow_graph_node_impl.h.
Referenced by add_nodes_impl().
 {}
template<typename CompositeType , typename NodeType1 , typename... NodeTypes> void internal::add_nodes_impl (CompositeType * c_node, bool visible, const NodeType1 & n1, const NodeTypes &... n)
Definition at line 886 of file _flow_graph_node_impl.h.
References add_nodes_impl(), addr, and tbb::internal::fgt_alias_port().
{
         void *addr = const_cast<NodeType1 *>(&n1);
         fgt_alias_port(c_node, addr, visible);
         add_nodes_impl(c_node, visible, n...);
     }
void internal::check_task_and_spawn (graph & g, task * t) inline
Definition at line 652 of file _flow_graph_node_impl.h.
References tbb::flow::interface10::internal::spawn_in_graph_arena(), and tbb::flow::internal::SUCCESSFULLY_ENQUEUED.
Referenced by internal::emit_element< N >::emit_this(), and internal::emit_element< 1 >::emit_this().
{
         if (t && t != SUCCESSFULLY_ENQUEUED) {
             internal::spawn_in_graph_arena(g, *t);
         }
     }
template<size_t N, typename MOP > tbb::flow::tuple_element<N, typename MOP::output_ports_type>::type& internal::output_port (MOP & op)
Definition at line 648 of file _flow_graph_node_impl.h.
{
         return tbb::flow::get<N>(op.output_ports());
     }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.