Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10a::write_once_node< T > Class Template Reference
tbb::flow::interface10a::write_once_node< T > Class Template Reference
#include <flow_graph.h>
Public Types
typedef T input_type
typedef T output_type
typedef overwrite_node< T > base_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
Public Types inherited from tbb::flow::interface10a::overwrite_node< T >
typedef T input_type
typedef T output_type
typedef receiver< input_type >::predecessor_type predecessor_type
typedef sender< output_type >::successor_type successor_type
Public Types inherited from tbb::flow::interface10::receiver< T >
typedef T input_type
The input type of this receiver.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_receiver
typedef untyped_sender predecessor_type
The predecessor type for this node.
Public Types inherited from tbb::flow::interface10::sender< T >
typedef T output_type
The output type of this sender.
typedef internal::async_helpers< T >::filtered_type filtered_type
Public Types inherited from tbb::flow::interface10::internal::untyped_sender
typedef untyped_receiver successor_type
The successor type for this node.
Public Member Functions
write_once_node (graph &g)
Constructor.
write_once_node (const write_once_node &src)
Copy constructor: call base class copy constructor.
Public Member Functions inherited from tbb::flow::interface10a::overwrite_node< T >
overwrite_node (graph &g)
overwrite_node (const overwrite_node &src)
Copy constructor; doesn't take anything from src; default won't work.
~overwrite_node ()
bool register_successor (successor_type &s) __TBB_override
Add a new successor to this node.
bool remove_successor (successor_type &s) __TBB_override
Removes a successor from this node.
bool try_get (input_type &v) __TBB_override
Request an item from the sender.
bool try_reserve (T &v) __TBB_override
Reserves an item.
bool try_release () __TBB_override
Releases the reserved item.
bool try_consume () __TBB_override
Consumes the reserved item.
bool is_valid ()
void clear ()
Public Member Functions inherited from tbb::flow::interface10::graph_node
graph_node (graph &g)
virtual ~graph_node ()
Public Member Functions inherited from tbb::flow::interface10::receiver< T >
bool try_put (const typename internal::async_helpers< T >::filtered_type &t)
Put an item to the receiver.
bool try_put (const typename internal::async_helpers< T >::async_type &t)
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
virtual ~untyped_receiver ()
Destructor.
template<typename X >
bool try_put (const X &t)
Put an item to the receiver.
virtual bool register_predecessor (predecessor_type &)
Add a predecessor to the node.
virtual bool remove_predecessor (predecessor_type &)
Remove a predecessor from the node.
Public Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
virtual ~untyped_sender ()
Protected Member Functions
task * try_put_task (const T &v) __TBB_override
Put item to successor; return task to run the successor if possible.
Protected Member Functions inherited from tbb::flow::interface10a::overwrite_node< T >
task * try_put_task_impl (const input_type &v)
graph & graph_reference () __TBB_override
void reset_receiver (reset_flags) __TBB_override
put receiver back in initial state
void reset_node (reset_flags f) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::receiver< T >
virtual task * try_put_task_wrapper (const void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_receiver
template<typename X >
task * try_put_task (const X &t)
virtual bool is_continue_receiver ()
Protected Member Functions inherited from tbb::flow::interface10::sender< T >
virtual bool try_get_wrapper (void *p, bool is_async) __TBB_override
virtual bool try_reserve_wrapper (void *p, bool is_async) __TBB_override
Protected Member Functions inherited from tbb::flow::interface10::internal::untyped_sender
template<typename X >
bool try_get (X &t)
Request an item from the sender.
template<typename X >
bool try_reserve (X &t)
Reserves an item in the sender.
Friends
template<typename R , typename B >
class run_and_put_task
template<typename X , typename Y >
class internal::broadcast_cache
template<typename X , typename Y >
class internal::round_robin_cache
Additional Inherited Members
Protected Attributes inherited from tbb::flow::interface10a::overwrite_node< T >
spin_mutex my_mutex
internal::broadcast_cache< input_type, null_rw_mutex > my_successors
input_type my_buffer
bool my_buffer_is_valid
Protected Attributes inherited from tbb::flow::interface10::graph_node
graph & my_graph
graph_node * next
graph_node * prev
Detailed Description
template<typename T>
class tbb::flow::interface10a::write_once_node< T >
Definition at line 3861 of file flow_graph.h.
Member Typedef Documentation
template<typename T > typedef overwrite_node<T> tbb::flow::interface10a::write_once_node< T >::base_type
Definition at line 3865 of file flow_graph.h.
template<typename T > typedef T tbb::flow::interface10a::write_once_node< T >::input_type
Definition at line 3863 of file flow_graph.h.
template<typename T > typedef T tbb::flow::interface10a::write_once_node< T >::output_type
Definition at line 3864 of file flow_graph.h.
template<typename T > typedef receiver<input_type>::predecessor_type tbb::flow::interface10a::write_once_node< T >::predecessor_type
Definition at line 3866 of file flow_graph.h.
template<typename T > typedef sender<output_type>::successor_type tbb::flow::interface10a::write_once_node< T >::successor_type
Definition at line 3867 of file flow_graph.h.
Constructor & Destructor Documentation
template<typename T > tbb::flow::interface10a::write_once_node< T >::write_once_node (graph & g) inline explicit
Constructor.
Definition at line 3870 of file flow_graph.h.
References tbb::internal::fgt_node(), and tbb::flow::interface10::graph_node::my_graph.
                                        : base_type(g) {
         tbb::internal::fgt_node( tbb::internal::FLOW_WRITE_ONCE_NODE, &(this->my_graph),
                                  static_cast<receiver<input_type> *>(this),
                                  static_cast<sender<output_type> *>(this) );
     }
template<typename T > tbb::flow::interface10a::write_once_node< T >::write_once_node (const write_once_node< T > & src) inline
Copy constructor: call base class copy constructor.
Definition at line 3877 of file flow_graph.h.
References __TBB_override, tbb::internal::fgt_node(), tbb::internal::fgt_node_desc(), and tbb::flow::interface10::graph_node::my_graph.
                                                   : base_type(src) {
         tbb::internal::fgt_node( tbb::internal::FLOW_WRITE_ONCE_NODE, &(this->my_graph),
                                  static_cast<receiver<input_type> *>(this),
                                  static_cast<sender<output_type> *>(this) );
     }
Member Function Documentation
template<typename T > task* tbb::flow::interface10a::write_once_node< T >::try_put_task (const T & t) inline protected virtual
Put item to successor; return task to run the successor if possible.
Reimplemented from tbb::flow::interface10a::overwrite_node< T >.
Definition at line 3893 of file flow_graph.h.
References tbb::flow::interface10::internal::cast_to(), tbb::flow::interface10::copy_body(), input_port(), tbb::flow::interface10::internal::is_a(), tbb::flow::interface10::make_edge(), tbb::flow::internal::no_priority, tbb::flow::interface10::internal::output_port(), tbb::flow::interface10::port_ref(), tbb::flow::interface10::remove_edge(), tbb::flow::interface10::rf_clear_edges, tbb::flow::interface10::rf_reset_bodies, and tbb::flow::interface10::rf_reset_protocol.
{
         spin_mutex::scoped_lock l( this->my_mutex );
         return this->my_buffer_is_valid ? NULL : this->try_put_task_impl(v);
     }
Friends And Related Function Documentation
template<typename T > template<typename X , typename Y > friend class internal::broadcast_cache friend
Definition at line 3891 of file flow_graph.h.
template<typename T > template<typename X , typename Y > friend class internal::round_robin_cache friend
Definition at line 3892 of file flow_graph.h.
template<typename T > template<typename R , typename B > friend class run_and_put_task friend
Definition at line 3890 of file flow_graph.h.
The documentation for this class was generated from the following file:
flow_graph.h
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.