Intel(R) Threading Building Blocks Doxygen Documentation: msvc_ia32_common.h File Reference
msvc_ia32_common.h File Reference
#include <intrin.h>
Classes
class tbb::internal::cpu_ctl_env
Namespaces
tbb
The graph class.
tbb::internal
Identifiers declared inside namespace internal should never be used directly by client code.
tbb::internal::msvc_intrinsics
tbb::internal::msvc_inline_asm
Macros
#define __TBB_X86_MSVC_INLINE_ASM_AVAILABLE 1
#define __TBB_r(reg_name) e##reg_name
#define __TBB_W(name) name
#define __TBB_compiler_fence() __asm { __asm nop }
#define __TBB_full_memory_fence() __asm { __asm mfence }
#define __TBB_control_consistency_helper() __TBB_compiler_fence()
#define __TBB_acquire_consistency_helper() __TBB_compiler_fence()
#define __TBB_release_consistency_helper() __TBB_compiler_fence()
#define __TBB_Pause(V) tbb::internal::msvc_inline_asm::pause(V)
#define __TBB_SINGLE_PAUSE __asm pause
#define __TBB_Log2(V) tbb::internal::msvc_inline_asm::lg_bsr(V)
#define __TBB_AtomicOR(P, V) tbb::internal::msvc_inline_asm::lock_or(P,V)
#define __TBB_AtomicAND(P, V) tbb::internal::msvc_inline_asm::lock_and(P,V)
#define __TBB_time_stamp() __TBB_machine_time_stamp()
#define __TBB_CPU_CTL_ENV_PRESENT 1
#define __TBB_Yield() SwitchToThread()
Typedefs
typedef long tbb::internal::msvc_intrinsics::word
Functions
namespace msvc_inline_asm static inline void tbb::internal::pause (uintptr_t delay)
static uintptr_t tbb::internal::msvc_inline_asm::lg_bsr (uintptr_t i)
static void tbb::internal::msvc_inline_asm::lock_or (volatile void *operand, __int32 addend)
static void tbb::internal::msvc_inline_asm::lock_and (volatile void *operand, __int32 addend)
static tbb::internal::machine_tsc_t __TBB_machine_time_stamp ()
void __TBB_get_cpu_ctl_env (tbb::internal::cpu_ctl_env *ctl)
void __TBB_set_cpu_ctl_env (const tbb::internal::cpu_ctl_env *ctl)
__declspec (dllimport) int __stdcall SwitchToThread(void)
__int8 __TBB_EXPORTED_FUNC __TBB_machine_try_lock_elided (volatile void *ptr)
void __TBB_EXPORTED_FUNC __TBB_machine_unlock_elided (volatile void *ptr)
static void __TBB_machine_try_lock_elided_cancel ()
__int8 __TBB_EXPORTED_FUNC __TBB_machine_is_in_transaction ()
unsigned __int32 __TBB_EXPORTED_FUNC __TBB_machine_begin_transaction ()
void __TBB_EXPORTED_FUNC __TBB_machine_end_transaction ()
void __TBB_EXPORTED_FUNC __TBB_machine_transaction_conflict_abort ()
Macro Definition Documentation
#define __TBB_acquire_consistency_helper () __TBB_compiler_fence()
Definition at line 93 of file msvc_ia32_common.h.
#define __TBB_AtomicAND (P, V) tbb::internal::msvc_inline_asm::lock_and(P,V)
Definition at line 193 of file msvc_ia32_common.h.
#define __TBB_AtomicOR (P, V) tbb::internal::msvc_inline_asm::lock_or(P,V)
Definition at line 192 of file msvc_ia32_common.h.
#define __TBB_compiler_fence () __asm { __asm nop }
Definition at line 86 of file msvc_ia32_common.h.
#define __TBB_control_consistency_helper () __TBB_compiler_fence()
Definition at line 92 of file msvc_ia32_common.h.
#define __TBB_CPU_CTL_ENV_PRESENT 1
Definition at line 204 of file msvc_ia32_common.h.
#define __TBB_full_memory_fence () __asm { __asm mfence }
Definition at line 87 of file msvc_ia32_common.h.
#define __TBB_Log2 (V) tbb::internal::msvc_inline_asm::lg_bsr(V)
Definition at line 154 of file msvc_ia32_common.h.
#define __TBB_Pause (V) tbb::internal::msvc_inline_asm::pause(V)
Definition at line 123 of file msvc_ia32_common.h.
#define __TBB_r (reg_name) e##reg_name
Definition at line 45 of file msvc_ia32_common.h.
Referenced by __TBB_get_cpu_ctl_env(), __TBB_set_cpu_ctl_env(), tbb::internal::msvc_inline_asm::lg_bsr(), and tbb::internal::pause().
#define __TBB_release_consistency_helper () __TBB_compiler_fence()
Definition at line 94 of file msvc_ia32_common.h.
#define __TBB_SINGLE_PAUSE __asm pause
Definition at line 124 of file msvc_ia32_common.h.
Referenced by __TBB_machine_try_lock_elided_cancel().
#define __TBB_time_stamp () __TBB_machine_time_stamp()
Definition at line 201 of file msvc_ia32_common.h.
#define __TBB_W (name) name
Definition at line 46 of file msvc_ia32_common.h.
#define __TBB_X86_MSVC_INLINE_ASM_AVAILABLE 1
Definition at line 31 of file msvc_ia32_common.h.
#define __TBB_Yield () SwitchToThread()
Definition at line 249 of file msvc_ia32_common.h.
Function Documentation
__declspec (dllimport)
Referenced by tbb::internal::cpu_ctl_env::set_env().
void __TBB_get_cpu_ctl_env (tbb::internal::cpu_ctl_env * ctl) inline
Definition at line 208 of file msvc_ia32_common.h.
References __TBB_r.
Referenced by __TBB_set_cpu_ctl_env(), and tbb::internal::cpu_ctl_env::get_env().
{
         __asm {
             __asm mov     __TBB_r(ax), ctl
             __asm stmxcsr [__TBB_r(ax)]
             __asm fstcw   [__TBB_r(ax)+4]
         }
     }
unsigned __int32 __TBB_EXPORTED_FUNC __TBB_machine_begin_transaction ()
Referenced by __TBB_machine_try_lock_elided_cancel().
void __TBB_EXPORTED_FUNC __TBB_machine_end_transaction ()
Referenced by __TBB_machine_try_lock_elided_cancel().
__int8 __TBB_EXPORTED_FUNC __TBB_machine_is_in_transaction ()
Referenced by __TBB_machine_try_lock_elided_cancel().
static tbb::internal::machine_tsc_t __TBB_machine_time_stamp () inline static
Definition at line 198 of file msvc_ia32_common.h.
{
     return __rdtsc();
 }
void __TBB_EXPORTED_FUNC __TBB_machine_transaction_conflict_abort ()
Referenced by __TBB_machine_try_lock_elided_cancel().
__int8 __TBB_EXPORTED_FUNC __TBB_machine_try_lock_elided (volatile void * ptr)
static void __TBB_machine_try_lock_elided_cancel () inline static
Definition at line 264 of file msvc_ia32_common.h.
References __TBB_EXPORTED_FUNC, __TBB_machine_begin_transaction(), __TBB_machine_end_transaction(), __TBB_machine_is_in_transaction(), __TBB_machine_transaction_conflict_abort(), and __TBB_SINGLE_PAUSE.
 { __TBB_SINGLE_PAUSE; }
void __TBB_EXPORTED_FUNC __TBB_machine_unlock_elided (volatile void * ptr)
void __TBB_set_cpu_ctl_env (const tbb::internal::cpu_ctl_env * ctl) inline
Definition at line 215 of file msvc_ia32_common.h.
References __TBB_EXPORTED_FUNC, __TBB_get_cpu_ctl_env(), and __TBB_r.
Referenced by tbb::internal::cpu_ctl_env::set_env().
{
         __asm {
             __asm mov     __TBB_r(ax), ctl
             __asm ldmxcsr [__TBB_r(ax)]
             __asm fldcw   [__TBB_r(ax)+4]
         }
     }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.