Intel(R) Threading Building Blocks Doxygen Documentation: macos_common.h File Reference
macos_common.h File Reference
#include <sched.h>
#include <sys/types.h>
#include <sys/sysctl.h>
#include <libkern/OSAtomic.h>
Macros
#define __TBB_Yield() sched_yield()
#define __TBB_HardwareConcurrency() __TBB_macos_available_cpu()
#define __TBB_UnknownArchitecture 1
#define __TBB_machine_cmpswp8 __TBB_machine_cmpswp8_OsX
#define __TBB_WORDSIZE __SIZEOF_POINTER__
#define __TBB_ENDIANNESS __TBB_ENDIAN_UNSUPPORTED
#define __TBB_control_consistency_helper() OSMemoryBarrier()
#define __TBB_acquire_consistency_helper() OSMemoryBarrier()
#define __TBB_release_consistency_helper() OSMemoryBarrier()
#define __TBB_full_memory_fence() OSMemoryBarrier()
#define __TBB_USE_GENERIC_PART_WORD_CAS 1
#define __TBB_USE_GENERIC_PART_WORD_FETCH_ADD 1
#define __TBB_USE_GENERIC_FETCH_STORE 1
#define __TBB_USE_GENERIC_HALF_FENCED_LOAD_STORE 1
#define __TBB_USE_GENERIC_RELAXED_LOAD_STORE 1
#define __TBB_USE_GENERIC_SEQUENTIAL_CONSISTENCY_LOAD_STORE 1
Functions
static int __TBB_macos_available_cpu ()
static int64_t __TBB_machine_cmpswp8_OsX (volatile void *ptr, int64_t value, int64_t comparand)
static int32_t __TBB_machine_cmpswp4 (volatile void *ptr, int32_t value, int32_t comparand)
static int32_t __TBB_machine_fetchadd4 (volatile void *ptr, int32_t addend)
static int64_t __TBB_machine_fetchadd8 (volatile void *ptr, int64_t addend)
Macro Definition Documentation
#define __TBB_acquire_consistency_helper () OSMemoryBarrier()
Definition at line 96 of file macos_common.h.
#define __TBB_control_consistency_helper () OSMemoryBarrier()
As this generic implementation has absolutely no information about underlying hardware, its performance most likely will be sub-optimal because of full memory fence usages where a more lightweight synchronization means (or none at all) could suffice. Thus if you use this header to enable TBB on a new platform, consider forking it and relaxing below helpers as appropriate.
Definition at line 95 of file macos_common.h.
#define __TBB_ENDIANNESS __TBB_ENDIAN_UNSUPPORTED
Definition at line 87 of file macos_common.h.
#define __TBB_full_memory_fence () OSMemoryBarrier()
Definition at line 98 of file macos_common.h.
#define __TBB_HardwareConcurrency () __TBB_macos_available_cpu()
Definition at line 43 of file macos_common.h.
#define __TBB_machine_cmpswp8 __TBB_machine_cmpswp8_OsX
Definition at line 70 of file macos_common.h.
#define __TBB_release_consistency_helper () OSMemoryBarrier()
Definition at line 97 of file macos_common.h.
#define __TBB_UnknownArchitecture 1
Definition at line 48 of file macos_common.h.
#define __TBB_USE_GENERIC_FETCH_STORE 1
Definition at line 125 of file macos_common.h.
#define __TBB_USE_GENERIC_HALF_FENCED_LOAD_STORE 1
Definition at line 126 of file macos_common.h.
#define __TBB_USE_GENERIC_PART_WORD_CAS 1
Definition at line 123 of file macos_common.h.
#define __TBB_USE_GENERIC_PART_WORD_FETCH_ADD 1
Definition at line 124 of file macos_common.h.
#define __TBB_USE_GENERIC_RELAXED_LOAD_STORE 1
Definition at line 127 of file macos_common.h.
#define __TBB_USE_GENERIC_SEQUENTIAL_CONSISTENCY_LOAD_STORE 1
Definition at line 131 of file macos_common.h.
#define __TBB_WORDSIZE __SIZEOF_POINTER__
Definition at line 77 of file macos_common.h.
#define __TBB_Yield () sched_yield()
Definition at line 28 of file macos_common.h.
Function Documentation
static int32_t __TBB_machine_cmpswp4 (volatile void * ptr, int32_t value, int32_t comparand) inline static
Definition at line 100 of file macos_common.h.
References __TBB_ASSERT, address, and tbb::internal::is_aligned().
 {
     __TBB_ASSERT( tbb::internal::is_aligned(ptr,4), "address not properly aligned for macOS atomics");
     int32_t* address = (int32_t*)ptr;
     while( !OSAtomicCompareAndSwap32Barrier(comparand, value, address) ){
         int32_t snapshot = *address;
         if( snapshot!=comparand ) return snapshot;
     }
     return comparand;
 }
static int64_t __TBB_machine_cmpswp8_OsX (volatile void * ptr, int64_t value, int64_t comparand) inline static
Definition at line 55 of file macos_common.h.
References __TBB_ASSERT, address, and tbb::internal::is_aligned().
 {
     __TBB_ASSERT( tbb::internal::is_aligned(ptr,8), "address not properly aligned for macOS* atomics");
     int64_t* address = (int64_t*)ptr;
     while( !OSAtomicCompareAndSwap64Barrier(comparand, value, address) ){
 #if __TBB_WORDSIZE==8
         int64_t snapshot = *address;
 #else
         int64_t snapshot = OSAtomicAdd64( 0, address );
 #endif
         if( snapshot!=comparand ) return snapshot;
     }
     return comparand;
 }
static int32_t __TBB_machine_fetchadd4 (volatile void * ptr, int32_t addend) inline static
Definition at line 111 of file macos_common.h.
References __TBB_ASSERT, and tbb::internal::is_aligned().
 {
     __TBB_ASSERT( tbb::internal::is_aligned(ptr,4), "address not properly aligned for macOS atomics");
     return OSAtomicAdd32Barrier(addend, (int32_t*)ptr) - addend;
 }
static int64_t __TBB_machine_fetchadd8 (volatile void * ptr, int64_t addend) inline static
Definition at line 117 of file macos_common.h.
References __TBB_ASSERT, and tbb::internal::is_aligned().
 {
     __TBB_ASSERT( tbb::internal::is_aligned(ptr,8), "address not properly aligned for macOS atomics");
     return OSAtomicAdd64Barrier(addend, (int64_t*)ptr) - addend;
 }
static int __TBB_macos_available_cpu () inline static
Definition at line 35 of file macos_common.h.
References name, and size.
{
     int name[2] = {CTL_HW, HW_AVAILCPU};
     int ncpu;
     size_t size = sizeof(ncpu);
     sysctl( name, 2, &ncpu, &size, NULL, 0 );
     return ncpu;
 }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.