Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface9::gfx_offload Namespace Reference
tbb::flow::interface9::gfx_offload Namespace Reference
Typedefs
typedef GfxTaskId task_id_type
Functions
void throw_gfx_exception ()
void check_enqueue_retcode (task_id_type err)
void check_gfx_retcode (task_id_type err)
template<typename DataType , typename SizeType >
void share (DataType *p, SizeType n)
template<typename DataType >
void unshare (DataType *p)
template<typename T >
T * raw_data (gfx_buffer< T > &buffer)
template<typename T >
const T * raw_data (const gfx_buffer< T > &buffer)
template<typename T >
T & raw_data (T &data)
template<typename T >
const T & raw_data (const T &data)
template<typename F , typename... ArgType>
task_id_type run_kernel (F ptr, ArgType &...args)
void wait_for_task (task_id_type id)
Typedef Documentation
typedef GfxTaskId tbb::flow::interface9::gfx_offload::task_id_type
Definition at line 48 of file gfx_factory.h.
Function Documentation
void tbb::flow::interface9::gfx_offload::check_enqueue_retcode (task_id_type err) inline
Definition at line 63 of file gfx_factory.h.
References throw_gfx_exception().
Referenced by run_kernel().
{
         if (err == 0) {
             throw_gfx_exception();
         }
     }
void tbb::flow::interface9::gfx_offload::check_gfx_retcode (task_id_type err) inline
Definition at line 69 of file gfx_factory.h.
References throw_gfx_exception().
Referenced by share(), unshare(), and wait_for_task().
{
         if (err != GFX_SUCCESS) {
             throw_gfx_exception();
         }
     }
template<typename T > T* tbb::flow::interface9::gfx_offload::raw_data (gfx_buffer< T > & buffer)
Definition at line 88 of file gfx_factory.h.
References tbb::flow::interface9::gfx_buffer< T >::data().
Referenced by run_kernel().
 { return buffer.data(); }
template<typename T > const T* tbb::flow::interface9::gfx_offload::raw_data (const gfx_buffer< T > & buffer)
Definition at line 90 of file gfx_factory.h.
References tbb::flow::interface9::gfx_buffer< T >::data().
 { return buffer.data(); }
template<typename T > T& tbb::flow::interface9::gfx_offload::raw_data (T & data)
Definition at line 92 of file gfx_factory.h.
References data.
 { return data; }
template<typename T > const T& tbb::flow::interface9::gfx_offload::raw_data (const T & data)
Definition at line 94 of file gfx_factory.h.
References data.
 { return data; }
template<typename F , typename... ArgType> task_id_type tbb::flow::interface9::gfx_offload::run_kernel (F ptr, ArgType &... args)
Definition at line 98 of file gfx_factory.h.
References check_enqueue_retcode(), id, and raw_data().
Referenced by tbb::flow::interface9::gfx_factory::send_kernel().
{
         task_id_type id = _GFX_offload(ptr, raw_data(args)...);
         // Check if something during offload went wrong (ex: driver initialization failure)
         gfx_offload::check_enqueue_retcode(id);
         return id;
     }
template<typename DataType , typename SizeType > void tbb::flow::interface9::gfx_offload::share (DataType * p, SizeType n)
Definition at line 81 of file gfx_factory.h.
References check_gfx_retcode().
Referenced by tbb::flow::interface9::gfx_factory::share_data().
 { check_gfx_retcode(_GFX_share(p, sizeof(*p)*n)); }
void tbb::flow::interface9::gfx_offload::throw_gfx_exception () inline
Definition at line 57 of file gfx_factory.h.
Referenced by check_enqueue_retcode(), and check_gfx_retcode().
{
         std::string msg = "GFX error occurred: " + std::to_string(_GFX_get_last_error());
         std::cerr << msg << std::endl;
         throw msg;
     }
template<typename DataType > void tbb::flow::interface9::gfx_offload::unshare (DataType * p)
Definition at line 83 of file gfx_factory.h.
References check_gfx_retcode().
Referenced by tbb::flow::interface9::gfx_factory::unshare_data().
 { check_gfx_retcode(_GFX_unshare(p)); }
void tbb::flow::interface9::gfx_offload::wait_for_task (task_id_type id)
Definition at line 108 of file gfx_factory.h.
References check_gfx_retcode().
Referenced by tbb::flow::interface9::gfx_factory::callback().
 { check_gfx_retcode(_GFX_wait(id)); }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.