Intel(R) Threading Building Blocks Doxygen Documentation: IDs
IDs
Functions
ITT_INLINE __itt_id ITTAPI __itt_id_make (void *addr, unsigned long long extra) ITT_INLINE_ATTRIBUTE
A convenience function is provided to create an ID without domain control.
void ITTAPI __itt_id_create (const __itt_domain *domain, __itt_id id)
Create an instance of identifier. This establishes the beginning of the lifetime of an instance of the given ID in the trace. Once this lifetime starts, the ID can be used to tag named entity instances in calls such as __itt_task_begin, and to specify relationships among identified named entity instances, using the Relations APIs. Instance IDs are not domain specific!
void ITTAPI __itt_id_destroy (const __itt_domain *domain, __itt_id id)
Destroy an instance of identifier. This ends the lifetime of the current instance of the given ID value in the trace. Any relationships that are established after this lifetime ends are invalid. This call must be performed before the given ID value can be reused for a different named entity instance.
Variables
static const __itt_id __itt_null = { 0, 0, 0 }
Detailed Description
IDs group
Function Documentation
void ITTAPI __itt_id_create (const __itt_domain * domain, __itt_id id)
Create an instance of identifier. This establishes the beginning of the lifetime of an instance of the given ID in the trace. Once this lifetime starts, the ID can be used to tag named entity instances in calls such as __itt_task_begin, and to specify relationships among identified named entity instances, using the Relations APIs. Instance IDs are not domain specific!
Parameters
[in] domain The domain controlling the execution of this call.
[in] id The ID to create.
Referenced by __itt_id_make().
void ITTAPI __itt_id_destroy (const __itt_domain * domain, __itt_id id)
Destroy an instance of identifier. This ends the lifetime of the current instance of the given ID value in the trace. Any relationships that are established after this lifetime ends are invalid. This call must be performed before the given ID value can be reused for a different named entity instance.
Parameters
[in] domain The domain controlling the execution of this call.
[in] id The ID to destroy.
Referenced by __itt_id_make().
ITT_INLINE __itt_id ITTAPI __itt_id_make (void * addr, unsigned long long extra)
A convenience function is provided to create an ID without domain control.
This is a convenience function to initialize an __itt_id structure. This function does not affect the collector runtime in any way. After you make the ID with this function, you still must create it with the __itt_id_create function before using the ID to identify a named entity.
Parameters
[in] addr The address of object; high QWORD of the ID value.
[in] extra The extra data to unique identify object; low QWORD of the ID value.
Definition at line 1793 of file ittnotify.h.
References __itt_id_create(), __itt_id_destroy(), __itt_null, __itt_string_handle_createA(), __itt_string_handle_createW(), addr, id, id_destroy, and ITT_STUBV.
Referenced by tbb::internal::call_itt_notify_v5().
 {
     __itt_id id = __itt_null;
     id.d1 = (unsigned long long)((uintptr_t)addr);
     id.d2 = (unsigned long long)extra;
     id.d3 = (unsigned long long)0; /* Reserved. Must be zero */
     return id;
 }
Variable Documentation
const __itt_id __itt_null = { 0, 0, 0 } static
Definition at line 1779 of file ittnotify.h.
Referenced by __itt_id_make().
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.