Intel(R) Threading Building Blocks Doxygen Documentation: String Handles
String Handles
Macros
#define __itt_string_handle_create __itt_string_handle_createA
#define __itt_string_handle_create_ptr __itt_string_handle_createA_ptr
Functions
__itt_string_handle *ITTAPI __itt_string_handle_createA (const char *name)
Create a string handle. Create and return handle value that can be associated with a string. Consecutive calls to __itt_string_handle_create with the same name return the same value. Because the set of string handles is expected to remain static during the application's execution time, there is no mechanism to destroy a string handle. Any string handle can be accessed by any thread in the process, regardless of which thread created the string handle. This call is thread-safe.
__itt_string_handle *ITTAPI __itt_string_handle_createW (const wchar_t *name)
Detailed Description
String Handles group
Macro Definition Documentation
#define __itt_string_handle_create __itt_string_handle_createA
Definition at line 1903 of file ittnotify.h.
Referenced by tbb::internal::__TBB_InitOnce::remove_ref().
#define __itt_string_handle_create_ptr __itt_string_handle_createA_ptr
Definition at line 1904 of file ittnotify.h.
Function Documentation
__itt_string_handle* ITTAPI __itt_string_handle_createA (const char * name)
Create a string handle. Create and return handle value that can be associated with a string. Consecutive calls to __itt_string_handle_create with the same name return the same value. Because the set of string handles is expected to remain static during the application's execution time, there is no mechanism to destroy a string handle. Any string handle can be accessed by any thread in the process, regardless of which thread created the string handle. This call is thread-safe.
Parameters
[in] name The input string
Referenced by __itt_id_make(), and tbb::internal::__TBB_InitOnce::remove_ref().
__itt_string_handle* ITTAPI __itt_string_handle_createW (const wchar_t * name)
Referenced by __itt_id_make().
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.