Intel(R) Threading Building Blocks Doxygen Documentation: Algorithms
Algorithms
Classes
class tbb::blocked_range< Value >
A range over which to iterate.
class tbb::blocked_range2d< RowValue, ColValue >
A 2-dimensional range that models the Range concept.
class tbb::blocked_range3d< PageValue, RowValue, ColValue >
A 3-dimensional range that models the Range concept.
class tbb::interface9::internal::parallel_do_operator_selector< Body, Item >
For internal use only.
class tbb::interface9::internal::do_iteration_task< Body, Item >
For internal use only.
class tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >
For internal use only.
class tbb::interface9::internal::do_group_task_forward< Iterator, Body, Item >
For internal use only.
class tbb::interface9::internal::do_task_iter< Iterator, Body, Item >
For internal use only.
class tbb::interface9::internal::start_for< Range, Body, Partitioner >
Task type used in parallel_for.
class tbb::interface9::internal::finish_reduce< Body >
Task type used to combine the partial results of parallel_reduce.
class tbb::interface9::internal::start_reduce< Range, Body, Partitioner >
Task type used to split the work of parallel_reduce.
class tbb::interface9::internal::finish_deterministic_reduce< Body >
Task type used to combine the partial results of parallel_deterministic_reduce.
class tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >
Task type used to split the work of parallel_deterministic_reduce.
class tbb::internal::lambda_reduce_body< Range, Value, RealBody, Reduction >
Auxiliary class for parallel_reduce; for internal use only.
struct tbb::pre_scan_tag
Used to indicate that the initial scan is being performed.
struct tbb::final_scan_tag
Used to indicate that the final scan is being performed.
class tbb::internal::final_sum< Range, Body >
Performs final scan for a leaf.
class tbb::internal::sum_node< Range, Body >
Split work to be done in the scan.
class tbb::internal::finish_scan< Range, Body >
Combine partial results.
class tbb::internal::start_scan< Range, Body, Partitioner >
Initial task to split the work.
class tbb::interface9::internal::quick_sort_range< RandomAccessIterator, Compare >
Range used in quicksort to split elements into subranges based on a value.
class tbb::interface9::internal::quick_sort_pretest_body< RandomAccessIterator, Compare >
Body class used to test if elements in a range are presorted.
struct tbb::interface9::internal::quick_sort_body< RandomAccessIterator, Compare >
Body class used to sort elements in a range that is smaller than the grainsize.
class tbb::internal::while_iteration_task< Body >
For internal use only.
class tbb::internal::while_group_task< Body >
For internal use only.
class tbb::internal::while_task< Stream, Body >
For internal use only.
class tbb::parallel_while< Body >
Parallel iteration over a stream, with optional addition of more work.
class tbb::simple_partitioner
A simple partitioner.
class tbb::auto_partitioner
An auto partitioner.
class tbb::filter
A stage in a pipeline.
class tbb::thread_bound_filter
A stage in a pipeline served by a user thread.
class tbb::pipeline
A processing pipeline that applies filters to items.
class tbb::split
Dummy type that distinguishes splitting constructor from copy constructor.
Functions
template<typename Range , typename Body >
void tbb::serial::interface9::parallel_for (const Range &range, const Body &body)
Parallel iteration over range with default partitioner.
template<typename Range , typename Body >
void tbb::serial::interface9::parallel_for (const Range &range, const Body &body, const simple_partitioner &partitioner)
Parallel iteration over range with simple partitioner.
template<typename Range , typename Body >
void tbb::serial::interface9::parallel_for (const Range &range, const Body &body, const auto_partitioner &partitioner)
Parallel iteration over range with auto_partitioner.
template<typename Range , typename Body >
void tbb::serial::interface9::parallel_for (const Range &range, const Body &body, const static_partitioner &partitioner)
Parallel iteration over range with static_partitioner.
template<typename Range , typename Body >
void tbb::serial::interface9::parallel_for (const Range &range, const Body &body, affinity_partitioner &partitioner)
Parallel iteration over range with affinity_partitioner.
template<typename Iterator , typename Body , typename Item >
void tbb::interface9::internal::run_parallel_do (Iterator first, Iterator last, const Body &body, task_group_context &context)
For internal use only.
template<typename Iterator , typename Body , typename Item >
void tbb::interface9::internal::select_parallel_do (Iterator first, Iterator last, const Body &body, void(Body::*)(Item) const , task_group_context &context)
For internal use only.
template<typename Iterator , typename Body , typename Item , typename _Item >
void tbb::interface9::internal::select_parallel_do (Iterator first, Iterator last, const Body &body, void(Body::*)(Item, parallel_do_feeder< _Item > &) const , task_group_context &context)
For internal use only.
template<typename RandomAccessIterator , typename Compare >
void tbb::interface9::internal::parallel_quick_sort (RandomAccessIterator begin, RandomAccessIterator end, const Compare &comp)
Wrapper method to initiate the sort by calling parallel_for.
parallel_do
See also requirements on parallel_do Body.
template<typename Iterator , typename Body >
void tbb::parallel_do (Iterator first, Iterator last, const Body &body)
Parallel iteration over a range, with optional addition of more work.
template<typename Iterator , typename Body >
void tbb::parallel_do (Iterator first, Iterator last, const Body &body, task_group_context &context)
Parallel iteration over a range, with optional addition of more work and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_do (Range &rng, const Body &body)
template<typename Range , typename Body >
void tbb::parallel_do (const Range &rng, const Body &body)
template<typename Range , typename Body >
void tbb::parallel_do (Range &rng, const Body &body, task_group_context &context)
template<typename Range , typename Body >
void tbb::parallel_do (const Range &rng, const Body &body, task_group_context &context)
parallel_for
See also requirements on Range and parallel_for Body.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body)
Parallel iteration over range with default partitioner.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, const simple_partitioner &partitioner)
Parallel iteration over range with simple partitioner.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, const auto_partitioner &partitioner)
Parallel iteration over range with auto_partitioner.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, const static_partitioner &partitioner)
Parallel iteration over range with static_partitioner.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, affinity_partitioner &partitioner)
Parallel iteration over range with affinity_partitioner.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, task_group_context &context)
Parallel iteration over range with default partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, const simple_partitioner &partitioner, task_group_context &context)
Parallel iteration over range with simple partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, const auto_partitioner &partitioner, task_group_context &context)
Parallel iteration over range with auto_partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, const static_partitioner &partitioner, task_group_context &context)
Parallel iteration over range with static_partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_for (const Range &range, const Body &body, affinity_partitioner &partitioner, task_group_context &context)
Parallel iteration over range with affinity_partitioner and user-supplied context.
parallel_for_each
template<typename Iterator , typename Function >
void tbb::parallel_for_each (Iterator first, Iterator last, const Function &f, task_group_context &context)
Calls function f for all items from [first, last) interval using user-supplied context.
template<typename Range , typename Function >
void tbb::parallel_for_each (Range &rng, const Function &f, task_group_context &context)
Calls function f for all items from rng using user-supplied context.
template<typename Range , typename Function >
void tbb::parallel_for_each (const Range &rng, const Function &f, task_group_context &context)
Calls function f for all items from const rng user-supplied context.
template<typename Iterator , typename Function >
void tbb::parallel_for_each (Iterator first, Iterator last, const Function &f)
Uses default context.
template<typename Range , typename Function >
void tbb::parallel_for_each (Range &rng, const Function &f)
Uses default context.
template<typename Range , typename Function >
void tbb::parallel_for_each (const Range &rng, const Function &f)
Uses default context.
parallel_invoke
template<typename F0 , typename F1 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, tbb::task_group_context &context)
Executes a list of tasks in parallel and waits for all tasks to complete.
template<typename F0 , typename F1 , typename F2 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, tbb::task_group_context &context)
template<typename F0 , typename F1 , typename F2 , typename F3 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, tbb::task_group_context &context)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, tbb::task_group_context &context)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, tbb::task_group_context &context)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6, tbb::task_group_context &context)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6, const F7 &f7, tbb::task_group_context &context)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6, const F7 &f7, const F8 &f8, tbb::task_group_context &context)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 , typename F9 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6, const F7 &f7, const F8 &f8, const F9 &f9, tbb::task_group_context &context)
template<typename F0 , typename F1 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1)
template<typename F0 , typename F1 , typename F2 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2)
template<typename F0 , typename F1 , typename F2 , typename F3 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6, const F7 &f7)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6, const F7 &f7, const F8 &f8)
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 , typename F9 >
void tbb::parallel_invoke (const F0 &f0, const F1 &f1, const F2 &f2, const F3 &f3, const F4 &f4, const F5 &f5, const F6 &f6, const F7 &f7, const F8 &f8, const F9 &f9)
parallel_reduce
See also requirements on Range and parallel_reduce Body.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body)
Parallel iteration with reduction and default partitioner.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, const simple_partitioner &partitioner)
Parallel iteration with reduction and simple_partitioner.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, const auto_partitioner &partitioner)
Parallel iteration with reduction and auto_partitioner.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, const static_partitioner &partitioner)
Parallel iteration with reduction and static_partitioner.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, affinity_partitioner &partitioner)
Parallel iteration with reduction and affinity_partitioner.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, task_group_context &context)
Parallel iteration with reduction, default partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, const simple_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, simple partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, const auto_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, auto_partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, const static_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, static_partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_reduce (const Range &range, Body &body, affinity_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, affinity_partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction)
Parallel iteration with reduction and default partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const simple_partitioner &partitioner)
Parallel iteration with reduction and simple_partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const auto_partitioner &partitioner)
Parallel iteration with reduction and auto_partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const static_partitioner &partitioner)
Parallel iteration with reduction and static_partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, affinity_partitioner &partitioner)
Parallel iteration with reduction and affinity_partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, task_group_context &context)
Parallel iteration with reduction, default partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const simple_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, simple partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const auto_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, auto_partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const static_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, static_partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, affinity_partitioner &partitioner, task_group_context &context)
Parallel iteration with reduction, affinity_partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_deterministic_reduce (const Range &range, Body &body)
Parallel iteration with deterministic reduction and default simple partitioner.
template<typename Range , typename Body >
void tbb::parallel_deterministic_reduce (const Range &range, Body &body, const simple_partitioner &partitioner)
Parallel iteration with deterministic reduction and simple partitioner.
template<typename Range , typename Body >
void tbb::parallel_deterministic_reduce (const Range &range, Body &body, const static_partitioner &partitioner)
Parallel iteration with deterministic reduction and static partitioner.
template<typename Range , typename Body >
void tbb::parallel_deterministic_reduce (const Range &range, Body &body, task_group_context &context)
Parallel iteration with deterministic reduction, default simple partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_deterministic_reduce (const Range &range, Body &body, const simple_partitioner &partitioner, task_group_context &context)
Parallel iteration with deterministic reduction, simple partitioner and user-supplied context.
template<typename Range , typename Body >
void tbb::parallel_deterministic_reduce (const Range &range, Body &body, const static_partitioner &partitioner, task_group_context &context)
Parallel iteration with deterministic reduction, static partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_deterministic_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction)
Parallel iteration with deterministic reduction and default simple partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_deterministic_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const simple_partitioner &partitioner)
Parallel iteration with deterministic reduction and simple partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_deterministic_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const static_partitioner &partitioner)
Parallel iteration with deterministic reduction and static partitioner.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_deterministic_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, task_group_context &context)
Parallel iteration with deterministic reduction, default simple partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_deterministic_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const simple_partitioner &partitioner, task_group_context &context)
Parallel iteration with deterministic reduction, simple partitioner and user-supplied context.
template<typename Range , typename Value , typename RealBody , typename Reduction >
Value tbb::parallel_deterministic_reduce (const Range &range, const Value &identity, const RealBody &real_body, const Reduction &reduction, const static_partitioner &partitioner, task_group_context &context)
Parallel iteration with deterministic reduction, static partitioner and user-supplied context.
parallel_scan
See also requirements on Range and parallel_scan Body.
template<typename Range , typename Body >
void tbb::parallel_scan (const Range &range, Body &body)
Parallel prefix with default partitioner.
template<typename Range , typename Body >
void tbb::parallel_scan (const Range &range, Body &body, const simple_partitioner &partitioner)
Parallel prefix with simple_partitioner.
template<typename Range , typename Body >
void tbb::parallel_scan (const Range &range, Body &body, const auto_partitioner &partitioner)
Parallel prefix with auto_partitioner.
template<typename Range , typename Value , typename Scan , typename ReverseJoin >
Value tbb::parallel_scan (const Range &range, const Value &identity, const Scan &scan, const ReverseJoin &reverse_join)
Parallel prefix with default partitioner.
template<typename Range , typename Value , typename Scan , typename ReverseJoin >
Value tbb::parallel_scan (const Range &range, const Value &identity, const Scan &scan, const ReverseJoin &reverse_join, const simple_partitioner &partitioner)
Parallel prefix with simple_partitioner.
template<typename Range , typename Value , typename Scan , typename ReverseJoin >
Value tbb::parallel_scan (const Range &range, const Value &identity, const Scan &scan, const ReverseJoin &reverse_join, const auto_partitioner &partitioner)
Parallel prefix with auto_partitioner.
parallel_sort
See also requirements on iterators for parallel_sort.
template<typename RandomAccessIterator , typename Compare >
void tbb::parallel_sort (RandomAccessIterator begin, RandomAccessIterator end, const Compare &comp)
Sorts the data in [begin,end) using the given comparator.
template<typename RandomAccessIterator >
void tbb::parallel_sort (RandomAccessIterator begin, RandomAccessIterator end)
Sorts the data in [begin,end) with a default comparator std::less<RandomAccessIterator>
template<typename Range , typename Compare >
void tbb::parallel_sort (Range &rng, const Compare &comp)
Sorts the data in rng using the given comparator.
template<typename Range >
void tbb::parallel_sort (Range &rng)
Sorts the data in rng with a default comparator std::less<RandomAccessIterator>
template<typename T >
void tbb::parallel_sort (T *begin, T *end)
Sorts the data in the range [begin,end) with a default comparator std::less<T>
Detailed Description
Function Documentation
template<typename Range , typename Body > void tbb::parallel_deterministic_reduce (const Range & range, Body & body)
Parallel iteration with deterministic reduction and default simple partitioner.
Definition at line 549 of file parallel_reduce.h.
References tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run().
Referenced by tbb::parallel_deterministic_reduce().
{
     internal::start_deterministic_reduce<Range, Body, const simple_partitioner>::run(range, body, simple_partitioner());
 }
template<typename Range , typename Body > void tbb::parallel_deterministic_reduce (const Range & range, Body & body, const simple_partitioner & partitioner)
Parallel iteration with deterministic reduction and simple partitioner.
Definition at line 556 of file parallel_reduce.h.
References tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run().
{
     internal::start_deterministic_reduce<Range, Body, const simple_partitioner>::run(range, body, partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_deterministic_reduce (const Range & range, Body & body, const static_partitioner & partitioner)
Parallel iteration with deterministic reduction and static partitioner.
Definition at line 563 of file parallel_reduce.h.
References tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run().
{
     internal::start_deterministic_reduce<Range, Body, const static_partitioner>::run(range, body, partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_deterministic_reduce (const Range & range, Body & body, task_group_context & context)
Parallel iteration with deterministic reduction, default simple partitioner and user-supplied context.
Definition at line 571 of file parallel_reduce.h.
References tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run().
{
     internal::start_deterministic_reduce<Range,Body, const simple_partitioner>::run( range, body, simple_partitioner(), context );
 }
template<typename Range , typename Body > void tbb::parallel_deterministic_reduce (const Range & range, Body & body, const simple_partitioner & partitioner, task_group_context & context)
Parallel iteration with deterministic reduction, simple partitioner and user-supplied context.
Definition at line 578 of file parallel_reduce.h.
References tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run().
{
     internal::start_deterministic_reduce<Range, Body, const simple_partitioner>::run(range, body, partitioner, context);
 }
template<typename Range , typename Body > void tbb::parallel_deterministic_reduce (const Range & range, Body & body, const static_partitioner & partitioner, task_group_context & context)
Parallel iteration with deterministic reduction, static partitioner and user-supplied context.
Definition at line 585 of file parallel_reduce.h.
References tbb::interface9::internal::start_deterministic_reduce< Range, Body, Partitioner >::run().
{
     internal::start_deterministic_reduce<Range, Body, const static_partitioner>::run(range, body, partitioner, context);
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_deterministic_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction)
Parallel iteration with deterministic reduction and default simple partitioner.
parallel_reduce overloads that work with anonymous function objects (see also requirements on parallel_reduce anonymous function objects).
Definition at line 597 of file parallel_reduce.h.
References tbb::parallel_deterministic_reduce().
{
     return parallel_deterministic_reduce(range, identity, real_body, reduction, simple_partitioner());
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_deterministic_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const simple_partitioner & partitioner)
Parallel iteration with deterministic reduction and simple partitioner.
Definition at line 604 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_deterministic_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>, const simple_partitioner>
                           ::run(range, body, partitioner);
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_deterministic_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const static_partitioner & partitioner)
Parallel iteration with deterministic reduction and static partitioner.
Definition at line 614 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range, Value, RealBody, Reduction> body(identity, real_body, reduction);
     internal::start_deterministic_reduce<Range, internal::lambda_reduce_body<Range, Value, RealBody, Reduction>, const static_partitioner>
         ::run(range, body, partitioner);
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_deterministic_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, task_group_context & context)
Parallel iteration with deterministic reduction, default simple partitioner and user-supplied context.
Definition at line 624 of file parallel_reduce.h.
References tbb::parallel_deterministic_reduce().
{
     return parallel_deterministic_reduce(range, identity, real_body, reduction, simple_partitioner(), context);
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_deterministic_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const simple_partitioner & partitioner, task_group_context & context)
Parallel iteration with deterministic reduction, simple partitioner and user-supplied context.
Definition at line 632 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range, Value, RealBody, Reduction> body(identity, real_body, reduction);
     internal::start_deterministic_reduce<Range, internal::lambda_reduce_body<Range, Value, RealBody, Reduction>, const simple_partitioner>
         ::run(range, body, partitioner, context);
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_deterministic_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const static_partitioner & partitioner, task_group_context & context)
Parallel iteration with deterministic reduction, static partitioner and user-supplied context.
Definition at line 643 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range, Value, RealBody, Reduction> body(identity, real_body, reduction);
     internal::start_deterministic_reduce<Range, internal::lambda_reduce_body<Range, Value, RealBody, Reduction>, const static_partitioner>
         ::run(range, body, partitioner, context);
     return body.result();
 }
template<typename Iterator , typename Body > void tbb::parallel_do (Iterator first, Iterator last, const Body & body)
Parallel iteration over a range, with optional addition of more work.
Definition at line 498 of file parallel_do.h.
References __TBB_TASK_GROUP_CONTEXT, and tbb::interface9::internal::select_parallel_do().
Referenced by tbb::internal::parallel_for_each_impl< Iterator, Function, Generic >::doit(), and tbb::parallel_do().
 {
     if ( first == last )
         return;
 #if __TBB_TASK_GROUP_CONTEXT
     task_group_context context(internal::PARALLEL_DO);
 #endif
     interface9::internal::select_parallel_do( first, last, body, &Body::operator()
 #if __TBB_TASK_GROUP_CONTEXT
         , context
 #endif
         );
 }
template<typename Range , typename Body > void tbb::parallel_do (Range & rng, const Body & body)
Definition at line 513 of file parallel_do.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_do().
{
     parallel_do(tbb::internal::first(rng), tbb::internal::last(rng), body);
 }
template<typename Range , typename Body > void tbb::parallel_do (const Range & rng, const Body & body)
Definition at line 518 of file parallel_do.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_do().
{
     parallel_do(tbb::internal::first(rng), tbb::internal::last(rng), body);
 }
template<typename Iterator , typename Body > void tbb::parallel_do (Iterator first, Iterator last, const Body & body, task_group_context & context)
Parallel iteration over a range, with optional addition of more work and user-supplied context.
Definition at line 526 of file parallel_do.h.
References tbb::interface9::internal::select_parallel_do().
 {
     if ( first == last )
         return;
     interface9::internal::select_parallel_do( first, last, body, &Body::operator(), context );
 }
template<typename Range , typename Body > void tbb::parallel_do (Range & rng, const Body & body, task_group_context & context)
Definition at line 534 of file parallel_do.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_do().
{
     parallel_do(tbb::internal::first(rng), tbb::internal::last(rng), body, context);
 }
template<typename Range , typename Body > void tbb::parallel_do (const Range & rng, const Body & body, task_group_context & context)
Definition at line 539 of file parallel_do.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_do().
{
     parallel_do(tbb::internal::first(rng), tbb::internal::last(rng), body, context);
 }
template<typename Range , typename Body > void tbb::serial::interface9::parallel_for (const Range & range, const Body & body)
Parallel iteration over range with default partitioner.
Definition at line 101 of file serial/tbb/parallel_for.h.
References __TBB_DEFAULT_PARTITIONER, and tbb::serial::interface9::start_for< Range, Body, Partitioner >::run().
Referenced by tbb::serial::interface9::parallel_for().
{
     serial::interface9::start_for<Range,Body,const __TBB_DEFAULT_PARTITIONER>::run(range,body,__TBB_DEFAULT_PARTITIONER());
 }
template<typename Range , typename Body > void tbb::serial::interface9::parallel_for (const Range & range, const Body & body, const simple_partitioner & partitioner)
Parallel iteration over range with simple partitioner.
Definition at line 108 of file serial/tbb/parallel_for.h.
References tbb::serial::interface9::start_for< Range, Body, Partitioner >::run().
{
     serial::interface9::start_for<Range,Body,const simple_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::serial::interface9::parallel_for (const Range & range, const Body & body, const auto_partitioner & partitioner)
Parallel iteration over range with auto_partitioner.
Definition at line 115 of file serial/tbb/parallel_for.h.
References tbb::serial::interface9::start_for< Range, Body, Partitioner >::run().
{
     serial::interface9::start_for<Range,Body,const auto_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::serial::interface9::parallel_for (const Range & range, const Body & body, const static_partitioner & partitioner)
Parallel iteration over range with static_partitioner.
Definition at line 122 of file serial/tbb/parallel_for.h.
References tbb::serial::interface9::start_for< Range, Body, Partitioner >::run().
{
     serial::interface9::start_for<Range,Body,const static_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::serial::interface9::parallel_for (const Range & range, const Body & body, affinity_partitioner & partitioner)
Parallel iteration over range with affinity_partitioner.
Definition at line 129 of file serial/tbb/parallel_for.h.
References tbb::serial::interface9::start_for< Range, Body, Partitioner >::run().
{
     serial::interface9::start_for<Range,Body,affinity_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body)
Parallel iteration over range with default partitioner.
Definition at line 201 of file tbb/parallel_for.h.
References __TBB_DEFAULT_PARTITIONER, and tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
Referenced by tbb::internal::parallel_for_each_impl< Iterator, Function, std::random_access_iterator_tag >::doit(), tbb::strict_ppl::parallel_for_impl(), and tbb::interface9::internal::parallel_quick_sort().
{
     internal::start_for<Range,Body,const __TBB_DEFAULT_PARTITIONER>::run(range,body,__TBB_DEFAULT_PARTITIONER());
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, const simple_partitioner & partitioner)
Parallel iteration over range with simple partitioner.
Definition at line 208 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,const simple_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, const auto_partitioner & partitioner)
Parallel iteration over range with auto_partitioner.
Definition at line 215 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,const auto_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, const static_partitioner & partitioner)
Parallel iteration over range with static_partitioner.
Definition at line 222 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,const static_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, affinity_partitioner & partitioner)
Parallel iteration over range with affinity_partitioner.
Definition at line 229 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,affinity_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, task_group_context & context)
Parallel iteration over range with default partitioner and user-supplied context.
Definition at line 237 of file tbb/parallel_for.h.
References __TBB_DEFAULT_PARTITIONER, and tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,const __TBB_DEFAULT_PARTITIONER>::run(range, body, __TBB_DEFAULT_PARTITIONER(), context);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, const simple_partitioner & partitioner, task_group_context & context)
Parallel iteration over range with simple partitioner and user-supplied context.
Definition at line 244 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,const simple_partitioner>::run(range, body, partitioner, context);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, const auto_partitioner & partitioner, task_group_context & context)
Parallel iteration over range with auto_partitioner and user-supplied context.
Definition at line 251 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,const auto_partitioner>::run(range, body, partitioner, context);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, const static_partitioner & partitioner, task_group_context & context)
Parallel iteration over range with static_partitioner and user-supplied context.
Definition at line 258 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,const static_partitioner>::run(range, body, partitioner, context);
 }
template<typename Range , typename Body > void tbb::parallel_for (const Range & range, const Body & body, affinity_partitioner & partitioner, task_group_context & context)
Parallel iteration over range with affinity_partitioner and user-supplied context.
Definition at line 265 of file tbb/parallel_for.h.
References tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
{
     internal::start_for<Range,Body,affinity_partitioner>::run(range,body,partitioner, context);
 }
template<typename Iterator , typename Function > void tbb::parallel_for_each (Iterator first, Iterator last, const Function & f, task_group_context & context)
Calls function f for all items from [first, last) interval using user-supplied context.
Definition at line 96 of file parallel_for_each.h.
Referenced by tbb::parallel_for_each().
{
     internal::parallel_for_each_impl<Iterator, Function, typename std::iterator_traits<Iterator>::iterator_category>::doit(first, last, f, context);
 }
template<typename Range , typename Function > void tbb::parallel_for_each (Range & rng, const Function & f, task_group_context & context)
Calls function f for all items from rng using user-supplied context.
Definition at line 103 of file parallel_for_each.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_for_each().
{
     parallel_for_each(tbb::internal::first(rng), tbb::internal::last(rng), f, context);
 }
template<typename Range , typename Function > void tbb::parallel_for_each (const Range & rng, const Function & f, task_group_context & context)
Calls function f for all items from const rng user-supplied context.
Definition at line 110 of file parallel_for_each.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_for_each().
{
     parallel_for_each(tbb::internal::first(rng), tbb::internal::last(rng), f, context);
 }
template<typename Iterator , typename Function > void tbb::parallel_for_each (Iterator first, Iterator last, const Function & f)
Uses default context.
Definition at line 117 of file parallel_for_each.h.
{
     internal::parallel_for_each_impl<Iterator, Function, typename std::iterator_traits<Iterator>::iterator_category>::doit(first, last, f);
 }
template<typename Range , typename Function > void tbb::parallel_for_each (Range & rng, const Function & f)
Uses default context.
Definition at line 123 of file parallel_for_each.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_for_each().
{
     parallel_for_each(tbb::internal::first(rng), tbb::internal::last(rng), f);
 }
template<typename Range , typename Function > void tbb::parallel_for_each (const Range & rng, const Function & f)
Uses default context.
Definition at line 129 of file parallel_for_each.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_for_each().
{
     parallel_for_each(tbb::internal::first(rng), tbb::internal::last(rng), f);
 }
template<typename F0 , typename F1 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, tbb::task_group_context & context)
Executes a list of tasks in parallel and waits for all tasks to complete.
Definition at line 258 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
{
     internal::parallel_invoke_cleaner cleaner(2, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, tbb::task_group_context & context)
Definition at line 269 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
{
     internal::parallel_invoke_cleaner cleaner(3, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f2);
     root.add_children(f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, tbb::task_group_context & context)
Definition at line 281 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
 {
     internal::parallel_invoke_cleaner cleaner(4, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f3);
     root.add_children(f2);
     root.add_children(f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, tbb::task_group_context & context)
Definition at line 296 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
 {
     internal::parallel_invoke_cleaner cleaner(3, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f4, f3);
     root.add_children(f2, f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, tbb::task_group_context & context)
Definition at line 310 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
 {
     internal::parallel_invoke_cleaner cleaner(3, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f5, f4, f3);
     root.add_children(f2, f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6, tbb::task_group_context & context)
Definition at line 324 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
 {
     internal::parallel_invoke_cleaner cleaner(3, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f6, f5, f4);
     root.add_children(f3, f2, f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6, const F7 & f7, tbb::task_group_context & context)
Definition at line 340 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
 {
     internal::parallel_invoke_cleaner cleaner(4, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f7, f6, f5);
     root.add_children(f4, f3);
     root.add_children(f2, f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6, const F7 & f7, const F8 & f8, tbb::task_group_context & context)
Definition at line 357 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
 {
     internal::parallel_invoke_cleaner cleaner(4, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f8, f7, f6);
     root.add_children(f5, f4, f3);
     root.add_children(f2, f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 , typename F9 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6, const F7 & f7, const F8 & f8, const F9 & f9, tbb::task_group_context & context)
Definition at line 374 of file parallel_invoke.h.
References tbb::internal::parallel_invoke_helper::add_children().
 {
     internal::parallel_invoke_cleaner cleaner(4, context);
     internal::parallel_invoke_helper& root = cleaner.root;
     root.add_children(f9, f8, f7);
     root.add_children(f6, f5, f4);
     root.add_children(f3, f2, f1);
     root.run_and_finish(f0);
 }
template<typename F0 , typename F1 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1)
Definition at line 390 of file parallel_invoke.h.
{
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1>(f0, f1, context);
 }
template<typename F0 , typename F1 , typename F2 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2)
Definition at line 396 of file parallel_invoke.h.
{
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2>(f0, f1, f2, context);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3)
Definition at line 402 of file parallel_invoke.h.
{
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2, F3>(f0, f1, f2, f3, context);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4)
Definition at line 408 of file parallel_invoke.h.
{
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2, F3, F4>(f0, f1, f2, f3, f4, context);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5)
Definition at line 414 of file parallel_invoke.h.
{
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2, F3, F4, F5>(f0, f1, f2, f3, f4, f5, context);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6)
Definition at line 420 of file parallel_invoke.h.
 {
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2, F3, F4, F5, F6>(f0, f1, f2, f3, f4, f5, f6, context);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6, const F7 & f7)
Definition at line 429 of file parallel_invoke.h.
 {
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2, F3, F4, F5, F6, F7>(f0, f1, f2, f3, f4, f5, f6, f7, context);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6, const F7 & f7, const F8 & f8)
Definition at line 438 of file parallel_invoke.h.
 {
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2, F3, F4, F5, F6, F7, F8>(f0, f1, f2, f3, f4, f5, f6, f7, f8, context);
 }
template<typename F0 , typename F1 , typename F2 , typename F3 , typename F4 , typename F5 , typename F6 , typename F7 , typename F8 , typename F9 > void tbb::parallel_invoke (const F0 & f0, const F1 & f1, const F2 & f2, const F3 & f3, const F4 & f4, const F5 & f5, const F6 & f6, const F7 & f7, const F8 & f8, const F9 & f9)
Definition at line 447 of file parallel_invoke.h.
 {
     task_group_context context(internal::PARALLEL_INVOKE);
     parallel_invoke<F0, F1, F2, F3, F4, F5, F6, F7, F8, F9>(f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, context);
 }
template<typename RandomAccessIterator , typename Compare > void tbb::interface9::internal::parallel_quick_sort (RandomAccessIterator begin, RandomAccessIterator end, const Compare & comp)
Wrapper method to initiate the sort by calling parallel_for.
Definition at line 163 of file parallel_sort.h.
References __TBB_ASSERT, tbb::interface9::internal::quick_sort_range< RandomAccessIterator, Compare >::begin, tbb::interface9::internal::quick_sort_range< RandomAccessIterator, Compare >::comp, tbb::task_group_context::is_group_execution_cancelled(), and tbb::parallel_for().
Referenced by tbb::parallel_sort().
{
 #if __TBB_TASK_GROUP_CONTEXT
     task_group_context my_context(PARALLEL_SORT);
     const int serial_cutoff = 9;
     __TBB_ASSERT( begin + serial_cutoff < end, "min_parallel_size is smaller than serial cutoff?" );
     RandomAccessIterator k = begin;
     for ( ; k != begin + serial_cutoff; ++k ) {
         if ( comp( *(k+1), *k ) ) {
             goto do_parallel_quick_sort;
         }
     }
     parallel_for( blocked_range<RandomAccessIterator>(k+1, end),
                   quick_sort_pretest_body<RandomAccessIterator,Compare>(comp),
                   auto_partitioner(),
                   my_context);
     if (my_context.is_group_execution_cancelled())
 do_parallel_quick_sort:
 #endif /* __TBB_TASK_GROUP_CONTEXT */
         parallel_for( quick_sort_range<RandomAccessIterator,Compare>(begin, end-begin, comp ),
                       quick_sort_body<RandomAccessIterator,Compare>(),
                       auto_partitioner() );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body)
Parallel iteration with reduction and default partitioner.
Definition at line 363 of file parallel_reduce.h.
References __TBB_DEFAULT_PARTITIONER, and tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body, const __TBB_DEFAULT_PARTITIONER>::run( range, body, __TBB_DEFAULT_PARTITIONER() );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, const simple_partitioner & partitioner)
Parallel iteration with reduction and simple_partitioner.
Definition at line 370 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,const simple_partitioner>::run( range, body, partitioner );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, const auto_partitioner & partitioner)
Parallel iteration with reduction and auto_partitioner.
Definition at line 377 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,const auto_partitioner>::run( range, body, partitioner );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, const static_partitioner & partitioner)
Parallel iteration with reduction and static_partitioner.
Definition at line 384 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,const static_partitioner>::run( range, body, partitioner );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, affinity_partitioner & partitioner)
Parallel iteration with reduction and affinity_partitioner.
Definition at line 391 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,affinity_partitioner>::run( range, body, partitioner );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, task_group_context & context)
Parallel iteration with reduction, default partitioner and user-supplied context.
Definition at line 399 of file parallel_reduce.h.
References __TBB_DEFAULT_PARTITIONER, and tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,const __TBB_DEFAULT_PARTITIONER>::run( range, body, __TBB_DEFAULT_PARTITIONER(), context );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, const simple_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, simple partitioner and user-supplied context.
Definition at line 406 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,const simple_partitioner>::run( range, body, partitioner, context );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, const auto_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, auto_partitioner and user-supplied context.
Definition at line 413 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,const auto_partitioner>::run( range, body, partitioner, context );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, const static_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, static_partitioner and user-supplied context.
Definition at line 420 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,const static_partitioner>::run( range, body, partitioner, context );
 }
template<typename Range , typename Body > void tbb::parallel_reduce (const Range & range, Body & body, affinity_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, affinity_partitioner and user-supplied context.
Definition at line 427 of file parallel_reduce.h.
References tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::run().
{
     internal::start_reduce<Range,Body,affinity_partitioner>::run( range, body, partitioner, context );
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction)
Parallel iteration with reduction and default partitioner.
parallel_reduce overloads that work with anonymous function objects (see also requirements on parallel_reduce anonymous function objects).
Definition at line 438 of file parallel_reduce.h.
References __TBB_DEFAULT_PARTITIONER.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const __TBB_DEFAULT_PARTITIONER>
                           ::run(range, body, __TBB_DEFAULT_PARTITIONER() );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const simple_partitioner & partitioner)
Parallel iteration with reduction and simple_partitioner.
Definition at line 448 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const simple_partitioner>
                           ::run(range, body, partitioner );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const auto_partitioner & partitioner)
Parallel iteration with reduction and auto_partitioner.
Definition at line 459 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const auto_partitioner>
                           ::run( range, body, partitioner );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const static_partitioner & partitioner)
Parallel iteration with reduction and static_partitioner.
Definition at line 470 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const static_partitioner>
                                         ::run( range, body, partitioner );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, affinity_partitioner & partitioner)
Parallel iteration with reduction and affinity_partitioner.
Definition at line 481 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,affinity_partitioner>
                                         ::run( range, body, partitioner );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, task_group_context & context)
Parallel iteration with reduction, default partitioner and user-supplied context.
Definition at line 493 of file parallel_reduce.h.
References __TBB_DEFAULT_PARTITIONER.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const __TBB_DEFAULT_PARTITIONER>
                           ::run( range, body, __TBB_DEFAULT_PARTITIONER(), context );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const simple_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, simple partitioner and user-supplied context.
Definition at line 504 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const simple_partitioner>
                           ::run( range, body, partitioner, context );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const auto_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, auto_partitioner and user-supplied context.
Definition at line 515 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const auto_partitioner>
                           ::run( range, body, partitioner, context );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, const static_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, static_partitioner and user-supplied context.
Definition at line 526 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,const static_partitioner>
                                         ::run( range, body, partitioner, context );
     return body.result();
 }
template<typename Range , typename Value , typename RealBody , typename Reduction > Value tbb::parallel_reduce (const Range & range, const Value & identity, const RealBody & real_body, const Reduction & reduction, affinity_partitioner & partitioner, task_group_context & context)
Parallel iteration with reduction, affinity_partitioner and user-supplied context.
Definition at line 537 of file parallel_reduce.h.
{
     internal::lambda_reduce_body<Range,Value,RealBody,Reduction> body(identity, real_body, reduction);
     internal::start_reduce<Range,internal::lambda_reduce_body<Range,Value,RealBody,Reduction>,affinity_partitioner>
                                         ::run( range, body, partitioner, context );
     return body.result();
 }
template<typename Range , typename Body > void tbb::parallel_scan (const Range & range, Body & body)
Parallel prefix with default partitioner.
Definition at line 364 of file parallel_scan.h.
References __TBB_DEFAULT_PARTITIONER, and tbb::internal::start_scan< Range, Body, Partitioner >::run().
Referenced by tbb::parallel_scan().
{
     internal::start_scan<Range,Body,__TBB_DEFAULT_PARTITIONER>::run(range,body,__TBB_DEFAULT_PARTITIONER());
 }
template<typename Range , typename Body > void tbb::parallel_scan (const Range & range, Body & body, const simple_partitioner & partitioner)
Parallel prefix with simple_partitioner.
Definition at line 371 of file parallel_scan.h.
References tbb::internal::start_scan< Range, Body, Partitioner >::run().
{
     internal::start_scan<Range,Body,simple_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Body > void tbb::parallel_scan (const Range & range, Body & body, const auto_partitioner & partitioner)
Parallel prefix with auto_partitioner.
Definition at line 378 of file parallel_scan.h.
References tbb::internal::start_scan< Range, Body, Partitioner >::run().
{
     internal::start_scan<Range,Body,auto_partitioner>::run(range,body,partitioner);
 }
template<typename Range , typename Value , typename Scan , typename ReverseJoin > Value tbb::parallel_scan (const Range & range, const Value & identity, const Scan & scan, const ReverseJoin & reverse_join)
Parallel prefix with default partitioner.
Definition at line 385 of file parallel_scan.h.
References __TBB_DEFAULT_PARTITIONER, and tbb::parallel_scan().
{
     internal::lambda_scan_body<Range, Value, Scan, ReverseJoin> body(identity, scan, reverse_join);
     tbb::parallel_scan(range,body,__TBB_DEFAULT_PARTITIONER());
     return body.result();
 }
template<typename Range , typename Value , typename Scan , typename ReverseJoin > Value tbb::parallel_scan (const Range & range, const Value & identity, const Scan & scan, const ReverseJoin & reverse_join, const simple_partitioner & partitioner)
Parallel prefix with simple_partitioner.
Definition at line 394 of file parallel_scan.h.
References tbb::parallel_scan().
{
     internal::lambda_scan_body<Range, Value, Scan, ReverseJoin> body(identity, scan, reverse_join);
     tbb::parallel_scan(range,body,partitioner);
     return body.result();
 }
template<typename Range , typename Value , typename Scan , typename ReverseJoin > Value tbb::parallel_scan (const Range & range, const Value & identity, const Scan & scan, const ReverseJoin & reverse_join, const auto_partitioner & partitioner)
Parallel prefix with auto_partitioner.
Definition at line 403 of file parallel_scan.h.
References tbb::parallel_scan().
{
     internal::lambda_scan_body<Range, Value, Scan, ReverseJoin> body(identity, scan, reverse_join);
     tbb::parallel_scan(range,body,partitioner);
     return body.result();
 }
template<typename RandomAccessIterator , typename Compare > void tbb::parallel_sort (RandomAccessIterator begin, RandomAccessIterator end, const Compare & comp)
Sorts the data in [begin,end) using the given comparator.
The compare function object is used for all comparisons between elements during sorting. The compare object must define a bool operator() function.
Definition at line 211 of file parallel_sort.h.
References tbb::interface9::internal::parallel_quick_sort().
Referenced by tbb::parallel_sort().
{
     const int min_parallel_size = 500;
     if( end > begin ) {
         if (end - begin < min_parallel_size) {
             std::sort(begin, end, comp);
         } else {
             interface9::internal::parallel_quick_sort(begin, end, comp);
         }
     }
 }
template<typename RandomAccessIterator > void tbb::parallel_sort (RandomAccessIterator begin, RandomAccessIterator end) inline
Sorts the data in [begin,end) with a default comparator std::less<RandomAccessIterator>
Definition at line 225 of file parallel_sort.h.
References tbb::parallel_sort().
{
     parallel_sort( begin, end, std::less< typename std::iterator_traits<RandomAccessIterator>::value_type >() );
 }
template<typename Range , typename Compare > void tbb::parallel_sort (Range & rng, const Compare & comp)
Sorts the data in rng using the given comparator.
Definition at line 232 of file parallel_sort.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_sort().
{
     parallel_sort(tbb::internal::first(rng), tbb::internal::last(rng), comp);
 }
template<typename Range > void tbb::parallel_sort (Range & rng)
Sorts the data in rng with a default comparator std::less<RandomAccessIterator>
Definition at line 239 of file parallel_sort.h.
References tbb::internal::first(), tbb::internal::last(), and tbb::parallel_sort().
{
     parallel_sort(tbb::internal::first(rng), tbb::internal::last(rng));
 }
template<typename T > void tbb::parallel_sort (T * begin, T * end) inline
Sorts the data in the range [begin,end) with a default comparator std::less<T>
Definition at line 246 of file parallel_sort.h.
References tbb::parallel_sort().
{
     parallel_sort( begin, end, std::less< T >() );
 }
template<typename Iterator , typename Body , typename Item > void tbb::interface9::internal::run_parallel_do (Iterator first, Iterator last, const Body & body, task_group_context & context)
For internal use only.
Implements parallel iteration over a range.
Definition at line 415 of file parallel_do.h.
References tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::my_barrier, and tbb::interface9::internal::parallel_do_feeder_impl< Body, Item >::my_body.
     {
         typedef do_task_iter<Iterator, Body, Item> root_iteration_task;
 #if __TBB_TASK_GROUP_CONTEXT
         parallel_do_feeder_impl<Body, Item> feeder(context);
 #else
         parallel_do_feeder_impl<Body, Item> feeder;
 #endif
         feeder.my_body = &body;
         root_iteration_task &t = *new( feeder.my_barrier->allocate_child() ) root_iteration_task(first, last, feeder);
         feeder.my_barrier->set_ref_count(2);
         feeder.my_barrier->spawn_and_wait_for_all(t);
     }
template<typename Iterator , typename Body , typename Item > void tbb::interface9::internal::select_parallel_do (Iterator first, Iterator last, const Body & body, void(Body::*)(Item) const, task_group_context & context)
For internal use only.
Detects types of Body's operator function arguments.
Definition at line 439 of file parallel_do.h.
References tbb::internal::first(), tbb::internal::last(), and type.
Referenced by tbb::parallel_do().
     {
         run_parallel_do<Iterator, Body, typename ::tbb::internal::strip<Item>::type>( first, last, body
 #if __TBB_TASK_GROUP_CONTEXT
             , context
 #endif
             );
     }
template<typename Iterator , typename Body , typename Item , typename _Item > void tbb::interface9::internal::select_parallel_do (Iterator first, Iterator last, const Body & body, void(Body::*)(Item, parallel_do_feeder< _Item > &) const, task_group_context & context)
For internal use only.
Detects types of Body's operator function arguments.
Definition at line 456 of file parallel_do.h.
References tbb::internal::first(), tbb::internal::last(), and type.
     {
         run_parallel_do<Iterator, Body, typename ::tbb::internal::strip<Item>::type>( first, last, body
 #if __TBB_TASK_GROUP_CONTEXT
             , context
 #endif
             );
     }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.