Intel(R) Threading Building Blocks Doxygen Documentation: windows_intel64.h File Reference
windows_intel64.h File Reference
#include "msvc_ia32_common.h"
#include <intrin.h>
Macros
#define __TBB_WORDSIZE 8
#define __TBB_ENDIANNESS __TBB_ENDIAN_LITTLE
#define __TBB_USE_FETCHSTORE_AS_FULL_FENCED_STORE 1
#define __TBB_USE_GENERIC_HALF_FENCED_LOAD_STORE 1
#define __TBB_USE_GENERIC_RELAXED_LOAD_STORE 1
#define __TBB_USE_GENERIC_SEQUENTIAL_CONSISTENCY_LOAD_STORE 1
Functions
__int8 __TBB_EXPORTED_FUNC __TBB_machine_cmpswp1 (volatile void *ptr, __int8 value, __int8 comparand)
__int8 __TBB_EXPORTED_FUNC __TBB_machine_fetchadd1 (volatile void *ptr, __int8 addend)
__int8 __TBB_EXPORTED_FUNC __TBB_machine_fetchstore1 (volatile void *ptr, __int8 value)
__int16 __TBB_EXPORTED_FUNC __TBB_machine_cmpswp2 (volatile void *ptr, __int16 value, __int16 comparand)
__int16 __TBB_EXPORTED_FUNC __TBB_machine_fetchadd2 (volatile void *ptr, __int16 addend)
__int16 __TBB_EXPORTED_FUNC __TBB_machine_fetchstore2 (volatile void *ptr, __int16 value)
long __TBB_machine_cmpswp4 (volatile void *ptr, __int32 value, __int32 comparand)
long __TBB_machine_fetchadd4 (volatile void *ptr, __int32 addend)
long __TBB_machine_fetchstore4 (volatile void *ptr, __int32 value)
__int64 __TBB_machine_cmpswp8 (volatile void *ptr, __int64 value, __int64 comparand)
__int64 __TBB_machine_fetchadd8 (volatile void *ptr, __int64 addend)
__int64 __TBB_machine_fetchstore8 (volatile void *ptr, __int64 value)
Macro Definition Documentation
#define __TBB_ENDIANNESS __TBB_ENDIAN_LITTLE
Definition at line 28 of file windows_intel64.h.
#define __TBB_USE_FETCHSTORE_AS_FULL_FENCED_STORE 1
Definition at line 71 of file windows_intel64.h.
#define __TBB_USE_GENERIC_HALF_FENCED_LOAD_STORE 1
Definition at line 72 of file windows_intel64.h.
#define __TBB_USE_GENERIC_RELAXED_LOAD_STORE 1
Definition at line 73 of file windows_intel64.h.
#define __TBB_USE_GENERIC_SEQUENTIAL_CONSISTENCY_LOAD_STORE 1
Definition at line 74 of file windows_intel64.h.
#define __TBB_WORDSIZE 8
Definition at line 27 of file windows_intel64.h.
Function Documentation
__int8 __TBB_EXPORTED_FUNC __TBB_machine_cmpswp1 (volatile void * ptr, __int8 value, __int8 comparand)
Referenced by tbb::internal::__TBB_CompareAndSwapGeneric< 1, int8_t >(), and __TBB_TryLockByte().
__int16 __TBB_EXPORTED_FUNC __TBB_machine_cmpswp2 (volatile void * ptr, __int16 value, __int16 comparand)
Referenced by tbb::internal::__TBB_CompareAndSwapGeneric< 2, int16_t >().
long __TBB_machine_cmpswp4 (volatile void * ptr, __int32 value, __int32 comparand) inline
Definition at line 49 of file windows_intel64.h.
{
     return _InterlockedCompareExchange( (long*)ptr, value, comparand );
 }
__int64 __TBB_machine_cmpswp8 (volatile void * ptr, __int64 value, __int64 comparand) inline
Definition at line 59 of file windows_intel64.h.
{
     return _InterlockedCompareExchange64( (__int64*)ptr, value, comparand );
 }
__int8 __TBB_EXPORTED_FUNC __TBB_machine_fetchadd1 (volatile void * ptr, __int8 addend)
__int16 __TBB_EXPORTED_FUNC __TBB_machine_fetchadd2 (volatile void * ptr, __int16 addend)
long __TBB_machine_fetchadd4 (volatile void * ptr, __int32 addend) inline
Definition at line 52 of file windows_intel64.h.
Referenced by __itt_interlocked_increment().
{
     return _InterlockedExchangeAdd( (long*)ptr, addend );
 }
__int64 __TBB_machine_fetchadd8 (volatile void * ptr, __int64 addend) inline
Definition at line 62 of file windows_intel64.h.
{
     return _InterlockedExchangeAdd64( (__int64*)ptr, addend );
 }
__int8 __TBB_EXPORTED_FUNC __TBB_machine_fetchstore1 (volatile void * ptr, __int8 value)
__int16 __TBB_EXPORTED_FUNC __TBB_machine_fetchstore2 (volatile void * ptr, __int16 value)
long __TBB_machine_fetchstore4 (volatile void * ptr, __int32 value) inline
Definition at line 55 of file windows_intel64.h.
{
     return _InterlockedExchange( (long*)ptr, value );
 }
__int64 __TBB_machine_fetchstore8 (volatile void * ptr, __int64 value) inline
Definition at line 65 of file windows_intel64.h.
{
     return _InterlockedExchange64( (__int64*)ptr, value );
 }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.