Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface6 Namespace Reference
tbb::interface6 Namespace Reference
Namespaces
internal
Classes
class aggregator
Basic aggregator interface.
class aggregator_ext
Aggregator base class and expert interface.
class aggregator_operation
class concurrent_lru_cache
class enumerable_thread_specific
The enumerable_thread_specific container.
class filter_t
Class representing a chain of type-safe pipeline filters.
class fixed_pool
class flattened2d
class flow_control
input_filter control to signal end-of-input for parallel_pipeline
class memory_pool
Thread-safe growable pool allocator for variable-size requests.
class memory_pool_allocator
Meets "allocator" requirements of ISO C++ Standard, Section 20.1.5.
class memory_pool_allocator< void, P >
Analogous to std::allocator<void>, as defined in ISO C++ Standard, Section 20.4.1.
class runtime_loader
Load TBB at runtime.
Functions
template<typename T >
atomic< T > make_atomic (T t)
Make an atomic for use in an initialization (list), as an alternative to zero-initialization or normal assignment.
template<typename Container >
flattened2d< Container > flatten2d (const Container &c, const typename Container::const_iterator b, const typename Container::const_iterator e)
template<typename Container >
flattened2d< Container > flatten2d (const Container &c)
template<typename T , typename U , typename P >
bool operator== (const memory_pool_allocator< T, P > &a, const memory_pool_allocator< U, P > &b)
template<typename T , typename U , typename P >
bool operator!= (const memory_pool_allocator< T, P > &a, const memory_pool_allocator< U, P > &b)
template<typename T , typename U , typename Body >
filter_t< T, U > make_filter (tbb::filter::mode mode, const Body &body)
Create a filter to participate in parallel_pipeline.
template<typename T , typename V , typename U >
filter_t< T, U > operator& (const filter_t< T, V > &left, const filter_t< V, U > &right)
void parallel_pipeline (size_t max_number_of_live_tokens, const filter_t< void, void > &filter_chain, tbb::task_group_context &context)
void parallel_pipeline (size_t max_number_of_live_tokens, const filter_t< void, void > &filter_chain)
Function Documentation
template<typename Container > flattened2d<Container> tbb::interface6::flatten2d (const Container & c, const typename Container::const_iterator b, const typename Container::const_iterator e)
Definition at line 1116 of file enumerable_thread_specific.h.
Referenced by flatten2d().
{
         return flattened2d<Container>(c, b, e);
     }
template<typename Container > flattened2d<Container> tbb::interface6::flatten2d (const Container & c)
Definition at line 1121 of file enumerable_thread_specific.h.
References flatten2d().
{
         return flattened2d<Container>(c);
     }
template<typename T > atomic<T> tbb::interface6::make_atomic (T t)
Make an atomic for use in an initialization (list), as an alternative to zero-initialization or normal assignment.
Definition at line 529 of file atomic.h.
{
     atomic<T> a;
     store<relaxed>(a,t);
     return a;
 }
template<typename T , typename U , typename Body > filter_t<T,U> tbb::interface6::make_filter (tbb::filter::mode mode, const Body & body)
Create a filter to participate in parallel_pipeline.
Definition at line 573 of file pipeline.h.
References mode.
Referenced by parallel_pipeline().
{
     return new internal::filter_node_leaf<T,U,Body>(mode, body);
 }
template<typename T , typename U , typename P > bool tbb::interface6::operator!= (const memory_pool_allocator< T, P > & a, const memory_pool_allocator< U, P > & b) inline
Definition at line 187 of file memory_pool.h.
References tbb::interface6::memory_pool_allocator< T, P >::my_pool.
 {return a.my_pool!=b.my_pool;}
template<typename T , typename V , typename U > filter_t<T,U> tbb::interface6::operator& (const filter_t< T, V > & left, const filter_t< V, U > & right)
Definition at line 578 of file pipeline.h.
References __TBB_ASSERT, and tbb::interface6::filter_t< T, U >::root.
{
     __TBB_ASSERT(left.root,"cannot use default-constructed filter_t as left argument of '&'");
     __TBB_ASSERT(right.root,"cannot use default-constructed filter_t as right argument of '&'");
     return new internal::filter_node_join(*left.root,*right.root);
 }
template<typename T , typename U , typename P > bool tbb::interface6::operator== (const memory_pool_allocator< T, P > & a, const memory_pool_allocator< U, P > & b) inline
Definition at line 184 of file memory_pool.h.
References tbb::interface6::memory_pool_allocator< T, P >::my_pool.
 {return a.my_pool==b.my_pool;}
void tbb::interface6::parallel_pipeline (size_t max_number_of_live_tokens, const filter_t< void, void > & filter_chain, tbb::task_group_context & context) inline
Definition at line 635 of file pipeline.h.
Referenced by parallel_pipeline().
       {
     internal::pipeline_proxy pipe(filter_chain);
     // tbb::pipeline::run() is called via the proxy
     pipe->run(max_number_of_live_tokens
 #if __TBB_TASK_GROUP_CONTEXT
               , context
 #endif
     );
 }
void tbb::interface6::parallel_pipeline (size_t max_number_of_live_tokens, const filter_t< void, void > & filter_chain) inline
Definition at line 650 of file pipeline.h.
References make_filter(), and parallel_pipeline().
{
     tbb::task_group_context context;
     parallel_pipeline(max_number_of_live_tokens, filter_chain, context);
 }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.