Intel(R) Threading Building Blocks Doxygen Documentation: tbb::this_tbb_thread Namespace Reference
tbb::this_tbb_thread Namespace Reference
Functions
tbb_thread::id get_id ()
void yield ()
Offers the operating system the opportunity to schedule another thread.
void sleep (const tick_count::interval_t &i)
The current thread blocks at least until the time specified.
Function Documentation
tbb_thread::id tbb::this_tbb_thread::get_id () inline
Definition at line 321 of file tbb_thread.h.
References tbb::internal::thread_get_id_v3().
Referenced by tbb::interface5::reader_writer_lock::is_current_writer(), tbb::internal::tbb_thread_v3::join(), tbb::internal::critical_section_v4::lock(), tbb::interface5::reader_writer_lock::start_write(), tbb::internal::critical_section_v4::try_lock(), tbb::internal::critical_section_v4::unlock(), and tbb::internal::tbb_thread_v3::~tbb_thread_v3().
 { return internal::thread_get_id_v3(); }
void tbb::this_tbb_thread::sleep (const tick_count::interval_t & i) inline
The current thread blocks at least until the time specified.
Definition at line 325 of file tbb_thread.h.
References tbb::internal::thread_sleep_v3().
{
         internal::thread_sleep_v3(i);
     }
void tbb::this_tbb_thread::yield () inline
Offers the operating system the opportunity to schedule another thread.
Definition at line 323 of file tbb_thread.h.
References tbb::internal::thread_yield_v3().
 { internal::thread_yield_v3(); }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.