Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10::internal Namespace Reference
tbb::flow::interface10::internal Namespace Reference
Namespaces
graph_policy_namespace
Classes
struct aligned_pair
struct alignment_of
class apply_body_task_bypass
A task that calls a node's apply_body_bypass function, passing in an input of type Input.
class async_body
class async_body_base
struct async_helpers
struct async_helpers< T, typename std::enable_if< std::is_base_of< async_msg< typename T::async_msg_data_type >, T >::value >::type >
class async_storage
class broadcast_cache
A cache of successors that are broadcast to.
struct buffer_element_type
struct clear_element
struct clear_element< 1 >
class continue_input
Implements methods for an executable node that takes continue_msg as input.
struct convert_and_call_impl
struct convert_and_call_impl< A1, Args1... >
struct convert_and_call_impl<>
struct count_element
class decrementer
struct default_constructed
struct do_if
struct do_if< T, false >
struct do_if< T, true >
struct emit_element
struct emit_element< 1 >
struct empty_body
An empty functor that takes an Input and returns a default constructed Output.
struct ERROR_Type_Not_allowed_In_Tagged_Msg_Not_Member_Of_Tuple
class forward_task_bypass
A task that calls a node's forward_task function.
struct forwarding_base
class function_body
A functor that takes an Input and generates an Output.
class function_body_leaf
the leaf for function_body
class function_body_leaf< continue_msg, continue_msg, B >
the leaf for function_body specialized for Input and output of continue_msg
class function_body_leaf< continue_msg, Output, B >
the leaf for function_body specialized for Input of continue_msg
class function_body_leaf< Input, continue_msg, B >
the leaf for function_body specialized for Output of continue_msg
class function_input
Implements methods for a function node that takes a type Input as input and sends.
class function_input_base
Input and scheduling for a function node that takes a type Input as input.
class function_input_queue
class function_output
Implements methods for both executable and function nodes that puts Output to its successors.
struct graph_task_comparator
struct has_policy
struct has_policy< ExpectedPolicy, FirstPolicy, Policies... >
struct has_policy< ExpectedPolicy, Policy< Policies... > >
struct has_policy< ExpectedPolicy, SinglePolicy >
class hash_buffer
struct indexer_helper
struct indexer_helper< TupleTypes, 1 >
class indexer_input_port
class indexer_node_base
indexer_node_base
class indexer_node_FE
struct indexer_types
class initializer_list_wrapper
struct input_types
struct input_types< 1, InputTuple >
struct input_types< 10, InputTuple >
struct input_types< 2, InputTuple >
struct input_types< 3, InputTuple >
struct input_types< 4, InputTuple >
struct input_types< 5, InputTuple >
struct input_types< 6, InputTuple >
struct input_types< 7, InputTuple >
struct input_types< 8, InputTuple >
struct input_types< 9, InputTuple >
struct is_element_of
struct is_element_of< Q, 0, Tuple >
struct is_port_ref
struct is_port_ref_impl
struct is_port_ref_impl< port_ref_impl< N1, N2 > >
struct is_port_ref_impl< port_ref_impl< N1, N2 >(*)() >
class item_buffer
struct join_base
struct join_base< N, key_matching_port, OutputTuple, key_matching< K, KHash > >
struct join_helper
struct join_helper< 1 >
class join_node_base
join_node_base
class join_node_FE
join_node_FE : implements input port policy
class join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >
class join_node_FE< queueing, InputTuple, OutputTuple >
class join_node_FE< reserving, InputTuple, OutputTuple >
class kernel_executor_helper
class kernel_executor_helper< StreamFactory, KernelInputTuple, typename tbb::internal::void_t< typename StreamFactory::range_type >::type >
struct key_from_message_body
struct key_from_message_body< K &, T >
struct key_from_policy
struct key_from_policy< key_matching< Key & > >
struct key_from_policy< key_matching< Key > >
class key_matching_port
struct key_to_count_functor
struct KeyTrait
struct make_sequence
struct make_sequence< 0, S... >
struct matching_forwarding_base
class multifunction_body
function_body that takes an Input and a set of output ports
class multifunction_body_leaf
leaf for multifunction. OutputSet can be a std::tuple or a vector.
class multifunction_input
Implements methods for a function node that takes a type Input as input.
class multifunction_output
class node_cache
A node_cache maintains a std::queue of elements of type T. Each operation is protected by a lock.
struct num_arguments
struct num_arguments< port_ref_impl< N1, N2 > >
struct num_arguments< port_ref_impl< N1, N2 >(*)()>
struct pick_max
struct pick_one
struct pick_one< false, T1, T2 >
struct pick_one< true, T1, T2 >
struct pick_tuple_max
struct pick_tuple_max< 0, Tuple, Selector >
struct Policy
struct port_ref_impl
class predecessor_cache
A cache of predecessors that only supports try_get.
class priority_task_selector
class queueing_port
queueing join_port
class reservable_item_buffer
item_buffer with reservable front-end. NOTE: if reserving, do not
class reservable_predecessor_cache
An cache of predecessors that supports requests and reservations.
class reserving_port
The two-phase join port.
class round_robin_cache
A cache of successors that are put in a round-robin fashion.
class sequence
struct size_of
class source_body
A functor that takes no input and generates a value of type Output.
class source_body_leaf
The leaf for source_body.
class source_task_bypass
A task that calls a node's apply_body_bypass function with no input.
class streaming_device_with_key
struct streaming_node_traits
class successor_cache
An abstract cache of successors.
class successor_cache< continue_msg >
An abstract cache of successors, specialized to continue_msg.
class tagged_msg
struct tagged_null_type
struct type_plus_align
type mimicking std::pair but with trailing fill to ensure each element of an array
struct type_plus_align< T1, T2, 0 >
class type_to_key_function_body
class type_to_key_function_body< Input, Output & >
class type_to_key_function_body_leaf
class type_to_key_function_body_leaf< Input, Output &, B >
class unfolded_indexer_node
class unfolded_join_node
unfolded_join_node : passes input_ports_type to join_node_base. We build the input port type
class unfolded_join_node< 10, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 2, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 3, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 4, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 5, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 6, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 7, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 8, key_matching_port, OutputTuple, key_matching< K, KHash > >
class unfolded_join_node< 9, key_matching_port, OutputTuple, key_matching< K, KHash > >
class untyped_receiver
class untyped_sender
struct wrap_key_tuple_elements
struct wrap_key_tuple_elements< 1, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 10, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 2, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 3, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 4, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 5, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 6, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 7, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 8, PT, KeyTraits, TypeTuple >
struct wrap_key_tuple_elements< 9, PT, KeyTraits, TypeTuple >
struct wrap_tuple_elements
struct wrap_tuple_elements< 1, PT, TypeTuple >
struct wrap_tuple_elements< 10, PT, TypeTuple >
struct wrap_tuple_elements< 2, PT, TypeTuple >
struct wrap_tuple_elements< 3, PT, TypeTuple >
struct wrap_tuple_elements< 4, PT, TypeTuple >
struct wrap_tuple_elements< 5, PT, TypeTuple >
struct wrap_tuple_elements< 6, PT, TypeTuple >
struct wrap_tuple_elements< 7, PT, TypeTuple >
struct wrap_tuple_elements< 8, PT, TypeTuple >
struct wrap_tuple_elements< 9, PT, TypeTuple >
struct Wrapper
struct Wrapper< T[N]>
struct WrapperBase
Typedefs
typedef tbb::internal::uint64_t tag_value
typedef tbb::concurrent_priority_queue< graph_task *, graph_task_comparator > graph_task_priority_queue_t
Enumerations
enum op_stat { WAIT = 0, SUCCEEDED, FAILED }
Functions
template<typename V , typename T >
const V & cast_to (T const &t)
template<typename V , typename T >
bool is_a (T const &t)
template<size_t N, typename MOP >
tbb::flow::tuple_element< N, typename MOP::output_ports_type >::type & output_port (MOP &op)
void check_task_and_spawn (graph &g, task *t)
template<typename CompositeType >
void add_nodes_impl (CompositeType *, bool)
template<typename CompositeType , typename NodeType1 , typename... NodeTypes>
void add_nodes_impl (CompositeType *c_node, bool visible, const NodeType1 &n1, const NodeTypes &...n)
template<size_t N, typename JNT >
tbb::flow::tuple_element< N, typename JNT::input_ports_type >::type & input_port (JNT &jn)
templated function to refer to input ports of the join node
template<typename IndexerNodeBaseType , typename T , size_t K>
task * do_try_put (const T &v, void *p)
template<typename... Args>
void ignore_return_values (Args &&...)
template<typename T >
T or_return_values (T &&t)
template<typename T , typename... Rest>
T or_return_values (T &&t, Rest &&...rest)
opencl_device_list find_available_devices ()
void activate_graph (graph &g)
void deactivate_graph (graph &g)
bool is_graph_active (graph &g)
void spawn_in_graph_arena (graph &g, tbb::task &arena_task)
Spawns a task inside graph arena.
void add_task_to_graph_reset_list (graph &g, tbb::task *tp)
template<typename F >
void execute_in_graph_arena (graph &g, F &f)
Executes custom functor inside graph arena.
Typedef Documentation
typedef tbb::concurrent_priority_queue<graph_task*, graph_task_comparator> tbb::flow::interface10::internal::graph_task_priority_queue_t
Definition at line 172 of file _flow_graph_impl.h.
typedef tbb::internal::uint64_t tbb::flow::interface10::internal::tag_value
Definition at line 33 of file flow_graph.h.
Enumeration Type Documentation
enum tbb::flow::interface10::internal::op_stat
Enumerator
WAIT
SUCCEEDED
FAILED
Definition at line 710 of file flow_graph.h.
 {
Function Documentation
void tbb::flow::interface10::internal::activate_graph (graph & g) inline
Definition at line 454 of file _flow_graph_impl.h.
References tbb::flow::interface10::graph::my_is_active.
Referenced by tbb::flow::interface10::graph::reset().
{
     g.my_is_active = true;
 }
template<typename CompositeType > void tbb::flow::interface10::internal::add_nodes_impl (CompositeType * , bool)
Definition at line 883 of file flow_graph.h.
Referenced by tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::add_nodes(), tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::add_nodes(), tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::add_nodes(), tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::add_visible_nodes(), tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::add_visible_nodes(), and tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::add_visible_nodes().
 : graph_node(g), my_active(is_active), init_my_active(is_active),
template<typename CompositeType , typename NodeType1 , typename... NodeTypes> void tbb::flow::interface10::internal::add_nodes_impl (CompositeType * c_node, bool visible, const NodeType1 & n1, const NodeTypes &... n)
Definition at line 886 of file flow_graph.h.
References tbb::internal::fgt_node_with_body(), and tbb::flow::interface10::graph_node::my_graph.
     {
         my_successors.set_owner(this);
         tbb::internal::fgt_node_with_body( tbb::internal::FLOW_SOURCE_NODE, &this->my_graph,
                                            static_cast<sender<output_type> *>(this), this->my_body );
void tbb::flow::interface10::internal::add_task_to_graph_reset_list (graph & g, tbb::task * tp) inline
Definition at line 495 of file _flow_graph_impl.h.
References tbb::flow::interface10::graph::my_reset_task_list.
{
     g.my_reset_task_list.push_back(tp);
 }
template<typename V , typename T > const V& tbb::flow::interface10::internal::cast_to (T const & t)
Definition at line 705 of file flow_graph.h.
Referenced by tbb::flow::interface10a::write_once_node< T >::try_put_task().
 {
void tbb::flow::interface10::internal::check_task_and_spawn (graph & g, task * t) inline
Definition at line 652 of file flow_graph.h.
                         : SUCCESSFULLY_ENQUEUED;
     }
void tbb::flow::interface10::internal::deactivate_graph (graph & g) inline
Definition at line 458 of file _flow_graph_impl.h.
References tbb::flow::interface10::graph::my_is_active.
Referenced by tbb::flow::interface10::graph::reset().
{
     g.my_is_active = false;
 }
template<typename IndexerNodeBaseType , typename T , size_t K> task* tbb::flow::interface10::internal::do_try_put (const T & v, void * p)
Definition at line 38 of file flow_graph.h.
template<typename F > void tbb::flow::interface10::internal::execute_in_graph_arena (graph & g, F & f) inline
Executes custom functor inside graph arena.
Definition at line 468 of file _flow_graph_impl.h.
References __TBB_ASSERT, is_graph_active(), and tbb::flow::interface10::graph::my_task_arena.
Referenced by spawn_in_graph_arena(), and tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::try_put_impl().
{
     if (is_graph_active(g)) {
         __TBB_ASSERT(g.my_task_arena && g.my_task_arena->is_active(), NULL);
         g.my_task_arena->execute(f);
     }
 }
opencl_device_list tbb::flow::interface10::internal::find_available_devices () inline
Definition at line 284 of file flow_graph_opencl_node.h.
References tbb::flow::interface10::opencl_device_list::add(), d, tbb::flow::interface10::enforce_cl_retcode(), and p.
Referenced by tbb::flow::interface10::opencl_info::available_devices().
{
     opencl_device_list opencl_devices;
     cl_uint num_platforms;
     enforce_cl_retcode(clGetPlatformIDs(0, NULL, &num_platforms), "clGetPlatformIDs failed");
     std::vector<cl_platform_id> platforms(num_platforms);
     enforce_cl_retcode(clGetPlatformIDs(num_platforms, platforms.data(), NULL), "clGetPlatformIDs failed");
     cl_uint num_devices;
     std::vector<cl_platform_id>::iterator platforms_it = platforms.begin();
     cl_uint num_all_devices = 0;
     while (platforms_it != platforms.end()) {
         cl_int err = clGetDeviceIDs(*platforms_it, CL_DEVICE_TYPE_ALL, 0, NULL, &num_devices);
         if (err == CL_DEVICE_NOT_FOUND) {
             platforms_it = platforms.erase(platforms_it);
         }
         else {
             enforce_cl_retcode(err, "clGetDeviceIDs failed");
             num_all_devices += num_devices;
             ++platforms_it;
         }
     }
     std::vector<cl_device_id> devices(num_all_devices);
     std::vector<cl_device_id>::iterator devices_it = devices.begin();
     for (auto p = platforms.begin(); p != platforms.end(); ++p) {
         enforce_cl_retcode(clGetDeviceIDs((*p), CL_DEVICE_TYPE_ALL, (cl_uint)std::distance(devices_it, devices.end()), &*devices_it, &num_devices), "clGetDeviceIDs failed");
         devices_it += num_devices;
     }
     for (auto d = devices.begin(); d != devices.end(); ++d) {
         opencl_devices.add(opencl_device((*d)));
     }
     return opencl_devices;
 }
template<typename... Args> void tbb::flow::interface10::internal::ignore_return_values (Args && ...)
Definition at line 68 of file flow_graph.h.
 {
template<size_t N, typename JNT > tbb::flow::tuple_element<N, typename JNT::input_ports_type>::type& tbb::flow::interface10::internal::input_port (JNT & jn)
templated function to refer to input ports of the join node
Definition at line 1997 of file flow_graph.h.
Referenced by tbb::flow::interface10::limiter_node< T >::reset_node().
template<typename V , typename T > bool tbb::flow::interface10::internal::is_a (T const & t)
Definition at line 708 of file flow_graph.h.
Referenced by tbb::flow::interface10a::write_once_node< T >::try_put_task().
 {
bool tbb::flow::interface10::internal::is_graph_active (graph & g) inline
Definition at line 462 of file _flow_graph_impl.h.
References tbb::flow::interface10::graph::my_is_active.
Referenced by internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::create_body_task(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::create_forward_task(), internal::join_node_FE< reserving, InputTuple, OutputTuple >::decrement_port_count(), internal::join_node_FE< queueing, InputTuple, OutputTuple >::decrement_port_count(), internal::continue_input< Output, Policy >::execute(), execute_in_graph_arena(), internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::fill_output_buffer(), tbb::flow::interface10::limiter_node< T >::forward_task(), internal::join_node_base< JP, InputTuple, OutputTuple >::handle_operations(), tbb::flow::interface10::limiter_node< T >::register_predecessor(), tbb::flow::interface10::limiter_node< T >::register_successor(), tbb::flow::interface10a::overwrite_node< T >::register_successor(), tbb::flow::interface10::graph::run(), tbb::flow::interface10::source_node< Output >::spawn_put(), and tbb::flow::interface10::limiter_node< T >::try_put_task().
{
     return g.my_is_active;
 }
template<typename T > T tbb::flow::interface10::internal::or_return_values (T && t)
Definition at line 71 of file flow_graph.h.
 {
template<typename T , typename... Rest> T tbb::flow::interface10::internal::or_return_values (T && t, Rest &&... rest)
Definition at line 73 of file flow_graph.h.
               {
template<size_t N, typename MOP > tbb::flow::tuple_element<N, typename MOP::output_ports_type>::type& tbb::flow::interface10::internal::output_port (MOP & op)
Definition at line 648 of file flow_graph.h.
Referenced by tbb::flow::interface10a::write_once_node< T >::try_put_task().
                         : SUCCESSFULLY_ENQUEUED;
void tbb::flow::interface10::internal::spawn_in_graph_arena (graph & g, tbb::task & arena_task) inline
Spawns a task inside graph arena.
Non-preemptive priority pattern. The original task is submitted as a work item to the priority queue, and a new critical task is created to take and execute a work item with the highest known priority. The reference counting responsibility is transferred (via allocate_continuation) to the new task.
Non-preemptive priority pattern. The original task is submitted as a work item to the priority queue, and a new critical task is created to take and execute a work item with the highest known priority. The reference counting responsibility is transferred (via allocate_continuation) to the new task.
Definition at line 476 of file _flow_graph_impl.h.
References tbb::task::allocate_continuation(), execute_in_graph_arena(), tbb::internal::make_critical(), tbb::flow::interface10::graph::my_priority_queue, tbb::flow::internal::no_priority, and tbb::flow::interface10::graph_task::priority.
Referenced by internal::function_input< Input, Output, Policy, A >::apply_body_impl_bypass(), check_task_and_spawn(), internal::join_node_FE< reserving, InputTuple, OutputTuple >::decrement_port_count(), internal::join_node_FE< queueing, InputTuple, OutputTuple >::decrement_port_count(), internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::fill_output_buffer(), tbb::flow::interface10::limiter_node< T >::forward_task(), internal::join_node_base< JP, InputTuple, OutputTuple >::handle_operations(), tbb::flow::interface10::limiter_node< T >::register_predecessor(), tbb::flow::interface10::limiter_node< T >::register_successor(), tbb::flow::interface10a::overwrite_node< T >::register_successor(), tbb::flow::interface10::graph::reset(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::spawn_forward_task(), and tbb::flow::interface10::source_node< Output >::spawn_put().
{
     task* task_to_spawn = &arena_task;
 #if __TBB_PREVIEW_FLOW_GRAPH_PRIORITIES
     // TODO: change flow graph's interfaces to work with graph_task type instead of tbb::task.
     graph_task* t = static_cast<graph_task*>(&arena_task);
     if( t->priority != no_priority ) {
         task_to_spawn = new( t->allocate_continuation() ) priority_task_selector(g.my_priority_queue);
         tbb::internal::make_critical( *task_to_spawn );
         g.my_priority_queue.push(t);
     }
 #endif /* __TBB_PREVIEW_FLOW_GRAPH_PRIORITIES */
     graph::spawn_functor s_fn(*task_to_spawn);
     execute_in_graph_arena(g, s_fn);
 }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.