Intel(R) Threading Building Blocks Doxygen Documentation: tbb::strict_ppl::internal Namespace Reference
tbb::strict_ppl::internal Namespace Reference
Classes
class concurrent_queue_base_v3
base class of concurrent_queue
class concurrent_queue_iterator
Meets requirements of a forward iterator for STL.
class concurrent_queue_iterator_base_v3
Constness-independent portion of concurrent_queue_iterator.
class concurrent_queue_iterator_rep
class concurrent_queue_page_allocator
Abstract class to define interface for page allocation/deallocation.
struct concurrent_queue_rep
representation of concurrent_queue_base
struct concurrent_queue_rep_base
parts of concurrent_queue_rep that do not have references to micro_queue
class micro_queue
A queue using simple locking.
class micro_queue_pop_finalizer
struct tbb_remove_cv
Similar to C++0x std::remove_cv.
struct tbb_remove_cv< const T >
struct tbb_remove_cv< const volatile T >
struct tbb_remove_cv< volatile T >
Typedefs
typedef size_t ticket
Functions
bool is_valid_page (const concurrent_queue_rep_base::page *p)
template<typename C , typename T , typename U >
bool operator== (const concurrent_queue_iterator< C, T > &i, const concurrent_queue_iterator< C, U > &j)
template<typename C , typename T , typename U >
bool operator!= (const concurrent_queue_iterator< C, T > &i, const concurrent_queue_iterator< C, U > &j)
Typedef Documentation
typedef size_t tbb::strict_ppl::internal::ticket
Definition at line 60 of file _concurrent_queue_impl.h.
Function Documentation
bool tbb::strict_ppl::internal::is_valid_page (const concurrent_queue_rep_base::page * p) inline
Definition at line 106 of file _concurrent_queue_impl.h.
Referenced by tbb::strict_ppl::internal::micro_queue< T >::assign(), tbb::strict_ppl::internal::concurrent_queue_base_v3< T >::internal_finish_clear(), tbb::strict_ppl::internal::micro_queue< T >::invalidate_page_and_rethrow(), tbb::strict_ppl::internal::micro_queue< T >::push(), and tbb::strict_ppl::internal::micro_queue_pop_finalizer< T >::~micro_queue_pop_finalizer().
{
     return uintptr_t(p)>1;
 }
template<typename C , typename T , typename U > bool tbb::strict_ppl::internal::operator!= (const concurrent_queue_iterator< C, T > & i, const concurrent_queue_iterator< C, U > & j)
Definition at line 804 of file _concurrent_queue_impl.h.
References tbb::strict_ppl::internal::concurrent_queue_iterator_base_v3< tbb_remove_cv< Value >::type >::my_item.
{
     return i.my_item!=j.my_item;
 }
template<typename C , typename T , typename U > bool tbb::strict_ppl::internal::operator== (const concurrent_queue_iterator< C, T > & i, const concurrent_queue_iterator< C, U > & j)
Definition at line 799 of file _concurrent_queue_impl.h.
References tbb::strict_ppl::internal::concurrent_queue_iterator_base_v3< tbb_remove_cv< Value >::type >::my_item.
{
     return i.my_item==j.my_item;
 }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.