Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::interface10 Namespace Reference
tbb::flow::interface10 Namespace Reference
Namespaces
internal
opencl_info
Classes
class async_msg
class async_node
Implements async node.
class broadcast_node
Forwards messages of type T to all successors.
class buffer_node
Forwards messages in arbitrary order.
class callback
class callback_base
class composite_node
class composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >
class composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >
class composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >
class continue_msg
An empty class used for messages that mean "I'm done".
class continue_node
Implements an executable node that supports continue_msg -> Output.
class continue_receiver
Base class for receivers of completion messages.
class function_node
Implements a function node that supports Input -> Output.
class graph
The graph class.
class graph_iterator
class graph_node
The base of all graph nodes.
class graph_proxy
Pure virtual template classes that define interfaces for async communication.
struct graph_task
Base class for tasks generated by graph nodes.
class indexer_node
class indexer_node< T0 >
class indexer_node< T0, T1 >
class indexer_node< T0, T1, T2 >
class indexer_node< T0, T1, T2, T3 >
class indexer_node< T0, T1, T2, T3, T4 >
class indexer_node< T0, T1, T2, T3, T4, T5 >
class indexer_node< T0, T1, T2, T3, T4, T5, T6 >
class indexer_node< T0, T1, T2, T3, T4, T5, T6, T7 >
class indexer_node< T0, T1, T2, T3, T4, T5, T6, T7, T8 >
class join_node
class join_node< OutputTuple, key_matching< K, KHash > >
class join_node< OutputTuple, queueing >
class join_node< OutputTuple, reserving >
class limiter_node
Forwards messages only if the threshold has not been reached.
class multifunction_node
implements a function node that supports Input -> (set of outputs)
struct null_type
A generic null type.
class opencl_async_msg
class opencl_buffer
class opencl_buffer_impl
class opencl_device
class opencl_device_list
class opencl_factory
class opencl_memory
class opencl_node
class opencl_node< tuple< Ports... > >
class opencl_node< tuple< Ports... >, JP >
class opencl_node< tuple< Ports... >, JP, Factory >
class opencl_program
class opencl_range
class opencl_subbuffer
class priority_queue_node
Forwards messages in priority order.
class queue_node
Forwards messages in FIFO order.
class receiver
Pure virtual template class that defines a receiver of messages of type T.
class receiver_gateway
class run_and_put_task
class sender
Forward declaration section.
class sequencer_node
Forwards messages in sequence order.
class source_node
An executable node that acts as a source, i.e. it has no predecessors.
class split_node
split_node: accepts a tuple as input, forwards each element of the tuple to its
class streaming_node
class streaming_node< tuple< Ports... >, JP, StreamFactory >
Enumerations
enum access_type { read_write, write_only, read_only }
enum opencl_program_type { opencl_program_type::SOURCE, opencl_program_type::PRECOMPILED, opencl_program_type::SPIR }
enum reset_flags { rf_reset_protocol = 0, rf_reset_bodies = 1 << 0, rf_clear_edges = 1 << 1 }
Functions
static tbb::task * combine_tasks (graph &g, tbb::task *left, tbb::task *right)
void internal_make_edge (internal::untyped_sender &p, internal::untyped_receiver &s)
template<typename T >
void make_edge (sender< T > &p, receiver< T > &s)
Makes an edge between a single predecessor and a single successor.
template<typename TS , typename TR , typename = typename tbb::internal::enable_if<tbb::internal::is_same_type<TS, internal::untyped_sender>::value || tbb::internal::is_same_type<TR, internal::untyped_receiver>::value>::type>
void make_edge (TS &p, TR &s)
template<typename T >
void make_edge (sender< T > &p, receiver< typename T::async_msg_data_type > &s)
template<typename T >
void make_edge (sender< typename T::async_msg_data_type > &p, receiver< T > &s)
template<typename T , typename V , typename = typename T::output_ports_type, typename = typename V::input_ports_type>
void make_edge (T &output, V &input)
template<typename T , typename R , typename = typename T::output_ports_type>
void make_edge (T &output, receiver< R > &input)
template<typename S , typename V , typename = typename V::input_ports_type>
void make_edge (sender< S > &output, V &input)
void internal_remove_edge (internal::untyped_sender &p, internal::untyped_receiver &s)
template<typename T >
void remove_edge (sender< T > &p, receiver< T > &s)
Removes an edge between a single predecessor and a single successor.
template<typename TS , typename TR , typename = typename tbb::internal::enable_if<tbb::internal::is_same_type<TS, internal::untyped_sender>::value || tbb::internal::is_same_type<TR, internal::untyped_receiver>::value>::type>
void remove_edge (TS &p, TR &s)
template<typename T >
void remove_edge (sender< T > &p, receiver< typename T::async_msg_data_type > &s)
template<typename T >
void remove_edge (sender< typename T::async_msg_data_type > &p, receiver< T > &s)
template<typename T , typename V , typename = typename T::output_ports_type, typename = typename V::input_ports_type>
void remove_edge (T &output, V &input)
template<typename T , typename R , typename = typename T::output_ports_type>
void remove_edge (T &output, receiver< R > &input)
template<typename S , typename V , typename = typename V::input_ports_type>
void remove_edge (sender< S > &output, V &input)
template<typename Body , typename Node >
Body copy_body (Node &n)
Returns a copy of the body from a function or continue node.
template<int N1, int N2 = N1>
internal::port_ref_impl< N1, N2 > port_ref ()
void enforce_cl_retcode (cl_int err, std::string msg)
template<typename T >
T event_info (cl_event e, cl_event_info i)
template<typename T >
T device_info (cl_device_id d, cl_device_info i)
template<>
std::string device_info< std::string > (cl_device_id d, cl_device_info i)
template<typename T >
T platform_info (cl_platform_id p, cl_platform_info i)
template<>
std::string platform_info< std::string > (cl_platform_id p, cl_platform_info i)
template<typename K , typename T , typename Factory >
K key_from_message (const opencl_async_msg< T, Factory > &dmsg)
is_typedef (native_object_type)
is_typedef (memory_object_type)
template<typename T >
std::enable_if< is_native_object_type< T >::value, typename T::native_object_type >::type get_native_object (const T &t)
template<typename T >
std::enable_if<!is_native_object_type< T >::value, T >::type get_native_object (T t)
template<typename T , typename Factory >
std::enable_if< is_memory_object_type< T >::value >::type send_if_memory_object (opencl_device device, opencl_async_msg< T, Factory > &dmsg)
template<typename T >
std::enable_if< is_memory_object_type< T >::value >::type send_if_memory_object (opencl_device device, T &t)
template<typename T >
std::enable_if<!is_memory_object_type< T >::value >::type send_if_memory_object (opencl_device, T &)
template<typename T , typename Factory >
std::enable_if< is_memory_object_type< T >::value >::type receive_if_memory_object (const opencl_async_msg< T, Factory > &dmsg)
template<typename T >
std::enable_if<!is_memory_object_type< T >::value >::type receive_if_memory_object (const T &)
Enumeration Type Documentation
enum tbb::flow::interface10::access_type
Enumerator
read_write
write_only
read_only
Definition at line 623 of file flow_graph_opencl_node.h.
                  {
     read_write,
     write_only,
     read_only
 };
enum tbb::flow::interface10::opencl_program_type strong
Enumerator
SOURCE
PRECOMPILED
SPIR
Definition at line 1215 of file flow_graph_opencl_node.h.
{
     SOURCE,
     PRECOMPILED,
     SPIR
 };
enum tbb::flow::interface10::reset_flags
Enumerator
rf_reset_protocol
rf_reset_bodies
rf_clear_edges
Definition at line 150 of file _flow_graph_impl.h.
                  {
     rf_reset_protocol = 0,
     rf_reset_bodies = 1 << 0,  // delete the current node body, reset to a copy of the initial node body.
     rf_clear_edges = 1 << 1   // delete edges
 };
Function Documentation
static tbb::task* tbb::flow::interface10::combine_tasks (graph & g, tbb::task * left, tbb::task * right) inline static
Definition at line 171 of file flow_graph.h.
Referenced by internal::function_input< Input, Output, Policy, A >::apply_body_impl_bypass(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::forward_task(), internal::join_node_base< JP, InputTuple, OutputTuple >::handle_operations(), tbb::flow::interface10::queue_node< T, A >::try_put_and_add_task(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::try_put_and_add_task(), and internal::broadcast_cache< output_type >::try_put_task().
{
     // if no RHS task, don't change left.
     if (right == NULL) return left;
     // right != NULL
     if (left == NULL) return right;
     if (left == SUCCESSFULLY_ENQUEUED) return right;
     // left contains a task
     if (right != SUCCESSFULLY_ENQUEUED) {
         // both are valid tasks
         internal::spawn_in_graph_arena(g, *left);
         return right;
     }
     return left;
 }
template<typename Body , typename Node > Body tbb::flow::interface10::copy_body (Node & n)
Returns a copy of the body from a function or continue node.
Definition at line 3254 of file flow_graph.h.
Referenced by tbb::flow::interface10a::write_once_node< T >::try_put_task().
{
     return n.template copy_function_object<Body>();
 }
template<typename T > T tbb::flow::interface10::device_info (cl_device_id d, cl_device_info i)
Definition at line 73 of file flow_graph_opencl_node.h.
References enforce_cl_retcode().
{
     T res;
     enforce_cl_retcode(clGetDeviceInfo(d, i, sizeof(res), &res, NULL), "Failed to get OpenCL device information");
     return res;
 }
template<> std::string tbb::flow::interface10::device_info< std::string > (cl_device_id d, cl_device_info i) inline
Definition at line 80 of file flow_graph_opencl_node.h.
References enforce_cl_retcode().
{
     size_t required;
     enforce_cl_retcode(clGetDeviceInfo(d, i, 0, NULL, &required), "Failed to get OpenCL device information");
     char *buff = (char*)alloca(required);
     enforce_cl_retcode(clGetDeviceInfo(d, i, required, buff, NULL), "Failed to get OpenCL device information");
     return buff;
 }
void tbb::flow::interface10::enforce_cl_retcode (cl_int err, std::string msg) inline
Definition at line 58 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_async_msg< T, Factory >::clear_event(), tbb::flow::interface10::opencl_async_msg< T, Factory >::data(), device_info(), device_info< std::string >(), tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_map_buffer(), tbb::flow::interface10::opencl_factory< default_device_filter >::enqueue_unmap_buffer(), event_info(), tbb::flow::interface10::opencl_factory< default_device_filter >::finalize(), tbb::flow::interface10::internal::find_available_devices(), tbb::flow::interface10::opencl_program< Factory >::get_cl_kernel(), tbb::flow::interface10::opencl_program< Factory >::init(), tbb::flow::interface10::opencl_factory< default_device_filter >::init_once(), tbb::flow::interface10::opencl_factory< DeviceFilter >::kernel::kernel(), tbb::flow::interface10::opencl_async_msg< T, Factory >::opencl_async_msg(), tbb::flow::interface10::opencl_buffer_impl< Factory >::opencl_buffer_impl(), tbb::flow::interface10::opencl_program< Factory >::opencl_device_filter::opencl_device_filter(), tbb::flow::interface10::opencl_program< Factory >::opencl_program_builder::opencl_program_builder(), tbb::flow::interface10::opencl_async_msg< T, Factory >::operator=(), platform_info(), platform_info< std::string >(), tbb::flow::interface10::opencl_factory< default_device_filter >::process_one_arg(), tbb::flow::interface10::opencl_memory< Factory >::receive(), tbb::flow::interface10::opencl_async_msg< T, Factory >::register_callback(), tbb::flow::interface10::opencl_memory< Factory >::send(), tbb::flow::interface10::opencl_factory< default_device_filter >::send_kernel(), tbb::flow::interface10::opencl_factory< default_device_filter >::send_kernel_impl(), tbb::flow::interface10::opencl_async_msg< T, Factory >::set_event(), tbb::flow::interface10::opencl_factory< DeviceFilter >::kernel::~kernel(), tbb::flow::interface10::opencl_async_msg< T, Factory >::~opencl_async_msg(), tbb::flow::interface10::opencl_factory< default_device_filter >::~opencl_factory(), and tbb::flow::interface10::opencl_memory< Factory >::~opencl_memory().
{
     if (err != CL_SUCCESS) {
         std::cerr << msg << "; error code: " << err << std::endl;
         throw msg;
     }
 }
template<typename T > T tbb::flow::interface10::event_info (cl_event e, cl_event_info i)
Definition at line 66 of file flow_graph_opencl_node.h.
References enforce_cl_retcode().
{
     T res;
     enforce_cl_retcode(clGetEventInfo(e, i, sizeof(res), &res, NULL), "Failed to get OpenCL event information");
     return res;
 }
template<typename T > std::enable_if<is_native_object_type<T>::value, typename T::native_object_type>::type tbb::flow::interface10::get_native_object (const T & t)
Definition at line 736 of file flow_graph_opencl_node.h.
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::process_one_arg().
{
     return t.native_object();
 }
template<typename T > std::enable_if<!is_native_object_type<T>::value, T>::type tbb::flow::interface10::get_native_object (T t)
Definition at line 741 of file flow_graph_opencl_node.h.
{
     return t;
 }
void tbb::flow::interface10::internal_make_edge (internal::untyped_sender & p, internal::untyped_receiver & s) inline
Definition at line 3108 of file flow_graph.h.
References tbb::internal::fgt_make_edge(), and tbb::flow::interface10::internal::untyped_sender::register_successor().
Referenced by make_edge().
{
 #else
 template< typename T >
 inline void internal_make_edge( sender<T> &p, receiver<T> &s ) {
 #endif
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
     s.internal_add_built_predecessor(p);
     p.internal_add_built_successor(s);
 #endif
     p.register_successor( s );
     tbb::internal::fgt_make_edge( &p, &s );
 }
void tbb::flow::interface10::internal_remove_edge (internal::untyped_sender & p, internal::untyped_receiver & s) inline
Definition at line 3171 of file flow_graph.h.
References tbb::internal::fgt_remove_edge(), and tbb::flow::interface10::internal::untyped_sender::remove_successor().
Referenced by remove_edge().
{
 #else
 template< typename T >
 inline void internal_remove_edge( sender<T> &p, receiver<T> &s ) {
 #endif
     p.remove_successor( s );
 #if TBB_DEPRECATED_FLOW_NODE_EXTRACTION
     // TODO: should we try to remove p from the predecessor list of s, in case the edge is reversed?
     p.internal_delete_built_successor(s);
     s.internal_delete_built_predecessor(p);
 #endif
     tbb::internal::fgt_remove_edge( &p, &s );
 }
tbb::flow::interface10::is_typedef (native_object_type)
tbb::flow::interface10::is_typedef (memory_object_type)
template<typename K , typename T , typename Factory > K tbb::flow::interface10::key_from_message (const opencl_async_msg< T, Factory > & dmsg)
Definition at line 496 of file flow_graph_opencl_node.h.
References __TBB_STATIC_ASSERT, tbb::flow::interface10::opencl_async_msg< T, Factory >::data(), and tbb::flow::key_from_message().
{
     using tbb::flow::key_from_message;
     const T &t = dmsg.data( false );
     __TBB_STATIC_ASSERT( true, "" );
     return key_from_message<K, T>( t );
 }
template<typename T > void tbb::flow::interface10::make_edge (sender< T > & p, receiver< T > & s) inline
Makes an edge between a single predecessor and a single successor.
Definition at line 3123 of file flow_graph.h.
References internal_make_edge(), and type.
Referenced by make_edge(), streaming_node< tuple< Ports... >, JP, StreamFactory >::make_edges(), streaming_node< tuple< Ports... >, JP, StreamFactory >::make_Nth_edge(), and tbb::flow::interface10a::write_once_node< T >::try_put_task().
{
     internal_make_edge( p, s );
 }
template<typename TS , typename TR , typename = typename tbb::internal::enable_if<tbb::internal::is_same_type<TS, internal::untyped_sender>::value || tbb::internal::is_same_type<TR, internal::untyped_receiver>::value>::type> void tbb::flow::interface10::make_edge (TS & p, TR & s) inline
Definition at line 3131 of file flow_graph.h.
References internal_make_edge().
{
     internal_make_edge( p, s );
 }
template<typename T > void tbb::flow::interface10::make_edge (sender< T > & p, receiver< typename T::async_msg_data_type > & s) inline
Definition at line 3136 of file flow_graph.h.
References internal_make_edge().
{
     internal_make_edge( p, s );
 }
template<typename T > void tbb::flow::interface10::make_edge (sender< typename T::async_msg_data_type > & p, receiver< T > & s) inline
Definition at line 3141 of file flow_graph.h.
References internal_make_edge().
{
     internal_make_edge( p, s );
 }
template<typename T , typename V , typename = typename T::output_ports_type, typename = typename V::input_ports_type> void tbb::flow::interface10::make_edge (T & output, V & input) inline
Definition at line 3151 of file flow_graph.h.
References make_edge().
{
     make_edge(get<0>(output.output_ports()), get<0>(input.input_ports()));
 }
template<typename T , typename R , typename = typename T::output_ports_type> void tbb::flow::interface10::make_edge (T & output, receiver< R > & input) inline
Definition at line 3158 of file flow_graph.h.
References make_edge(), and S.
{
      make_edge(get<0>(output.output_ports()), input);
 }
template<typename S , typename V , typename = typename V::input_ports_type> void tbb::flow::interface10::make_edge (sender< S > & output, V & input) inline
Definition at line 3165 of file flow_graph.h.
References make_edge().
{
      make_edge(output, get<0>(input.input_ports()));
 }
template<typename T > T tbb::flow::interface10::platform_info (cl_platform_id p, cl_platform_info i)
Definition at line 91 of file flow_graph_opencl_node.h.
References enforce_cl_retcode().
{
     T res;
     enforce_cl_retcode(clGetPlatformInfo(p, i, sizeof(res), &res, NULL), "Failed to get OpenCL platform information");
     return res;
 }
template<> std::string tbb::flow::interface10::platform_info< std::string > (cl_platform_id p, cl_platform_info i) inline
Definition at line 98 of file flow_graph_opencl_node.h.
References enforce_cl_retcode().
{
     size_t required;
     enforce_cl_retcode(clGetPlatformInfo(p, i, 0, NULL, &required), "Failed to get OpenCL platform information");
     char *buff = (char*)alloca(required);
     enforce_cl_retcode(clGetPlatformInfo(p, i, required, buff, NULL), "Failed to get OpenCL platform information");
     return buff;
 }
template<int N1, int N2 = N1> internal::port_ref_impl<N1,N2> tbb::flow::interface10::port_ref ()
Definition at line 46 of file flow_graph.h.
Referenced by tbb::flow::interface10a::write_once_node< T >::try_put_task().
template<typename T , typename Factory > std::enable_if<is_memory_object_type<T>::value>::type tbb::flow::interface10::receive_if_memory_object (const opencl_async_msg< T, Factory > & dmsg)
Definition at line 770 of file flow_graph_opencl_node.h.
References d, tbb::flow::interface10::opencl_async_msg< T, Factory >::data(), tbb::flow::interface10::opencl_async_msg< T, Factory >::get_event(), and tbb::flow::interface10::opencl_async_msg< T, Factory >::set_event().
Referenced by tbb::flow::interface10::opencl_async_msg< T, Factory >::finalize().
{
     const T &t = dmsg.data( false );
     typedef typename T::memory_object_type mem_obj_t;
     mem_obj_t mem_obj = t.memory_object();
     opencl_async_msg<mem_obj_t, Factory> d( mem_obj );
     if ( dmsg.get_event() ) d.set_event( *dmsg.get_event() );
     mem_obj.receive( d );
     if ( d.get_event() ) dmsg.set_event( *d.get_event() );
 }
template<typename T > std::enable_if<!is_memory_object_type<T>::value>::type tbb::flow::interface10::receive_if_memory_object (const T &)
Definition at line 781 of file flow_graph_opencl_node.h.
 {}
template<typename T > void tbb::flow::interface10::remove_edge (sender< T > & p, receiver< T > & s) inline
Removes an edge between a single predecessor and a single successor.
Definition at line 3187 of file flow_graph.h.
References internal_remove_edge(), and type.
Referenced by remove_edge(), and tbb::flow::interface10a::write_once_node< T >::try_put_task().
{
     internal_remove_edge( p, s );
 }
template<typename TS , typename TR , typename = typename tbb::internal::enable_if<tbb::internal::is_same_type<TS, internal::untyped_sender>::value || tbb::internal::is_same_type<TR, internal::untyped_receiver>::value>::type> void tbb::flow::interface10::remove_edge (TS & p, TR & s) inline
Definition at line 3195 of file flow_graph.h.
References internal_remove_edge().
{
     internal_remove_edge( p, s );
 }
template<typename T > void tbb::flow::interface10::remove_edge (sender< T > & p, receiver< typename T::async_msg_data_type > & s) inline
Definition at line 3200 of file flow_graph.h.
References internal_remove_edge().
{
     internal_remove_edge( p, s );
 }
template<typename T > void tbb::flow::interface10::remove_edge (sender< typename T::async_msg_data_type > & p, receiver< T > & s) inline
Definition at line 3205 of file flow_graph.h.
References internal_remove_edge().
{
     internal_remove_edge( p, s );
 }
template<typename T , typename V , typename = typename T::output_ports_type, typename = typename V::input_ports_type> void tbb::flow::interface10::remove_edge (T & output, V & input) inline
Definition at line 3214 of file flow_graph.h.
References remove_edge().
{
     remove_edge(get<0>(output.output_ports()), get<0>(input.input_ports()));
 }
template<typename T , typename R , typename = typename T::output_ports_type> void tbb::flow::interface10::remove_edge (T & output, receiver< R > & input) inline
Definition at line 3221 of file flow_graph.h.
References remove_edge(), and S.
{
      remove_edge(get<0>(output.output_ports()), input);
 }
template<typename S , typename V , typename = typename V::input_ports_type> void tbb::flow::interface10::remove_edge (sender< S > & output, V & input) inline
Definition at line 3227 of file flow_graph.h.
References remove_edge(), and S.
{
      remove_edge(output, get<0>(input.input_ports()));
 }
template<typename T , typename Factory > std::enable_if<is_memory_object_type<T>::value>::type tbb::flow::interface10::send_if_memory_object (opencl_device device, opencl_async_msg< T, Factory > & dmsg)
Definition at line 747 of file flow_graph_opencl_node.h.
References d, tbb::flow::interface10::opencl_async_msg< T, Factory >::data(), tbb::flow::interface10::opencl_async_msg< T, Factory >::get_event(), and tbb::flow::interface10::opencl_async_msg< T, Factory >::set_event().
Referenced by tbb::flow::interface10::opencl_factory< default_device_filter >::send_data().
{
     const T &t = dmsg.data( false );
     typedef typename T::memory_object_type mem_obj_t;
     mem_obj_t mem_obj = t.memory_object();
     opencl_async_msg<mem_obj_t, Factory> d( mem_obj );
     if ( dmsg.get_event() ) d.set_event( *dmsg.get_event() );
     mem_obj.send( device, d );
     if ( d.get_event() ) dmsg.set_event( *d.get_event() );
 }
template<typename T > std::enable_if<is_memory_object_type<T>::value>::type tbb::flow::interface10::send_if_memory_object (opencl_device device, T & t)
Definition at line 758 of file flow_graph_opencl_node.h.
{
     typedef typename T::memory_object_type mem_obj_t;
     mem_obj_t mem_obj = t.memory_object();
     opencl_async_msg<mem_obj_t, typename mem_obj_t::opencl_factory_type> dmsg( mem_obj );
     mem_obj.send( device, dmsg );
 }
template<typename T > std::enable_if<!is_memory_object_type<T>::value>::type tbb::flow::interface10::send_if_memory_object (opencl_device , T &)
Definition at line 766 of file flow_graph_opencl_node.h.
 {};
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.