Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface7::internal Namespace Reference
tbb::interface7::internal Namespace Reference
Classes
class delegate_base
class delegated_function
class delegated_function< F, void >
class delegated_task
class padded_mutex
class padded_mutex< Mutex, false >
class padded_mutex< Mutex, true >
struct return_type_or_void
class task_arena_base
class wait_task
Functions
void __TBB_EXPORTED_FUNC isolate_within_arena (delegate_base &d, intptr_t reserved=0)
template<typename R , typename F >
R isolate_impl (F &f)
Variables
static const size_t cache_line_size = 64
Function Documentation
template<typename R , typename F > R tbb::interface7::internal::isolate_impl (F & f)
Definition at line 159 of file task_arena.h.
References tbb::interface7::internal::delegated_function< F, R >::consume_result(), d, and isolate_within_arena().
                      {
     delegated_function<F, R> d(f);
     isolate_within_arena(d);
     return d.consume_result();
 }
void __TBB_EXPORTED_FUNC tbb::interface7::internal::isolate_within_arena (delegate_base & d, intptr_t reserved = 0)
Referenced by tbb::interface7::internal::task_arena_base::internal_current_slot(), and isolate_impl().
Variable Documentation
const size_t tbb::interface7::internal::cache_line_size = 64 static
Definition at line 32 of file _mutex_padding.h.
Referenced by tbb::interface7::internal::padded_mutex< Mutex, true >::impl(), and tbb::operator!=().
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.