Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow Namespace Reference
tbb::flow Namespace Reference
Namespaces
interface10
interface10a
interface9
internal
Enumerations
enum concurrency { unlimited = 0, serial = 1 }
An enumeration the provides the two most common concurrency levels: unlimited and serial.
Functions
template<typename K , typename T >
K key_from_message (const T &t)
Enumeration Type Documentation
enum tbb::flow::concurrency
An enumeration the provides the two most common concurrency levels: unlimited and serial.
Enumerator
unlimited
serial
Definition at line 88 of file flow_graph.h.
 { unlimited = 0, serial = 1 };
Function Documentation
template<typename K , typename T > K tbb::flow::key_from_message (const T & t)
Definition at line 695 of file flow_graph.h.
Referenced by streaming_node< tuple< Ports... >, JP, StreamFactory >::device_selector< UserFunctor >::get_key(), tbb::flow::interface10::key_from_message(), and internal::unfolded_join_node< N, PT, OutputTuple, JP >::unfolded_join_node().
{
         return t.key();
     }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.