Intel(R) Threading Building Blocks Doxygen Documentation: tbb::internal Namespace Reference
tbb::internal Namespace Reference
Identifiers declared inside namespace internal should never be used directly by client code.
Namespaces
gcc_builtins
icc_intrinsics_port
msvc_inline_asm
msvc_intrinsics
rml
Classes
class __TBB_InitOnce
Class that supports TBB initialization.
class affinity_helper
class affinity_partitioner_base_v3
Defines entry point for affinity partitioner into tbb run-time library.
struct aligned_storage
struct aligned_storage< value_type, 1 >
class allocate_additional_child_of_proxy
class allocate_child_proxy
class allocate_continuation_proxy
class allocate_root_proxy
class allocate_root_with_context_proxy
class allocator_base
struct allocator_rebind
struct allocator_traits
struct allocator_type
Class for determining type of std::allocator<T>::value_type.
class allowed_parallelism_control
class arena
struct arena_base
The structure of an arena, except the array of slots.
struct arena_slot
struct arena_slot_line1
struct arena_slot_line2
class atomic_backoff
Class that implements exponential backoff.
struct atomic_impl
Base class that provides basic functionality for atomic<T> without fetch_and_add.
struct atomic_impl_with_arithmetic
Base class that provides basic functionality for atomic<T> with fetch_and_add.
struct atomic_load_store_traits
struct atomic_rep
struct atomic_rep< 1 >
struct atomic_rep< 2 >
struct atomic_rep< 4 >
struct atomic_rep< 8 >
struct atomic_selector
struct atomic_selector< 1 >
struct atomic_selector< 2 >
struct atomic_selector< 4 >
struct atomic_selector< 8 >
struct atomic_traits
class auto_empty_task
Smart holder for the empty task class with automatic destruction.
class basic_tls
Basic cross-platform wrapper class for TLS operations.
class binary_semaphore
binary_semaphore for concurrent monitor
class blocked_rangeNd_impl
struct bool_constant
class circular_doubly_linked_list_with_sentinel
Circular doubly-linked list with sentinel.
class concurrent_monitor
concurrent_monitor
class concurrent_queue_base_v3
For internal use only.
class concurrent_queue_base_v8
For internal use only.
class concurrent_queue_iterator
Meets requirements of a forward iterator for STL.
class concurrent_queue_iterator_base_v3
Type-independent portion of concurrent_queue_iterator.
class concurrent_queue_iterator_rep
class concurrent_queue_rep
Internal representation of a ConcurrentQueue.
class concurrent_vector_base_v3
Base class of concurrent vector implementation.
struct context_guard_helper
struct context_list_node_t
class control_storage
class cpu_ctl_env
struct cpu_ctl_env_space
class critical_section_v4
class custom_scheduler
A scheduler with a customized evaluation loop.
struct DefaultSchedulerTraits
Traits classes for scheduler.
struct enable_if
Enables one or the other code branches.
struct enable_if< true, T >
class fast_reverse_vector
Vector that grows without reallocations, and stores items in the reverse order.
class FastRandom
A fast random number generator.
struct fgt_internal_input_alias_helper
struct fgt_internal_output_alias_helper
class final_sum
Performs final scan for a leaf.
class finish_scan
Combine partial results.
class function_invoker
class function_task
class generic_scheduler
Work stealing task scheduler.
class governor
The class handles access to the single instance of market, and to TLS to keep scheduler instances.
struct hash_map_segment_base
class index_sequence
class input_buffer
A buffer of input items for a filter.
struct int_to_type
Utility helper structure to ease overload resolution.
struct IntelSchedulerTraits
class intrusive_list
Double linked list of items of type T that is derived from intrusive_list_node class.
class intrusive_list_base
List of element of type T, where T is derived from intrusive_list_node.
struct intrusive_list_node
Data structure to be inherited by the types that can form intrusive lists.
struct is_ref
struct is_ref< U & >
struct is_same_type
Detects whether two given types are the same.
struct is_same_type< W, W >
class lambda_reduce_body
Auxiliary class for parallel_reduce; for internal use only.
class lambda_scan_body
struct lane_selector_base
struct machine_load_store
struct machine_load_store_relaxed
struct machine_load_store_seq_cst
class mail_inbox
Class representing source of mail.
class mail_outbox
Class representing where mail is put.
struct make_index_sequence_impl
struct make_index_sequence_impl< 0, S... >
class market
class memptr_intrusive_list
Double linked list of items of type T containing a member of type intrusive_list_node.
struct micro_queue
A queue using simple locking.
class micro_queue_pop_finalizer
class mutex_copy_deprecated_and_disabled
class nested_arena_context
class no_assign
Base class for types that should not be assigned.
class no_copy
Base class for types that should not be copied or assigned.
struct padded
Pads type T to fill out to a multiple of cache line size.
struct padded_base
struct padded_base< T, S, 0 >
class parallel_for_body
Calls the function with values from range [begin, end) with a step provided.
class parallel_for_each_body_do
class parallel_for_each_body_for
struct parallel_for_each_impl
struct parallel_for_each_impl< Iterator, Function, std::random_access_iterator_tag >
class parallel_invoke_cleaner
class parallel_invoke_helper
class partition_type_base
Provides backward-compatible methods for partition objects without affinity.
class pipeline_cleaner
class pipeline_root_task
struct preceding_lane_selector
struct predicate_leq
struct queue_and_mutex
Essentially, this is just a pair of a queue and a mutex to protect the queue.
struct random_lane_selector
struct reverse
class scheduler
struct scheduler_properties
Bit-field representing properties of a sheduler.
struct scheduler_state
struct select_size_t_constant
A template to select either 32-bit or 64-bit constant as compile time, depending on machine word size.
class semaphore
Edsger Dijkstra's counting semaphore.
class spawner
class stack_size_control
class stage_task
class start_scan
Initial task to split the work.
struct STATIC_ASSERTION_FAILED
struct STATIC_ASSERTION_FAILED< false >
struct stored_pack
Allows to store a function parameter pack as a variable and later pass it to another function.
struct stored_pack< T, Types... >
struct stored_pack<>
struct strip
Strips its template type argument from cv- and ref-qualifiers.
struct strip< const T & >
struct strip< const T && >
struct strip< const T >
struct strip< const T(&)[N]>
struct strip< const volatile T & >
struct strip< const volatile T && >
struct strip< const volatile T >
struct strip< const volatile T(&)[N]>
struct strip< T & >
struct strip< T && >
struct strip< T(&)()>
Specialization for function pointers.
struct strip< T(&)[N]>
Specialization for arrays converts to a corresponding pointer.
struct strip< volatile T & >
struct strip< volatile T && >
struct strip< volatile T >
struct strip< volatile T(&)[N]>
struct subsequent_lane_selector
class sum_node
Split work to be done in the scan.
struct supports_impl
struct supports_impl< T, typename void_t< Checks< T >... >::type, Checks... >
class task_group_base
class task_handle_task
struct task_info
This structure is used to store task information in a input buffer.
class task_prefix
Memory prefix to a task object.
struct task_proxy
class task_scheduler_observer_v3
class task_stream
The container for "fairness-oriented" aka "enqueued" tasks.
class task_stream_accessor
class task_stream_accessor< back_nonnull_accessor >
class task_stream_base
class tbb_exception_ptr
Exception container that preserves the exact copy of the original exception.
class tbb_thread_v3
Versioned thread class.
struct thread_closure_0
struct thread_closure_1
Structure used to pass user function with 1 argument to thread.
struct thread_closure_2
struct thread_closure_base
class tls
More advanced TLS support template class.
class tls< T * >
struct type_with_alignment
struct type_with_alignment< 1 >
struct type_with_alignment< 16 >
struct type_with_alignment< 2 >
struct type_with_alignment< 32 >
struct type_with_alignment< 4 >
struct type_with_alignment< 64 >
struct type_with_alignment< 8 >
class unpadded_mail_outbox
Internal representation of mail_outbox, without padding.
class vector_iterator
Meets requirements of a forward iterator for STL and a Value for a blocked_range.*/.
struct version_tag_v3
struct void_t
std::void_t internal implementation (to avoid GCC < 4.7 "template aliases" absence)
class while_group_task
For internal use only.
class while_iteration_task
For internal use only.
class while_task
For internal use only.
Typedefs
typedef concurrent_vector_base_v3 concurrent_vector_base
typedef tbb::internal::true_type traits_true_type
typedef tbb::internal::false_type traits_false_type
typedef concurrent_queue_iterator_base_v3 concurrent_queue_iterator_base
template<typename T , template< typename > class... Checks>
using supports = typename supports_impl< T, void, Checks... >::type
template<std::size_t N>
using make_index_sequence = typename tbb::internal::make_index_sequence_impl< N >::type
typedef uint64_t machine_tsc_t
typedef enum tbb::internal::memory_order memory_order
typedef unsigned long Token
typedef long tokendiff_t
typedef intptr_t reference_count
A reference count.
typedef unsigned short affinity_id
An id as used for specifying affinity.
typedef intptr_t isolation_tag
A tag for task isolation.
typedef version_tag_v3 version_tag
typedef bool_constant< true > true_type
typedef bool_constant< false > false_type
typedef pthread_t thread_id_type
typedef circular_doubly_linked_list_with_sentinel waitset_t
typedef circular_doubly_linked_list_with_sentinel::node_t waitset_node_t
typedef concurrent_queue_base_v3 concurrent_queue_base
typedef size_t ticket
typedef __TBB_SCHEDULER_MUTEX_TYPE scheduler_mutex_type
Mutex type for global locks in the scheduler.
typedef uint32_t sem_count_t
for performance reasons, we want specialized binary_semaphore
typedef uintptr_t population_t
typedef void(* tls_dtor_t) (void *)
Enumerations
enum memory_order {
memory_order_relaxed, memory_order_consume, memory_order_acquire, memory_order_release,
memory_order_acq_rel, memory_order_seq_cst
}
enum exception_id {
eid_bad_alloc = 1, eid_bad_last_alloc, eid_nonpositive_step, eid_out_of_range,
eid_segment_range_error, eid_index_range_error, eid_missing_wait, eid_invalid_multiple_scheduling,
eid_improper_lock, eid_possible_deadlock, eid_operation_not_permitted, eid_condvar_wait_failed,
eid_invalid_load_factor, eid_reserved, eid_invalid_swap, eid_reservation_length_error,
eid_invalid_key, eid_user_abort, eid_reserved1, eid_bad_tagged_msg_cast,
eid_max
}
enum string_index { TBB_STRING_RESOURCE }
enum itt_relation {
__itt_relation_is_unknown = 0, __itt_relation_is_dependent_on, __itt_relation_is_sibling_of, __itt_relation_is_parent_of,
__itt_relation_is_continuation_of, __itt_relation_is_child_of, __itt_relation_is_continued_by, __itt_relation_is_predecessor_to
}
enum notify_type { prepare =0, cancel, acquired, releasing }
enum itt_domain_enum { ITT_DOMAIN_FLOW =0, ITT_DOMAIN_MAIN =1, ITT_DOMAIN_ALGO =2, ITT_NUM_DOMAINS }
enum task_extra_state {
es_version_1_task = 0, es_version_3_task = 1, es_task_enqueued = 0x10, es_task_proxy = 0x20,
es_ref_count_active = 0x40, es_task_is_stolen = 0x80
}
Definitions for bits in task_prefix::extra_state.
enum free_task_hint {
no_hint =0, local_task =1, small_task =2, small_local_task =3,
no_cache = 4, no_cache_small_task = no_cache | small_task
}
Optimization hint to free_task that enables it omit unnecessary tests and code.
enum task_stream_accessor_type { front_accessor = 0, back_nonnull_accessor }
enum do_once_state { do_once_uninitialized = 0, do_once_pending, do_once_executed, initialization_complete = do_once_executed }
One-time initialization states.
Functions
__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (full_fence)
__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (acquire)
__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (release)
__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (relaxed)
template<memory_semantics M, typename T >
void swap (atomic< T > &lhs, atomic< T > &rhs)
template<typename T >
atomic< T > & as_atomic (T &t)
size_t __TBB_EXPORTED_FUNC NFS_GetLineSize ()
Cache/sector line size.
void *__TBB_EXPORTED_FUNC NFS_Allocate (size_t n_element, size_t element_size, void *hint)
Allocate memory on cache/sector line boundary.
void __TBB_EXPORTED_FUNC NFS_Free (void *)
Free memory allocated by NFS_Allocate.
template<typename T >
void handle_unconstructed_elements (T *array, size_t n_of_elements)
Exception helper function.
void swap (concurrent_vector_base_v3::segment_t &lhs, concurrent_vector_base_v3::segment_t &rhs) __TBB_NOEXCEPT(true)
template<typename Container , typename T >
vector_iterator< Container, T > operator+ (ptrdiff_t offset, const vector_iterator< Container, T > &v)
template<typename Container , typename T , typename U >
bool operator== (const vector_iterator< Container, T > &i, const vector_iterator< Container, U > &j)
template<typename Container , typename T , typename U >
bool operator!= (const vector_iterator< Container, T > &i, const vector_iterator< Container, U > &j)
template<typename Container , typename T , typename U >
bool operator< (const vector_iterator< Container, T > &i, const vector_iterator< Container, U > &j)
template<typename Container , typename T , typename U >
bool operator> (const vector_iterator< Container, T > &i, const vector_iterator< Container, U > &j)
template<typename Container , typename T , typename U >
bool operator>= (const vector_iterator< Container, T > &i, const vector_iterator< Container, U > &j)
template<typename Container , typename T , typename U >
bool operator<= (const vector_iterator< Container, T > &i, const vector_iterator< Container, U > &j)
template<typename Container , typename T , typename U >
ptrdiff_t operator- (const vector_iterator< Container, T > &i, const vector_iterator< Container, U > &j)
template<typename MyAlloc , typename OtherAlloc >
void allocator_move_assignment (MyAlloc &my_allocator, OtherAlloc &other_allocator, traits_true_type)
template<typename MyAlloc , typename OtherAlloc >
void allocator_move_assignment (MyAlloc &, OtherAlloc &, traits_false_type)
template<typename MyAlloc , typename OtherAlloc >
void allocator_swap (MyAlloc &my_allocator, OtherAlloc &other_allocator, traits_true_type)
template<typename MyAlloc , typename OtherAlloc >
void allocator_swap (MyAlloc &, OtherAlloc &, traits_false_type)
template<typename C , typename T , typename U >
bool operator== (const concurrent_queue_iterator< C, T > &i, const concurrent_queue_iterator< C, U > &j)
template<typename C , typename T , typename U >
bool operator!= (const concurrent_queue_iterator< C, T > &i, const concurrent_queue_iterator< C, U > &j)
static void fgt_alias_port (void *, void *, bool)
static void fgt_composite (void *, void *)
static void fgt_graph (void *)
template<typename NodeType >
static void fgt_multioutput_node_desc (const NodeType *, const char *)
template<typename NodeType >
static void fgt_node_desc (const NodeType *, const char *)
static void fgt_graph_desc (void *, const char *)
static void fgt_body (void *, void *)
template<int N, typename PortsTuple >
static void fgt_multioutput_node (string_index, void *, void *, PortsTuple &)
template<int N, typename PortsTuple >
static void fgt_multioutput_node_with_body (string_index, void *, void *, PortsTuple &, void *)
template<int N, typename PortsTuple >
static void fgt_multiinput_node (string_index, void *, PortsTuple &, void *)
static void fgt_multiinput_multioutput_node (string_index, void *, void *)
static void fgt_node (string_index, void *, void *)
static void fgt_node (string_index, void *, void *, void *)
static void fgt_node (string_index, void *, void *, void *, void *)
static void fgt_node_with_body (string_index, void *, void *, void *)
static void fgt_node_with_body (string_index, void *, void *, void *, void *)
static void fgt_make_edge (void *, void *)
static void fgt_remove_edge (void *, void *)
static void fgt_begin_body (void *)
static void fgt_end_body (void *)
static void fgt_async_try_put_begin (void *, void *)
static void fgt_async_try_put_end (void *, void *)
static void fgt_async_reserve (void *, void *)
static void fgt_async_commit (void *, void *)
static void fgt_reserve_wait (void *)
static void fgt_release_wait (void *)
template<typename NodeType >
void fgt_multiinput_multioutput_node_desc (const NodeType *, const char *)
template<typename Container >
auto first (Container &c) -> decltype(begin(c))
template<typename Container >
auto first (const Container &c) -> decltype(begin(c))
template<typename Container >
auto last (Container &c) -> decltype(begin(c))
template<typename Container >
auto last (const Container &c) -> decltype(begin(c))
template<typename T , size_t size>
T * first (T(&arr)[size])
template<typename T , size_t size>
T * last (T(&arr)[size])
static void fgt_algorithm (string_index, void *, void *)
static void fgt_begin_algorithm (string_index, void *)
static void fgt_end_algorithm (void *)
static void fgt_alg_begin_body (string_index, void *, void *)
static void fgt_alg_end_body (void *)
template<typename F , typename Pack >
void call (F &&f, Pack &&p)
Calls the given function with arguments taken from a stored_pack.
template<typename Ret , typename F , typename Pack >
Ret call_and_return (F &&f, Pack &&p)
template<typename... Types>
stored_pack< Types... > save_pack (Types &&...types)
__TBB_MACHINE_DEFINE_ATOMICS (1, int8_t)
__TBB_MACHINE_DEFINE_ATOMICS (2, int16_t)
__TBB_MACHINE_DEFINE_ATOMICS (4, int32_t)
__TBB_MACHINE_DEFINE_ATOMICS (8, int64_t)
namespace msvc_inline_asm static inline void pause (uintptr_t delay)
size_t __TBB_EXPORTED_FUNC get_initial_auto_partitioner_divisor ()
void make_critical (task &t)
bool is_critical (task &t)
void __TBB_EXPORTED_FUNC deallocate_via_handler_v3 (void *p)
Deallocates memory using FreeHandler.
void *__TBB_EXPORTED_FUNC allocate_via_handler_v3 (size_t n)
Allocates memory using MallocHandler.
bool __TBB_EXPORTED_FUNC is_malloc_used_v3 ()
Returns true if standard malloc/free are used to work with memory.
void __TBB_EXPORTED_FUNC throw_bad_last_alloc_exception_v4 ()
Obsolete.
void __TBB_EXPORTED_FUNC throw_exception_v4 (exception_id)
Gathers all throw operators in one place.
void throw_exception (exception_id eid)
Versionless convenience wrapper for throw_exception_v4()
template<typename T , typename U >
void spin_wait_while_eq (const volatile T &location, U value)
Spin WHILE the value of the variable is equal to a given value.
template<typename T , typename U >
void spin_wait_until_eq (const volatile T &location, const U value)
Spin UNTIL the value of the variable is equal to a given value.
template<typename predicate_type >
void spin_wait_while (predicate_type condition)
template<typename T >
T __TBB_MaskedCompareAndSwap (volatile T *const ptr, const T value, const T comparand)
template<size_t S, typename T >
T __TBB_CompareAndSwapGeneric (volatile void *ptr, T value, T comparand)
template<>
int8_t __TBB_CompareAndSwapGeneric< 1, int8_t > (volatile void *ptr, int8_t value, int8_t comparand)
template<>
int16_t __TBB_CompareAndSwapGeneric< 2, int16_t > (volatile void *ptr, int16_t value, int16_t comparand)
template<>
int32_t __TBB_CompareAndSwapGeneric< 4, int32_t > (volatile void *ptr, int32_t value, int32_t comparand)
template<>
int64_t __TBB_CompareAndSwapGeneric< 8, int64_t > (volatile void *ptr, int64_t value, int64_t comparand)
template<size_t S, typename T >
T __TBB_FetchAndAddGeneric (volatile void *ptr, T addend)
template<size_t S, typename T >
T __TBB_FetchAndStoreGeneric (volatile void *ptr, T value)
template<typename T >
T __TBB_load_with_acquire (const volatile T &location)
template<typename T , typename V >
void __TBB_store_with_release (volatile T &location, V value)
void __TBB_store_with_release (volatile size_t &location, size_t value)
Overload that exists solely to avoid /Wp64 warnings.
template<typename T >
T __TBB_load_full_fence (const volatile T &location)
template<typename T , typename V >
void __TBB_store_full_fence (volatile T &location, V value)
void __TBB_store_full_fence (volatile size_t &location, size_t value)
Overload that exists solely to avoid /Wp64 warnings.
template<typename T >
T __TBB_load_relaxed (const volatile T &location)
template<typename T , typename V >
void __TBB_store_relaxed (volatile T &location, V value)
void __TBB_store_relaxed (volatile size_t &location, size_t value)
Overload that exists solely to avoid /Wp64 warnings.
__TBB_DefineTypeWithAlignment (8) __TBB_DefineTypeWithAlignment(16) __TBB_DefineTypeWithAlignment(32) __TBB_DefineTypeWithAlignment(64) typedef __TBB_machine_type_with_alignment_64 __TBB_machine_type_with_strictest_alignment
void __TBB_EXPORTED_FUNC call_itt_notify_v5 (int t, void *ptr)
void __TBB_EXPORTED_FUNC itt_store_pointer_with_release_v3 (void *dst, void *src)
void *__TBB_EXPORTED_FUNC itt_load_pointer_with_acquire_v3 (const void *src)
void *__TBB_EXPORTED_FUNC itt_load_pointer_v3 (const void *src)
void __TBB_EXPORTED_FUNC itt_make_task_group_v7 (itt_domain_enum domain, void *group, unsigned long long group_extra, void *parent, unsigned long long parent_extra, string_index name_index)
void __TBB_EXPORTED_FUNC itt_metadata_str_add_v7 (itt_domain_enum domain, void *addr, unsigned long long addr_extra, string_index key, const char *value)
void __TBB_EXPORTED_FUNC itt_relation_add_v7 (itt_domain_enum domain, void *addr0, unsigned long long addr0_extra, itt_relation relation, void *addr1, unsigned long long addr1_extra)
void __TBB_EXPORTED_FUNC itt_task_begin_v7 (itt_domain_enum domain, void *task, unsigned long long task_extra, void *parent, unsigned long long parent_extra, string_index name_index)
void __TBB_EXPORTED_FUNC itt_task_end_v7 (itt_domain_enum domain)
void __TBB_EXPORTED_FUNC itt_region_begin_v9 (itt_domain_enum domain, void *region, unsigned long long region_extra, void *parent, unsigned long long parent_extra, string_index name_index)
void __TBB_EXPORTED_FUNC itt_region_end_v9 (itt_domain_enum domain, void *region, unsigned long long region_extra)
template<typename T , typename U >
void itt_store_word_with_release (tbb::atomic< T > &dst, U src)
template<typename T >
T itt_load_word_with_acquire (const tbb::atomic< T > &src)
template<typename T >
void itt_store_word_with_release (T &dst, T src)
template<typename T >
T itt_load_word_with_acquire (const T &src)
template<typename T >
void itt_hide_store_word (T &dst, T src)
template<typename T >
T itt_hide_load_word (const T &src)
void call_itt_notify (notify_type, void *)
void itt_make_task_group (itt_domain_enum, void *, unsigned long long, void *, unsigned long long, string_index)
void itt_metadata_str_add (itt_domain_enum, void *, unsigned long long, string_index, const char *)
void itt_relation_add (itt_domain_enum, void *, unsigned long long, itt_relation, void *, unsigned long long)
void itt_task_begin (itt_domain_enum, void *, unsigned long long, void *, unsigned long long, string_index)
void itt_task_end (itt_domain_enum)
void itt_region_begin (itt_domain_enum, void *, unsigned long long, void *, unsigned long long, string_index)
void itt_region_end (itt_domain_enum, void *, unsigned long long)
void __TBB_EXPORTED_FUNC handle_perror (int error_code, const char *aux_info)
Throws std::runtime_error with what() returning error_code description prefixed with aux_info.
bool __TBB_false ()
void __TBB_EXPORTED_FUNC runtime_warning (const char *format,...)
Report a runtime warning.
template<typename T >
void poison_pointer (T *__TBB_atomic &)
template<typename T , typename U >
T punned_cast (U *ptr)
Cast between unrelated pointer types.
template<typename T >
bool is_aligned (T *pointer, uintptr_t alignment)
A function to check if passed in pointer is aligned on a specific border.
template<typename integer_type >
bool is_power_of_two (integer_type arg)
A function to check if passed integer is a power of 2.
template<typename argument_integer_type , typename divisor_integer_type >
argument_integer_type modulo_power_of_two (argument_integer_type arg, divisor_integer_type divisor)
A function to compute arg modulo divisor where divisor is a power of 2.
template<typename argument_integer_type , typename power2_integer_type >
bool is_power_of_two_at_least (argument_integer_type arg, power2_integer_type power2)
A function to determine if arg is a power of 2 at least as big as another power of 2.
template<typename T1 >
void suppress_unused_warning (const T1 &)
Utility template function to prevent "unused" warnings by various compilers.
template<typename T1 , typename T2 >
void suppress_unused_warning (const T1 &, const T2 &)
template<typename T1 , typename T2 , typename T3 >
void suppress_unused_warning (const T1 &, const T2 &, const T3 &)
void *__TBB_EXPORTED_FUNC allocate_closure_v3 (size_t size)
Allocate a closure.
void __TBB_EXPORTED_FUNC free_closure_v3 (void *)
Free a closure allocated by allocate_closure_v3.
void __TBB_EXPORTED_FUNC move_v3 (tbb_thread_v3 &t1, tbb_thread_v3 &t2)
tbb_thread_v3::id __TBB_EXPORTED_FUNC thread_get_id_v3 ()
void __TBB_EXPORTED_FUNC thread_yield_v3 ()
void __TBB_EXPORTED_FUNC thread_sleep_v3 (const tick_count::interval_t &i)
bool operator== (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator!= (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator< (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator<= (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator> (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
bool operator>= (tbb_thread_v3::id x, tbb_thread_v3::id y) __TBB_NOEXCEPT(true)
static bool occupy_slot (generic_scheduler *&slot, generic_scheduler &s)
static void * DummyMalloc (size_t size)
Dummy routine used for first indirect call via MallocHandler.
static void DummyFree (void *ptr)
Dummy routine used for first indirect call via FreeHandler.
static void * dummy_padded_allocate (size_t bytes, size_t alignment)
Dummy routine used for first indirect call via padded_allocate_handler.
static void dummy_padded_free (void *ptr)
Dummy routine used for first indirect call via padded_free_handler.
static void * padded_allocate (size_t bytes, size_t alignment)
static void padded_free (void *p)
void initialize_handler_pointers ()
Initialize the allocation/free handler pointers.
void initialize_cache_aligned_allocator ()
Defined in cache_aligned_allocator.cpp.
int __TBB_load_ittnotify ()
static unsigned calc_workers_soft_limit (unsigned workers_soft_limit, unsigned workers_hard_limit)
generic_scheduler * allocate_scheduler (market &m)
void Scheduler_OneTimeInitialization (bool itt_present)
Defined in scheduler.cpp.
void reset_extra_state (task *t)
void assert_task_valid (const task *)
bool ConcurrentWaitsEnabled (task &t)
void prolonged_pause ()
void set_one_bit (population_t &dest, int pos)
void clear_one_bit (population_t &dest, int pos)
bool is_bit_set (population_t val, int pos)
static bool GetBoolEnvironmentVariable (const char *name)
void DoOneTimeInitializations ()
Performs thread-safe lazy one-time general TBB initialization.
void itt_set_sync_name_v3 (void *obj, const tchar *name)
void fix_broken_rethrow ()
bool gcc_rethrow_exception_broken ()
void PrintVersion ()
Prints TBB version information on stderr.
void PrintExtraVersionInfo (const char *category, const char *format,...)
Prints arbitrary extra TBB version information on stderr.
void PrintRMLVersionInfo (void *arg, const char *server_info)
A callback routine to print RML version information on stderr.
bool cpu_has_speculation ()
check for transaction support.
int AvailableHwConcurrency ()
Returns maximal parallelism level supported by the current OS configuration.
void handle_win_error (int error_code)
Throws std::runtime_error with what() returning error_code description prefixed with aux_info.
template<typename T >
T min (const T &val1, const T &val2)
Utility template function returning lesser of the two values.
template<typename T >
T max (const T &val1, const T &val2)
Utility template function returning greater of the two values.
unsigned GetPrime (unsigned seed)
template<typename T1 , typename T2 , class Pred >
T1 atomic_update (tbb::atomic< T1 > &dst, T2 newValue, Pred compare)
Atomically replaces value of dst with newValue if they satisfy condition of compare predicate.
template<typename F >
void atomic_do_once (const F &initializer, atomic< do_once_state > &state)
One-time initialization function.
void run_initializer (void(*f)(), atomic< do_once_state > &state)
void run_initializer (bool(*f)(), atomic< do_once_state > &state)
void destroy_process_mask ()
Variables
static void *const vector_allocation_error_flag = reinterpret_cast<void*>(size_t(63))
Bad allocation marker.
const isolation_tag no_isolation = 0
static const int priority_stride_v4 = INT_MAX / 4
static const int priority_critical = priority_stride_v4 * 3 + priority_stride_v4 / 3 * 2
const uintptr_t NUM_NOTIFY_TYPES = 4
const size_t NFS_MaxLineSize = 128
Compile-time constant that is upper bound on cache line/sector size.
static void *(* MallocHandler)(size_t size) = &DummyMalloc
Handler for memory allocation.
static void(* FreeHandler)(void *pointer) = &DummyFree
Handler for memory deallocation.
static void *(* padded_allocate_handler)(size_t bytes, size_t alignment) = &dummy_padded_allocate
Handler for padded memory allocation.
static void(* padded_free_handler)(void *p) = &dummy_padded_free
Handler for padded memory deallocation.
static const dynamic_link_descriptor MallocLinkTable []
Table describing how to link the handlers.
static tbb::atomic< do_once_state > initialization_state
static size_t NFS_LineSize = 128
static void * static_invalid_page
generic_scheduler *(* AllocateSchedulerPtr)(market &)
Pointer to the scheduler factory function.
static const intptr_t num_priority_levels = 1
const size_t task_alignment = 32
Alignment for a task object.
const size_t task_prefix_reservation_size = ((sizeof(internal::task_prefix)-1)/task_alignment+1)*task_alignment
Number of bytes reserved for a task prefix.
const population_t one = 1
static const char _pad [NFS_MaxLineSize-sizeof(int)] = {}
Padding in order to prevent false sharing.
static __TBB_InitOnce __TBB_InitOnceHiddenInstance
static allowed_parallelism_control allowed_parallelism_ctl
static stack_size_control stack_size_ctl
static control_storage * controls [] = {&allowed_parallelism_ctl, &stack_size_ctl}
static const char VersionString [] = "\0" TBB_VERSION_STRINGS
static bool PrintVersionFlag = false
const size_t MByte = 1024*1024
const size_t ThreadStackSize = (sizeof(uintptr_t) <= 4 ? 2 : 4)*MByte
Detailed Description
Identifiers declared inside namespace internal should never be used directly by client code.
Typedef Documentation
typedef unsigned short tbb::internal::affinity_id
An id as used for specifying affinity.
Definition at line 124 of file task.h.
typedef concurrent_queue_base_v3 tbb::internal::concurrent_queue_base
Definition at line 44 of file concurrent_queue.cpp.
typedef concurrent_queue_iterator_base_v3 tbb::internal::concurrent_queue_iterator_base
Definition at line 1000 of file _concurrent_queue_impl.h.
typedef concurrent_vector_base_v3 tbb::internal::concurrent_vector_base
Definition at line 289 of file concurrent_vector.h.
typedef bool_constant<false> tbb::internal::false_type
Definition at line 473 of file tbb_stddef.h.
typedef intptr_t tbb::internal::isolation_tag
A tag for task isolation.
Definition at line 128 of file task.h.
typedef uint64_t tbb::internal::machine_tsc_t
Definition at line 57 of file gcc_ia32_common.h.
template<std::size_t N> using tbb::internal::make_index_sequence = typedef typename tbb::internal::make_index_sequence_impl<N>::type
Definition at line 196 of file _template_helpers.h.
typedef enum tbb::internal::memory_order tbb::internal::memory_order
typedef uintptr_t tbb::internal::population_t
Definition at line 50 of file task_stream.h.
typedef intptr_t tbb::internal::reference_count
A reference count.
Should always be non-negative. A signed type is used so that underflow can be detected.
Definition at line 121 of file task.h.
typedef __TBB_SCHEDULER_MUTEX_TYPE tbb::internal::scheduler_mutex_type
Mutex type for global locks in the scheduler.
Definition at line 137 of file scheduler_common.h.
typedef uint32_t tbb::internal::sem_count_t
for performance reasons, we want specialized binary_semaphore
Definition at line 96 of file semaphore.h.
template<typename T , template< typename > class... Checks> using tbb::internal::supports = typedef typename supports_impl<T, void, Checks...>::type
Definition at line 85 of file _template_helpers.h.
typedef pthread_t tbb::internal::thread_id_type
Definition at line 42 of file tbb_thread.h.
typedef size_t tbb::internal::ticket
Definition at line 46 of file concurrent_queue.cpp.
typedef void(* tbb::internal::tls_dtor_t) (void *)
Definition at line 34 of file tls.h.
typedef unsigned long tbb::internal::Token
Definition at line 44 of file pipeline.h.
typedef long tbb::internal::tokendiff_t
Definition at line 45 of file pipeline.h.
typedef tbb::internal::false_type tbb::internal::traits_false_type
Definition at line 47 of file _allocator_traits.h.
typedef tbb::internal::true_type tbb::internal::traits_true_type
Internal implementation of allocator traits, propagate_on_* use internal boolean_constant. In order to avoid code duplication, check what implementation of boolean constant will likely be passed.
Definition at line 46 of file _allocator_traits.h.
typedef bool_constant<true> tbb::internal::true_type
Definition at line 472 of file tbb_stddef.h.
typedef version_tag_v3 tbb::internal::version_tag
Definition at line 390 of file tbb_stddef.h.
typedef circular_doubly_linked_list_with_sentinel::node_t tbb::internal::waitset_node_t
Definition at line 93 of file concurrent_monitor.h.
typedef circular_doubly_linked_list_with_sentinel tbb::internal::waitset_t
Definition at line 92 of file concurrent_monitor.h.
Enumeration Type Documentation
enum tbb::internal::do_once_state
One-time initialization states.
Enumerator
do_once_uninitialized
No execution attempts have been undertaken yet.
do_once_pending
A thread is executing associated do-once routine.
do_once_executed
Do-once routine has been executed.
initialization_complete
Convenience alias.
Definition at line 193 of file tbb_misc.h.
                    {
     do_once_uninitialized = 0,
     do_once_pending,
     do_once_executed,
     initialization_complete = do_once_executed
 };
enum tbb::internal::exception_id
Enumerator
eid_bad_alloc
eid_bad_last_alloc
eid_nonpositive_step
eid_out_of_range
eid_segment_range_error
eid_index_range_error
eid_missing_wait
eid_invalid_multiple_scheduling
eid_improper_lock
eid_possible_deadlock
eid_operation_not_permitted
eid_condvar_wait_failed
eid_invalid_load_factor
eid_reserved
eid_invalid_swap
eid_reservation_length_error
eid_invalid_key
eid_user_abort
eid_reserved1
eid_bad_tagged_msg_cast
eid_max
The last enumerator tracks the number of defined IDs. It must remain the last one.
When adding new IDs, place them immediately before this comment (that is after all the existing IDs. NEVER insert new IDs between the existing ones.
Definition at line 68 of file tbb_exception.h.
                   {
     eid_bad_alloc = 1,
     eid_bad_last_alloc,
     eid_nonpositive_step,
     eid_out_of_range,
     eid_segment_range_error,
     eid_index_range_error,
     eid_missing_wait,
     eid_invalid_multiple_scheduling,
     eid_improper_lock,
     eid_possible_deadlock,
     eid_operation_not_permitted,
     eid_condvar_wait_failed,
     eid_invalid_load_factor,
     eid_reserved, // free slot for backward compatibility, can be reused.
     eid_invalid_swap,
     eid_reservation_length_error,
     eid_invalid_key,
     eid_user_abort,
     eid_reserved1,
 #if __TBB_SUPPORTS_WORKERS_WAITING_IN_TERMINATE
     // This id is used only from inside the library and only for support of CPF functionality.
     // So, if we drop the functionality, eid_reserved1 can be safely renamed and reused.
     eid_blocking_thread_join_impossible = eid_reserved1,
 #endif
     eid_bad_tagged_msg_cast,
     eid_max
 };
enum tbb::internal::free_task_hint
Optimization hint to free_task that enables it omit unnecessary tests and code.
Enumerator
no_hint
No hint.
local_task
Task is known to have been allocated by this scheduler.
small_task
Task is known to be a small task.
Task should be returned to the free list of some scheduler, possibly not this scheduler.
small_local_task
Bitwise-OR of local_task and small_task.
Task should be returned to free list of this scheduler.
no_cache
Disable caching for a small task.
no_cache_small_task
Task is known to be a small task and must not be cached.
Definition at line 190 of file scheduler_common.h.
                     {
     no_hint=0,
     local_task=1,
     small_task=2,
     small_local_task=3,
     no_cache = 4,
     no_cache_small_task = no_cache | small_task
 };
enum tbb::internal::itt_domain_enum
Enumerator
ITT_DOMAIN_FLOW
ITT_DOMAIN_MAIN
ITT_DOMAIN_ALGO
ITT_NUM_DOMAINS
Definition at line 137 of file tbb_profiling.h.
 { ITT_DOMAIN_FLOW=0, ITT_DOMAIN_MAIN=1, ITT_DOMAIN_ALGO=2, ITT_NUM_DOMAINS };
enum tbb::internal::itt_relation
Enumerator
__itt_relation_is_unknown
__itt_relation_is_dependent_on
"A is dependent on B" means that A cannot start until B completes
__itt_relation_is_sibling_of
"A is sibling of B" means that A and B were created as a group
__itt_relation_is_parent_of
"A is parent of B" means that A created B
__itt_relation_is_continuation_of
"A is continuation of B" means that A assumes the dependencies of B
__itt_relation_is_child_of
"A is child of B" means that A was created by B (inverse of is_parent_of)
__itt_relation_is_continued_by
"A is continued by B" means that B assumes the dependencies of A (inverse of is_continuation_of)
__itt_relation_is_predecessor_to
"A is predecessor to B" means that B cannot start until A completes (inverse of is_dependent_on)
Definition at line 35 of file tbb_profiling.h.
         {
         __itt_relation_is_unknown = 0,
         __itt_relation_is_dependent_on,
         __itt_relation_is_sibling_of,
         __itt_relation_is_parent_of,
         __itt_relation_is_continuation_of,
         __itt_relation_is_child_of,
         __itt_relation_is_continued_by,
         __itt_relation_is_predecessor_to
         };
enum tbb::internal::memory_order
Enumerator
memory_order_relaxed
memory_order_consume
memory_order_acquire
memory_order_release
memory_order_acq_rel
memory_order_seq_cst
Definition at line 78 of file icc_generic.h.
{
     memory_order_relaxed, memory_order_consume, memory_order_acquire,
     memory_order_release, memory_order_acq_rel, memory_order_seq_cst
 } memory_order;
enum tbb::internal::notify_type
Enumerator
prepare
cancel
acquired
releasing
Definition at line 129 of file tbb_profiling.h.
 {prepare=0, cancel, acquired, releasing};
enum tbb::internal::string_index
Enumerator
TBB_STRING_RESOURCE
Definition at line 29 of file tbb_profiling.h.
{
            #include "internal/_tbb_strings.h"
            NUM_STRINGS
         };
enum tbb::internal::task_extra_state
Definitions for bits in task_prefix::extra_state.
Enumerator
es_version_1_task
Tag for v1 tasks (i.e. tasks in TBB 1.0 and 2.0)
es_version_3_task
Tag for v3 tasks (i.e. tasks in TBB 2.1-2.2)
es_task_enqueued
Tag for enqueued tasks.
es_task_proxy
Tag for v3 task_proxy.
es_ref_count_active
Set if ref_count might be changed by another thread. Used for debugging.
es_task_is_stolen
Set if the task has been stolen.
Definition at line 166 of file scheduler_common.h.
                       {
     es_version_1_task = 0,
     es_version_3_task = 1,
 #if __TBB_PREVIEW_CRITICAL_TASKS
     es_task_critical = 0x8,
 #endif
     es_task_enqueued = 0x10,
     es_task_proxy = 0x20,
     es_ref_count_active = 0x40,
     es_task_is_stolen = 0x80
 };
enum tbb::internal::task_stream_accessor_type
Enumerator
front_accessor
back_nonnull_accessor
Definition at line 135 of file task_stream_extended.h.
 { front_accessor = 0, back_nonnull_accessor };
Function Documentation
template<size_t S, typename T > T tbb::internal::__TBB_CompareAndSwapGeneric (volatile void * ptr, T value, T comparand) inline
Referenced by __TBB_MaskedCompareAndSwap().
template<> int8_t tbb::internal::__TBB_CompareAndSwapGeneric< 1, int8_t > (volatile void * ptr, int8_t value, int8_t comparand) inline
Definition at line 480 of file tbb_machine.h.
References __TBB_machine_cmpswp1().
{
 #if __TBB_USE_GENERIC_PART_WORD_CAS
     return __TBB_MaskedCompareAndSwap<int8_t>((volatile int8_t *)ptr,value,comparand);
 #else
     return __TBB_machine_cmpswp1(ptr,value,comparand);
 #endif
 }
template<> int16_t tbb::internal::__TBB_CompareAndSwapGeneric< 2, int16_t > (volatile void * ptr, int16_t value, int16_t comparand) inline
Definition at line 489 of file tbb_machine.h.
References __TBB_machine_cmpswp2().
{
 #if __TBB_USE_GENERIC_PART_WORD_CAS
     return __TBB_MaskedCompareAndSwap<int16_t>((volatile int16_t *)ptr,value,comparand);
 #else
     return __TBB_machine_cmpswp2(ptr,value,comparand);
 #endif
 }
template<> int32_t tbb::internal::__TBB_CompareAndSwapGeneric< 4, int32_t > (volatile void * ptr, int32_t value, int32_t comparand) inline
Definition at line 498 of file tbb_machine.h.
References __TBB_machine_cmpswp4.
{
     // Cast shuts up /Wp64 warning
     return (int32_t)__TBB_machine_cmpswp4(ptr,value,comparand);
 }
template<> int64_t tbb::internal::__TBB_CompareAndSwapGeneric< 8, int64_t > (volatile void * ptr, int64_t value, int64_t comparand) inline
Definition at line 505 of file tbb_machine.h.
References __TBB_machine_cmpswp8.
{
     return __TBB_machine_cmpswp8(ptr,value,comparand);
 }
tbb::internal::__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (full_fence)
tbb::internal::__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (acquire)
tbb::internal::__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (release)
tbb::internal::__TBB_DECL_ATOMIC_LOAD_STORE_PRIMITIVES (relaxed)
tbb::internal::__TBB_DefineTypeWithAlignment (8)
bool tbb::internal::__TBB_false () inline
Definition at line 286 of file tbb_stddef.h.
 { return false; }
template<size_t S, typename T > T tbb::internal::__TBB_FetchAndAddGeneric (volatile void * ptr, T addend) inline
Definition at line 511 of file tbb_machine.h.
References tbb::internal::atomic_backoff::pause().
{
     T result;
     for( atomic_backoff b;;b.pause() ) {
         result = *reinterpret_cast<volatile T *>(ptr);
         // __TBB_CompareAndSwapGeneric presumed to have full fence.
         if( __TBB_CompareAndSwapGeneric<S,T> ( ptr, result+addend, result )==result )
             break;
     }
     return result;
 }
template<size_t S, typename T > T tbb::internal::__TBB_FetchAndStoreGeneric (volatile void * ptr, T value) inline
Definition at line 523 of file tbb_machine.h.
References __TBB_acquire_consistency_helper, __TBB_full_memory_fence, __TBB_machine_cmpswp8, __TBB_MACHINE_DEFINE_LOAD8_GENERIC_FENCED, __TBB_MACHINE_DEFINE_STORE8_GENERIC_FENCED, __TBB_machine_load8(), __TBB_machine_store8(), __TBB_release_consistency_helper, tbb::full_fence, tbb::load(), tbb::internal::machine_load_store< T, S >::load_with_acquire(), tbb::internal::atomic_backoff::pause(), tbb::store(), tbb::internal::machine_load_store< T, S >::store_with_release(), and value.
{
     T result;
     for( atomic_backoff b;;b.pause() ) {
         result = *reinterpret_cast<volatile T *>(ptr);
         // __TBB_CompareAndSwapGeneric presumed to have full fence.
         if( __TBB_CompareAndSwapGeneric<S,T> ( ptr, value, result )==result )
             break;
     }
     return result;
 }
template<typename T > T tbb::internal::__TBB_load_full_fence (const volatile T & location) inline
Definition at line 726 of file tbb_machine.h.
{
     return machine_load_store_seq_cst<T,sizeof(T)>::load( location );
 }
int tbb::internal::__TBB_load_ittnotify ()
Referenced by tbb::internal::__TBB_InitOnce::remove_ref().
template<typename T > T tbb::internal::__TBB_load_relaxed (const volatile T & location) inline
Definition at line 739 of file tbb_machine.h.
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), tbb::queuing_rw_mutex::scoped_lock::acquire(), tbb::internal::circular_doubly_linked_list_with_sentinel::add(), tbb::internal::generic_scheduler::cleanup_master(), tbb::internal::concurrent_monitor::commit_wait(), tbb::queuing_rw_mutex::scoped_lock::downgrade_to_reader(), tbb::internal::mail_outbox::empty(), tbb::internal::generic_scheduler::enqueue(), tbb::internal::circular_doubly_linked_list_with_sentinel::flush_to(), tbb::internal::allocate_root_proxy::free(), tbb::internal::generic_scheduler::generic_scheduler(), tbb::internal::generic_scheduler::get_task(), tbb::internal::generic_scheduler::init_stack_info(), tbb::internal::mail_outbox::internal_pop(), tbb::internal::arena::is_out_of_work(), tbb::internal::generic_scheduler::is_quiescent_local_task_pool_empty(), tbb::internal::generic_scheduler::is_quiescent_local_task_pool_reset(), tbb::task::note_affinity(), tbb::internal::concurrent_monitor::notify_all_relaxed(), tbb::internal::concurrent_monitor::notify_one_relaxed(), tbb::internal::concurrent_monitor::notify_relaxed(), tbb::internal::generic_scheduler::prepare_task_pool(), tbb::internal::concurrent_monitor::prepare_wait(), tbb::internal::generic_scheduler::publish_task_pool(), tbb::queuing_rw_mutex::scoped_lock::release(), tbb::internal::circular_doubly_linked_list_with_sentinel::remove(), tbb::internal::generic_scheduler::steal_task_from(), and tbb::queuing_rw_mutex::scoped_lock::upgrade_to_writer().
{
     return machine_load_store_relaxed<T,sizeof(T)>::load( const_cast<T&>(location) );
 }
template<typename T > T tbb::internal::__TBB_load_with_acquire (const volatile T & location) inline
Definition at line 713 of file tbb_machine.h.
Referenced by tbb::queuing_mutex::scoped_lock::acquire(), tbb::queuing_rw_mutex::scoped_lock::acquire(), tbb::internal::market::arena_in_need(), tbb::queuing_rw_mutex::scoped_lock::downgrade_to_reader(), tbb::internal::task_proxy::extract_task(), tbb::internal::__TBB_InitOnce::initialization_done(), tbb::interface7::internal::task_arena_base::internal_execute(), tbb::interface7::internal::task_arena_base::internal_wait(), tbb::internal::arena::is_out_of_work(), itt_load_pointer_with_acquire_v3(), itt_load_word_with_acquire(), tbb::internal::atomic_impl< tbb::strict_ppl::internal::concurrent_queue_rep_base::page * >::operator value_type(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::rehash_bucket(), tbb::queuing_rw_mutex::scoped_lock::release(), tbb::internal::market::release(), tbb::interface5::concurrent_priority_queue< T, Compare, A >::size(), tbb::queuing_mutex::scoped_lock::try_acquire(), tbb::queuing_rw_mutex::scoped_lock::try_acquire(), and tbb::queuing_rw_mutex::scoped_lock::upgrade_to_writer().
{
     return machine_load_store<T,sizeof(T)>::load_with_acquire( location );
 }
tbb::internal::__TBB_MACHINE_DEFINE_ATOMICS (1 , int8_t)
tbb::internal::__TBB_MACHINE_DEFINE_ATOMICS (2 , int16_t)
tbb::internal::__TBB_MACHINE_DEFINE_ATOMICS (4 , int32_t)
tbb::internal::__TBB_MACHINE_DEFINE_ATOMICS (8 , int64_t)
template<typename T > T tbb::internal::__TBB_MaskedCompareAndSwap (volatile T *const ptr, const T value, const T comparand) inline
Definition at line 436 of file tbb_machine.h.
References __TBB_CompareAndSwapGeneric(), __TBB_ENDIAN_BIG, __TBB_ENDIANNESS, __TBB_machine_cmpswp4, mask, tbb::internal::atomic_backoff::pause(), and value.
{
     struct endianness{ static bool is_big_endian(){
         #if __TBB_ENDIANNESS==__TBB_ENDIAN_DETECT
             const uint32_t probe = 0x03020100;
             return (((const char*)(&probe))[0]==0x03);
         #elif __TBB_ENDIANNESS==__TBB_ENDIAN_BIG || __TBB_ENDIANNESS==__TBB_ENDIAN_LITTLE
             return __TBB_ENDIANNESS==__TBB_ENDIAN_BIG;
         #else
             #error Unexpected value of __TBB_ENDIANNESS
         #endif
     }};
     const uint32_t byte_offset            = (uint32_t) ((uintptr_t)ptr & 0x3);
     volatile uint32_t * const aligned_ptr = (uint32_t*)((uintptr_t)ptr - byte_offset );
     // location of T within uint32_t for a C++ shift operation
     const uint32_t bits_to_shift     = 8*(endianness::is_big_endian() ? (4 - sizeof(T) - (byte_offset)) : byte_offset);
     const uint32_t mask              = (((uint32_t)1<<(sizeof(T)*8)) - 1 )<<bits_to_shift;
     // for signed T, any sign extension bits in cast value/comparand are immediately clipped by mask
     const uint32_t shifted_comparand = ((uint32_t)comparand << bits_to_shift)&mask;
     const uint32_t shifted_value     = ((uint32_t)value     << bits_to_shift)&mask;
     for( atomic_backoff b;;b.pause() ) {
         const uint32_t surroundings  = *aligned_ptr & ~mask ; // may have changed during the pause
         const uint32_t big_comparand = surroundings | shifted_comparand ;
         const uint32_t big_value     = surroundings | shifted_value     ;
         // __TBB_machine_cmpswp4 presumed to have full fence.
         // Cast shuts up /Wp64 warning
         const uint32_t big_result = (uint32_t)__TBB_machine_cmpswp4( aligned_ptr, big_value, big_comparand );
         if( big_result == big_comparand                    // CAS succeeded
           || ((big_result ^ big_comparand) & mask) != 0)   // CAS failed and the bits of interest have changed
         {
             return T((big_result & mask) >> bits_to_shift);
         }
         else continue;                                     // CAS failed but the bits of interest were not changed
     }
 }
template<typename T , typename V > void tbb::internal::__TBB_store_full_fence (volatile T & location, V value) inline
Definition at line 730 of file tbb_machine.h.
{
     machine_load_store_seq_cst<T,sizeof(T)>::store( location, T(value) );
 }
void tbb::internal::__TBB_store_full_fence (volatile size_t & location, size_t value) inline
Overload that exists solely to avoid /Wp64 warnings.
Definition at line 734 of file tbb_machine.h.
References value.
{
     machine_load_store_seq_cst<size_t,sizeof(size_t)>::store( location, value );
 }
template<typename T , typename V > void tbb::internal::__TBB_store_relaxed (volatile T & location, V value) inline
Definition at line 743 of file tbb_machine.h.
Referenced by tbb::internal::concurrent_monitor::abort_all_relaxed(), tbb::queuing_rw_mutex::scoped_lock::acquire(), tbb::internal::circular_doubly_linked_list_with_sentinel::add(), tbb::internal::circular_doubly_linked_list_with_sentinel::clear(), tbb::internal::generic_scheduler::commit_relocated_tasks(), tbb::internal::concurrent_monitor::concurrent_monitor(), tbb::internal::generic_scheduler::enqueue(), tbb::internal::circular_doubly_linked_list_with_sentinel::flush_to(), tbb::internal::allocate_root_proxy::free(), tbb::internal::generic_scheduler::get_task(), tbb::internal::generic_scheduler::leave_task_pool(), tbb::task::note_affinity(), tbb::internal::concurrent_monitor::notify_all_relaxed(), tbb::internal::concurrent_monitor::notify_one_relaxed(), tbb::internal::concurrent_monitor::notify_relaxed(), tbb::internal::concurrent_monitor::prepare_wait(), tbb::internal::mail_outbox::push(), tbb::queuing_rw_mutex::scoped_lock::release(), tbb::internal::circular_doubly_linked_list_with_sentinel::remove(), tbb::internal::generic_scheduler::reset_task_pool_and_leave(), tbb::internal::generic_scheduler::steal_task_from(), tbb::queuing_rw_mutex::scoped_lock::try_acquire(), and tbb::queuing_rw_mutex::scoped_lock::upgrade_to_writer().
{
     machine_load_store_relaxed<T,sizeof(T)>::store( const_cast<T&>(location), T(value) );
 }
void tbb::internal::__TBB_store_relaxed (volatile size_t & location, size_t value) inline
Overload that exists solely to avoid /Wp64 warnings.
Definition at line 747 of file tbb_machine.h.
{
     machine_load_store_relaxed<size_t,sizeof(size_t)>::store( const_cast<size_t&>(location), value );
 }
template<typename T , typename V > void tbb::internal::__TBB_store_with_release (volatile T & location, V value) inline
Definition at line 717 of file tbb_machine.h.
Referenced by tbb::queuing_rw_mutex::scoped_lock::acquire(), tbb::internal::generic_scheduler::cleanup_master(), tbb::internal::generic_scheduler::commit_spawned_tasks(), tbb::queuing_rw_mutex::scoped_lock::downgrade_to_reader(), tbb::internal::generic_scheduler::get_task(), internal::indexer_node_base< InputTuple, OutputType, StructTypes >::handle_operations(), internal::reserving_port< T >::handle_operations(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::handle_operations(), tbb::interface5::concurrent_priority_queue< T, Compare, A >::handle_operations(), internal::queueing_port< T >::handle_operations(), internal::key_matching_port< TraitsType >::handle_operations(), internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::handle_operations(), internal::join_node_base< JP, InputTuple, OutputTuple >::handle_operations(), tbb::flow::interface10::queue_node< T, A >::internal_consume(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::internal_consume(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::internal_forward(), tbb::flow::interface10::buffer_node< T, A >::internal_forward_task_impl(), tbb::flow::interface10::queue_node< T, A >::internal_pop(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::internal_pop(), tbb::flow::interface10::sequencer_node< T, A >::internal_push(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::internal_push(), tbb::flow::interface10::buffer_node< T, A >::internal_release(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::internal_release(), tbb::flow::interface10::queue_node< T, A >::internal_reserve(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::internal_reserve(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::internal_try_put_task(), itt_store_pointer_with_release_v3(), itt_store_word_with_release(), tbb::internal::generic_scheduler::nested_arena_exit(), tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::operator[](), tbb::internal::arena::process(), tbb::internal::generic_scheduler::publish_task_pool(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::rehash_bucket(), tbb::queuing_mutex::scoped_lock::release(), tbb::queuing_rw_mutex::scoped_lock::release(), tbb::queuing_rw_mutex::scoped_lock::release_internal_lock(), tbb::internal::generic_scheduler::release_task_pool(), tbb::interface6::internal::aggregator_generic< operation_type >::start_handle_operations(), tbb::interface6::aggregator_ext< internal::basic_handler >::start_handle_operations(), tbb::internal::atomic_impl< tbb::strict_ppl::internal::concurrent_queue_rep_base::page * >::store_with_release(), tbb::flow::interface10::internal::unfolded_join_node< 5, key_matching_port, OutputTuple, key_matching< K, KHash > >::unfolded_join_node(), tbb::flow::interface10::internal::unfolded_join_node< 6, key_matching_port, OutputTuple, key_matching< K, KHash > >::unfolded_join_node(), tbb::flow::interface10::internal::unfolded_join_node< 7, key_matching_port, OutputTuple, key_matching< K, KHash > >::unfolded_join_node(), tbb::internal::generic_scheduler::unlock_task_pool(), tbb::queuing_rw_mutex::scoped_lock::upgrade_to_writer(), and tbb::interface7::internal::delegated_task::~delegated_task().
{
     machine_load_store<T,sizeof(T)>::store_with_release( location, T(value) );
 }
void tbb::internal::__TBB_store_with_release (volatile size_t & location, size_t value) inline
Overload that exists solely to avoid /Wp64 warnings.
Definition at line 721 of file tbb_machine.h.
References value.
{
     machine_load_store<size_t,sizeof(size_t)>::store_with_release( location, value );
 }
void * tbb::internal::allocate_closure_v3 (size_t size)
Allocate a closure.
Definition at line 39 of file tbb_thread.cpp.
References allocate_via_handler_v3().
Referenced by tbb::internal::thread_closure_base::operator new().
 {
     return allocate_via_handler_v3( size );
 }
generic_scheduler* tbb::internal::allocate_scheduler (market & m) inline
Definition at line 41 of file scheduler.cpp.
References AllocateSchedulerPtr, and tbb::task_group_context::isolated.
Referenced by tbb::internal::generic_scheduler::create_master(), and tbb::internal::generic_scheduler::create_worker().
{
     return AllocateSchedulerPtr( m );
 }
void *__TBB_EXPORTED_FUNC tbb::internal::allocate_via_handler_v3 (size_t n)
Allocates memory using MallocHandler.
The function uses scalable_malloc if scalable allocator is available and malloc if not
Definition at line 228 of file cache_aligned_allocator.cpp.
References eid_bad_alloc, and throw_exception().
Referenced by tbb::tbb_allocator< T >::allocate(), allocate_closure_v3(), tbb::movable_exception< ExceptionData >::move(), tbb::interface5::reader_writer_lock::scoped_lock::operator new(), and tbb::interface5::reader_writer_lock::scoped_lock_read::operator new().
{
     void* result = (*MallocHandler) (n);
     if (!result) {
         throw_exception(eid_bad_alloc);
     }
     return result;
 }
template<typename MyAlloc , typename OtherAlloc > void tbb::internal::allocator_move_assignment (MyAlloc & my_allocator, OtherAlloc & other_allocator, traits_true_type) inline
Move assignment implementation for allocator if propagate_on_container_move_assignment == true_type. Noop if pocma == false_type.
Definition at line 54 of file _allocator_traits.h.
References tbb::move().
Referenced by tbb::concurrent_vector< padded_element, padded_allocator_type >::operator=().
{
     my_allocator = std::move(other_allocator);
 }
template<typename MyAlloc , typename OtherAlloc > void tbb::internal::allocator_move_assignment (MyAlloc & , OtherAlloc & , traits_false_type) inline
Definition at line 58 of file _allocator_traits.h.
 { /* NO MOVE */ }
template<typename MyAlloc , typename OtherAlloc > void tbb::internal::allocator_swap (MyAlloc & my_allocator, OtherAlloc & other_allocator, traits_true_type) inline
Swap implementation for allocators if propagate_on_container_swap == true_type. Noop if pocs == false_type.
Definition at line 64 of file _allocator_traits.h.
References swap().
Referenced by tbb::concurrent_vector< padded_element, padded_allocator_type >::swap().
{
     using std::swap;
     swap(my_allocator, other_allocator);
 }
template<typename MyAlloc , typename OtherAlloc > void tbb::internal::allocator_swap (MyAlloc & , OtherAlloc & , traits_false_type) inline
Definition at line 69 of file _allocator_traits.h.
 { /* NO SWAP */ }
template<typename T > atomic<T>& tbb::internal::as_atomic (T & t) inline
Definition at line 547 of file atomic.h.
Referenced by tbb::internal::generic_scheduler::acquire_task_pool(), tbb::interface5::internal::split_ordered_list< T, Allocator >::node::atomic_set_next(), tbb::CAS(), tbb::internal::market::create_one_job(), tbb::internal::task_proxy::extract_task(), tbb::internal::arena::free_arena(), tbb::internal::generic_scheduler::free_nonlocal_small_task(), tbb::internal::market::global_market(), tbb::internal::generic_scheduler::init_stack_info(), tbb::interface5::internal::hash_map_base::insert_new_node(), tbb::interface7::internal::task_arena_base::internal_initialize(), tbb::internal::mail_outbox::internal_pop(), tbb::interface7::internal::task_arena_base::internal_wait(), tbb::internal::market::is_arena_in_list(), tbb::internal::generic_scheduler::lock_task_pool(), tbb::interface7::task_arena::mark_initialized(), occupy_slot(), tbb::queuing_rw_mutex::scoped_lock::try_acquire_internal_lock(), and tbb::interface5::internal::split_ordered_list< value_type, typename concurrent_unordered_set_traits< Key, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type >::try_insert().
{
     return (atomic<T>&)t;
 }
void tbb::internal::assert_task_valid (const task *) inline
Definition at line 240 of file scheduler_common.h.
References tbb::task_group_context::concurrent_wait, ConcurrentWaitsEnabled(), tbb::task_group_context::exact_exception, tbb::tbb_exception::move(), tbb::task_group_context::my_version_and_traits, tbb::task::prefix(), and runtime_warning().
Referenced by tbb::internal::allocate_continuation_proxy::allocate(), tbb::internal::allocate_child_proxy::allocate(), tbb::internal::generic_scheduler::enqueue(), tbb::internal::generic_scheduler::generic_scheduler(), tbb::internal::generic_scheduler::get_task(), and tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all().
 {}
template<typename F > void tbb::internal::atomic_do_once (const F & initializer, atomic< do_once_state > & state)
One-time initialization function.
/param initializer Pointer to function without arguments The variant that returns bool is used for cases when initialization can fail and it is OK to continue execution, but the state should be reset so that the initialization attempt was repeated the next time. /param state Shared state associated with initializer that specifies its initialization state. Must be initially set to #uninitialized value (e.g. by means of default static zero initialization).
Definition at line 209 of file tbb_misc.h.
References tbb::internal::atomic_impl< T >::compare_and_swap(), do_once_executed, do_once_pending, do_once_uninitialized, run_initializer(), and spin_wait_while_eq().
Referenced by initialize_cache_aligned_allocator(), and tbb::internal::governor::one_time_init().
{
     // tbb::atomic provides necessary acquire and release fences.
     // The loop in the implementation is necessary to avoid race when thread T2
     // that arrived in the middle of initialization attempt by another thread T1
     // has just made initialization possible.
     // In such a case T2 has to rely on T1 to initialize, but T1 may already be past
     // the point where it can recognize the changed conditions.
     while ( state != do_once_executed ) {
         if( state == do_once_uninitialized ) {
             if( state.compare_and_swap( do_once_pending, do_once_uninitialized ) == do_once_uninitialized ) {
                 run_initializer( initializer, state );
                 break;
             }
         }
         spin_wait_while_eq( state, do_once_pending );
     }
 }
template<typename T1 , typename T2 , class Pred > T1 tbb::internal::atomic_update (tbb::atomic< T1 > & dst, T2 newValue, Pred compare)
Atomically replaces value of dst with newValue if they satisfy condition of compare predicate.
Return value semantics is the same as for CAS.
Definition at line 182 of file tbb_misc.h.
References tbb::internal::atomic_impl< T >::compare_and_swap().
Referenced by tbb::internal::arena::is_out_of_work(), and tbb::internal::arena::occupy_free_slot().
{
     T1 oldValue = dst;
     while ( compare(oldValue, newValue) ) {
         if ( dst.compare_and_swap((T1)newValue, oldValue) == oldValue )
             break;
         oldValue = dst;
     }
     return oldValue;
 }
int tbb::internal::AvailableHwConcurrency ()
Returns maximal parallelism level supported by the current OS configuration.
Referenced by tbb::internal::governor::default_num_threads().
static unsigned tbb::internal::calc_workers_soft_limit (unsigned workers_soft_limit, unsigned workers_hard_limit) static
Definition at line 90 of file market.cpp.
References tbb::internal::market::app_parallelism_limit(), tbb::internal::governor::default_num_threads(), and max().
Referenced by tbb::internal::market::global_market().
{
     if( int soft_limit = market::app_parallelism_limit() )
         workers_soft_limit = soft_limit-1;
     else // if user set no limits (yet), use market's parameter
         workers_soft_limit = max( governor::default_num_threads() - 1, workers_soft_limit );
     if( workers_soft_limit >= workers_hard_limit )
         workers_soft_limit = workers_hard_limit-1;
     return workers_soft_limit;
 }
template<typename F , typename Pack > void tbb::internal::call (F && f, Pack && p)
Calls the given function with arguments taken from a stored_pack.
Definition at line 162 of file _template_helpers.h.
References p.
Referenced by streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::enqueue(), streaming_node< tuple< Ports... >, JP, StreamFactory >::args_storage< Args >::send(), tbb::internal::stored_pack<>::stored_pack(), and tbb::internal::stored_pack< T, Types... >::stored_pack().
{
     strip<Pack>::type::template call<void>( std::forward<F>(f), std::forward<Pack>(p) );
 }
template<typename Ret , typename F , typename Pack > Ret tbb::internal::call_and_return (F && f, Pack && p)
Definition at line 167 of file _template_helpers.h.
References p.
Referenced by tbb::internal::stored_pack<>::stored_pack(), and tbb::internal::stored_pack< T, Types... >::stored_pack().
{
     return strip<Pack>::type::template call<Ret>( std::forward<F>(f), std::forward<Pack>(p) );
 }
void tbb::internal::call_itt_notify (notify_type , void *) inline
Definition at line 268 of file tbb_profiling.h.
Referenced by tbb::task::add_ref_count(), tbb::interface6::internal::aggregator_generic< operation_type >::execute(), tbb::interface6::aggregator_ext< internal::basic_handler >::execute_impl(), tbb::interface5::concurrent_priority_queue< T, Compare, A >::handle_operations(), itt_hide_load_word(), tbb::strict_ppl::internal::micro_queue< T >::pop(), tbb::strict_ppl::internal::micro_queue< T >::push(), tbb::interface6::aggregator_operation::start(), tbb::interface6::internal::aggregator_generic< operation_type >::start_handle_operations(), and tbb::interface6::aggregator_ext< internal::basic_handler >::start_handle_operations().
 {}
void tbb::internal::call_itt_notify_v5 (int t, void * ptr)
Definition at line 289 of file tbb_main.cpp.
References __itt_id_make(), addr, d, domain, itt_make_task_group_v7(), itt_metadata_str_add_v7(), itt_region_begin_v9(), itt_region_end_v9(), itt_relation_add_v7(), itt_task_begin_v7(), itt_task_end_v7(), key, parent, region_begin, relation, relation_add, task_begin, task_end, and value.
Referenced by itt_hide_load_word(), and itt_load_pointer_with_acquire_v3().
 {}
void tbb::internal::clear_one_bit (population_t & dest, int pos) inline
Definition at line 59 of file task_stream.h.
References __TBB_ASSERT, and __TBB_AtomicAND().
Referenced by tbb::internal::task_stream< num_priority_levels >::drain(), tbb::internal::task_stream< num_priority_levels >::pop(), tbb::internal::task_stream< num_priority_levels >::pop_specific(), tbb::internal::task_stream< num_priority_levels >::try_pop(), and tbb::internal::queue_and_mutex< T, mutex_t >::~queue_and_mutex().
{
     __TBB_ASSERT( pos>=0, NULL );
     __TBB_ASSERT( pos<int(sizeof(population_t)*CHAR_BIT), NULL );
     __TBB_AtomicAND( &dest, ~(one<<pos) );
 }
bool tbb::internal::ConcurrentWaitsEnabled (task & t) inline
Definition at line 296 of file scheduler_common.h.
Referenced by assert_task_valid(), and tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all().
 { return false; }
bool tbb::internal::cpu_has_speculation ()
check for transaction support.
Definition at line 221 of file tbb_misc.cpp.
Referenced by tbb::internal::governor::acquire_resources(), and destroy_process_mask().
{
 #if __TBB_TSX_AVAILABLE
 #if (__INTEL_COMPILER || __GNUC__ || _MSC_VER || __SUNPRO_CC)
     bool result = false;
     const int rtm_ebx_mask = 1<<11;
 #if _MSC_VER
     int info[4] = {0,0,0,0};
     const int reg_ebx = 1;
     __cpuidex(info, 7, 0);
     result = (info[reg_ebx] & rtm_ebx_mask)!=0;
 #elif __GNUC__ || __SUNPRO_CC
     int32_t reg_ebx = 0;
     int32_t reg_eax = 7;
     int32_t reg_ecx = 0;
     __asm__ __volatile__ ( "movl %%ebx, %%esi\n"
                            "cpuid\n"
                            "movl %%ebx, %0\n"
                            "movl %%esi, %%ebx\n"
                            : "=a"(reg_ebx) : "0" (reg_eax), "c" (reg_ecx) : "esi",
 #if __TBB_x86_64
                            "ebx",
 #endif
                            "edx"
                            );
     result = (reg_ebx & rtm_ebx_mask)!=0 ;
 #endif
     return result;
 #else
     #error Speculation detection not enabled for compiler
 #endif /* __INTEL_COMPILER || __GNUC__ || _MSC_VER */
 #else  /* __TBB_TSX_AVAILABLE */
     return false;
 #endif /* __TBB_TSX_AVAILABLE */
 }
void __TBB_EXPORTED_FUNC tbb::internal::deallocate_via_handler_v3 (void * p)
Deallocates memory using FreeHandler.
The function uses scalable_free if scalable allocator is available and free if not
Definition at line 236 of file cache_aligned_allocator.cpp.
References p.
Referenced by tbb::tbb_allocator< T >::deallocate(), tbb::movable_exception< ExceptionData >::destroy(), free_closure_v3(), tbb::interface5::reader_writer_lock::scoped_lock::operator delete(), tbb::interface5::reader_writer_lock::scoped_lock_read::operator delete(), and tbb::tbb_exception::operator delete().
{
     if( p ) {
         (*FreeHandler)( p );
     }
 }
void tbb::internal::destroy_process_mask () inline
Definition at line 262 of file tbb_misc.h.
References cpu_has_speculation(), fix_broken_rethrow(), and gcc_rethrow_exception_broken().
Referenced by tbb::internal::governor::release_resources(), and run_initializer().
 {}
void tbb::internal::DoOneTimeInitializations ()
Performs thread-safe lazy one-time general TBB initialization.
Definition at line 214 of file tbb_main.cpp.
References _pad, tbb::internal::__TBB_InitOnce::add_ref(), tbb::internal::governor::default_num_threads(), GetBoolEnvironmentVariable(), tbb::internal::__TBB_InitOnce::initialization_done(), initialize_cache_aligned_allocator(), tbb::internal::governor::initialize_rml_factory(), tbb::internal::__TBB_InitOnce::ITT_DoUnsafeOneTimeInitialization, tbb::internal::__TBB_InitOnce::lock(), tbb::internal::governor::print_version_info(), PrintExtraVersionInfo(), PrintVersion(), tbb::internal::__TBB_InitOnce::remove_ref(), Scheduler_OneTimeInitialization(), suppress_unused_warning(), tbb::internal::governor::terminate_auto_initialized_scheduler(), and tbb::internal::__TBB_InitOnce::unlock().
Referenced by tbb::internal::governor::one_time_init().
{
     suppress_unused_warning(_pad);
     __TBB_InitOnce::lock();
     // No fence required for load of InitializationDone, because we are inside a critical section.
     if( !__TBB_InitOnce::InitializationDone ) {
         __TBB_InitOnce::add_ref();
         if( GetBoolEnvironmentVariable("TBB_VERSION") )
             PrintVersion();
         bool itt_present = false;
 #if DO_ITT_NOTIFY
         ITT_DoUnsafeOneTimeInitialization();
         itt_present = ITT_Present;
 #endif /* DO_ITT_NOTIFY */
         initialize_cache_aligned_allocator();
         governor::initialize_rml_factory();
         Scheduler_OneTimeInitialization( itt_present );
         // Force processor groups support detection
         governor::default_num_threads();
         // Dump version data
         governor::print_version_info();
         PrintExtraVersionInfo( "Tools support", itt_present ? "enabled" : "disabled" );
         __TBB_InitOnce::InitializationDone = true;
     }
     __TBB_InitOnce::unlock();
 }
static void * tbb::internal::dummy_padded_allocate (size_t bytes, size_t alignment) static
Dummy routine used for first indirect call via padded_allocate_handler.
Executed on very first call through padded_allocate_handler.
Definition at line 155 of file cache_aligned_allocator.cpp.
References __TBB_ASSERT, initialize_cache_aligned_allocator(), and padded_allocate_handler.
{
     initialize_cache_aligned_allocator();
     __TBB_ASSERT( padded_allocate_handler!=&dummy_padded_allocate, NULL );
     return (*padded_allocate_handler)(bytes, alignment);
 }
static void tbb::internal::dummy_padded_free (void * ptr) static
Dummy routine used for first indirect call via padded_free_handler.
Executed on very first call through padded_free_handler.
Definition at line 162 of file cache_aligned_allocator.cpp.
References __TBB_ASSERT, initialize_cache_aligned_allocator(), and padded_free_handler.
{
     initialize_cache_aligned_allocator();
     __TBB_ASSERT( padded_free_handler!=&dummy_padded_free, NULL );
     (*padded_free_handler)( ptr );
 }
static void tbb::internal::DummyFree (void * ptr) static
Dummy routine used for first indirect call via FreeHandler.
Executed on very first call through FreeHandler.
Definition at line 148 of file cache_aligned_allocator.cpp.
References __TBB_ASSERT, FreeHandler, and initialize_cache_aligned_allocator().
Referenced by is_malloc_used_v3().
{
     initialize_cache_aligned_allocator();
     __TBB_ASSERT( FreeHandler!=&DummyFree, NULL );
     (*FreeHandler)( ptr );
 }
static void * tbb::internal::DummyMalloc (size_t size) static
Dummy routine used for first indirect call via MallocHandler.
Executed on very first call through MallocHandler.
Definition at line 141 of file cache_aligned_allocator.cpp.
References __TBB_ASSERT, initialize_cache_aligned_allocator(), MallocHandler, and size.
Referenced by initialize_handler_pointers(), and is_malloc_used_v3().
{
     initialize_cache_aligned_allocator();
     __TBB_ASSERT( MallocHandler!=&DummyMalloc, NULL );
     return (*MallocHandler)( size );
 }
static void tbb::internal::fgt_alg_begin_body (string_index , void * , void *) inline static
Definition at line 51 of file _tbb_trace_impl.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
 { }
static void tbb::internal::fgt_alg_end_body (void *) inline static
Definition at line 52 of file _tbb_trace_impl.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
 { }
static void tbb::internal::fgt_algorithm (string_index , void * , void *) inline static
Definition at line 48 of file _tbb_trace_impl.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::start_for().
 { }
static void tbb::internal::fgt_alias_port (void * , void * , bool) inline static
Definition at line 270 of file _flow_graph_trace_impl.h.
Referenced by add_nodes_impl().
 { }
static void tbb::internal::fgt_async_commit (void * , void *) inline static
Definition at line 313 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::receiver_gateway_impl::release_wait().
 { }
static void tbb::internal::fgt_async_reserve (void * , void *) inline static
Definition at line 312 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::receiver_gateway_impl::reserve_wait().
 { }
static void tbb::internal::fgt_async_try_put_begin (void * , void *) inline static
Definition at line 310 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::try_put_impl().
 { }
static void tbb::internal::fgt_async_try_put_end (void * , void *) inline static
Definition at line 311 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::try_put_impl().
 { }
static void tbb::internal::fgt_begin_algorithm (string_index , void *) inline static
Definition at line 49 of file _tbb_trace_impl.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
 { }
static void tbb::internal::fgt_begin_body (void *) inline static
Definition at line 307 of file _flow_graph_trace_impl.h.
Referenced by internal::continue_input< Output, Policy >::apply_body_bypass(), internal::function_input< Input, Output, Policy, A >::apply_body_impl(), and internal::multifunction_input< Input, OutputPortSet, Policy, A >::apply_body_impl_bypass().
 { }
static void tbb::internal::fgt_body (void * , void *) inline static
Definition at line 284 of file _flow_graph_trace_impl.h.
 { }
static void tbb::internal::fgt_composite (void * , void *) inline static
Definition at line 272 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::composite_node(), tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::composite_node(), tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::reset_node(), and tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::reset_node().
 { }
static void tbb::internal::fgt_end_algorithm (void *) inline static
Definition at line 50 of file _tbb_trace_impl.h.
Referenced by tbb::interface9::internal::start_for< Range, Body, Partitioner >::run().
 { }
static void tbb::internal::fgt_end_body (void *) inline static
Definition at line 308 of file _flow_graph_trace_impl.h.
Referenced by internal::continue_input< Output, Policy >::apply_body_bypass(), internal::function_input< Input, Output, Policy, A >::apply_body_impl(), and internal::multifunction_input< Input, OutputPortSet, Policy, A >::apply_body_impl_bypass().
 { }
static void tbb::internal::fgt_graph (void *) inline static
Definition at line 274 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::internal::key_matching_port< TraitsType >::try_put_task().
 { }
static void tbb::internal::fgt_graph_desc (void * , const char *) inline static
Definition at line 282 of file _flow_graph_trace_impl.h.
 { }
static void tbb::internal::fgt_make_edge (void * , void *) inline static
Definition at line 304 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::internal_make_edge().
 { }
static void tbb::internal::fgt_multiinput_multioutput_node (string_index , void * , void *) inline static
Definition at line 295 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::composite_node(), tbb::flow::interface10::opencl_node< tuple< Ports... >, JP, Factory >::opencl_node(), and tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::reset_node().
 { }
template<typename NodeType > void tbb::internal::fgt_multiinput_multioutput_node_desc (const NodeType * , const char *)
Definition at line 318 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::add_nodes(), tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::add_nodes(), tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::add_nodes(), tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple< OutputTypes... > >::reset_node(), tbb::flow::interface10::composite_node< tbb::flow::tuple< InputTypes... >, tbb::flow::tuple<> >::reset_node(), and tbb::flow::interface10::composite_node< tbb::flow::tuple<>, tbb::flow::tuple< OutputTypes... > >::reset_node().
 { }
template<int N, typename PortsTuple > static void tbb::internal::fgt_multiinput_node (string_index , void * , PortsTuple & , void *) inline static
Definition at line 293 of file _flow_graph_trace_impl.h.
 { }
template<int N, typename PortsTuple > static void tbb::internal::fgt_multioutput_node (string_index , void * , void * , PortsTuple &) inline static
Definition at line 287 of file _flow_graph_trace_impl.h.
 { }
template<typename NodeType > static void tbb::internal::fgt_multioutput_node_desc (const NodeType * , const char *) inline static
Definition at line 277 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::async_node< Input, Output, Policy, Allocator >::gateway(), and tbb::flow::interface10::internal::join_node_FE< key_matching< K, KHash >, InputTuple, OutputTuple >::tuple_build_may_succeed().
 { }
template<int N, typename PortsTuple > static void tbb::internal::fgt_multioutput_node_with_body (string_index , void * , void * , PortsTuple & , void *) inline static
Definition at line 290 of file _flow_graph_trace_impl.h.
 { }
static void tbb::internal::fgt_node (string_index , void * , void *) inline static
Definition at line 297 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::broadcast_node< T >::broadcast_node(), tbb::flow::interface10::buffer_node< T, A >::buffer_node(), tbb::flow::interface10::limiter_node< T >::limiter_node(), tbb::flow::interface10a::overwrite_node< T >::overwrite_node(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::priority_queue_node(), tbb::flow::interface10::queue_node< T, A >::queue_node(), tbb::flow::interface10::sequencer_node< T, A >::sequencer_node(), tbb::flow::interface10::internal::join_node_base< JP, InputTuple, OutputTuple >::try_get(), and tbb::flow::interface10a::write_once_node< T >::write_once_node().
 { }
static void tbb::internal::fgt_node (string_index , void * , void * , void *) inline static
Definition at line 298 of file _flow_graph_trace_impl.h.
 { }
static void tbb::internal::fgt_node (string_index , void * , void * , void * , void *) inline static
Definition at line 299 of file _flow_graph_trace_impl.h.
 { }
template<typename NodeType > static void tbb::internal::fgt_node_desc (const NodeType * , const char *) inline static
Definition at line 280 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::broadcast_node< T >::broadcast_node(), tbb::flow::interface10::continue_node< Output, Policy >::continue_node(), tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::function_node(), tbb::flow::interface10::indexer_node< T0 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2, T3 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2, T3, T4 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2, T3, T4, T5 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2, T3, T4, T5, T6 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2, T3, T4, T5, T6, T7 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2, T3, T4, T5, T6, T7, T8 >::indexer_node(), tbb::flow::interface10::indexer_node< T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::indexer_node(), tbb::flow::interface10::internal::join_node_FE< reserving, InputTuple, OutputTuple >::input_ports(), tbb::flow::interface10::join_node< OutputTuple, reserving >::join_node(), tbb::flow::interface10::join_node< OutputTuple, queueing >::join_node(), tbb::flow::interface10::join_node< OutputTuple, key_matching< K, KHash > >::join_node(), tbb::flow::interface10::limiter_node< T >::limiter_node(), tbb::flow::interface10::priority_queue_node< T, Compare, A >::priority_queue_node(), tbb::flow::interface10::queue_node< T, A >::queue_node(), tbb::flow::interface10a::write_once_node< T >::write_once_node(), tbb::flow::interface10a::overwrite_node< T >::~overwrite_node(), and tbb::flow::interface10::sequencer_node< T, A >::~sequencer_node().
 { }
static void tbb::internal::fgt_node_with_body (string_index , void * , void * , void *) inline static
Definition at line 301 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::internal::add_nodes_impl(), tbb::flow::interface10::continue_node< Output, Policy >::continue_node(), tbb::flow::interface10::internal::join_node_FE< reserving, InputTuple, OutputTuple >::decrement_port_count(), and tbb::flow::interface10::function_node< Input, Output, Policy, Allocator >::function_node().
 { }
static void tbb::internal::fgt_node_with_body (string_index , void * , void * , void * , void *) inline static
Definition at line 302 of file _flow_graph_trace_impl.h.
 { }
static void tbb::internal::fgt_release_wait (void *) inline static
Definition at line 315 of file _flow_graph_trace_impl.h.
 { }
static void tbb::internal::fgt_remove_edge (void * , void *) inline static
Definition at line 305 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::internal_remove_edge().
 { }
static void tbb::internal::fgt_reserve_wait (void *) inline static
Definition at line 314 of file _flow_graph_trace_impl.h.
Referenced by tbb::flow::interface10::internal::key_matching_port< TraitsType >::key_matching_port().
 { }
template<typename Container > auto tbb::internal::first (Container & c) -> decltype(begin(c))
Definition at line 38 of file _range_iterator.h.
References begin.
Referenced by tbb::internal::generic_scheduler::assert_task_pool_valid(), tbb::task_list::clear(), tbb::task_list::empty(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::insert(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::internal_copy(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::internal_equal_range(), internal::item_buffer< OutputTuple >::item(), last(), tbb::interface5::internal::split_ordered_list< value_type, typename concurrent_unordered_set_traits< Key, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type >::move_all(), tbb::parallel_do(), tbb::serial::interface9::parallel_for(), tbb::strict_ppl::parallel_for(), tbb::parallel_for_each(), tbb::parallel_sort(), tbb::internal::pipeline_root_task::pipeline_root_task(), tbb::task_list::push_back(), tbb::interface9::internal::do_task_iter< Iterator, Body, Item >::run_for_forward_iterator(), and tbb::interface9::internal::select_parallel_do().
 {return begin(c);}
template<typename Container > auto tbb::internal::first (const Container & c) -> decltype(begin(c))
Definition at line 41 of file _range_iterator.h.
References begin.
 {return begin(c);}
template<typename T , size_t size> T* tbb::internal::first (T(&) arr[size])
Definition at line 63 of file _range_iterator.h.
 {return arr;}
void tbb::internal::fix_broken_rethrow ()
Definition at line 188 of file tbb_misc.cpp.
Referenced by destroy_process_mask(), and throw_exception_v4().
 {}
void tbb::internal::free_closure_v3 (void * ptr)
Free a closure allocated by allocate_closure_v3.
Definition at line 45 of file tbb_thread.cpp.
References deallocate_via_handler_v3().
Referenced by tbb::internal::thread_closure_base::operator delete().
 {
     deallocate_via_handler_v3( ptr );
 }
bool tbb::internal::gcc_rethrow_exception_broken ()
Definition at line 189 of file tbb_misc.cpp.
Referenced by tbb::internal::governor::acquire_resources(), destroy_process_mask(), and throw_exception_v4().
 { return false; }
size_t tbb::internal::get_initial_auto_partitioner_divisor ()
Definition at line 153 of file task.cpp.
References tbb::internal::governor::local_scheduler(), and tbb::internal::generic_scheduler::max_threads_in_arena().
{
     const size_t X_FACTOR = 4;
     return X_FACTOR * governor::local_scheduler()->max_threads_in_arena();
 }
static bool tbb::internal::GetBoolEnvironmentVariable (const char * name) inline static
Definition at line 36 of file tbb_environment.h.
References s.
Referenced by DoOneTimeInitializations().
{
     if( const char* s = std::getenv(name) )
     {
         // The result is defined as true only if the environment variable contains
         // no characters except one '1' character and an arbitrary number of spaces
         // (including the absence of spaces).
         size_t index = std::strspn(s, " ");
         if (s[index] != '1') return false;
         index++;
         // Memory access after incrementing is safe, since the getenv() returns a
         // NULL terminated string, and even if the character getting by index is '1',
         // and this character is the end of string, after incrementing we will get
         // an index of character, that contains '\0'
         index += std::strspn(&s[index], " ");
         return !s[index];
     }
     return false;
 }
unsigned tbb::internal::GetPrime (unsigned seed)
Defined in tbb_main.cpp
Referenced by tbb::internal::FastRandom::init().
void tbb::internal::handle_perror (int error_code, const char * aux_info)
Throws std::runtime_error with what() returning error_code description prefixed with aux_info.
Definition at line 78 of file tbb_misc.cpp.
References __TBB_ASSERT_EX, handle_win_error(), and PRINT_ERROR_AND_ABORT.
Referenced by tbb::internal::governor::acquire_resources(), tbb::internal::input_buffer::create_my_tls(), tbb::internal::input_buffer::destroy_my_tls(), tbb::internal::tbb_thread_v3::detach(), tbb::mutex::scoped_lock::internal_acquire(), tbb::recursive_mutex::scoped_lock::internal_acquire(), tbb::mutex::internal_construct(), tbb::recursive_mutex::internal_construct(), tbb::internal::tbb_thread_v3::internal_start(), tbb::internal::tbb_thread_v3::join(), tbb::mutex::lock(), tbb::recursive_mutex::lock(), tbb::mutex::mutex(), and tbb::recursive_mutex::recursive_mutex().
{
     char buf[256];
 #if _MSC_VER
  #define snprintf _snprintf
 #endif
     int written = snprintf(buf, sizeof(buf), "%s: %s", what, strerror( error_code ));
     // On overflow, the returned value exceeds sizeof(buf) (for GLIBC) or is negative (for MSVC).
     __TBB_ASSERT_EX( written>0 && written<(int)sizeof(buf), "Error description is too long" );
     // Ensure that buffer ends in terminator.
     buf[sizeof(buf)-1] = 0;
 #if TBB_USE_EXCEPTIONS
     throw std::runtime_error(buf);
 #else
     PRINT_ERROR_AND_ABORT( "runtime_error", buf);
 #endif /* !TBB_USE_EXCEPTIONS */
 }
template<typename T > void tbb::internal::handle_unconstructed_elements (T * array, size_t n_of_elements)
Exception helper function.
Definition at line 78 of file concurrent_vector.h.
Referenced by tbb::concurrent_vector< T, A >::push_back_helper::element_construction_guard::~element_construction_guard(), and tbb::concurrent_vector< T, A >::internal_loop_guide::~internal_loop_guide().
{
         std::memset( static_cast<void*>(array), 0, n_of_elements * sizeof( T ) );
     }
void tbb::internal::handle_win_error (int error_code)
Throws std::runtime_error with what() returning error_code description prefixed with aux_info.
Referenced by tbb::internal::tbb_thread_v3::detach(), handle_perror(), and tbb::internal::tbb_thread_v3::join().
void tbb::internal::initialize_cache_aligned_allocator ()
Defined in cache_aligned_allocator.cpp.
Definition at line 136 of file cache_aligned_allocator.cpp.
References atomic_do_once(), and initialize_handler_pointers().
Referenced by DoOneTimeInitializations(), dummy_padded_allocate(), dummy_padded_free(), DummyFree(), DummyMalloc(), and tbb::internal::__TBB_InitOnce::remove_ref().
{
     atomic_do_once( &initialize_handler_pointers, initialization_state );
 }
void tbb::internal::initialize_handler_pointers ()
Initialize the allocation/free handler pointers.
Caller is responsible for ensuring this routine is called exactly once. The routine attempts to dynamically link with the TBB memory allocator. If that allocator is not found, it links to malloc and free.
Definition at line 117 of file cache_aligned_allocator.cpp.
References __TBB_ASSERT, DummyMalloc(), dynamic_link(), FreeHandler, MallocHandler, padded_allocate(), padded_allocate_handler, padded_free(), padded_free_handler, and PrintExtraVersionInfo().
Referenced by initialize_cache_aligned_allocator().
{
     __TBB_ASSERT( MallocHandler==&DummyMalloc, NULL );
     bool success = dynamic_link( MALLOCLIB_NAME, MallocLinkTable, 4 );
     if( !success ) {
         // If unsuccessful, set the handlers to the default routines.
         // This must be done now, and not before FillDynamicLinks runs, because if other
         // threads call the handlers, we want them to go through the DoOneTimeInitializations logic,
         // which forces them to wait.
         FreeHandler = &std::free;
         MallocHandler = &std::malloc;
         padded_allocate_handler = &padded_allocate;
         padded_free_handler = &padded_free;
     }
 #if !__TBB_RML_STATIC
     PrintExtraVersionInfo( "ALLOCATOR", success?"scalable_malloc":"malloc" );
 #endif
 }
template<typename T > bool tbb::internal::is_aligned (T * pointer, uintptr_t alignment) inline
A function to check if passed in pointer is aligned on a specific border.
Definition at line 353 of file tbb_stddef.h.
Referenced by __TBB_machine_aligned_load8(), __TBB_machine_aligned_store8(), __TBB_machine_cmpswp4(), __TBB_machine_cmpswp8_OsX(), __TBB_machine_fetchadd4(), __TBB_machine_fetchadd8(), __TBB_machine_load8(), __TBB_machine_store8(), tbb::internal::concurrent_queue_base_v3::concurrent_queue_base_v3(), and NFS_Allocate().
{
     return 0==((uintptr_t)pointer & (alignment-1));
 }
bool tbb::internal::is_bit_set (population_t val, int pos) inline
Definition at line 65 of file task_stream.h.
References __TBB_ASSERT.
Referenced by tbb::internal::task_stream< num_priority_levels >::drain(), tbb::internal::task_stream< num_priority_levels >::pop(), tbb::internal::task_stream< num_priority_levels >::pop_specific(), tbb::internal::task_stream< num_priority_levels >::try_pop(), and tbb::internal::queue_and_mutex< T, mutex_t >::~queue_and_mutex().
{
     __TBB_ASSERT( pos>=0, NULL );
     __TBB_ASSERT( pos<int(sizeof(population_t)*CHAR_BIT), NULL );
     return (val & (one<<pos)) != 0;
 }
bool tbb::internal::is_critical (task & t) inline
Definition at line 953 of file task.h.
References tbb::task::prefix().
Referenced by tbb::internal::arena::enqueue_task(), tbb::internal::generic_scheduler::free_task(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::task::prefix(), tbb::internal::generic_scheduler::prepare_for_spawning(), tbb::internal::custom_scheduler< SchedulerTraits >::receive_or_steal_task(), and tbb::internal::custom_scheduler< SchedulerTraits >::tally_completion_of_predecessor().
 { return bool((t.prefix().extra_state & 0x8) != 0); }
bool __TBB_EXPORTED_FUNC tbb::internal::is_malloc_used_v3 ()
Returns true if standard malloc/free are used to work with memory.
Definition at line 242 of file cache_aligned_allocator.cpp.
References __TBB_ASSERT, DummyFree(), DummyMalloc(), FreeHandler, and MallocHandler.
Referenced by tbb::tbb_allocator< T >::allocator_type().
{
     if (MallocHandler == &DummyMalloc) {
         void* void_ptr = (*MallocHandler)(1);
         (*FreeHandler)(void_ptr);
     }
     __TBB_ASSERT( MallocHandler!=&DummyMalloc && FreeHandler!=&DummyFree, NULL );
     // Cast to void avoids type mismatch errors on some compilers (e.g. __IBMCPP__)
     __TBB_ASSERT( !(((void*)MallocHandler==(void*)&std::malloc) ^ ((void*)FreeHandler==(void*)&std::free)),
                   "Both shim pointers must refer to routines from the same package (either TBB or CRT)" );
     return (void*)MallocHandler == (void*)&std::malloc;
 }
template<typename integer_type > bool tbb::internal::is_power_of_two (integer_type arg) inline
A function to check if passed integer is a power of 2.
Definition at line 359 of file tbb_stddef.h.
Referenced by is_power_of_two_at_least(), modulo_power_of_two(), NFS_Allocate(), and tbb::operator!=().
{
     return arg && (0 == (arg & (arg - 1)));
 }
template<typename argument_integer_type , typename power2_integer_type > bool tbb::internal::is_power_of_two_at_least (argument_integer_type arg, power2_integer_type power2) inline
A function to determine if arg is a power of 2 at least as big as another power of 2.
Definition at line 375 of file tbb_stddef.h.
References __TBB_ASSERT, and is_power_of_two().
Referenced by tbb::internal::concurrent_vector_base_v3::is_first_element_in_segment().
{
     __TBB_ASSERT( is_power_of_two(power2), "Divisor should be a power of two" );
     return 0 == (arg & (arg - power2));
 }
template<typename T > T tbb::internal::itt_hide_load_word (const T & src) inline
Definition at line 220 of file tbb_profiling.h.
References __TBB_ASSERT, call_itt_notify(), call_itt_notify_v5(), itt_load_pointer_v3(), itt_make_task_group(), itt_make_task_group_v7(), itt_metadata_str_add(), itt_metadata_str_add_v7(), itt_region_begin(), itt_region_begin_v9(), itt_region_end(), itt_region_end_v9(), itt_relation_add(), itt_relation_add_v7(), itt_task_begin(), itt_task_begin_v7(), itt_task_end(), and itt_task_end_v7().
Referenced by tbb::interface5::concurrent_priority_queue< T, Compare, A >::handle_operations(), tbb::interface5::internal::hash_map_base::insert_new_node(), and tbb::interface6::aggregator_operation::next().
{
 #if TBB_USE_THREADING_TOOLS
             //TODO: This assertion should be replaced with static_assert
             __TBB_ASSERT(sizeof(T) == sizeof(void *), "Type must be word-sized.");
             return (T)itt_load_pointer_v3(&src);
 #else
             return src;
 #endif
         }
template<typename T > void tbb::internal::itt_hide_store_word (T & dst, T src) inline
Definition at line 208 of file tbb_profiling.h.
References __TBB_ASSERT, and itt_store_pointer_with_release_v3().
Referenced by tbb::interface5::internal::hash_map_base::enable_segment(), tbb::interface5::concurrent_priority_queue< T, Compare, A >::handle_operations(), tbb::strict_ppl::internal::micro_queue< T >::push(), and tbb::interface6::aggregator_operation::set_next().
{
 #if TBB_USE_THREADING_TOOLS
             //TODO: This assertion should be replaced with static_assert
             __TBB_ASSERT(sizeof(T) == sizeof(void *), "Type must be word-sized");
             itt_store_pointer_with_release_v3(&dst, (void *)src);
 #else
             dst = src;
 #endif
         }
void * tbb::internal::itt_load_pointer_v3 (const void * src)
Definition at line 417 of file tbb_main.cpp.
Referenced by itt_hide_load_word().
{
     //TODO: replace this with __TBB_load_relaxed
     void* result = *static_cast<void*const*>(src);
     return result;
 }
void * tbb::internal::itt_load_pointer_with_acquire_v3 (const void * src)
Definition at line 273 of file tbb_main.cpp.
References __TBB_load_with_acquire(), call_itt_notify_v5(), ITT_NOTIFY, sync_cancel, and sync_releasing.
Referenced by itt_load_word_with_acquire().
{
     void* result = __TBB_load_with_acquire(*static_cast<void*const*>(src));
     ITT_NOTIFY(sync_acquired, const_cast<void*>(src));
     return result;
 }
template<typename T > T tbb::internal::itt_load_word_with_acquire (const tbb::atomic< T > & src) inline
Definition at line 166 of file tbb_profiling.h.
References __TBB_ASSERT, and itt_load_pointer_with_acquire_v3().
Referenced by tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::bucket_accessor::acquire(), tbb::interface5::internal::hash_map_base::check_mask_race(), tbb::interface5::internal::hash_map_base::check_rehashing_collision(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::erase(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::exclude(), tbb::interface6::internal::aggregator_generic< operation_type >::execute(), tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::execute(), tbb::interface6::aggregator_ext< internal::basic_handler >::execute_impl(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::internal_fast_find(), and tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::lookup().
{
 #if TBB_USE_THREADING_TOOLS
             // This assertion should be replaced with static_assert
             __TBB_ASSERT(sizeof(T) == sizeof(void *), "Type must be word-sized.");
 #if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
             // Workaround for overzealous compiler warnings
             #pragma warning (push)
             #pragma warning (disable: 4311)
 #endif
             T result = (T)itt_load_pointer_with_acquire_v3(&src);
 #if defined(_MSC_VER) && !defined(__INTEL_COMPILER)
             #pragma warning (pop)
 #endif
             return result;
 #else
             return src;
 #endif // TBB_USE_THREADING_TOOLS
         }
template<typename T > T tbb::internal::itt_load_word_with_acquire (const T & src) inline
Definition at line 197 of file tbb_profiling.h.
References __TBB_ASSERT, __TBB_load_with_acquire(), and itt_load_pointer_with_acquire_v3().
{
 #if TBB_USE_THREADING_TOOLS
             // This assertion should be replaced with static_assert
             __TBB_ASSERT(sizeof(T) == sizeof(void *), "Type must be word-sized");
             return (T)itt_load_pointer_with_acquire_v3(&src);
 #else
             return __TBB_load_with_acquire(src);
 #endif // TBB_USE_THREADING_TOOLS
         }
void tbb::internal::itt_make_task_group (itt_domain_enum , void * , unsigned long long, void * , unsigned long long, string_index) inline
Definition at line 270 of file tbb_profiling.h.
Referenced by itt_hide_load_word().
                                                                                          {}
void tbb::internal::itt_make_task_group_v7 (itt_domain_enum domain, void * group, unsigned long long group_extra, void * parent, unsigned long long parent_extra, string_index name_index)
Definition at line 396 of file tbb_main.cpp.
Referenced by call_itt_notify_v5(), and itt_hide_load_word().
                                                                              { }
void tbb::internal::itt_metadata_str_add (itt_domain_enum , void * , unsigned long long, string_index , const char *) inline
Definition at line 273 of file tbb_profiling.h.
Referenced by itt_hide_load_word(), and itt_region_end().
                                                                           {}
void tbb::internal::itt_metadata_str_add_v7 (itt_domain_enum domain, void * addr, unsigned long long addr_extra, string_index key, const char * value)
Definition at line 399 of file tbb_main.cpp.
Referenced by call_itt_notify_v5(), and itt_hide_load_word().
                                                               { }
void tbb::internal::itt_region_begin (itt_domain_enum , void * , unsigned long long, void * , unsigned long long, string_index) inline
Definition at line 284 of file tbb_profiling.h.
Referenced by itt_hide_load_word().
                                                                                       {}
void tbb::internal::itt_region_begin_v9 (itt_domain_enum domain, void * region, unsigned long long region_extra, void * parent, unsigned long long parent_extra, string_index name_index)
Definition at line 410 of file tbb_main.cpp.
Referenced by call_itt_notify_v5(), and itt_hide_load_word().
                                                                           { }
void tbb::internal::itt_region_end (itt_domain_enum , void * , unsigned long long) inline
Definition at line 287 of file tbb_profiling.h.
References event, ITT_DOMAIN_FLOW, and itt_metadata_str_add().
Referenced by itt_hide_load_word().
 {}
void tbb::internal::itt_region_end_v9 (itt_domain_enum domain, void * region, unsigned long long region_extra)
Definition at line 413 of file tbb_main.cpp.
Referenced by call_itt_notify_v5(), and itt_hide_load_word().
 { }
void tbb::internal::itt_relation_add (itt_domain_enum , void * , unsigned long long, itt_relation , void * , unsigned long long) inline
Definition at line 276 of file tbb_profiling.h.
Referenced by itt_hide_load_word().
                                                                                       {}
void tbb::internal::itt_relation_add_v7 (itt_domain_enum domain, void * addr0, unsigned long long addr0_extra, itt_relation relation, void * addr1, unsigned long long addr1_extra)
Definition at line 402 of file tbb_main.cpp.
Referenced by call_itt_notify_v5(), and itt_hide_load_word().
                                                                           { }
void tbb::internal::itt_set_sync_name_v3 (void * obj, const tchar * name)
Definition at line 423 of file tbb_main.cpp.
References ITT_SYNC_RENAME, and suppress_unused_warning().
{
     ITT_SYNC_RENAME(obj, name);
     suppress_unused_warning(obj, name);
 }
void tbb::internal::itt_store_pointer_with_release_v3 (void * dst, void * src)
Definition at line 268 of file tbb_main.cpp.
References __TBB_store_with_release(), ITT_NOTIFY, and sync_releasing.
Referenced by itt_hide_store_word(), and itt_store_word_with_release().
{
     ITT_NOTIFY(sync_releasing, dst);
     __TBB_store_with_release(*static_cast<void**>(dst),src);
 }
template<typename T , typename U > void tbb::internal::itt_store_word_with_release (tbb::atomic< T > & dst, U src) inline
Definition at line 155 of file tbb_profiling.h.
References __TBB_ASSERT, and itt_store_pointer_with_release_v3().
Referenced by tbb::interface5::internal::hash_map_base::enable_segment(), tbb::interface9::internal::finish_reduce< Body >::execute(), tbb::interface9::internal::start_reduce< Range, Body, Partitioner >::execute(), tbb::interface6::aggregator_operation::finish(), tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::handle_operations(), tbb::interface5::concurrent_priority_queue< T, Compare, A >::handle_operations(), tbb::strict_ppl::internal::micro_queue< T >::invalidate_page_and_rethrow(), tbb::interface6::internal::aggregator_generic< operation_type >::start_handle_operations(), tbb::interface6::aggregator_ext< internal::basic_handler >::start_handle_operations(), and tbb::strict_ppl::internal::micro_queue_pop_finalizer< T >::~micro_queue_pop_finalizer().
{
 #if TBB_USE_THREADING_TOOLS
             // This assertion should be replaced with static_assert
             __TBB_ASSERT(sizeof(T) == sizeof(void *), "Type must be word-sized.");
             itt_store_pointer_with_release_v3(&dst, (void *)uintptr_t(src));
 #else
             dst = src;
 #endif // TBB_USE_THREADING_TOOLS
         }
template<typename T > void tbb::internal::itt_store_word_with_release (T & dst, T src) inline
Definition at line 186 of file tbb_profiling.h.
References __TBB_ASSERT, __TBB_store_with_release(), and itt_store_pointer_with_release_v3().
{
 #if TBB_USE_THREADING_TOOLS
             // This assertion should be replaced with static_assert
             __TBB_ASSERT(sizeof(T) == sizeof(void *), "Type must be word-sized.");
             itt_store_pointer_with_release_v3(&dst, (void *)src);
 #else
             __TBB_store_with_release(dst, src);
 #endif // TBB_USE_THREADING_TOOLS
         }
void tbb::internal::itt_task_begin (itt_domain_enum , void * , unsigned long long, void * , unsigned long long, string_index) inline
Definition at line 279 of file tbb_profiling.h.
Referenced by itt_hide_load_word().
                                                                                     {}
void tbb::internal::itt_task_begin_v7 (itt_domain_enum domain, void * task, unsigned long long task_extra, void * parent, unsigned long long parent_extra, string_index name_index)
Definition at line 405 of file tbb_main.cpp.
Referenced by call_itt_notify_v5(), and itt_hide_load_word().
                                                                         { }
void tbb::internal::itt_task_end (itt_domain_enum) inline
Definition at line 282 of file tbb_profiling.h.
Referenced by itt_hide_load_word().
 {}
void tbb::internal::itt_task_end_v7 (itt_domain_enum domain)
Definition at line 408 of file tbb_main.cpp.
Referenced by call_itt_notify_v5(), and itt_hide_load_word().
 { }
template<typename Container > auto tbb::internal::last (Container & c) -> decltype(begin(c))
Definition at line 44 of file _range_iterator.h.
References end.
Referenced by tbb::interface5::internal::split_ordered_list< value_type, typename concurrent_unordered_set_traits< Key, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type >::check_range(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::concurrent_unordered_base(), tbb::strict_ppl::internal::micro_queue< Value >::get_ref(), tbb::concurrent_bounded_queue< T, A >::get_ref(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::insert(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::insert(), tbb::interface5::internal::split_ordered_list< value_type, typename concurrent_unordered_set_traits< Key, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type >::insert_dummy(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::internal_copy(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::internal_distance(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::internal_equal_range(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::internal_erase(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::internal_find(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::internal_insert(), last(), tbb::interface5::internal::split_ordered_list< value_type, typename concurrent_unordered_set_traits< Key, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type >::move_all(), tbb::parallel_do(), tbb::serial::interface9::parallel_for(), tbb::strict_ppl::parallel_for(), tbb::parallel_for_each(), tbb::serial::interface9::parallel_for_impl(), tbb::parallel_sort(), and tbb::interface9::internal::select_parallel_do().
 {return end(c);}
template<typename Container > auto tbb::internal::last (const Container & c) -> decltype(begin(c))
Definition at line 47 of file _range_iterator.h.
References end, first(), and last().
 {return end(c);}
template<typename T , size_t size> T* tbb::internal::last (T(&) arr[size])
Definition at line 66 of file _range_iterator.h.
References size.
 {return arr + size;}
void tbb::internal::make_critical (task & t) inline
Definition at line 952 of file task.h.
References tbb::task::prefix().
Referenced by tbb::internal::arena::enqueue_task(), tbb::task::prefix(), and tbb::flow::interface10::internal::spawn_in_graph_arena().
 { t.prefix().extra_state |= 0x8; }
template<typename T > T tbb::internal::max (const T & val1, const T & val2)
Utility template function returning greater of the two values.
Provided here to avoid including not strict safe <algorithm>.
In case operands cause signed/unsigned or size mismatch warnings it is caller's responsibility to do the appropriate cast before calling the function.
Definition at line 115 of file tbb_misc.h.
Referenced by calc_workers_soft_limit(), tbb::internal::market::create_one_job(), tbb::internal::allowed_parallelism_control::default_value(), tbb::internal::generic_scheduler::enqueue(), tbb::internal::market::global_market(), tbb::tbb_allocator< T >::max_size(), tbb::interface6::memory_pool_allocator< T, P >::max_size(), and tbb::internal::arena::num_arena_slots().
{
     return val1 < val2 ? val2 : val1;
 }
template<typename T > T tbb::internal::min (const T & val1, const T & val2)
Utility template function returning lesser of the two values.
Provided here to avoid including not strict safe <algorithm>.
In case operands cause signed/unsigned or size mismatch warnings it is caller's responsibility to do the appropriate cast before calling the function.
Definition at line 106 of file tbb_misc.h.
Referenced by tbb::internal::allowed_parallelism_control::active_value(), tbb::internal::market::adjust_demand(), tbb::internal::market::set_active_num_workers(), and tbb::internal::market::update_allotment().
{
     return val1 < val2 ? val1 : val2;
 }
template<typename argument_integer_type , typename divisor_integer_type > argument_integer_type tbb::internal::modulo_power_of_two (argument_integer_type arg, divisor_integer_type divisor) inline
A function to compute arg modulo divisor where divisor is a power of 2.
Definition at line 365 of file tbb_stddef.h.
References __TBB_ASSERT, and is_power_of_two().
Referenced by tbb::strict_ppl::internal::concurrent_queue_iterator_base_v3< Value >::advance(), tbb::internal::concurrent_queue_iterator_base_v3::advance(), tbb::internal::micro_queue::assign(), tbb::strict_ppl::internal::micro_queue< T >::assign(), tbb::internal::concurrent_queue_iterator_rep::get_item(), tbb::strict_ppl::internal::concurrent_queue_iterator_rep< T >::get_item(), tbb::internal::arena::on_thread_leaving(), tbb::internal::micro_queue::pop(), tbb::strict_ppl::internal::micro_queue< T >::pop(), tbb::internal::micro_queue::push(), and tbb::strict_ppl::internal::micro_queue< T >::push().
{
     __TBB_ASSERT( is_power_of_two(divisor), "Divisor should be a power of two" );
     return (arg & (divisor - 1));
 }
void tbb::internal::move_v3 (tbb_thread_v3 & t1, tbb_thread_v3 & t2)
Definition at line 151 of file tbb_thread.cpp.
References tbb::internal::tbb_thread_v3::detach(), tbb::internal::tbb_thread_v3::joinable(), and tbb::internal::tbb_thread_v3::my_handle.
Referenced by tbb::internal::tbb_thread_v3::get_id(), tbb::internal::tbb_thread_v3::internal_move(), and tbb::move().
 {
     if (t1.joinable())
         t1.detach();
     t1.my_handle = t2.my_handle;
     t2.my_handle = 0;
 #if _WIN32||_WIN64
     t1.my_thread_id = t2.my_thread_id;
     t2.my_thread_id = 0;
 #endif // _WIN32||_WIN64
 }
static bool tbb::internal::occupy_slot (generic_scheduler *& slot, generic_scheduler & s) inline static
Definition at line 71 of file arena.cpp.
References as_atomic().
Referenced by tbb::internal::arena::occupy_free_slot_in_range().
{
     return !slot && as_atomic( slot ).compare_and_swap( &s, NULL ) == NULL;
 }
bool tbb::internal::operator!= (tbb_thread_v3::id x, tbb_thread_v3::id y) inline
Definition at line 276 of file tbb_thread.h.
     {
         return x.my_id != y.my_id;
     }
template<typename Container , typename T , typename U > bool tbb::internal::operator!= (const vector_iterator< Container, T > & i, const vector_iterator< Container, U > & j)
Definition at line 440 of file concurrent_vector.h.
Referenced by tbb::internal::tbb_thread_v3::id::id().
{
         return !(i==j);
     }
template<typename C , typename T , typename U > bool tbb::internal::operator!= (const concurrent_queue_iterator< C, T > & i, const concurrent_queue_iterator< C, U > & j)
Definition at line 1065 of file _concurrent_queue_impl.h.
References tbb::internal::concurrent_queue_iterator_base_v3::my_item.
{
     return i.my_item!=j.my_item;
 }
template<typename Container , typename T > vector_iterator<Container,T> tbb::internal::operator+ (ptrdiff_t offset, const vector_iterator< Container, T > & v)
Definition at line 430 of file concurrent_vector.h.
References tbb::internal::vector_iterator< Container, Value >::my_index, and tbb::internal::vector_iterator< Container, Value >::my_vector.
{
         return vector_iterator<Container,T>( *v.my_vector, v.my_index+offset );
     }
template<typename Container , typename T , typename U > ptrdiff_t tbb::internal::operator- (const vector_iterator< Container, T > & i, const vector_iterator< Container, U > & j)
Definition at line 465 of file concurrent_vector.h.
References tbb::internal::vector_iterator< Container, Value >::my_index.
{
         return ptrdiff_t(i.my_index)-ptrdiff_t(j.my_index);
     }
bool tbb::internal::operator< (tbb_thread_v3::id x, tbb_thread_v3::id y) inline
Definition at line 280 of file tbb_thread.h.
     {
         return x.my_id < y.my_id;
     }
template<typename Container , typename T , typename U > bool tbb::internal::operator< (const vector_iterator< Container, T > & i, const vector_iterator< Container, U > & j)
Definition at line 445 of file concurrent_vector.h.
References tbb::internal::vector_iterator< Container, Value >::my_index.
Referenced by tbb::internal::tbb_thread_v3::id::id().
{
         return i.my_index<j.my_index;
     }
bool tbb::internal::operator<= (tbb_thread_v3::id x, tbb_thread_v3::id y) inline
Definition at line 284 of file tbb_thread.h.
     {
         return x.my_id <= y.my_id;
     }
template<typename Container , typename T , typename U > bool tbb::internal::operator<= (const vector_iterator< Container, T > & i, const vector_iterator< Container, U > & j)
Definition at line 460 of file concurrent_vector.h.
Referenced by tbb::internal::tbb_thread_v3::id::id().
{
         return !(j<i);
     }
bool tbb::internal::operator== (tbb_thread_v3::id x, tbb_thread_v3::id y) inline
Definition at line 272 of file tbb_thread.h.
     {
         return x.my_id == y.my_id;
     }
template<typename Container , typename T , typename U > bool tbb::internal::operator== (const vector_iterator< Container, T > & i, const vector_iterator< Container, U > & j)
Definition at line 435 of file concurrent_vector.h.
References tbb::internal::vector_iterator< Container, Value >::my_index, and tbb::internal::vector_iterator< Container, Value >::my_vector.
Referenced by tbb::internal::tbb_thread_v3::id::id().
{
         return i.my_index==j.my_index && i.my_vector == j.my_vector;
     }
template<typename C , typename T , typename U > bool tbb::internal::operator== (const concurrent_queue_iterator< C, T > & i, const concurrent_queue_iterator< C, U > & j)
Definition at line 1060 of file _concurrent_queue_impl.h.
References tbb::internal::concurrent_queue_iterator_base_v3::my_item.
{
     return i.my_item==j.my_item;
 }
bool tbb::internal::operator> (tbb_thread_v3::id x, tbb_thread_v3::id y) inline
Definition at line 288 of file tbb_thread.h.
     {
         return x.my_id > y.my_id;
     }
template<typename Container , typename T , typename U > bool tbb::internal::operator> (const vector_iterator< Container, T > & i, const vector_iterator< Container, U > & j)
Definition at line 450 of file concurrent_vector.h.
Referenced by tbb::internal::tbb_thread_v3::id::id().
{
         return j<i;
     }
bool tbb::internal::operator>= (tbb_thread_v3::id x, tbb_thread_v3::id y) inline
Definition at line 292 of file tbb_thread.h.
     {
         return x.my_id >= y.my_id;
     }
template<typename Container , typename T , typename U > bool tbb::internal::operator>= (const vector_iterator< Container, T > & i, const vector_iterator< Container, U > & j)
Definition at line 455 of file concurrent_vector.h.
Referenced by tbb::internal::tbb_thread_v3::id::id().
{
         return !(i<j);
     }
static void * tbb::internal::padded_allocate (size_t bytes, size_t alignment) static
Definition at line 206 of file cache_aligned_allocator.cpp.
Referenced by initialize_handler_pointers().
{
     unsigned char* result = NULL;
     unsigned char* base = (unsigned char*)std::malloc(alignment+bytes);
     if( base ) {
         // Round up to the next line
         result = (unsigned char*)((uintptr_t)(base+alignment)&-alignment);
         // Record where block actually starts.
         ((uintptr_t*)result)[-1] = uintptr_t(base);
     }
     return result;
 }
static void tbb::internal::padded_free (void * p) static
Definition at line 218 of file cache_aligned_allocator.cpp.
References __TBB_ASSERT.
Referenced by initialize_handler_pointers().
{
     if( p ) {
         __TBB_ASSERT( (uintptr_t)p>=0x4096, "attempt to free block not obtained from cache_aligned_allocator" );
         // Recover where block actually starts
         unsigned char* base = ((unsigned char**)p)[-1];
         __TBB_ASSERT( (void*)((uintptr_t)(base+NFS_LineSize)&-NFS_LineSize)==p, "not allocated by NFS_Allocate?" );
         std::free(base);
     }
 }
namespace msvc_inline_asm static inline void tbb::internal::pause (uintptr_t delay)
Definition at line 111 of file msvc_ia32_common.h.
References __TBB_r.
Referenced by tbb::internal::atomic_backoff::atomic_backoff(), and ITT_VERSIONIZE().
{
             _asm
             {
                 mov __TBB_r(ax), delay
               __TBB_L1:
                 pause
                 add __TBB_r(ax), -1
                 jne __TBB_L1
             }
             return;
         }
template<typename T > void tbb::internal::poison_pointer (T *__TBB_atomic &) inline
Definition at line 309 of file tbb_stddef.h.
Referenced by tbb::internal::generic_scheduler::deallocate_task(), tbb::internal::generic_scheduler::enqueue(), tbb::internal::final_sum< Range, Body >::final_sum(), tbb::internal::generic_scheduler::free_task(), tbb::internal::generic_scheduler::get_task(), tbb::queuing_mutex::scoped_lock::initialize(), tbb::queuing_rw_mutex::scoped_lock::initialize(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::internal::generic_scheduler::prepare_for_spawning(), tbb::internal::generic_scheduler::steal_task_from(), tbb::internal::sum_node< Range, Body >::sum_node(), tbb::internal::input_buffer::~input_buffer(), tbb::internal::rml::private_server::~private_server(), and tbb::task_scheduler_init::~task_scheduler_init().
 {/*do nothing*/}
void tbb::internal::PrintExtraVersionInfo (const char * category, const char * format, ...)
Prints arbitrary extra TBB version information on stderr.
Definition at line 202 of file tbb_misc.cpp.
Referenced by DoOneTimeInitializations(), initialize_handler_pointers(), tbb::internal::governor::print_version_info(), and PrintRMLVersionInfo().
{
     if( PrintVersionFlag ) {
         char str[1024]; memset(str, 0, 1024);
         va_list args; va_start(args, format);
         // Note: correct vsnprintf definition obtained from tbb_assert_impl.h
         vsnprintf( str, 1024-1, format, args);
         va_end(args);
         fprintf(stderr, "TBB: %s\t%s\n", category, str );
     }
 }
void tbb::internal::PrintRMLVersionInfo (void * arg, const char * server_info)
A callback routine to print RML version information on stderr.
Definition at line 213 of file tbb_misc.cpp.
References PrintExtraVersionInfo().
Referenced by tbb::internal::governor::print_version_info().
{
     PrintExtraVersionInfo( server_info, (const char *)arg );
 }
void tbb::internal::PrintVersion ()
Prints TBB version information on stderr.
Definition at line 197 of file tbb_misc.cpp.
Referenced by DoOneTimeInitializations().
                     {
     PrintVersionFlag = true;
     fputs(VersionString+1,stderr);
 }
void tbb::internal::prolonged_pause () inline
Definition at line 300 of file scheduler_common.h.
References __TBB_Pause(), __TBB_STEALING_PAUSE, __TBB_time_stamp, and tbb::internal::atomic_backoff::bounded_pause().
Referenced by tbb::internal::custom_scheduler< SchedulerTraits >::receive_or_steal_task().
{
 #if defined(__TBB_time_stamp) && !__TBB_STEALING_PAUSE
     // Assumption based on practice: 1000-2000 ticks seems to be a suitable invariant for the
     // majority of platforms. Currently, skip platforms that define __TBB_STEALING_PAUSE
     // because these platforms require very careful tuning.
     machine_tsc_t prev = __TBB_time_stamp();
     const machine_tsc_t finish = prev + 1000;
     atomic_backoff backoff;
     do {
         backoff.bounded_pause();
         machine_tsc_t curr = __TBB_time_stamp();
         if ( curr <= prev )
             // Possibly, the current logical thread is moved to another hardware thread or overflow is occurred.
             break;
         prev = curr;
     } while ( prev < finish );
 #else
 #ifdef __TBB_STEALING_PAUSE
     static const long PauseTime = __TBB_STEALING_PAUSE;
 #elif __TBB_ipf
     static const long PauseTime = 1500;
 #else
     static const long PauseTime = 80;
 #endif
     // TODO IDEA: Update PauseTime adaptively?
     __TBB_Pause(PauseTime);
 #endif
 }
template<typename T , typename U > T tbb::internal::punned_cast (U * ptr) inline
Cast between unrelated pointer types.
This method should be used sparingly as a last resort for dealing with situations that inherently break strict ISO C++ aliasing rules.
Definition at line 318 of file tbb_stddef.h.
Referenced by tbb::aligned_space< Body >::begin(), internal::do_if< T, false >::construct(), internal::item_buffer< OutputTuple >::destroy_item(), tbb::internal::generic_scheduler::free_task(), internal::item_buffer< OutputTuple >::get_my_item(), internal::tagged_msg< TagType, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::variant::operator=(), throw_exception_v4(), internal::tagged_msg< TagType, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::variant::variant(), internal::tagged_msg< TagType, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::variant::variant_cast_to(), internal::tagged_msg< TagType, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::variant::variant_is_a(), and internal::tagged_msg< TagType, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::variant::~variant().
{
     uintptr_t x = reinterpret_cast<uintptr_t>(ptr);
     return reinterpret_cast<T>(x);
 }
void tbb::internal::reset_extra_state (task * t) inline
Definition at line 185 of file scheduler_common.h.
References es_task_enqueued, es_task_is_stolen, and tbb::task::prefix().
Referenced by tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all().
{
     t->prefix().extra_state &= ~(es_task_is_stolen | es_task_enqueued);
 }
void tbb::internal::run_initializer (void(*)() f, atomic< do_once_state > & state) inline
Definition at line 228 of file tbb_misc.h.
References do_once_executed.
Referenced by atomic_do_once().
{
     f();
     state = do_once_executed;
 }
void tbb::internal::run_initializer (bool(*)() f, atomic< do_once_state > & state) inline
Definition at line 234 of file tbb_misc.h.
References destroy_process_mask(), do_once_executed, and do_once_uninitialized.
{
     state = f() ? do_once_executed : do_once_uninitialized;
 }
void __TBB_EXPORTED_FUNC tbb::internal::runtime_warning (const char * format, ...)
Report a runtime warning.
Definition at line 89 of file tbb_assert_impl.h.
Referenced by assert_task_valid(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::clear(), tbb::internal::governor::create_rml_server(), tbb::internal::market::destroy(), tbb::internal::market::global_market(), tbb::internal::governor::initialize_rml_factory(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::rehash(), tbb::internal::governor::release_resources(), and tbb::TBB_runtime_interface_version().
         {
             char str[1024]; memset(str, 0, 1024);
             va_list args; va_start(args, format);
             vsnprintf( str, 1024-1, format, args);
             va_end(args);
             fprintf( stderr, "TBB Warning: %s\n", str);
         }
template<typename... Types> stored_pack<Types...> tbb::internal::save_pack (Types &&... types)
Definition at line 172 of file _template_helpers.h.
{
     return stored_pack<Types...>( std::forward<Types>(types)... );
 }
void tbb::internal::Scheduler_OneTimeInitialization (bool itt_present)
Defined in scheduler.cpp.
Definition at line 56 of file scheduler.cpp.
References __TBB_ASSERT, AllocateSchedulerPtr, tbb::task_group_context::low_unused_state_bit, tbb::task_group_context::my_priority, tbb::task_group_context::my_state, and num_priority_levels.
Referenced by DoOneTimeInitializations(), and tbb::internal::__TBB_InitOnce::remove_ref().
{
     AllocateSchedulerPtr = itt_present ? &custom_scheduler<DefaultSchedulerTraits>::allocate_scheduler :
                                       &custom_scheduler<IntelSchedulerTraits>::allocate_scheduler;
 #if __TBB_TASK_GROUP_CONTEXT
     // There must be no tasks belonging to this fake task group. Mark invalid for the assert
     __TBB_ASSERT(!(task_group_context::low_unused_state_bit & (task_group_context::low_unused_state_bit-1)), NULL);
     the_dummy_context.my_state = task_group_context::low_unused_state_bit;
 #if __TBB_TASK_PRIORITY
     // It should never prevent tasks from being passed to execution.
     the_dummy_context.my_priority = num_priority_levels - 1;
 #endif /* __TBB_TASK_PRIORITY */
 #endif /* __TBB_TASK_GROUP_CONTEXT */
 }
void tbb::internal::set_one_bit (population_t & dest, int pos) inline
Definition at line 53 of file task_stream.h.
References __TBB_ASSERT, and __TBB_AtomicOR().
Referenced by tbb::internal::task_stream< num_priority_levels >::push(), tbb::internal::task_stream< num_priority_levels >::try_push(), and tbb::internal::queue_and_mutex< T, mutex_t >::~queue_and_mutex().
{
     __TBB_ASSERT( pos>=0, NULL );
     __TBB_ASSERT( pos<int(sizeof(population_t)*CHAR_BIT), NULL );
     __TBB_AtomicOR( &dest, one<<pos );
 }
template<typename T , typename U > void tbb::internal::spin_wait_until_eq (const volatile T & location, const U value)
Spin UNTIL the value of the variable is equal to a given value.
T and U should be comparable types.
Definition at line 403 of file tbb_machine.h.
References tbb::internal::atomic_backoff::pause().
Referenced by tbb::queuing_rw_mutex::scoped_lock::acquire(), tbb::internal::generic_scheduler::init_stack_info(), tbb::internal::micro_queue::pop(), tbb::strict_ppl::internal::micro_queue< T >::pop(), tbb::interface6::internal::aggregator_generic< operation_type >::start_handle_operations(), tbb::interface6::aggregator_ext< internal::basic_handler >::start_handle_operations(), and tbb::queuing_rw_mutex::scoped_lock::wait_for_release_of_internal_lock().
{
     atomic_backoff backoff;
     while( location!=value ) backoff.pause();
 }
template<typename predicate_type > void tbb::internal::spin_wait_while (predicate_type condition)
Definition at line 409 of file tbb_machine.h.
References tbb::internal::atomic_backoff::pause().
Referenced by tbb::internal::concurrent_vector_base_v3::helper::acquire_segment(), tbb::internal::concurrent_vector_base_v3::helper::enable_segment(), and tbb::internal::concurrent_vector_base_v3::helper::get_segment_value().
{
     atomic_backoff backoff;
     while( condition() ) backoff.pause();
 }
template<typename T , typename U > void tbb::internal::spin_wait_while_eq (const volatile T & location, U value)
Spin WHILE the value of the variable is equal to a given value.
T and U should be comparable types.
Definition at line 395 of file tbb_machine.h.
References tbb::internal::atomic_backoff::pause().
Referenced by tbb::queuing_mutex::scoped_lock::acquire(), tbb::queuing_rw_mutex::scoped_lock::acquire(), atomic_do_once(), tbb::queuing_rw_mutex::scoped_lock::downgrade_to_reader(), tbb::internal::concurrent_vector_base_v3::helper::enable_segment(), tbb::interface5::reader_writer_lock::end_write(), tbb::interface6::internal::aggregator_generic< operation_type >::execute(), tbb::interface6::aggregator_ext< internal::basic_handler >::execute_impl(), tbb::internal::concurrent_vector_base_v3::internal_grow_to_at_least_with_result(), tbb::interface7::internal::task_arena_base::internal_initialize(), tbb::interface6::concurrent_lru_cache< key_type, value_type, value_functor_type >::operator[](), tbb::internal::micro_queue::pop(), tbb::strict_ppl::internal::micro_queue< T >::pop(), tbb::queuing_mutex::scoped_lock::release(), tbb::queuing_rw_mutex::scoped_lock::release(), tbb::interface5::reader_writer_lock::start_read(), tbb::interface5::reader_writer_lock::start_write(), and tbb::queuing_rw_mutex::scoped_lock::upgrade_to_writer().
{
     atomic_backoff backoff;
     while( location==value ) backoff.pause();
 }
template<typename T1 > void tbb::internal::suppress_unused_warning (const T1 &)
Utility template function to prevent "unused" warnings by various compilers.
Definition at line 381 of file tbb_stddef.h.
Referenced by tbb::internal::allocate_additional_child_of_proxy::allocate_additional_child_of_proxy(), tbb::interface5::internal::split_ordered_list< value_type, typename concurrent_unordered_set_traits< Key, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type >::check_range(), tbb::internal::mail_outbox::construct(), DoOneTimeInitializations(), tbb::flow::interface10::opencl_factory< default_device_filter >::finalize_callback(), itt_set_sync_name_v3(), tbb::internal::rml::padded_private_worker::padded_private_worker(), tbb::flow::interface10::opencl_async_msg< T, Factory >::register_callback_func(), internal::queueing_port< T >::reset_receiver(), internal::key_matching_port< TraitsType >::reset_receiver(), tbb::spin_mutex::scoped_lock::scoped_lock(), tbb::internal::governor::sign_off(), and tbb::task_scheduler_init::terminate().
 {}
template<typename T1 , typename T2 > void tbb::internal::suppress_unused_warning (const T1 & , const T2 &)
Definition at line 382 of file tbb_stddef.h.
 {}
template<typename T1 , typename T2 , typename T3 > void tbb::internal::suppress_unused_warning (const T1 & , const T2 & , const T3 &)
Definition at line 383 of file tbb_stddef.h.
 {}
void tbb::internal::swap (concurrent_vector_base_v3::segment_t & lhs, concurrent_vector_base_v3::segment_t & rhs) inline
Definition at line 285 of file concurrent_vector.h.
{
         lhs.swap(rhs);
     }
template<memory_semantics M, typename T > void tbb::internal::swap (atomic< T > & lhs, atomic< T > & rhs)
Definition at line 539 of file atomic.h.
Referenced by allocator_swap(), tbb::interface6::enumerable_thread_specific< T, Allocator, ETS_key_type >::internal_swap(), tbb::strict_ppl::internal::concurrent_queue_base_v3< Value >::internal_throw_exception(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::operator=(), tbb::interface5::concurrent_priority_queue< T, Compare, A >::swap(), tbb::interface5::internal::split_ordered_list< value_type, typename concurrent_unordered_set_traits< Key, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false >::allocator_type >::swap(), and tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::swap().
{
     T tmp = load<M>(lhs);
     store<M>(lhs,load<M>(rhs));
     store<M>(rhs,tmp);
 }
tbb_thread_v3::id tbb::internal::thread_get_id_v3 ()
Definition at line 143 of file tbb_thread.cpp.
References id.
Referenced by tbb::internal::tbb_thread_v3::get_id(), and tbb::this_tbb_thread::get_id().
{
 #if _WIN32||_WIN64
     return tbb_thread_v3::id( GetCurrentThreadId() );
 #else
     return tbb_thread_v3::id( pthread_self() );
 #endif // _WIN32||_WIN64
 }
void tbb::internal::thread_sleep_v3 (const tick_count::interval_t & i)
Definition at line 168 of file tbb_thread.cpp.
References tbb::tick_count::now(), and tbb::tick_count::interval_t::seconds().
Referenced by tbb::internal::tbb_thread_v3::get_id(), and tbb::this_tbb_thread::sleep().
 {
 #if _WIN32||_WIN64
      tick_count t0 = tick_count::now();
      tick_count t1 = t0;
      for(;;) {
          double remainder = (i-(t1-t0)).seconds()*1e3;  // milliseconds remaining to sleep
          if( remainder<=0 ) break;
          DWORD t = remainder>=INFINITE ? INFINITE-1 : DWORD(remainder);
 #if !__TBB_WIN8UI_SUPPORT
          Sleep( t );
 #else
          std::chrono::milliseconds sleep_time( t );
          std::this_thread::sleep_for( sleep_time );
 #endif
          t1 = tick_count::now();
     }
 #else
     struct timespec req;
     double sec = i.seconds();
     req.tv_sec = static_cast<long>(sec);
     req.tv_nsec = static_cast<long>( (sec - req.tv_sec)*1e9 );
     nanosleep(&req, NULL);
 #endif // _WIN32||_WIN64
 }
void tbb::internal::thread_yield_v3 ()
Definition at line 163 of file tbb_thread.cpp.
References __TBB_Yield.
Referenced by tbb::internal::tbb_thread_v3::get_id(), and tbb::this_tbb_thread::yield().
 {
     __TBB_Yield();
 }
void tbb::internal::throw_bad_last_alloc_exception_v4 ()
Obsolete.
Definition at line 113 of file tbb_misc.cpp.
References eid_bad_last_alloc, and throw_exception_v4().
{
     throw_exception_v4(eid_bad_last_alloc);
 }
void tbb::internal::throw_exception (exception_id eid) inline
Versionless convenience wrapper for throw_exception_v4()
Definition at line 106 of file tbb_exception.h.
References throw_exception_v4().
Referenced by tbb::interface6::memory_pool_allocator< T, P >::allocate(), tbb::strict_ppl::concurrent_queue< T, A >::allocate_block(), tbb::concurrent_bounded_queue< T, A >::allocate_page(), tbb::internal::concurrent_vector_base_v3::helper::allocate_segment(), allocate_via_handler_v3(), tbb::interface5::concurrent_unordered_map< Key, T, Hasher, Key_equality, Allocator >::at(), tbb::internal::concurrent_monitor::commit_wait(), tbb::interface6::fixed_pool::fixed_pool(), tbb::interface5::reader_writer_lock::scoped_lock::internal_construct(), tbb::interface5::reader_writer_lock::scoped_lock_read::internal_construct(), tbb::internal::concurrent_queue_base_v3::internal_insert_item(), tbb::internal::concurrent_queue_base_v3::internal_pop(), tbb::internal::concurrent_vector_base_v3::internal_reserve(), tbb::concurrent_vector< T, A >::internal_subscript_with_exceptions(), tbb::internal::concurrent_vector_base_v3::internal_throw_exception(), tbb::strict_ppl::internal::concurrent_queue_base_v3< Value >::internal_throw_exception(), tbb::internal::concurrent_queue_base_v3::internal_throw_exception(), tbb::internal::critical_section_v4::lock(), tbb::interface5::reader_writer_lock::lock(), tbb::interface5::reader_writer_lock::lock_read(), tbb::task_handle< F >::mark_scheduled(), tbb::interface5::internal::concurrent_unordered_base< concurrent_unordered_map_traits< Key, T, internal::hash_compare< Key, Hasher, Key_equality >, Allocator, false > >::max_load_factor(), tbb::interface6::memory_pool< Alloc >::memory_pool(), NFS_Allocate(), tbb::interface5::concurrent_hash_map< Key, T, HashCompare, Allocator >::node::operator new(), tbb::strict_ppl::parallel_for_impl(), tbb::internal::micro_queue::push(), tbb::interface5::concurrent_priority_queue< T, Compare, A >::push(), tbb::strict_ppl::internal::micro_queue< T >::spin_wait_until_my_turn(), tbb::task_scheduler_init::terminate(), internal::tagged_msg< TagType, T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::variant::variant_cast_to(), and tbb::internal::task_group_base::~task_group_base().
 { throw_exception_v4(eid); }
void tbb::internal::throw_exception_v4 (exception_id eid)
Gathers all throw operators in one place.
Its purpose is to minimize code bloat that can be caused by throw operators scattered in multiple places, especially in templates.
Definition at line 117 of file tbb_misc.cpp.
References __TBB_ASSERT, DO_THROW, eid_bad_alloc, eid_bad_last_alloc, eid_bad_tagged_msg_cast, eid_condvar_wait_failed, eid_improper_lock, eid_index_range_error, eid_invalid_key, eid_invalid_load_factor, eid_invalid_multiple_scheduling, eid_invalid_swap, eid_max, eid_missing_wait, eid_nonpositive_step, eid_operation_not_permitted, eid_out_of_range, eid_possible_deadlock, eid_reservation_length_error, eid_reserved, eid_segment_range_error, eid_user_abort, fix_broken_rethrow(), gcc_rethrow_exception_broken(), and punned_cast().
Referenced by throw_bad_last_alloc_exception_v4(), and throw_exception().
{
     __TBB_ASSERT ( eid > 0 && eid < eid_max, "Unknown exception ID" );
     switch ( eid ) {
     case eid_bad_alloc: DO_THROW(std::bad_alloc, () );
     case eid_bad_last_alloc: DO_THROW( bad_last_alloc, () );
     case eid_nonpositive_step: DO_THROW(std::invalid_argument, ("Step must be positive") );
     case eid_out_of_range: DO_THROW(std::out_of_range, ("Index out of requested size range") );
     case eid_segment_range_error: DO_THROW(std::range_error, ("Index out of allocated segment slots") );
     case eid_index_range_error: DO_THROW(std::range_error, ("Index is not allocated") );
     case eid_missing_wait: DO_THROW( missing_wait, () );
     case eid_invalid_multiple_scheduling: DO_THROW( invalid_multiple_scheduling, () );
     case eid_improper_lock: DO_THROW( improper_lock, () );
     case eid_possible_deadlock: DO_THROW(std::runtime_error, ("Resource deadlock would occur") );
     case eid_operation_not_permitted: DO_THROW(std::runtime_error, ("Operation not permitted") );
     case eid_condvar_wait_failed: DO_THROW(std::runtime_error, ("Wait on condition variable failed") );
     case eid_invalid_load_factor: DO_THROW(std::out_of_range, ("Invalid hash load factor") );
     case eid_reserved: DO_THROW(std::out_of_range, ("[backward compatibility] Invalid number of buckets") );
     case eid_invalid_swap: DO_THROW(std::invalid_argument, ("swap() is invalid on non-equal allocators") );
     case eid_reservation_length_error: DO_THROW(std::length_error, ("reservation size exceeds permitted max size") );
     case eid_invalid_key: DO_THROW(std::out_of_range, ("invalid key") );
     case eid_user_abort: DO_THROW( user_abort, () );
     case eid_bad_tagged_msg_cast: DO_THROW(std::runtime_error, ("Illegal tagged_msg cast") );
 #if __TBB_SUPPORTS_WORKERS_WAITING_IN_TERMINATE
     case eid_blocking_thread_join_impossible: DO_THROW(std::runtime_error, ("Blocking terminate failed") );
 #endif
     default: break;
     }
 #if !TBB_USE_EXCEPTIONS && __APPLE__
     out_of_range e1("");
     length_error e2("");
     range_error e3("");
     invalid_argument e4("");
 #endif /* !TBB_USE_EXCEPTIONS && __APPLE__ */
 }
Variable Documentation
__TBB_InitOnce tbb::internal::__TBB_InitOnceHiddenInstance static
Definition at line 71 of file tbb_main.cpp.
const char tbb::internal::_pad[NFS_MaxLineSize-sizeof(int)] = {} static
Padding in order to prevent false sharing.
Definition at line 38 of file tbb_main.cpp.
Referenced by DoOneTimeInitializations().
generic_scheduler *(* tbb::internal::AllocateSchedulerPtr)(market &)
Pointer to the scheduler factory function.
Defined in tbb_main.cpp
Definition at line 78 of file tbb_main.cpp.
Referenced by allocate_scheduler(), and Scheduler_OneTimeInitialization().
allowed_parallelism_control tbb::internal::allowed_parallelism_ctl static
Definition at line 487 of file tbb_main.cpp.
control_storage* tbb::internal::controls[] = {&allowed_parallelism_ctl, &stack_size_ctl} static
Definition at line 490 of file tbb_main.cpp.
Referenced by tbb::interface9::global_control::active_value(), tbb::interface9::global_control::internal_create(), and tbb::interface9::global_control::internal_destroy().
void(* tbb::internal::FreeHandler) (void *pointer) = &DummyFree static
Handler for memory deallocation.
Definition at line 65 of file cache_aligned_allocator.cpp.
Referenced by DummyFree(), initialize_handler_pointers(), and is_malloc_used_v3().
tbb::atomic<do_once_state> tbb::internal::initialization_state static
Definition at line 135 of file cache_aligned_allocator.cpp.
void*(* tbb::internal::MallocHandler) (size_t size) = &DummyMalloc static
Handler for memory allocation.
Definition at line 62 of file cache_aligned_allocator.cpp.
Referenced by DummyMalloc(), initialize_handler_pointers(), and is_malloc_used_v3().
const dynamic_link_descriptor tbb::internal::MallocLinkTable[] static
Initial value:
= {
    DLD(scalable_malloc, MallocHandler),
    DLD(scalable_free, FreeHandler),
    DLD(scalable_aligned_malloc, padded_allocate_handler),
    DLD(scalable_aligned_free, padded_free_handler),
}
Table describing how to link the handlers.
Definition at line 86 of file cache_aligned_allocator.cpp.
const size_t tbb::internal::MByte = 1024*1024
Definition at line 44 of file tbb_misc.h.
Referenced by tbb::internal::generic_scheduler::init_stack_info().
size_t tbb::internal::NFS_LineSize = 128 static
Definition at line 169 of file cache_aligned_allocator.cpp.
Referenced by NFS_Allocate(), and NFS_GetLineSize().
const isolation_tag tbb::internal::no_isolation = 0
Definition at line 129 of file task.h.
Referenced by tbb::internal::generic_scheduler::allocate_task(), tbb::internal::generic_scheduler::get_task(), tbb::internal::mail_outbox::internal_pop(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::internal::arena::process(), tbb::internal::custom_scheduler< SchedulerTraits >::receive_or_steal_task(), tbb::internal::generic_scheduler::steal_task_from(), and tbb::internal::custom_scheduler< SchedulerTraits >::tally_completion_of_predecessor().
const uintptr_t tbb::internal::NUM_NOTIFY_TYPES = 4
Definition at line 131 of file tbb_profiling.h.
const intptr_t tbb::internal::num_priority_levels = 1 static
Definition at line 133 of file scheduler_common.h.
Referenced by tbb::internal::generic_scheduler::enqueue(), tbb::internal::arena::has_enqueued_tasks(), tbb::internal::custom_scheduler< SchedulerTraits >::local_wait_for_all(), tbb::internal::arena::on_thread_leaving(), tbb::internal::arena::restore_priority_if_need(), Scheduler_OneTimeInitialization(), and tbb::internal::market::try_destroy_arena().
const population_t tbb::internal::one = 1
Definition at line 51 of file task_stream.h.
Referenced by tbb::internal::queue_and_mutex< T, mutex_t >::~queue_and_mutex().
void*(* tbb::internal::padded_allocate_handler) (size_t bytes, size_t alignment) = &dummy_padded_allocate static
Handler for padded memory allocation.
Definition at line 80 of file cache_aligned_allocator.cpp.
Referenced by dummy_padded_allocate(), and initialize_handler_pointers().
void(* tbb::internal::padded_free_handler) (void *p) = &dummy_padded_free static
Handler for padded memory deallocation.
Definition at line 83 of file cache_aligned_allocator.cpp.
Referenced by dummy_padded_free(), and initialize_handler_pointers().
bool tbb::internal::PrintVersionFlag = false static
Definition at line 195 of file tbb_misc.cpp.
const int tbb::internal::priority_critical = priority_stride_v4 * 3 + priority_stride_v4 / 3 * 2 static
Definition at line 291 of file task.h.
Referenced by tbb::interface7::task_arena::enqueue(), tbb::task::enqueue(), and tbb::internal::arena::enqueue_task().
const int tbb::internal::priority_stride_v4 = INT_MAX / 4 static
Definition at line 288 of file task.h.
stack_size_control tbb::internal::stack_size_ctl static
Definition at line 488 of file tbb_main.cpp.
void* tbb::internal::static_invalid_page static
Definition at line 160 of file concurrent_queue.cpp.
Referenced by tbb::internal::micro_queue::make_invalid().
const size_t tbb::internal::task_alignment = 32
Alignment for a task object.
Definition at line 159 of file scheduler_common.h.
const size_t tbb::internal::task_prefix_reservation_size = ((sizeof(internal::task_prefix)-1)/task_alignment+1)*task_alignment
Number of bytes reserved for a task prefix.
If not exactly sizeof(task_prefix), the extra bytes precede the task_prefix.
Definition at line 163 of file scheduler_common.h.
Referenced by tbb::internal::generic_scheduler::allocate_task(), tbb::internal::generic_scheduler::deallocate_task(), and tbb::internal::mail_outbox::drain().
const size_t tbb::internal::ThreadStackSize = (sizeof(uintptr_t) <= 4 ? 2 : 4)*MByte
Definition at line 52 of file tbb_misc.h.
Referenced by tbb::internal::stack_size_control::default_value().
void* const tbb::internal::vector_allocation_error_flag = reinterpret_cast<void*>(size_t(63)) static
Bad allocation marker.
Definition at line 74 of file concurrent_vector.h.
Referenced by tbb::internal::concurrent_vector_base_v3::segment_t::store().
const char tbb::internal::VersionString[] = "\0" TBB_VERSION_STRINGS static
The leading "\0" is here so that applying "strings" to the binary delivers a clean result.
Definition at line 193 of file tbb_misc.cpp.
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.