Intel(R) Threading Building Blocks Doxygen Documentation: tbb::flow::internal Namespace Reference
tbb::flow::internal Namespace Reference
Typedefs
typedef unsigned int node_priority_t
Variables
static tbb::task *const SUCCESSFULLY_ENQUEUED = (task *)-1
static const node_priority_t no_priority = node_priority_t(0)
Typedef Documentation
typedef unsigned int tbb::flow::internal::node_priority_t
Definition at line 57 of file _flow_graph_impl.h.
Variable Documentation
const node_priority_t tbb::flow::internal::no_priority = node_priority_t(0) static
Definition at line 58 of file _flow_graph_impl.h.
Referenced by tbb::flow::interface10::internal::priority_task_selector::execute(), tbb::flow::interface10::internal::spawn_in_graph_arena(), and tbb::flow::interface10a::write_once_node< T >::try_put_task().
tbb::task* const tbb::flow::internal::SUCCESSFULLY_ENQUEUED = (task *)-1 static
Definition at line 55 of file _flow_graph_impl.h.
Referenced by internal::function_input< Input, Output, Policy, A >::apply_body_impl_bypass(), internal::multifunction_input< Input, OutputPortSet, Policy, A >::apply_body_impl_bypass(), check_task_and_spawn(), internal::emit_element< 1 >::emit_this(), tbb::flow::interface10::internal::priority_task_selector::execute(), tbb::flow::interface10::graph::run_and_put_task< Receiver, Body >::execute(), internal::forward_task_bypass< NodeType >::execute(), internal::apply_body_task_bypass< NodeType, Input >::execute(), internal::source_task_bypass< NodeType >::execute(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::forward_task(), internal::queueing_port< T >::handle_operations(), internal::function_input_base< Input, Policy, A, multifunction_input< Input, OutputPortSet, Policy, A > >::internal_try_put_task(), internal::async_storage< T >::subscribe(), internal::multifunction_output< Output >::try_put(), internal::queueing_port< T >::try_put_task(), internal::key_matching_port< TraitsType >::try_put_task(), tbb::flow::interface10::broadcast_node< T >::try_put_task(), and tbb::flow::interface10a::overwrite_node< T >::try_put_task_impl().
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.