Intel(R) Threading Building Blocks Doxygen Documentation: tbb::serial::interface9 Namespace Reference
tbb::serial::interface9 Namespace Reference
Classes
class start_for
Functions
template<typename Range , typename Body >
void parallel_for (const Range &range, const Body &body)
Parallel iteration over range with default partitioner.
template<typename Range , typename Body >
void parallel_for (const Range &range, const Body &body, const simple_partitioner &partitioner)
Parallel iteration over range with simple partitioner.
template<typename Range , typename Body >
void parallel_for (const Range &range, const Body &body, const auto_partitioner &partitioner)
Parallel iteration over range with auto_partitioner.
template<typename Range , typename Body >
void parallel_for (const Range &range, const Body &body, const static_partitioner &partitioner)
Parallel iteration over range with static_partitioner.
template<typename Range , typename Body >
void parallel_for (const Range &range, const Body &body, affinity_partitioner &partitioner)
Parallel iteration over range with affinity_partitioner.
template<typename Index , typename Function , typename Partitioner >
void parallel_for_impl (Index first, Index last, Index step, const Function &f, Partitioner &)
Implementation of parallel iteration over stepped range of integers with explicit step and partitioner (ignored)
template<typename Index , typename Function >
void parallel_for (Index first, Index last, Index step, const Function &f)
Parallel iteration over a range of integers with explicit step and default partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, Index step, const Function &f, const simple_partitioner &p)
Parallel iteration over a range of integers with explicit step and simple partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, Index step, const Function &f, const auto_partitioner &p)
Parallel iteration over a range of integers with explicit step and auto partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, Index step, const Function &f, const static_partitioner &p)
Parallel iteration over a range of integers with explicit step and static partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, Index step, const Function &f, affinity_partitioner &p)
Parallel iteration over a range of integers with explicit step and affinity partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, const Function &f)
Parallel iteration over a range of integers with default step and default partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, const Function &f, const simple_partitioner &p)
Parallel iteration over a range of integers with default step and simple partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, const Function &f, const auto_partitioner &p)
Parallel iteration over a range of integers with default step and auto partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, const Function &f, const static_partitioner &p)
Parallel iteration over a range of integers with default step and static partitioner.
template<typename Index , typename Function >
void parallel_for (Index first, Index last, const Function &f, affinity_partitioner &p)
Parallel iteration over a range of integers with default step and affinity_partitioner.
Function Documentation
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, Index step, const Function & f)
Parallel iteration over a range of integers with explicit step and default partitioner.
Definition at line 157 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), and tbb::internal::last().
{
     parallel_for_impl<Index,Function,const auto_partitioner>(first, last, step, f, auto_partitioner());
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, Index step, const Function & f, const simple_partitioner & p)
Parallel iteration over a range of integers with explicit step and simple partitioner.
Definition at line 162 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), tbb::internal::last(), and p.
{
     parallel_for_impl<Index,Function,const simple_partitioner>(first, last, step, f, p);
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, Index step, const Function & f, const auto_partitioner & p)
Parallel iteration over a range of integers with explicit step and auto partitioner.
Definition at line 167 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), tbb::internal::last(), and p.
{
     parallel_for_impl<Index,Function,const auto_partitioner>(first, last, step, f, p);
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, Index step, const Function & f, const static_partitioner & p)
Parallel iteration over a range of integers with explicit step and static partitioner.
Definition at line 172 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), tbb::internal::last(), and p.
{
     parallel_for_impl<Index,Function,const static_partitioner>(first, last, step, f, p);
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, Index step, const Function & f, affinity_partitioner & p)
Parallel iteration over a range of integers with explicit step and affinity partitioner.
Definition at line 177 of file serial/tbb/parallel_for.h.
References parallel_for_impl().
{
     parallel_for_impl(first, last, step, f, p);
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, const Function & f)
Parallel iteration over a range of integers with default step and default partitioner.
Definition at line 183 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), and tbb::internal::last().
{
     parallel_for_impl<Index,Function,const auto_partitioner>(first, last, static_cast<Index>(1), f, auto_partitioner());
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, const Function & f, const simple_partitioner & p)
Parallel iteration over a range of integers with default step and simple partitioner.
Definition at line 188 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), and tbb::internal::last().
{
     parallel_for_impl<Index,Function,const simple_partitioner>(first, last, static_cast<Index>(1), f, p);
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, const Function & f, const auto_partitioner & p)
Parallel iteration over a range of integers with default step and auto partitioner.
Definition at line 193 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), and tbb::internal::last().
{
     parallel_for_impl<Index,Function,const auto_partitioner>(first, last, static_cast<Index>(1), f, p);
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, const Function & f, const static_partitioner & p)
Parallel iteration over a range of integers with default step and static partitioner.
Definition at line 198 of file serial/tbb/parallel_for.h.
References tbb::internal::first(), and tbb::internal::last().
{
     parallel_for_impl<Index,Function,const static_partitioner>(first, last, static_cast<Index>(1), f, p);
 }
template<typename Index , typename Function > void tbb::serial::interface9::parallel_for (Index first, Index last, const Function & f, affinity_partitioner & p)
Parallel iteration over a range of integers with default step and affinity_partitioner.
Definition at line 203 of file serial/tbb/parallel_for.h.
References parallel_for(), and parallel_for_impl().
{
     parallel_for_impl(first, last, static_cast<Index>(1), f, p);
 }
template<typename Index , typename Function , typename Partitioner > void tbb::serial::interface9::parallel_for_impl (Index first, Index last, Index step, const Function & f, Partitioner &)
Implementation of parallel iteration over stepped range of integers with explicit step and partitioner (ignored)
Definition at line 135 of file serial/tbb/parallel_for.h.
References tbb::internal::last().
Referenced by parallel_for().
{
     if (step <= 0 ) {
 #if TBB_USE_EXCEPTIONS
         throw std::invalid_argument( "nonpositive_step" );
 #else
         std::cerr << "nonpositive step in a call to parallel_for" << std::endl;
         std::abort();
 #endif
     } else if (last > first) {
         // Above "else" avoids "potential divide by zero" warning on some platforms
         ANNOTATE_SITE_BEGIN( tbb_parallel_for );
         for( Index i = first; i < last; i = i + step ) {
             ANNOTATE_TASK_BEGIN( tbb_parallel_for_iteration );
             { f( i ); }
             ANNOTATE_TASK_END( tbb_parallel_for_iteration );
         }
         ANNOTATE_SITE_END( tbb_parallel_for );
     }
 }
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.