Intel(R) Threading Building Blocks Doxygen Documentation: tbb::interface5 Namespace Reference
tbb::interface5 Namespace Reference
Namespaces
internal
Classes
class concurrent_hash_map
Unordered map from Key to T.
class concurrent_priority_queue
Concurrent priority queue.
class concurrent_unordered_map
class concurrent_unordered_map_traits
class concurrent_unordered_multimap
class concurrent_unordered_multiset
class concurrent_unordered_set
class concurrent_unordered_set_traits
class reader_writer_lock
Writer-preference reader-writer lock with local-only spinning on readers.
Functions
template<typename T >
size_t tbb_hasher (const T &t)
Hasher functions.
template<typename P >
size_t tbb_hasher (P *ptr)
template<typename E , typename S , typename A >
size_t tbb_hasher (const std::basic_string< E, S, A > &s)
template<typename F , typename S >
size_t tbb_hasher (const std::pair< F, S > &p)
uintptr_t fetch_and_or (atomic< uintptr_t > &operand, uintptr_t value)
uintptr_t fetch_and_and (atomic< uintptr_t > &operand, uintptr_t value)
template<typename T , typename U >
void spin_wait_while_geq (const volatile T &location, U value)
Spin WHILE the value at the location is greater than or equal to a given value.
template<typename T , typename U >
void spin_wait_until_and (const volatile T &location, U value)
Spin UNTIL (location & value) is true.
Variables
const uintptr_t WFLAG1 = 0x1
const uintptr_t WFLAG2 = 0x2
const uintptr_t RFLAG = 0x4
const uintptr_t RC_INCR = 0x8
Function Documentation
uintptr_t tbb::interface5::fetch_and_and (atomic< uintptr_t > & operand, uintptr_t value) inline
Definition at line 50 of file reader_writer_lock.cpp.
References tbb::internal::atomic_impl< T >::compare_and_swap(), and tbb::internal::atomic_backoff::pause().
Referenced by tbb::interface5::reader_writer_lock::end_write().
{
     for (tbb::internal::atomic_backoff b;;b.pause()) {
         uintptr_t old = operand;
         uintptr_t result = operand.compare_and_swap(old&value, old);
         if (result==old) return result;
     }
 }
uintptr_t tbb::interface5::fetch_and_or (atomic< uintptr_t > & operand, uintptr_t value) inline
Definition at line 41 of file reader_writer_lock.cpp.
References tbb::internal::atomic_impl< T >::compare_and_swap(), and tbb::internal::atomic_backoff::pause().
Referenced by tbb::interface5::reader_writer_lock::set_next_writer(), and tbb::interface5::reader_writer_lock::start_read().
{
     for (tbb::internal::atomic_backoff b;;b.pause()) {
         uintptr_t old = operand;
         uintptr_t result = operand.compare_and_swap(old|value, old);
         if (result==old) return result;
     }
 }
template<typename T , typename U > void tbb::interface5::spin_wait_until_and (const volatile T & location, U value)
Spin UNTIL (location & value) is true.
T and U should be comparable types.
Definition at line 69 of file reader_writer_lock.cpp.
References tbb::internal::atomic_backoff::pause().
Referenced by tbb::interface5::reader_writer_lock::set_next_writer().
{
     tbb::internal::atomic_backoff backoff;
     while( !(location & value) ) backoff.pause();
 }
template<typename T , typename U > void tbb::interface5::spin_wait_while_geq (const volatile T & location, U value)
Spin WHILE the value at the location is greater than or equal to a given value.
T and U should be comparable types.
Definition at line 61 of file reader_writer_lock.cpp.
References tbb::internal::atomic_backoff::pause().
Referenced by tbb::interface5::reader_writer_lock::set_next_writer().
{
     tbb::internal::atomic_backoff backoff;
     while( location>=value ) backoff.pause();
 }
template<typename T > size_t tbb::interface5::tbb_hasher (const T & t) inline
Hasher functions.
Definition at line 65 of file _tbb_hash_compare_impl.h.
References tbb::interface5::internal::hash_multiplier.
Referenced by tbb::tbb_hash_compare< Key >::hash(), tbb::tbb_hash< Key >::operator()(), and tbb_hasher().
{
     return static_cast<size_t>( t ) * internal::hash_multiplier;
 }
template<typename P > size_t tbb::interface5::tbb_hasher (P * ptr) inline
Definition at line 69 of file _tbb_hash_compare_impl.h.
References h.
{
     size_t const h = reinterpret_cast<size_t>( ptr );
     return (h >> 3) ^ h;
 }
template<typename E , typename S , typename A > size_t tbb::interface5::tbb_hasher (const std::basic_string< E, S, A > & s) inline
Definition at line 74 of file _tbb_hash_compare_impl.h.
References h, and tbb::interface5::internal::hash_multiplier.
{
     size_t h = 0;
     for( const E* c = s.c_str(); *c; ++c )
         h = static_cast<size_t>(*c) ^ (h * internal::hash_multiplier);
     return h;
 }
template<typename F , typename S > size_t tbb::interface5::tbb_hasher (const std::pair< F, S > & p) inline
Definition at line 81 of file _tbb_hash_compare_impl.h.
References tbb_hasher().
{
     return tbb_hasher(p.first) ^ tbb_hasher(p.second);
 }
Variable Documentation
const uintptr_t tbb::interface5::RC_INCR = 0x8
Definition at line 37 of file reader_writer_lock.cpp.
Referenced by tbb::interface5::reader_writer_lock::end_read(), tbb::interface5::reader_writer_lock::start_read(), and tbb::interface5::reader_writer_lock::try_lock_read().
const uintptr_t tbb::interface5::RFLAG = 0x4
Definition at line 36 of file reader_writer_lock.cpp.
Referenced by tbb::interface5::reader_writer_lock::set_next_writer(), and tbb::interface5::reader_writer_lock::unblock_readers().
const uintptr_t tbb::interface5::WFLAG1 = 0x1
Definition at line 34 of file reader_writer_lock.cpp.
const uintptr_t tbb::interface5::WFLAG2 = 0x2
Definition at line 35 of file reader_writer_lock.cpp.
Referenced by tbb::interface5::reader_writer_lock::try_lock_read().
Copyright © 2005-2019 Intel Corporation. All Rights Reserved.
Intel, Pentium, Intel Xeon, Itanium, Intel XScale and VTune are registered trademarks or trademarks of Intel Corporation or its subsidiaries in the United States and other countries.
* Other names and brands may be claimed as the property of others.